### ISSUE TITLE
Issue in generated java code with brace

### ISSUE THREAD

**Issue by Hotinly** [firasdib/Regex101#1002]
api.get.ess=http://www.aaa00.com/query?type={type}&postid={postid}

/{(.+?)}/g

**Generated java code**
`final String regex = "{(.+?)}";`        //ERROR
&nbsp;&nbsp;&nbsp;&nbsp; _`java.util.regex.PatternSyntaxException: Illegal repetition {(.+?)}`_
`final String regex = "\\{(.+?)\\}";`  //OK

**Comment by Zarthus** [comment]
the codegen doesn't fix your regex if your regex is not compatible in the first place.
