### ISSUE TITLE
Mark javascript's "s" flag as draft

### ISSUE THREAD

**Issue by kakty3** [firasdib/Regex101#1004]
Javascript's `s` flag appears only in [ECMAScript® 2019 Language Specification](https://tc39.github.io/ecma262/#sec-notation). So expression
```js
const regex = /^.*?/s;
```
works in Safari 11.1, but returns `SyntaxError: invalid regular expression flag s` in Firefox Nightly 61.0a1. 

I think it will be convenient to somehow mark `s` flag as draft flag in UI.

**Comment by firasdib** [comment]
I could do that. I currently feature detect for it, so it should only show up in browsers that support it.

If you save a regex and load it in an older browser, you'll have this error though.

**Comment by TWiStErRob** [comment]
I think they key is to communicate to the users that this is not a fully supported feature, use with caution if you paste it in production code.

**Comment by firasdib** [comment]
Added to explanation area. Will be available in next release (tonight).

**Comment by geri777** [comment]
I agree, this is a bad solution. The s-flag should be removed or clearly be marked as unsupported by the majority of browsers.

**Comment by danmarshall** [comment]
Ouch - I just got the `SyntaxError: Invalid regular expression flags` in Node.js. Ended up searching to find this issue, it wasn't obvious in the UI.
Thanks so much for Regex101, it is fantastic 🥇
