### ISSUE TITLE
Clicking on a match scrolls and "pops" the matched value in the test string

### ISSUE THREAD

**Issue by hobbes3** [firasdib/Regex101#1005]
I often work with test strings that are really looooong (think sometimes over 1 MB of text). When I write a regex and I see a match, I have to carefully scroll manually until I see some highlighted value in the looooong text. Sometimes if I scroll too fast then I miss it.

It would be _awesome_, if I can simply stay on the "Match Information" side and simply click on the match to see that match value in the test string. Ideally I want to see an animation scroll to the match, then the match to "pop" by doing a little enlarged bounce or something (or possible make it change highlight color briefly).

**Comment by hobbes3** [comment]
Is this a bad enhancement request, @firasdib?

**Comment by firasdib** [comment]
No, this is a great enhancement. 

Im just very pressed on time atm. I will try to look at this soon!

Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Ouims** [comment]
Shit, this is the best feature suggestion i have seen for the website, I have been in that case so many times.

**Comment by firasdib** [comment]
This is now implemented

**Comment by TWiStErRob** [comment]
Nice! Not as fluffy as OP wanted, but I think the important thing is the functionality.
Wow, it also highlights groups, not just full matches!

**Comment by firasdib** [comment]
@TWiStErRob I see no point in removing the highlight until the user interacts with the area or they edit their regex (or whatever that might update it). Might be useful to keep it highlighted, and I see no immediate issue with it being so.

Secondly, the animation, is probably just going to be confusing, especially if you have disabled line wrapping and it needs to animate both X and Y axis.
