### ISSUE TITLE
Feature request: multiple test strings

### ISSUE THREAD

**Issue by lorenmh** [firasdib/Regex101#1009]
Right now it looks like there is only one string to test your regex against with highlighting.

It would be nice if we could test our regex against a set of strings and see the matching / highlighting for each one.

For example, if I have some regex of `^foo(bar)?$`, I may want to see what's captured for test strings `foo`, `foob`, `foobar`. The unit tests will only tell me if there is a match, it will not show me the highlighting of what was matched, and it will not show me the matched string.

In your app too do this I simply remove the `^` and `$` from the regex and then I use the test string of:

```
foo
foob
foobar
```

**Comment by working-name** [comment]
Hi @lorenmh, is [**this**](https://regex101.com/r/k3U8O4/1/) what you have in mind? 

`^` and `$` have a purpose. Additionally, when you first load regex101.com in your browser there are two flags that are turned on by default `/gm`, which means:

`^` - match the beginning of a line (with `/m`) or of the whole input string (no `/m`)
`$` - match the end of a line (with `/m`) or of the whole input string (no `/m`)
`/g` - global flag, which instructs the regex engine to not stop after returning the first match but keep going until the very last valid match
`/m` - multiline flag, which instructs the regex engine to treat `^` and `$` as described above.

Therefore you want `^` and `$` to require the beginning and end of a single line, and in the test string you simply separate each test case by a newline. If you discard `^` and `$`, regex will attempt to match anywhere in the line/string, [**like so**](https://regex101.com/r/k3U8O4/2).

It is my understanding that line 2 should not return any valid matches given your regex's requirement that `bar` either be present in whole or not at all.

**Comment by lorenmh** [comment]
Hi @working-name , thank you for your response, exactly what I was looking for
