### ISSUE TITLE
Wrong help text for named capturing groups

### ISSUE THREAD

**Issue by grongor** [firasdib/Regex101#1010]
Acording to the help texts:
![selection_003](https://user-images.githubusercontent.com/972493/41090809-6b7df398-6a45-11e8-8756-7fcb9812692c.png)
, the `\g'delim'` and `\g<delim>` should match previously matched group, but instead they recurse the pattern:
![selection_001](https://user-images.githubusercontent.com/972493/41090770-566f3db8-6a45-11e8-9094-f609570be771.png)

**Comment by TWiStErRob** [comment]
So the difference is "recurse" will re-match and "match -previously named" will exactly match what was matched before?

**Comment by grongor** [comment]
Yeah, if I understand you correctly.

Check these examples:
https://regex101.com/r/n6ykQM/2
https://regex101.com/r/n6ykQM/3

**Comment by firasdib** [comment]
From the PCRE documentation:

>    Absolute and relative back references
> 
>        The sequence \g followed by an unsigned or a negative  number,  option-
>        ally  enclosed  in braces, is an absolute or relative back reference. A
>        named back reference can be coded as \g{name}. Back references are dis-
>        cussed later, following the discussion of parenthesized subpatterns.
> 
>    Absolute and relative subroutine calls
> 
>        For  compatibility with Oniguruma, the non-Perl syntax \g followed by a
>        name or a number enclosed either in angle brackets or single quotes, is
>        an  alternative  syntax for referencing a subpattern as a "subroutine".
>        Details are discussed later.   Note  that  \g{...}  (Perl  syntax)  and
>        \g<...>  (Oniguruma  syntax)  are  not synonymous. The former is a back
>        reference; the latter is a subroutine call.

I think the error is in the quickref, not the tooltip.

**Comment by working-name** [comment]
My mistake, I'll review all the `\g` constructs in the quickref and update you, Firas.

Thank you @grongor

**Comment by firasdib** [comment]
@working-name status?

**Comment by working-name** [comment]
@firasdib addressed, posted in `#developers`.

**Comment by firasdib** [comment]
Thanks @working-name - ive pushed it live.
