### ISSUE TITLE
The explanation text disappears bit by bit when you scroll

### ISSUE THREAD

**Issue by Tofandel** [firasdib/Regex101#1011]
When you scroll the regex explanation on the main page, the text disappears by how much you've scrolled

See this screen : 
![image](https://user-images.githubusercontent.com/6115458/41093661-380feabe-6a4c-11e8-9d57-0894dcb121fb.png)

Initially it is entirely visible but if I scroll to 70% then only 30% of the text will be visible.
If I scroll entirely then it disappears completely

I'm using the latest version of chrome and I noticed this issue only today (it wasn't happening last time I used the app which may be 1-2 weeks ago)

**Comment by Doqnach** [comment]
Do you have a link to a regex that showcases this issue?

**Comment by firasdib** [comment]
This looks very weird. Which OS?

**Comment by working-name** [comment]
I can confirm this happens on `macOS 10.13.4`, `Chrome 67.0.3396.79 64bit`. It's a rendering issue as far as I can tell. Any action that triggers a refresh of that particular DIV container will return everything to normal. The "covering" is not a real HTML element that I can find in the DOM.

[![Screencast of the bug in action](https://bugout.regex.ga/scrollingbug.gif)](https://bugout.regex.ga/scrollingbug.mp4)<br/>([download screencast](https://bugout.regex.ga/scrollingbug.mp4))

- I have turned off hardware acceleration and there's no change in behavior.
- it does not seem to happen anywhere else in the UI where scrolling is possible

Hope this helps.

**Comment by firasdib** [comment]
Unable to reproduce on

```
macOS Version 10.13.4 (17E202)
Chrome Version 67.0.3396.79 (Official Build) (64-bit)
```

**Comment by Doqnach** [comment]
could not reproduce on MacOS with Opera (OPR/53.0.2907.68 which is Chrome/66.0.3359.170)

**Comment by Tofandel** [comment]
I'm on Microsoft Windows 7 Professional
Chrome Version 67.0.3396.79 (Official Build) (32-bit)

This indeed seems to be a rendering issue, if I force Chrome to rerender the scrollbox (by setting a dummy css rule in one of the child html div for example) then it appears correctly until I scroll again.

Is there maybe a special scrolling mechanism for this element ? (as @working-name mentioned it's not happening anywhere else)

**Comment by firasdib** [comment]
There is no special logic @Tofandel.

It could be that there is just too much in there and it tries to optimize it.

**Comment by Tofandel** [comment]
Okay I found the issue

I commented those 2 rules and the issue disappeared 

.R5C_f {
    overflow-y: hidden;
    /* -webkit-transform: translateZ(0); */
    /* transform: translateZ(0); */
}

**Comment by firasdib** [comment]
Good find. I will look at this later. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by firasdib** [comment]
Try again @Tofandel. I removed that rule.

**Comment by Tofandel** [comment]
Working perfectly :+1:
