### ISSUE TITLE
[Request] API docs collection

### ISSUE THREAD

**Issue by OrangutanGaming** [firasdib/Regex101#1012]
Is it possible to clone the docs to something like swagger so that you can have a JSON with all the docs? It could allow us to make Postman collections to make experimenting with the API easier.

**Comment by Zarthus** [comment]
I don't see why not.

It might make sense as a Pull Request in this repository too.

Everything is documented here:

https://github.com/firasdib/Regex101/wiki/API

**Comment by firasdib** [comment]
I think the API docs are sufficient. I don't use swagger.
