### ISSUE TITLE
/^\d{5}$/ is not working in my chrome browser

### ISSUE THREAD

**Issue by NeetishRaj** [firasdib/Regex101#1014]
it does not matches for test string 
12345

problem seems to be with $ 
I am using Chrome  Version 67.0.3396.62 (Official Build) (64-bit)

**Comment by firasdib** [comment]
Please post a permalink with your data.

**Comment by NeetishRaj** [comment]
heres a screenshot for the bug, 
For javascript regex /^\d{5}$/ does not seem to work correctly
![screenshot from 2018-06-11 13-49-55](https://user-images.githubusercontent.com/26858235/41220337-b1bcfd7c-6d7e-11e8-907d-e625ea64355d.png)

**Comment by firasdib** [comment]
You likely have a whitespace at the end. See here: https://regex101.com/r/D2CYqn/1

**Comment by NeetishRaj** [comment]
Yes it works right now, thank you for he tip
