### ISSUE TITLE
Will support ES2018 (ES9) in future?

### ISSUE THREAD

**Issue by grass0916** [firasdib/Regex101#1017]
## Features in ES9

* Lookbehind
* Named capture groups
* Flag - `s` (dotall)

## Refs

* [What’s New in ES2018](https://www.sitepoint.com/es2018-whats-new/)
* [ES2018: RegExp named capture groups](http://2ality.com/2017/05/regexp-named-capture-groups.html)

Thanks :)

**Comment by Zarthus** [comment]
default vague answer you could expect from a project written during free time: Probably, but not any time soon.

**Comment by firasdib** [comment]
Sorry, missed this.

This is already supported - I use feature detection to turn it off and on: https://regex101.com/r/kdHQ8V/1/

This does mean a user with a modern browser (like me) can create a regex (like the one above) and share it with someone with an older browser, on which it will not work (which I think is fine).

<img width="1678" alt="screen shot 2018-06-29 at 19 47 31" src="https://user-images.githubusercontent.com/1335165/42106712-506f2242-7bd5-11e8-8049-60e877dcd991.png">
