### ISSUE TITLE
Add support for string literals in Text Input

### ISSUE THREAD

**Issue by ashleybartlett** [firasdib/Regex101#1019]
I spent far too long trying to understand why my regex matched in Regex101, and not in Python. It turns out that I was using the string literal for the test string, and not the interpreted string output. 

For example, the regex in regex101 `(\w+ ?)+\\n(\w+ ?)+\\n(\w+ ?)+\.`, would match the literal string: `my simple string\nwith multiple\nlines.` 

But the above fails when doing it in Python, so doing a `re.match(r'(\w+ ?)+\\n(\w+ ?)+\\n(\w+ ?)+\.', 'my simple string\nwith multiple\nlines.')` returns None

It would be nice to have support for either some kind of detecting on the text source, or a tick box with an explanation.

**Comment by Doqnach** [comment]
How do you mean 'string literals'? Because the "Text input" already takes the text as-is? It does not resolve the \n in any way. Or do you mean you DO want the \n to be resolved in some way, to be treated as a new line?

**Comment by ashleybartlett** [comment]
What I would like is a way to toggle, or convert, the \n and other codes to be text. Or provide some hinting if they exist, that they aren't being treated as new lines.

**Comment by ashleybartlett** [comment]
It caught me out again, because I was copying from the debugger, not from a string output. And so when I should have thought to do multiline regex, I of course didn't. And tested for literals.

**Comment by firasdib** [comment]
I'm not exactly sure what you're asking here?

**Comment by ashleybartlett** [comment]
I'm asking for there to be some detection in the test string, for new line or other escaped literals, and give an option to convert them to actual values or interpret them appropriately for the particular language. 
Or maybe even just hint to the user that it will be interpreted exactly as presented.

**Comment by firasdib** [comment]
I don't think thats a feature worth implementing to be honest. Many cases you want to match things literally with regex. I think this is better suited as a search and replace on the site or in your editor of choice.
