### ISSUE TITLE
js: /($)/gm returns different index 

### ISSUE THREAD

**Issue by zemiak1** [firasdib/Regex101#1020]
```js
var reg = /($)/gm;
var str = "\n\n\n\n";
for(let a, i=0; i<4; i++) {
     a = reg.exec(str);
     console.log([ a[0], a.index, reg.lastIndex]);
}
/*
output:
(3) ["", 0, 0]
(3) ["", 0, 0]
(3) ["", 0, 0]
(3) ["", 0, 0]
*/
```
-----------------

regex101 return different index and lastIndex of match:

Match 1
Full match	0-0	``
Group 1.	n/a	``
Match 2
Full match	1-1	``
Group 1.	n/a	``
Match 3
Full match	2-2	``
Group 1.	n/a	``
Match 4
Full match	3-3	``
Group 1.	n/a	``

tested on Avast Chromium (66.1.564.182), FireFox (60.0.2, 32-bit), + some online compilers

**Comment by firasdib** [comment]
Please see the generated code here:  https://regex101.com/r/O7o6DR/1/codegen?language=javascript

This is intentional.
