### ISSUE TITLE
Non Latin characters match highlight is missed. 

### ISSUE THREAD

**Issue by saidbakr** [firasdib/Regex101#1022]
For non Latin characters such as Arabic, the highlight of the matched string in the **Test String** panel is not rendered. According to [this regex](https://regex101.com/r/n2mXWR/1):

```
/\w+/giu
// For Arabic string حال
```
The string `حال` should be totally highlighted as the result displayed in **Match Information** panel, but it does not.

The browser used is Chrome `67.0.3396.99` on Ubuntu Linux 64 Bit. Also tested with Firefox `61.0 (64-bit)` and the same issue is found too.

**Comment by firasdib** [comment]
Dup of https://github.com/firasdib/Regex101/issues/764
