### ISSUE TITLE
[Javascript] Different testing result from V8 (Chrome console)

### ISSUE THREAD

**Issue by YunzheZJU** [firasdib/Regex101#1023]
Details
-------
* Testing string `-` with reg `(n)?-\1` shows a different result.

* `/(n)?-\1/.test('-')` turns out to be `true` in Chrome devtool while does not pass [regex101](https://regex101.com/r/GqnJvQ/2).

* It may be caused be different explanation to `\1` when the 1st group does not even exist.

Environment
--------------
Chrome 67.0

**Comment by firasdib** [comment]
Select the JS flavor: https://regex101.com/r/GqnJvQ/3
