### ISSUE TITLE
Support for accented characters 

### ISSUE THREAD

**Issue by Chetan21** [firasdib/Regex101#1024]
## Feature
Regex patterns provided as input don't detect accented characters. 

Example;

Simple regex pattern to check whether first character is an alphabet or accented charater:
^[a-zA-Z\\u00C0-\\u017F]{1} 

The tool treats, \\u as characters instead of the unicode format.

**Comment by TWiStErRob** [comment]
Probably a flavor mismatch: what you write is not what's executed; working examples (same regex):
Javascript: https://regex101.com/r/Fp21kP/1
PCRE: https://regex101.com/r/Fp21kP/2/

Chose your flavor and then go to lower right corner for Quick Reference and check meta sequences / hex character.
