### ISSUE TITLE
Generated code isn't working correct on php server

### ISSUE THREAD

**Issue by AbdulHaye** [firasdib/Regex101#1025]
Hi community,
Your web helped me lot. But regex output on ins't valid by generated php code.
![image](https://user-images.githubusercontent.com/9510519/43387354-a4446548-93ff-11e8-96a0-36db9a51a611.png)
This is regex is working on web is perfect. And when I generated code for PHP then it returns null.
![image](https://user-images.githubusercontent.com/9510519/43387425-d38e7c26-93ff-11e8-8814-5ed9d9039378.png)
What thing I'm doing wrong?

**Comment by firasdib** [comment]
Please post a permalink

**Comment by AbdulHaye** [comment]
https://regex101.com/r/nn9ZXV/2/

**Comment by firasdib** [comment]
Seems to work here: https://repl.it/repls/DarkorangeElatedMetadata

**Comment by AbdulHaye** [comment]
Yes. You're right. It seems there might be some issue in my environment or I need to enable or disable something in my php.ini file.

Thanks,
You're Great (Y)

**Comment by firasdib** [comment]
You're most welcome
