### ISSUE TITLE
Quick Reference for javascript flavor misses lookbehind (?<...) group construct

### ISSUE THREAD

**Issue by adambadura** [firasdib/Regex101#1027]

**Comment by firasdib** [comment]
Thank you. Fixed.

**Comment by adambadura** [comment]
Is this really fixed?

I see there is now following additional entry:
```
(?(?<=...)yes|no)
```
and yet I had working (Google Chrom) use of
```
(?<!...)
```
negative lookbehind case.

It doesn't seem to be covered. I would expect same with (?<=...).

**Comment by firasdib** [comment]
Sorry, *now* its fixed :-)
