### ISSUE TITLE
Quick Positioning

### ISSUE THREAD

**Issue by yueraiyu** [firasdib/Regex101#1029]
## Feature
while insert a large amount of text,the server response a large amount of result,but it's very hard to find it in the text.I think can show it in another area.

**Comment by firasdib** [comment]
There's a window called "Match Information" on the right hand side, where you can see a detailed view of everything.

You can change the language to Chinese in the settings.

**Comment by yueraiyu** [comment]
thanks,sometimes i insert a lot text,but has one or less matched.then i want to see the detail,it hard to location in a window called "Test String".If i can location the text,i can change my pattern.Can you intercept a certain length of characters before and after the match information?

**Comment by firasdib** [comment]
You can click the matches in the match info window :)


Vänliga hälsningar / Best regards,

Firas Dib
