### ISSUE TITLE
Quick Reference Content Incorrect,  `(*THEN)`

### ISSUE THREAD

**Issue by hundan2020** [firasdib/Regex101#1030]
## Bug Description

`(*THEN)` control was filled with content of `(*SKIP)`

![image](https://user-images.githubusercontent.com/9510938/43672780-ae4488d4-97e7-11e8-86f2-346f4a5043e5.png)

### Reproduction steps

Follow Steps
Quick Reference > Group Constructs > (*THEN)

### Expected Outcome

Expect `(*THEN)` control example instead of `(*SKIP)`

**Comment by working-name** [comment]
Thank you @hundan2020, don't know how that escaped me. I'll handle it shortly.

**Comment by working-name** [comment]
Resolved.
