### ISSUE TITLE
The ability to use multiple RegEx on one string

### ISSUE THREAD

**Issue by lukepighetti** [firasdib/Regex101#1031]
I am testing a suite of RegEx that each have a specific function and I would like to be able to test all of them on a string simultaneously.

**Comment by Doqnach** [comment]
You can cheat this by simply using a `|` between each regex, though I understand this is not exactly the same.

**Comment by firasdib** [comment]
There is no way to do this currently I'm afraid. This is a very specific use case. May I ask why?

**Comment by TWiStErRob** [comment]
Expanding on Doqnach's tip, if you put them in parentheses you can even get color coded results (useful when there's an overlap between the regexes): https://regex101.com/r/RPndpv/1

**Comment by lukepighetti** [comment]
@firasdib Maybe I am regex wrong, but I am filtering a bunch of text from web scraping and I have multiple stages of sanitization, each one intended to solve different problems. Putting this into a single regex makes it complicated to test.

But to develop the regex I put all the scraped text in the regex101 window and start composing all my regex.

I did try the (|) route but unfortunately newlines cause errors. Is there a way to make regex101 just ignore newlines when composing regex?

**Comment by TWiStErRob** [comment]
`x` flag? https://regex101.com/r/RPndpv/2

**Comment by lukepighetti** [comment]
Awesome man, I think that's going to work for now. Would love to see multiple regex stages in the future but this seems like a great way to do it also.

**Comment by Ouims** [comment]
Using an OR statement with the pipe is far from being what you're asking for, as what has been matched so far cannot be matched by an alternation, which multiple pass of regex would, not to mention that you may very well expect the output of the previous regex to be the input of the next, meaning that an alternation is not even going to try on the input you would have in real life.

That being said, I think the real feature you're asking for is not well suited for regex101, which is meant to test a regex against one string. It's not a bad feature but GUI speaking, depending if you're replacing and if you want to chain the pattern with the output of the previous, or just apply all the patterns to the same string, it would require great thinking to accomplish that feat without making it ugly.
I also think big change in the UI is not something the author is looking for ;)

**Comment by Doqnach** [comment]
I think there are ways to do this nicely, but you do have to define what you want to support.

One would be: regex + test string + sub, where the result becomes the test-string of the next iteration. The other one being regex + test string, only supporting a full match (so no groups and no global) where the full match becomes the test string for the next iteration. UI wise it could just add fields under the current sub pane and cause vertical scrolling, for those opting in for that option (via a button or otherwise).

I think full support for groups and global would become a mess UI wise, let alone to implement.

**Comment by firasdib** [comment]
I believe this discussion is out of scope for the site.

If you think I'm wrong, feel free to write here.
