### ISSUE TITLE
Regex and python giving different results

### ISSUE THREAD

**Issue by shawon017** [firasdib/Regex101#1033]
## Question
**REGULAR EXPRESSION ->** 

`(?i)\b(https?(?::(?:\/{1,3}|[a-z0-9%])(?:www\d{0,3}[.])?|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))`

**TEST STRING ->**  

`<zone h='9190' id='204' is-scaled='1' param='Image/sharepoint-icon-2.png' type='bitmap' url='http://teamspace.slb.com/sites/SSODnA/SSODnA_Internal/Lists/ADSL%20DnA%20OperationCalendar%20Refresh%20Tracking/AllItems.aspx?InitialTabId=Ribbon%2EListItem&amp;VisibilityContext=WSSTabPersistence' w='8640' x='91018' y='11487' />`

**regex101 gives ->** 

```
Full match | 2959-3155 | `http://teamspace.slb.com/sites/SSODnA/SSODnA_Internal/Lists/ADSL%20DnA%20OperationCalendar%20Refresh%20Tracking/AllItems.aspx?InitialTabId=Ribbon%2EListItem&amp;VisibilityContext=WSSTabPersistence`
-- | -- | --
Group 1. | 2959-3155 | `http://teamspace.slb.com/sites/SSODnA/SSODnA_Internal/Lists/ADSL%20DnA%20OperationCalendar%20Refresh%20Tracking/AllItems.aspx?InitialTabId=Ribbon%2EListItem&amp;VisibilityContext=WSSTabPersistence`
```

**python gives ->** 

`[('http://teamspace.slb.com/sites/SSODnA/SSODnA_Internal/Lists/ADSL%20DnA%20OperationCalendar%20Refresh%20Tracking/AllItems.aspx?InitialTabId=Ribbon%2EListItem&amp;VisibilityContext=WSSTabPersistence', '', '', '', '')]`

Why it is giving some extra trailing commas and single quotes?. 
Any help is highly appreciated. Thank you.

**Comment by Doqnach** [comment]
Did you get the same (in your eyes wrong) output when using the python code by using the code generator on the site? That can help investigate the issue.

**Comment by firasdib** [comment]
Thats because you have multiple capturing groups all over the place. Swap them to `(?:)` and it should be fine.

**Comment by shawon017** [comment]
Anyway I solved the issue with some finditer rather than using findall in regex. Thank you
