### ISSUE TITLE
Match in App. but fail in php >5

### ISSUE THREAD

**Issue by Raf-sns** [firasdib/Regex101#1034]
Hi,
Would you test this 

```php
// pass regex tester
$_POST['mess'] = "<?php echo 'koko'; ?>" ; 

// escape html vars
$mess = htmlspecialchars($_POST['mess']);  

// pass regex tester        
if( preg_match_all('/<|>|\\^|\\$|\\*|(UNION)|(SELECT)|(delete)|(update)|(script)/mi', $mess) ){

        // return error
        $tab = array('type' => 'mess',
                              'error' => 'Error non-authorized char');
        echo json_encode($tab, JSON_FORCE_OBJECT);
        exit;
}
```
it was matched in the app. but not in a real script of PHP ...
thanks for your help

**Comment by working-name** [comment]
What's does your `$mess` contain? Or if you have a regex101.com link would you please share it?

**Comment by Raf-sns** [comment]
Hi, thanks for your interest,
finally, it's the htmlspecialchars php function who fail the regex.
i remove the htmlspecialchars test before use the regex.

the code parsed by hmlspecialchars dont' pass the regex test,
i would test the presence of the "<" char on a  textarea note i have not searched the "%" char,
on the regex beacause i want the user will able to enter it...
Conclusion, it's an error of me in the code and a lesson, not pass a string throw a function 
before test it in a regex ...
Sorry for the time passed,
Cordially,
Raf

**Comment by working-name** [comment]
Got it, no worries, glad you got it resolved!
