### ISSUE TITLE
feature_request(enhancement): embed Regex101

### ISSUE THREAD

**Issue by Kristinita** [firasdib/Regex101#1035]
### 1. Summary

It would be nice, if would be possible embed Regex101 to HTML site or blog.

### 2. Examples in other apps

Currently available embed Repls, for example, use RunKit and Repl.it.

+ [**RunKit**](https://runkit.com/docs/embed),
+ [**Repl.it**](https://repl.it/site/docs/embed).

Example:

![Sasha__Demo--RunKit&ReplItEmbed](https://i.imgur.com/kQJ0muW.png)

+ [**Code**](https://codepen.io/Kristinita/pen/qygVKe),
+ [**Result**](https://codepen.io/Kristinita/full/qygVKe/).

### 3. Argumentation

**For** users, this is convenient, because the user does not need to click on the links, and user can test regular expressions on the same site where they were seen.

**For** Regex101 developers this is convenient, because users can find out which Regex101 is good service by visiting sites without accessing regex101.com. I'm sure that regex101.com will have more users with this feature.

Thanks.

**Comment by firasdib** [comment]
Could you not already do this with regex101.com? Just put it in an iframe and it will work. Or do you want the sidebars collapsed by default then?

**Comment by Kristinita** [comment]
**Status: :heavy_check_mark: Solved for me**

![Sasha__Regex101--IframeWithTests](https://i.imgur.com/Bknp6LV.png)

+ [**Code**](https://codepen.io/Kristinita/pen/jpJEZQ)
+ [**Result**](https://codepen.io/Kristinita/full/jpJEZQ/)

Sorry, I didn't think that the site regex101.com has an adaptive design.

Thanks.
