### ISSUE TITLE
Can you fix Time Out?

### ISSUE THREAD

**Issue by blogers2** [firasdib/Regex101#1036]
## Bug Description

Does it hurt you to tell them the truth?
About the timeout bug constantly?
And you get excuses for my computer, or that line of regex code.
In case you do not know, my computer is an i7 12 gb ram, 4 gb graphic card

You can fix Time Out
### Reproduction steps

Do you think this code is difficult for you ??
(^ \ d0 {3,} \. 0 $)

1212.0

Produce TIME OUT!!!!!

### Expected Outcome
No match results

**Comment by firasdib** [comment]
That sounds weird. Could you please send me a permalink? Are there any errors in your console?

**Comment by blogers2** [comment]
https://regex101.com/r/w1rdrp/5

**Comment by blogers2** [comment]
![image](https://user-images.githubusercontent.com/17837956/44005720-40e08d8e-9e35-11e8-8411-6bea3070014a.png)

**Comment by firasdib** [comment]
This does not produce any errors for me. Can you please show me the contents of your console?

**Comment by blogers2** [comment]
![image](https://user-images.githubusercontent.com/17837956/44005742-b1bd4312-9e35-11e8-989a-7090673cf8dc.png)

**Comment by firasdib** [comment]
I don't see anything weird.

Can you show me your settings? (regex101.com/settings)

**Comment by blogers2** [comment]
Can you show me your settings? (regex101.com/settings) 

> Okei

![image](https://user-images.githubusercontent.com/17837956/44007700-4b001bfa-9e57-11e8-81d4-e6dec0dd88e3.png)

**Comment by firasdib** [comment]
That also looks fine. 

Can you try setting your timeout to 10s? Does that help?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Doqnach** [comment]
If that doesn't help, could you show which extensions/plugins/addons you have loaded?

**Comment by firasdib** [comment]
Any update @blogers2 ?
