### ISSUE TITLE
Quick reference window's examples

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1037]
I only checked this with pcre being set.

In the quick reference panel, the examples for \p{...} and \P{...} are wrong:

-it gives the string "???????" as an amernian word for 'fun' that would be matched by \p{Armenian}+ (the string is glitchy, the regex in itself is fine

 -it gives the same glitchy string for \P{Armenian} but it claims it would also match that word, where \P{Armenian}+ wouldn't match it

**Comment by Doqnach** [comment]
Could you provide a permalink showing this issue?

https://regex101.com/r/OSU20Y/1

Because I might just not understand your problem, since it seems to work as expected here?

**Comment by firasdib** [comment]
@working-name Do you know what happened here?

**Comment by working-name** [comment]
No idea will check when I get to a computer. Sorry!
