### ISSUE TITLE
Paste with escape all special chars

### ISSUE THREAD

**Issue by VGoudkov** [firasdib/Regex101#1038]
It will be extremely useful to paste a line into "Regular expession" edit with auto-escaping all special chars.
For example ``System.out.println("Hello, world"); ``  should change to ``System\.out\.println\("Hello, world"\);``
Optionally - change all whitespaces and tabs to ``\s+?``

**Comment by TWiStErRob** [comment]
Think about: What if I paste `(.)-`? (it has the same special chars)

**Comment by Ouims** [comment]
99,9% of the time someone paste something in the regex field, they want to get the meta character to be interpreted, it would be extremely painful if we had to delete the backslash or \Q...\E everytime for every meta character.

Changing all whitespace to \s+ (not \s+?, why non greedy? who use nongreedy \s on a daily basis compared to greedy?) is a better suggestion, it would be an option turned off by default and it would not do it if /x is used, but i'm still not a fan of it.

**Comment by VGoudkov** [comment]
I had to suggest it to be an option - may be a button "escape meta".  Sometimes it is useful - when I need to convert a text sample into regex template:  `myObject.toUpper("abc"+"def");` --> `(\s*\w+\.)toUpper(\(.+\)\s*;) ` step by step

**Comment by firasdib** [comment]
I don't feel that this is within the scope of the website I'm afraid.
