### ISSUE TITLE
Requesting csv format export of results causes a white screen

### ISSUE THREAD

**Issue by KutanaDev** [firasdib/Regex101#1039]
## Bug Description
Requesting csv format export of matches causes a white screen

### Reproduction steps
Windows 8.1 and the most up-to-date version of Chrome

**Regex** 
\\/[a-zA-Z]*(\d+)|\\/[a-zA-Z]+
**Test String**
/Documents/21/Pages/35.fpage
/Documents/13/Pages/Esc12.fpage
/Documents/1/FixedDocument.fdoc

Click the Export button in the results window and a dialog appears with a group of radiobuttons giving the choice of json, csv or plain text. Json is the default and the dialog is populated correctly. Clicking the plaintext radiobutton also populates the dialog correctly.

But clicking the csv radiobutton and the screen goes white. You have to hit [F5] to refresh and then you have to enter the regex and test strings all over again.

It's not a problem with all regexes - I've pasted in the regex and test strings I was using.

### Expected Outcome
Clicking the csv radiobutton  should export the results in csv format.

**Comment by KutanaDev** [comment]
https://regex101.com/r/UMPZYf/2

**Comment by firasdib** [comment]
Thank you, I will fix this tonight.

**Comment by firasdib** [comment]
Fixed
