### ISSUE TITLE
PCRE 8.42

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1040]
It looks like the website does not use the latest version of pcre which is 8.42.

https://lists.exim.org/lurker/message/20171210.084535.4ce8c449.en.html
and https://bugs.exim.org/show_bug.cgi?id=1882 reported by yourself
with https://github.com/firasdib/Regex101/issues/333 as for a report in here.

The bug was fixed on 8.42 but the website still shows the issue so i assume the website is not using the latest. If that's right it would be best to update.

**Comment by firasdib** [comment]
We're on 8.42, but the bug remains.

**Comment by Ouims** [comment]
I'm using PCRE 8.42 and it's working fine.

**Comment by Ouims** [comment]
Well it's working now so I'm not sure what you mean https://regex101.com/r/feZhVr/1

**Comment by firasdib** [comment]
@Ouims I'm fairly sure @jay-tea found a few related bugs
