### ISSUE TITLE
API Support to Evaluate Entries with Debug Information

### ISSUE THREAD

**Issue by campearce** [firasdib/Regex101#1041]
## Feature
It would be great, if the sites regex evaluation ui was moved, or replicated into an API.

We don't necessarily want to create regexes into your library, but an evaluation api, with the debug information returned is incredibly useful to us.

e.g. `POST /api/evaluate/`
```
{
  "regex": "testing \\w+",
  "testString": "Testing Regex",
  "flags": "gs",
  "delimiter": "/",
  "flavor": "pcre",
  "substitution": null,
  "unitTests": [
    {
      "description": "testing ok festering not ok",
      "criteria": "DOES_NOT_MATCH",
      "target": "REGEX",
      "testString": "festering",
      "compareString": null
    }
  ]
}
```

**Comment by firasdib** [comment]
This would open up the server to DoS and other vulnerabilities, which is the whole reason everything is evaluated on the client.

Plus this would require an even beefier server with higher specs.
