### ISSUE TITLE
Library search: search in pattern as well

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1045]
## Feature

I was trying to show an user a typical usage of \G, specifically (?!^)\G which is often used.

Google doesn't like symbols for exact match, so I thought I'd try the library, but the library does not search inside the pattern.
I believe this would be extremely useful, for the case above but even for ourselves, when you can't find an entry but you remember some part of the pattern of it.

The current behavior could be preserved and a checkbox "search in regular expression as well" (or a better name..) could be added, although I'd be for searching in pattern without the checkbox. That being said, I would understand if user typically don't want to look in pattern since that could return a lot of false positive. 

In fact, the best would be a second checkbox called "search only in pattern" which would improve the search for when you know you want to look for a pattern.

**Comment by firasdib** [comment]
I think it makes little sense and would just pollute the results.

**Comment by Ouims** [comment]
Well then you can still implement it with a checkbox, default behavior wouldn't change, no pollution : :1st_place_medal:
