### ISSUE TITLE
\p{ASCII} is not recognized

### ISSUE THREAD

**Issue by Wolfeur** [firasdib/Regex101#1046]
\p{ASCII} does not work. pcre and golang put it as an error, while javascript and python understand it as literal p and literal {ASCII} character string.

**Comment by firasdib** [comment]
That is because `\p` means something in PCRE/GO, but not the rest.

**Comment by Doqnach** [comment]
What error does PCRE and GO give you @Wolfeur ?

**Comment by Wolfeur** [comment]
@Doqnach This is what is shown in the explanation panel:

> \p{ASCII} This script is unknown/invalid

**Comment by Doqnach** [comment]
Going by http://www.pcre.org/pcre.txt, `\p{ASCII}` does not exist. Only as a POSIX `[[:ascii:]]` character-class.
