### ISSUE TITLE
Pcre debugger lists match attempt as pcre_exec() attempt

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1047]
## Bug Description

https://regex101.com/r/Q8w5eO/1

This is only one match. But the underlying code has to do some check to figure it out.
As described by PCRE, it has to try the pattern (call to pcre_exec()) at the same position with PCRE_NOTEMPTY_ATSTART and PCRE_ANCHORED set, and only if that fails advance the pointer and try.

This is done correctly, it's just that the attempt with PCRE_NOTEMPTY_ATSTART and PCRE_ANCHORED set + the attempt with the advanced pointer represents only one match attempt, not two, as the debugger is suggesting: https://regex101.com/r/Q8w5eO/1/debugger

### Reproduction steps

https://regex101.com/r/Q8w5eO/1/debugger

### Expected Outcome

Only one failed match should be displayed on the left menu

**Comment by firasdib** [comment]
These are not counted in the debugger.

**Comment by Ouims** [comment]
Hello @firasdib 

I do not understand your answer, and this is related to the pcretest discussion we had on irc.

Well I'm not really sure about any argument about this, but I think you should combine the try with PCRE_NOTEMPTY_ATSTART and PCRE_ANCHORED set and the attempt with the advanced forward position in the debugger into one failed attempt.
But I think, as far as the user is concerned, after a match is found and you have /g, if there's no more match, only one failed match attempt occured, not multiple.
Then I figured this may be hard to do because what you display is accurate regarding how many times the exec function is called, and it would be problematic for the step by step thing.
So instead, I would like to suggest that you make it explicit when a match attempt is tried because of /g and because of an empty match at the start.

In my link above, the debugger would display something like this

> Match 1 found in 43 step(s)
> Match 2 failed in 43 step(s)  *
> Match 3 failed in 18 step(s)

* Because of a empty match at the start of the string, a match with PCRE_NOTEMPTY_ATSTART and PCRE_ANCHORED has to be attempted before trying the next position.


It's not pretty, but you get the idea, maybe you can make it fit nicely, maybe just a tooltip on the *
