### ISSUE TITLE
Quick Reference for (?(DEFINE)...)

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#1048]
The displayed text for `(DEFINE)` under the Quick Reference is:

> The DEFINE group is completely ignored by regex. It gets treated as a var name="value", whereas you can recall the specific pattern for use via its name. Multiple patterns can be defined in the same DEFINE group.
> (?(DEFINE)(?\\'numbers\\'\\d+)(?\\'lowercase\\'[a-z]+)(?\\'uppercase\\'[A-Z]+))

Note that the single quotes (apostrophes) are escaped as `\'` instead of `'`:

> (?(DEFINE)(?'numbers'\d+)(?'lowercase'[a-z]+)(?'uppercase'[A-Z]+))

**Comment by firasdib** [comment]
Thanks, fixed

**Comment by OnlineCop** [comment]
I was going to fix it when I got off work tonight (I just wanted the bug here for reference) but looks like you already got it.
Don't we have to also update the translation files as well, though?

**Comment by OnlineCop** [comment]
I guess not: https://github.com/firasdib/regex101-translations/blob/master/ru.json#L703 only contains the text before the example, not the example itself.
