### ISSUE TITLE
In the Regex Editor view, add additional information and a link to the FAQ entry that states the limitations, versions, ... of the regex engines used.

### ISSUE THREAD

**Issue by mklement0** [firasdib/Regex101#1050]
<sup>First things first: regex101.com is a great site.</sup>

## Feature
 
In the Regex Editor view, add additional information and a link to the FAQ entry that states the limitations, versions, ... of the regex engines used.

Said FAQ entry - https://github.com/firasdib/Regex101/wiki/FAQ#how-close-does-regex101-emulates-the-engines - is not easily discoverable, but it contains vital information, most notably that  an imperfect Python _emulation_ is being used.

Here's a crude mock-up:

![image](https://user-images.githubusercontent.com/588825/46220118-307d9200-c317-11e8-81fe-5aaad1aea501.png)

Note the annotations next to the engine names, and the FAQ link at the bottom.

**Comment by Ouims** [comment]
I disagree that those informations should be displayed there. I agree that the informations should be available, but keep in mind the UI of the website is meant for everyone, not only technical users, so I believe the author would want to leave this menu as it is.

**Comment by mklement0** [comment]
@Ouims 

> not only technical users

If someone is experimenting with regular expressions, they're a technical user.

> I disagree that those informations should be displayed there.

It is vital that users be told _directly in the UI_ that the Python flavor is _not real Python_, because users - understandable expect the real thing - and it wouldn't even occur to them that you need to read the fine print in a - currently hard to find - FAQ to find out that it isn't.

While the other information is less crucial, I suggest including it as well - that way, you get high-level information at a glance, and the FAQ link can take you to detailed information.

**Comment by JMichaelTX** [comment]
> Here's a crude mock-up:
> 
> ![image](https://user-images.githubusercontent.com/588825/46220118-307d9200-c317-11e8-81fe-5aaad1aea501.png)

@mklement0, I really like your suggestion.  IMO, it is essential for all users to be able to quickly see the pedigree of each flavor.

In addition to what @mklement0 has shown in his mockup, if you really wanted to be user-friendly, you could add one of the following:
1. A link in each flavor to displays the details, either in a popup or new window.
2. A tooltip that displays the details.

**Comment by Doqnach** [comment]
I think it would clutter the UI if you display it directly like the mockup. 

> If someone is experimenting with regular expressions, they're a technical user.

In the chatroom we often see it differently ;-]. Many people experimenting with Regex are doing so for the first time in their life and/or with little programming experience. Many times because some tool they are using uses regex for some form of filters.

A tooltip with details about the flavour would be a solution that is the best of both worlds.

**Comment by mklement0** [comment]
Thanks, @JMichaelTX  and @Doqnach.

Tooltips would be fine - the important thing is that the information is readily available.

I'd still include a link to the FAQ, though; one option to keep clutter down is to hyperlink the section header instead ("FLAVOR") - unless all information fits in the tooltips themselves, in line with @JMichaelTX's suggestion.

**Comment by firasdib** [comment]
My only issue is if this raises more questions than it answers.

`16-bit? Are there other? Which is <insert language> using?`

`Emulated? What does that mean? Does it work with python or not?`

**Comment by mklement0** [comment]
>  raises more questions than it answers.

And the FAQ link would be there to _answer_ these questions - which _should_ be raised by those for whom the concise qualifier is insufficient.

**Comment by Ouims** [comment]
A tooltip would not make the info available immediately...
imo the best would be to display a (?) icon next to the text "flavor" in the left menu, tooltiping that icon would reveal a small text saying "click to get more information about how the website use the different flavor/engine,", and that would lead to the faq or whatever.

**Comment by firasdib** [comment]
I'm torn on this. On on hand, it can be useful info, but on the other hand, its confusing information 90% of the time.

It doesn't matter PCRE is running the 16bit version, since the input from JS is UTF16. The most useful piece of info would be to mention that python is emulated, but how we place that info on the screen is the hard part.

**Comment by mklement0** [comment]
@firasdib: Then perhaps the FAQ link is sufficient, possibly supplemented with a tooltip for each item.

In addition to the Python info I think it's also important to know that the user's _own_ browser is used for JS.

**Comment by mklement0** [comment]
Perhaps hyperlinking the word "FLAVOR" would work.

**Comment by firasdib** [comment]
@mklement0 That would be a bit weird I reckon, as the text is already blue and its an unnatural UX behavior.

**Comment by mklement0** [comment]
Well, blue, yes, but it (rightfully) doesn't look like a hyperlink at the moment, so it could be styled as one.

I suggested it because it wouldn't take up additional space and wouldn't add visual clutter.
Another option is to add to the right of "FLAVOR" - there's space there.

**Comment by firasdib** [comment]
@mklement0 I think adding it to the right is better, but still not ideal. I need to think about this one :)

**Comment by TWiStErRob** [comment]
little (i) icon wouldn't take up much space next to flavor or even next to individual engines

**Comment by firasdib** [comment]
@TWiStErRob The entire row is clickable, and has a checkmark at the end. Adding another icon would add two clickable surfaces that intersect is an odd way, I think.

**Comment by Doqnach** [comment]
I would go with adding it at the right in the "Flavor" heading.

**Comment by Ouims** [comment]
Bump, knowing pcre uses the 16 bit lib is important to us, not to you @firasdib, i would have liked to know this in the past.

**Comment by firasdib** [comment]
There is now a button next to the flavor menu in the sidebar that will give you information about each flavor.

**Comment by mklement0** [comment]
That's great - thank you, @firasdib.

As for improving the content of the new pop-up: I think it would make sense to link to https://github.com/firasdib/Regex101/wiki/FAQ#how-close-does-regex101-emulates-the-engines from there, for more detailed info.
