### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by Jonathan435** [firasdib/Regex101#1051]
## Bug Description
if i am not wrong the editor should mark only '.' and not ' . '.

REGEX: `\W\.\W`

TEST STRING OUTPUT: https://imgur.com/a/0hspPuz

**Comment by working-name** [comment]
Hi Jonathan,

`\W` is the same as `[^a-zA-Z0-9_]` which will match spaces.

Was the point to only match a dot if preceded and followed by a space character? If so `(?<= )\.(?= )` is one way to do it.
