### ISSUE TITLE
Does JavaScript actually support negative lookbehinds on Regex101?

### ISSUE THREAD

**Issue by tommai78101** [firasdib/Regex101#1053]
## Does JavaScript actually support negative lookbehinds on Regex101?

![image](https://user-images.githubusercontent.com/6444116/46818084-5ad74280-cd4e-11e8-98eb-282b05cda1ab.png)

This is what's shown on Regex101. Javascript is the selected flavor. In the Quick Reference pane (bottom right corner), it shows Negative Lookbehinds are supported for some browsers, but not all. So I'm under the assumption Firefox Quantum has Negative Lookbehind support for JavaScript RegExp flavor.

However, at the top right corner, it shows a linter error, describing that the `preceding token is not quantifiable`.

Thus I have a few questions:

- Given the error, does this imply negative lookbehinds are not yet supported on certain browsers? 
- The vagueness of the error might mean JavaScript isn't ready yet?
- What else could the error mean?

Thanks.

**Comment by tommai78101** [comment]
I see. Thus far:

- Chrome supports negative lookbehind.
- Chrome Beta supports negative lookbehind.
- Firefox does not support negative lookbehind.
- Firefox Dev does not support negative lookbehind.
- Edge does not support negative lookbehind. (Windows 10 Update 1809)

May I ask if the following list be displayed on the Negative Lookbehind Quick Reference section?

**Comment by stamminator** [comment]
More info here: https://stackoverflow.com/a/50434875/4028303

**Comment by firasdib** [comment]
The site will automatically detect what browser you're using, and disable or enable specific features. In modern browsers, you can use lookbehinds in javascript. See picture.

<img width="1922" alt="screenshot 2018-11-26 at 17 57 36" src="https://user-images.githubusercontent.com/1335165/49029402-ca8d7980-f1a4-11e8-9c08-afffa64cde94.png">

**Comment by tommai78101** [comment]
Thanks for the confirmation, @firasdib.

**Comment by L5eoneill** [comment]
I can confirm that lookbehinds do NOT work in IE 11 or Edge, and yet regex101 shows them working. This is a problem.

**Comment by firasdib** [comment]
How is it showing that it is working? Which flavor have you selected?

Please share a print screen. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by working-name** [comment]
>I can confirm that lookbehinds do NOT work in IE 11 or Edge, and yet regex101 shows them working. This is a problem.

@L5eoneill IE or anything Microsoft put out has historically been and continues to be a handicapped product, unfortunately. The site does not show them working, the owner describes its behavior 2 comments above yours.

**Comment by L5eoneill** [comment]
I think, as it turns out, the PCRE flavor was selected. So, my error. I probably assumed my last selection (in Chrome, probably) would still be selected, and didn't check.

**Comment by TWiStErRob** [comment]
@firasdib this seems to be a recurring issue, have you thought about detecting lookaround in JS and adding a hint/link in the error message?
