### ISSUE TITLE
Modal to add unit test closes unexpectedly when selecting text with mouse

### ISSUE THREAD

**Issue by HatScripts** [firasdib/Regex101#1054]
## Bug description
The **Add unit test** modal closes when you release the mouse outside of it.

### Reproduction steps
1. Switch to [unit tests mode](https://regex101.com/tests)
2. Press the **Add test** button
3. Press and hold the mouse down anywhere within the modal (including within one of the text boxes as though you were selecting text), and then release the mouse outside of the modal.

### Expected outcome
I expect the modal to close only when I either
* Click the **x** icon
* Click or mouse press outside of the modal area

**Comment by Doqnach** [comment]
Just tried it out and I also notice this behaviour. I can understand that having the mousedown event also originating outside of the modal dialog makes more sense and would counter accidentally letting the mouse button go outside of the modal dialog when selecting text for instance.

**Comment by firasdib** [comment]
There does not seem to be a clean solution for this problem, that does not involve quite a bit of stupid code.

I'm currently checking where you're releasing the mouse, and using that to determine if your intention is to close it. This has the side-effect you're describing.

If I instead only look at distinct clicks, the browser will not recognize if you move your mouse. That is, if you click outside, but move the mouse inside of the modal, it will still close, as the browser reports the click happening outside of the modal.

So this kind of boils down to choosing our poison :D

**Comment by HatScripts** [comment]
@firasdib Hmm, why wouldn't something as simple as binding the [onclick](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick) of the modal's close button and its transparent background overlay thing, work? [Here's a codepen example of what I mean](https://codepen.io/HatScripts/pen/jQeqJe).

Or just something like this if you're using jQuery:
```js
$("#blackout, .close-button").click(function() {
    $(this).hide();
});

**Comment by firasdib** [comment]
It works for your case, but breaks another. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Doqnach** [comment]
Only solution would be tracking mousedown & mouseup individually, but that can have very annoying issues with cases like mousedown within the browser and mouseup outside of it (and vice-versa).

**Comment by firasdib** [comment]
@Doqnach The best solution would be for me to re-write the modal, as its a bit stupidly layered. I can look into this in a bit.

**Comment by Doqnach** [comment]
![image](https://user-images.githubusercontent.com/25537191/49218207-196b2700-f3d0-11e8-817b-ac3dc2bfd816.png)
