### ISSUE TITLE
The explanation for limited repetition of a token is ambiguous

### ISSUE THREAD

**Issue by KingSupernova31** [firasdib/Regex101#1056]
When using the repetition quantifier {min,max}, the explanation that the site gives is "Matches between min and max times." This is ambiguous because the word "between" in English can mean either inclusive or exclusive depending on context. I suggest changing the explanation text to "Matches between min and max times (inclusive)." or even simpler "Matches from min to max times."

**Comment by Doqnach** [comment]
I would prefer the first suggestion since the second one can have the exact same problem (perhaps only from the point of view of non-native speakers). "to" can also be interpreted as "up to (not including)".

**Comment by firasdib** [comment]
The explanation of quantifiers can already get quite heavy.

For example:

```
{1,4}? Quantifier — Matches between 1 and 4 times, as few times as possible, expanding as needed (lazy)
```
