### ISSUE TITLE
Typo in settings

### ISSUE THREAD

**Issue by Sod-Almighty** [firasdib/Regex101#1057]
Thank you for creating the most useful regex website currently in existence. I very much appreciate it.

That said, there is a small typo in your settings page:
> Select the flavor you want to use when the site loads. Note: a saved entries' flavor overwrites this.

Should read:

> Note: a saved entry's flavor overwrites this.

Reason being, you are referring to "a" saved entry, i.e. a singular. If you wanted to refer to multiple entries, you would say:

> Note: saved entries' flavors will overwrite this.

On a related note, saying "will supersede this setting" or "will override this" would be better than "overwrite".

**Comment by firasdib** [comment]
Thanks, fixed.
