### ISSUE TITLE
pcre lookahead invalid match

### ISSUE THREAD

**Issue by wolfsoft** [firasdib/Regex101#1058]
## Bug Description

The website shows invalid matches for some of regular expressions in pcre mode.

### Reproduction steps

1. Select pcre (php) flavor.

2. Type the regular expression:
`(?=.*Firefox\/(\d+))(?!.*rv:\1).+`

2. Type following test string:

`Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0`

The match information pane shows "Full match"

### Expected Outcome

No match.

You can check this expression on https://www.regextester.com, for example (in pcre mode it not matches, but in Javascript mode it matches).

Possibly, it's because you don't execute real pcre (php) code, but some sort of javascript emulation.

**Comment by firasdib** [comment]
This is not how lookbehinds work. Your pattern is incorrect. Add anchors to it and it will do what you expect.

You can get more info on IRC (see link in website, on the sidebar).
