### ISSUE TITLE
Python modifier span (?aiLmsux-imsx:...) not supported

### ISSUE THREAD

**Issue by rgbrowngh** [firasdib/Regex101#1059]
https://docs.python.org/3/library/re.html
`(?aiLmsux-imsx:...)`
"New in version 3.6."

If a pattern such as `r'(?s:.*)'` is used, regex101 displays it as an incomplete group structure.

**Comment by TWiStErRob** [comment]
Repro permalink: https://regex101.com/r/nUkup0/1/
Same works in PCRE: https://regex101.com/r/nUkup0/4/, so it's potentially simulating <3.6
Not fully equivalent, but workaround nonetheless: https://regex101.com/r/nUkup0/2/

Interesting clue that could be related: https://regex101.com/r/nUkup0/3/
> `(?s)` Regex101 only supports inline modifiers to be placed at the start of the regex for python (which is also best practice)

**Comment by firasdib** [comment]
As of right now, we only support placing the flags at the front of the regex.
