### ISSUE TITLE
Voltage emoji not detected

### ISSUE THREAD

**Issue by lzkbloodmage** [firasdib/Regex101#1060]
## Bug Description
Emoji U000026A1 (voltage) is not detected in python.

### Reproduction steps
Use python regex checker to check for U000026A1

### Expected Outcome
No match if voltage emoji is present, regardless whether regex is correct or not.
![image](https://user-images.githubusercontent.com/41339931/47794042-9b791900-dd5a-11e8-9c22-17df70b7a856.png)

**Comment by working-name** [comment]
@lzkbloodmage Hi there, I'm sure you know this but most of these fancy looking emojis are built from two code points. You're only matching "half" of the thunderbolt with your regex. You need a `+` or `{2}` or whatever you think is pertinent after the character class `[...]`to match these 2-code point emojis.

**Comment by lzkbloodmage** [comment]
Thank you. Solved.
