### ISSUE TITLE
saving regex gives HTTP 500

### ISSUE THREAD

**Issue by Doqnach** [firasdib/Regex101#1061]
## Bug Description

Saving a regex gives a HTTP 500

### Reproduction steps

1. enter regex
2. press save

### Expected Outcome

saved regex

### Actual Outcome

```
POST https://regex101.com/api/regex/ 500 (Internal Server Error)
Unable to save regex Error: Internal Server Error
    at r (main.js:11)
```

**Comment by firasdib** [comment]
Fixed
