### ISSUE TITLE
Please add option to disable showing `Full match` in right side panel.

### ISSUE THREAD

**Issue by NabiKAZ** [firasdib/Regex101#1062]
Please add option to disable showing `Full match` in right side panel.
Some pattern is large, and the `Full match` in this section makes it busy.

**Comment by Doqnach** [comment]
But the full match is important is many cases and most tools report back the full match. If you don't have any capture groups then the full match is also the most important thing to see.

How would you see such a feature? An option in settings? directly in the UI some toggle?

**Comment by TWiStErRob** [comment]
Here's an example, try to find Group 1 by scrolling: https://regex101.com/r/qvz783/1

> But the full match is important is many cases

that's why he's asking for an option :)

re UI: I think a little cog next to the export icon would do (with persisted state).
And of course when there are no groups in the regex this option wouldn't have any effect.

**Comment by TWiStErRob** [comment]
Note: I've experienced this problem not only with full match, but with other groups as well. When the groups are long it's hard to see the matches. Especially since we lost the ability to resize the sidebars.

@firasdib potentially a more generic solution would be to display any group (0..n) as collapsed by default and only expand when the user clicks on it:
![image](https://user-images.githubusercontent.com/2906988/48060265-6aae3f00-e1b3-11e8-8c7e-cf9804e7fd6c.png)

e.g. https://stackoverflow.com/a/30362531/253468

**Comment by NabiKAZ** [comment]
As the @TWiStErRob points out, this problem is very acute when the Full match is too large and we have to scroll a lot. He provided a good example.

In my opinion, the toggle for expansion is not very good because the problem is not just in the UI, and sometimes it's necessary to have the results in Export Matches in the form of plain text without a full match. It's like trying to extract all the URLs on a page for download, so need just the URL in each line of export without full matches.
Of course, maybe the way data is displayed in the output section can be another issue, and I try to further explain it in another issue.

I think it's best to have a button in Settings to show or not to show the full match. Of course, it can be both, so also be toggle for expansion.

**Comment by firasdib** [comment]
I believe the full match is crucial information, and needs to be visible. However, I do understand the issue of it taking up too much space when you're working with large strings.

Clicking to expand will clash with the feature which is currently used to highlight the matches within the subject string.

I see no simple solution for this, short of adding some sort of global setting, which I don't think is a nice way of solving it.

**Comment by Ouims** [comment]
@firasdib what about some + icon which once clicked displays the data, like in a tree structure

To preserve compatibility they would always be expanded:



- Match 1
- Full match: blablabla
                    blablabla
                    blablabla
- Group 1: bla

clicking on the - in front of Match 1 would collapse the Match 1 entirely.

clicking on the - in front of Full match would result in:

- Match 1
+ Full match:
- Group 1: bla

**Comment by firasdib** [comment]
I've decided to truncate text in the sidebar for ALL groups if they are longer than 100 chars. If you want to see the text, just click it to show, and then click to truncate again.

**Comment by ciscorucinski** [comment]
There should be two conditions to split. Length and number of newlines.

The widest English letter (W) takes up 3 lines at 100 characters.
Under the new implementation, if each line is 1 letter long, you will display 100 lines in Full match.

A good workaround would be to allow 100 characters or maybe 5 newlines. This will allow users to still see the Group or next Full Match

**Comment by firasdib** [comment]
You make a valid point @ciscorucinski, but I'm unsure of the real world scenario in which you'd match 100 consecutive newlines.

The amount of lines also depends on how wide you have the sidebar, which depends on your screen resolution, and can be dragged to be wider/narrower.

**Comment by ciscorucinski** [comment]
Actually, it's 50 lines max. Those two extremes are just that extremes. **All use cases will fall somewhere in the middle of the two.**

Why do most people need to see more than 2 lines for a large number of use cases? I don't think they really need to, especially with the ability to expand/truncate with a click.

I showed that the unrealistic 100-w string takes 3 lines. The vast majority of Full matches probably fall under less than 1 line. The only examples that bypass this are the examples with newline characters.

So a great solution **to not hide valuable information** (other Full matches and group matches) would be to limit it to 100 characters or 3, 4, or 5 lines max (whichever happens first).

If you look at https://regex101.com/r/cgu4yl/3/ which is slightly modified from a real YAML file. Why do I need to see 11 lines plus a scrollbar in the Full match. I can see the match in the editor. I can expand it, so I want to see all the other group data without having to scroll or collapsing sidebar sections

If you look at TWiStErRob's link https://regex101.com/r/qvz783/1, and collapse **Quick Reference**, then you still cannot see the group matches. You still only see the Full match.

**Comment by firasdib** [comment]
Ok, this makes sense @ciscorucinski. I'll make it limit to 5 newlines or 100 characters.

**Comment by ciscorucinski** [comment]
Counting lines is very hard.

Easiest solution is to weigh newlines characters as more than one character ("point"). I've look **at weighing them as 5 points, 10 points, 15 points.**

I've also looked **at doubling the weight for each newline character** starting at 2 or 4 points. This method seems best. At the extreme of 1 character per line will result in 5 - 6 lines max based on starting weight. A result with only one newline will result in almost no change of 2 - 3 lines max.

**Comment by firasdib** [comment]
You're confusing me now. Why not just count where the 5th newline is, and if its earlier than 100, cap it at that, otherwise at 100?

**Comment by NabiKAZ** [comment]
That's good, Thanks.
