### ISSUE TITLE
Feature: The choice of fields (matches) required in the Export Matches can be useful.

### ISSUE THREAD

**Issue by NabiKAZ** [firasdib/Regex101#1063]
The choice of fields (matches) required in the Export Matches can be useful.

See this example:
https://regex101.com/r/Jmgcqg/2

![image](https://user-images.githubusercontent.com/246721/48087988-125c5900-e216-11e8-9988-944f991524dd.png)

The text export is be like this, that is not useful:

![image](https://user-images.githubusercontent.com/246721/48087118-b264b300-e213-11e8-9b19-85d78b9212c2.png)

But perhaps you need the only URL list to use for download manager, so this might be useful:

![image](https://user-images.githubusercontent.com/246721/48088520-7e8b8c80-e217-11e8-8743-ac85246d09fa.png)

Or need titles and URLs in the json format, without any long and useless Full Matches, or additional descriptions. So this can be useful:

![image](https://user-images.githubusercontent.com/246721/48088552-93682000-e217-11e8-9399-b8318c5d7211.png)

_(I added the top bar to select the fields for the sample and explain this feature.)_

**Comment by TWiStErRob** [comment]
Have you tried the workaround I mentioned in https://github.com/firasdib/Regex101/issues/792#issuecomment-282523712? You define the output yourself with a replace pattern; granted it's not as fancy as clicking on the UI, but it's possible right now.

Here it is adapted to your example: https://regex101.com/r/Jmgcqg/3

**Comment by NabiKAZ** [comment]
@TWiStErRob 
Sure it's have benefit, But it's advanced to use and all normal users do not know it.. I thinks add this option in export menu has simple to use.

**Comment by Doqnach** [comment]
A dropdown with checkboxes would be a solution that also works for small screen.

I can see the benefit when using the website as a parser. Personally I would simply write a script to do the conversion and only use the website for testing out the regex. 

Does make you wonder how much this feature would be used. I kind of lean in the direction of new users not knowing they can export anything, and power users simply writing their own conversion scripts.

**Comment by firasdib** [comment]
I believe the core purpose of regex101 is to provide users with a means to test and develop regular expressions. The feature to export matches is merely a "nice to have" kind of feature. If we extend it, we will end up with more and more sub-features of it. I believe its up to the user to prune the results as they see fit. Merely filtering on column is just one out of multiple filters one might want for such a feature.
