### ISSUE TITLE
I CANT PAST TEXT?!! FROM THIS WEEK. I CANT USE IN THE SITE 

### ISSUE THREAD

**Issue by devorel** [firasdib/Regex101#1064]

**Comment by TWiStErRob** [comment]
Please describe your problem in more detail, hopefully in full sentences, and with correct spelling. Otherwise it's pretty hard to help.

**Comment by working-name** [comment]
Have you tried another browser?

**Comment by lalaithan** [comment]
Are you using right-click or keyboard shortcuts?

**Comment by devorel** [comment]
right-click or keyboard shortcuts? also.
now i can use , do u did something?

**Comment by working-name** [comment]
I'm glad to hear it's working again!
