### ISSUE TITLE
Contradicting explanation information about case sensitivity in non [a-zA-Z]

### ISSUE THREAD

**Issue by circular-code** [firasdib/Regex101#1066]
## Bug Description
![image](https://user-images.githubusercontent.com/31777077/48471370-0ebb6a00-e7f4-11e8-911c-10147e4b883a.png)

### Reproduction steps
-set Flags gmi
-write ä in your expression
-write case insensitive Ä in your test string

### Expected Outcome
ä matches the character ä literally (case sensitive)

**Comment by Doqnach** [comment]
You are missing the unicode flag.

https://regex101.com/r/g0sjaD/1

working as intended

**Comment by circular-code** [comment]
Thanks for the suggestion, but my problem is not that it does not match (this is the correct behaviour,  like you said i am missing the unicode flag). My problem is that the explanation is contradictory, since the text adds "case insensitive" instead of case sensitive as soon as you add the i-flag, not taking into account that the case insensitivity is only ignoring the case of [a-zA-Z] in this case.

In this case the topmost explanation becomes invalid because it does not take into account if the letter ä is inside the range of [a-zA-Z]

**Comment by Doqnach** [comment]
Well.. I believe that under the rules of ANSI ä is not considered the lowercase of Ä. So it does exactly what it says it is doing. Under UTF-8 it does see it like you are expecting it.

https://en.wikipedia.org/wiki/Ä#Independent_letter

**Comment by circular-code** [comment]
Ah I see. So this is where my confusion originates. Thank you for clearing it up.
