### ISSUE TITLE
Add ES2018 unicode escapes for javascript

### ISSUE THREAD

**Issue by tlbdk** [firasdib/Regex101#1067]
## Bug Description
ES2018 added unicode property escapes:
https://flaviocopes.com/es2018/#unicode-property-escapes-p-and-p

We are using the Unicode categories feature to match casing: 
https://www.regular-expressions.info/unicode.html

### Reproduction steps

1. Select "javascript"
2. Type in ((?:\p{Lu}\p{Ll})|\p{Ll}{2,})(\p{Lu})

### Expected Outcome

No errors and would match
BoWinter
TroelsLiebeBentsen

Works on chrome and node:
``` javascript
"BoWinther".replace(/(?:(\p{Lu}\p{Ll}|\p{Ll}{2,}))(\p{Lu})/gu, "$1 $2") // Returns "Bo Winther"
"TroelsLiebeBentsen".replace(/(?:(\p{Lu}\p{Ll}|\p{Ll}{2,}))(\p{Lu})/gu, "$1 $2") // Returns "Troels Liebe Bentsen"
```

**Comment by anurbol** [comment]
I can confirm, this issue confused me, I spent some time before I understood that this is simply not supported by regex101.

**Comment by xenoterracide** [comment]
+1

**Comment by firasdib** [comment]
These are implemented since a while back now.
