### ISSUE TITLE
Difference between Regex101 and actual result in JS

### ISSUE THREAD

**Issue by volodymyrradchenko** [firasdib/Regex101#1069]
Hi!
That's what I get in 101:
![image](https://user-images.githubusercontent.com/40847850/48969088-00dec380-f002-11e8-9df1-6349f25b3159.png)

And here is what I was expecting to see:
![image](https://user-images.githubusercontent.com/40847850/48969100-32578f00-f002-11e8-975e-b52edd7a96f5.png)

**Comment by TWiStErRob** [comment]
Your input is different.

On the website you have `\\"Hi`.
In the console you have `\"Hi`.
Notice the result array that's being shown and count backslashes.
Also `console.log(str)` to see what a `Regexp` will match against.

Try to replace `str = '...'` with ``str = `...``` to use the same copy-pasteable inputs and get the same behaviour.

**Comment by volodymyrradchenko** [comment]
@TWiStErRob thank's for reply!
The array you see in the console is the output of the match method on the string.
Input is the same both for 101 and codepen and equals to `' .. "test me" .. "Say \\"Hi\\"!" .. "\\r\\n\\\\" .. '`
The point of this regex match is to find chunks of string embedded in `"`  quotes, skipping escaped quotes `\"`
The thing I'm talking about is that output for 101 is array `['"test me"', '"Say \\"', '"\\r\\n\\\\"']` instead of the expected `['"test me"', '"Say \\"Hi\\"!"', '"\\r\\n\\\\"']`

P.S Just noticed a typo in the input string, but it doesn't make any difference anyway. Proper input string should look like this: `' .. "test me" .. "Say \\"Hi\\"!" .. "\\r\\n\\\\"" .. '`
The output for codepen will be `['"test me"', '"Say \\"Hi\\"!"', '"\\r\\n\\\\""']` and 101:

![image](https://user-images.githubusercontent.com/40847850/48984537-64054e80-f105-11e8-922a-c0823f9fad31.png)

https://codepen.io/bratko_bob/pen/MzGrpz?editors=0011

P.P.S That's where I took example string from [github repo](https://github.com/iliakan/javascript-tutorial-en/blob/master/5-regular-expressions/11-regexp-alternation/03-match-quoted-string/solution.md), [website](https://javascript.info/task/match-quoted-string)

**Comment by Doqnach** [comment]
The input is not the same actually (Like @TWiStErRob said), because the "test string" on Regex101 is taken literal and no escapes are processed.

```javascript
var str = ' .. "test me" .. "Say \\"Hello\\"!" .. "\\\\ \\"" ..'
console.log(str)
 .. "test me" .. "Say \"Hello\"!" .. "\\ \"" ..
```

https://regex101.com/r/XBA8Ig/1
