### ISSUE TITLE
Updating Library Regex Loses Previous Version's Tests

### ISSUE THREAD

**Issue by IanGabes** [firasdib/Regex101#1071]
## Bug Description
Updating a library regex will lose the tests from the previous version.

### Reproduction steps
1. Create a Regex with unit tests.
2. Save that Regex to your library.
3. Open the permalink to that library entry.
4. Update the library entry with a new version.
5. Observe that unit tests are gone, only available on the previous version.

First Entry: https://regex101.com/r/K6VV92/1
Second Entry: https://regex101.com/r/K6VV92/2

My first entry has tests, my second does not.

### Expected Outcome

I would like to keep my tests across versions of a regex, between updates.

**Comment by firasdib** [comment]
Thanks for the excellent report. This has been fixed. Sorry for the inconvenience.
