### ISSUE TITLE
Splitting the list of "Flavors" to "Native" and "Emulated"

### ISSUE THREAD

**Issue by Doqnach** [firasdib/Regex101#1074]
## Feature

> Doqnach:
> Is it an idea to maybe split the flavours in "native" and "emulated" sections, with a caveat for the "emulated" section that the implementation might not be 100% complete and a link to "known issues"?
> 
> Related also somewhat to #1050

> Firasdib:
> @Doqnach Thats not a bad idea.
> 
> Should python be in that section then? Its emulated, but its implemented to 99% of native.

> Doqnach:
> Putting Python under "Emulated" has the advantage of being 99% covering and providing a hook for people to understand to not expect 100%? So I would go for emulated in that case. If emulated is 100% covering: sweet! But at least it leaves you an explanation for that 1%.

> Firasdib
> @Doqnach We also open up for "omg what does this mean? can I even use it anymore?"

Discussion from #141, related to #1050 and others

**Comment by Doqnach** [comment]
> We also open up for "omg what does this mean? can I even use it anymore?"

I kind of expect this only being an issue to returning novices maybe. In the end it's only a UI clarification of existing functionality.

The next question is that of UX... would it then become something like:

* Native:
  * PCRE (PHP)
  * ECMAScript
  * golang
* Emulated:
  * Python (PCRE-based)
  * C++ (ECMAScript-based)
  * Javascript (ECMAScript-based)

Or even put PHP (and Perl, and "grep -e", etc) under emulated

**Comment by firasdib** [comment]
Lets keep the discussion https://github.com/firasdib/Regex101/issues/1050 -- doesn't seem anyone has anything to say here.
