### ISSUE TITLE
Is there a way to put \r AND \n into the test text?

### ISSUE THREAD

**Issue by rquadling** [firasdib/Regex101#1075]
## Question
I need to parse the output of a command where the output contains progress information ...
```
Line1 Some status\n
Line2.1 10% (10/100)\rLine2.2 20% (20/100)\rLine2.3 30% (30/100)\r...\rLine2.10 100% (100/100) Done\n
Line3.1 10% (10/100)\rLine3.2 20% (20/100)\rLine3.3 30% (30/100)\r...\rLine3.10 100% (100/100) Done\n
Line4.1 10% (10/100)\rLine4.2 20% (20/100)\rLine4.3 30% (30/100)\r...\rLine4.10 100% (100/100) Done\n
```
I need to display the segments of the lines that end with \n ...
```
Line1 Some status\n
Line2.10 100% (100/100) Done\n
Line3.10 100% (100/100) Done\n
Line4.10 100% (100/100) Done\n
```
(Note that the text above is just an example. Only the `\r` and `\n`).

Can I do this in a single regex?

**Comment by TWiStErRob** [comment]
e.g. https://regex101.com/r/xOJwcE/1
If you need help with constructing a regex, please join the [IRC channel (no reg needed)](http://webchat.freenode.net/?channels=regex)
(link from last button on left sidebar on regex101.com)

**Comment by firasdib** [comment]
Unfortunately there is no way to insert \r currently due to a limitation in codemirror.

Hopefully this is fixed in their new version, but until then, I'm afraid you're out of luck.
