### ISSUE TITLE
Quiz Comments

### ISSUE THREAD

**Issue by jay-tea** [firasdib/Regex101#1078]
Just some random comments:

Task 28: "Match only those strings which have an equal amount of each character, in order. For example, match both abc and xyz, but aab or xyy. The string length is arbitrary, which means you also need to match aaaabbbbcccc etc."

Should be "but NOT aab"

Task 29: "Given an unshortened IPv6 address, return the shortened version of it. You need to collapse octets of zeroes into :: and remove all leading zeroes."

Should be "hextets" and "zeros". In fact, I'd rewrite it as:

"Given an unshortened IPv6 address, return the shortened version of it. You need to remove all leading zeros and collapse a series of two or more zero hextets into "::""

Task 26: "You have previously solved a task for matching the outer most balanced brackets. Let's extend on that, and grab all balanced brackets in a string."

I'd recommend rephrasing that as "and capture all groups of balanced brackets and their contents"

**Comment by firasdib** [comment]
Thank you. I've fixed the wording. Lets keep the rest of the comments in https://github.com/firasdib/Regex101/issues/1076
