### ISSUE TITLE
Prefill fields via URL are not working

### ISSUE THREAD

**Issue by ggolan** [firasdib/Regex101#1079]
## Bug Description
While attempting to use the prefill behavior via URL defined in the FAQ (https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url) the fields are not prefilled as expected. This behavior worked a few weeks ago but no longer works when I try it now. 

### Reproduction steps

1. Put the following url into a web browser: https://regex101.com/?regex=myregex&testString=mystring
2. View the resulting page that is not populated with the requested regex and test string. 

### Expected Outcome

The appropriate fields to be populated using the values passed in via the URL.

**Comment by firasdib** [comment]
This seems to be an issue with the service worker, caching too aggressively (every programmers favourite problem). 

I need to re-evaluate how I cache things, and how to manage offline vs online.

Thanks for bringing this to my attention.

**Comment by firasdib** [comment]
I've pushed a fix for this. It will require you to close all tabs you have open with regex101.com, and then reopen a new tab (this is the standard update behavior for the service worker -- I haven't found the need to invalidate peoples caches more often than this during normal usage).

If it still doesn't work, please comment here.
