### ISSUE TITLE
github login redirects to blank page

### ISSUE THREAD

**Issue by pjetr3k** [firasdib/Regex101#1080]
Tried to log in with github as usual today, no oauth pop up, just a blank screen after selecting github from sign in options

**Comment by firasdib** [comment]
Thanks for the report.

I've been doing major refactoring lately (in hopes of improving code quality, and in the end, user experience), and sometimes a few dumb things slip through.

You'll have to close all tabs of regex101 (perhaps restart the browser), and your service worker will update and you should be back on track.

Sorry for the inconvenience.
