### ISSUE TITLE
Issues highlighting text in Test String multi-line textbox

### ISSUE THREAD

**Issue by AshleyJamesy** [firasdib/Regex101#1085]
Having issues highlighting text in the Test String box - cannot highlight sentences or even a few words, however highlighting big chunks sometimes works. Chrome and Firefox have same issue.

**Comment by firasdib** [comment]
Please use the issue template and fill out your issue properly.

Critical information is missing: Browser, OS, reproduction steps, gifs/screenshots, permalink, etc.

**Comment by firasdib** [comment]
Maybe related to: https://github.com/codemirror/CodeMirror/issues/5733

**Comment by firasdib** [comment]
User report:

![image](https://user-images.githubusercontent.com/1335165/50823659-c3759180-1334-11e9-93a6-ac13cb19db83.png)

**Comment by Cosmatevs** [comment]
Browsers: Chrome, Firefox, Edge. OS: Windows 10 Home v. 1803.
It happens to me after I open a link to someone's regular expression (e.g. https://regex101.com/r/phuHP8/4) but I can't exclude other reasons. I can't highlight text in the Test String box by dragging while holding mouse cursor but I can still do it by double-clicking or ctrl+A.
![clip0017](https://user-images.githubusercontent.com/44393502/50824453-eef97b80-1336-11e9-9214-56daa2d4c57d.gif)
(red starburst means left-click)
Once it happens, I can't properly highlight text in any Test String box even if I open the Regex Editor in a new tab or in another browser. To get rid of the issue, I need to restart system.

**Comment by firasdib** [comment]
Sorry, this was all my fault. Fixed!
