### ISSUE TITLE
Please add hotkeys to go forward and back 1 step in the regex debugger

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1086]
## Feature
In the regex debugger, it's very nice to be able to adjust the number of steps being viewed to an arbitrarily high number. (I usually just click on the "number of steps" box on the right and press the zero key several times to go to the max.)

But when there are thousands of steps, it's impossible to go forward and back just 1 step at a time using the mouse. Thus, important steps must be skipped, leaving one to guess what may have happened between those steps.

Please make the left and right arrow keys go back and forward 1 step. It might also be a good idea to make comma [,] and period [.] do the same thing, respectively, as those are common hotkeys in video players for going forward and back by 1 frame.

**Comment by firasdib** [comment]
This has been implemented. I will push it soon.

**Comment by Ouims** [comment]
when i asked for this i was told "no", that was a couple of days ago only.
