### ISSUE TITLE
Please show the contents of captures in the debugger

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1087]
## Feature
It would be incredibly useful to be able to see the contents of each capture/backreference in the debugger, with their values updated whenever they are changed by moving to a different step. This would take a lot of the guesswork out of figuring out why a regex works or doesn't when given with a particular input.

And in the new style of the debugger, this would work very nicely. There is currently a large amount of empty space below. This would be perfectly employed to show the contents of all of the captures.

If there are so many captures that they don't fit vertically all at once (which should admittedly be unusual), there should be a scroll bar allowing them all to be viewed.

**Comment by firasdib** [comment]
Its a nice idea, but nothing I can do atm.
