### ISSUE TITLE
Unit test area redesign

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#1090]
I think the unit test area is long overdue for a redesign. I'd appreciate if we could brainstorm what we like and dislike about the current solution, and how a better one might look/work.

I would greatly appreciate mocks and images that showcase your idea (does not have to be fancy).

**Comment by OnlineCop** [comment]
Import/export unit tests. XML/JSON and other formats is fine.

**Comment by firasdib** [comment]
Do we want to keep the unit tests "inline", as they are today? I get the feeling its a bit cluttered, and perhaps it should live as a "tool" in the left sidebar, and open in an overlay. This does however limit the work you can do on the regex during this, which can be included in the overlay if need be.

**Comment by OnlineCop** [comment]
Depends on how much screen real estate you want to utilize for mobile and small displays.

**Comment by firasdib** [comment]
@OnlineCop Not sure what you mean, you'd get the same as you get today.

My largest gripe with the current solution is that it feels cluttered and a bit lost/hidden.

**Comment by TWiStErRob** [comment]
actually, where's the unit test page?

**Comment by TWiStErRob** [comment]
Long time since I laughed this hard, nice arrows! I was looking near the debugger/generator...

**Comment by firasdib** [comment]
That is where I want to put it: in the sidebar under "tools", with an overlay much like that of the code generator and debugger. If we want to be able to edit the regex from in there as well, it can be added.

**Comment by TWiStErRob** [comment]
It doesn't even have to be a popup just because it's under tools. I like the inline-ness of it. Easy access to explanation and quickref.

I would like the test to have an auto-test if I was using this, pressing Run Tests all the time is annoying (kbd<->mouse change). Also a freshly added test could auto-execute immediately.

**Comment by firasdib** [comment]
Personally, I'd like an easier way to add unit tests to begin with. I do not like the use of a modal.

I see the point to having it inline, but typically the focus isn't that regex intensive while writing unit tests (I think).

**Comment by TWiStErRob** [comment]
If you follow TDD you would need to add a test, see it fail, fix regex, see it green, add next test, repeat.
The email task in quiz starting from `.*@.*` and only fixing what the test message says is a good example of TDD.

**Comment by firasdib** [comment]
@TWiStErRob That sounds more like BDD -- TDD in my eyes is create all test cases and then make your code pass it. Either way, having the regex editable from another place is not an issue, I can add the components anywhere I like.

**Comment by firasdib** [comment]
As for the unit test creation, I want to get rid of the modal. Perhaps you can just click a `+` button or something, which inserts an "empty" row, which you then fill in, kind of like how slack does it. Unsure if it works with more complex data (such as the unit tests).

![screenshot 2019-01-09 at 08 53 02](https://user-images.githubusercontent.com/1335165/50884727-0ba3bb00-13ec-11e9-9c85-78d62becb4a4.png)

**Comment by firasdib** [comment]
Key points:

1. Easy to navigate to. Perhaps sticky toggle in sidebar?
2. Easy to add and edit tests -- maybe something like the slack design? I don't think you need a save button -- it should be automatically saved when you edit the fields.
3. Easy to run tests -- maybe have a run button with status in the sidebar, so you can run it even when you don't have the view open?
4. Run individual tests -- One play button next to each item?
5. Easy overview of tests. Some tests will have a description, some wont. How do we present a simplified view without limiting the tests? You might have really large inputs, that will be unwieldily to work with. Perhaps when you click on an input, it "expands" somehow, and takes focus, then when you close it, it shrinks down back and "truncates" the data so it fits on one line.

**Comment by Doqnach** [comment]
Related issues:

#795 
#847 
#869

**Comment by firasdib** [comment]
One thing that I dislike with the inline view is that it hides the match info and takes over the test area. It feels like you're doing a context switch, but its inline in the previous flow, which somehow doesn't sit quite right with me.

Is a full screen view, such as the code generator, bad?

**Comment by TWiStErRob** [comment]
The question is do you want to allow quick-ref and explanation visible while writing unit tests. Also do you want the left sidebar (icons) and settings accessible while editing tests, or you want the user to have to close, do stuff and re-open?

**Comment by firasdib** [comment]
@TWiStErRob Its not what I want, its what you, and everyone else, wants. 

- Quick ref: I don't see a point, as thats for the regex, and unit tests are typically not part of that.
- Left sidebar: There is nothing there of value I'd say. 
- Settings: again, I don't see the value there either.

**Comment by willthemoor** [comment]
Are there a few examples of the sort of test setups that we're looking to make it easier to create?

**Comment by firasdib** [comment]
I've been working on this and here is what I have so far

![image](https://user-images.githubusercontent.com/1335165/107966184-c6c7b680-6fab-11eb-87cc-449767091c7f.png)

To add a test, simply click "add new test" and a new entry will pop up in the list above, and you can edit it freely, without modals.

Thoughts? If all goes smoothly I will push this live in a week or so.

**Comment by OnlineCop** [comment]
Do any of those inline areas require validation, like to check that there are no invalid characters/options? Are duplicate descriptions allowed? If not, what happens when the user attempts to blur the field (keyboard input, like `TAB`, or switching to a different browser tab)?

**Comment by firasdib** [comment]
@OnlineCop No validation, they can be empty if need be. Any and all characters are valid and supported. Duplicate descriptions are fine, as are duplicate tests. Its up to the user to decide what to include.

The data is automatically saved on blur, tabbing, switching browser tabs etc. Nothing to worry about there.

**Comment by working-name** [comment]
#### looks great

That looks good, although to me it feels like it would be about the same as with the modal input other minus the visual occlusion. Right now I can still hit add test and use tab to navigate between inputs, save the unit test and I'm back to add test - awesome.

#### I'm pro collapsing left + right sidebars
As far as hiding left + right sidebars while in the unit tests view I see a clear advantage for people using TAB to navigate back to Add Test - much faster to get to it. 

### Suggestion 1: first switch to Unit tests: automatically add a new unit test and auto-focus description field
To that effect, popping-up "Add Test" and auto-focusing the description field might also be a sensible thing to do when you first switch to Unit Tests - less tabbing around hopefully.

### Suggestion 2: auto-populate description from string+assertion
I don't know what I would use the description for other than "potato should match" or "orange should not match" which in turn leads me to think that you could auto-populate it from the truncated sample string and the assertion selection, i.e. `given so... should not match` or `given so... full match contains given`. 

>It might create more work for you if some people find value in manually entering/editing said description. You'd have to disable auto-updating truncated string for example if the user adjusts it after altering description manually.

> It can also get stupid when you need to truncate too much in the case of full match assertion. Having a decent width is a requirement, possibly taking a dump on mobile views.
![Screen Shot 2021-02-15 at 1 11 23 PM](https://user-images.githubusercontent.com/16505052/107981078-717dac00-6f8f-11eb-8025-28736e62cef3.png)

### Suggestion 3: automatically run tests upon saving a new one

Another thing might be to run tests automatically upon saving a new one (like it does now when switching from match/substitution to unit tests). It would save another click or `SHIFT+TAB, ENTER, TAB` to get back to ADD TEST.

**Comment by firasdib** [comment]
@working-name Thanks for the feedback.

1. The description will be automatically focused when the element is created after pressing "Add test", so that should be quite keyboard friendly.
2. How should this work when creating the test? If the description is left empty it auto fills? A bit sceptic to this.
3. Not a bad idea. I will add a keyboard shortcut (ctrl+enter) to run the test too. I can, on any change, re-run the tests after a fixed amount of time.

**Comment by working-name** [comment]
1. and 3. sound great to me.

> 2\. How should this work when creating the test? If the description is left empty it auto fills? A bit sceptic to this.

I was actually just trying to build upon the current behavior which lists the test string (and updates it) above target and criteria – unless a manual description is given. That is, rather than having `(no description)` when collapsed, which in my view doesn't inform enough, we could auto-generate said description.

![auto-description](https://user-images.githubusercontent.com/16505052/108017611-491f9d00-6fe3-11eb-8cc2-48e2554f75ce.jpg)

The behavior would copy the current one: 

**When collapsed**: auto-generate the one-liner description when none is typed up. If there is a custom description, display it instead.

**When expanded**: go back to regular view as in your preview above, and either display a blank description field if none was entered, or display the previously typed description.

**Comment by firasdib** [comment]
@working-name Hmm, maybe that would work. I'll try it out. Thanks!

**Comment by firasdib** [comment]
I think it worked out very well, thanks @working-name.

**Comment by firasdib** [comment]
This has been merged, will be pushed live in a couple of days.

**Comment by CarlitoGil** [comment]
> Import/export unit tests. XML/JSON and other formats is fine.

Hi. Could import/export be added to Unit Tests, please?
