### ISSUE TITLE
Mouse selection seems to be broken

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#1091]
## Bug Description
Can't select characters in input area, it works in regex editor.

### Reproduction steps
drag-select some text in input

### Expected Outcome
:)

### Browser
Chrome 71.0.3578.98 (Official Build) (64-bit)

### OS
Windows 10

**Comment by firasdib** [comment]
duplicate of https://github.com/firasdib/Regex101/issues/1085
