### ISSUE TITLE
Account page redesign

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#1092]
The current iteration of the account system has been around for a while now, and is due for a revamp. Initially there were no requirements, but has since grown more and more.

The current features supported are:

- Make a regex private
- Lock a regex
- Favorite a regex
- Add tags to entries and filter
- Keep track of everything you've submitted (through different categories)
- Add a descriptive title to your entries' and see this title in the regex editor (don't like the way this looks atm)
- Delete entries (no need to save the delete code)
- Adjust tags/title immediately in the save modal in the regex editor

Are there any features you think are missing? Should any of the existing features be removed?

Please give me your thoughts and ideas, and together we might be able to make something nicer.

**Comment by TWiStErRob** [comment]
Don't forget quiz progress and submissions. Library?

**Comment by firasdib** [comment]
@TWiStErRob That is true. Should you maintain a full history for each task? Just a few? Only the unique ones?  I don't believe we can save all quiz entries, as there can be 100s for each task, and need some way to restrict it. Be it unique, max number, whatever.

Library entries are already stored in there. Or was there something else you had in mind?

**Comment by Zarthus** [comment]
A quiz task would only be a few bytes in space, no? I don't think saving
all attempts is unreasonable unless you don't already have a pagination
system in your backend + frontend (which you seem to have due to libraries)

**Comment by firasdib** [comment]
Its unwieldily for the user. How are you going to navigate and find anything meaningful in 100 entries of regex...?

**Comment by TWiStErRob** [comment]
I think last successful and current field value would be enough.

**Comment by firasdib** [comment]
@TWiStErRob These values are already available in the quiz.

**Comment by TWiStErRob** [comment]
Just verified, true, although I can't access last success, I only see how long it was. The intent of my comment was to amend the "current features" list though.

**Comment by firasdib** [comment]
@TWiStErRob You see the "best" pattern, as well as the latest. But there is no full history of submissions, which was what I thought you meant.
