### ISSUE TITLE
There are some differences between regex101's ECMAScript mode and native browser regex matching

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1093]
## Bug Description
The [FAQ says](https://github.com/firasdib/Regex101/wiki/FAQ#how-close-does-regex101-emulates-the-engines) that "For **JavaScript**, regex101 uses the browser's regex engine, so you may see different results on different browsers for the same test case." However, some differences between regex101 and native browser regex are apparent.

Also note there is a typo in the FAQ article: "How close does regex101 **emulates** the engines?" It should say "emulate".

### Reproduction steps
Put a quantifier on an assertion: `(?=hi){1}` or `\b{1}` or `${1}`  
Under the browsers I've tested (Firefox and Chrome), native JavaScript accepts this and the assertion works normally. This is despite the fact that in the official ECMAScript spec, quantifiers are not allowed on assertions.

If a minimum of zero is used, the assertion is completely ignored, even if the quantifier has a nonzero maximum. For example, `(?=(hi)){0,1}` and `(?=(hi))?` are both ignored, and do not capture `hi` even if it present.

PCRE2 (and new enough versions of PCRE) also allow this construct. Like JavaScript, any quantifier higher than 1 acts like 1. Unlike JavaScript, it will backtrack to change the number of matches from 1 to 0 (or vice versa for lazy quantifiers) in order to make the subsequent expression match, making it actually useful. This is also unlike PCRE (including as emulated by regex101), which does not accept quantifiers after assertions under any circumstances.

I was going to say that `^(?=(a))?\1b` in PCRE acts like `^(?:(?=(a)))?\1b` does in browser-native JavaScript, i.e. matching "ab", but bizarrely, in Firefox and Chrome JavaScript the latter regex does not match. I have no idea why. This bug does, however, show that regex101 is doing something different in its JavaScript mode than in its PCRE mode, because it also matches "ab" in PCRE mode but not in JavaScript mode.

### Expected Outcome
If regex101 is using the native browser JavaScript to execute regexes in ECMAScript/JavaScript mode, it should behave exactly as the browser does, and allow quantifiers on assertions.

For this reason I suspect that regex101 is using PCRE to pre-parse a regex (to find errors and show information in the "explanation" pane) even in JavaScript mode. If there is some way to make an exception for assertions on quantifiers, or use a later version of PCRE that supports them, this would make the JavaScript mode more faithful. (And I suspect this is very much possible, because I just noticed that under the latest version of Chrome, variable-length lookbehind can be used in JavaScript mode in regex101.)

### Browser
Firefox ESR 52.9.0
Firefox 64.0
Chrome 49.0
Chrome 71.0.3578.98

**Comment by firasdib** [comment]
> Also note there is a typo in the FAQ article: "How close does regex101 emulates the engines?" It should say "emulate".

Fixed.

> This is despite the fact that in the official ECMAScript spec, quantifiers are not allowed on assertions.

I think this says it all, tbh. PCRE added support for it just to stay compatible with Perl, but they do nothing (they are ignored). For that reason, I have decided to disallow quantifiers on assertions.

> This bug does, however, show that regex101 is doing something different in its JavaScript mode than in its PCRE mode, because it also matches "ab" in PCRE mode but not in JavaScript mode.

Yes, the PCRE engine is run when you select the PCRE flavor, and when you select ECMAScript, you run the built in regex engine in your browser.

> If regex101 is using the native browser JavaScript to execute regexes in ECMAScript/JavaScript mode, it should behave exactly as the browser does, and allow quantifiers on assertions.

If this does not follow the specification, I have to feature test and detect which browsers do or don't. I don't think its worth it, and generally, you should never go out of spec with your regexes -- especially if they are used on the web. More users will add quantifiers thinking they do something else on assertions, than those who know what they are doing.

> For this reason I suspect that regex101 is using PCRE to pre-parse a regex (to find errors and show information in the "explanation" pane) even in JavaScript mode.

Incorrect. They are independent parsers.

**Comment by Davidebyzero** [comment]
FWIW, there are two legitimate reasons for using quantifiers on assertions in ECMAScript regexes:

1. For constructing quine-type regexes (regexes that match themselves, or don't match themselves, or things of that ilk). I actually did this in some of my earlier solutions to Quine on [Regex Golf](https://alf.nu/RegexGolf).
2. For temporarily disabling an assertion in the course of editing a regex (so that you can avoid deleting it entirely) thereby making it easier to re-enable it later. Otherwise you'd need to paste it back into the regex at the correct position.

> but they do nothing (they are ignored)

Well that's not true. As described above, in the latest versions of PCRE and PCRE2 they work as they should. `(?=lookahead)?` first tries evaluating the lookahead, and if the rest of the expression fails to match, backtracks and tries skipping the lookahead. `(?=lookahead)??` first tries skipping it and then tries evaluating it. Of course this will only make a difference if the lookahead captured something. If the lookahead doesn't do any capturing, `?` and `??` will be exactly the same as deleting it (except potentially slower).

> Incorrect. They are independent parsers.

Thanks, that is good to know.

**Comment by Davidebyzero** [comment]
> Fixed.

You fixed the index entry, but the heading itself still says "emulates".

**Comment by firasdib** [comment]
Fixed x2

**Comment by L5eoneill** [comment]
Another issue is that IE (11/Edge) doesn't allow lookbehinds, but testing on your site doesn't reveal that fact (no errors in console). Wish I had a way to test expressions that guarantees they'll work in IE!

**Comment by Doqnach** [comment]
Have you tried using the site in IE11 and Edge, and trying that way? The website uses feature detection to see what is supported for the JS flavor in your browser, so using the website in IE11 will not use any features not supported by it.
