### ISSUE TITLE
Substitution wrong when using \K in lookahead

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1094]
## Bug Description
Substitution is inserting extra characters when \K is in a lookahead

### Reproduction steps
https://regex101.com/r/JrTZTc/1/ (enable subsitution)

### Expected Outcome
I have no idea :P

### Browser
Waterfox 56.2.5

### OS
Arch Linux, no version

**Comment by firasdib** [comment]
Fixed. Thanks for the report.
