### ISSUE TITLE
Quiz tasks involving replacement are scored 2 less than their length in characters

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1095]
## Bug Description
All tasks involving only matching/capturing are scored by their exact length, including delimiters, flags/modifiers, and the regex itself. However, all tasks involving replacement are scored 2 less than this value.

### Reproduction steps
Count the characters in the solution string shown in your **TASK STATISTICS** for any quiz task. Compare this with the **N** in the text "Your shortest solution thus far is **N** characters long." If the task is a matching/capturing task, N will be its exact length; if it's a replacement task, N will be 2 less than its exact length.

For example:

The shortest solution for task #(1)[], a matching task, is 11 characters long, and says "Your shortest solution thus far is **11** characters long. The overall shortest solution is **11** characters long."

The shortest solution for task #(2)[], a replacement task, is actually 11 characters long, but what is shown is "Your shortest solution thus far is **9** characters long. The overall shortest solution is **9** characters long."

The same applies to all the others.

**Comment by firasdib** [comment]
I don't include the `s` and one of the delimiters when calculating substitution length.
