### ISSUE TITLE
Task 7 (IP) doesn't always find capture groups

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1097]
### Task
Task 7: Validate an IP

### Bug Description

The IP task didn't notice I was using a capture group.

### Reproduction steps

Use my solution, which I'm not going to post here :)

### Expected Outcome
Add e.g. 111.27.0.244 to test 132

### Browser
Waterfox 56.2.5

### OS
Arch Linux

**Comment by firasdib** [comment]
Thanks Tim, fixed.
