### ISSUE TITLE
Quiz task 28: aaabbbccc - Description insufficient

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1098]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
28: aaabbbccc

### Bug Description
The description in this task implies, with its examples, that you need to match triplets of repeated characters, like `mmqqjj`, `iiizzz222`, `%%%%~~~~wwww`, etc., so that is the problem I initially solved. The test case errors then made it look likely that the task is actually to match any number of repeated characters, even just one. And that fact that my subsequent solution passed, which was to this problem instead of the triplet one, strongly suggests that this really is the task that is tested.

The description could also be understood to be technically incorrect. It says "Match only those strings which have an **equal amount of each character**, in order." But my solution accepts strings like `aaaabbbbccccaaaa`, and this solution was accepted. I have no problem with that, but the description should be edited to make it clear that it's the length of each run of identical characters that needs to be equal, not the total number of each character present in the string.

### Reproduction steps
Complete tasks 1-27, and then work on solving 28, using its own description as your guide. The test cases behave differently than would be expected.

### Expected Outcome
The description should give a clear idea of what the task is supposed to be, and it does not.

Please add some examples to the description to make it clear that there can be any number of repeated characters, not just 3. Currently, every single example given is of a triplet, until you actually submit a solution and start to see test errors.

**Comment by firasdib** [comment]
Do you have any suggestions for how it can be improved?

**Comment by Davidebyzero** [comment]
Here's a suggestion:

> Match only strings in which every character has an run of adjacent repeats of identical length. For example, match `abc` and `wwxxyyzzww` and `bbbaaa`, but not `aab` or `xyyz` or `foof`. The string length is arbitrary, which means you also need to match `aaaabbbbcccc`, `hhiiffggeecchhdd`, etc.

**Comment by firasdib** [comment]
Fixed. Will push soon.
