### ISSUE TITLE
Server allows viewing scores of current unsolved task, but the quiz page doesn't

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1101]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Presumably applies to all tasks.

### Bug Description
When I hadn't yet solved task #27, I tried using the URL that returns the scores in JSON format to view them for that task. It returned a result in exactly the same format as those of tasks I'd already completed. However, restricting against viewing of scores of not-yet-reached challenges appears to be correctly enforced; when I tried to view them for #28 when I was still only on #27, it returned a result of `{"error":"You can't access this task yet (Error Id: f44af063-1f90-4353-841b-c3054eaee197)"}`.

### Reproduction steps
Try to view the scores for the task you're currently on and haven't completed yet, via the URL schema that the quiz's scripts automatically use, substituting the task number in that URL with the one you're currently on.

Since I've now completed all tasks, I'm no longer able to test reproducing this unless I create a new account for testing, and I'd prefer to avoid doing that because it would pollute the score statistics.

### Expected Outcome
Since the quiz itself does not show you the scores of the other people who completed a particular task until you've completed it yourself, I would expect the server to refuse returning those scores even when directly asked via HTTP request. And it does do this refusal for future tasks, but not for the current one.

**Comment by firasdib** [comment]
Thanks, fixed.
