### ISSUE TITLE
Some of the new debugger hotkeys do not work as documented

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1102]
## Bug Description
In Firefox ESR 52.9.0 and Chrome 49.0 (the last versions that support Windows XP), most of the new hotkeys in the regex101 debugger work nicely, but `+` and `-` have no effect. Instead, `Insert` decreases the step range, `Delete` is another synonym for `→` and `.` (it seeks forward one step), and there seems to be no key at all that increases the step range.

In the latest versions of Firefox (64.0) and Chrome (71.0) under Windows 7 (edit: also under Linux), Numpad- and Numpad+ do work to decrease and increase the step range, and the `-` key (`-_` key) to the right of the `0` key works to decrease the step range, but the `⩲` key to the right of that does not work to increase the step range, even when Shift is held. Insert and Delete have the same buggy bindings as described above.

### Reproduction steps
1. Open https://regex101.com/
2. Put in any regex + input string combination that takes more than 50 steps to complete
3. Enter the debugger
4. Click the "Available keyboard shortcuts" link to review the shortcuts, then try all of those shortcuts, as well as other keys that would be expected to have bindings.

### Expected Outcome
Both the NumPad- and `-_` key should act as `-`.  
Both the NumPad+ and `⩲` key should act as `+`, with the latter working even without Shift being held.

Also, it would be nice for Home, End, PageUp, and PageDown to have sensible bindings. Not having the keys on your own keyboard should not be an impediment to implementing them as hotkeys in your software. Other people can test the keys and report a bug if they do not work as documented. These keys are within very easy reach on my keyboard and it would be quite convenient to be able to use them.

### Browser
Firefox ESR 52.9.0
Firefox 64.0
Chrome 49.0
Chrome 71.0.3578.98

### OS
Windows XP 64-bit
Windows 7 64-bit
Linux (recent version of ArchLinux)

**Comment by firasdib** [comment]
@TWiStErRob Do you have a PC to verify this? It works as expected on my Mac.

**Comment by Doqnach** [comment]
You can try https://www.microsoft.com/en-us/download/details.aspx?id=11575 with VirtualBox to test older Windows versions?

**Comment by Ouims** [comment]
Everything works for me as expected, what's true though is that some others keys that are not listed can also be used to do stuff, like insert and suppr, probably more.

@Davidebyzero can you triple check that stuff listed are not working for you? it's about keypress only, can't use shift+key to get a + i think, however, for people with no numpad, this is not going to work @firasdib .

**Comment by Davidebyzero** [comment]
In the latest version of Firefox (84.0.1), I am still experiencing the exact same behavior as described in my filed **Bug Description** as having happened under Firefox 64.0.

That is to say, every documented hotkey works, but "Increase step range" can only be done via NumPad+ not the `⩲` key (with or without Shift). And those weird `Insert` and `Delete` buggy bindings, for "Decrease step range" and "Seek one step forwards" respectively, still happen.

**Comment by Ouims** [comment]
Right well I'm using chrome. 
The += key is not supposed to work I think, can you clarify @firasdib ?

So I think there's no issue except that others keys such as insert and delete can be used as well which looks like a bug.

Ah also, there is also the tab key that can be used to browse the element in the background for ex the paypal url to donate, I think that's a bug

**Comment by TWiStErRob** [comment]
*Oops only a year late...*
Windows 10 + Chrome 87.
All documented bindings work when using Numpad.
`-_` works without shift only, and `+=` never works

This is with US keyboard layout, **mind you that other languages have different keys**. For example my [native Hungarian one](https://en.wikipedia.org/wiki/QWERTZ#Hungary) has `+` only at `shift+3` and `-` only next to the right shift, ignoring numpad of course. This means that I can only use `-` because `shift+3` doesn't do anything.

**Comment by firasdib** [comment]
I've rewritten the code that handles this, and it should now work as expected. Will be live in a few days.
