### ISSUE TITLE
Please provide a way of copying the current regex to the clipboard with delimiters + substitution + flags

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1103]
## Feature
regex101.com already has the very nice feature of allowing a full regex with delimiters + substitution + flags to be *pasted* in, but as far as I can tell there is no way to *copy* the regex in this format.

There should of course be a button under "Tools" to do this, but having a hotkey as well would be nice. I would suggest Ctrl+Alt+C and/or Ctrl+Alt+Insert.

A slightly less direct but also acceptable feature would be to instead have a button under "Tools" that opens a pop-up dialog showing the full regex with delimiters + substitution + flags, which could then easily be manually copied into the clipboard. (The debugger *almost* already provides this feature, but it omits the substitution portion, and there's also a delay after clicking "Regex Debugger" while it calculates the debugging info, inappropriate for times when I just want to copy the full regex string. The "Code Generator" also *almost* provides this feature, but there's no language provided where the regex is just printed in the same standard format of s/pattern/substitution/flags – in all the languages, the substitution is in a separate line).

**Comment by TWiStErRob** [comment]
+1 for a "raw" code generator

**Comment by TWiStErRob** [comment]
potentially related: https://github.com/firasdib/Regex101/issues/272

**Comment by firasdib** [comment]
@TWiStErRob I think you're on the right track.

We should write a sed code gen.

@Davidebyzero you up for the task?

**Comment by Davidebyzero** [comment]
> We should write a sed code gen.
> 
> @Davidebyzero you up for the task?

I'm not personally interested in a sed code gen (would be more interested in a raw code gen, and perl one-liner code gen), but if it would help you out I could get on it. What language are the code gens written in, and would I have the already-implemented ones as a template to work from? What should it do for features not supported by sed? (Ideally there should be a "sed" mode so that this isn't an issue.)

**Comment by Doqnach** [comment]
@Davidebyzero https://github.com/firasdib/Regex101/wiki/Writing-a-Code-Generator

**Comment by Davidebyzero** [comment]
> @Davidebyzero https://github.com/firasdib/Regex101/wiki/Writing-a-Code-Generator

Okay, but where do I put it so that regex101 sees it and includes it in the code gen menu?

Keep in mind I've barely ever touched JavaScript. I mainly program in native code.

**Comment by Davidebyzero** [comment]
Well that's no fun. So there's no way to test it on regex101?

**Comment by Ouims** [comment]
Bump, unrelated to sed. we need a way to copy the raw delimiter+exp+modifiers.

This has to be doable in an nice way @firasdib :

![r101](https://user-images.githubusercontent.com/18450877/103482139-483dfd80-4ddf-11eb-9f22-8085b7334c57.png)

**Comment by firasdib** [comment]
Its not a bad idea @Ouims, but I feel the flags and that button interrupt eachother and don't look very intuitive. I don't see a better placement for it though..

**Comment by firasdib** [comment]
I have something in the works for this, might come live soon.
