### ISSUE TITLE
Loophole in Task 11: Validate Floating Point Numbers

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1104]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 11: Validate Floating Point Numbers

### Bug Description
Solutions that match strings in which the exponent has a decimal point, or consists only of a decimal point, are not rejected by the quiz.

### Reproduction steps
Construct a regex that matches the following strings in addition to valid floating point numbers:  
`-1.234e-5.67`  
`5.555e87.6`  
`+3.14e.15`  
`2.718e+.2`  
`1.61e8.`  
`7.142e.`
Such a regex passes the quiz's tests.

### Expected Outcome
Since a regex that accepts such solutions is shorter than one that doesn't, it allows beating the best score with an invalid solution. Thus the test cases should reject such a regex, and any solutions currently in the scoreboard that do this should be deleted.

**Comment by firasdib** [comment]
Thanks, fixed.
