### ISSUE TITLE
ECMAScript named capture groups

### ISSUE THREAD

**Issue by friendlyanon** [firasdib/Regex101#1106]
## Feature
[ECMAScript named capture groups are stage 4](https://github.com/tc39/proposal-regexp-named-groups) and are being shipped by major vendors in stable releases.

**Comment by firasdib** [comment]
This is supported: https://regex101.com/r/JsC2P9/1

**Comment by friendlyanon** [comment]
```
All the errors detected are listed below, from left to right, as they appear in the pattern.
? The preceding token is not quantifiable
```

**Comment by firasdib** [comment]
get a newer browser

**Comment by TWiStErRob** [comment]
Confirmed working in Chrome 71.0.3578.98 (Official Build) (64-bit) both on regex101 and console:
![image](https://user-images.githubusercontent.com/2906988/51360943-a3c53280-1ac5-11e9-8612-315ac5f86de6.png)
