### ISSUE TITLE
Task 27 tests allow imprecise solutions

### ISSUE THREAD

**Issue by jay-tea** [firasdib/Regex101#1108]
### Task
Task 27 Shorten IPv6

### Bug Description

Hey Lindrian, I posted about this along with an updated set of tests on IRC, but I know you like keeping track of these issues on here ;)

### Expected Outcome
`a:a:a:a:a:a:00:001` shouldn't become `a:a:a:a:a:a::1`, etc.

**Comment by Davidebyzero** [comment]
> `a:a:a:a:a:a:00:001` shouldn't become `a:a:a:a:a:a::1`, etc.

What's wrong with that? The task says:

> Given an **unshortened** IPv6 address, return the shortened version of it.

But your example is taking an already partially-shortened IPv6 address and doing something incorrect with it. This shouldn't matter, right? That input was not an **unshortened** IPv6 and thus should be irrelevant to the task.

**Comment by firasdib** [comment]
I can't remember if I fixed this. Can you send me the info again?

**Comment by Davidebyzero** [comment]
This was never properly fixed. jayea's solution was the same length before and after this incomplete fix. See Issue #1229: Bug 1.
