### ISSUE TITLE
The /A flag is incorrectly documented in the quick reference

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1109]
## Bug Description
In the **Flags/Modifiers** page of the regex101 quick reference, the /A flag is incorrectly documented.

`A` The pattern is forced to become anchored, equal to a ^.

However, it is not equal to a `^`. It is equivalent to a `\G` at the start of the pattern applying to all branches.

### Reproduction steps
Test any pattern in regex101 with:

1. `\G` at the start of the pattern such that it applies to all branches, and the /A flag unset
2. No `\G`, and the /A flag set

The behavior is equivalent. For example, as a simple test:

1. Use `s/\d/g` as the pattern and `123a456` as the input. Every character except `a` will be matched.
2. Use `s/^\d/g` as the pattern and `123a456` as the input. Only `1` will be matched.
3. Use `s/\G\d/g` as the pattern and `123a456` as the input. Only `1`, `2`, and `3` will be matched.
4. Use `s/\d/gA` as the pattern and `123a456` as the input. Only `1`, `2`, and `3` will be matched.

Clearly, /A is not the same as `^`, but instead is the same as `\G`.

**Comment by working-name** [comment]
Thanks! Updated the quickref

**Comment by firasdib** [comment]
Fixed. Will push soon.
