### ISSUE TITLE
Keep invalid solutions even after invalidation

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#1110]
### Task
all/any

### Bug Description
As far as I know, when issues are found with a task some migration steps are done to invalidate old solutions that violate that issue.

### Reproduction steps
 * I had an accepted solution for Task 9 (email)
 * some time elapsed, people reported issues/@firasdib modified it
 * my solution was not valid any more

### Actual Outcome
Solution disappeared without a trace:
![image](https://user-images.githubusercontent.com/2906988/51442805-946a0300-1cd8-11e9-928a-0db3675944cc.png)
Notice that tasks before AND after are open and accessible.

### Expected Outcome
Solution visible when I open the task (as with other tasks that were not invalidated), so I can edit from a baseline (show the test failure?) and fix the issue, instead of having to re-do the whole thing again:
![image](https://user-images.githubusercontent.com/2906988/51442818-bf545700-1cd8-11e9-8d37-e04cfce0caee.png)
This is particularly annoying and discouraging for email task, which was by far the longest task so far.

### Browser
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### OS
Windows 10 latest

**Comment by firasdib** [comment]
This is a manual process for me, I'll try to find a way to prevent loss of data like this.
