### ISSUE TITLE
support regex as if contained in javascript quoted string

### ISSUE THREAD

**Issue by msftrncs** [firasdib/Regex101#1112]
## Feature

I think it might help some if the regex input box supported expressions that were escaped as if they were in a JavaScript quoted string, where the `\` requires escaping.

Another possibility might be patterns that are escaped from XML, where `&`, `<` and `>` are escaped.

Specifically I am working on textmate syntaxes, and they are either contained in JSON, XML (plist) or sometimes CSON.

**Comment by Doqnach** [comment]
This suggestion has come up before but it is not something that seems very feasible for the website to do, since many tools have their own form of doing escapes. Writing a PCRE which you will use in PHP or in sed would require very different escaping methods. Also a difference in many languages between single quoted and double quoted strings (let alone the many other methods out there like unescaped raw strings etc).

Similar to #1038 #1019 #979

**Comment by msftrncs** [comment]
I am just thinking that the website is already escaping (requires escaping) `/` when the delimiter is `/` so why can it not switch to `\` being required to be escaped when the delimiter is `"`?  

Also, `"` would also require delimiting, of course.

**Comment by working-name** [comment]
Please see https://github.com/firasdib/Regex101/issues/1019#issuecomment-410521370

**Comment by msftrncs** [comment]
So you are saying I should look for a better website that suits my need (Ruby Regex inside JSON quoted strings) and then send my donations there?   Otherwise the comment in 1019 has no value to my request here.

example:
```json
{
	"begin": "\\[",
	"end": "(])(?=(\\.(?!\\.)|::))|(?>[^\\s\\p{L},])",
}
```

**Comment by working-name** [comment]
No, I don't think I should have a say in what website you use and/or financially support. I'm only attempting to point out that the author of the site has considered similar requests in the past and feels that the site should remain neutral and not try to handle all meta character escape requirements of each language and variations thereof.

What I would do is make my own regex converter script or have two more regex101.com tabs open that handle escaping and reversal of the same. If you need help with that, drop by #regex on Freenode, or hit live help on the left sidebar of the site.

**Comment by msftrncs** [comment]
What I am doing now, when the need arises:

PowerShell (and using the \` separator)
```PowerShell
@'
(?=@?(['\\x{2018}-\\x{201B}\"\\x{201C}-\\x{201E}])(?:(?<!@\\g<1>)|\\s*$))
'@ -replace '\\\\', '\' -replace '`', '\`'  # adapt a JSON regex for regex101.com

@'
(?=@?(['\x{2018}-\x{201B}\"\x{201C}-\x{201E}])(?:(?<!@\g<1>)|\s*$))
'@ -replace '\\`', '`' -replace '\\(?!")', '\\'  #adapt the regex101.com regex back for JSON
```

**Comment by GitHub-Mike** [comment]
My modest proposal would be an additional point in the quick reference section, which lists the necessary characters to be escaped.

I think that would be a useful addition.
