### ISSUE TITLE
golang Code Generator improvement request

### ISSUE THREAD

**Issue by kzhui125** [firasdib/Regex101#1113]
<img width="647" alt="123" src="https://user-images.githubusercontent.com/11925432/51777964-7ff39380-213a-11e9-81f1-01627ab23051.png">

I see the output is 12xxx56, so I use in my go code, and it's not correct.

<img width="557" alt="456" src="https://user-images.githubusercontent.com/11925432/51778029-bb8e5d80-213a-11e9-980e-46a18e057ca2.png">

see https://github.com/golang/go/issues/29936

**Comment by working-name** [comment]
//**TODO**: change golang generator to output replacement group references as `${1}` rather than `$1` to avoid confusion with variables should anything else exist after the capture group id.

**Comment by firasdib** [comment]
Fixed
