### ISSUE TITLE
Newlines within an inline comment cause incorrect syntax highlighting

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1114]
## Bug Description
Inline comments of the form `(?#...)` have syntax highlighting applied to them by regex101 – they're shown in gray italics. But if a newline is inside such a comment, only the first line will have the syntax highlighting, and subsequent line(s) will just be in a plain non-italic black text.

### Reproduction steps
https://regex101.com/r/DBvKtf/1

### Expected Outcome
The entire comment, as recognized by the PCRE parser, should be syntax-highlighted consistently.

**Comment by firasdib** [comment]
Fixed. Will push soon.
