### ISSUE TITLE
negative lookbehind not working ?

### ISSUE THREAD

**Issue by ioulai** [firasdib/Regex101#1118]
## Bug Description
This expression (?<!(\s|.)) should be a negative lookbehind but do not work 
return this -> ? The preceding token is not quantifiable

https://regex101.com/r/Z9DJnx/6/tests

### Expected Outcome
negative lookbehind

### Browser
Firefox developper 66.0b4 (64 bit)

**Comment by ioulai** [comment]
understood !
i didn't know the feature was new to JS 
thanks for the advice

**Comment by ioulai** [comment]
![regexp](https://user-images.githubusercontent.com/26062183/52344231-83c8c500-2a1a-11e9-874d-89070bec0e61.PNG)
i found these information on console (F12) which could be useful !

**Comment by working-name** [comment]
Yup that’s still the site issuing the warnings, not your browser.

**Comment by Doqnach** [comment]
Maybe what he means is that he would have liked to have seen those warnings somewhere in the UI itself?

Perhaps some warning indicator somewhere for the JS flavour, with a tooltip containing those types of messages, if they occur.

**Comment by ioulai** [comment]
exactly ! 
it'll be helpful to have those warnings directly in the UI
and avoid usless issues
