### ISSUE TITLE
Engine error in recursion

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1119]
## Bug Description
I get the error message "recursive call could loop indefinitely - offset: 9"

### Reproduction steps
Works: https://regex101.com/r/6DmYlL/3/
Doesn't work: https://regex101.com/r/6DmYlL/4/

### Expected Outcome
The second example should also work.

### Browser
Waterfox 56.2.6

### OS
Arch Linux

**Comment by Timvde** [comment]
Ouims tested this for me in mIRC, and it has the same behaviour. So it might be a PCRE bug.

**Comment by firasdib** [comment]
This is reported directly by the engine, as it cannot be precomputed (without great effort). Might be an engine bug. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by firasdib** [comment]
Has anyone filed a bug with PCRE? If so, we can close this.

**Comment by Ouims** [comment]
don't think so, going to do that.

**Comment by Ouims** [comment]
There: https://bugs.exim.org/show_bug.cgi?id=2682

**Comment by firasdib** [comment]
Since the website now runs on PCRE2 I will consider this resolved.
