### ISSUE TITLE
Missing tests in Task 28

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1121]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 28: aaabbbccc

### Bug Description
The task accepts a regex that doesn't match `aa`, `aaa`... Test 1 tests for `a` as an example of a substring that's only repeated once, but not longer strings.

### Reproduction steps
See my solution ;)

### Expected Outcome
Add tests for multiple repetitions of a single character, like `aa`, `aaa`...

### Browser
Waterfox 56.2.7

### OS
Arch Linux

**Comment by Davidebyzero** [comment]
This is a subset of #1261 and was fixed when it was fixed.
