### ISSUE TITLE
CORS error on entity creation

### ISSUE THREAD

**Issue by SmelayaPanda** [firasdib/Regex101#1122]
## Bug Description
When I try to use public method for entity creation with JS on client side I receive CORS error:
`Access to XMLHttpRequest at 'https://regex101.com/api/regex' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
### Reproduction steps
*API call example used

### Expected Outcome
Success/error response

### Browser
Google Chrome 71.0.3578.98 (Official Build) (64-bit)
### OS
MacOS Mojave 10.14.3

**Comment by firasdib** [comment]
Try it now. Added CORS support.
