### ISSUE TITLE
Test string does not recognize carriage returns

### ISSUE THREAD

**Issue by ash-m** [firasdib/Regex101#1123]
## Bug Description
The test string cannot effectively contain a carriage return. Entering one into the test input is immediately converted to a line feed. If you check a regex `/\n/` you will see a match which says to me the input is converted. The options don't seem to have a feature to turn that off in the event you're testing something containing  `CRLF` formatting; there is a way to display the newlines as paragraph marks though.

### Use Case
I view [regex101.com](https://regex101.com) as a learning tool and sort of logic debugger. I was trying to run a sed expression on a text file to add a space after characters at the end of a line which did not already have one. When attempting matches on the regex `/([^ ])\n/`, the pattern matched everyline, because `\r` is not ` `. Of course, I had forgotten they would even exist in the document. You can make the argument that is simply a bad regex for my goal, but that's what [regex101.com](https://regex101.com) is for in my opinion; to discover the error of thy ways.

### Reproduction steps
Try entering a carriage return, for example inputting the unicode directly as `\x000D` into the test area and check using the regex `/\r/`.

### Expected Outcome
Pattern `/\r/` contains 1 match.

### Browser
Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

### OS
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by working-name** [comment]
Please see https://github.com/firasdib/Regex101/issues/442

**Comment by firasdib** [comment]
This is a limitation of code mirror arm. Follow #442 for future updates
