### ISSUE TITLE
highlight substitution text (and alternating colors)

### ISSUE THREAD

**Issue by 4evermaat** [firasdib/Regex101#1124]
Any particular reason not to have the substitution have color coded highlighting that matches the group color code from original regex search?

As a non-programmer, it seemed weird that you did not extend color coding of the search to the substitution item so readers could see exactly where the substitutions are.

See #647

I am saying this from a layperson's perspective; someone who is just beginning to get comfortable with regex.   

---

BTW, I think you have a wonderful tool here.

**Comment by firasdib** [comment]
You want to see where the replaced text was put? With `s/b/d/` used on `abc`, you'd want the `d` to be highlighted in `adc`?

**Comment by 4evermaat** [comment]
@firasdib something like that.  And there can also be mouseover text, showing the group # that was substituted, and the occurrence count (e.g. if it was the 5th replacement, then it could say Occurence #5).   So each group or portion of the replacement can have its own color.  Similar to how the regex is done.

Does this really use a lot of overhead?  I guess you could disable it with a checkbox.

**Comment by firasdib** [comment]
Im just trying to think if it makes sense. Im not convinced it does. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by liOnux33** [comment]
Hello Firas Dib,
Great tool !
But I were surprised not to see the replaced strings in highlighting, when I used subsitution the first time.
With very long regular expressions (severals groups), results could be easier to check if they are highlighted.
Thanks for your job :-)
Best regards

**Comment by Ouims** [comment]
It does make sense @firasdib ^_^

**Comment by firasdib** [comment]
The biggest issue here is that I use the native replace functionality of the language thats performing the regex matching, and those functions just return the result, which is what is displayed on the screen. I would need to know the positions of each replacement in order to know what to highlight, which I don't. It could potentially be inferred by the match result, but seeing as how replacement strings can be quite complex, this is a non-trivial task. Because of that, I don't think this is feasible. Sorry.

**Comment by 4evermaat** [comment]
@firasdib   I ended up using [TextCrawler Pro](https://www.digitalvolcano.co.uk/textcrawler.html), which is windows based and allows command line search from a saved search where multiple manipulations can be done in a defined sequence.   This was ideal for a file that is updated daily, and then needs to be manipulated to ensure it is formatted properly.

It has a RegEx test feature where you can play with regex and see exactly how it will look on the text.  4 tabs:  
1. `the matches`
2. `the matches highlighted within original text`
3. `replacement highlighted` (within original text)
4. original text with replacement (no highlighting)

I use 2 and 3 most often to see how the regex formula is working.

![textcrawler RegEx test expressions sample](https://user-images.githubusercontent.com/830306/144711566-7d4eeecc-acc4-4dce-9b62-f511104b06ea.png)


But that doesn't mean your regex doesn't have value.  It is web-based and is good.  I just wanted to show how highlighting can help.
