### ISSUE TITLE
Wrong data in Group capture

### ISSUE THREAD

**Issue by radumro** [firasdib/Regex101#1125]
## Bug Description
The first capture group does not contain all the data

### Reproduction steps
regex: ^(.)+\s([a-z0-9]{7,10})\s([a-z0-9]{17})\s?([0-9]{1})\s+([0-9\,\-]+)\s+=\s+([0-9\,\-]+)\s
flags gmi

text string 
6, IPM2_Q1-2019 DLXXXXXEAY JMZDK6W760XXXXXXX 1 -20,00 = -30,00
2, IPM2_Q1-2019 DLXXEAP JMZDK6W7A0XXXXXXX1 -10,00 = -50,00

### Expected Outcome
group 1 expected outcome:  6, IPM2_Q1-2019 
group 1 outcome: 9

### Browser
Include browser name and version
google chrome 71.0.8578.98 64bit
### OS
Include OS name and version Windows 10
![image](https://user-images.githubusercontent.com/5021095/52801739-363a0100-3087-11e9-84e6-25c161706bf8.png)

**Comment by TWiStErRob** [comment]
Nope, you get what you asked for ;)
You're asking for a group of a single character that's repeated (which returns the last match), not some characters repeated in a group:
`^(.+)\s`

**Comment by radumro** [comment]
Ok, thanks for the suggestion. but i have to ask. then in php why i get the desired resolute???

**Comment by TWiStErRob** [comment]
Hmm... do you mean in real PHP or PHP flavor on the website? Assuming real, that I don't know, others will probably chime in.

The behavior I described is learned when doing regex in Perl, but I also saw the same in Java. It was a tough facepalm when I first realized this.

**Comment by radumro** [comment]
in real php i tested the regex simulated on the website and i got the result that i wanted. so that's why i posted as a bug. but thanks for the explanation. it really makes sense

**Comment by Doqnach** [comment]
Looks to me PHP does the exact same as the website:

https://ideone.com/lxvLOx

**Comment by firasdib** [comment]
Behavior looks correct to me.
