### ISSUE TITLE
"[^]" : A case your web page does not run. May be you can fix it

### ISSUE THREAD

**Issue by Lutier2017** [firasdib/Regex101#1128]
## Bug Description
Review:  https://eloquentjavascript.net/09_regexp.html
                “GREED” paragraph and code

This part of the regular expression : "[^]*?
does not work in your web site.

### Reproduction steps
Regular expression: /\/\/.*|\/\*[^]*?\*\//g

Text to test: 
1 + /* 2 */3
x = 10;// ten!
1 /* a */+ /* b */ 1
1 /* a */+ /* b 
KKK */ 1

### Expected Outcome
1 + 3
x = 10;
1 +  1
1 +  
 1

### Browser
Chrome, Version 72.0.3626.119 (Official Build) (64-bit)

### OS
Windows 7

**Comment by Doqnach** [comment]
Seems to work just fine: https://regex101.com/r/wHeFgY/1

This only works in the javascript flavour though, not under PCRE, Python or Golang. This is not a notation that PCRE supports.
