### ISSUE TITLE
[cat]+|dog

### ISSUE THREAD

**Issue by luyunlin** [firasdib/Regex101#1130]
## Bug Description
[cat]+|dog
pattern match with cat catch dog attack
### Expected Outcome
match dog but it doesn't say it will match dog

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by Doqnach** [comment]
Working as intended: https://regex101.com/r/JzjXtE/1

Drop by the chat if you need any help on writing regex. See the webchat link on the website, or join #regex on irc.freenode.org.
