### ISSUE TITLE
JS Capturing Group Backreferences not Labeled Correctly in Lookbehinds

### ISSUE THREAD

**Issue by thatcomputerguy0101** [firasdib/Regex101#1132]
## Bug Description
Capturing groups in JS lookbehinds do not have a reversed order.

### Reproduction steps

1. Use multiple capturing groups in a lookbehind, or use a capture group reference in a lookbehind (such as in the following).
``` javascript
/(?<=\2(2nd group)\1(1st group))/
```
2. Hover over the group that contains "2nd group", which results in it being labeled 1st group
3. Note that the \2 backreference doesn't match anything, while the \1 backreference only does because it is placed in the middle.

### Expected Outcome
The group labeling order should be reversed so that the 1st group is the group that appears second, and the backreferences should reference the groups after them, not before. Evaluation in the text area works as expected.

### Browser
Chrome  72.0.3626.119

### OS
macOS Mojave 10.14.3

**Comment by TWiStErRob** [comment]
> Capturing groups in JS lookbehinds do not have a reversed order.

Why would they be reversed? The regex engine parses the string character by character left to right.

It works as expected: https://regex101.com/r/Qwr9fd/1

> Hover over the group that contains "2nd group", which results in it being labeled 1st group

Groups are counted based on the starting position of the opening parentheses `(`.

> backreferences should reference the groups after them, not before

Backreferences are referencing **back**wards, so you cannot use the backreference before the thing it is refererring to, otherwise it would be a forward reference.

> while the \1 backreference only does because it is placed in the middle.

Based on the above rules, `\1` works because it is after the first group is created (with content "2nd group").

> Note that the \2 backreference doesn't match anything

Note that `\2`, without having two capturing groups **before**, is matching `\u0002` as pointed out by the site: 
![image](https://user-images.githubusercontent.com/2906988/53922813-c6a7a800-406d-11e9-9f7c-0601e9a78f4e.png)

See https://www.regular-expressions.info/backref.html

**Comment by thatcomputerguy0101** [comment]
I have a correction to make. After looking at the [spec proposal](https://github.com/tc39/proposal-regexp-lookbehind/blob/master/README.md) (which contains some notes about the specification), I have determined that the groups are labeled in the correct order.

However, I was right about the capturing groups having to appear after their respective backreferences, described here in [the proposal](https://github.com/tc39/proposal-regexp-lookbehind/blob/master/README.md#referring-to-capture-groups), which is how the implementations in Chrome and NodeJS appear to work. As far as I understand, this ts due to the evaluation direction of lookbehinds, which is reversed from normal. This causes what would normally be backwards to become forwards, so the direction of evaluated items, such as backreferences, needs to be reversed.

As a quick demo, notice that the first line at https://regex101.com/r/SpX5KE/1 matches, while the second doesn't. The first line is the actual implantation expectation, while the second line is what you get if you don't reverse the lookbehinds.

**Comment by firasdib** [comment]
So the issue seems to be that regex101 is labeling the `\2` incorrectly, or is there something else I'm missing?

This does however make for an interesting challenge. How should the explanation be worded? Since its all reversed.

**Comment by thatcomputerguy0101** [comment]
That is correct, since in my second demo `\2` matches the second group, while `\1` matches an empty string since the group was parsed but not matched yet. As a side note, even if the group hasn't been reached yet, backrefrences match an empty string if the group exists but hasn't been matched, not an octal escape. The octal escape only occurs if there are less total groups than the number for the escape.

**Comment by firasdib** [comment]
@thatcomputerguy0101 Thank you for the information, I did not know that. 

I was under the impression that they were octal escapes, if the backref was not yet set. But if I understood your correctly, then its the total amount of backrefs (wherever they are defined) that matters.

That should be an easy fix then. I was a bit afraid that the reversed order of the lookbehind would be a pain to sort out, as it was something I had never considered.

**Comment by firasdib** [comment]
Fixed, will be pushed soon
