### ISSUE TITLE
Regexp cant find the consecutive match

### ISSUE THREAD

**Issue by asztalosaron** [firasdib/Regex101#1133]
https://regex101.com/r/1Mjtba/1

**Comment by firasdib** [comment]
Please use an appropriate issue template and fill in the necessary information.

**Comment by TWiStErRob** [comment]
Yes, it can, if you **have** consecutive matches that the pattern is looking for: https://regex101.com/r/1Mjtba/3
It'll also work as you expect it to if you use lookarounds: https://regex101.com/r/1Mjtba/4

*If you need help with regex click "Live Help" on the left icon bar on the website to join the IRC channel (without reg).*
