### ISSUE TITLE
Option to hide left menu

### ISSUE THREAD

**Issue by VeneetReddyK** [firasdib/Regex101#1135]
## Feature
The menu which contains "Save and share", "Flavors" and "Tools". When working with regexes with long lines it is a hindrance. Usually it's not needed to be open all the time.

**Comment by firasdib** [comment]
See the settings page


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by VeneetReddyK** [comment]
Oh. That's awesome. Thanks for this great tool. 👍
