### ISSUE TITLE
Add a 'scratchpad' area to the page...

### ISSUE THREAD

**Issue by spinjector** [firasdib/Regex101#1136]
## Feature
I think it must be very common to copy & paste chunks of expressions back & forth between Regex101,  Notepad++, regex web pages, and whatever application it's being used in. I do this constantly. Today I just had the random thought that it would be nice if Regex101 had a "scratchpad" area to copy & paste bits of expressions. And it would be even awesomer if that scratchpad was saved in a cookie so it remembers the contents from session to session. See attached screenshot. 
![chrome_2019-03-21_10-49-34](https://user-images.githubusercontent.com/21039987/54761668-e50eb700-4bc8-11e9-813c-1904ace42bc3.png)

**Comment by working-name** [comment]
Have you tried [this](https://regex101.com/r/0hmzdU/1)?

**Comment by Doqnach** [comment]
To me this feels more as something for a browser extension than a thing the website should solve. It can take quite a bit of screen space so would need to be very optional and opt-in.

A "folded by default" pane under the Quick Reference would be an okay place I guess?
In PCRE you could simply use DEFINE blocks for this...

**Comment by spinjector** [comment]
Yes, a folded pane is exactly what I was thinking - under the Quick Reference section. Or perhaps in the left sidebar, under Regex Library; there's a bit more screen real estate over there.

**Comment by firasdib** [comment]
I think this is out of scope for the website to be honest.
