### ISSUE TITLE
Highlight the point of mismatch the input string

### ISSUE THREAD

**Issue by il86be** [firasdib/Regex101#1137]
Since the matching algorithm is essentially a stack machine, it should be easy to pinpoint the position of the first mismatch in the input string.

Currently the online tester just reports "Your regular expression does not match the subject string.", which is not very helpful.

**Comment by firasdib** [comment]
You can use the debugger for this. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Doqnach** [comment]
Only possible for PCRE though since the other engines don't report positions.
