### ISSUE TITLE
Task 14: Bad error message shown

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1139]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 14: spam filter

### Bug Description
A very unclear error message is shown when the filter is only matched at the beginning of the line.

### Reproduction steps
Only check for "not allowed" etc right after ^ instead of on the entire line. An error message is shown: "Are you sure you're matching the words in the task description correctly?", which can be confusing.

### Expected Outcome
A clear error message indicating that the filters should be allowed anywhere on the line

### Browser + OS
Irrelevant.

**Comment by TWiStErRob** [comment]
Task 14?

**Comment by Timvde** [comment]
I have no idea how I typed 6...
