### ISSUE TITLE
Task 8: HTML Tags -- please vote

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#1140]
It has come to my attention that this task is quite confusing, and a lot of people are getting stuck on it.

Please cast your vote.

[![](https://api.gh-polls.com/poll/01D79QGVGGCDKAMDWQMN632QSZ/Remove%20it)](https://api.gh-polls.com/poll/01D79QGVGGCDKAMDWQMN632QSZ/Remove%20it/vote)
[![](https://api.gh-polls.com/poll/01D79QGVGGCDKAMDWQMN632QSZ/Keep%20it)](https://api.gh-polls.com/poll/01D79QGVGGCDKAMDWQMN632QSZ/Keep%20it/vote)
[![](https://api.gh-polls.com/poll/01D79QGVGGCDKAMDWQMN632QSZ/Keep%20it%2C%20but%20update%20it%20%3Cplease%20specify%3E)](https://api.gh-polls.com/poll/01D79QGVGGCDKAMDWQMN632QSZ/Keep%20it%2C%20but%20update%20it%20%3Cplease%20specify%3E/vote)

**Comment by Timvde** [comment]
In the original quiz, the HTML task was task 6, before the IP task. I *think* it was meant to teach people about alternations in a slightly simpler context (maybe r00tb0y knows). So if you remove it, I think it should be replaced (and put back in front of the IP task). The task by itself is a nice and sort-of real-life example, but it's hard to communicate what you actually want to achieve. I'd first try to improve it before removing.

**Comment by TWiStErRob** [comment]
Rephrase it as "HTML cleanup"? the goal is to try to remove all HTML tag looking parts of the text for sanitizing and preventing XSS and formatting.

**Comment by Timvde** [comment]
I wouldn't want people to think regex is a good way to sanitize HTML or prevent XSS. I'm not against a rename, but I'd propose "Filter HTML" instead.

**Comment by firasdib** [comment]
Seems most people are in favor of keeping this task as well.

Again, few people have suggested any changes. But those who have seem to want me to clarify to a larger degree that this is just for learning purposes. Perhaps changing the task to "Log cleanup" or something would suffice?

**Comment by ChrisForsythe** [comment]
I just finished this one. Maybe this will help:

- The good: this helped me to learn.

- The bad: It was confusing without laid out examples of what was expected. It seemed like every time I had something working in just the editor and went back, the result wasn't happy with it because I had not thought of edge case after edge case.

If all of the rules had been laid out up front I would have probably found it to be easier to understand.

**Comment by firasdib** [comment]
This task is now optional!
