### ISSUE TITLE
Task 9: Email -- vote please

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#1141]
I personally think this quiz task is a bit tedious, and I'm unsure if it adds much benefit to the quiz as a whole. I believe it (along with task 8) deters a lot of users from the quiz.

This poll will decide the fate of task 9. Cast your vote.

[![](https://api.gh-polls.com/poll/01D79QJQ51V0CAGYDGF8K4HT8Y/Remove%20it)](https://api.gh-polls.com/poll/01D79QJQ51V0CAGYDGF8K4HT8Y/Remove%20it/vote)
[![](https://api.gh-polls.com/poll/01D79QJQ51V0CAGYDGF8K4HT8Y/Keep%20it)](https://api.gh-polls.com/poll/01D79QJQ51V0CAGYDGF8K4HT8Y/Keep%20it/vote)
[![](https://api.gh-polls.com/poll/01D79QJQ51V0CAGYDGF8K4HT8Y/Keep%20it%2C%20but%20update%20it%20%3Cplease%20specify%3E)](https://api.gh-polls.com/poll/01D79QJQ51V0CAGYDGF8K4HT8Y/Keep%20it%2C%20but%20update%20it%20%3Cplease%20specify%3E/vote)

**Comment by TWiStErRob** [comment]
"Simplified" is a lie... or at least normal assumptions fail fast (it's not RFC, granted, so it's simpler than that, but still not "simple"). My original feedback from initial run-through:
> It's really frustrating, the task descriptions make it sound really simple, and then 40 test cases each adding a new thing.

The above is based on the original state, I'm guessing you didn't change it much since then.

Upon solution you could put a link to http://emailregex.com/ to show how impossible it is to write a correct regex.

**Comment by firasdib** [comment]
The results seem to indicate a 50-50 split so far. Unfortunately, none of the people who asked me to update it has specified what to update.

@TWiStErRob Would specifying more details in the task description be helpful?

**Comment by firasdib** [comment]
The results seem to indicate a ~40-60 split so far. Unfortunately, none of the people who asked me to update it has specified what to update.

@TWiStErRob Would specifying more details in the task description be helpful?

**Comment by TWiStErRob** [comment]
Yes, clarifying what is expected, e.g. some bullet points which describe the constraints of an email address you want the solver to match. (Similar to how password constraints are listed on some sign-up forms.)

Also, I think you should halve the test case count and be a bit more lax. As far as I remember this task alone took similar effort than most before it, and got really tediously annoying. I think the goal here should be not to validate the email, but to grep a sufficiently strict one in some large corpus.

**Comment by NeverUsedID** [comment]
I'am learning Regex and at the momnent that one is a tough one

My Suggestion, make the task optional.

**Comment by firasdib** [comment]
@NeverUsedID This is a good idea. I think I will do that.

**Comment by ddrscott** [comment]
This is an extremely tedious test. Would be nice to see what valid and invalid emails addresses look like.

**Comment by firasdib** [comment]
@ddrscott I agree. I will start by making it optional. I'll update the code and database to reflect this the coming weekend, when I have some free time over.

**Comment by iago-lito** [comment]
Wops! I have voted "Remove it", but I had no intention to vote at all (just clicked the image, hoping I could find more information about the decision being made).

If you can, please consider removing my vote, or at least not taking it into account :)

**Comment by firasdib** [comment]
This task is now optional!
