### ISSUE TITLE
Line terminator(s) are \n

### ISSUE THREAD

**Issue by jgomezprada** [firasdib/Regex101#1142]
... and `\r`
::
![Screenshot - 2019-04-01 , 10_12_26](https://user-images.githubusercontent.com/26471671/55334840-ac3fcf00-545f-11e9-8b71-cb8c7401f3dd.png)

**Comment by Doqnach** [comment]
Except that CodeMirror (the library used for the fancy textarea's) does not support \r so those don't actually exist in Regex101.

See #931 #442 #257 #1075
