### ISSUE TITLE
Mismatched Parenthesis

### ISSUE THREAD

**Issue by brylee123** [firasdib/Regex101#1143]
## Bug Description
The nested brackets and parenthesis do not match up.

### Reproduction steps
An example of this is:
([([^\w])|( )])

### Expected Outcome
Internal brackets don't match up.

### Browser
Include browser name and version
Chrome Version 73.0.3683.86 (Official Build) (64-bit)

### OS
Include OS name and version
Win10

**Comment by working-name** [comment]
`(,[,],)` are all metacharacters in regex. If you want them considered literal, you need to escape them `\(`. 

What were you expecting the result to be?

**Comment by brylee123** [comment]
I was hoping to nest them, but I'm not sure if that is logically correct. I
wasn't trying to use them as literals.

**Comment by working-name** [comment]
Not sure about logic, but as far as regex goes, the `(` inside a character class is literal, it no longer represents the start of a capture group. 

I'm only guessing at this point, but is this what you meant? 
`(\[([^\w])|( )])`

I think you'd be better off if you provided a regex101.com link with your sample text as it is originally, and what it should look like or what should be matched after regex is done with it.

**Comment by Zarthus** [comment]
@brylee123
