### ISSUE TITLE
notify user of new revision

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#1145]
## Feature

Based on interaction on IRC with `re-*` users, they'll sometimes quit before being provided with an answer or revision. Per digitok, we might be able to salvage the time that was put in by "displaying a badge/tag of some kind indicating an update" (digitok) or sending a notification to the user's browser that a new version is available for that `/r/####` trunk.

Is this something feasible in terms of amount of time needed to implement?

**Comment by Doqnach** [comment]
Having a push notification for "external" updates would not be a bad feature.

https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications

**Comment by Ouims** [comment]
If this is added, please make it optional, because you might get annoyed by all the alert if you're slowly working on something and the link was shared on irc and lot of people are writing their own version.

**Comment by firasdib** [comment]
I don't think this is worth the hassle, especially considering the amount of work that is necessary to make this work.
