### ISSUE TITLE
website source code

### ISSUE THREAD

**Issue by ronh1** [firasdib/Regex101#1146]
## Feature
Did you publish the source code of the web site?

**Comment by Doqnach** [comment]
No, see:

#6 #77 #89 #806 #930 and #707

**Comment by someone77** [comment]
It's possible to purchase the application for a closed network (for a private company)?

**Comment by Zarthus** [comment]
@someone77 Regex101 is a public website, you can access it on any network (closer or public) and it supports offline mode as long as you visit it at least one when connected to the internet.

You can always donate if you'd like to contribute to the project.

**Comment by someone77** [comment]
closed network, I mean to an offline network without any connection to internet

**Comment by Zarthus** [comment]
like i mentioned, regex101 supports offline use so long as, at some point, you can be online to cache everything at least once.

**Comment by someone77** [comment]
OK, Thanks

**Comment by tacerus** [comment]
A computer without access to the internet will not be able to fetch the website for offline use either.
