### ISSUE TITLE
Python, the description of \Z is not accurate

### ISSUE THREAD

**Issue by yangshuairocks** [firasdib/Regex101#1148]
## Bug Description
On regex101 website, it describes `Python`'s `\Z` as 

> \Z asserts position at the end of the string, or before the line terminator right at the end of the string (if any)

However, the `Python`'s document describes it only as

> \Z
> Matches only at the end of the string.

Where does 

> or before the line terminator right at the end of the string (if any)

come from?

Should we remove it and make it more accurate?

**Comment by working-name** [comment]
Hi @yangshuairocks, the explanation comes from [pcre.txt](http://www.pcre.org/pcre.txt)
> The difference between \Z  and  \z  is that \Z matches before a newline at the end of the string as well as at the very end, whereas \z matches only at the end.

Behavior wise, the python flavor seems to utilize \Z correctly, essentially making it a PCRE \z. 

Therefore this is purely a typo. Will submit an updated quickef/explanation string which makes the distinction between the two and Python's own behavior.

Thanks!

**Comment by working-name** [comment]
Done. The updated quick ref will be pushed with the next site update. Thank you for your help!
