### ISSUE TITLE
Explanation API 

### ISSUE THREAD

**Issue by MinerChAI** [firasdib/Regex101#1150]
## Feature
Add ability to get explanation via API

**Comment by firasdib** [comment]
There isnt one, and there likely wont be one, due to the immense computational cost this would incur.

**Comment by MinerChAI** [comment]
Can you give the code so I can compute it on my PC then?

**Comment by firasdib** [comment]
@MinerChAI No sorry. Its not going to work out of the box for that purpose either I'm afraid.

**Comment by TWiStErRob** [comment]
Just out of curiosity: where would you want to use this automated?

**Comment by MinerChAI** [comment]
I'm making a Discord bot and I want it to have as many functions as possible (including things for devs). So when I saw these explanation i thought "Wow! My bot **must** have it"

**Comment by MinerChAI** [comment]
Well, no I have another one reason to learn selenium
