### ISSUE TITLE
Task 11 wrong solution accepted

### ISSUE THREAD

**Issue by Maximk0o** [firasdib/Regex101#1151]
## Quiz Bug
Task 11 wrong solution accepted

### Task
Task 11: Validate Floating Point Numbers

### Bug Description
My regex was accepted even though it accepts `-.`, which is wrong in my opinion

### Reproduction steps
1. Open the 11th task
2. Submit the regex (send me a private message in order to get the regex)

### Expected Outcome
It should not be accepted as it matches `-.`

### Browser
Chrome/74.0.3729.108

### OS
Win 10

**Comment by Doqnach** [comment]
Related to #1104 ?

**Comment by Maximk0o** [comment]
> Related to #1104 ?

This issue is marked as closed and now it checks the regex with just a dot. But it's similar (=

**Comment by firasdib** [comment]
Thanks for the report! I can add a test for this specific case.

**Comment by firasdib** [comment]
Fixed, thanks for the report.
