### ISSUE TITLE
Group replacement in Java generator

### ISSUE THREAD

**Issue by jacobhampel** [firasdib/Regex101#1152]
## Bug Description
The generated code for Java contains an issue if used with groups replacement.
The syntax for groups is wrong. 
It says
`"\\1";`
But it has to be
`"$1";`

### Reproduction steps
Type a regex with a group. E.g.
`(\w)`
Add as substitution something like
`\1_`
Go to code generation -> Java

### Expected Outcome
The substitution should be in the Java syntax. For the example above the substitution `\1_` is replaced with `\\1_`. This substitution is stored in the Java variable `final String subst`.
Instead of replacing `\1_` with  `\\1_` it should be replaced with `$1_`.
Compare: [Description of the correct Java syntax](https://www.javamex.com/tutorials/regular_expressions/search_replace.shtml)

### Browser
Firefox, 66.0.3

### OS
Ubuntu 18.04

**Comment by Doqnach** [comment]
The code-generator does nothing more than placing your supplied regex in a code template. Make sure the syntax you are using on the website is valid voor the programming language you are using it for.

Currently, there is no specific JAVA flavour supported by the website that would validate the syntax for you.
