### ISSUE TITLE
Debugger displays a different glyph 

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1154]
## Bug Description

For code point 8204 (and maybe similar), the debugger shows a different glyph than the 'regular expression' field in the main UI, which caused me to not understand why it was behaving this way. The main UI shows a filled black dot like •, the debugger shows an invisible character, on win7/chrome

### Reproduction steps

https://regex101.com/r/V1CTdu/1 with ([a-zA-Z\-0-9]‌+\.)

### Expected Outcome

I would like the same display. Best would be for both to show an actual glyph rather than an invisible character but that's up to font handling and can't really be expected depending on the font usage, but at least the display should be consistent.

**Comment by firasdib** [comment]
The debugger shows the literal character, the input field on the editor shows a black dot instead of the invisible character.

How would one maintain a list of which characters to replace? Some fonts might show it, other might not.

**Comment by Doqnach** [comment]
An improvement could be maybe made to the hover. The tooltip shows the UTF-8 escape-sequence, but the hover also shows it as an empty character. Maybe try and detect non-printables (like `\p{C}`) and show their UTF-8 escape-sequence in the hover?

https://regex101.com/r/V1CTdu/2

**Comment by firasdib** [comment]
@Doqnach If there is a JS-compatible regex that does this, it will be possible

**Comment by Ouims** [comment]
Hello, I don't understand the reply, I'm not responsible for the design, but if you don't get the same rendering it's because you're not using the same font, which would be the issue, you would need to use the same font everywhere, which makes a lot of sense, there's nothing else to do imo.
