### ISSUE TITLE
Task 10: Please explain what "consume" means

### ISSUE THREAD

**Issue by ChrisForsythe** [firasdib/Regex101#1155]
I'm running into a meaning issue I believe. Task 10 states to not consume something. I'm not sure what this means. If I don't then I think others may have the same problem. Any chance of getting this requirement expanded or a link to documentation added when you hit check 5/18?

**Comment by Doqnach** [comment]
Are you still unsure what it means?

"Not consuming" is when the regex engine looks (around) in your input without "moving the cursor". 

Seeing as this is a quiz question I won't give any examples, but if you need some help with it join us on IRC.

**Comment by ChrisForsythe** [comment]
I’m not, I figured out what it means. 

However I found googling for that specific phrase to be rather.. difficult. Which is why I filed this, for the next person. If the explanation were expanded slightly I think it would be a bigger help for the quiz taker. 

As an aside the quiz is fantastic. The part showing there are better answers have made me better at regex. Thanks for making this.

**Comment by firasdib** [comment]
Thanks for the valuable feedback.

How would you recommend I rephrase this?

**Comment by ChrisForsythe** [comment]
I’m not 100% sure. Something searchable would be helpful. Obviously not wanting to give it away but what @dognach said was helpful. Maybe something about zero-length? Or maybe just a link to documentation like the first couple of hints?

Just a nudge more in the right direction would be a big help I think. Not a big deal either way though

**Comment by Timvde** [comment]
Maybe don't focus on the technicality of "consuming" characters, but focus on "Please make sure to match *twice* in the string `a##`".

**Comment by firasdib** [comment]
Maybe we can link to: https://www.regular-expressions.info/lookaround.html ?

It explicitly states

> They do not consume characters in the string, but only assert whether a match is possible or not.

**Comment by firasdib** [comment]
This has gone stale. Please reopen if you have ideas.

**Comment by ChrisForsythe** [comment]
II think something along the lines of what @Timvde said is fine.
