### ISSUE TITLE
PCRE: Unexpected replacement

### ISSUE THREAD

**Issue by jcd-pcre** [firasdib/Regex101#1158]
Hi regex fans,

I hit a case for which I don't have a solid explanation.
Pattern is **/\H.*\H\K|\h/#/g**
Minimal repro subject is **MM**
Goal: suppress leading & trailing blanks, leaving inner blanks untouched.

[regex101.com link](https://regex101.com/r/vFABmv/1)

As soon as the subject contains at least 2 **\H** (here the **MM**) the replacement engine appends a spurious **#** at the end of output.
Behavior is consistant in PCRE1 & PCRE2 (several implementations tested) so there must be some logic behind it but I admit I fail to see it.
I suspect it's a consequence of using \K but still I don't get it.
Of course there are several other ways to achieve that goal but my question is on this particular pattern behavior.

**Comment by Doqnach** [comment]
got a regex101.com link to an example showing this behaviour? that will be easier to look into than a text description.

You are saying that regex101.com behaves the same as several PCRE1 and PCRE2 tools? which tools did you use to check? So your question is more understanding the behaviour, and you don't consider this a bug?

**Comment by jcd-pcre** [comment]
Please forget it, it was a blind spot of mine.
\K doesn't suppress the fact that a match occurred, so the replace is perform anyway.
Geez, why did I not see that?
