### ISSUE TITLE
Matching Failed

### ISSUE THREAD

**Issue by greenbea** [firasdib/Regex101#1159]
## Bug Description
^1?(\d{10})$

### Expected Outcome
should match 10 or 11 digit number but fails for 10 digit

### Browser
Include browser name and version
latest chrome
### OS
Include OS name and version
windows 10

**Comment by TWiStErRob** [comment]
https://regex101.com/r/yVXhNz/1/

Can you give an example? Best if you provide a permalink like above.

**Comment by greenbea** [comment]
https://regex101.com/r/hiu4oF/2

**Comment by TWiStErRob** [comment]
You mix up 9 and 5 there in the mandatory prefix.

**Comment by greenbea** [comment]
Ok thanks sorry
