### ISSUE TITLE
"Don't create backreferences when you don't need them." But what if you actually need them?

### ISSUE THREAD

**Issue by e-gautier** [firasdib/Regex101#1160]
### Task
TASK 7: VALIDATE AN IP
### Bug Description
The result show up "Don't create backreferences when you don't need them. If you need to group, use (?:regex); it's the same as (regex) but it doesn't create a backreference." even if the regex is valid an we are using a backreference.
### Reproduction steps
Create a regex with a backreference, then use it with `(?1)`.
Ex: `/^(?:(xxx)\.){3}(?1)$/m`
### Expected Outcome
A valid result.
### Browser
Firefox 67.0
### OS
Fedora 29

**Comment by BeyondPerception** [comment]
I’m not getting the same error as you. Using the example you provided it matched xxx.xxx.xxx.xxx which is expected

Additionally, why are you using (?1) vs \1 to back reference (sorry I’m not familiar with that syntax but it seems to work both ways)

**Comment by e-gautier** [comment]
"xxx" is actually to avoid writing the full regex in the issue.
What I mean here is that we cannot reuse a pattern with (?1) because we get an error even if the regex is valid.
I send you the full regex in mp.

**Comment by firasdib** [comment]
The earlier tasks do not allow for backreferences, you can use them in more advanced tasks though.
