### ISSUE TITLE
regex101 matches unicode characters without `u` flag

### ISSUE THREAD

**Issue by Danon** [firasdib/Regex101#1162]
## Bug Description

In PHP, pattern `/\p{L}/` will not match 'ę' - it has to be `/\p{L}/u`. Regex101 will match letter `ę` with both patterns.

### Reproduction steps

Use pattern with unicode value, like `\p{L}` and not check `u` flag.

### Expected Outcome

Unicode letter `ę` not being matched without `u` flag checked.

### Browser
I believe all browsers

### OS
I believe all OSs

**Comment by firasdib** [comment]
Looks like PHP matches one byte, while regex101 matches both. I believe this is a discrepancy between the UTF8 in PHP and UTF16 on regex101.

This isn't something I will be able to fix, unfortunately.

**Comment by Danon** [comment]
I don't understand? Can't we somehow block matching utf-8 characters without `u` flag?

**Comment by firasdib** [comment]
@Danon Your text in the browser is UTF16 encoded, and thus, the regex engines run on UTF-16 encoded strings.

**Comment by Danon** [comment]
So? Why can't we re-encode them to utf-8?

**Comment by firasdib** [comment]
Maybe I have misunderstood this, but this is my take on it:

The browser uses UTF-16 throughout, and to avoid incompatibility issues when matching, the regex libraries also use UTF-16. 

If I used UTF-8, I would not know when the engine matched one or two bytes. For example, in your case, the engine would return a match length of 1 in both cases, but in the first case, the engine just matched one byte, while with the u-flag it matched two bytes.

The engine doesn't return the string it matched, but rather the position in the subject string, and then its up to you to do what you want with that information.

In fact, now that I think about it, the engine itself might actually be matching a single byte, but reporting length of 1 (which would be correct). But I have no way of knowing if this is the full character or not.
