### ISSUE TITLE
Might be better to put Quantifier out of Group block in explanation. 

### ISSUE THREAD

**Issue by VertexC** [firasdib/Regex101#1163]
## Bug Description
![image](https://user-images.githubusercontent.com/32974123/59334630-c7288e00-8caf-11e9-8ec5-5b3a16d76771.png)

### Reproduction steps
On web page, https://regex101.com/, type expression `^[^\/\\]*\.py$`, it shows on explanation side.

### Expected Outcome
It might be better to put "Quantifier ..." out of "Match a single block".

**Comment by firasdib** [comment]
I've been thinking about this myself as well. The reason it looks like this is to indicate that this entire block is quantified.

The quantifier relates to that token (and the entire block in the UI), and putting it outside of it can be confusing.
