### ISSUE TITLE
Missing "regex" dictionary data when searching library with API

### ISSUE THREAD

**Issue by Balthamos** [firasdib/Regex101#1165]
According to the API wiki, when using the List/Search Library method, it should return json data like the following:

> {
>   "data": [
>     {
>       "title": "My awesome title",
>       "description": "My even more awesome description",
>       "dateModified": "2016-10-07T03:46:35.000Z",
>       "author": "JohnDoe2",
>       **"regex": "(\\w+)(2)?",**
>       "delimiter": "@",
>       "flavor": "pcre",
>       "flags": "g",
>       "version": 1,
>       "permalinkFragment": "YtA4hF",
>       "upvotes": 0,
>       "downvotes": 0,
>       "userVote": null
>     }
>   ],
>   "page": 1,
>   "pages": 1
> }

However all my search results are missing the actual "regex" key/value pair, unless I use the Retrieve an Entry call to grab a specific entry.

Example:
curl -X GET "https://regex101.com/api/library/1/"
Returns results like this:

> {
>    "data": [
>      {
>         "title": "URL Validator",
>         "description": "Finds valid URLs (they have to start with \"https:\/\/\")",
>         "dateModified": "2019-06-23T05:06:35.000Z",
>         "author": "chris mccoy",
>         "flavor": "pcre",
>         "version": 1,
>         "permalinkFragment": "wM8zuj",
>         "upvotes": 0,
>         "downvotes": 0,
>         "userVote": null,
>       }
> ...
>    ],
>    "page": 1,
>    "pages": 479
> }

**Comment by firasdib** [comment]
To get specific data about a regex, you need to query the correct API. The library doesn't list it, but I could potentially add it.

**Comment by Balthamos** [comment]
Ah gotcha - in that case I think it’s just a typo in the wiki, because under the Library API Documentation the [example success call](https://github.com/firasdib/Regex101/wiki/API#success-response-http-200) indicates that the regex should in fact be returned when querying the library’s api, unless I’m really bad at reading =P

If it wouldn’t be complicated to add, I’d certainly find it useful. The way I’m using the API is through an iOS Shortcuts App shortcut (which is the platform that has introduced me to regex), and I made a quick little tool to search the regex library, return the results, and display them in a menu where I see the title, description and can preview the regex. 

When I tap on one it copies the regex to my clipboard while popping up the editor to see it in more detail. 

Since I’m unable to retrieve the regex in my original library search query, to display the regex in my menu I need to take each result from the original query and run it through individual api/regex queries, which obviously takes a lot more time and many calls vs just grabbing the regex data while grabbing titles/ID+Vs/descriptions in a single call.

Thanks!

**Comment by Doqnach** [comment]
There indeed seems to be some discrepancies between the docs and reality.

@firasdib I'm okay with running through it once and updating it where need.

**Comment by firasdib** [comment]
I understand your use case, but this will increase the overall load on the people using the website (and my network traffic); since everyone will now download more data than they need to.

I would have to grab regex, delimiter and flags as well.

I'm torn on this one tbh. This is ideally the role a BFF would have.

**Comment by Balthamos** [comment]
That makes sense... what if as a compromise it were not sent by default but could be fetched using an optional parameter? That way it wouldn’t be sent unless you used something like https://regex101.com/api/library/1/?search=awesome+title&grabRegex=true and the default were =false ?

**Comment by Doqnach** [comment]
people will tend to then always supply the param, no matter if they need the data or not, simply because it is there and [FOMO](https://www.urbandictionary.com/define.php?term=Fomo).

**Comment by Doqnach** [comment]
@Balthamos the wiki entry has been fixed on this one issue, but I already detected more things that probably changed over time and are outdated (plus an issue with the ordering of results when calling the `/api/library` endpoint). So, work in progress on that (documentation) front.

**Comment by qywSof-zotbu9-jenheq** [comment]
> According to the API wiki, when using the List/Search Library method, it should return json data like the following:
> 
> > {
> > "data": [
> > {
> > "title": "My awesome title",
> > "description": "My even more awesome description",
> > "dateModified": "2016-10-07T03:46:35.000Z",
> > "author": "JohnDoe2",
> > **"regex": "(\w+)(2)?",**
> > "delimiter": "@",
> > "flavor": "pcre",
> > "flags": "g",
> > "version": 1,
> > "permalinkFragment": "YtA4hF",
> > "upvotes": 0,
> > "downvotes": 0,
> > "userVote": null
> > }
> > ],
> > "page": 1,
> > "pages": 1
> > }
> 
> However all my search results are missing the actual "regex" key/value pair, unless I use the Retrieve an Entry call to grab a specific entry.
> 
> Example:
> curl -X GET "https://regex101.com/api/library/1/"
> Returns results like this:
> 
> > {
> > "data": [
> > {
> > "title": "URL Validator",
> > "description": "Finds valid URLs (they have to start with "https://")",
> > "dateModified": "2019-06-23T05:06:35.000Z",
> > "author": "chris mccoy",
> > "flavor": "pcre",
> > "version": 1,
> > "permalinkFragment": "wM8zuj",
> > "upvotes": 0,
> > "downvotes": 0,
> > "userVote": null,
> > }
> > ...
> > ],
> > "page": 1,
> > "pages": 479
> > }

;)

**Comment by firasdib** [comment]
I'm going to close this for now, feel free to comment if you have any ideas.
