### ISSUE TITLE
Regex for facebook videos url 

### ISSUE THREAD

**Issue by TheAliChaudhary** [firasdib/Regex101#1166]
## Bug Description
The code Generated in JavaScript is not correct. for reference check these links.
https://regex101.com/r/nV4rI3/1
https://regex101.com/r/nV4rI3/1/codegen?language=javascript
here is the pattern generated  **/^http(?:s)?://(?:www\.)?facebook.(?:[a-z]+)/(?!(?:video\.php\?v=\d+|usernameFB/videos/\d+)).*$/gm;** which is not correct.

### Expected Outcome
generated regex in Php is working fine but in javascript its not working. i want this to work. 
please help!
### Browser
Google Chrome is up to date
Version 77.0.3831.6 (Official Build) dev (64-bit)
### OS
Include OS name and version
Windows 10* 64-bit

**Comment by working-name** [comment]
Hi there! It seems your regex needed a few escapes of the forward slashes. If you switch flavor to javascript on the left sidebar you will get specific error messages that can help you remedy any errors. 

Check out version https://regex101.com/r/nV4rI3/11

Keep in mind that the regex implementation is not the same across all languages. Javascript has less features than PCRE for example.

**Comment by firasdib** [comment]
This is not a forum for regex help. Please use irc for that.
