### ISSUE TITLE
Support for 're.sub()'

### ISSUE THREAD

**Issue by VishalSharma26** [firasdib/Regex101#1167]
## Feature

Should have support for re.sub(regex, replacewith. content)

**Comment by Doqnach** [comment]
Is that different then the current code-generator?

https://regex101.com/r/COtMEu/1/codegen?language=python

**Comment by working-name** [comment]
Just a quick mention, @VishalSharma26: if you don't enable the `SUBSTITUTION` tab below `TEST STRING`, code generator will focus on matching only - so no `re.sub`

**Comment by working-name** [comment]
Please reach back if this is still troublesome. Thank you!
