### ISSUE TITLE
Include "#" as delimiter choice

### ISSUE THREAD

**Issue by teo1978** [firasdib/Regex101#1168]
## Bug Description
"#" is a very, very common choice of delimiter used in regex's, so it's ridiculous that it's not included in the list of delimiters among which to choose.

Also you should allow entering an arbitrary delimiter, but that's a feature request 

### Reproduction steps
Click on the three vertical dots on the left of the pattern input field

### Expected Outcome
"#" should be among the delimiters choices

### Observed Outcome
It's not

### Browser
All

### OS
all

**Comment by working-name** [comment]
Hey @teo1978, thanks for the request. I am not aware of what it takes to include more delimiters but I'm sure the owner will chime in and let you know.

**Comment by firasdib** [comment]
Reason is that it clashes with the comment feature in PCRE, and to avoid confusion, I opted to not allow for that delimiter.
