### ISSUE TITLE
Add C# flavor

### ISSUE THREAD

**Issue by mydeveloperday** [firasdib/Regex101#1170]
## Feature

I love your Regex101 site, I use it all the time, but I have to translate back and forth between the regex and something that I can use with C# code  (generally escaping items)

Sometimes, even though I think I've done it correctly, the C# doesn't show the same expected results

I'd love it if we could see the regex as something that would work in C# code

so it could be put directly into some sort of code statement without modification, either using the "@" syntax or without

            string reg =
                @"[^:=*\/_A-Za-z\/][,(\s]*(false,|true,|false\);|true\);|,true|,false|,nullptr|nullptr\);)[^;][,]*";
            Regex regex = new Regex(reg);
            Match match = regex.Match(textToFind);

**Comment by mydeveloperday** [comment]
I hadn't seen the code generator...

**Comment by Doqnach** [comment]
FYI: keep an eye on #156
