### ISSUE TITLE
Russian language sequence "[А-я]" haven't "ё" character

### ISSUE THREAD

**Issue by Inetov** [firasdib/Regex101#1171]
## Bug Description
Russian language sequence "[А-я]" haven't "ё" character.
Russian alphabet:
А а, Б б, В в, Г г, Д д, Е е, Ё ё
Ж ж, З з, И и, Й й, К к, Л л, М м
Н н, О о, П п, Р р, С с, Т т, У у
Ф ф, Х х, Ц ц, Ч ч, Ш ш, Щ щ, Ъ ъ
Ы ы, Ь ь, Э э, Ю ю, Я я

### Reproduction steps
regex "[А-я]" with text "мёд" gives result: "м" and "д" (two matchs)

### Expected Outcome
"м", "ё", "д" (three matches)

### Browser
Include browser name and version
Firefox 68

### OS
Include OS name and version
Win10 1803

**Comment by Inetov** [comment]
ok, is't bug, just strange behavior

**Comment by Doqnach** [comment]
Better to use UTF-8 codepoints `[\x{0400}-\x{052F}]`, or if your regex engine supports it, `\p{Cyrillic}`.

https://regex101.com/r/N3vRTY/1

**Comment by Inetov** [comment]
> 
> 
> Better to use UTF-8 codepoints `[\x{0400}-\x{052F}]`, or if your regex engine supports it, `\p{Cyrillic}`.
> 
> https://regex101.com/r/N3vRTY/1

thx!
