### ISSUE TITLE
Global mode for unit testing

### ISSUE THREAD

**Issue by thisismydesign** [firasdib/Regex101#1172]
## Feature

I would like to be able to write unit tests where I can assert all the matches and not only the first one. AFAICT this is not possible currently.

The format could be something simple like comma-separated values to full-blown UI-support.

https://github.com/firasdib/Regex101/issues/991 is a similar request and I disagree with the conclusion.

> A global expression is the same as applying the expression over the same string multiple times, with different start positions. Its better to create a test case for each nth match, than to try target specific iterations.

Sometimes you want to test for complex scenarios and showcase that they actually work but in any case, it should be safe to let the users decide what they prefer IMO.

**Comment by firasdib** [comment]
Could you show me a real world case where multiple test are unable to cover one complex larger scenario? I can't think of any regex that depends on a previous matches success/failure to work.

**Comment by TWiStErRob** [comment]
Not real world, but an example for match dependency with global flag:
https://regex101.com/r/mSNcGY/1
vs
https://regex101.com/r/mSNcGY/2
I can't think of a way to write a test to lock in either behavior without multi-match testing.

@thisismydesign if you have a real example, please share!

**Comment by thisismydesign** [comment]
It might be the case that it's technically impossible to have a regex where an existence of a match affects other matches (although given lookarounds and lazy matching I'm not sure about that) but as a user of a regex I really don't want to care about that. I just want to make sure the regex works with complex examples.

So to your point

> I can't think of any regex that depends on a previous matches success/failure to work.

You might be right but that's not what I'm arguing:

> Sometimes you want to test for complex scenarios and showcase that they actually work but in any case, it should be safe to let the users decide what they prefer IMO.

An example:

I have a regex to match comma separated argument list incl support for quote-enclosed params (broken now for some reason): https://regex101.com/r/UL8kyy/3/tests

I have to provide test strings like `, in-the-middle-single_param, ` instead of being able to provide an actual meaningful input.

Also, I'd like to show that the regex works on real-life examples, such as a param followed by a quote-enclosed param: `param1, "quoted,param", param2` which I cannot do.

**Comment by firasdib** [comment]
I'm still on the fence, but I have a better idea of the problem now.

This would impose a few new requirements for the unit test page though. You'd probably want something like "Matches N times", "Nth full match", "Nth Matches Kth capturing group" etc.

**Comment by thisismydesign** [comment]
I think a simple solution would be to assert all matches. The others are
nice to have.

**Comment by firasdib** [comment]
@thisismydesign You propose that I simply go through all of the matches, and see if any match the given condition? That might be good enough.

**Comment by thisismydesign** [comment]
I'm proposing that all of the matches would have to be provided in exact
order. Might be more than what the user wants sometimes (e.g. If they only
want nth match) but it should always be feasible to write tests like this.
I'd not do it in a way where the result can be ambiguous (what you're
proposing). The input format is the question imo, it should resemble an
array of strings. Maybe it could be that the user can add new fields or
some arbitrary format.

**Comment by firasdib** [comment]
That sounds very clumsy. How would the UI for something like that look?
