### ISSUE TITLE
Highlight "test string" and "unit test" tabs based on whether there's data present

### ISSUE THREAD

**Issue by thisismydesign** [firasdib/Regex101#1174]
## Feature

I would like if users could easily tell that there're unit tests and test strings present if they're on the other tab, even if they're not familiar with the platform.

I think it's very easy to miss one of these features or the other (and the data added there) unless the user specifically knows what to look for.

I think a solution using tabs would be better where
- the tabs are next to each other (instead of being in the 2 corners)
- the tabs that include data are highlighted with different colors
- the number of tabs could be extended over time to include other features, e.g. documentation (https://github.com/firasdib/Regex101/issues/832), explanation (https://github.com/firasdib/Regex101/issues/1173)

**Comment by lorenzleutgeb** [comment]
If only one of the two tabs have content (i.e. someone specified either a test string or unit test(s), but not both) you could show the one that has content by default.

**Comment by firasdib** [comment]
The behavior has been changed with the implementation of #1502. Feel free to comment if you have any other thoughts!
