### ISSUE TITLE
Feature: Allow granting pattern write permission to specific user

### ISSUE THREAD

**Issue by JEltgroth** [firasdib/Regex101#1175]
## Feature
I apologize if this is a dup or this feature exists.

My coworkers and I use and love RegEx101.  We have tons of Regex patterns in our code, and the ability to save regex patterns along with test strings and other features, and then linking to the RegEx101 Pattern Url in our code via a comment is immensely useful and prevents repetitious work on our part.

Right now, we just have individual accounts we use to store patterns and lock it to prevent editing from the public.  It would be nice if there was an organization or whitelist feature where I could allow my coworkers to easily see and edit RegEx stored in my account from theirs, without allowing public write access, and vice versa.

Perhaps this would look like adding a "shared folder" to your library with access permissions set on it.

**Comment by firasdib** [comment]
Right now there are no such features. These types of enterprise level features are quite a bit of work for minimal reward. If this was a SaaS offering that business were paying for I could see it happening, but right now, its unlikely.
