### ISSUE TITLE
Typo or not

### ISSUE THREAD

**Issue by free6k** [firasdib/Regex101#1176]
## Question
Hello is maybe it typo? ```Single line - dot matches new line``` -> maybe is right "```don’t```"?

![image](https://user-images.githubusercontent.com/1732637/61945158-f6693500-afa7-11e9-8171-d58ce6e98194.png)

Thanks.

**Comment by working-name** [comment]
Not a typo. Dot refers to the character `.` which for regex means `any character except line terminators`. When you turn on the `/s` flag you remove the exception, which is why `dot (now) matches newline (too)`
