### ISSUE TITLE
Task 3: Accepts invalid solution, description not 100% precise

### ISSUE THREAD

**Issue by xpac1985** [firasdib/Regex101#1177]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 3: Uppercase consonants

### Bug Description
* Task 3 accepts regexes that match ASCII chars 0-31 - so e.g. a newline character. The task should test for some chars between ASCII 0-31.
* Task 3 says "ASCII only". From my understanding, it should say "Extended ASCII only". ASCII is chars with values 0-127, isn't it? But it checks for chars in the 128-255 range...

### Reproduction steps
Without giving away solutions...
* Use a regex that does not match ASCII 32-64, A, E, I, O, U, and 91-255. Task will accept it although it does NOT exclude ASCII chars 0-31.
* Use a regex that does not match ASCII 0-64, A, E, I, O, U, and 91-127. Task won't accept it because it checks for chars from the range 128-255.

### Expected Outcome
Fail with regex that allows ASCII 0-31.
Succeed with regex that allows ASCII 128-255.

Also, maybe add "Extended ASCII" to description.

### Browser
Include browser name and version
Chrome 75
### OS
Include OS name and version
Windows 10

**Comment by Davidebyzero** [comment]
Furthermore, it would actually be theoretically possible to get the same best score of **16** characters even if the requirements of the task were tightened to reject regexes that accept ASCII 0-31. But if an attempt is made to submit that solution (without being too spoilery, it involves submitting a request whose payload includes the JSON escape `\u0000`), the response is `{"errorMessage":"missing terminating ] for character class - offset: 2","testNumber":2,"totalTests":9}`, i.e. the quiz software uses C strings, treating ASCII 0 as a string terminator.

It is currently possible to submit a  **16** character solution that rejects ASCII 1-31 and Unicode 256-65535 and is accepted by the quiz software.

**Comment by firasdib** [comment]
I'll add some tests for this.
