### ISSUE TITLE
Modern C++ flavor

### ISSUE THREAD

**Issue by Delta456** [firasdib/Regex101#1178]
How about implementing support for Modern C++ as it has a regex library in it?

**Comment by Doqnach** [comment]
With C++ it depends on which library you use. So the question becomes: which library are you looking for (regex, boost, pcrepp, etc)?

**Comment by Delta456** [comment]
Sorry for not being clear, I mean `std::regex`

**Comment by Doqnach** [comment]
As stated in #198 and #141, it should be enough to use the ECMAScript (Javascript) flavour in the case of `std::regex`.
If you feel this is insufficient, please let us know why and the issue could be reopened.

**Comment by firasdib** [comment]
Posix-ERE will be supported in the next version, which I hope covers this.
