### ISSUE TITLE
The named capturing group throw a unwanted syntax error

### ISSUE THREAD

**Issue by Jerome1337** [firasdib/Regex101#1179]
## Bug Description
When using the named capturing group with the JavaScript flavor, the pattern is shown as wrong.

### Reproduction steps
Select the JavaScript flavor and provide a regex using a named capturing group

For example:
```
/(?P<name>Sally)/
```

### Expected Outcome
No pattern error and catch `Sally` with `name` name.

### Browser
```
Firefox 68.0.1
```

### OS
```
OS: Arch Linux 
Kernel: x86_64 Linux 5.2.4-arch1-1-ARCH
```

**Comment by working-name** [comment]
Hi @Jerome1337 

This is not a bug, it's just a misunderstanding of what JavaScript regex can and cannot do (yet?) across browsers. Here's some more information: #1053 

Hope this helps ;)

**Comment by Doqnach** [comment]
The actual problem here is the notation for named capture groups which is different between PCRE and Javascript. See https://www.regular-expressions.info/refext.html (select the flavours at the top left corner).

**Comment by working-name** [comment]
Javascript has been making great progress in improving their implementation of regex. As of late, you can now use look-behinds and named capture groups. 

Gecko, the rendering engine behind Firefox, does not support named capture groups (not yet, hopefully?). However, Webkit does; in other words, switch to chrome if you want to test those things on regex101.com.

And yes, @Doqnach was right about the syntax being a little off. Yours is more python-like, but javascript understands `(?<MightyName>...)` - no P needed.

**Comment by firasdib** [comment]
@working-name is correct. The site will feature detect this and add support for it accordingly.

**Comment by Jerome1337** [comment]
@working-name 

> And yes, @Doqnach was right about the syntax being a little off. Yours is more python-like, but javascript understands (?<MightyName>...) - no P needed.

Ok then the examples shown on the `quick reference` panel should change when the flavor change, right?

**Comment by Doqnach** [comment]
@Jerome1337 they do. When you select the PCRE flavour it mentions `(?P<name>...)`, but under ECMAScript flavour it does not.
