### ISSUE TITLE
Add PWA manifest

### ISSUE THREAD

**Issue by cglong** [firasdib/Regex101#1180]
## Feature
According to [PWABuilder](https://www.pwabuilder.com/), this site doesn't have a [PWA manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest). Can one be added so Regex101 can be installed as an app?

**Comment by firasdib** [comment]
Fixed

**Comment by cglong** [comment]
Hi @firasdib, thanks for taking care of this so quickly! It looks like [the manifest file](https://regex101.com/static/manifest.json) is a list of files, rather than the expected metadata about the app. Can this be fixed to be in [the expected format](https://developer.mozilla.org/en-US/docs/Web/Manifest)?

![Screen Shot 2019-09-11 at 11 12 29 PM](https://user-images.githubusercontent.com/137214/64758618-e4a50800-d4e9-11e9-8f71-e4864aa143fd.png)
