### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by marinvch** [firasdib/Regex101#1181]
Its not working on JavaScript , only on Php
![notWorking](https://user-images.githubusercontent.com/28672157/62626061-2d880080-b92f-11e9-8fa3-305e5e3a363b.png)

**Comment by Doqnach** [comment]
Firefox does not yet support look-behind in javascript. 

Try a Chrome based browser instead.

See also #1179.

**Comment by marinvch** [comment]
ok thanks

На ср, 7.08.2019 г., 16:25 Doqnach <notifications@github.com> написа:
