### ISSUE TITLE
error in quick reference example for [[:alnum:]]

### ISSUE THREAD

**Issue by stoccc** [firasdib/Regex101#1188]
## Bug Description
There is an error in the quick reference example for `[[:alnum:]]`

The example reported is

    /[[:alnum:]]/g

but the result displayed is for

    /[[:alnum:]]+/g

here follows the screenshot.

![immagine](https://user-images.githubusercontent.com/24807203/63341425-7b4a3300-c349-11e9-9d85-1971e37c69e7.png)

and this is the result of the wrong example
![immagine](https://user-images.githubusercontent.com/24807203/63341591-d8de7f80-c349-11e9-97ca-3618bc782f19.png)

**Comment by working-name** [comment]
Hey @stoccc, thanks for the report! I've updated the example regex and it will be pushed with the next site update.
