### ISSUE TITLE
TLD length in task 8 incorrect

### ISSUE THREAD

**Issue by ChrisForsythe** [firasdib/Regex101#1191]
The TLD length requirement from test 20/56 limits to 6 characters in length for task 9. TLD's can be much longer now.

http://data.iana.org/TLD/tlds-alpha-by-domain.txt is the current list of TLD's.

**Comment by firasdib** [comment]
The task is not meant to be a real world use case, more of a learning experience. There is much more wrong with a regex like that than just the TLD matching :)
