### ISSUE TITLE
Chrome Duplicate tab not supported

### ISSUE THREAD

**Issue by kkava** [firasdib/Regex101#1192]
## Feature
When I'm testing RegExes, sometimes I want to duplicate the Chrome tab (RMB/Duplicate tab) and tweak something. Currently this just produces a fresh Regex101.com site.

**Comment by Doqnach** [comment]
what is your expectation? it also clones the current content of the textareas? or duplicates from the last saved version?

The way browser tab duplication works, is that it simply opens a new tab based on the URL you were visiting, with a copy of the original tabs history.

This means that duplicating a tab will never retain live form data.

Workaround for your use-case would probably be to first save the regex and then duplicate the tab. That or fork the regex.

**Comment by firasdib** [comment]
This would rely on storing things in local storage, but this is quite difficult to get right. The reason is that I sometimes use multiple instances of the site to test, and it would be annoying if it came prefilled or that the changes on the different instances were fighting with each other.

But I'm definitely up for any changes that improve workflow.

**Comment by kkava** [comment]
I see what you mean. Storing all that in the URL would be impossible. But
you could store a key in the URL and store the data (regex, content) server
side. Like you said, you already do that with the save function. You could
"just" autosave and present a unique URL on change (simple javascript URL
changer I think). Then when the tab is duplicated call up the data based on
that unique URL (key). Really you could eliminate the save feature entirely
if you cached all queries for a few months (not sure how persistent your
saves are) but maybe even that would be too much data. Anyway thanks for
the attention. :)

**Comment by Doqnach** [comment]
Auto-saving would be done when? at every keystroke/change? that would mean a high amount of client-server roundtrips which would only benefit the infrequent use of tab duplication.

For now, as I mentioned, the workaround is to save the regex before duplicating.

Would that be sufficient for you, at least for now?

**Comment by oozcitak** [comment]
It could be possible to solve this entirely on the client side by listening to `onLoad` events combined with `tabs.onActivated` and `tabs.onUpdated`. This SO post has some pointers: https://stackoverflow.com/questions/25922776/how-to-realize-when-a-browser-tab-has-been-duplicated.

**Comment by firasdib** [comment]
The question is if this is desirable behavior or not? I am not convinced it is.
