### ISSUE TITLE
Misleading explanation for "(?!)"

### ISSUE THREAD

**Issue by il86be** [firasdib/Regex101#1194]
## Bug Description

The human explanations for (?!) says:

> Negative Lookahead (?!) — null, matches any position

I guess something is missing, maybe just some newlines, but as it is now it says that the expression is null and matches anything, which is the opposite of its true meaning.

### Reproduction steps

On regex101.com, enter  the regular expression **(?!)**

### Expected Outcome
Something like 
"Negative Lookahead (?!) 
Asserts that the expression below does no match.
- empty expression, matches any position"

### Browser
Firefox Quantum 68.0.2 (64-bit)

### OS
Windows10 pro, version 1803

**Comment by working-name** [comment]
Hi @il86be 

I'm not sure I completely follow what you're saying. What would you rather have as an explanation for a blank negative lookahead? "null, matches no position"?

Also, since we're addressing semantics, the explanation refers to the negative lookahead only, not what the regex is matching. What is being matched by the regex as a whole is under `MATCH INFORMATION` sidebar.

What's your thought on `/(?=)/` ?

**Comment by il86be** [comment]
> What would you rather have as an explanation for a blank negative lookahead? "null, matches no position"?

Either "Negation of null, matches no position", or 
"Assert that the Regex below does not match.
null, matches no position".
Then It would be consistent with a non-empty negative lookahead. 
Take for example /(?!())/, the explanation reads:

| **Negative Lookahead** (?!|)
| Assert that the Regex below does not match
|1st Alternative — null, matches any position
|2nd Alternative — null, matches any position

Here the top-level negative lookahead and its subexpression "|" are separated, so everything is pretty clear.

> Also, since we're addressing semantics, the explanation refers to the negative lookahead only, not what the regex is matching

If the explanation would refer to the negative lookahead only, it would say "this expression matches the empty string if its sub-expression,  whatever it is, does not match at that position". And this what it basically says, when the subexpression is not empty. But when it is empty, it says "**Negative lookahead** (?!) — null, matches any position" which is wrong, because it refers to who different levels at the same time.

> What is being matched by the regex as a whole is under MATCH INFORMATION sidebar.
Explantion abohat sidebar is about matching a particular input string against the regex. 
As you say, "being matches" . I am talking aboy "matches"It is something different, I am talking about semantics of the whole expression, not any concrete example (I hope there are noabout any concrete examples. 

For /(?=)/ the explanation reads:
| **Positive Lookahead** (?=) — null, matches any position
This as well scrambles two levels together, but since the semantics of both levels is identical, this is not a big deal, just as in the case of an empty capturing group, or the empty alternatives above.

**Comment by firasdib** [comment]
I believe your proposal is incorrect. Stating that `(?!)` matches no position is factually incorrect. The expression will match at any position in the string, and fail the match immediately. A negative lookahead will fail the match if it matches.

**Comment by il86be** [comment]
Sorry, what definition of matching are you using?
How can a regular expression match and fail at the same time? 

Let us take another example, (?!(?!)).
By your definition, (?!)  matches anything therefore ((?!(?!)) will always fail, right?
Technically, this agrees with the explanation that https://regex101.com/r/H8Fdqr/1  gives:

> /(?!(?!))/gm
> Negative Lookahead (?!(?!))
> Assert that the Regex below does not match
> Negative Lookahead (?!) — null, matches any position

But this explanation is wrong, the double negative lookahead should matches at any position, as the "Matching information" section confirms.

Once again: all negative lookaheads should be explained in the same way. They "assert" that their parameter does not match.  "Assert" here means matching the empty string if the condition is true, and not matching otherwise. It is not like assert() in a C program which is global.

**Comment by firasdib** [comment]
Lookaheads are kind of like if-statements. A positive lookahead, such as `(?=abc)` can be translated to something like `if (abc does match) continue`, while a negative lookahead, such as `(?!abc)`, translates to `if (abc does match) break`.

Does this make sense?
