### ISSUE TITLE
Rust invalid generate of code

### ISSUE THREAD

**Issue by webdesus** [firasdib/Regex101#1197]
## Bug Description
this construction is not valid
```rust
let (start, end) = match result {
    Some((s, e)) => (s, e),
    None => {
        // ...
    }
  };
  
  
  println!("{}", &string[start, end]);

```

### Reproduction steps
any regex

### Expected Outcome

should it be 

```rust
println!("{:?}", &result);
```
[link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=231aa56ad3ad8b5d4e7ebad520ed6233) to work example

### Browser
any

### OS
any

**Comment by firasdib** [comment]
Thank you for this, I will make sure to update the code to reflect this.

Are there any other errors? Would you mind having a look at the substitution examples, as well as the global/non-global mode?

**Comment by webdesus** [comment]
Wow :smiley:  very long time using your app and only now found substitution examples 😂

1. Substitutuin work fine.

2. I think will be better change match construction to short...

**now:** 
```rust
let regex = match Regex::new(r"(?m)123") {
    Ok(r) => r,
    Err(e) => {
      println!("Could not compile regex: {}", e);
      return;
    }
  };
````
**my solution**

```rust
let regex = Regex::new(r"\(?m)123").unwrap();
```
method `unwrap` does the same only with color.

3. All flags work fine, exclude only global flag.

**work solution** 

```rust
extern crate regex;
use regex::Regex;

fn main() {
    let regex = Regex::new(r"123").unwrap();
    let text = "123 123";
    
    for mat in regex.find_iter(text) {
        println!("{:?}", mat);
    }
}

```

**Comment by 1982julie** [comment]
https://github.com/firasdib/Regex101.wiki.git
Try looking here for the right path.

**Comment by firasdib** [comment]
Thanks, using your suggestions now! I'll push this live soon.
