### ISSUE TITLE
Inconsistent result between unit tests and test area

### ISSUE THREAD

**Issue by Opsse** [firasdib/Regex101#1199]
## Bug Description
Different matching between unit tests and test area for the sames regex and the same strings.

### Reproduction steps
https://regex101.com/r/iQutYJ/1

With `(?<=\w+)~\d+` regex: `test~42` and `4~2` matchs in test area but not in unit test.  

I don't know if it's related to it but I use lookbehind.

### Expected Outcome
Same matching in both side.  
(Take note than I'm not sure than my unit tests should succeed.)

### Browser
Chromium Version 76.0.3809.100 (Official Build) Built on Ubuntu

### OS
Ubuntu 18.04 (64-bit)

**Comment by firasdib** [comment]
If you expand the items in the unit tests, you see you filled in the description field with your test string.
