### ISSUE TITLE
Less error prone interface for unit test description

### ISSUE THREAD

**Issue by victor-yon** [firasdib/Regex101#1200]
## Feature
After my mistake, leading to an invalid bug issue (#1199) I think it could be useful to make the interface less confusing and error prone in the unit test view.

Currently it's difficult to see the difference between :
- description: "abc" | test: "abc"
- description: "abc" | test: ""

Here the 3 tests seems very similar if not unfold:
https://regex101.com/r/0QpGq8/1
![image](https://user-images.githubusercontent.com/3708059/64614860-addfcc80-d3d9-11e9-811a-334bfa6373fc.png)

But the first 2nd have empty string and the second have no description.
![image](https://user-images.githubusercontent.com/3708059/64614914-c2bc6000-d3d9-11e9-973c-f27b26220e47.png)

## Suggestion

Do not use the test string as description if the description is empty.

With the same example it would be clearer this way : 
![image](https://user-images.githubusercontent.com/3708059/64615593-25622b80-d3db-11e9-80a3-91386c7884b7.png)

**Comment by firasdib** [comment]
The obvious answer would be to simply type in better descriptions, but perhaps this can facilitated in some sort of automatic way? The test string can be ambiguous too though.

**Comment by firasdib** [comment]
Should the default behavior simply be to show _`no description`_?

**Comment by TWiStErRob** [comment]
I think the quotes are a good idea regardless of using "no description". I'm not sure where would this "no description" show btw, but some kind of placeholder is always good.

**Comment by firasdib** [comment]
The test description goes on top, if that doesn't exist, the test string is used. The problem is there is no way to know which is which, and can be difficult to distinguish. My question was if the default behavior of showing the test string when the description is missing should be removed or not.

Other ideas are very much welcome, too!

**Comment by TWiStErRob** [comment]
I think using the test string as fallback was/is a good idea, but format it similar to how "target" and "criteria" is, which makes it clear that it's the input: `Test string <b>abc</b>`

**Comment by firasdib** [comment]
This has been adjusted, check out the new version live.

**Comment by TWiStErRob** [comment]
Pretty neat!
