### ISSUE TITLE
(?<=\s|^)(\d{13}|\d{10})(?=\s|$)

### ISSUE THREAD

**Issue by zuozhiwen** [firasdib/Regex101#1202]
(?<=\s|^)(\d{13}|\d{10})(?=\s|$)
A lookbehind assertion has to be fixed width

**Comment by Doqnach** [comment]
... that look-behind is fixed width? it is either a space or start-of-string, both of which are of defined length.

**Comment by zuozhiwen** [comment]
environment: regex101 - python
 it works good on regex, failed on re module. perhaps regex101 should support a chooice?

**Comment by Doqnach** [comment]
https://regex101.com/r/hXKKOV/1

As you can see, the website also tells you this. Maybe you still had it set to PCRE instead of Python flavour?
