### ISSUE TITLE
Quiz task 8: It's possible to not match a valid domain name and pass

### ISSUE THREAD

**Issue by ChrisForsythe** [firasdib/Regex101#1204]
## Bug Description

In step 8 detection of a domain will pass the submit button, however the actual regex will fail on domains like this and not match the last .us.

odyssey.davis.k12.ut.us

### Reproduction steps

I can provide my regex privately if necessary

**Comment by firasdib** [comment]
@Davidebyzero Is this something we should clarify in the task description?

**Comment by Davidebyzero** [comment]
@ChrisForsythe it sounds like you may have found an actual bug. Sorry for the very late reply.

If your regex that has this bug is still passing all the tests, please email me the regex. My email is my username here at gmail dot com.

**Comment by ChrisForsythe** [comment]
> @ChrisForsythe it sounds like you may have found an actual bug. Sorry for the very late reply.
> 
> If your regex that has this bug is still passing all the tests, please email me the regex. My email is my username here at gmail dot com.

Sure thing, just sent it over. It may or may not be a bug but I figured it was weird enough to bring up. Thanks for r101 I use it almost every day.

**Comment by Davidebyzero** [comment]
Thanks! You were right, it wasn't verifying that domains containing subdomains shorter than 3 characters in length were accepted. Now fixed.

**Comment by Davidebyzero** [comment]
Actually, it seems that not enforcing subdomains shorter than 3 characters will have to be part of what makes this task "Simplified". 209 out of 302 users took advantage of this loophole in their solutions. I suppose we could add an "Advanced" version of this task that does more enforcement?

**Comment by firasdib** [comment]
@Davidebyzero Writing a regex that properly validates an email, as short as possible, would be.... super cool.
