### ISSUE TITLE
Extra backslash in \V description

### ISSUE THREAD

**Issue by Alcaro** [firasdib/Regex101#1205]
## Bug Description
The \V description contains an extraneous backslash.

### Reproduction steps
Enter \H\V as regex. Look at the explanation panel at the top right.

### Expected Outcome
\H matches any character that's not a horizontal whitespace character
\V matches any character that's not a vertical whitespace character

### Actual Outcome
\H matches any character that's not a horizontal whitespace character
\V matches any character that\\'s not a vertical whitespace character

### Browser
Firefox 69, x86_64

### OS
Lubuntu 18.04, x86_64

**Comment by firasdib** [comment]
Thanks! I'll push this live in the coming days
