### ISSUE TITLE
PHP regex interpreter implicitly applied /u modifier

### ISSUE THREAD

**Issue by kkava** [firasdib/Regex101#1207]
## Bug Description
Regex101.com result differs from PHP result when special characters are present.

### Reproduction steps
1. See example https://regex101.com/r/vjvZeO/1
     -Note that the quotes are correctly included in the set of split characters
2. Run same regex from PHP 7
     -Now, the fancy end quote is not included in the split, and appears on the end of the word "Tax".

### Expected Outcome
Fancy quote characters should NOT split words in the above example unless the /u (utf-8) modifier is applied. Because this is not listed in the default list of applied modifiers (/g, /m), it is confusing, and produces results different to those in PHP. If the /u modifier is applied in PHP then the result is the same as that given by regex101.com. So I think the /u modifier is being applied by regex101.com implicitly.

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by Doqnach** [comment]
Question: where is the string coming from? Is it in some way hardcoded? Is the original string encoded in UTF-8 or ASCII?

I copied your string from your link to https://3v4l.org/3lWDh and it is showing some unexpected behaviour there.

**Comment by firasdib** [comment]
Could this be a discrepancy between PCRE1 and PCRE2?

**Comment by Doqnach** [comment]
My bet right now is a difference in character encoding... (the sources being ASCII, while regex101 does UTF-8 for all input).

**Comment by kkava** [comment]
The string contains some UTF-8 characters (e.g. fancy quotes).
It was copied from https://taz.de/Fehlende-Transparenz-bei-Handel/!5625399/

**Comment by firasdib** [comment]
The site is PCRE-compliant, not necessarily identical to PHP. The only reason PHP is mentioned is because its a very common language that uses PCRE, to help people identify it.

**Comment by firasdib** [comment]
Same issue as this: https://github.com/firasdib/Regex101/issues/1248
