### ISSUE TITLE
Task 9

### ISSUE THREAD

**Issue by ghost** [firasdib/Regex101#1210]
## Quiz Bug
Task 9, i am giving a valid solution but it keeps telling me that 

Test 20/56: The TLD is only allowed to be up to 6 characters long. Hint: if you are not already using anchors, you should start now.

and using this {x,x} which is the way to do it (this is if i am keeping with old standards with the TLD is still 6 characters long) , it keeps saying the same thing

And i have tested this code and it works everywhere outside the realm of quiz

please fix issue

**Comment by firasdib** [comment]
Likely a bug with the test, where yours is matching something its not expecting. I'll have to look into this. Could you email me your regex?

**Comment by sayginify** [comment]
I've got the same with [a-z0-9]+@[a-z0-9]+\.[a-z]{2,6}/i
