### ISSUE TITLE
In Python, regex '\d*|x' cannot match correctly.

### ISSUE THREAD

**Issue by A-hoy** [firasdib/Regex101#1215]
## Bug Description
In Python, regex '\d*|x' cannot match character 'x' in 'x1' and missing position 1 .
![python_re_bug](https://user-images.githubusercontent.com/55936555/67136736-36654e80-f25d-11e9-8e2e-5515b39f3132.png)

I test in python 3.7.3, it should match character 'x', '1' and position 0, 1, 2.
```
>>> import re
>>> text = re.sub(r'\d*|x', 's', 'x1')
>>> print(text)
ssss
```

### Reproduction steps
REGULAR EXPRESSION: '\d*|x'
TEST STRING: 'x1'

### Expected Outcome
full match

### Browser
Yandex 19.9.3.314

### OS
Windows7 32-bit

### User-Agent
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 YaBrowser/19.9.3.314 Yowser/2.5 Safari/537.36

**Comment by wangpeipei90** [comment]
I tried substitution on regex101, and it looked correct to me. 
The results on regex101 show four matches: \d* matches two empty spaces and "1" while "x" matches "x".

**Comment by TWiStErRob** [comment]
The behavior for Python 2.7 looks consistent to me: https://ideone.com/V8ubKp vs https://regex101.com/r/WD8VPe/1
```
Match 1 was found at 0-0: 
Match 2 was found at 1-2: 1
Match 3 was found at 2-2: 
```

Strangely when you run it in JavaScript it also does the same:
`'x1'.match(/\d*|x/g)` resulting in `["", "1", ""]`

However Python 3.5 matches more: https://ideone.com/RSzNr6
```
Match 1 was found at 0-0: 
Match 2 was found at 0-1: x
Match 3 was found at 1-2: 1
Match 4 was found at 2-2: 
```
and so does Perl on Regex101.

Just to confuse things even more, swapping the alternation to `x|\d*` gives different 3 results: https://regex101.com/r/WD8VPe/2

**Comment by wangpeipei90** [comment]
I found in python re spec on re.sub
2.7:  Empty matches for the pattern are replaced only when not adjacent to a previous match, so sub('x*', '-', 'abc') returns '-a-b-c
3.8:  Empty matches for the pattern are replaced only when not adjacent to a previous empty match, so sub('x*', '-', 'abxd') returns '-a-b--d-'.

**Comment by A-hoy** [comment]
> I tried substitution on regex101, and it looked correct to me.
> The results on regex101 show four matches: \d* matches two empty spaces and "1" while "x" matches "x".

@wangpeipei90 
Actually, \d* should have three empty match in Python 3.7.

**Comment by wangpeipei90** [comment]
On "x1", I think there are only two empty matches because the empty between 'x' and '1' is adjacent to the matching "x"

**Comment by A-hoy** [comment]
@wangpeipei90  you're right. I made a mistake because of my carelessness. The expression '\d*|x' only have two empty match in 3.7.
The issue appears when using expression '\d*?|x' which i show in [issue #1219](https://github.com/firasdib/Regex101/issues/1219), because re engine in Python 3.7+ (contain 3.7) is different form Python 3.6 and below.

@TWiStErRob  if you still confuse about the different result, you could see the section 'Advancing After a Zero-Length Regex Match' in https://www.regular-expressions.info/zerolength.html
