### ISSUE TITLE
Set default URL to latest version rather than 1st version

### ISSUE THREAD

**Issue by eh1160** [firasdib/Regex101#1222]
## Feature
By default, when visiting the base URL (without the version parameter), the page defaults to the _1st version_ of the code.  Instead, I propose that the page should default to the _latest_ version.  

This would be really useful when sharing URLs.  I would like to share my regex with co-workers (and link within internal documentation), but currently there is no way to share a link that automatically picks up new changes (at least that I know about).  I could share an existing specific version, but I can't share "latest".  

Revision>>>
I actually just had the bright idea to append the URL with `/latest` and it worked!  I still think this should be the default behavior when the parameter isn't supplied.

**Comment by firasdib** [comment]
`/latest` is the way to go :)

**Comment by eh1160** [comment]
> `/latest` is the way to go :)

Is this documented anywhere?  Seems like a nice, but hidden, feature.

**Comment by firasdib** [comment]
If its not in the wiki we definitely need to add it!

I’ll try to remind myself to look at it soon. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by zachhardesty7** [comment]
I also came across a situation needing the ability to link to the newest version and struggling to find a way. It would be super useful to include a note about that on the modal that provides the link, if not make it the default link to the regex.

**Comment by qubist** [comment]
I tried `/newest` `/n` `/9999` and `/current` before searching and finding this post

**Comment by working-name** [comment]
Added to the FAQ as a first step: https://github.com/firasdib/Regex101/wiki/FAQ#how-to-get--link-the-latest-version-of-a-regex-url-or-entry

**Comment by qubist** [comment]
I still think latest should be the default behavior, not v1. Is there any reason having an unspecified version number in the URL redirect to v1 is better than having it redirect to the latest version?
