### ISSUE TITLE
Delimiter '~' is listed in the menu as '–'

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1225]
## Bug Description
In the "Change delimiter" menu, one of the choices appears to be `–`, but when actually chosen, it turns out to be `~`.

### Reproduction steps
In either regex101 or the regex101 quiz, click the delimiter on the left side of the "Regular Expression" box. This opens a menu of 6 choices; click the `–` option inside that menu.

After some investigation, it turns out that having "Open Sans" first on the list in the "font-family" style is the culprit: `font-family:Open Sans,Lucida Sans Unicode,Lucida Grande,sansSerif;`
Removing it from font-family or moving it to the second option or later fixes the glitch.

This bug occurs unconditionally in Firefox at 100% zoom (and at 70% and 80%, but not other zooms). In Chrome, the bug only occurs (at 100% or 80% zoom) if the font "Open Sans" is actually installed. If the font is not installed, it shows up as `~` in the delimiter menu, but if it is installed, it shows up as `–`. (This is with default system DPI; at other values, results will probably be different.)

In some software, "Open Sans" shows the same bug: WordPad, Notepad++, mIRC
In some other software, the bug doesn't happen: LibreOffice Writer, Character Map (charmap.exe)
On https://fonts.adobe.com/fonts/open-sans the bug shows up only at sizes 15 or 16 with Open Sans Light Italic.
On https://fonts.google.com/specimen/Open+Sans and https://www.1001fonts.com/open-sans-font.html the bug shows up at many sizes, with Open Sans Regular (up to size 13), Light Italic (up to size 16), and Extrabold (up to size 13).

### Expected Outcome
The delimiter choice should show up as `~` in the menu, not `–`.

### Browser
Firefox 70.0 (64-bit)
Firefox 52.9.0 ESR (64-bit)
Chrome 78.0.3904.70 (64-bit)

### OS
Windows 7

**Comment by firasdib** [comment]
I am unable to reproduce this on Linux with Firefox 70.

Is this a windows font rendering issue? can anyone else verify?

**Comment by TWiStErRob** [comment]
hope this helps: Windows 10, Chrome 77

![image](https://user-images.githubusercontent.com/2906988/67909979-07ae7880-fb79-11e9-96e5-f7bfaf4fc3b3.png)
![image](https://user-images.githubusercontent.com/2906988/67910123-6aa00f80-fb79-11e9-992f-0e3ccc37bcf6.png)

**Comment by Doqnach** [comment]
I have this issue less than the above screenshot but the font does render the tilde not very clearly.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.73

![Screenshot 2019-10-31 at 09 12 29](https://user-images.githubusercontent.com/25537191/67929842-a7422a00-fbbe-11e9-98c2-c903e36cb91d.png)

So MacOS 1.14.6 (I need to update still to 1.15), "Open Sans"

**Comment by firasdib** [comment]
This is quite interesting. Is there a way to solve this besides switching font? Or perhaps the delimiter menu should be a monospaced font?

**Comment by TWiStErRob** [comment]
> Or perhaps the delimiter menu should be a monospaced font?
☝️ that!

**Comment by Doqnach** [comment]
Not unless you replace the font renderer in every OS :-P

So yeah, I would go with changing the font of the menu.

**Comment by firasdib** [comment]
Adjusted it, will push it live in the coming days
