### ISSUE TITLE
pcre not match

### ISSUE THREAD

**Issue by Imtinmin** [firasdib/Regex101#1226]
## Bug Description
online not match but in php code is match

### Expected Outcome
match

### Browser
Include browser name and version
chrome

### OS
Include OS name and version

linux

![image](https://user-images.githubusercontent.com/38977612/67916164-cbf2cd80-fbcf-11e9-9abc-0476052170be.png)

the regex is
```
benchmark\s*?\(.*\)|sleep\s*?\(.*\)|load_file\s*?\(|\\b(and|or)\\b\\s*?([\\(\\)'\"\\d]+?=[\\(\\)'\"\\d]+?|[\\(\\)'\"a-zA-Z]+?=[\\(\\)'\"a-zA-Z]+?|>|<|\s+?[\\w]+?\\s+?\\bin\\b\\s*?\(|\\blike\\b\\s+?[\"'])|\/\\*.*\\*\/|<\\s*script\\b|\\bEXEC\\b|UNION.+?SELECT\s*(\(.+\)\s*|@{1,2}.+?\s*|\s+?.+?|(`|'|\").*?(`|'|\")\s*)|UPDATE\s*(\(.+\)\s*|@{1,2}.+?\s*|\s+?.+?|(`|'|\").*?(`|'|\")\s*)SET|INSERT\\s+INTO.+?VALUES|(SELECT|DELETE)@{0,2}(\\(.+\\)|\\s+?.+?\\s+?|(`|'|\").*?(`|'|\")|(\+|-|~|!|@:=|" . urldecode('%0B') . ").+?)FROM(\\(.+\\)|\\s+?.+?|(`|'|\").*?(`|'|\"))|(CREATE|ALTER|DROP|TRUNCATE)\\s+(TABLE|DATABASE)			
```

php code
```php
$filter = "benchmark\s*?\(.*\)|sleep\s*?\(.*\)|load_file\s*?\(|\\b(and|or)\\b\\s*?([\\(\\)'\"\\d]+?=[\\(\\)'\"\\d]+?|[\\(\\)'\"a-zA-Z]+?=[\\(\\)'\"a-zA-Z]+?|>|<|\s+?[\\w]+?\\s+?\\bin\\b\\s*?\(|\\blike\\b\\s+?[\"'])|\/\\*.*\\*\/|<\\s*script\\b|\\bEXEC\\b|UNION.+?SELECT\s*(\(.+\)\s*|@{1,2}.+?\s*|\s+?.+?|(`|'|\").*?(`|'|\")\s*)|UPDATE\s*(\(.+\)\s*|@{1,2}.+?\s*|\s+?.+?|(`|'|\").*?(`|'|\")\s*)SET|INSERT\\s+INTO.+?VALUES|(SELECT|DELETE)@{0,2}(\\(.+\\)|\\s+?.+?\\s+?|(`|'|\").*?(`|'|\")|(\+|-|~|!|@:=|" . urldecode('%0B') . ").+?)FROM(\\(.+\\)|\\s+?.+?|(`|'|\").*?(`|'|\"))|(CREATE|ALTER|DROP|TRUNCATE)\\s+(TABLE|DATABASE)";
$value = "1'or'1'='1'#";
if(preg_match('/' . $filter . '/is', $value)){
    echo 'hello!';
}
```

**Comment by OnlineCop** [comment]
The pattern you have in regex101 contains backslashes so characters are being matched as literals:

`benchmark\s*?\(.*\)` is fine: it looks for a literal '(' followed by stuff, followed by another literal ')'.
`|\\b(and|or)\\b\\s*?` is going to look for a literal '\' followed by a literal 'b' followed by either 'and' or 'or', followed by  '\' then 'b' then '\' then 0 or more instances of 's'.

I think what you wanted there is the unescaped version: `\b(and|or)\b\s*?`

**Comment by OnlineCop** [comment]
Also note that
`" . urldecode('%0B') . "`  on regex101 won't be able to inject the actual characters into that `(...|...|...)` group, so it's an edge case on regex101 that will allow `" ! urldecode'%0B' !` but not in your PHP code: https://regex101.com/r/k0cnpR/1
