### ISSUE TITLE
Show results of a javascript "string".split(/regex/)

### ISSUE THREAD

**Issue by Frozenfire92** [firasdib/Regex101#1227]
## Feature

It would be nice to see how each line would behave if ran thru something like javascript's string split

**Comment by Doqnach** [comment]
One way to do it right now if to run it as a substitution, and maybe use some funky UTF8 icon glyph as the replacement (or simply some newlines). Then you can see each spot the string will split at.

**Comment by firasdib** [comment]
The replacement feature is the closest thing you have
