### ISSUE TITLE
Task 27 allows invalid solutions, and doesn't allow some valid solutions

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1229]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 27: Shorten IPv6

### Bug Description
Various bugs, so I will list each one below. Bug 1 is by far the most important.

#### Bug 1: Some tests only check that a certain input does *not* produce a very specific output
Tests 32-35 only fail if a very specific output is produced.
Test 32: `0000:001:2:3:4:5:6:7` → `::1:2:3:4:5:6:7` fails, but → `:1:2:3:4:5:6:7` does not fail. What if should do is fail if anything other than `0:1:2:3:4:5:6:7` is produced.
Test 33: `0000:00d:2:3:4:5:6:7` → `::d:2:3:4:5:6:7` fails, but → `:d:2:3:4:5:6:7` does not fail. What if should do is fail if anything other than `0:d:2:3:4:5:6:7` is produced.
Test 34: `a:b:c:d:e:f:0000:001` → `a:b:c:d:e:f::1` fails, but  → `a:b:c:d:e:f:1` does not fail. What if should do is fail if anything other than `a:b:c:d:e:f:0:1` is produced.
Test 35: `a:b:c:d:e:f:0000:00a` → `a:b:c:d:e:f::a` fails, but  → `a:b:c:d:e:f:a` does not fail. What if should do is fail if anything other than `a:b:c:d:e:f:0:a` is produced.
(See also Issue #1108, especially the "etc." part of it.)

These tests should be changed to fail if the correct output is not produced.

Before arriving at my valid 30 character solution, I had a 30 character solution that was invalid in the way shown above, incorrectly not failing the tests.

#### Bug 2: Tests 1-3 have non-hexadecimal digits
All three of these tests have a `g` in them. For optimized solutions this won't matter, but if someone submits a solution that checks that the input has only hexadecimal in it, it should still pass all the tests, but due to these three tests, it will not. This confused me at first when I was first starting to solve this task (because my strategy was to start with something overengineered and then pare it down; I started with a version that verified all digits matched `[\da-f]` and never changed any valid IPv6 address into an invalid one, even if the input contained multiple disconnected series of zero hextets, or already contained a collapsed series).

#### Bug 3: Test 22 has an input with only 7 hextet groups (making it an invalid IPv6 address), instead of 8.
For optimized solutions this won't matter, but still, none of the tests should use anything other than valid IPv6 addresses as input. (I think that like Bug 2 above, this may have also resulted in frustrating my initial attempt, which was hard-coded for 8 hextet groups.)

#### Bug 4: There are no tests for `0:001` in the middle of a address
Tests 32-35 check for this at the beginning and end (though, as described above, they are incomplete tests), but there is no corresponding test for the middle.
There should be a test such as verifying that an input of `a:b:c:0000:001:d:e:f` produces an output of `a:b:c:0:1:d:e:f`.
There should also be a test such as verifying that an input of `a:b:000:0:00:0001:c:d` produces an output of `a:b::1:c:d`.

#### Bug 5: There are no tests for `0:0:001` at the beginning or end of an address
Tests 32-35 are similar (assuming they are fixed, as per Bug 1 above), but it's conceivable that a regex could pass those test but fail these:
There should be a test such as verifying that an input of `0000:0:00:001:2:3:4:5` produces an output of `::1:2:3:4:5`.
There should be a test such as verifying that an input of `5:4:3:2:0000:0:00:001` produces an output of `5:4:3:2::1`.

**Comment by firasdib** [comment]
Think i've gotten these right now... Pushed soon ish.
