### ISSUE TITLE
Quick Reference: \v, \V, \R, \N, and (?imsxXU:...)

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1231]
## Bug Description

The description of `\v` and `\V` leaves out that `\v` also matches form feed and is equivalent to `[\n\xB\f\r]` or `[\xA-\xD]` or `[\cJ-\cM]`. And in most apps that support it, CMD/CTRL+ENTER does a form feed, not a vertical tab.

`\R` is incorrectly described in the Quick Reference as being equivalent to `[\r\n]`. This is incorrect because it would only match `\r` and `\n`, and not the other things `\R` matches, which are `\r\n`, vertical tab, form feed, and Unicode newline `\x85`.
`\R` is actually equivalent to `(?>\r\n|\v|\x85)`, or `(?>\r?\n|[\xB\f\r\x85])` if not defined in terms of `\v`.

`\N` is missing from the Quick Reference. It means "any character that is not a newline", and as such, is complementary to `\X`, in that regardless of the current "**s**ingle line"/dotall mode setting, `\N` behaves like `.` does in **-s** mode (just like how regardless of the current "**s**ingle line"/dotall mode setting, `\X` behaves like `.` does in **s** mode).

The Quick Reference includes `(?imsxXU)`, inline mode modifier, but does not include `(?imsxXU:...)` group, which locally applies the mode modifiers only to the `...`, being equivalent to `(?:(?imsxXU)...)`.
Also, the entry for `(?imsxXU)` does not explain that you can combine positive and negative mode modifiers, for example `(?ix-ms)` sets `i` and `x` modes and unsets `m` and `s` modes.

### Additional notes

It would be nice to include in the Quick Reference entry for `\X` that it's equivalent to `(?:s.)`, and for `\N`, that it's equivalent to `(?-s:.)` (except can't be followed by `{`). This would serve two purposes: explaining succinctly what those two things do, and introducing people to the awesome `(?imsxXU:...)` syntax.

**Comment by firasdib** [comment]
@working-name Is this fixed?

**Comment by working-name** [comment]
My apologies, things got busy for me these past few months. Will focus on it this week.

**Comment by gitwdel** [comment]
#1231

**Comment by working-name** [comment]
## The \v issue
Did some more research, it seems (only?) [Microsoft Word](http://web.archive.org/web/20080325092316/http://support.microsoft.com/kb/59096) gets the `CTRL + ENTER` to input a vertical tab but it's not universal. Other software uses `SHIFT + ENTER` to enter a \v while `CTRL + ENTER` will indeed insert a formfeed. For the sake of being complete, I'll just mention what vertical space characters are and refrain from giving software examples.

```php
         U+000A     Linefeed (LF)
         U+000B     Vertical tab (VT)
         U+000C     Form feed (FF)
         U+000D     Carriage return (CR)
         U+0085     Next line (NEL)
         U+2028     Line separator
         U+2029     Paragraph separator
```

**Comment by working-name** [comment]
Implemented missing syntax, fixed/added needed info for the others, and implemented additional notes. Thank you!

**Comment by Davidebyzero** [comment]
@working-name Thanks! Looks great, except for one problem: `\N` is miscategorized. It is in **General Tokens** but should be in **Meta Sequences**.

**Comment by Ouims** [comment]
@working-name always goofing around, i'm telling ya!! :blue_heart:

**Comment by firasdib** [comment]
I'll adjust that, thanks.
