### ISSUE TITLE
Quick Reference: Lookbehind under ECMAScript

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1232]
## Bug Description
When the flavor is set to "ECMAScript (JavaScript)", the Quick Reference descriptions for `(?<=...)` and `(?<!...)` correctly say "Note that this feature is not yet supported on all browsers; use at your own discretion!". However, the sentence "The pattern must have a fixed width." is still in the description, but it is incorrect.

### Expected Outcome
All browsers that support regex lookbehind (i.e., Chrome and Chrome-based) all support it with variable-length, right-to-left evaluation.

**Comment by working-name** [comment]
Thank you David! Adjusted, it will be pushed with the next update 👍

**Comment by Davidebyzero** [comment]
Thank ye, Alan! But now the text be written in Pirate: "The pattern be of variable width."

**Comment by working-name** [comment]
We'll get it right
