### ISSUE TITLE
quick reference - differential description needed

### ISSUE THREAD

**Issue by sbi6c** [firasdib/Regex101#1234]
## Feature
**Many many thanks for your great work on regex101, saved me a lots of time, nerves, ... :),**

pls check the following texts, they are almost the same,

maybe a **more differential description would be even more helpful** as the text currently is, to give the user even higher added value by describing not what these approaches have the same, but also what is different in it

(to understand when/why should I better use the first one, when the second one) as usualy an implementation of two functions instead of one has a reason = each offers something the other does not (of course except some backward compatibility similar functionality commands with different names, etc...:).

Currently:
`Recurse nth relative upcoming subpattern`
**Recurses nth capture group ahead of the current position of \g<+n>. \g<+2> is the second capture group after \g.**
/\g<+1> and (b)/
extra b and b stuff

`Match nth relative upcoming subpattern`
**Recurses nth capture group ahead of the current position of \g'+n'. \g'+2' is the second capture group after \g.**
/g'+1' and (b)/
extra b and b stuff

Thaaaaanks a lot for all the good in your work, God bless you all, Peter+++

**Comment by working-name** [comment]
Hi @sbi6c,

Both `g<..>` and `g'..'` do the same thing. If I were to guess both `'` and `<` were introduced to avoid escaping when the pattern delimiters match one or the other. If not it might be a relic of some kind as you suggested. Either way, there's nothing to differentiate between the two.

Thanks!

**Comment by sbi6c** [comment]
thanks for explaing the background Alan
