### ISSUE TITLE
quick reference - 'Recurse whole pattern' example

### ISSUE THREAD

**Issue by sbi6c** [firasdib/Regex101#1235]
## Feature
Hi, does the example for 'Recurse whole pattern' match the same as the pattern without the use of recursion and even non-capturing group? I mean, if yes, I would be thankful for an example that shows advantage(s) of using the "(?R)" instead:

Currently:
`\[(?:[\w\/ ="-]|(?R))*]`
matches the same as without using (?R)
`\[(?:[\w\/ ="-])*]`
and even without the non-capturing group
`\[[\w\/ ="-]*]`

btw, should not the second "]" be escaped to "\]" ?

Many many thanks for all your help, best regards, God bless you, Peter

**Comment by working-name** [comment]
Hi @sbi6c,

You are correct, the example is absolutely useless. It will be replaced with the next update pushed to the site. Here's one that makes more sense:

```js
/\[(?:[^[\]]|((?R)))+\]/g
// Sample text: [a tag] [or another [inside tag, not matched without (?R)] here]
```

About escaping `]` inside character classes: no, it's not necessary unless it is ambiguous. For example:

`[^[]+` - no escaping needed
`[^]]+` - no escaping needed
`[^[]]+` - the end of the character class `]` is ambiguous. If you escape the inner `]` you meant the character class should include it. If you escape the very last `]` you meant the character class should only contain `[`.

If you need additional help and examples, including on how to use `(?R)`, I encourage you to join us on IRC by clicking the chat icon on the left sidebar of the site.

**Comment by working-name** [comment]
Quickref updated. Thank you again!

**Comment by sbi6c** [comment]
thx a lot for another added value and care, Pete+

**Comment by AlexGuo1998** [comment]
```js
/((?:[^()]|((?R)))+)/g
```
