### ISSUE TITLE
Task 24 incorrect backreferences are accepted

### ISSUE THREAD

**Issue by ArcaneSaint** [firasdib/Regex101#1237]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task24: Outermost brackets

### Bug Description
Backreferences that do not actually contain the outermost brackets are accepted.
Example: in `2 + (x ** (8 + b)) - (2 + 1) ` 
I get the following result: 
**Match 1:**
Full match `(x ** (8 + b))` 
Group 1 `(8 + b)`

**Match 2:**
Full match`(2 + 1)`
Group 1 `1`

It seems as if only the existence of the backreference is checked, and not the contents.
### Reproduction steps
I can send the regex that is incorrectly accepted if requested.

### Expected Outcome
My regex should not match.

### Browser
Chrome 78.0.3904.87

### OS
Windows 10 Pro 64-bit (10.0, Build 18362)

**Comment by firasdib** [comment]
Fixed and pushed live
