### ISSUE TITLE
Update JavaScript to use matchAll

### ISSUE THREAD

**Issue by ChrisKader** [firasdib/Regex101#1240]
[matchAll - Mozilla Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll)

While its not officially part of EMCA, it is already supported by most major browsers along with nodeJS. matchAll not only performs better than regexp.exec, its A LOT easier to use and supports things like map/filter. I would be more than happy to update the code generator if this is something you are willing to support.

**Comment by gitwdel** [comment]
#1240

**Comment by firasdib** [comment]
Its not a bad idea, but doesn't work on older browsers at all. In fact, seems to only work on the more recent versions. I feel this might introduce errors to users who aren't all too familiar with js regex.

Thoughts?

**Comment by Doqnach** [comment]
Option would be to simply have both methods in the code generator, with accompanying comments that explains the difference?

**Comment by firasdib** [comment]
Dup of https://github.com/firasdib/Regex101/issues/1398
