### ISSUE TITLE
qualifier with implicit min length is not parsed

### ISSUE THREAD

**Issue by DavidBiesack** [firasdib/Regex101#1241]
## Bug Description

Enter the regex on regex101.com:
```
^\d{0,14}$
```
the parser shows "{0,14} Quantifier — Matches between 0 and 14 times, as many times as possible, giving back as needed (greedy)" as expected.

Enter the regex
```
^\d{,14}$
```
the parser shows "{,14} matches the characters {,14} literally (case sensitive)"

I'm using ECMAScript RegEx

Running Node.js v8.12.0 accepts `const numberRe = /^\d{,14}$/;` and that matches correctly.

### Expected Outcome
should default to 0 

"{,14} Quantifier — Matches between 0 and 14 times, as many times as possible, giving back as needed (greedy)" as expected.

### Browser
Chrome 78.0.3904.97 (Official Build) (64-bit)

### OS
Mac OS X Catalina 10.15

**Comment by working-name** [comment]
Hi David,

Not sure if that's Node doing something extra or maybe a newly implemented ECMAScript feature, but as of `Chrome 78.0.3704.108` this feature does not exist in the browser. 

Chrome is generally ahead of other browsers when it comes to implementing new JS features, but I also tested in FF and Safari.

**Comment by Doqnach** [comment]
I know that `{3,} is allowed (for 3-or-more), but pretty sure most languages do not support the above `{,3}` (for uptil-and-including-3) notation. It's not very intuitive in some ways... but I'm pretty used to it being this way. Maybe some optimisation of whatever engine nodeJS is using?

**Comment by firasdib** [comment]
Looks like a bug in previous versions of node:

```
> node -v
v12.11.1

> node -e "console.log(/.{,2}/.test('foo'))"
false
```
