### ISSUE TITLE
regex101.com server clock is drifting ahead

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1244]
## Bug Description
As of 2019-11-06, the regex101.com system clock was 220 seconds ahead of the correct time. As of 2019-11-12, six days later, it is now 223 seconds ahead.

The daemon (e.g. **ntpd**) or cron job responsible for updating the system clock via NTP must have encountered a problem preventing it from working, and this probably started about 440 days ago, given the drift rate extrapolated from the above data.

### Reproduction steps
1. Make sure your own system is synchronized with the correct time.
2. View the "date: " field in any HTTP response header for loading a dynamic page (i.e. pretty much any page) from regex101.com, and compare it with your own system's time at the moment the page was loaded. The easiest way to do this is to execute the following on a *nix command line: `wget -qSO/dev/null https://regex101.com; date -u` and then subtract one time from the other.

### Expected Outcome
Like the vast majority of severs on the Internet, regex101.com should have its time well-synchronized.

### Browser
N/A

### OS
N/A

**Comment by firasdib** [comment]
This should now be resolved. Thanks for reporting!
