### ISSUE TITLE
what is the difference between "save regex" and "fork regex"

### ISSUE THREAD

**Issue by wangpeipei90** [firasdib/Regex101#1245]
## Question
It looks unclear to me the difference between these two features as I can always get a link. 
I could save my own regex and fork it, and also fork others' regex.  But what are the scenarios to use "save" and when to use "fork".

**Comment by Doqnach** [comment]
`Save regex` creates a new entry with a perma-link. `Fork regex` creates a copy of the version of the regex you are looking at as a new entry without any of the history. 'Update regex' saves a new version for the currently already saved regex entry.

**Comment by working-name** [comment]
Please reopen if necessary. Closing for now.
