### ISSUE TITLE
Support for \p{L&} or \p{Cased_Letter}

### ISSUE THREAD

**Issue by darthtong** [firasdib/Regex101#1246]
## Feature

Described as:

\p{L&} or \p{Cased_Letter}: a letter that exists in lowercase and uppercase variants (combination of Ll, Lu and Lt).

by:

https://www.regular-expressions.info/unicode.html#prop

Really useful when dealing with languages from around the world! Only used in PHP 7.1, not sure what support other languages/versions have.

**Comment by Doqnach** [comment]
>  The special property L& is also supported: it matches a character  that has  the  Lu,  Ll, or Lt property, in other words, a letter that is not classified as a modifier or "other".

From: http://www.pcre.org/pcre.txt

**Comment by firasdib** [comment]
Thanks. Added the missing `L&`-property. The fix will be pushed live soon.
