### ISSUE TITLE
PCRE operates in UTF-8 mode regardless of 'u' modifier

### ISSUE THREAD

**Issue by Bilge** [firasdib/Regex101#1248]
## Bug Description
PCRE engine operates in UTF-8 mode regardless of whether the `u` modifier is enabled or not.

### Reproduction steps
Pattern: `.{1,50}`
Test string: `私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私私`.

### Expected Outcome
Matches 16 whole characters and two corrupt bytes (of an incomplete 3-byte character). Instead, it matches all 50 characters. This should only happen when `u` modifier is enabled, which by default it is not.

Moreover, the explanation of the `u` modifier is incorrect. It reads:

>u modifier: unicode. Pattern strings are treated as UTF-16.

The actual encoding is UTF-8 as corroborated in [the manual](https://www.php.net/manual/en/reference.pcre.pattern.modifiers.php).

### Browser
Firefox 70.0.1

### OS
Ubuntu 18.04.3 LTS

**Comment by firasdib** [comment]
Since JS uses UTF-16, the library is compiled to use that as well, which might explain whats going on here. If you try matching against something like `😀` you'll see it works differently with or without the `u` flag.

**Comment by Bilge** [comment]
OK but this still doesn't match PHP behaviour.

**Comment by firasdib** [comment]
That is correct. 


Vänliga hälsningar / Best regards,

Firas Dib
