### ISSUE TITLE
Regex with set of charachters dosn't find match

### ISSUE THREAD

**Issue by ankerok-dingdong** [firasdib/Regex101#1249]
Hello. 

I test on JavaScript Falvor the regex ^[\d\\\/.-]{1,}$/g. The test string 1234\2/. expected to match but no matching found.

Thanks.

**Comment by Orabig** [comment]
Your string does contain a '\' which is not matched by your regexp.
May be you'll want :
^[\d\\/.-]{1,}$/g

( explanation : '\' should be escaped, because if you don't, then it just escapes \/ . [\d\/.-] actually means "any chars in \d or \/ or . or -)

**Comment by working-name** [comment]
What I see is the `\` before `2` which is not in your character class, meaning regex won't match that. You need to add `\\` inside the character class if you want your string to match.

If you need further help with regex in general, please join us on IRC by clicking the bottom icon on the furthest left sidebar, or [click here](http://webchat.freenode.net/?channels=regex&nick=re101-gecko-...).
