### ISSUE TITLE
Incorrect "Unmatched parentheses"

### ISSUE THREAD

**Issue by reedy** [firasdib/Regex101#1250]
## Bug Description
Regex incorrectly identified as having unmatched parentheses

### Reproduction steps
`/\\[\\[([^|]+\\|)(.*?)\\]\\]/` with PCRE/PHP

<img width="389" alt="Screenshot 2019-12-03 at 15 14 31" src="https://user-images.githubusercontent.com/67615/70063445-aea28c00-15df-11ea-8631-3c11dade3699.png">

### Expected Outcome

No error about unmatched parentheses

PHP 7.2 doesn't complain about this being unmatched/invalid regex

```
$ php -v
PHP 7.2.24-0ubuntu0.19.04.1 (cli) (built: Oct 24 2019 11:49:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.19.04.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
$ php -r 'preg_match("/\\[\\[([^|]+\\|)(.*?)\\]\\]/", "[[wiki]]");'
`

### Browser
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

### OS
macOS 10.14.6

**Comment by firasdib** [comment]
This is PHP string interpolation thats messing with your head. 

Echo the string, then use it om regex101.com :)


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by reedy** [comment]
> This is PHP string interpolation thats messing with your head. Echo the string, then use it om regex101.com :)

Sure, and that makes perfect sense... But most people aren't going to be adding/removing escaping to test/update/modify a regex...

So it would seem sensible, at least when using the PCRE/PHP flavour that this gets catered for? :)

**Comment by wangpeipei90** [comment]
It should work if you use single backslashes “\[\[([^|]+\|)(.*?)\]\]”.
Here "[" is not escapable character, so \\[ is interpreted as a backslash and a square[, which expects character class.

**Comment by reedy** [comment]
I'm not sure what you mean by it's not escapable... It's asking for a literal `[`, hence the escaping so it's not looking for a character class

`\[\[([^|]+\|)(.*?)\]\]`

<img width="391" alt="Screenshot 2019-12-03 at 19 35 22" src="https://user-images.githubusercontent.com/67615/70083355-22ef2680-1604-11ea-9790-f5e9532fefc8.png">

It works fine (as suggested above) if you replace all `\\` with `\`, but this isn't useful in terms of actually working with regexes and copying back and forth from php code

**Comment by Doqnach** [comment]
@reedy try copying from the code generator instead.

Pasting is annoying I admit, but the website can't really handle all the different ways that strings are escaped for the dozens of programming languages that use a PCRE based regex engine.

What helps there is to use an IDE like PHPStorm that helps you with the copy&pasting from/into PHP code. Go to a regex and use the feature to edit the regex fragment. That will provide a UI that will handle the escaping for you.
