### ISSUE TITLE
Explanation incorrect for \w with python flavour

### ISSUE THREAD

**Issue by darkclouder** [firasdib/Regex101#1251]
# Current explanation
`\w* matches any word character (equal to [a-zA-Z0-9_])`

# Problem
This explanation is unfortunately wrong for python.
`\w` and `[a-zA-Z0-9_]` are actually not the same, as `\w` includes non-latin characters such as umlauts (ä, ö, ü) or even japanese signs (try with 私は), `[a-zA-Z0-9_]` doesn't include those.
The python documenation says
> Matches Unicode word characters; this includes most characters that can be part of a word in any language, as well as numbers and the underscore.
[Source](https://docs.python.org/3.8/library/re.html)

The same problem is in the description of `\W`.

**Comment by working-name** [comment]
Please see #1169
