### ISSUE TITLE
Little Bug

### ISSUE THREAD

**Issue by xiaoerhai** [firasdib/Regex101#1252]
![4EA4FC10-4BAC-45E7-9075-EE13888B057B](https://user-images.githubusercontent.com/48662601/70323831-d6585500-1868-11ea-970b-23dc5dcfc817.png)

**Comment by firasdib** [comment]
Add the `g` flag

**Comment by Doqnach** [comment]
If you still have problems, please visit the (IRC) chatroom to get help on writing regex's
