### ISSUE TITLE
Invalide group construct in quick reference with ECMAScript flavor

### ISSUE THREAD

**Issue by Gurdil** [firasdib/Regex101#1256]
## Bug Description
When ECMAScript flavor is selected under quick reference the group Construction propose the "Negative Lookbehind" and "Positive Lookbehind" pattern even if this pattern is not supported by this flavor.

### Reproduction steps
- Select ECMAScript flavor
- In Group construct select "Positive Lookbehind"
- Copy/paste the example to the regular expression windows
- The example generate an pattern error

### Expected Outcome
"Negative Lookbehind" and "Positive Lookbehind" pattern doesn't appear when ECMAScript flavor is selected

### Browser
Firefox 71.0(64bits)

### OS
windows 10 Pro 1909

**Comment by Doqnach** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

> (Added in ES2018, not yet supported in Firefox)

The quick-reference does not feature-detects this though to hide them if your browser does not support it.
