### ISSUE TITLE
Match number on Test String Panel

### ISSUE THREAD

**Issue by wp-perc** [firasdib/Regex101#1257]
I'd like to have, on each row of the Test String Panel, its match number.

With complex regex that needs to be tested against a large number of possible values, I have to hoover the line, read the match number, then scroll the Matching Information Panel until I find the right match. If I can see the match number at the beginning of every line, I just have to scroll the Matching Information Panel, resulting in a more quickly user experience.

![image](https://user-images.githubusercontent.com/47447882/70948279-6497bc80-205b-11ea-87b5-6b1752cfc602.png)

**Comment by working-name** [comment]
Hi there, just FYI, the opposite is possible: you can highlight the match in the test string by clicking "Full Match" under the match information sidebar

**Comment by wp-perc** [comment]
I see, but you still have to scroll the Match Information panel looking for values you don't expect (and actively read and understand them).
Also, with a lot of groups and matches, colors of selected group match is not so different from the not-selected ones...

Otherwise, by looking at the Test String panel you can spot anomalies very quickly.

**Comment by Doqnach** [comment]
it will also get tricky when having more than one match on a line. The UI would get really full very quickly if you would want to show each and every number.
Also with documents with high amount of matches the number of digits to show can rise to 3+.

**Comment by firasdib** [comment]
I see where you're coming from, but I don't think its viable.
