### ISSUE TITLE
Allow additional URL params for link used in Youtube Video Player

### ISSUE THREAD

**Issue by jereDev89** [firasdib/Regex101#1258]
Adjust Regex to also allow URLs like this:
https://www.youtube.com/watch?v=1ph8qQnjXts&feature=emb_title

This is my Regex:
const youtubeRegex = /(?:https?\:\/\/)?(?:www\.)?(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/;

**Comment by Doqnach** [comment]
Please drop by the (IRC) chat if you are looking for help on writing regex.
