### ISSUE TITLE
Input field - invalid revert input hotkey for macOS

### ISSUE THREAD

**Issue by x1unix** [firasdib/Regex101#1259]
## Bug Description

Invalid *revert* action hotkey for RegExp input field on macOS systems.

*This issue affects only RegExp input field.*

### Reproduction steps

- Open `regex101.com`
- Put some text into **RegExp** text field
- Try to revert changes with `Command-Z` hotkey and get failed.

### Expected Outcome

**Expected:**
On macOS systems, `Command-Z` should be used for **Revert** action.

**Got:**
`Command-Z` doesn't work in regexp field, but default `CTRL-Z` works.

### Browser

Firefox 71

### OS

macOS 10.15.2 Catalina

**Comment by working-name** [comment]
I was unable to reproduce it. Maybe there's some weird software messing with your stuff? Are you remote controlling the mac? FF Addons? Beats me :)

![screencap](https://bugout.regex.ga/input.gif)

**Comment by x1unix** [comment]
@working-name I'm using Razer Blackwidow Chroma keyboard. Maybe Razer synapse software is doing something nasty here.
