### ISSUE TITLE
Unmatched expression

### ISSUE THREAD

**Issue by russell-dunn** [firasdib/Regex101#1260]
## Bug Description
I'm trying to match a simple expression in a block of text but the editor isn't picking it up.

### Reproduction steps
![image](https://user-images.githubusercontent.com/17747205/71246219-283fb700-230e-11ea-9e4b-ebaa7417e6e9.png)

### Expected Outcome
I would expect the '[Client: 192.168.1.1]' line to be matched.

### Browser
Firefox 71.0

### OS
Windows 10 v1903

**Comment by Doqnach** [comment]
Please visit the (IRC) chatroom if you want to get help with writing regex's.

**Comment by firasdib** [comment]
You need the `m` flag.
