### ISSUE TITLE
Wrong group position indicators

### ISSUE THREAD

**Issue by edjm1971** [firasdib/Regex101#1263]
## Bug Description
Group position indicator are incorrect. Unclear if you are intended on starting at 0 or 1 for positions. Either way it is incorrect.

### Reproduction steps
This example contains 15 "foo " values which is 60 characters.
[https://regex101.com/r/aD4zC1/163](https://regex101.com/r/aD4zC1/163)
Currently
Group 0 is : 0-60
1st group match is: 0-16
2nd group match is 16-20
3rd group match is 20-24
5th group match is 24-60

### Expected Outcome
Group 0 should be : 1-60
1st group match should be: 1-16
2nd group match should be 17-20
3rd group match should be 21-24
5th group match should be 25-60

### Browser
Include browser name and version
Google Chrome is up to date
Version 79.0.3945.88 (Official Build) (64-bit)

### OS
Include OS name and version
Windows 10

**Comment by working-name** [comment]
Hi! The way I understand it, position is not the same as a character. Therefore position 0 is the beginning of the input (aka what `^` returns). 

```py
 f o o
^ pos 0

 f o o
  ^ pos 1 (after f, before o)

 f o o
    ^ pos 2 (after o, before second o)

 f o o
      ^ pos 3 (after o, before space character)

... and so on
```

Take [this](https://regex101.com/r/wbKfmB/1) as an example. Your browser generates that emoji as a single character but the match spans two positions.

Hope this makes sense!

**Comment by edjm1971** [comment]
Perhaps this will be a better explanation of what I'm saying.
![sideBySide](https://user-images.githubusercontent.com/9003753/71518595-b32a2f80-2881-11ea-82a6-df3d9efdeddb.png)

Take a look at this graphic I put up from mouseovers on matched items.
You can see from the graphic
group 1 contains pos: 12-16
group 2 contains pos: 16-20
1st, 12-16 and 16-20 are actually representative of 5 characters not 4
So being a match of 4 characters would then take up positions 12-15

2nd If group 1 contains pos:  12-16 then group 2 could not possibly start at 16 as it is part of group 1 and therefore would be starting at pos 17

**Comment by firasdib** [comment]
Normally substrings are inclusive of the start index and exclusive of the end index. 

This is how substring methods are implemented in most languages. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by working-name** [comment]
![position-vs-character](https://user-images.githubusercontent.com/16505052/71525546-1d51cd00-28a0-11ea-93ea-680425f4ddb0.jpg)

This is how my mind sees positions :)

**Comment by firasdib** [comment]
I think we'll close this for now.
