### ISSUE TITLE
ECMAScript crash on lookbehind timeout after PCRE pattern fail

### ISSUE THREAD

**Issue by ctwheels** [firasdib/Regex101#1264]
## Step 1

I saved a regex101 link here: https://regex101.com/r/G4PkoY/1
It's has the following regex pattern:

    (?:\((['"`])(?:(?!\1).)+\1\)|(['"`])(?:(?!\2).)+\2|(\((?:(?3)|[^()])*\)))(*SKIP)(*FAIL)|[^'"`(]+

With options `gm` and the following test string:

    'hello'(hello)('hello')hello((((a)))hello)

---

## Step 2

- [ ] Now change the pattern to `(?<=^[^(]*\()`, which causes a pattern error in PCRE (as expected - variable length lookbehind).
- [ ] Change the flavor to ECMAScript.

The order of the above task list doesn't matter, so long as both are performed, the application crashes.

---

## What seems to cause it?

Removing the `m` flag prevents the crash (if done before completing **Step 2**), but adding it back after completing **Step 2** causes it to crash.

**Comment by Doqnach** [comment]
Nothing happens here? It just works as expected?

Could you please provide some more information, like browser version and OS?

**Comment by firasdib** [comment]
I'm a bit confused, can you please elaborate? Maybe screen record?

**Comment by firasdib** [comment]
Closing as there seems to be no response
