### ISSUE TITLE
Character Class Subtraction

### ISSUE THREAD

**Issue by TonyValenti** [firasdib/Regex101#1265]
## Bug Description
It does not properly parse character class subtraction.

### Reproduction steps
Use this regex:
^[0-9-[2468]]+$

It should accept 0,1,3,5,7,9.  It does not.

### Expected Outcome
See Above

### Browser
Chrome

### OS
Windows 10.

**Comment by working-name** [comment]
Hey Tony,

Character subtraction is not a feature of PCRE/js/py/Go. I'm not aware of all flavors supporting character class subtraction out there but at least these are among them:  ruby, .net, and then a couple more as listed [here](https://www.regular-expressions.info/charclasssubtract.html) - unverified. 

If you'd like to check out the rest of the flavor requests [have a look here](https://github.com/firasdib/Regex101/projects/3). As always, if interested in helping please chime in :)
