### ISSUE TITLE
python raw string incorrect

### ISSUE THREAD

**Issue by zivoy** [firasdib/Regex101#1268]
## Bug Description
you have an r in front of the sting in the when you click on python witch should denote raw string,
meaning that all spacial characters will be canceled out. but it does not

### Reproduction steps
put in a backslash `\` in the input field while in python mode
add some text with backslashes to the input section

### Expected Outcome
the backslashes will be highlighted
but that will only happen if you add in a second backslash `\\`, but that should be unnecessary as its a raw string

### Browser
firefox

### OS
windows 10

**Comment by Doqnach** [comment]
@zivoy did you close it because your above assumption was invalid? or some other reason?
