### ISSUE TITLE
JavaScript Generated code for replace() and named capture groups

### ISSUE THREAD

**Issue by cvlab** [firasdib/Regex101#1269]
## Bug Description
For substitution & named capture groups generated code contain `${name}` instead of `$<name>`

### Reproduction steps
https://regex101.com/r/wKkxSx/1

Generated code:
```js
const subst = `${month}/${day}/${year}`;
```

### Expected Outcome
```js
const subst = `$<month>/$<day>/$<year>`;
```

**Comment by Doqnach** [comment]
The code generator does nothing other than putting your input into a template.
Your link is set to PCRE (PHP), but setting it to javascript shows that the substitution string is actually not valid.
Changing it to javascript, fixing the substitution to `$<month>/$<day>/$<year>` and then going to the code generator, it does show it correctly.

https://regex101.com/r/wKkxSx/2
