### ISSUE TITLE
Horizontal space is not supported in python

### ISSUE THREAD

**Issue by stdedos** [firasdib/Regex101#1270]
## Bug Description
Horizontal space is not supported in Python. (Multiple more, but I don't know where the regex specification for Python is).

### Reproduction steps
Enter `^\h*\+(.+)\+\h*$` on the searh field

### Expected Outcome
`\h` is marked red

### Browser
GChrome 79+

### OS
Ubuntu 16.04.X

**Comment by working-name** [comment]
The site does not state `\h` is supported when in python flavor mode. Instead, the `\h` is not treated as a token at all - it's gray in color like any other literal text you have in there, including `\+`. I don't find the expectation of making `\h` red to be worthwhile or more informative than simply parsing it as plain text.

**Comment by stdedos** [comment]
I guess you are right. Due to the way the regex is read (and the way I tested various inputs), it seems that I had an wrong expectation formed (i.e.: the string never contains `^h*` or `*h$`
