### ISSUE TITLE
Python supports setting flags in the regex

### ISSUE THREAD

**Issue by stdedos** [firasdib/Regex101#1271]
## Bug Description
If flags are given at the beginning of the regex, REPL flags should follow the flags set on the regex string itself.

### Reproduction steps
`(?mu)^\h*\+(.+)\+\h*$`

```
"(?mu)^\h*\+(.+)\+\h*$"
mu
All the errors detected are listed below, from left to right, as they appear in the pattern.
(? Incomplete group structure
) Incomplete group structure
```

### Expected Outcome
* Pattern is recognised
* `mu` flags are set, without removing them from the regex string
* Aforementioned flags have a two-way sync with each other (?)

### Browser
GChrome 79+

### OS
Ubuntu 16.04.X

**Comment by Doqnach** [comment]
Inline flags and global flags are two different things... I don't think your expectation of having the global flags be in sync with the inline flags is correct.

**Comment by stdedos** [comment]
> Inline flags and global flags are two different things... I don't think your expectation of having the global flags be in sync with the inline flags is correct.

True, but I don't expect that a user will ever have a different set of flags set.
User will either have global flags set, or inline.

Assuming I am making sense, then this would only help a user in copy-pasting between his code and his playground.

The only issue I see is if the user explicitly wants to set global flags, and, at the same time, explicitly does not want to set inline flags. However, this could be easily solvable (`if user-pasted string has no inline flags, then don't attempt to create them`)

**Comment by mari77111** [comment]
Regex

**Comment by mari77111** [comment]
Regex

**Comment by firasdib** [comment]
`g` isn't a valid flag in python, but its kept to keep a consistent UI and UX on the site.

If its included, the regex will be invalid when used in code. I try to refrain from that as much as possible.
