### ISSUE TITLE
Python: Unknown extension `?g`

### ISSUE THREAD

**Issue by stdedos** [firasdib/Regex101#1272]
## Bug Description
`(?g)` is not a valid flag for python

### Reproduction steps
![image](https://user-images.githubusercontent.com/133706/72641828-b17cf480-3973-11ea-859f-e5b7678279e5.png)

### Expected Outcome
_Does not exist_

### Browser
GChrome 79+

### OS
Ubuntu 16.04.X

**Comment by working-name** [comment]
Hello stdedos,

`/g` and `(?g)` are two different notations. The first is a flag, the second is an inline flag. I'm not sure how you got the site to accept an inline `g` flag, I was not able to.

As far as py and php are concerned (and maybe others that I don't know of), those have separate functions for non-global and global matching. The site will accept the `/g` flag for ease of use and a clutter-free UI.

If you then look at the code generator you'll see that the `/g` flag is used to determine whether `re.finditer` should be used.

**Comment by stdedos** [comment]
True dat. Maybe I was a bit taken away by https://github.com/firasdib/Regex101/issues/1271

**Comment by stdedos** [comment]
++ I was processing line input (and not the whole string), and I missed the nuances between search/match/find#.

Damn the Python way to "handle" strings ....
