### ISSUE TITLE
JavaScript quick reference for \L, \U, \E and \x

### ISSUE THREAD

**Issue by learnbyexample** [firasdib/Regex101#1273]
## Bug Description

* `\L`, `\U` and `\E` are not supported in JavaScript as far as I know. But these are listed in quick reference.
* Hexadecimal replacement values `\x{06fa}` should be `\u{06fa}`
    * Also, `\u{}` format isn't working on the site, see https://regex101.com/r/9DjcdL/1 and works when `{}` is omitted, see https://regex101.com/r/9DjcdL/2. I have set the `u` flag, but based on my experiments on console, seems `u` flag is needed for `\u{}` format only for regexp definition and not needed in replacement section.

See also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet 

### Browser

Chromium Version 79.0.3945.79

**Comment by Doqnach** [comment]
Can confirm that both notations (`\u{03b1}` and `\u03b1`) work in an ES6 compatible browser.

```
> console.log("\u{03b1}", "\u03b1")
  α α
```

**Comment by working-name** [comment]
> * `\L`, `\U` and `\E` are not supported in JavaScript as far as I know. But these are listed in quick reference.

Fixed, will be pushed with the new update.

**Comment by working-name** [comment]
Resolved by #1330
