### ISSUE TITLE
Please make task 11 optional

### ISSUE THREAD

**Issue by ChrisForsythe** [firasdib/Regex101#1274]
Quiz 11 assumes you know what sentences like the following mean:

Test 31/63: You must not allow for decimals in the exponent. Don't match 1.61e8..

However you have to know both what an exponent is and what this notation is, and then why the example shouldn't match. 

This task is rampant with these rules which require further and further lengthy research into a level of math I do not believe should be required to learn regular expressions. Please consider making this task optional.

**Comment by firasdib** [comment]
I mean, the rest of the tasks aren't going to get any easier. There are some rules, but is it really too much? Perhaps the description should include more information of whats expected?

**Comment by ChrisForsythe** [comment]
If it had two lists, ^(?:do not) match this list$

And then provided each list of strings to match and not match then you wouldn’t need to know whatever notation this is. Otherwise yes this is fairly difficult if you haven’t taken a math class in 25 years and was never presented this type of math when taking it.

**Comment by jk-fm** [comment]
I get the error "Do not match 1.2e" - well I get this error even if I don't match e at all. So what the heck? Then I added a simple pattern to also match e followed by at least a number but get the same error. 

The  error-descriptions are much less precise than the expected solutions we've never been asked for. And tbh, that is very arrogant.

**Comment by firasdib** [comment]
@ChrisForsythe Perhaps we can rework the description with some examples and helpful links to understand the syntax.

My apologies @jk-fm, I try to do my best to maintain this website for free on my spare time.
