### ISSUE TITLE
wrong results in multiline

### ISSUE THREAD

**Issue by fda-odoo** [firasdib/Regex101#1275]
## Bug Description

Regex match lines that shouldn't match.
Given url is self-explainatory - in multi-line and with ^ and $, regex match lines that it shouldn't if next lines match

### Reproduction steps

check these url: 

https://regex101.com/r/osZQL0/6 - not ok
https://regex101.com/r/osZQL0/7 - ok

### Expected Outcome

Other lines doens't change results

### Browser
Include browser name and version

Chrome - 79.0.3945.130

### OS
Include OS name and version

Ubuntu - 18.04

**Comment by Doqnach** [comment]
I'm unsure how version 6 is wrong? Seems to behave like expected. The look-ahead will span multiple lines since you are using `\D` which will also match EOLs, so it will wrap to the next like and match the `5` for the `\d`.

**Comment by fda-odoo** [comment]
Ok my bad. I didn't expect \D to catch \n too. I find it weird in a multiline mode, but ok, it's a misunderstanding from me, sorry.
In fact I was thinking that in multiline mode, the regex would be tested on each line separately and so the \n wouldn't be tested...

**Comment by Doqnach** [comment]
the `m` flag only changes the behaviour of `^` and `$`, where they will match the beginning and end of a line, instead of beginning and end of the entire string. Everything else just works in the same way.
