### ISSUE TITLE
dot should not match \n or \r

### ISSUE THREAD

**Issue by jianlin** [firasdib/Regex101#1277]
## Bug Description

https://regex101.com/r/tNlHzp/1

a.*b
should not match
a\r\nb

not `s` flag was used by the way.

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by working-name** [comment]
Hi jianlin,

The \r and \n are literal. The browser can handle a newline character (enter key), but it does not emulate \r or \r\n. Just remember these characters are invisible. 

Hope this helps :)

**Comment by jianlin** [comment]
> Hi jianlin,
> 
> The \r and \n are literal. The browser can handle a newline character (enter key), but it does not emulate \r or \r\n. Just remember these characters are invisible.
> 
> Hope this helps :)

Inside of NodeJS:

```
> "a\r\nb".match(/a.*b/)
null
```

but on https://regex101.com/r/tNlHzp/1 
it does, so it is misinformation provided to the users?

**Comment by Doqnach** [comment]
@jianlin the "test string" is treated as plain text. The `\r\n` there are simply 4 individual characters, not a `CRLF`.

https://regex101.com/r/tNlHzp/2

**Comment by jianlin** [comment]
> @jianlin the "test string" is treated as plain text. The `\r\n` there are simply 4 individual characters, not a `CRLF`.
> 
> PS: please note that CodeMirror does not support `carriage return (\r)` in textfields so any "end of line" sequence will be converted to `line feed (\n)` only.
> 
> https://regex101.com/r/tNlHzp/2

this might be confusing at times to some users... when they thought they have got something that works but in fact they are not dealing with `\n` but with a backslash and `n`. I wonder if you can have a "string" mode and a textbox mode, where the textbox is "pasted in content" and so `\n` will just make the text go to the next line instead of showing `\n`, and then a string mode that actually represent all internal encoding of a string `"abcde\r\nfghijk"`

**Comment by firasdib** [comment]
This is how input fields work in every application, everywhere, on every system. Changing this behavior will just cause more confusion.
