### ISSUE TITLE
Export Matches should support Select All

### ISSUE THREAD

**Issue by equin0x80** [firasdib/Regex101#1278]
Thanks for this good tool. I think that Export Matches > Plain Text should offer a Select All command. Ctrl+A selects the entire page including tooling (not useful) and right-clicking the results box (in Chrome at least) does not offer Select All: apparently it is not a standard text box.

**Comment by Doqnach** [comment]
At the top right corner there is a "copy to clipboard" button for me, or is that maybe some extension of my browser?

I agree that the UX might be better with a textarea (with e.g. CodeMirror), rather than a div.

**Comment by working-name** [comment]
<img width="114" alt="Screen Shot 2020-01-30 at 4 19 00 PM" src="https://user-images.githubusercontent.com/16505052/73491349-710e7500-437c-11ea-97b4-91e1a3b4e0fd.png">

(I was about to post that, thank you Doqnach)

**Comment by equin0x80** [comment]
Yep, works fine for me (latest Chrome on Win64) and I simply missed it because that's not copy and select works in native Windows apps, and I suppose there's no standardised way to do it in "Web apps".  Only semi-relatedly, I would ask that you consider showing the results in a proper HTML text box (input type="text") so that it supports the usual select operations.  This will also improve usability for people with disabilities: I'm not throwing out buzzwords here... I used to work with a blind colleague and it was incredibly frustrating to see how she was blocked from doing everyday basic things simply because pages were not designed properly.  Thanks again for this great regex tool and for considering my suggestion.

**Comment by working-name** [comment]
On a mac, the voiceover thing has no difficulty reading the explanation and results sidebars although they are not textareas. But that's where usability stops, it does not recognize the export icon link.

Narrator on Windows is able to recognize the export icon link but it ignores the modal pop-up.

That being said, as of right now, the website does not seem to have been built with this level of accessibility in mind. Additionally, I don't think our current technology is there yet - at least as far as macOS is concerned - I could not make it recognize the export button as an action. Voiceover struggles to read basic things like `a{3}` or `one or more of a` as an explanation for `a+` and so on. Same goes for Narrator which fails even harder by simply ignoring `{` and other such 'punctuation'. I think the notation is technical in nature and having voiceover software properly read things is a big challenge yet to be overcome.

Therefore the decision to make export matches -> plain text a textarea has 0 effect on current accessibility tools available for the vision-impaired.

**Comment by firasdib** [comment]
The app is by no means designed for accessibility in mind, that'd be quite a tedious task to get 100% right.

But I do agree these fields would be better as a selectable component. I'll look into it.

**Comment by equin0x80** [comment]
OK.  Closing issue because the original issue was really just me failing to find a feature.  I hope you can improve accessibility but that's really a separate deal.  Thanks for the helpful feedback.
