### ISSUE TITLE
TASK 7: "Validate an IP" does not accept backreferencing groups

### ISSUE THREAD

**Issue by jk-fm** [firasdib/Regex101#1279]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!
...meh! ok.

### Task
Please write both task name and number.
TASK 7: Validate an IP

### Bug Description

The quiz does not like my solution. I'm using \g'1' in the regex to reference a preceding group.

I get the Error :
"Test 132/134: Don't create backreferences when you don't need them. If you need to group, use (?:regex); it's the same as (regex) but it doesn't create a backreference."

### Reproduction steps

I shall not tell you the solution. My score would be 52.

### Expected Outcome
It should match when using a backreference. The test thinks you don't need it. that's correct for a replacement string, but I need it within the pattern itself.

### Browser
Include browser name and version
firefox 72

### OS
Include OS name and version
win10

**Comment by Doqnach** [comment]
See #1209, this is intentional.

**Comment by georgytom98** [comment]
you can achieve 44 chars even with the current rule set of no backreference: `^(?:(?:1?\d?\d|2[0-4]\d|25[0-5])\.?\b){4}$`
