### ISSUE TITLE
Automatic System Dark Mode

### ISSUE THREAD

**Issue by flostellbrink** [firasdib/Regex101#1280]
## Feature: Automatic System Dark Mode

I appreciate that regex101 already has a dark mode.
However, dark mode preferences can change depending on the time of the day.
Fortunately, the system wide dark mode from (among others) windows, macOS, and iOS can be read from the browser.

Given that you already have an options menu for this, it would be great to have a default automatic option. That one could simply attach an event listener to [`window.matchMedia`](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and update the dark mode according to the [`prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

I found this [blog post with a small example](https://www.freecodecamp.org/news/how-to-detect-a-users-preferred-color-scheme-in-javascript-ec8ee514f1ef/) that explains it a bit better :)

I think this would be a great addition, because only a small portion of those who would appreciate the dark mode ever go into the settings. This could make that feature much more accessible!

**Comment by firasdib** [comment]
This is implemented
