### ISSUE TITLE
[matches] Copy to clipboard nonfunctional

### ISSUE THREAD

**Issue by despecial** [firasdib/Regex101#1281]
## Bug Description
Exporting matches are not copied to clipboard

### Reproduction steps
Make a regex test with matches in the right sidebar.
Click "export matches" (which is mostly hidden by a scrollbar) and then hit the copy to clipboard icon. Or mark all entries and click the button. Both steps are not working

### Expected Outcome
Popup content in clipboard

### Browser
Firefox (72.0.2)

### OS
MacOS Mojave

**Comment by Doqnach** [comment]
Maybe related to #1267 ?

**Comment by firasdib** [comment]
Should work as intended now!
