### ISSUE TITLE
Description for \D unnecessarily contains an escape character

### ISSUE THREAD

**Issue by DavidMetcalfe** [firasdib/Regex101#1282]
## Bug Description
Description for "\D" unnecessarily contains an escape character.

![image](https://user-images.githubusercontent.com/80915/73705056-a92df480-46a9-11ea-82d1-a19256e50984.png)

### Reproduction steps
1. Use "\D" in the Regular Expression
2. Read the Explanation and note "\D matches any character **that\'s** not a digit (equal to [^0-9])"

### Expected Outcome
The explanation reads "\D matches any character that's not a digit (equal to [^0-9])" instead

### Browser
Chrome Version 79.0.3945.130 (Official Build) (64-bit)

### OS
Windows 10

**Comment by DanTalash** [comment]
This seems related: if your regex is searching for \x22 (double quote) then the preview will incorrectly escape it to a `&quot;`. See below screenshot.

![image](https://user-images.githubusercontent.com/3004715/74988037-94639780-53f1-11ea-9382-6dd43f6d6dd5.png)
