### ISSUE TITLE
Import (and unescape!) regular expressions pasted from quoted strings

### ISSUE THREAD

**Issue by cameronkerrnz** [firasdib/Regex101#1284]
## Feature

I would find Regex101 to be have much greater utility if I can copy and paste a string from some program source (eg. in a JSON string) and have it automatically (and correctly) unescape the string.

I suppose this is somewhat the reverse of code generation, but much simpler in scope.

Thanks!

**Comment by Doqnach** [comment]
Related to #1112 #1038 #1019 #979

**Comment by firasdib** [comment]
It would be fairly hard to know when you want to unescape something, and when the escaped text is part of the regular expression.

**Comment by working-name** [comment]
Closing for now, please reopen if deemed necessary.
