### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by dragokas** [firasdib/Regex101#1285]
## Feature

Hi, can you provide please link to offline version installer of your tool previously available on your site?

Thank you.

**Comment by Doqnach** [comment]
The site works offline once it's in your cache.

See #76 #322 #707 #945 #1099.

**Comment by dragokas** [comment]
No. I read all topics. That's not the same I'm asking about.

Previously, you had installer on your site:
 - without dependency on browser (chrome)
 - it was dependent on Adobe AIR only.
 - it is based on python script.
 - no internet connection needed

**Comment by Doqnach** [comment]
That was a community script and not something officially supported by the website, see  #945 (which you already did).
