### ISSUE TITLE
About backslash bug when choose PCRE(PHP)

### ISSUE THREAD

**Issue by dollzcx** [firasdib/Regex101#1290]
## Bug Description
I want to match the 'index' in string like 'E:\web\new\index.html', so i use pattern 
`'[^\\]*(?=\.html)',` it works on site https://regex101.com, but it didn't work in PHP, which should be 
`'[^\\\\]*(?=\.html)'` cause 4 backslashes trans to 1 backslash in the end.

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by working-name** [comment]
Hi there,

That’s php specific escaping needs. Perl for example doesn’t need that and it’s the same reflex flavor. 

The site is a regex tester first and foremost, therefore working with escaping needs of various languages will quickly bloat regexes and make them even more unreadable. 

That being said, the site does have a great feature called code generator which will escape the regex properly for you, given the example code it generates. Try it out, it’s on the left sidebar. 

Please let us know if you have further questions.
