### ISSUE TITLE
Add a progressive web app manifest.

### ISSUE THREAD

**Issue by PhonicUK** [firasdib/Regex101#1292]
## Feature

Regex101 is something that I use so often that I've added a chrome shortcut to launch it directly sans-browser.

A proper web app manifest would make this feel more like an actual desktop application for those who use it frequently.

Basic support for this requires little more than a valid manifest.json file and a reference to it in the main pages HTML. Among other minor perks, this also allows you to control the title bar color of the window to blend in with the title bar at the top of the application and specify the icon to be used for the 'application'.

This would also improve the offline experience as a fully fledged progressive web app with a web worker can explicitly cache certain application assets and make sure they're up-to-date.

**Comment by Doqnach** [comment]
Is this related to the last comment in #1180?

**Comment by PhonicUK** [comment]
Looks like it yes, if a manifest does already exist then its data is invalid.

**Comment by Doqnach** [comment]
could you please also link to the place you did the audit or the audit results?

**Comment by PhonicUK** [comment]
It's a feature built into Chrome Devtools called Lighthouse. Browse to site, hit F12 -> Audits -> Select just "Progressive Web App" under categories and hit "Generate Report"
