### ISSUE TITLE
Strange Behavior with .* versus *. 

### ISSUE THREAD

**Issue by AaronJaegerVA** [firasdib/Regex101#1293]
Regex: ^/.*/*./[A-Z]{3,}$

This is matching /u02/a/ADS and /u02/a//////ADS as expected, but also matches /u02/aaa/ADS which I would not expect. 

---
name: Bug Report
about: Report a bug
labels: bug
---

## Bug Description
Strange Behavior with .* versus *. 

### Reproduction steps
Regex: ^/.*/*./[A-Z]{3,}$

This is matching /u02/a/ADS and /u02/a//////ADS as expected, but also matches /u02/aaa/ADS which I would not expect. 

### Expected Outcome
I expect ^/.*/*./[A-Z]{3,}$ to _not_ match /u02/aaa/ADS

### Browser
Chrome 80.0.3987.87

### OS
Windows 10 1809

**Comment by Doqnach** [comment]
Please provide a link to regex101 showing the behaviour.

`.*` means "matches any character (except for line terminators), Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)". That means that `/.*/.*/` will also 'eat up' any intermediate slashes, and not stop at the first. If you want it to stop at the first slash it meets, you want to use it 'non-greedy' like so: `/.*?/.*?/`: "matches any character (except for line terminators), Matches between zero and unlimited times, as few times as possible, expanding as needed (lazy)".

https://regex101.com/r/4Qi4Go/1 see the explanation here on the right pane.

**Comment by AaronJaegerVA** [comment]
The issue was really how regex101.com seemed to treat ‘.*’ the same as ‘*.’ but perhaps with the “greedy” behavior you described and my whole pattern, something was not as it seemed.

Sincerely,

Aaron Jaeger
Systems Administrator
ETS TSEI
Perspecta
Enterprise Testing Service (Station 116) (005Q)
VA OIT EPMD
727-320-1972
[Title: EPMD logo - Description: EPMD logo][Title: ETS logo - Description: ETS Flame logo]
