### ISSUE TITLE
Task 6 - Whitespace false positive

### ISSUE THREAD

**Issue by jacksonrya** [firasdib/Regex101#1294]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 6: Broken Keyboard

### Bug Description
False positive when the duplicated character is a space.

### Reproduction steps
Use \S

### Expected Outcome
Add test case for successive whitespaces.

### Browser
Chrome - Version 80.0.3987.122 (Official Build) (64-bit)

### OS
Windows 10 Pro - Version 1903

**Comment by firasdib** [comment]
I'm not entirely sure how to reproduce this. Could you please post full reproduction steps to contact@regex101.com?

**Comment by firasdib** [comment]
Fixed
