### ISSUE TITLE
Save/Navigate:  Find latest version of the regular expression.

### ISSUE THREAD

**Issue by merriam** [firasdib/Regex101#1295]
## Feature

Three closely related features for saved regular expressions:

* Resolve link to a regular expression to highest valid version number.  For example, https://regex101.com/r/K2vfEJ should resolve to https://regex101.com/r/K2vfEJ/3 not https://regex101.com/r/K2vfEJ/1.  This allows a link to embedded in code documentation and not go out of date the moment a new example is added.
* Save of a link by anyone but the owner increments a different series.   This prevents accidental or intentional abuse to saved regular expressions.  That is, if someone other than me (who created https://regex101.com/r/K2vfEJ/3) edits and saves the regular expression, it would be saved as https://regex101.com/r/K2vfEJ/others/1.  It also gives you the option, at a later date, to allow a subscription model to allow more complex sharing.
* If there is a newer version of a saved regex, change the shading or background of the version pop-down menu (the v1 down-caret next to "REGULAR EXPRESSION") to be more noticeable.

Let me know if you wish a pull request or sample documentation.

**Comment by firasdib** [comment]
- You can use https://regex101.com/r/K2vfEJ/latest to get the latest version, always
- If you sign in, you can "lock" permalinks, so only you (the owner) can add new revisions. Others are then implicitly given read access only.
- Perhaps one could show an "outdated" flag somewhere?

**Comment by merriam** [comment]
Magic!  Thank you,

**Comment by Doqnach** [comment]
Should this be reopened because of that last point (outdated flag)?
