### ISSUE TITLE
Favorites for QUICK REFERENCE

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#130]
I'd love to be able to "favorite" one or more QUICK REFERENCE entries. It would probably need to be flavor-aware, of course, so I only see relevant ones for Javascript but different ones for Python/PHP.

**Comment by firasdib** [comment]
I don't really think this is something worth investing time in. I fear it will clutter and complicate things unnecessarily. Reopen if you feel otherwise!
