### ISSUE TITLE
Is there a way to match R regex where a double escape is required?

### ISSUE THREAD

**Issue by jzadra** [firasdib/Regex101#1300]
In R, it's necessary to double escape special characters.  Ie matching 4 digits on regex101 is:
"\d{4}"

While in R, you have to escape the escape:

"\\d{4}"

Typically I just add the backslash when I get my expression the way I want it and move to R, but is there any way to set Regex101 to use that double backsplash?

**Comment by Doqnach** [comment]
R is not a supported flavour yet.

Closest you can get was to just write the regex as normal and then check the code generator for java: https://regex101.com/r/ADdocE/1/codegen?language=java.

You can help get R added as a supported 'code generator' language by following: https://github.com/firasdib/Regex101/wiki/Writing-a-Code-Generator

**Comment by TomAuger** [comment]
I have the same issue, but it's for Java. Currently Java is not in the list of supported languages, nor is it available in preferences, so the above comment from @Doqnach isn't jiving with me. If it's possible to add that option (back?) to the list of language options, that would be nice. Removing the escapes and then adding them back in after pasting into code is a (bit) of a pain... might have to write a RegularExpression to automate that.... ;)

**Comment by working-name** [comment]
Facilitating pasting of language-specific escaped regexes is sometimes requested here. There's a lot of variability out there not only within a particular language but also across programming languages. This may not be feasible to implement outside of Doqnach's suggestion. See #1038 for the [current official response](https://github.com/firasdib/Regex101/issues/1038#issuecomment-415096820).

Closing for now, please reopen if deemed necessary.
