### ISSUE TITLE
Show only matched or non matched lines

### ISSUE THREAD

**Issue by sparetimesplunker** [firasdib/Regex101#1302]
I would like to ask for a feature where you can choose to show only matched or not matched lines in the test string box.

In my daily routine sometimes it is needed to see if a regex matches all lines, or to show only those witch didn't match or vice versa.

Would be really great!

**Comment by Doqnach** [comment]
matches don't always span a single line, so that makes it hard to make a unified UI for this. Gets even worse when having look-arounds spanning lines.

Showing the lines that did not match you can cheat at by using an empty substitution and checking what is left in that pane.

**Comment by sparetimesplunker** [comment]
I understand, thanks a lot for your response and for the hint.

**Comment by working-name** [comment]
It seems a solution was reached for now. Please reopen if deemed necessary.
