### ISSUE TITLE
Inconsistent results across browsers

### ISSUE THREAD

**Issue by StephenCarboni** [firasdib/Regex101#1304]
## Bug Description

Given this regex: https://regex101.com/r/qp7xCa/1

Firefox, 76.0a1 (2020-04-03) (64-bit), complains "? The preceding token is not quantifiable"
Chrome, Version 80.0.3987.163 (Official Build) (64-bit), does not complain.

**Comment by working-name** [comment]
Hi there!

Mozilla [knows about it for 4 years](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665) already.

If you open your console while on the site you'll see the warning about what your browser doesn't support.

**Comment by working-name** [comment]
Please reopen if deemed necessary
