### ISSUE TITLE
Task 7 false positive with leading zero

### ISSUE THREAD

**Issue by Haksell** [firasdib/Regex101#1305]
## Bug Description
My "solution" matches wrong IP adresses like "01.2.3.4" but still passes all tests.

**Comment by firasdib** [comment]
Fixed

**Comment by firasdib** [comment]
Actually... I ended up reverting this change. Its too limiting, and in fact, the IP is still "valid"...

**Comment by liudongmiao** [comment]
@Haksell 01 is valid, however, 010 is invalid.

As a leading zero followed by only a digit is valid (won't be treated at oct encoded).
