### ISSUE TITLE
Non-capturing group (?:) is badly titled

### ISSUE THREAD

**Issue by alystair** [firasdib/Regex101#1306]
## Bug Description
I was very confused when I couldn't find a way to group, but not capture elements.

![image](https://user-images.githubusercontent.com/159109/78960512-4a776380-7abc-11ea-8eb1-4f9c7b5b1dea.png)

Looking at the listing as it is, or searching - you would never realize what `?:` does unless you clicked through and you saw the extended "but won't create a capture group." description.

Should be titled 'Non-capturing group' or something similar including 'non-capturing' similar to Atomic group.

### Reproduction steps
Search for 'non-capturing' or similar

### Expected Outcome
Non-capturing group `?:` should appear.

### Browser
Include browser name and version
irrelevant

### OS
Include OS name and version
irrelevant

**Comment by working-name** [comment]
Hello! Sure, that should work just fine. It will be pushed with the next update. Thank you!
