### ISSUE TITLE
a non valid expression is defined as valid

### ISSUE THREAD

**Issue by randll32** [firasdib/Regex101#1307]
![изображение](https://user-images.githubusercontent.com/27913875/79043713-e2d32c80-7c11-11ea-9d03-3e8730ebfaa6.png)

**Comment by SuperSandro2000** [comment]
What about this expression is invalid?

**Comment by randll32** [comment]
the search should fail due to "[\d-\-]{10}". or am I wrong?

**Comment by randll32** [comment]
apologize. this is because the php interpreter swears at the format
`Compilation failed: invalid range in character class at offset 4 in <b>[...][...]</b> on line <b>4</b><br />` in php 7.3 and over
if the pattern is valid, I think you can close the ticket

**Comment by firasdib** [comment]
The pattern is valid, but perhaps you're not using the code generator when copying it?

**Comment by randll32** [comment]
![изображение](https://user-images.githubusercontent.com/27913875/79388761-f7e7ec80-7f7e-11ea-82ed-7f3252589d67.png)
I use code generation
![изображение](https://user-images.githubusercontent.com/27913875/79388831-19e16f00-7f7f-11ea-8ab7-a4f9202dc4e5.png)

**Comment by working-name** [comment]
You are asking for regex to grab characters between digits and a `-`. Whether that's what you meant to do or not - no idea, but the regex itself is technically valid.

May I suggest we talk about this on [IRC / live help](http://webchat.freenode.net/?channels=regex&nick=re101-wolf-...)?

**Comment by randll32** [comment]
ok
