### ISSUE TITLE
Recursive Entire Patern from Quick Reference BUG!

### ISSUE THREAD

**Issue by alexalex1024** [firasdib/Regex101#1309]
## Bug Description
Recursive Entire Patern from Quick Reference->engine error or infinite loop
### Reproduction steps
Recursive Entire Patern from Quick Reference->engine error or infinite loop

### Expected Outcome
like in the quick reference

### Browser
Include browser name and version
last firefox
### OS
Include OS name and version
unbuntu16.04

**Comment by Doqnach** [comment]
https://regex101.com/r/yupjRb/1

Confirmed.

**Comment by working-name** [comment]
Hey there, thanks for bringing this to our attention. There's a typo but not quite sure why, probably has to do with me being derpy on the escapes. That should have been:

`\((?:[^()]|((?R)))+\)`

But it could be further improved.

Either way, this fix will be pushed out on the next update cycle. Thanks again!

**Comment by working-name** [comment]
done.
