### ISSUE TITLE
Wrong text displayed

### ISSUE THREAD

**Issue by GodModus** [firasdib/Regex101#1311]
## Bug Description
Please see the image below. Its quite discriptive in what the issue is. The wrong \c is used in the example. \cI is a horizontal tab. The text says vertical tab. This should be rectified.
https://www.dropbox.com/s/se40owrhlkihna9/Screenshot%202020-04-16%20at%2012.02.35.png?dl=0
### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by working-name** [comment]
Thank you for bringing this up to our attention. This will be rectified in the next update.
