### ISSUE TITLE
Adding two targets for unitary tests: custom capture group, and substitution

### ISSUE THREAD

**Issue by verdy-p** [firasdib/Regex101#1315]
## Feature
It is possible to create unitary tests only for matches. But there's no unitaty tests for substitutions, where one would enter a substitution pattern, including not just one but possibly more capture groups (possibly surrounded by text transforms like \U or \L terminated by \E), plus some static separators, and expect a specified result.

So to the list displayed as possible "Target", containing only:

 * "regexp" : tests if the input string in the unit test "does match" or "does not match" with the tested regexp.
 * "full match", "capture group 1", ..., "capture group 10" : test if the returned capture group from "0" to "10" returns a value that verifies a selectable assertion, which can be either
   * "starts with", "ends with", or "contains" a specified "comparison string", or
   * "is null" or "is not null" (another possible test to add).
add these two targets:
 * "custom capture group": add an input field to specify another group number (above 10) or group name, and work like with "full match".
 * "substitution": add an input field to specify the "substitution string", before the selectable "assertion" and the input field for the "comparison string" (like with capture groups)

**Comment by verdy-p** [comment]
Also allow adding more than one comparison strings, and then expect that the tests for full match, capture groups, substitution will return the same number of matches verifying the assertion for each successive comparison string

For the "regexp" target, allow specifying a number of matches for the assertion, not just 0 ("does not match") or _any_ non zero value ("does match")

**Comment by firasdib** [comment]
The substitution discussion can be continued in #1161 

Regarding the other suggestion, of allowing a global match, it has been discussed before. I don't see a reasonable way for that to be implemented. You would have to specify which specific match your assertions belong to, which I don't think is very intuitive. 

The only case I can think of where a global match is required for accurate testing would be when using `\G` or `A`-flag. Why do you feel global match is necessary?
