### ISSUE TITLE
🐞🐞🐞🐞 of website

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1319]
### Debug for Chrome 69/79/80
Did no one find this 🐞?
🔧Settings:
🔲 Always collapse left sidebar. No problem.
![123](https://user-images.githubusercontent.com/10995302/80438375-9ccad800-8936-11ea-9f8e-ee43b8225c38.gif)

## 🐞🐞🐞 is coming.
# Ctrl+🆂 (<kbd>Ctrl</kbd>+<kbd>S</kbd>)⇒ Dialog box:
As soon as the mouse clicks, the dialog box will automatically close and disappear.
![Snipaste_2020-04-28_10-05-49](https://user-images.githubusercontent.com/10995302/80438903-e10aa800-8937-11ea-8dce-d711a7fd2925.png)

Looking Gif
![1234](https://user-images.githubusercontent.com/10995302/80438932-f253b480-8937-11ea-8f64-a6d1e92c7afb.gif)

**Comment by firasdib** [comment]
I'm not sure I follow.

If you're trying to show that the left sidebar shows when you hit ctrl+s, then this is intended behavior.

Is there anything else I've missed?

**Comment by dnknn** [comment]
> If you're trying to show that the left sidebar shows when you hit ctrl+s, then this is intended behavior.

This is no problem, but it is not saying that.

**Comment by firasdib** [comment]
Please clarify then

**Comment by dnknn** [comment]
> I understand now! Thanks!

Reproduce🐞?

**Comment by firasdib** [comment]
Yes, and fixed :)

**Comment by dnknn** [comment]
> Yes, and fixed :)
Can I give 2 suggestions?

**Comment by firasdib** [comment]
Go ahead

**Comment by dnknn** [comment]
> Go ahead

Two emailboxes✉📧, please check📮.
It is also the only two remaining problems.
Should be able to understand the specific meaning.
