### ISSUE TITLE
Update live chat help link

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#1320]
## Live chat link - kiwi IRC friendly
It seems you're generating animal names locally and then the `...` were supposed to be randomly generated by their previous web IRC install. Now the [URLs look like this](https://webchat.freenode.net/#regex?nick=re101-zebra-?):
```sql
https://webchat.freenode.net/#regex?nick=re101-zebra-?
```
Where the `?` at the end will turn into 2x random digits generated by Kiwi IRC.

**Comment by firasdib** [comment]
Thanks, updated.
