### ISSUE TITLE
Show line numbers for multi-line test string

### ISSUE THREAD

**Issue by cleverdaemon** [firasdib/Regex101#1321]
## Feature
Hi Team,
Thanks for this beautiful tool.

Just an improvement suggestion. It will be great if the test string section can also have line numbers

**Comment by Doqnach** [comment]
Already possible:

![image](https://user-images.githubusercontent.com/25537191/81200214-f2048a80-8fc3-11ea-8c63-b49b350f83df.png)

**Comment by working-name** [comment]
Closing this, please reopen if deemed necessary
