### ISSUE TITLE
Inconsisten behaviour between Chrome and FireFox

### ISSUE THREAD

**Issue by RamonCar66** [firasdib/Regex101#1322]
When analyzing some expressions, FireFox does not match the expression while Chrome does. For example the central B3 in string AB34 is matched on against /[A-Z][0-9]/gm on Chrome, but is not identified as a match in FireFox.

**Comment by working-name** [comment]
Hi there,

Care to share some screenshots and maybe a link? The link would answer the following:
- what flavor?
- is there anything else in your test string?
- is your regex just that or is it part of a larger regex?
- was it a fluke and you'll discover that the behavior cannot be replicated? 

I was not able to get that behavior from my limited testing while on a Chromebook.
![image](https://user-images.githubusercontent.com/16505052/81474564-5c8c1500-91d4-11ea-80a5-278450c6b030.png)
(big one is chrome, the two little ones are firefox preview and firefox beta on android)

**Comment by RamonCar66** [comment]
Hello Alan,
So sorry. Environment is Windows 7 + FireFox 75.0 (64-bit).

Indeed yesterday I was showing one of my colaborators how to debug and
build regular expressions from the ground. I was showing this website
because it's very helpful to me in testing RegEx. But I was not getting the
expected results, and getting fool, then I switched to Chrome and it did
work. Indeed, the proposed expression is a simplification of the one I was
testing that exhibit the wrong behaviour.

After your response I've closed all Firefox windows, and restarted it
again. Now this behaviour does not show any more.

I really apologize by making you loose your time.

Thanks very much for your help

[image: imagen.png]

**Comment by working-name** [comment]
Not a problem Ramon, glad to hear it worked!

Just FYI, when it comes to the ECMAScript/Javascript, some features work only in Chrome as Firefox is lagging behind with implementation of certain new features. You can open dev tools -> console to see feature detection results.

Have a great one!
