### ISSUE TITLE
Regex expression generates a single hit only while Python and other's generate multiple

### ISSUE THREAD

**Issue by oli71** [firasdib/Regex101#1323]
## Bug Description
The regex given below is processed to have a single result only, while Python (import re) as well as other regex tester tools i tested this one: https://www.regextester.com/96872 give two results.
I am neither a regex expert nor Github, but i believe the two results are right and this is what i intended to get, while regex101 identifies a single result only.

### Reproduction steps
I entered this regex: (?<=\%)([\w.-_]+?)(?=\%)
with flavor Python activated.
The test string is this: '%HOMEDRIVE%%HOMEPATH%/Myconfig'

### Expected Outcome
HOMEDRIVE
HOMEPATH

### Browser
Chrome Version 81.0.4044.129 (Offizieller Build) (64-Bit)

### OS
Win 10, 1803

**Comment by rxmzes** [comment]
Do you have the global flag on?

I don't have your issue when I do put it on, which seems normal.

![image](https://user-images.githubusercontent.com/15831108/82061864-8d36e780-96c9-11ea-8ecd-bbae2a1ae3de.png)

**Comment by oli71** [comment]
Can’t find the context menue for regex flags!?

Oliver





Von: rxmzes <notifications@github.com>
Gesendet: Freitag, 15. Mai 2020 16:32
An: firasdib/Regex101 <Regex101@noreply.github.com>
Cc: oli71 <o.schneider.email@web.de>; Author <author@noreply.github.com>
Betreff: Re: [firasdib/Regex101] Regex expression generates a single hit only while Python and other's generate multiple (#1323)



Do you have the global flag on?

I don't have your issue when I do put it on, which seems normal.

<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15831108%2F82061864-8d36e780-96c9-11ea-8ecd-bbae2a1ae3de.png&data=02%7C01%7Coliverschneider%40siemens.com%7C7783eacadbf64cb588e008d7f8dcc05a%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C1%7C637251499309353190&sdata=mj%2FyqjiAqPwRIZSrlB6j%2FEwSKKurGNLV8OnI%2BHLDYLk%3D&reserved=0>

**Comment by rxmzes** [comment]
It's just over to the right of the input:

![image](https://user-images.githubusercontent.com/15831108/82064457-13a0f880-96cd-11ea-98da-85ae7c7fb5e2.png)

P.S. Have a look at my edits on the original post: https://github.com/firasdib/Regex101/issues/1323

**Comment by working-name** [comment]
To the right of the regex input box - it should have ‘gm’ by default when you load up the page. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oli71** [comment]
Ohh, yes. This solves the issue.

Sorry for setting this as a bug.



Oliver





Von: rxmzes <notifications@github.com>
Gesendet: Freitag, 15. Mai 2020 16:58
An: firasdib/Regex101 <Regex101@noreply.github.com>
Cc: oli71 <o.schneider.email@web.de>; Author <author@noreply.github.com>
Betreff: Re: [firasdib/Regex101] Regex expression generates a single hit only while Python and other's generate multiple (#1323)



It's just over to the right of the input:

<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F15831108%2F82064457-13a0f880-96cd-11ea-98da-85ae7c7fb5e2.png&data=02%7C01%7Coliverschneider%40siemens.com%7Cf28aa8dde8d64d0d5e8208d7f8e055f2%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C1%7C637251514704412934&sdata=HITa25y0L%2FHQRdBkX74GCh%2FrpJpqH9Xhc8kd5%2FEhDa4%3D&reserved=0>

P.S. Have a look at my edits on the original post: #1323<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffirasdib%2FRegex101%2Fissues%2F1323&data=02%7C01%7Coliverschneider%40siemens.com%7Cf28aa8dde8d64d0d5e8208d7f8e055f2%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C1%7C637251514704422930&sdata=iz34Lu1OvxkFTkfv9mk6XKCSyCEdMrSchMSV5beC4a4%3D&reserved=0>

**Comment by oli71** [comment]
I think i called the site straight away and not touched these global settings. – thing /g should be really a default.

None the less, got it now. Sorry for having this as a bug report.



Oliver







Von: Alan <notifications@github.com>
Gesendet: Freitag, 15. Mai 2020 16:58
An: firasdib/Regex101 <Regex101@noreply.github.com>
Cc: oli71 <o.schneider.email@web.de>; Author <author@noreply.github.com>
Betreff: Re: [firasdib/Regex101] Regex expression generates a single hit only while Python and other's generate multiple (#1323)



To the right of the regex input box - it should have ‘gm’ by default when you load up the page.

Sent with GitHawk<https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgithawk.com%2F&data=02%7C01%7Coliverschneider%40siemens.com%7C8c9f5f1111ad417115ce08d7f8e06980%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C637251515035618387&sdata=B%2FKxRiQSY398PAA2ci7IaoqnevTsfoD%2FUOchpfo4Ur8%3D&reserved=0>

**Comment by oli71** [comment]
Thankyou for the friendly help even when it's not a bug.7
Sorry.

**Comment by working-name** [comment]
Just FYI global and multi line flags are on by default.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rxmzes** [comment]
all flags were off by default for me when I first visited the site @working-name

**Comment by working-name** [comment]
@rxmzes interesting. Brand new page, no prior saves? I can’t make that happen for some reason. ‘gm’ is always there for me on a fresh load. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
