### ISSUE TITLE
Is it possible to utilise compiled with Emscripten pcrelib.js?

### ISSUE THREAD

**Issue by fedulovivan** [firasdib/Regex101#1324]
## Question
Hi, Firas!
My apologises for minor reverse engineering of your project, but I noticed that you are using PCRE library compiled with [Emscripten](https://emscripten.org/) to run execute regular expressions of that format.
So I have downloaded the bundle file from https://regex101.com/static/pcrelib.js and loading it in ES6 environment as
```js
import pcrelib from 'lib/pcrelib';
console.log(pcrelib());
```
This dumps a huge object, but none of its fields looks like API towards PCRE. 
Could you give some advises on further steps. Am I on right direction, is it possible to utilise pcrelib.js?

**Comment by firasdib** [comment]
You can use it, but best is to compile it yourself so it does what you need. I've compiled it do to what the website specifically needs.

**Comment by john5634** [comment]
@firasdib Hi Firas!

I too was wondering how you approached PCRE regex in JavaScript?

Did you write C code that uses a PCRE library that you then compiled with Emscripten? String ,Regex Into emscripten compiled code -> then Matches out to JavaScript?

Anyway, awesome work with REGEX101! I use the site every day!!! freaking awesome!
