### ISSUE TITLE
List of warnings

### ISSUE THREAD

**Issue by fabiospampinato** [firasdib/Regex101#1327]
Upon trying something like the following: `/(foo)*/` I stumbled across this warning:

> A repeated capturing group will only capture the last iteration. Put a capturing group around the repeated group to capture all iterations or use a non-capturing group instead if you're not interested in the data

Is there a list of all such warnings somewhere? I think they would be extremely valuable to somebody trying to master a particular regex flavor.

**Comment by firasdib** [comment]
There is not, but I do agree, it would be valuable. I would recommend http://www.regular-expressions.info/ - they cover it all.
