### ISSUE TITLE
Python codegen: single line test string with trailing \n+ is generated without enclosing ( and )

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#1328]
## Bug Description
Codegen for python does not switch `test_str` to multi-line when the test string has a single line and then a bunch of trailing `\n`s (or just one). If you try to run that in 2.x or 3.x it will scream at you the following:
```python
File "main.py", line 8
    test_str = "ff afff
                      ^
SyntaxError: EOL while scanning string literal
```

### Reproduction steps
https://regex101.com/r/9E9bsA/2/codegen?language=python get the code and try to run in on either 2.x or 3x.

### Expected Outcome
Codegen should switch to multi-line notation so as to avoid upsetting the parser:
```php
test_str = (" ....

")
```
or 
```py
test_str = """....


"""
```

### Browser
irrelevant, codegen behaves the same in major browsers

### OS
irrelevant

**Comment by firasdib** [comment]
I've tried a fix for this, will be pushed live soon.
