### ISSUE TITLE
[\U]ppercase & [\L]owercase substitution modifiers not working

### ISSUE THREAD

**Issue by Jaucordi1** [firasdib/Regex101#1330]
**WARN**
This whole bug report may be wrong because of a simple lack of understanding and/or knowledge concerning myself. If the previous sentence become a truth, I want to apologize, btw, it's my really first bug report and I wish I'm doing it the right way and not for nothing.
**END WARN**

## Bug Description

The substitution flags **`\U`** & **`\L`** at it is described in the **Quick Reference** section of the **regex101.com** page, seems to not work at all.

What the **Quick Reference** section said about Uppercase & Lowercase modifiers : 

**Upercase** : **`\U`** Transforms text to uppercase until either end of string or a **`\E`** is encountered.
**This is a feature only available on regex101.com**.

**Lowercase** : **`\L`** Transforms text to lowercase until either end of string or a **`\E`** is encountered.
**This is a feature only available on regex101.com**.

The goal is to transform the string **`left-arrow`** to became **`LeftArrow`**.

### Reproduction steps
Regex Flavor (left menu) : **ECMAScript**
Regex : **`^((.)(.*)(?:-|_| )(.)(.*))$`**
Test String : 
```
left_arrow
right_arrow
up_arrow
down_arrow
dashed-cross
test case
```
Substitution : **`\U$2\E$3 \U$4\E$5`**

Actual Outcome : 
```
UlEeft UaErrow
UrEight UaErrow
UuEp UaErrow
UdEown UaErrow
UdEashed UcEross
UtEest UcEase
```
![screenshot-bug-report](https://user-images.githubusercontent.com/29695562/83976576-0d342400-a8fb-11ea-9ae4-b62bcf6b1b27.png)

### Expected Outcome
```
LeftArrow
RightArrow
UpArrow
DownArrow
DashedCross
TestCase
```

### Browser
**Google Chrome v83.0.4103.61**

### OS
**Microsoft Windows 10 Professional Edition**
Version : **1909**
Operating System Version : **18363.836**

**Comment by Doqnach** [comment]
`\L` and `\U` don't actually exist for ECMAScript. It probably shows up in the reference for ECMAScript by mistake. The description is indeed not very clear (since it does work in certain flavours of PCRE).

**Comment by Jaucordi1** [comment]
Oh, I didn't know that they aren't exists for ECMAScript.

Are you talking about my **Bug description** when you say **`The description is indeed not very clear`** ? Are you saying this for the part **`seems to not work at all`** ?
Do I must edit my first post and remove this part or, at least, change it to a more precise part like **`not working for ECMAScript flavor but Quick Reference didn't notice about that`** ?

Thank you for your answer by the way ! 👍

**Comment by Doqnach** [comment]
No, sorry, your issue is very clear thank you!

I meant that the description of the token in the quick reference is not very clear.

**Comment by Jaucordi1** [comment]
Oh okay, thank you ^^

So, what's going on now,
Do I need to close this issue or just wait for a dev to fix the issue and close it at the same time ?

I'm sorry for spamming but it's all new for me, I need to know to execute it the right way ^^'

**Comment by Doqnach** [comment]
No, please leave the issue so the relevant people can look at the issues with the quick reference.

**Comment by working-name** [comment]
Hello there, 

Not sure if this was intended as a universal feature at first given `This is a feature only available on regex101.com` and then plans changed. I'll wait for guidance before updating the quickref.

**Comment by Jaucordi1** [comment]
Ok, thank you @Doqnach for all your answers! :)

**Comment by firasdib** [comment]
I never intended for this to collide with any other syntax, this was just meant as a nice to have thing for people using the website.

**Comment by Doqnach** [comment]
See also #1273

**Comment by firasdib** [comment]
The only place where this is currently implemented is in PCRE, where I have written my custom replacement logic. The other languages have a defined set of features that I have tried to follow. I will limit the quickref for these entries to PCRE for now.
