### ISSUE TITLE
New line remplacement  in OpenOffice with the «Alternative dialog Find & Replace for Writer»

### ISSUE THREAD

**Issue by leonprimer** [firasdib/Regex101#1332]
## Question
Hi, when I try to remplace text with a new line in OpenOffice, sometimes the normal remplace tool don't match the text. For that reason I use the extension «Alternative dialog Find & Replace for Writer» (https://extensions.openoffice.org/en/project/alternative-dialog-find-replace-writer-altsearch), with \p*^ it matches perfect. But today this extension is not more in the Writer, it disappeared. I tried to uploaded it newly, but it's not possible.

Does anybody know if they have a problem with the extension? There is another free extension I can upload to solve the problem of the new lines? There is another solution for this problem? 

I'll appreciate your answers.

**Comment by Doqnach** [comment]
Hi @leonprimer. This github repository is for issues regarding regex101.com. I'm afraid it is not really the place for questions regarding other tools.

I do think that maybe writing a different regex can help you with your problem. You can join the "Live help" webchat (or IRC directly) for help on how to write a regex that will work in your use-case.
