### ISSUE TITLE
add \p{...} support to JavaScript flavor

### ISSUE THREAD

**Issue by nikitaKurtin** [firasdib/Regex101#1333]
## Bug Description
The unicode shortcut properties such as: \p{L}, \p{M}, \p{N}, \p{P}, etc...

Are not supported in the ECMAScript(JavaScript) flavor.

When switching to other flavors (PCRE, Python, Golang) - it works properly, so it seems as a local bug only in JavaScript mode.

### Reproduction steps
Type regex like: 

/^[\p{L}\p{N}]+$/u

And you will see the bug

### Expected Outcome
To compile and run

### Browser
Google Chrome 80.0.3987.163

### OS
MacOS Catalina 10.15.3

**Comment by Doqnach** [comment]
The support for `\p` in ECMAScript is dependent on your browser.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet#Unicode_property_escapes

If your browser doesn't support it, neither can the website.

**Comment by nikitaKurtin** [comment]
The browser support it perfectly. 

See screen shot below.

<img width="1306" alt="Screen Shot 2020-06-16 at 8 46 22" src="https://user-images.githubusercontent.com/26906567/84736411-690f4480-afae-11ea-9237-1af8f1070259.png">

**Comment by Doqnach** [comment]
Thank you for this report. Seems like `\p` is not yet feature-detected then by the website since it is a rather recent additional to ECMAScript.

![image](https://user-images.githubusercontent.com/25537191/84748560-1a1adc80-afb9-11ea-87c5-b4fc2d7e521e.png)

**Comment by firasdib** [comment]
Yes, this will have to be added. I will try to get it added soon.

**Comment by firasdib** [comment]
This has finally been implemented, and will be pushed live shortly.

**Comment by I-keep-trying** [comment]
Has this been fixed yet? I don't see an error, but it does not find a match with ECMAscript selected. 

Try it with `\p{Pc}+` and test against the underscore `_` character, (unicode `U+005F`.)

**Comment by Doqnach** [comment]
Works for me: https://regex101.com/r/YVH1S1/1

Don't forget to turn on unicode mode (`u` flag) for `\p` to work in JS flavour.
