### ISSUE TITLE
Opera graphic issue

### ISSUE THREAD

**Issue by ros86** [firasdib/Regex101#1336]
## Bug Description
Opening https://regex101.com shows only title bar and side menu

### Reproduction steps
Open https://regex101.com as not logged user

### Expected Outcome
https://imgur.com/a/RizFBb2

### Browser
Opera v69.0.3686.36

### OS
Windows 10 pro 1803 x64

**Comment by Doqnach** [comment]
Unable to reproduce on MacOS, Opera 68.0.3618.173 nor 69.0.3686.36.

@ros86 have you tried emptying the browser cache? try reloading the page with the developer toolbar open with under "Network" the option "Disable cache" checked. If the "Console" gives any errors, please provide them here to help debug the issue.

**Comment by ros86** [comment]
Addon "Annotating the Web" make regex101 fails. I disabled it.
