### ISSUE TITLE
Changing language doesn't work on mobile

### ISSUE THREAD

**Issue by Sharcoux** [firasdib/Regex101#1337]
## Bug Description

When I try to change the language being used on regex101.com while browsing on mobile device, the buttons don't seem to be working.

### Reproduction steps

1) Access regex101.com with a small device like a smartphone (tested with chrome for android)
2) Try to change the language for javascript

### Expected Outcome

The language should change but nothing happen instead.

### Browser
Include browser name and version

Chrome 83.0.4103.106

### OS
Include OS name and version

Android 10 ONEPLUS A6000 Build/QKQ1.190716.003

**Comment by working-name** [comment]
Safari on iOS 13.3 also has issues switching languages or activating any links with a tap or double tap. A long press on some links will open a preview 'card' UI - which belongs to the browser - showing the linked page. It does not however open in the main page.

To be noted, `:hover` gets applied when tapping but there's no action taken by the browser outside of rendering the css change. Don't have a usb cable on me so I can't open a console to see if there's any errors.

I would test other browsers but we all know fapple doesn't allow browser engines outside of its own dear webkit.

**Comment by Doqnach** [comment]
Also doesn't work in Opera (also based on chrome) on Android.

**Comment by firasdib** [comment]
This should now be resolved. Will be pushed live shortly.
