### ISSUE TITLE
Adding a graphical visualizer

### ISSUE THREAD

**Issue by mandy8055** [firasdib/Regex101#1338]
## Feature
Regex 101 is already the best tool ever created when working with regular expressions. One enhancement which is an added advantage and much required for tyros is to visualize them using graph. It is always preferable to visualize something in pictures; so this enhancement feature might be added in order to ameliorate the site which is one of the best already. Below is the attached snap of the sample feature that this issue talks about.

![regss](https://user-images.githubusercontent.com/21336536/86493085-c61c4000-bd8d-11ea-8452-ed3e3326f289.PNG)

**Comment by Doqnach** [comment]
See #400, #958

**Comment by thorade** [comment]
The keyword that might lead people here is:
regex railroad diagram

I used this Atom plugin in the past:
https://atom.io/packages/regex-railroad-diagram
