### ISSUE TITLE
Wrong descriptions for JavaScript Character classes

### ISSUE THREAD

**Issue by cvlab** [firasdib/Regex101#1340]
## Bug Description

`\s matches any whitespace character (equal to [\r\n\t\f\v ])`
Should be
`equal to [ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]`

`\S matches any non-whitespace character (equal to [^\r\n\t\f\v ])`
Should be
`equal to [^ \f\n\r\t\v\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff]`

Source - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet

Also many description for **unicode** flag
`\d matches a digit zero through nine in any script except ideographic scripts (equal to \p{Nd})`
Should be
`\d matches a digit (equal to [0-9])`

In JS flavour `Character classes` do not change with **unicode** flag set.

Reference - https://github.com/tc39/proposal-regexp-unicode-property-escapes

Thank you!

**Comment by firasdib** [comment]
Thanks! I've adjusted this (finally)
