### ISSUE TITLE
ABAP programming

### ISSUE THREAD

**Issue by kimkhumba** [firasdib/Regex101#1344]
LOOP AT lt_notice INTO DATA(ls_notice).
    CALL FUNCTION 'IB_CONVERT_FROM_TIMESTAMP'
      EXPORTING
        i_timestamp = ls_notice-mod_timestamp
        i_tzone     = sy-zonlo
      IMPORTING
        e_datlo     = ls_notice-mod_date
        e_timlo     = ls_notice-mod_time.
    MODIFY lt_notice FROM ls_notice.
    CLEAR ls_notice.
  ENDLOOP.
Can someone explain me this code?

**Comment by Doqnach** [comment]
I'm sorry, this is a place for issues regarding the regex101.com website/tool. We can not provide help regarding specific programming languages or any other subject outside of that context.
