### ISSUE TITLE
Can support setting the default flavor of DELIMITERS ?

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1355]
![0713232655](https://user-images.githubusercontent.com/10995302/87322726-59a8fa00-c560-11ea-976b-6327eb96142b.png)

Give a most common example : 
Because `https?://` itself is allowed, in many places do not need to escape `\/` slash symbol. Not necessary: `https?:\/\/`

And this is the most commonly used, in the regular processing of URLs.

**Comment by firasdib** [comment]
You could use the semi-unofficial feature: https://regex101.com/?delimiter=~

**Comment by dnknn** [comment]
Thanks♪(･ω･)ﾉ
