### ISSUE TITLE
a little wrong with Unicode characters

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1356]
## It will only appear �   when :hover Emoji and tooltip, on the regexp input.

         A 🤬 will be broken down into two �

RegExp rule itself is no problem. testing see 👇
### https://regex101.com/r/y1lvOr/1

![Unicode](https://user-images.githubusercontent.com/10995302/87391808-feb5e800-c5dd-11ea-938a-049cd773493b.gif)

**Comment by firasdib** [comment]
Thx, this was a fun bug. Fixed and will be pushed live soon.
