### ISSUE TITLE
Java code generator not handling groups properly

### ISSUE THREAD

**Issue by arpieb** [firasdib/Regex101#1357]
## Bug Description
Capture groups are not being iterated over properly in the Java code generator, only the full match is being output.  It appears this is due to an improper comparison of `matcher.groupCount()`:

`        for (int i = 1; i < matcher.groupCount(); i++) {`

which should be:

`        for (int i = 1; i <= matcher.groupCount(); i++) {`

according to the `Matcher#groupCount()` docs:

> Returns the number of capturing groups in this matcher's pattern.
> Group zero denotes the entire pattern by convention. It is not included in this count.

### Reproduction steps
re: `{([a-zA-Z0-9_.]+)}`
text: `This is a {regex} pattern {test}`

### Expected Outcome
Full match: {regex}
Group 1: regex
Full match: {test}
Group 1: test

### Browser
Firefox 78.0.2 (64-bit)

### OS
Windows 10

**Comment by firasdib** [comment]
Thanks, adjusted.
