### ISSUE TITLE
Why can't use \d+

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1358]
PCRE(PHP) 

`(?<=🆔\d+)abc` why  it is error ❓

https://regex101.com/r/9YJyHZ/1

![0715123452](https://user-images.githubusercontent.com/10995302/87503770-a2af9a00-c697-11ea-9707-42398944464c.png)

Is this rule itself correct?  Why can't use  `\d+` ,if can't ,then how do you match 1-999 digits? 

https://uzitech.github.io/regexper/#%7Cflavor%3Djavascript%7C%28%3F%3C%3D%F0%9F%86%94%5Cd%2B%29abc

![0715123825](https://user-images.githubusercontent.com/10995302/87504001-2a95a400-c698-11ea-9029-c61ff9bdd46d.png)

Switch to ECMAScript (JavaScript) flavor, it working. But can't use `/` directly .
The slash  **/**  symbol, which needs to be escaped, is very troublesome and inconvenient.

because` / `is allowed in most places without escaping. `Tampermonkey`  `Stylus`  `Stylish`  `Regular search in text editor`  .etc

As` /` is not used as delimiter character, you do not need to escape it like in other RegExp environments.

It is very inconvenient and inconsistent when matching URLs need to escape `https?:\/\/foo\.com\/dd\/dgg\/` ...
So have to switch to `PCRE(PHP)` for paste directly 👉 `https?://foo\.com/dd/dgg/` ...

**Comment by Doqnach** [comment]
PCRE(1) does not support variable-length look-behind. Some other regex flavours do, but PCRE(1) does not.

**Comment by dnknn** [comment]
> A case could be made for supporting both the literal as well as the string notation for the ECMAScript flavour, but that needs to be a separate issue then.

ok , Act now.
