### ISSUE TITLE
allow /  not need to escape when Switch to ECMAScript  

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1359]
sorry for my English, translate by Google most 🤦🙈

related https://github.com/firasdib/Regex101/issues/1355 
> A case could be made for supporting both the literal as well as the string notation for the ECMAScript flavour.

It will be convenient for ordinary users are not developers.

![0715153338](https://user-images.githubusercontent.com/10995302/87516837-98e66080-c6b0-11ea-9ce9-f69219462ae6.png)

---

- 1, `PCRE` can used&ensp; `/` &ensp;directly , but it can not use `?<=😭\d+)` see👇, maybe there are other restrictions.

### https://github.com/firasdib/Regex101/issues/1358

---

-  2,  So, Switch to `ECMAScript ` ,request &ensp; `/` &ensp; slash can  allow be escaped,   because `/` is allowed in most places without escaping.

&emsp;&emsp;&emsp;E.g `🐵Tampermonkey`  `🆂 Stylus`  `Stylish`  `🔍Regular search in text editor`  .etc...
There are many Chrome extensions with RegExp functions, I personally have not seen one that needs to be escaped `/`

Other regular test sites are also allowed to escape, e.g. [debuggex](https://www.debuggex.com/)  or  [jex.im/regulex](https://jex.im/regulex)  (I don’t know, maybe they are not in ECMAScript mode,)

As long as it is not a place to write code, almost no escaping is allowed, especially where it is related to the  URLs RegExp. 

> As / is not used as delimiter tcharacter, you do not need to escape it like in other RegExp environments.

---
- ### 3, Otherwise , at present, it is very inconvenient.

---

- ## Implementation plan:
In https://regex101.com/settings,  add an option switch(ON/OFF) for ECMAScript flavour.
> If possible, the default state is preferably OFF (not need to escape)

**Comment by firasdib** [comment]
If you use the `RegExp` constructor you do not need to escape the slash, you are right, but 99% of developers do not use that, and thus need to escape the slash. Thus I've decided to mimic that behavior.
