### ISSUE TITLE
Multi-step substitution

### ISSUE THREAD

**Issue by sunchezz89** [firasdib/Regex101#1360]
## Feature
I often use regex101.com for substitute some large texts.
This often goes hand in hand with substitute this texts with more then one regex.
It would be great to have the ability to save a pipeline with multiple regex's (and substitution patterns), which you can later feed with a text and the pipeline is applied to it.

Is this clear enough?

It would be a HUGE help for many workflows!

**Comment by firasdib** [comment]
This has been discussed before, but I'm concerned this workflow might be a bit complicated to include. Some people have suggested the inclusion of a "copy substitution text to test string", would that be sufficient?

**Comment by sunchezz89** [comment]
for me the goal is to 'automate' common programming tasks, where i know i need multiple regex to achieve my goal to transform text, or even code. therefor, i would like to have a multi-step workflow, which also can be saved, like normal regexes.
of cause, copying the substituted text to input is a first step, and would also be nice, but i think this is not satisfying in the big picture. 

Is it complicated in terms of UI, UX, or implementation logic?

one thing i could imagine, is to have a button on the normal page, to `ADD` a regex to the `chain` (maby only seen if you open the substitution panel).
If you click the button, a `new` page is opening (where you also have button to navigate back). 
this way you have the general workflow of "just" a new regex where input is filled with the previous substitution output.

Maybe you could tell, which part is complicated so that maybe the community can help with ideas :)

**Comment by firasdib** [comment]
Its not complicated per se, but it is a lot of work, and its non-trivial to include it in the UI without major UX rework.

**Comment by Doqnach** [comment]
To me personally, regex101's intention would also not to provide a regex parsing service to replace doing so in actual programming languages. The website to me is a tool to write/refine regex till it meets the needs so you can then take it and use it in some program/script.

**Comment by firasdib** [comment]
I agree with @Doqnach and close this issue.

**Comment by Ouims** [comment]
Yes but chaining regex is definitely a thing people are doing, and yeah some are doing it on the website, you don't always have a programming language to test stuff or do stuff.
Here is a proposal:
A new UI from a new menu item after 'unit test', something like 'multi-regex' (note that it could be included in the main ui directly, and i'm going to try to make it work that way below).

So this would open an UI similar to what we have on the main UI + eventual substitution UI.

So on the first step, you just write a pattern, an input string, and an eventual substitution field.

Then at the bottom, you would have a '+' icon, which add another main UI into the main ui, in a scrollable fashion.

So let's say you used substitution, the second UI's input string would reflect that the input string is the actual substitution of the previous stage, and it should not be an editable editbox, in fact there should be no input string available for edition at this point, just something clear showing the input string is the sub from previous stage.

Each stage is saved as a separate url to keep the current db as it is and it then opens a door to having the input coming from anywhere from the web, including regex101 url where then you would be extracing the sub field.
And a new db could be made for storing this new stuff.

If you're not doing subsitution, then clicking on the + could still work where it would ask which value you want to use, if you select 'use full match' then it would basically recreate an input string out of them, same if you select 'use capture number 2' for example, there could be more options in such a dropdown, such as 'use fullmatch (separated by newline)' 'use fullmatch (separated by space)', etc (ditto for captures). real dynamic shit would even get you an input string from both the full match and captures at the same time, separated by what you want etc hehe.

That's definitely a lot of work but it would work with the website.

**Comment by firasdib** [comment]
I have been thinking a lot about this feature and its usefulness, and decided, it provides a lot of value. It took me 5+ years to realize this, but I can announce that it's on the road map and being developed.

I will be a feature available to regex101 Pro users, and it will allow you to create an arbitrary chain of regexes and substitutions and apply those recursively on an input string.

If you'd like to discuss more, I am available on both IRC and Discord.

**Comment by firasdib** [comment]
This feature is now live on the site.
