### ISSUE TITLE
'command' to access match-counter in substitution

### ISSUE THREAD

**Issue by sunchezz89** [firasdib/Regex101#1361]
## Feature

It would be really great to have access to n'th number of the match count in substitution pattern, with a command like `\#`. 
Lets assume the following scenario:

regex pattern `/(.+),?/gm`
Input Text:
```
Example,Input,Text
```

substitute pattern `\#. $1`
Output: 
```
1. Example
2. Input
3. Text
```

**Comment by Ouims** [comment]
i'm all for it, although it may not be realistic to accomplish on any given engine/tool

**Comment by Ouims** [comment]
In fact I already suggested this a long time ago and @firasdib said no basically :(

#765

**Comment by Doqnach** [comment]
This could maybe be made a part of #1410 as a feature. That way possible syntax issues are limited to this specific function only.

**Comment by Ouims** [comment]
You're going to make me lose my mind! When I asked about it, I got a terrible answer. Now, the substitution supports non-standard-at-all markers to modify the output, why would you not add another one that makes a lot of sense and has been asked many times? It should be available directly in the substitution field.
Current \U \L \E behaviors are breaking far more attempt than a \# would do.

**Comment by sunchezz89** [comment]
@Doqnach 
It would be nice to have some more insight in what problems you see with that.  
(the best way to collaboratively find solutions for any given problems... ).

If i understand correctly, you want to limit this feature to a "match export", as stated in #1410 ?
Because you see any syntax issues... Which one and why?
if it is just the `#`-sign, this was just an example and could be easily replaced by anything else.

Regarding the compatibility to some code-generator languages...
There are already some substitution commands, which do not work very well with some languages, so i do not see an issue with that. If you declare it as online-tool (website-only-feature) and not compatible for any language in the discription, i see no problem at all.

please let us know what else should be discussed or needs a solution, because i really want this feature!

**Comment by firasdib** [comment]
I'm not immediately against this suggestion, but am generally cautious to adding non-standard functionality.

Perhaps a custom token of `$#` could be used to denote match index? Do we forsee any problems with adding a feature like this?

**Comment by Doqnach** [comment]
I think a best-of-both-worlds could be that the 'list' feature of #1410 would get an option to number the matches/lines (possible to set in-place or via settings?). That would provide the requested syntax without injecting any new custom syntax.

**Comment by Ouims** [comment]
@Doqnach, people who want this wants this inside the substitution, a lot of people are using the website like an editor and doing replacement like that, having it in #1410 is fine, but the suggestion here is for substitution field.

**Comment by Doqnach** [comment]
Outside of @sunchezz89 I have not seen other people ask for this feature since you raised it the first time 4 years ago. Could be that I missed related issues that never got linked? That is a very small number of people.

Also, the use-case from this issue would be solved using my suggestion. Up til now the only request has been in the form of more or less an export of (full) matches in a numbered list. 

It is possible that someone might have a use-case where they do not want to touch the original content except for whatever the full-match touches, but I have not seen any requests for that nor clear use-cases describing that requirement?

@sunchezz89 do you see this differently? Is your use-case other than how I have described it so far?

**Comment by firasdib** [comment]
With the most recent change I am entirely relying on the native substitution engines, which means I cannot do any additional processing. The legacy implementation is available for pcre1 but I don't think its worth spending more time on that.
