### ISSUE TITLE
JavaScript hover over \1 \2 \3 etc. shows weird characters

### ISSUE THREAD

**Issue by RedDragonWebDesign** [firasdib/Regex101#1363]
## Bug Description

JavaScript - hovering over \1 \2 \3 etc. shows weird characters.

![2020-07-23_064319](https://user-images.githubusercontent.com/43397938/88293576-08abab00-ccb0-11ea-9d53-8388711a44b0.png)

### Reproduction steps

- Select flavor EMCAScript (JavaScript)
- Type in \1
- Hover over \1

### Recommended Solution

- That upside down "L" character displaying in the gray box is probably a bug. Maybe display [invalid] or [not found] or something similar.
- Include the word "octal" or "base 8" somewhere in the explanation, so that inexperienced people like me know what we're looking at.

### Browser
Chrome 83.0.4103.116 (Official Build) (64-bit)

### OS
Windows 7 Pro 64-bit

**Comment by Doqnach** [comment]
Please provide a link to a saved regex that displays this behaviour.

**Comment by RedDragonWebDesign** [comment]
@Doqnach Sure. Here you go.

https://regex101.com/r/ZWtAw2/1

**Comment by Doqnach** [comment]
The problem you have is that you are using `\1` without having a capture group, thus JS will think you mean: `character with ASCII code 1` (octal). See https://regex101.com/r/ZWtAw2/2

Note that look-arounds, even though they use `()` do not create a capture group.

**Comment by RedDragonWebDesign** [comment]
Ah. Thanks for the explanation. In that case, I would recommend 2 changes to the Regex101 code if anybody is interested.

- That upside down "L" character displaying in the gray box is probably a bug. Maybe display [invalid] or [not found] or something similar.
- Include the word "octal" or "base 8" somewhere in the explanation, so that inexperienced people like me know what we're looking at.

**Comment by Doqnach** [comment]
The notation for the `base` (8 for octal, 10 for decimal, 16 for hex) is not uncommon in the IT world. Not heard anyone before having issues with this. Writing it out fully will increase the length of the tooltip by quite a bit.

The displaying of that 'upside-down L' might be a local font issue. The browser simply tries to render the actual character there.

**Comment by firasdib** [comment]
Yeah, thats a local font issue. The base notation is already included.
