### ISSUE TITLE
Can ⚙ ✅ Always collapse `QUICK REFERENCE`

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1364]
[regex101.com/settings](https://regex101.com/settings) Can add ❓:
## ✅ Always collapse `QUICK REFERENCE`
>it can no need to manually click to collapse each time.

For not newbies, `QUICK REFERENCE` will only be carried out occasionally in extremely rare circumstances.

☑ collapse `QUICK REFERENCE` by **default**, area to display more main content.

![0727054440](https://user-images.githubusercontent.com/10995302/88490191-5552f700-cfcc-11ea-9f60-b1a76ae4b5ff.png)

**Comment by firasdib** [comment]
This turns out to have been a bug. I have since fixed it. The choice will now be remembered.
