### ISSUE TITLE
Explenation for hebrew regex shows: ֐

### ISSUE THREAD

**Issue by Mendistern** [firasdib/Regex101#1366]
## Bug Description
The test for regex: ^[a-z\u0590-\u05fe ]+([a-z\u0590-\u05fe ]+)*$

### Reproduction steps
You'll see in the explanation such a line: 
\u0590-\u05fe a single character in the range between ֐ (index 1424) and ׾

### Expected Outcome
Real letters I guess.

**Comment by Doqnach** [comment]
What character should it be?

If I check https://www.utf8-chartable.de/unicode-utf8-table.pl > U+0590-U+05FF, I also see the boxes, which tells me my OS does not have a font that contains that glyph. Those glyphs also have no description, which leaves me with the question if they are even used in UTF-8 already.

So I'm leaning towards this not being an issue with Regex101.

**Comment by Ouims** [comment]
Your OS most likely have a font to display hebrew, it is the website that is responsible for the display, however this is not a bug but a feature.

**Comment by firasdib** [comment]
Sounds like a local font issue as mentioned earlier.
