### ISSUE TITLE
Rust codegen enhancement

### ISSUE THREAD

**Issue by LucianoBestia** [firasdib/Regex101#1367]
Thank you for your fantastic page! 
Writing regex in regex101.com is a dream come true. 
Thanks.
I hope you will also add the flavor for Rust. I don't know enough of the regex specifics to see the difference. 
So I cannot help here. But I can help with a more complete code generator.

## Rust
I wrote the Rust code for using Regex with all the important methods. 
I think it is better than the existing codegen for Rust.
Open this link and click on `Run` to see it compiling and running in the rust playground:
<https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=13975bff3879f843dc80d338091555b6>

I read the wiki Writing-a-Code-Generator. I could try to write it, but I don't know how to test if it works.
There are only 3 strings to be replaced in my code:
1. regex expression
2. test_string
3. substitution

Is there a way to just take the Rust code as a big string and then replace 3 strings with the regex101 variables?
So to create a working code gen for the website?

**Comment by firasdib** [comment]
I'm no Rust developer, so can you please elaborate on whats missing from the existing one?

**Comment by LucianoBestia** [comment]
1. When using Capture Groups the code-gen does not use the proper method.
The suggested method is ok for regex without groups:
` let result = regex.find_iter(string);`
For capturing groups the method should be:
`regex.captures_iter(test_string)`
2. The regex object should be created only once if used inside a loop.
The code-gen is very simple and is not itself inside a loop. But developers could use it inside a loop and be frustrated by bad performances. It is nice to "teach" the developer about this subtle detail in the code-gen.

**Comment by firasdib** [comment]
I've updated the function call.
