### ISSUE TITLE
[Request] Swift Code Generator

### ISSUE THREAD

**Issue by rogerluan** [firasdib/Regex101#1368]
## Code Generator Language

First of all, thank you for implementing Regex101.com. Creating, editing and iterating over regular expressions have never been easier. I've been personally using it for years!

I'd like to submit this format request to add a Swift code generator to the Code Generators. I'm surprised this request wasn't submitted by anyone before, so I'm formalizing it here. I intend to open a PR with my generator proposal.

Thank you!

**Comment by Doqnach** [comment]
For completeness sake: #1342 is also an open PR for this.
