### ISSUE TITLE
Cross-Site Scripting Attack via Usernames/Library Entry Names

### ISSUE THREAD

**Issue by SuperSonicHub1** [firasdib/Regex101#1370]
## Bug Description
A user is able to run JavaScript code via having a script tag either in their username or library entry name, I'm not sure.

### Reproduction steps
Go to this link: https://regex101.com/library/tP0nI8

### Expected Outcome
Get a JavaScript alert, it's contents being "1".

### Browser
Include browser name and version
Google Chrome Version 84.0.4147.110 (Official Build) (64-bit)

### OS
Include OS name and version
Google Chrome OS Version 84.0.4147.110 (Official Build) (64-bit)

**Comment by firasdib** [comment]
Thank you, fixed.

**Comment by SuperSonicHub1** [comment]
Glad I was able to help.

Kyle Williams
