### ISSUE TITLE
support for re.VERBOSE in Python regexp

### ISSUE THREAD

**Issue by marie-r** [firasdib/Regex101#1373]
## Feature

Dear Firas,

First off, kudos on a great site, I recommend it to my students frequently.  I was recently debugging a Python regexp where I was using verbose as it was a complicated timestamp parser and wanted to test some changes:

""".*
        (?P<year>\d\d(\d\d)?)[-_]?(?P<month>\d\d)[-_]?(?P<day>\d\d)
        .(?P<hour>\d\d)[:]?(?P<min>\d\d)[:]?(?P<sec>\d\d)
        \..*
        """

There is currently no support for the verbose flag which ignores whitespace.  It would be really nice to have.

Thanks so much,
Marie

**Comment by Doqnach** [comment]
I'm not that familiar with Python, but is `re.VERBOSE` similar to the `X` flag? See https://regex101.com/r/Fq3vRZ/1/codegen?language=python. This seems to already be supported.

**Comment by marie-r** [comment]
Dear @Doqnach,

You are correct.  It must have been a pilot error on my part.  As an aside, for anyone parsing datestrings within a larger string (in this case a filename), the pattern names in the post were munged: and I did not catch it in the preview.

```
""".*
        (?P<year>\d\d(\d\d)?)[-_]?(?P<month>\d\d)[-_]?(?P<day>\d\d)
        .(?P<hour>\d\d)[:]?(?P<min>\d\d)[:]?(?P<sec>\d\d)
        \..*"""
```

Thank you for the clarification.- Marie
