### ISSUE TITLE
Incorrect definition for alternation in quick reference?

### ISSUE THREAD

**Issue by minig0d** [firasdib/Regex101#1374]
## Bug Description
Currently the quick reference shows reads as follows.  I'm not sure if it's correct from a technical perspective, but it definitely keeps throwing me off from a lay perspective. Should it not say "Capture either a or b" since the alternation syntax doesn't automatically turn it into a non-capturing group like (?:  ) does?

```
Capture everything enclosed (...)
**Match either a or b (a|b)**
Match everything enclosed (?:...)
Atomic group (non-capturing) (?>...)
```

**Comment by firasdib** [comment]
@working-name thoughts?

I can see the confusion, but technically it is correctly described.

**Comment by minig0d** [comment]
I realize that it's technically correct as far as yes it does match (, but then it also captures when written as above) doesn't it?  And technically isn't matching (and capturing) implied in all groups?  I.e. the default assumption in regex is that all groups are capture groups unless a modifier makes it a non-capture groups?  i.e. all capture groups are matching, but not all matching groups capture (ex. ?: .  So while it may technically do matching, it's extra confusing because of 1) the placement directly between "Capture" and "Match" while repeating the word "Match" further would lead someone to think it is a matching only group and 2) the inconsistency because technically the first construct listed is a "Match" group as well. (i.e. technically if I call you a mammal it's correct, but calling you a human would be equally correct and equally readable, without getting too technical (ex. homo sapiens)

Being newish to RegEx I'm not sure if there is truly a technical standard that defines a "matching group" but I've never actually seen it used in definition anywhere, so I assume the intent was more just to simplify for newbies (which I thoroughly appreciate). 
But it's definitely not consistent with any official documentation I've ever seen. And technically is it even a standalone concept or just really a commonly used combination of alternation within a ("capture") group?

PS. it may even be worth considering clarifying the "Match everything enclosed" by either changing to "Match but not capture everything enclosed" or add (non-capturing group) to help people mentally correlate the concept between the document here and what they've read elsewhere which uses the more standard terminology of non-capturing group.)

Just as some examples of how it's worded elsewhere:
Ex. in the [PCRE docs](https://www.pcre.org/current/doc/html/pcre2pattern.html#SEC14) bullet 1 does say that it functionally matches, but then #2 goes on to deem it a "capture group".  
[perl.org docs](https://perldoc.perl.org/perlre.html) similar to above
[regular-expressions.info](https://www.regular-expressions.info/brackets.html) similarly mentions that the parentheses can be used to group and then says they create capture groups.
[regular-expressions.info](https://www.regular-expressions.info/refcapture.html) refers to the scenario as a capturing group as well in all the backreference example rows

Sorry not trying to be argumentative, just wanted to provide some context/references to support.

**Comment by working-name** [comment]
Yes I'm with you for consistency's sake, it can be called 'match and capture either an a or a b' as well as 'match and capture everything enclosed'. 

Just FYI, @minig0d 
- you can match but not capture: `/ok/`
- you can match and capture: `/(ok)/`
- you can capture but not match: `/(?=(ok))/`

Just like anything else you can have synonyms: non-capturing group = matching group. I would not let naming conventions deter you from learning what each thing does.

Thank you for the feedback!

It the above is cool with you @firasdib I can update the quickref as such.

**Comment by Ouims** [comment]
I have no idea why this report was handled like that, OP is obviously right, if it's not (a|b) that is wrongly described, then it would have to be (...) both are capturing, one is described as matching and the other as capturing, that's definitely incorrect.
As far as I'm concerned, in pcre, (a|b) is not even a different syntax than (...), it's just that any regex is allowed inside (), not just alternation. I'd remove the (a|b) line from the quickref entirely.

**Comment by piotr-dobrogost** [comment]
> I'd remove the (a|b) line from the quickref entirely.
This.

**Comment by working-name** [comment]
I would like to disagree with both @piotr-dobrogost and @Ouims because we're talking about "common tokens". The point there was to exemplify commonly used syntax, among which an alternation syntax. Alternation could be inside a capturing or a non-capturing group, or standalone - so there's plenty of ways to come up with an example. 

I don't think we should remove it altogether, but the verbiage should not confuse or state a half-truth - right now it's omitting the fact that it also happens to capture that "a" or "b".

**Comment by Ouims** [comment]
No, you're ending up writing incorrect statement for no good reason, and you should be willing to teach to people that (a|b) and (...) are the same capturing group, it never matters what's in the group, it's captured, that's all.

The statement is misleading, questionnable and raised this issue, removing the part about (a|b) is going to fix that, if you want to teach about alternation, capturing group are not the place to do that.

**Comment by minig0d** [comment]
Looking at it again...  For someone who doesn't know better, it also kind of implies that you HAVE to use ( )'s in order for alternation to work.  (I realize it's not meant to be an "all inclusive" list, but think about how many newcomers learn off the site and are the ones most likely to use the quick reference...)

Another way this could be resolved is by:
Adding a line:   
`Match either a or b     a|b`
Renaming existing line:
`Capture either a or b     (a|b)`

**Comment by working-name** [comment]
Cool, thanks for the feedback guys, I ended up going with `a|b` but provided the other options (non-cap and cap groups) in the token's description. I think it's important to differentiate between whole-regex alternates and isolated alternates.

**Comment by Ouims** [comment]
not sure what you did but the explanation is still incorrect.

I think the opposite, you should view them as dynamic because that's how they are, a|b is an alternation so is (a|b) just with a capture.
There are 0 difference in the alternations here.

**Comment by working-name** [comment]
The first one alternates the whole left side and right side of the regex, while the second one alternates just the items contained in the capture group, irrespective of what else is on the left and right side of the capture group.

Also update wasn't pushed until 1 hour ago and your comment is 2 hours old so you may have still seen the old tokens.

**Comment by minig0d** [comment]
Fix looks good... but now that it's not representing a group, may be worthwhile to move it out of the "Group Constructs" category and into "Common Tokens"?  (unless it may fit better if a different one?).

**Comment by working-name** [comment]
No it doesn't, it's hard to read :) Working on the layout.

And yes it's going to the Meta Sequences for now.
