### ISSUE TITLE
Conditionally show links to the debugger when no match found

### ISSUE THREAD

**Issue by minig0d** [firasdib/Regex101#1375]
## Feature
Honestly as long as I've been using the site, I never even knew the RegEx Debugger existed and was about to put in a request for something similar...  But I think it's an extremely invaluable tool for people just learning RegEx, so to give it more visibility, what about adding some kind of visual cues to cross-promote the tool?  Possibly something small/unobtrusive like the top location and/or a longer text blurb in the location on the right.  This could appear only when "no match" is found as to not clutter up the UI.

![2020-08-13_15h12_33](https://user-images.githubusercontent.com/54046315/90183151-a27aeb00-dd78-11ea-91b2-5d4416a4f44c.png)

**Comment by firasdib** [comment]
Great idea!

**Comment by firasdib** [comment]
This is implemented, will be pushed live soon!
