### ISSUE TITLE
Incorporate "basic debugging" / visual indication in editor when only one test string is specified

### ISSUE THREAD

**Issue by minig0d** [firasdib/Regex101#1376]
## Feature
Background: Even as I become more proficient with RegEx, inevitably I'll compose a longer RegExp (outside of this site) (ex. for a VSCode/N++ search and replace) which seemed simple enough that I could just freehand it but usually a typo or brain fart happens and a nice long RegExp doesn't match... (often thrown off by just one character).  And so I'll come over to this site and plug in my regexp and a basic test string and figure out where the problem is.  Currently it involves a lot of deleting segments of the RegExp to get back to the part that matches and fix the problem.  But currently there is no way to see where it is not matching without backspacing (or using the debugger tool I just learned about today IF its PCRE).

But what could be implemented unobtrusively, and save what I would imagine lots of people a lot of time debugging these really simple issues is to just have a visual indication of the inverse of the situation, showing up until which point the RegExp doesn't match the provided string.  The example/suggestion uses a bar below rather than highlighting the text, to prevent any confusion with any of the current syntax highlighting function.

Ex. in the below screenshot you can see I missed a ? after the s and I have a visual indication that points me exactly where to look.  Simple and unobtrusive but would save people countless hours, I'm sure! 

![2020-08-13_15h29_00](https://user-images.githubusercontent.com/54046315/90184113-39947280-dd7a-11ea-94df-ec4117f9cdbb.png)

**Comment by Doqnach** [comment]
For simple regex like this example it might work. It gets a great deal harder when dealing with more complex ones that contain backtracking. Also, at least the PCRE engine reports back the cursor position, but e.g. the JS engine does not. So such a feature would only work for specific engines and not across the board.

**Comment by minig0d** [comment]
Debugger doesn't appear to support JS and honestly I find it's really overkill in many situations.  I mean they are great as you mentioned for the very complex ones, but to me the above suggestion is akin to the squiggly lines in MS Word indicating a spelling mistake vs. running the full on spell-checker.  If there's a visual indication where the problem is often we can just quickly resolve the issue inline without having to switch over to a whole different interface. And while it may not help in every case, I would estimate that 90%+ of my "debugging" does not involve anything extremely complicated.

I don't know anything about the reported cursor positions or anything, but from a pseudocode standpoint, if it's not reported, couldn't it just iterate/increment through each character/group and if that one matches add the green bar below it, and stop when a non match is reached (except search forward to ensure it's not an optional match)?  ex. check h, then ht, then htt, then http, then https *NO MATCH*... then confirm there's no * or ? that would allow that s to not be required and therefore stop right there?

PS. I don't know how it works, but debuggex does support JS and has basically this functionality incorporated (they indicate it with a red underline rather than green to indicate the part that does match, but same concept) https://www.debuggex.com/

**Comment by firasdib** [comment]
While this is possible to some degree, it'll be at the expense of performance. It is also non-trivial to parse this sort of information as soon as the complexity of the expression increases.

I think a good middle ground would be to do what you suggested and add "smart links" to the debugger in the match information modal, at least as a start.

**Comment by minig0d** [comment]
Fair enough.

It could just be for basic cases though and if it hit any that were too difficult or intensive, suggest switching over to the full debugging tool if needed.  It also doesn't need to necessarily be prioritized in the JS.  Ex. could wait for the user to stop typing for a second and then start running (so that it was not constantly running).

Either way... just a suggestion.  If you don't like it feel free to close :)

**Comment by firasdib** [comment]
Its certainly not a bad idea, I'm just thinking about how to incorporate this into the UI in any meaningful way that is self-explanatory and meaningful.

The performance aspect can be worked around, but comes with a penalty in the form of complexity.

**Comment by minig0d** [comment]
I think the nature of it is pretty meaningful (i.e. as people insert or
delete text and see it move it becomes kind of self explanatory.)  But some
other ideas:

   1. Rather than just a green progress bar, have an orange background or
   red background that fills up in green.  And if you wanted labels could add
   a checkmark on the left and a X on the right of the bar?
   2. I really like the subtleness of a really low-key indicator, but could
   also incorporate the explanation in with the explanation of the RegEx
   syntax.
   [image: image.png]
   3.  Could add a checkbox and make people opt into the feature so they
   know what it is.
   4. Rather than a bar, could use a ^ right under the first non matching
   character if that is any more clear as in the first part of the expression
   that doesn't match.
   5. Could try to explain it in the above checkboxes.

Just a few things that come to mind.

**Comment by Doqnach** [comment]
What to do with a multiline regex `/.../x`?

Background colours will screw with the syntax highlighting.

Right now I see quite a few obstacles for implementing something that will work for a broad number of regex, both simple, complex and multiline.

**Comment by firasdib** [comment]
I think this is too closely related to just using the regex debugger. Unless I can come up with a better way to solve this for all cases, I'll keep refering to that.
