### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by fkupper** [firasdib/Regex101#1380]
## Bug Description
Sign in is not working.

### Reproduction steps
1. Click on sign in
2. try google
2.1 Nothing happens, no error, no console, no nothing
3. try github
3.1 Same as 2.1
4. try twitter
4.1 same as 2.1

### Expected Outcome
Sign in

### Browser
Firefox dev edition and chome

### OS
MacOS

**Comment by Alex-ley** [comment]
Same for me on Windows10 and Chrome

**Comment by firasdib** [comment]
Thanks for reporting. I messed something up yesterday, I’ll debug and fix as soon as I’m home from the gym 💪🏼💪🏼


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Doqnach** [comment]
Workaround is to manually navigate to the link behind the element (e.g.: https://regex101.com/connect/google?returnTo=/account/all for google).

**Comment by firasdib** [comment]
A fix has been pushed, issue is hopefully resolved now!
