### ISSUE TITLE
What is the URL request for Substitution ?

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1382]
## Question
![image](https://user-images.githubusercontent.com/10995302/90957954-791e3580-e4c3-11ea-948d-d7ce3a4c126f.png)

This revision does not feel useful, 
Every time you need to manually click on the left sidebar and switch manually, it feels less convenient than before.

### https://regex101.com/?delimiter=%60&substitution
👆 invalid

Prefer to restore the previous UI

**Comment by firasdib** [comment]
See here: https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url

The correct query parameter is `subst`

**Comment by dnknn** [comment]
Thanks♪(･ω･)ﾉ
