### ISSUE TITLE
Support dart

### ISSUE THREAD

**Issue by LiangLuDev** [firasdib/Regex101#1383]
## Feature
Can support the dart language？

**Comment by Doqnach** [comment]
> Dart regular expressions have the same syntax and semantics as JavaScript regular expressions. See ecma-international.org/ecma-262/9.0/#sec-regexp-regular-expression-objects for the specification of JavaScript regular expressions.

So it is supported by the ECMAScript flavour. Or are you looking for a code-generator for Dart?

**Comment by LiangLuDev** [comment]
OK   TKS
