### ISSUE TITLE
Unnecessary escape and incorrect recognition of dot inside square brackets

### ISSUE THREAD

**Issue by dev101** [firasdib/Regex101#1384]
## Bug Description
1) Dot inside square brackets requires unnecessary escape
2) Incorrect Description for dot inside square brackets incorrectly says  . matches a single character in the list  . (case sensitive)

### Reproduction steps
Consider the following JS regexp to match strings like "`XXX `" or "`XXX.`":

`/XXX[ .]/`

In https://regex101.com/

1) Description for dot in `/XXX[ .]/` incorrectly says  _. matches a single character in the list  . (case sensitive)_
2) Unnecessary escape `/XXX[ \.]/` is required for proper recognition of dot as literal

### Expected Outcome
1) Description for dot in `/XXX[ .]/` should be _matches the character . literally (case sensitive)_
2) Escaping dot inside square brackets is not required

### Browser
Any

### OS
Any

**Comment by Doqnach** [comment]
Working as intended.

https://regex101.com/r/R8ULwp/3

The description:
> Match a single character present in the list below [ .]
> . matches a single character in the list  . (case sensitive)
refers to the character class matching all the individual characters in the 'list' literally.

**Comment by dev101** [comment]
sorry, my bad.

I was confused because I expected explainations for `/XXX[ .]/` and `/XXX[ \.]/` to be the same, but they were different:

![image](https://user-images.githubusercontent.com/459389/91861354-64852e80-ec75-11ea-901d-546e73150f77.png)


![image](https://user-images.githubusercontent.com/459389/91861264-48818d00-ec75-11ea-9337-b43006f6213a.png)

Also I would recommend to make a notice about using unnecessary escape in `/XXX[ \.]/` similar to what [ESLint does](https://eslint.org/docs/rules/no-useless-escape). But this is for another feature request...
