### ISSUE TITLE
Unvalidated Open Redirection in regex101.com

### ISSUE THREAD

**Issue by febinrev** [firasdib/Regex101#1385]
### Security bug : Unvalidated Open Redirection in regex101.com

regex101.com allows Unvalidated Open redirection to malicious external sites.

#### Bug URL : [https://regex101.com/connect/github?returnTo=https://evil.com](https://regex101.com/connect/github?returnTo=https://evil.com)

The above URL will redirect authorized regex101 users to evil.com. evil.com could be a malicious external domain with phishing webpages or a url which delivers malwares to users.

### Expected Outcome
 Redirect authorized users to malicious sites.!

# Thank You!

**Comment by firasdib** [comment]
Thank you. This was a critical oversight by me, and has now been resolved. :star: to you!

**Comment by febinrev** [comment]
Hi  @firasdib ,
 It sounds great!
**_You can provide me a small credit by adding a recommendation to my openbugbounty.org profile, will add a +10 reputation in openbugbounty_** :  [https://www.openbugbounty.org/researchers/febin_rev/](https://www.openbugbounty.org/researchers/febin_rev/) 
 
Thank You!
