### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by klac** [firasdib/Regex101#1388]
## Bug Description
Regex returns false positive match. Position assertions are not respected.

### Reproduction steps
Regex:
^[\w-]+@[0-9a-zA-Z]+\..{1,3}$

Test string:
fjladfk_iasdfad234@sdlkjf23335.in
ha@git@int.cz
prashant24_@gmail.com

Returns
fjladfk_iasdfad234@sdlkjf23335.in
git@int.cz
prashant24_@gmail.com

### Expected Outcome
fjladfk_iasdfad234@sdlkjf23335.in
prashant24_@gmail.com

### Browser
Include browser name and version
Chrome

### OS
Include OS name and version
Win 10

**Comment by working-name** [comment]
Hi there,

I cannot seem to reproduce it. Are you still able to? If you're working with multiple regex101 pages open it's easy to get confused. Or at least that's what I tell myself to make myself feel better :)

On another note, your regex has a `.` that isn't escaped and thus will match any character that's not a line terminator given default flags `/gm`. Probably not what you want?

![Screen Shot 2020-09-15 at 11 24 22 PM](https://user-images.githubusercontent.com/16505052/93288767-a56b6000-f7aa-11ea-9582-9eccdf943d45.png)

**Comment by ret394** [comment]
match is the same

```
fjladfk_iasdfad234@sdlkjf23335.in
prashant24_@gmail.com
```

Escape is `\.` then `.{1,3}` for matching any character, so `\..{1,3}`. Depending on the file format, you'll have to omit the last character.

thanks
ret394

**Comment by working-name** [comment]
Please reopen if necessary.
