### ISSUE TITLE
Modifiers in the group have no effect outside the group

### ISSUE THREAD

**Issue by moonfruit** [firasdib/Regex101#1389]
## Bug Description
Modifiers in the group have no effect outside the group.
But it seems that the **Explanation** thinks this has an impact outside the group.

### Reproduction steps
For example:
https://regex101.com/r/V53Ay8/1

```regex
((?i)abc)def
```

This regular expression means match "abc" case **insensitive**, and match "def" case **sensitive**.
And it matches the string this way:

![image](https://user-images.githubusercontent.com/1070090/93580498-79cabe80-f9d2-11ea-9fc6-53387a231809.png)

But the **Explanation**:

![image](https://user-images.githubusercontent.com/1070090/93580237-16409100-f9d2-11ea-9215-c0900c6ea965.png)

### Expected Outcome

The **Explanation** should tell us that we want "def" case **sensitive**.

### Browser
Google Chrome 85.0.4183.102

### OS
macOS 10.15.6

**Comment by firasdib** [comment]
Thanks for this, excellent find! This has been adjusted, hopefully without introducing too many new bugs ;-)
