### ISSUE TITLE
Label Golang flavor as "(RE2)" as well

### ISSUE THREAD

**Issue by holisticmonkey** [firasdib/Regex101#1391]
It's not immediately clear from the UI that "Golang" is also RE2, suggest appending " (RE2)" to the label.

**Comment by Doqnach** [comment]
Do you have a source that shows that Golang's regex flavour is the same as RE2?

**Comment by holisticmonkey** [comment]
https://golang.org/pkg/regexp/

"Package regexp implements regular expression search.

The syntax of the regular expressions accepted is the same general syntax used by Perl, Python, and other languages. More precisely, it is the syntax accepted by RE2 and described at https://golang.org/s/re2syntax, except for \C. "

Assuming the regexp package is the standard Golang implementation of regular expressions and I'm reading the above correctly, that seems to indicate that Golang's regex flavour is the same as RE2.

**Comment by firasdib** [comment]
Good idea. Added.
