### ISSUE TITLE
Typing "100" as final step number in the debugger is not possible (minor problem, easy to workaround)

### ISSUE THREAD

**Issue by patrickroocks** [firasdib/Regex101#1393]
## Bug Description

If one wants to see steps number 1-100 in the debugger, the auto-correction of the text box for the debugger end point converts it automatically in the last debugging step.

### Reproduction steps

- Regex: ^(\w)+$
- Search text: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- Click on "Debugger"
- Select the text in the final step field ("50")
- Type "100"
- Instead "100", it appears first "2" (after typing "1"), then "20", then "189" in the text box (auto correction first converts 1 into 2, and finally converts "200" into "189")

### Expected Outcome

- auto correction should be applied when text box looses focus
- "100" should be the final step displayed in the text box

### Browser
Firefox 81

### OS
Ubuntu 18.04

### Workaround

- When "189" is displayed, select the "89" and type "00"

**Comment by groupGahzz** [comment]
> ## Bug Description
> 
> 
> 
> If one wants to see steps number 1-100 in the debugger, the auto-correction of the text box for the debugger end point converts it automatically in the last debugging step.
> 
> 
> 
> ### Reproduction steps
> 
> 
> 
> - Regex: ^(\w)+$
> 
> - Search text: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
> - Click on "Debugger"
> 
> - Select the text in the final step field ("50")
> 
> - Type "100"
> 
> - Instead "100", it appears first "2" (after typing "1"), then "20", then "189" in the text box (auto correction first converts 1 into 2, and finally converts "200" into "189")
> 
> 
> 
> ### Expected Outcome
> 
> 
> 
> - auto correction should be applied when text box looses focus
> 
> - "100" should be the final step displayed in the text box
> 
> 
> 
> ### Browser
> 
> Firefox 81
> 
> 
> 
> ### OS
> 
> Ubuntu 18.04
> 
> 
> 
> ### Workaround
> 
> 
> 
> - When "189" is displayed, select the "89" and type "00"

**Comment by firasdib** [comment]
I've fixed a related issue, where you were unable to use the arrow keys in these inputs. You can now shift-select and overwrite, which was the intended use case.
