### ISSUE TITLE
Cant Slove Task 6

### ISSUE THREAD

**Issue by autowert66** [firasdib/Regex101#1395]
## Question
Hello, i cant slove the Task 6 (Broken Keyboard).
My Problem is this:`Test 8/20: You're not replacing the strings according to the task description. For example, aaaaaa should become aa.`

Can i get a hint?

LG
autowert66

**Comment by Doqnach** [comment]
Please join the IRC chat if you are looking for help.

https://webchat.freenode.net/#regex

**Comment by kongmou** [comment]
(.)\1{2}

**Comment by Doqnach** [comment]
Please do not provide solutions/hints to the quiz in github issues, as to not spoil it for others.
