### ISSUE TITLE
PHP and /g modifier

### ISSUE THREAD

**Issue by bhsmither** [firasdib/Regex101#1396]
## Question
Is there a case where PHP's (I am working with 7.4) use of Pattern Modifiers includes `g` (global)?

If not, would it be appropriate to remove the `g` modifier when having selected the PCRE (PHP) engine? Or maybe create a sub-engine: PCRE, PCRE2, PHP5 PECR, and PHP7 PECR2?

**Comment by working-name** [comment]
Hi there, php is a special case where it has a dedicated function for /g, it’s called `preg_match_all()`. I have not heard of there being a different case with various php/pcre versions. 

As far as implementing PCRE2 changes/updates, last I heard it is being worked on. 

If you toggle the /g flag and click on code generator you’ll see the appropriate function is used. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Doqnach** [comment]
Actually, PHP 7.3 already changed to PCRE2 but they made some backwards compatibility changes.

https://wiki.php.net/rfc/pcre2-migration

**Comment by working-name** [comment]
Closing for now, please reopen if necessary.
