### ISSUE TITLE
experimental dump for testing Intel's hyperscan regex engine

### ISSUE THREAD

**Issue by x0rzkov** [firasdib/Regex101#1397]
Hi,

Hope you are all well !

I am posting this issue because I am working on a multiple regex processor with [Intel's hyperscan ](https://github.com/intel/hyperscan) library for an advanced chatbot with [deeppavlov](https://github.com/deepmipt/DeepPavlov) framework.

The only thing that I am missing it is a big dataset of regexes with their labels for building a hs dictionnary.

Do you think think that you can share a csv file with the format rule_name; rule_regex; rule_type; rule_desc with me ?

That would be really kind and awesome if I could get such dataset as I am sure that there would lots of fine tuning to do with hyperscan.

Thanks for any insights or input on that question.

Ps. here is my telegram "**deepocrates**" or twitter account: "**x0rzkov**" if you want to DM me.

Cheers,
X

**Comment by Doqnach** [comment]
Can you give an example of what `rule_name`, `rule_regex` and `rule_type` would be?

I'm not the person to decide on this, but keep in mind that people save their regex expecting that no one but them (and people they give the link to) will access the data, and sometimes it even can contain sensitive data. So sharing the database doesn't really seem like an option to me I'm afraid.

**Comment by x0rzkov** [comment]
Hi @Doqnach 

Thanks for your reply !

At least the one available at https://regex101.com/library?filterFlavors=golang&filterFlavors=python&filterFlavors=javascript&filterFlavors=pcre since they are public.

AN example would be (from https://regex101.com/library/kek0l4):
```csv
"Find ipv6 subnet","((?:(?:(?:[0-9a-fA-F]){1,4}):){1,4}:/[^\s:]\d{0,2})","PYTHON"
```

Hoping that's helpful !

**Comment by Doqnach** [comment]
You might be able to do that yourself then, see: https://github.com/firasdib/Regex101/wiki/API#list-andor-search-all-library-entries-

**Comment by x0rzkov** [comment]
Thanks 👍 

You won't ever feel it :-)

**Comment by Doqnach** [comment]
Closing the issue for now then. If you need any more help, just post again!
