### ISSUE TITLE
suggest use of String.prototype.matchAll in certain situations

### ISSUE THREAD

**Issue by boneskull** [firasdib/Regex101#1398]
## Usability/Documentation Issue

Using the "global" flag, JS' [`String.prototype.match`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) does not return an array having  a `groups` property containing named capture groups. Such a regex may demand use of [`String.prototype.matchAll`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll) instead of `String.prototype.match`.

### Example

1. Create a regular expression using ECMAScript/JS style using a named group and the "global" flag, e.g., [this one](https://regex101.com/r/bkRobU/1)
1. Copy & paste the regex into JS, e.g.:

    ```js
    let regex = /(?<word>\w+)/g;
    let result = 'foo bar baz'.match(regex); // ['foo', 'bar', 'baz']
    result.groups // undefined
    
    let result2 = [...'foo bar baz'.matchAll(rx4)]
      .map(match => match?.groups?.word) // ['foo', 'bar', 'baz']
    ```

### Suggested Change

If a user was not aware of the limitations, they may expect that the call to `String.prototype.match` would return named groups (as it does _without_ the global flag), since that's clearly intended by the regular expression.  Given named capture groups aren't very popular in JS, I imagine few developers know this until they run into it.

It may be helpful for the site to display a suggestion to use `String.prototype.matchAll` in the case that a regex:

- uses the JS engine
- contains a named group
- has enabled the global flag

I'm not sure if there's a precedent for this sort of guidance elsewhere on the site.

**Comment by Doqnach** [comment]
Named capture groups are a relatively recent addition to JS (ES2018 I believe?) and according to this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility

That can make it debatable if the code generator should use that method or something that is universally supported. But I can see the point of maybe going along with newer developments of course.

The code generator does not aim to provide you with the best possible method for each use-case, but simple with an example that shows you some basic output as a starting point.

**Comment by boneskull** [comment]
Understandable.  Wasn't sure if it was in scope.  Thanks!

**Comment by firasdib** [comment]
For now I think we keep the existing implementation!
