### ISSUE TITLE
Wrong match returned

### ISSUE THREAD

**Issue by shreepai** [firasdib/Regex101#1401]
I am trying to match a pattern [^I]*I with a string "II". This should ideally have returned only one match but it returns two matches.

**Comment by working-name** [comment]
Hello! That quantifier `*` means `match 0 or more of the previous, as many times as possible`. If you just keep `I` as your regex, you'll get the same result. If you need further help with regex, please join us on IRC (freenode, #regex).

**Comment by shreepai** [comment]
Incorrect query

**Comment by shreepai** [comment]
Thank you for your response. Missed this email somehow.

I was looking to a check how many sequence of "I"s exist within a given
string

e.g. "ISIXPIITI9III" should return 3

So I tried to match every I that was not preceded by an I.

But it did not work the way I assumed.

Thanks,
S
