### ISSUE TITLE
flag groups doesn't working in python

### ISSUE THREAD

**Issue by mujtabaxd** [firasdib/Regex101#1403]
## Bug Description
When using flag groups in python env, they doesn't match.

**Regex**
`(?i:foo)bar`
**String**
`foobar`

Output should be foobar, but it throws invalid group structure error.
### Browser
Chrome 86.0.4240.111
### OS
Win10 v2004

**Comment by firasdib** [comment]
This is because the website emulates python 2.7, not 3.x

This is a larger issue, so I will close this issue for now, as its not really a bug. The discussion regarding which python version is ongoing on this forum already.
