### ISSUE TITLE
Expression for multiple substrings with a concrete position and length

### ISSUE THREAD

**Issue by gerchicov-bp** [firasdib/Regex101#1408]
## Bug Description
```
(?<=^.{3}).{2}|(?<=^.{8}).{5}
```
Your website shows one match but in reality if the string is enough long this expression returns 2 matches. Checked on iOS and 
regexr.com

### Reproduction steps
Just input this regex and any text. Actual result - 1 match

### Expected Outcome
2 matches.

### Browser
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

### OS
Include OS name and version
MacOS Catalina 10.15.6

But the bug is independent from OS and browser

**Comment by Doqnach** [comment]
Please provide an example saved regex that shows the behaviour that you state here is wrong.

**Comment by working-name** [comment]
I'm unable to reproduce the bug, I always get 2 matches as soon as I hit 13 characters which is according to your regex's instructions. Please reopen if you are able to reproduce the issue.
