### ISSUE TITLE
character classes and hyphen

### ISSUE THREAD

**Issue by laszloplanetart** [firasdib/Regex101#1409]
## Feature: Warning about middle-of-character-class literal hyphens.

It is pretty commonly known that hyphens should be at the beginning or end of character classes to prevent ambiguity.
However, it so happens that hyphens in the middle can also mean literal hyphen, eg., if immediately following another range. So, it can lead to easily mutilated regex if working on teams.

[a-z0-9-\'] : range a-z, range 0-9, literal hyphen, literal apostrophe.

[a-z0-9~-\'] : character range out of order ~ to \'

[a-z0-9 -\'] : range a-z, range 0-9, space through apostrophe

would be nice to be warned that it is poor practice to have literal hyphens inside character classes and that they should really be at the beginning or end as first or last character always.

**Comment by firasdib** [comment]
Thats a great idea. I'll implement this and push it asap!
