### ISSUE TITLE
C++ flavor

### ISSUE THREAD

**Issue by neico** [firasdib/Regex101#141]
TR1 / C++11 has native regex support, but since the code looks quite different then on other languages (the lack of delimiters and modifiers) it could need a dedicated flavor section.

There's also the problem that C++ supports a broader range of regex grammars:

| Grammar | Description |
| --- | --- |
| ECMAScript | the default (http://www.cplusplus.com/reference/regex/ECMAScript/) |
| basic | basic POSIX grammar |
| extended | extended POSIX grammar |
| awk | awk POSIX grammar |
| grep | grep POSIX grammar |
| egrep | egrep POSIX gramar |

This entire thing might very well go out of the scope of the website but would help C++ programmers that didn't (or couldn't) bother with regex until recently.

As far as I've read so far ECMAScript seems to be the javascript grammar so one could adjust to that one pretty easily.

I hope that it's possible to add that to the website at some point as it can get really troublesome testing regex on any bigger c++ project as the compile times can take quite a while...

**Comment by rafzi** [comment]
I just got an inconsistency where { would match the character on r101, but failed to compile in C++. It requires the character to be escaped.

re:
`    func\s*{([\s\S]*)}\s*$`
str:
```
func
{
  body
}
```

Found from here (2nd section, 2nd paragraph):
https://www.regular-expressions.info/stdregex.html

**Comment by Doqnach** [comment]
You mean this as a bug in the code generator? Since C++ is not yet supported as a flavour. Best to open a new bug for that instead of commenting here.

**Comment by rafzi** [comment]
@Doqnach Sorry I was not clear enough.

My comment had the purpose to outline further motivation to support the flavour.

I'm not aware of a bug on r101 in this case, but it misguided me to think my RE was also valid for C++, which it was not.

**Comment by neico** [comment]
Which is why it's important to add flavours to the website, and if only as an alias to a existing one.
Not everyone is aware of which language supports which grammars across the board.

As I mentioned when I opened this issue, C++'s default syntax is `ECMAScript` which is basically JavaScript grammar (Not sure if there are actual differences to it tough), so as a first step one could rename "Javascript" to "ECMAScript (JavaScript)" (much like it is for PHP), which would make it easier to identify for the C++ people
eventually the website should get a C++ dropdown with all the flavours for optimal coverage (I mean, the others should be all easier to implement as they aren't as complex as regex)

**Comment by firasdib** [comment]
@neico Thats not a bad idea, perhaps calling it ECMAScript might be clearer.

I would add `C++` and just use JS to evaluate it, but I think that might be a bit confusing as there will be no C++ specific handling.

**Comment by Doqnach** [comment]
Is it an idea to maybe split the flavours in "native" and "emulated" sections, with a caveat for the "emulated" section that the implementation might not be 100% complete and a link to "known issues"?

Related also somewhat to #1050

**Comment by firasdib** [comment]
@Doqnach Thats not a bad idea.

Should python be in that section then? Its emulated, but its implemented to 99% of native.

**Comment by Doqnach** [comment]
Putting Python under "Emulated" has the advantage of being 99% covering and providing a hook for people to understand to not expect 100%? So I would go for emulated in that case. If emulated is 100% covering: sweet! But at least it leaves you an explanation for that 1%.

**Comment by firasdib** [comment]
@Doqnach We also open up for "omg what does this mean? can I even use it anymore?"

**Comment by Doqnach** [comment]
For keeping this thread clean: see #1074

**Comment by firasdib** [comment]
I've renamed `Javascript` to `ECMAScript (JavaScript)`, which I think is a great change. If anything else is needed, open a new issue (perhaps reference this).
