### ISSUE TITLE
unicode error 

### ISSUE THREAD

**Issue by macheteHot** [firasdib/Regex101#1412]
## Bug Description

set regex \p{sc=Han}*
test string  一二三
### Reproduction steps

\p{sc=Han} This script is unknown/invalid
+ The preceding token is not quantifiable
### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by Doqnach** [comment]
What flavour of regex do you want to use this in? Because that notation is not valid for PCRE or Python (maybe it is for JAVA/C#?).

https://regex101.com/r/sNyoQf/1

Those characters also don't seem to fall under the `Han` script as far as I can tell from this.

**Comment by Doqnach** [comment]
Update:

```
let regexp = /\p{sc=Han}/gu;
12:38:45.944 undefined
12:39:12.146 let str = `一二三`;
12:39:12.148 undefined
12:39:18.763 str.match(regexp)
12:39:18.769 (3) ["一", "二", "三"]
```

Does work in a modern browser.

**Comment by macheteHot** [comment]
> 更新：
> 
> ```
> let regexp = /\p{sc=Han}/gu;
> 12:38:45.944 undefined
> 12:39:12.146 let str = `一二三`;
> 12:39:12.148 undefined
> 12:39:18.763 str.match(regexp)
> 12:39:18.769 (3) ["一", "二", "三"]
> ```
> 
> 可以在现代浏览器中使用，但不能在regex101上的javascript风格下使用。

yes this is bug

**Comment by firasdib** [comment]
The parser currently only accepts `Script=Han`, is this case insensitive? I did not know the shortcut `sc` existed. Are there more shortcuts I need to consider, and are they case insensitive?

**Comment by firasdib** [comment]
I've fixed this case now.
