### ISSUE TITLE
ICU flavor

### ISSUE THREAD

**Issue by lilyball** [firasdib/Regex101#1414]
## Flavor Request

ICU defines its own regular expression package. This is the syntax used by Apple's Foundation framework (for macOS and iOS), or anyone else who uses libicu for regular expressions.

Documentation: https://unicode-org.github.io/icu/userguide/strings/regexp.html

**Comment by working-name** [comment]
Hi @lilyball, is there a specific issue you bumped into that PCRE flavor isn't able to handle? It looks like `\K` is missing from the libicu implementation but otherwise it's perl.

**Comment by lilyball** [comment]
Is that really the only distinction? I didn’t do an exhaustive comparison of PCRE vs ICU so I wasn’t sure what other differences may exist.

My basic concern is if I’m writing regular expressions for use with Apple’s Foundation APIs and I want to test them, I want to make sure I don’t accidentally use something that ICU doesn’t support. If `\K` is really the only distinction then that’s easy enough to simply remember.

**Comment by working-name** [comment]
I just skimmed through the link you posted and that's the only thing that jumped at me. If you bump into any issues with your regex you can always visit us on IRC (freenode, #regex) and someone will provide guidance for your pattern(s) - alternates, optimization, answer questions, make you lemonade. Kidding about the last one only.

**Comment by firasdib** [comment]
I'll close this for now, if there are large enough differences to warrant its own flavor, we can look into it then!
