### ISSUE TITLE
Somehow highlight the parsed characters

### ISSUE THREAD

**Issue by stdedos** [firasdib/Regex101#1416]
## Feature

for `s/(I am) \S+/`, the output feels a bit missing
![image](https://user-images.githubusercontent.com/133706/100345436-fee1dd80-2fea-11eb-9d5e-4a4743c00b9a.png)

(e.g. use a dark background color with high transparency like this ` ` (`rgba(27,31,35,0.05)`) or use `⎵` or https://ux.stackexchange.com/a/91256/140701)

**Comment by firasdib** [comment]
Not a bad idea, I've decided to just place a faint background on strings which are nothing but whitespace, to indicate something is there. I was initially going to show the actual characters in some way (like I do in the editor, when the white space setting is enabled), but this got too cluttered. 

I'll push this live soon!

**Comment by stdedos** [comment]
Now that this update makes my second point more clear:
![regex101 com_](https://user-images.githubusercontent.com/133706/102936985-d77b1500-44b1-11eb-8a23-dbd87b420b50.png)

The `⎵ matches the character ⎵ ...` text feels a little unaligned considering the other two groups.
I understand that the other groups have a nesting level (and therefore the down-arrow-image pads the left side).

It would look better in my eyes if all of the matching stuff start at the same x-coordinate (which would mean imaginary padding for the aforementioned line.

Finally, I thought that the regex field would accept `s/(I am) \S+/`, `s/(I am) \S+/g` to be pasted / parsed (by removing `s/`, `/`, and maybe even parsing the flags when they exist `g`), but that's not the case. Was it always like so, or is this newly broken?

**Comment by firasdib** [comment]
Ah, I see your point. I will see what I can do about the padding!

Regarding your other point, you need to use the correct syntax:

`s/regex/replacement/flags`, for example, `s/(I am) \S+//g` or just `/(I am) \S+/g` if you don't want substitution.
