### ISSUE TITLE
2 bugs unicode related

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1417]
## Bug Description

first bug: https://regex101.com/r/I16dQb/5 when /u is used, the unicode range are accepted, but when /u is not used and you anchor your pattern with (*UCP), it reports an offset is too large error, which i believe is wrong as /u is only (*UCP) + (*UTF) where (*UTF) only decodes your input and pattern from utf (it's utf16 on the website).

second bug: when you use a range with a character class with unicode letter beyond the bmp, the explanation panel reports the code point of the first surrogate instead of the correct code point: https://regex101.com/r/I16dQb/6

Edit: it's not (*UCP) that's required for the first issue, it's (*UTF) or (*UTF16) for the website, however with it it's still not working.

I have made some research about (*UTF) then, trying to find in pcre.txt where it says that this is what enables \x{} to support more char.

There are some things I don't understand and hope @firasdib can explain.

I take it the pcre lib used on the website is built with --enable-pcre16 and --disable-pcre8, with the website using utf16.

The pcre lib says:
By default, a library called libpcre  is  built,  containing  functions that  take  string  arguments  contained in vectors of bytes, either as single-byte characters, or interpreted as UTF-8 strings. You  can  also build  a  separate library, called libpcre16, in which strings are contained in vectors of 16-bit data units and interpreted either as single-unit characters or UTF-16 strings.

So after the lib is built, when you use the function to compile a regex:
When using UTF strings you must either call the compiling function with the PCRE_UTF8, PCRE_UTF16, or PCRE_UTF32 option,  or  the pattern must start with one of these special sequences:  (*UTF8),  (*UTF16),  (*UTF32)

So if one doesn't use /u or (*UTF16) then the utf16 that is passed to pcre from the website is not getting decoded
I then don't understand why /./g on an unicode char that takes two 16 bits surrogate to form is not reporting two matches on the website?

**Comment by firasdib** [comment]
To address the first issue, which you seem to have identified yourself, is that `UTF16`-verb is required, not `UCP`. 

```
PCRE_UCP

       This option changes the way PCRE processes \B, \b, \D, \d, \S, \s,  \W,
       \w,  and  some  of  the POSIX character classes.
```

This is not handled by the website currently, but will be fixed shortly. I imagine there are more places where this is not handled properly, but we can deal with that as we find those bugs.

As for the second issue, you are correct this is not handled properly. I'm not sure if there is a good solution to this though, because you are technically creating a range with the second part of the first surrogate, and the first part of the second. I think this should be an error, since its non-trivial and likely very confusing, since you're not creating a range between the characters on the screen.

I'm not entirely sure about your last anecdote though, perhaps you can explain over IRC at some point.

**Comment by Ouims** [comment]
Thanks for fixing these. I'd love to discuss it on IRC but you're never there :)

The question is simple, if (*UTF16) is making pcre decode your input string from utf16, then not using (*UTF16) is making pcre not decode anything. Which means that if you pass an unicode character's code point that is beyond the bmp and need two surrogates (16 bits) to be represented and you're not decoding, then the dot . should be matching one 16 bits data unit, and since there's two in this case, reports two.

**Comment by Ouims** [comment]
In fact, although this is all correct now as far as pcre is concerned, there is a concern about the usefulness of this.
Matching lone 16 bits data unit can be done with \C already, although that can lead to error.
So this https://regex101.com/r/I16dQb/10 results in 2 matches for only one 'character' input, which gets no highlight
There is 'paradox' between allowing user to do no unicode regex search and allowing them to input unicode character formed with more than 16 bits (to be specific).
I wonder if you should not enforce (*UTF16) because the website is really about visualizing the match via the colors highlights etc.
I also was wondering why are (*UCP) and (*UTF) two differents options because if (*UCP) is about changing \w \d etc for unicode and you're not passing (*UTF) then it's not possible to ever match the unicode char with \w etc so it would make no sense to pass (*UCP) without (*UTF)?

An idea may be to enforce /u (at least (*UTF16)) whenever the user input an unicode character beyond the BMP and if he manually try to unselect the /u modifier, warn him that he is about to do 16bits data unit based match.

**Comment by firasdib** [comment]
I think the current behavior is great, and reflects the behavior you would see in the real world. Implicitly adding UTF-16 verb or always using the unicode-flag is not desirable. 

They do two different things as I explained earlier, one affects the syntax, one affects the matching.
