### ISSUE TITLE
Conversion PCRE_EXTENDED in one line regex

### ISSUE THREAD

**Issue by ReinRaus** [firasdib/Regex101#142]
I propose to make the checkbox in the "Code Generator", which converts the original expression PCRE_EXTENDED in one line.  
It would be convenient to separate:  

 - Development and debugging regular expressions for regex101 
 - Insert the code in a compact expression without unnecessary whitespace and comments

------------------------------------
**Original message without translation**  
Предлагаю сделать чекбокс на вкладке "Генератор кода", который конвертирует исходное выражение PCRE_EXTENDED в одну строку.  
Это было бы удобно для разделения:  

 - разработка и отладка регулярного выражения на regex101   
 - вставка в код компактного выражения без лишних пробелов и комментариев

**Comment by firasdib** [comment]
This issue has been open for quite some time now, no one else has requested this and I personally don't agree with it. Closing for now.
