### ISSUE TITLE
PCRE (PHP) and not (Perl) ?

### ISSUE THREAD

**Issue by bobf** [firasdib/Regex101#1424]
## Question

PCRE stands for "Perl Compatible Regular Expressions". I understand that PHP who also uses this implementation so it makes sense to include PHP there, but it seems strange to me to not include Perl as well in the label !

I am just wondering if the omission was deliberate or not ? It's not a big deal either way. :-)

**Comment by Doqnach** [comment]
It is deliberate. I think the reason being that for a good number of (beginning) PHP users, they might not know they are looking for PCRE. I'm quite sure that most Perl users know very well, with very few people starting new with Perl. So the label containing '(PHP)' is mostly a little extra hint for those (beginning) PHP users.

**Comment by bobf** [comment]
That makes sense ! Thanks for answering.
