### ISSUE TITLE
Quick Reference: examples for group recursing should specifically show recursing not matching already matched text

### ISSUE THREAD

**Issue by piotr-dobrogost** [firasdib/Regex101#1425]
In Quick Reference there are examples of group recursing which do not clearly show that what is being done is recursing as opposed to matching already matched text.
For instance 

> RECURSE NAMED CAPTURE GROUP \`LETTER\`
> `\g'letter'` Recurses the capture group called \`letter\`.
> `/(?'letter'a).*(\g'letter')/`
> a plus a

It would be better to have the following example:
> `/(?'letter'\w).*(\g'letter')/`
> a plus b

The same goes for
> RECURSE SUBPATTERN \`NAME\`
> `/((?P>who))[a-z ]+(?P<who>one)/`
> one does not simply eat one pie

and for (btw, the title is wrong here as it's recursing not matching; will raise separate issue for this)
> MATCH NTH RELATIVE UPCOMING SUBPATTERN
> /g'+1' and (b)/
> extra b and b stuff

and probably more…

**Comment by firasdib** [comment]
Thanks for your feedback!

@working-name You got any free time :)?

**Comment by working-name** [comment]
Revised recursion vs matching examples to make it more obvious as to which one does what. Thank you!
