### ISSUE TITLE
Quick Reference: option to load example into editor

### ISSUE THREAD

**Issue by piotr-dobrogost** [firasdib/Regex101#1426]
When viewing entry in Quick Reference it would be nice to be able to copy both pattern and test string into editor to play with.

**Comment by firasdib** [comment]
Should this replace the content of the editor? Append it? Or should this just append the current token you're viewing into the editor?

**Comment by piotr-dobrogost** [comment]
> Should this replace the content of the editor?

I think so. This would be a way to quicky try out examples as a form of learning by playing.

**Comment by firasdib** [comment]
Hmm, could be a bit annoying if you're working on something and then have your stuff replaced. But adding a "Are you sure?" modal is quite annoying too.

**Comment by Doqnach** [comment]
I think the user experience could be disruptive indeed. I understand the given use-case, but I don't think this is a very common usage for the website.

Maybe some spin-off at some point could be a more "educational" offshoot of the website, with the quiz and a playground based on the quick reference and/or https://www.regular-expressions.info/ style documentation.
