### ISSUE TITLE
Quick Reference: confusing reference to (?P=named_group) in the entry for (?&name)

### ISSUE THREAD

**Issue by piotr-dobrogost** [firasdib/Regex101#1427]
In the entry for (?&name) (**RECURSE** SUBPATTERN \`NAME\`) one reads

> Recursively matches the given named capture group. Python supports (?P=named_group), but 'named group' has to be previously defined.

However in the entry for (?P=name) (**MATCH** SUBPATTERN \`NAME\`) one reads
> Matches the text matched by a previously named capture group. This is the python specific notation.

So as the latter – (?P=name) – is about matching already matched **text** and the former – (?&name) – is about recursing (matching referenced **pattern**) it is unclear why the latter is referenced in the entry for the former.

**Comment by firasdib** [comment]
Thanks for your feedback!

@working-name You got any free time :)?

**Comment by working-name** [comment]
Fixed.
