### ISSUE TITLE
Quick Reference: use consistent order for different ways of referencing a group

### ISSUE THREAD

**Issue by piotr-dobrogost** [firasdib/Regex101#1430]
In _Meta Sequences_ section there are the following entries (in order):

- `\g{n}`
- `\g<n>`
- `\g'n'`

and a bit later the following ones:

- `\g'letter'`
- `\g{letter}`
- `\g<letter>`

I would suggest keeping consistent order for different ways of referencing a group between the two sets.
That means the following ordering:

- `\g{letter}`
- `\g<letter>`
- `\g'letter'`

**Comment by joko300370** [comment]
i need support in problem out going tranfers

**Comment by firasdib** [comment]
Thanks for your feedback! I can see @working-name is already on it :)

**Comment by working-name** [comment]
Thank you for that, reorganized entries to be consistent, and grouped them together where appropriate; `\g{n}` and `\g{-1}`
