### ISSUE TITLE
Quick Reference: wrong title "MATCH NTH RELATIVE UPCOMING SUBPATTERN" for \g'+n'

### ISSUE THREAD

**Issue by piotr-dobrogost** [firasdib/Regex101#1431]
The title _MATCH NTH RELATIVE UPCOMING SUBPATTERN_ in section _Meta Sequences_ for `\g'+n'` is wrong as this is recursing not matching. The title should be the same as the one for the previous entry `\g<+n>` – _RECURSE NTH RELATIVE UPCOMING SUBPATTERN_.

Also, pattern in the example – `/g'+1' and (b)/` is missing backslash before `g`.
In addition, as described in https://github.com/firasdib/Regex101/issues/1425 this pattern is not the most fortunate for showing recursing.

**Comment by working-name** [comment]
Fixed, thank you!
