### ISSUE TITLE
Quiz Task 16, Test 2 bug or typo

### ISSUE THREAD

**Issue by UltraHex** [firasdib/Regex101#1435]
## Bug Description
Quiz Task 16, Test 2 has wrong test condition or a typo in its description.
It erroneously claims a regex does not match `word word word`.

### Reproduction steps
Goto https://regex101.com/quiz/16
enter the regex `word word word`
click submit

### Expected Outcome
The test should be passed or the description should accurately indicate why the test failed.

### Browser
Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

### OS
Windows 10

**Comment by Doqnach** [comment]
I think the hint indeed misses one occurrence of the word `word`.

**Comment by UltraHex** [comment]
Through trial and error I have deduced that test 2 is checking for "hello hello hello".

`^(?:word word word word|hello hello hello)$` passes.

**Comment by Doqnach** [comment]
I totally get your point, and I think it is valid indeed. The chosen wording of the hint can put someone on the wrong foot.

**Comment by UltraHex** [comment]
Yes. That happened to me. My regex was only matching 4-letter words and I couldn't tell why it wasn't passing test 2.

**Comment by firasdib** [comment]
Thanks, I'll update the test to actually use `word word word`.
