### ISSUE TITLE
Set default code generator (feature request)

### ISSUE THREAD

**Issue by ssent1** [firasdib/Regex101#1436]
Please consider adding a setting to **configure a default code generator language**.

At present, it defaults to `PHP`. It would be cool if it could be set to any language.

**Comment by OnlineCop** [comment]
![DefaultFlavor](https://user-images.githubusercontent.com/1168697/102636208-95e51580-4111-11eb-9cdd-12ff32f0398c.png)

**Comment by OnlineCop** [comment]
Click [settings](https://regex101.com/settings) on the left. You can choose from `pcre`, `javascript`, `python`, and `golang`.

I know that the URL updates when you click "Code Generator", such as: https://regex101.com/codegen?language=csharp but I don't know whether the base "flavor" can be updated in the same way, such as https://regex101.com/?language=javascript (as that still takes me to the default PCRE page).

**Comment by OnlineCop** [comment]
Whoops; I may have misread the original message. This was asking for the **code generator** default language, not the site's default language. Reopening so @ssent1 can confirm the original intent.

**Comment by firasdib** [comment]
The code generator follows the current selected flavor, but I can see a use case for defaulting to a specific language, since there is no one-to-one mapping between the two...

I'll add this and push it live asap.
