### ISSUE TITLE
Non-Capturing Group capturing group

### ISSUE THREAD

**Issue by EduardoMahl** [firasdib/Regex101#1437]
## Bug Description
Using a Non-Capturing Group (e.g. "(?:lorem)")  captures the group (in this case "lorem") along with the rest of the matched expression.

### Reproduction steps

Insert " (?:\/[0-9]{4}).+" as the Regular Expression and "CNPJ:04/12/2020 16:30" as the Test String. 

### Expected Outcome

" 16:30"

### Browser
Include browser name and version
Firefox Browser 83.0 (64-bits)

### OS
Include OS name and version
Windows 10 ver. 1909

**Comment by Doqnach** [comment]
https://regex101.com/r/UabV5u/1

Do you mean the "Full Match"? The "Full match" is always your entire regex match. There is no group match.

Compare it with the result of: https://regex101.com/r/UabV5u/2 (which doesn't use a non-capture group)

**Comment by working-name** [comment]
Hey Eduardo,

I wasn't able to replicate the bug. If the above information proves to be out of scope please reopen the issue or join us on IRC (live help link on the site) to further discuss your regex needs in a live manner.

> initial regex with what I perceive to be an extra space character in the beginning, typo most likely.

![extra space would never match test string](https://bugout.regex.cf/extraspace-NwYmthSeRVE7ZccaFfAzAiq8XhRyoJlcDgaRp11F3pAJxRNJqLAwXS4IimUdIKaD4t6zsbdRDG3TMnanh3EwlhPWgoxOIjE50ulR.png)

> yet another way to isolate your expected outcome, on top of Doqnach's excellent suggestion above

![another option](https://bugout.regex.cf/expected-1ctepaoUhIeiOb8rnCNwq0vxU4aDlvrzVoJI7LCkJGOc72TLsPPfSWoCv07N07gJWmVmBvnQ6wshM6BHlzooae8GOCUA34s0achN.png)

> non-capturing group vs capturing group seems to function as expected in Firefox 84 and 83

![84](https://bugout.regex.cf/noncapture-still-matches-Nx0wzjkUKWP1yaxtbNV9Pd1NR7NOTZoPnw5kKkZpkHGn3xjJ1nytT5YQ1ylkHASke2FMUpymKL4hegFmqaVRQuO2epMWnhQIN7uZ.png)

![83](https://bugout.regex.cf/83-ok-0xofuInADPhWdKCQgLn7RCQ1LPkHMOxHXq9QJ7pfLTE12HiIAH7HkPEblo8LUImIXY5JroebPFwZfU14CeSH8zxkCnKBzL4OWSk6.png)

**Comment by EduardoMahl** [comment]
Problem is, I don't know what will come after the "/2020" as it won't follow any specific pattern. Hence the usage of something that compares behind without adding it to the result. 

https://regex101.com/r/ZHdfRZ/1

Link to @working name

**Comment by working-name** [comment]
@EduardoMahl In that case @Doqnach's /v3 is excellent. If lookarounds are not an option to your regex engine, you can also simply capture what comes next and access your data by referring to capture group 1: https://regex101.com/r/ZHdfRZ/2
