### ISSUE TITLE
Change Header Color in Dark Mode

### ISSUE THREAD

**Issue by akhilesh-balaji** [firasdib/Regex101#1439]
## Feature
Hello there!
This is an amazing tool, and I use it with dark mode. However, the top header looks really weird to me in dark mode, so I would suggest a small change from this:

![image](https://user-images.githubusercontent.com/69246693/102678279-609dfd80-41cd-11eb-80c5-3961c7c5ec7e.png)

to this:

![image](https://user-images.githubusercontent.com/69246693/102678303-7ca19f00-41cd-11eb-8108-d6e717bafa09.png)

**Comment by firasdib** [comment]
Hmm, I'm not entirely convinced. Looks a bit too monocrome in your version in my opinion. I'll leave this open in case anyone has any other ideas!

**Comment by Doqnach** [comment]
I would not mind the top bar to be a bit darker shade, but I agree that to me personally the suggested colour would be too monochrome as well.

**Comment by firasdib** [comment]
I've updated the dark theme slightly, have a look and see what you think.

**Comment by akhilesh-balaji** [comment]
@firasdib This looks much better, Thanks!

**Comment by firasdib** [comment]
Thats a bit too complex for the current setup unfortunately. But I'm glad you like the change! I'll close this for now :)

**Comment by Doqnach** [comment]
@akhilesh-balaji that is something that can always be completed via something like Stylus (userstyles).
