### ISSUE TITLE
The debug info is not correct when check it step by step

### ISSUE THREAD

**Issue by chucklu** [firasdib/Regex101#1441]
## Bug Description
step info not correct

### Reproduction steps
test the regex `(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])[a-zA-Z0-9]{8,15} with Abc1234$`
The debug info shows step 27 as following:
The number 4 is red, actually it matches when check the step 27,which required to match [0,9]
![image](https://user-images.githubusercontent.com/3004057/102854520-a7a22200-445d-11eb-9d48-380d90d93eff.png)

### Expected Outcome
step 27, the number 4 should match

### Browser
Include browser name and version
Google Chrome, Version 86.0.4240.198 (Official Build) (64-bit)

### OS
Include OS name and version

Microsoft Windows [Version 10.0.18363.1199]

**Comment by firasdib** [comment]
The character is accepted at step 28. This is the expected behavior.

**Comment by chucklu** [comment]
@firasdib  But it‘s confused when see the red color in step 27.
And 81 steps only show 50 steps of them.
