### ISSUE TITLE
previously working regex rejected with error "Character range with surrogate pairs without unicode enables results in ambiguous behavior"

### ISSUE THREAD

**Issue by Felk** [firasdib/Regex101#1442]
I have used regex101 extensively to debug somewhat simple C# regular expressions by using the ECMAScript flavor. However, since recently regular expressions involving character ranges of surrogates get rejected with the error "Character range with surrogate pairs without unicode enables results in ambiguous behavior". I was unable to find out what kind of ambiguous behaviour this means, as they used to work perfectly fine and deterministic before as far as I could tell. Given that it was specifically constructed to deal with UTF-16 characters, as is the case for C# regexes. One regex in question would be this one that is supposed to detect all 4022 emojis in the test string: https://regex101.com/r/dQEURi/30

Is there a way to revert to the previous behaviour? Given that there is no C# flavor available (yet), there unfortunately is now no way to debug UTF-16 based regexes containing surrogate character sets on regex101 anymore :(

**Comment by firasdib** [comment]
Thanks for pointing this out! This was to try to alleviate the issues here: https://github.com/firasdib/Regex101/issues/1417

I'll publish the fix asap.
