### ISSUE TITLE
does not display highlighted newline matches intuitively

### ISSUE THREAD

**Issue by tsujp** [firasdib/Regex101#1443]
## Bug Description

Given the example regex `(?<=BLOCK)(\n)+` and example string you'd expect to see all newlines after `BLOCK` and before `foo` to be highlighted, but the UI only shows the second to last line before `foo` as highlighted. This would technically be correct, `\n` has 0 width after-all but it might confuse some and did me before I briefly sanity checked both within my own program and by using https://regexr.com/5j2sj which you can see does highlight the line.

I too have invisibles shown on Regex101 so perhaps this should be additional behavior dependent on that option.

```
BLOCK



foo



bar


baz



--------------------------------------
```

<details>
  <summary>Expand me for pictures</summary>
  
![Screenshot 2020-12-23 at 12 34 01](https://user-images.githubusercontent.com/4571498/102959720-32bffe00-44d8-11eb-861a-539744825cbd.png)
![Screenshot 2020-12-23 at 12 34 09](https://user-images.githubusercontent.com/4571498/102959728-35225800-44d8-11eb-9d88-654131538531.png)
</details>

### Reproduction steps

See above.

### Expected Outcome

See first section.

### Browser

Firefox 84.0

### OS

macOS Mojave 10.14.6

**Comment by firasdib** [comment]
Thanks for the report, fixed. Will be pushed live soon.
