### ISSUE TITLE
Quick Reference: Example for "Recurse Entire Pattern" is missing escape characters

### ISSUE THREAD

**Issue by jharrang** [firasdib/Regex101#1446]
## Bug Description
Testing the provided expression: `/((?:[^()]|((?R)))+)/g` against the text `(simple) (and(nested)) but (not here` does not match in the manner that is shown.

### Reproduction steps
View the documentation for Group Constructs->Recurse entire pattern

### Expected Outcome
Provided expression should be: `/\((?:[^()]|((?R)))+\)/g`, which matches as shown.

### Browser
Any

### OS
Any

**Comment by Doqnach** [comment]
Yes, I see indeed that some escapes are missing from the explanation (cc @working-name).

**Comment by working-name** [comment]
Thank you, fixed!
