### ISSUE TITLE
Matches are with black background

### ISSUE THREAD

**Issue by vesal** [firasdib/Regex101#1449]
## Bug Description

Today I noticed that all matching test strings are with black background

### Reproduction steps

https://regex101.com/r/mBll6z/1/

### Expected Outcome

earlier the matching part was light blue or something like that

### Browser
Chrome Version 87.0.4280.88 (Official Build) (64-bit)
Firefox 84.0 
Safari 14.0,2

### OS
Windows 10
Mac OS

**Comment by myounus96** [comment]
Facing same issue..
---------------------------**when matches**-------------------------
![image](https://user-images.githubusercontent.com/13608139/103137117-f236cf00-46e7-11eb-94a0-e248cacfddfe.png)
|
|
|
|
---------------------------**normally**-------------------------
![image](https://user-images.githubusercontent.com/13608139/103137123-02e74500-46e8-11eb-98d6-fcd25dad6301.png)

**Comment by firasdib** [comment]
Thanks for the report. 

This is due to the new automatic theme feature, I will get to it tonight. 

For now a workaround is to set the theme manually in the settings. 

Sorry for the inconvenience!


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by myounus96** [comment]
> Thanks for the report. This is due to the new automatic theme feature, I will get to it tonight. For now a workaround is to set the theme manually in the settings. Sorry for the inconvenience! Vänliga hälsningar / Best regards, Firas Dib
> […](#)
> On 25 Dec 2020, at 15:35, Muhammad Younus ***@***.***> wrote: ﻿ Facing same issue.. ---------------------------when matches------------------------- | | | | ---------------------------normally------------------------- — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for quick response, yes it is working fine with Light theme.

**Comment by vesal** [comment]
Thanks!  By the way, why JavaScript/Python mode is not as colorful than PHP or  Go?
