### ISSUE TITLE
Broken text highlighting

### ISSUE THREAD

**Issue by yooksi** [firasdib/Regex101#1452]
## Bug Description
Matched text highlighting seems completely broken. 
No matter what regular expression I use or what test string I set the highlighting is always the same color: black.

![2020-12-26_073209](https://user-images.githubusercontent.com/16436920/103146608-7f137400-474c-11eb-8449-e34664b8ba25.png)

### Reproduction steps
Try to match any pattern.

### Expected Outcome
Normal colored highlighting.

### Browser
Firefox 84.0.1 (64-bit)
Google Chrome 87.0.4280.88 (64-bit)

### OS
Windows 7 Ultimate SP1

**Comment by firasdib** [comment]
Thanks, issue is now fixed.
