### ISSUE TITLE
Illegible matches

### ISSUE THREAD

**Issue by timsassen** [firasdib/Regex101#1453]
## Bug Description
The matches in the Test String panel are rendered with a dark gray font color with black background, making it illegible.

### Reproduction steps
Go to https://regex101.com/
fill out any regex, for instance: \d*
add a line to the Test String panel, for instance: 123

### Expected Outcome
A combination of background color and font color with higher contrast

### Browser
Include browser name and version
Google Chrome
Version 86.0.4240.111 (Official Build) (64-bit)

### OS
Include OS name and version
Ubuntu 18.04.5 LTS

**Comment by firasdib** [comment]
Thanks, issue is now fixed.
