### ISSUE TITLE
The website seems to be down

### ISSUE THREAD

**Issue by moussa-b** [firasdib/Regex101#1454]
## Bug Description
When we connect to https://regex101.com/ there is a white empty page page. There is a stack in the console, see the screenshot

![image](https://user-images.githubusercontent.com/26151311/103154835-ab55e180-479a-11eb-983d-b66b1a0dac55.png)

### Reproduction steps
Just try to connect to the website

### Expected Outcome
Website to be displayed

### Browser
Firefox 84.0.1

### OS
Mac OS Big Sur Version 11.1

**Comment by working-name** [comment]
Thank you, fixed.
