### ISSUE TITLE
Support `#` as an alternative delimiter

### ISSUE THREAD

**Issue by stdedos** [firasdib/Regex101#1456]
Is it problematic to support `#` as an additional delimiter? e.g.:
```
s#(${HOME}/.installs/libs/perl5/bin|${HOME}/bin|/usr/local/bin|${HOME}/.installs/bin|${HOME}/.local/bin|/usr/local/sbin|/usr/local/bin|/usr/sbin|/usr/bin|/sbin|/bin|/usr/games|/usr/local/games|/snap/bin|/usr/lib/jvm/java-14-oracle/bin|/usr/lib/jvm/java-14-oracle/db/bin|/opt/freerdp-nightly/bin/|${HOME}/.installs/fzf/bin)##g
```

**Comment by working-name** [comment]
Hey @stdedos, sorry to be the bearer of bad news: #1168

**Comment by stdedos** [comment]
> Hey @stdedos, sorry to be the bearer of bad news: #1168

Oops :/ Too bad.
I did try searching though 😕 (probably not good enough)
 
> Follow-up question: are none of the existing delimiters worth it? You can also slap a `?delimiter=~` when visiting regex101.com for the first time. `~` can be any of the currently implemented delimiters.
> 
> ```
> s~(${HOME}/.installs/libs/perl5/bin|${HOME}/bin|/usr/local/bin|${HOME}/.installs/bin|${HOME}/.local/bin|/usr/local/sbin|/usr/local/bin|/usr/sbin|/usr/bin|/sbin|/bin|/usr/games|/usr/local/games|/snap/bin|/usr/lib/jvm/java-14-oracle/bin|/usr/lib/jvm/java-14-oracle/db/bin|/opt/freerdp-nightly/bin/|${HOME}/.installs/fzf/bin)~~g
> ```

I wanted to use the "weirdest" delimiter, except `/`, `|` since technically "any non-null byte can be in the pathname". The weirdest in shell-context (but still not illegal!) is `#`.

e.g. the `s@s@r@g` is parsed normally, so there is no need to `?delimeter=~`

> By the way the `.installs` in your regex will match any character before installs, among which a literal period.

I am writing a shell-script, so that shouldn't be "that much of" a problem. I would've used `\Qs#($(tr ':' '|' <<< "${PATH}"))/##g\E`, but, as you can see, I'll loose `|`.

---

Feel free to handle this as you wish 😄
Thank you for replying

**Comment by working-name** [comment]
> I wanted to use the "weirdest" delimiter, except `/`, `|` since technically "any non-null byte can be in the pathname". The weirdest in shell-context (but still not illegal!) is `#`.

I understand, sounds useful in that case. Although I've seen # used in filenames and it seems both bsd and linux are ok with that. Don't know about windows, did not test. 

I just did a `touch \~test` and it created the filename. So yeah you might bump into crazies either way 🤪.

> e.g. the `s@s@r@g` is parsed normally, so there is no need to `?delimeter=~`

Yes the site is able to parse regex pastes with implemented delimiters and correctly apply flags or enable substitution if it's a `s/this/that/gm`. 

`?delimiter=~` was meant as a quick helper bookmark to avoid getting the default `/` and having to click a delimiter to pick something else.

> I am writing a shell-script, so that shouldn't be "that much of" a problem. I would've used `\Qs#($(tr ':' '|' <<< "${PATH}"))/##g\E`, but, as you can see, I'll loose `|`.

You can also escape the period with a `\` so `\.installs` and that would make the period literal.

> Feel free to handle this as you wish 😄
> Thank you for replying

What I can do is tag @firasdib to see if anything has changed in the meantime. Will leave issue open for now.

**Comment by firasdib** [comment]
Nothing has changed per se, it could be added, but might be confusing in the cases where it collides with the syntax. Its a toin coss for me at this point.

**Comment by stdedos** [comment]
I am fine if you add it as a hidden feature i.e. allow `s#s#r#g` parsing, allow `?delimiter=#`, but otherwise "not show it" (or as a flag somehow, saving to localstorage).

**Comment by Doqnach** [comment]
Obviously the hash in the query param needs to be url encoded, since otherwise it will be treated as the start of fragments. So an even more hidden feature ;-).

**Comment by firasdib** [comment]
The reason I try to avoid is because PHP (and perhaps other implementations) fail horribly whenever the delimiter is unescaped in the regex, even if its part of a valid token, such as `(?#comment)`. I will add this delimiter and we can see how many issues we run into down the road ... :)

Will be live in a bit.

**Comment by stdedos** [comment]
Works like a charm (although I think it took a day or two to become live)!

Thank you 😃
