### ISSUE TITLE
pattern error for correct regex pattern

### ISSUE THREAD

**Issue by chucklu** [firasdib/Regex101#1457]
### Reproduction steps
The following pattern can not be recognized, however it can be recognized by https://regexr.com/
^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[^]{8,25}$

### Expected Outcome
The pattern should be correct, bu the site give error info.  

> [^ Character class missing closing bracket

**Comment by chucklu** [comment]
find another pattern  `[^][…]` can not be recognized, the pattern was mentioned here
https://stackoverflow.com/questions/6332288/what-does-a-character-class-with-only-a-lone-caret-do

**Comment by chucklu** [comment]
someone told me, it depends on engine  https://www.regular-expressions.info/charclass.html

> You can include an unescaped closing bracket by placing it right after the opening bracket, or right after the negating caret. []x] matches a closing bracket or an x. [^]x] matches any character that is not a closing bracket or an x. This does not work in JavaScript, which treats [] as an empty character class that always fails to match, and [^] as a negated empty character class that matches any single character. Ruby treats empty character classes as an error. So both JavaScript and Ruby require closing brackets to be escaped with a backslash to include them as literals in a character class.

**Comment by chucklu** [comment]
https://github.com/firasdib/Regex101/wiki/FAQ#how-close-does-regex101-emulate-the-engines

**Comment by firasdib** [comment]
Seems to be working as intended in the different flavors. Could you please show me screen shots of where its failing?

**Comment by chucklu** [comment]
error for `^(?=.[a-z])(?=.[A-Z])(?=.*\d)[^]{8,25}$`
![image](https://user-images.githubusercontent.com/3004057/103324111-003a7600-4a81-11eb-9463-6fdbe3e23443.png)

error for `[^][…]`
![image](https://user-images.githubusercontent.com/3004057/103324135-0e889200-4a81-11eb-88bb-a9c2f75d1395.png)

**Comment by working-name** [comment]
Which flavor is in the top screenshot? What about the bottom one? Check behavior against real code below:

### checked items match regex101.com's behavior for `[^]`.

- [x] 🚫 Python: [error](https://ideone.com/cBfWq7)
- [x] 🚫 PHP: [error](https://ideone.com/mVimW0)
- [x] 👍 JS: [ok](https://ideone.com/w6xZfP)

### ... and for `[^]x]`:
- [x] 👍 Python: [ok](https://ideone.com/klEIg8)
- [x] 👍 PHP: [ok](https://ideone.com/GaQe6A)
- [x] 🚫 JS: [error](https://ideone.com/gNI632)

**Comment by chucklu** [comment]
Thanks, I just notice there is a flavor choice on site.
