### ISSUE TITLE
Bugs from pressing TAB in the Regex Debugger

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1459]
## Bug Description

Pressing **Tab** or **Shift**+**Tab** in the Regex Debugger cycles through fields, and changes keyboard focus... which is fine, except that some of the fields it can give focus to are invisible and should not be accessible while in the debugger, and restoring focus using the mouse is not completely straightforward.

Related: https://github.com/firasdib/Regex101/issues/676

### Reproduction steps

After pressing **Tab** once, the `←` and `→` keys no longer step backwards and forwards... but every other hotkey still works (including Ctrl+`←` and Ctrl+`→`). Pressing Shift+`Tab` makes them work again. Intuitively I would have thought clicking the Debugger's navigation bar or the current-position circle on the bar would've given focus back to making every hotkey work, but it doesn't. The only mouse way to give focus back in this situation is to either click on the current step number edit box, or an entry in the **MATCH** list. (Except last night, I got into a state where even clicking an entry in the **MATCH** list did not restore focus, and at the time I didn't know it was caused by **Tab** presses. I can't reproduce this yet.) In some states (depending on number of **Tab** or **Shift**+**Tab** presses) even exiting the debugger and re-entering it does not restore proper keyboard focus for the `←` and `→` hotkeys.

The first 16 **Shift**+**Tab** presses cycle through a bunch of URLs, shown in the status bar. Pressing Enter while on one of these will jump to it. Although some of them result in further weirdness; for example, only pressing **Shift**+**Tab** once takes you to "https://regex101.com/debugger/codegen?language=php", and pressing Enter at that point does *not* take you to the code generator, it takes you back to the main regex mode. But then clicking on "Regex Debugger" at that point doesn't take you back into the debugger, it just appends "/debugger" to the current URL each time, resulting in "https://regex101.com/debugger/codegen/debugger/debugger/debugger/debugger/debugger/debugger" after 6 clicks, for example.

Pressing **Shift**+**Tab** 17 times gives focus to the **TEST STRING** box. At which point you can then invisibly type into that box while still in the Regex Debugger, and when you exit the debugger, you'll then see the text you entered. Pressing **Shift**+**Tab** an additional two times (for a total of 19) will, similarly, give focus to the **REGULAR EXPRESSION** text box.

Pressing **Shift**+**Tab** 18 times pops up a **REGEX FLAGS** box.

While the regex, test string, and flags can actually be changed using the above method, they don't have any effect on the debugger's state; to debug the result of the change, you need to exit the debugger and re-enter it.

### Expected Outcome

Cycling through fields with **Tab** and **Shift**+**Tab** is normal behavior in a browser, but it should never give focus to things that are invisible in the current mode.

In the Regex Debugger, clicking the "current step" navigation bar (or the circle on that bar, that represents the current position / step) should restore full keyboard focus to the debugger's hotkeys, to make it easy to get normal focus back if it's been messed with by **Tab** or **Shift**+**Tab** or anything else.

### Browser
Firefox 84.0.1 (64-bit)

### OS
Windows 7 (64-bit)

**Comment by firasdib** [comment]
I think this ties back to https://github.com/firasdib/Regex101/issues/676#issuecomment-753619746 and in general the lack of accessability on the website.

What you have described is clearly undesired behavior, and I shall try to remedy it with a surgical fix, but this will have to be solved in a better manner at some point.

**Comment by firasdib** [comment]
I've implemented a surgical fix to remedy the most critical issue as of right now. I suggest we continue the work and talk in #676
