### ISSUE TITLE
Extract Function

### ISSUE THREAD

**Issue by SethFalco** [firasdib/Regex101#1460]
## Feature
Would it be viable to make a new function on the sidebar that matches the input and returns a list of all full matches? 
It would be even better if a custom delimiter could be provided for the output.

#### Input
```
https://500px.com/p/{username}
https://7cups.com/@{username}
https://9gag.com/u/{username}
```

Regex: `(?<=https?:\/\/(\{.*\}\.)?)[A-Za-z\d.-]+`

#### Output
```
500px.com
7cups.com
9gag.com
```

Or with a custom delimeter of `,`.

```
500px.com,7cups.com,9gag.com
```

**Comment by Doqnach** [comment]
There is already an export function on the right in the "match information" panel. That should work for you.

Related to #1410

**Comment by SethFalco** [comment]
Ahh I see, didn't notice that! Thanks for the heads up.
I'll be closing this and following #1410 meanwhile.
