### ISSUE TITLE
step through "Unit Test" doesn't work

### ISSUE THREAD

**Issue by daholga** [firasdib/Regex101#1463]
## Bug Description
1) If you add more than one test in "unit tests" and run them, only the first is executed, the rest stays grey.
2) the first expression seems to stay green, even if the result ist false.
Tested with multiline and singleline, with and without ^$ delimiter.  
Flavors: PCRE, ECMA.
https://regex101.com/r/1pqvKG/6
Target: regex
criteria "does match"

### Reproduction steps
![image](https://user-images.githubusercontent.com/18163422/103999335-0c1eea00-519d-11eb-963e-33a56afe9bbc.png)
![image](https://user-images.githubusercontent.com/18163422/103999476-383a6b00-519d-11eb-9fdf-801a5dc4e848.png)

### Expected Outcome
Line 1 : red (False)
Line 2 : green (True)

### Browser
Chrome 87.0.4280.141

### OS
Windows 10

**Comment by firasdib** [comment]
Thanks, looks like a regression. Fixed locally, will be pushed in a few days!

**Comment by daholga** [comment]
By the way: Thanks for this very (!) useful tool !

**Comment by jaydenseric** [comment]
Still seeing this, it's a real showstopper. When will the fix be deployed to prod?

**Comment by Ouims** [comment]
@jaydenseric few days/week now
