### ISSUE TITLE
Python flavor is missing support for flag extension notation new in Python 3.6

### ISSUE THREAD

**Issue by sebastianw** [firasdib/Regex101#1464]
## Bug Description
The Python flavor is missing support for turning off re flags via extension notations. This is new in Python 3.6 so maybe it is not supported on purpose?

### Reproduction steps
Use this regex: `\b(?-i:[BCDFGHJKLMNPQRSTVWXYZbcdfghjklmnpqrstvwxyz0-9]+|[A-F0-9]+)\b`
Error displayed:

```
(? Incomplete group structure
) Incomplete group structure
```

### Expected Outcome
Regex is accepted.

### Browser
Firefox 84.0.2

### OS
MacOS 10.15.7  (Catalina)

**Comment by Doqnach** [comment]
The current Python flavour as supported by the website is emulating Python 2.7 and not 3+, so that is probably it.

Discussion on supporting Python 3.6/3.7 is ongoing. See the other (many) Python issues around.

Related to #1219, #1271, #1403, #1404, #1405.

**Comment by working-name** [comment]
Closing in favor of the other linked issues.
