### ISSUE TITLE
Permalink support

### ISSUE THREAD

**Issue by fabiospampinato** [firasdib/Regex101#1465]
## Feature

It'd be useful if the site was able to load a regex from a URL query parameter.

I'm adding a search query explainer to an app of mine, and for explaining how the regexes used in the query work I'd like to provide to the user links to regex101 for those regexes.

**Comment by working-name** [comment]
There is no official support for URL queries, but `regex=` exists; use at your own risk 😃

The official way to interact with regex101.com is through its API documented here: https://github.com/firasdib/Regex101/wiki/API

Related: #872

**Comment by fabiospampinato** [comment]
That's nice, thanks!

Hopefully it'll never break or it will be replaced with something more permanent, IMHO that's more useful than all the APIs available so it probably deserves some love
.
