### ISSUE TITLE
\b in substitution field get a tooltip about word boundary

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1469]
## Bug Description
\b in substitution field get a tooltip about word boundary

### Reproduction steps

https://regex101.com/r/oVHCXp/1

### Expected Outcome

tooltip should mention the ascii 8 char being used since that's the case.

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by firasdib** [comment]
Fixed in the new upcoming update.
