### ISSUE TITLE
Test run only shows on first test case

### ISSUE THREAD

**Issue by Bikonja** [firasdib/Regex101#1472]
When you have multiple unit tests and you press Run Tests, the first test blinks a few times (changes colours and displays progress) and ends up with the overall results of the run. The other tests appear as if they haven't been run, see below example (after clicking the Run Tests button at the bottom and waiting a second for the tests to run):
![image](https://user-images.githubusercontent.com/7753243/104892916-aab00580-596a-11eb-837e-5788bc1a0797.png)

**Comment by firasdib** [comment]
Yes, this is a known bug, will be fixed in the upcoming update. Hoping to have it ready in a week or two.
