### ISSUE TITLE
Unable to scroll Match Information

### ISSUE THREAD

**Issue by vBread** [firasdib/Regex101#1475]
## Bug Description
The Match Information panel, when overflowed, is unable to be scrolled to see all of the matches.

![Screen Shot 2021-01-23 at 2 15 32 PM](https://user-images.githubusercontent.com/60681223/105611796-7b8ffe80-5d85-11eb-9b68-48d6874a4e04.png)

Collapsing the other two panels will allow for more matches to show but doesn't fix the scrolling.

![Screen Shot 2021-01-23 at 2 17 22 PM](https://user-images.githubusercontent.com/60681223/105611841-c9a50200-5d85-11eb-9b8e-0c446d897ee3.png)

### Reproduction steps
Create a simple pattern and repeat the sample text to overflow the panel

### Expected Outcome
The panel is scrollable

### Browser
Google Chrome v88.0.4324.96

### OS
macOS Catalina v10.15.7

**Comment by firasdib** [comment]
Yes, I've noticed this just now too. Looks like webpack is bundling my css in a different order than before, which is very odd. I will have to investigate.

**Comment by firasdib** [comment]
I've resolved this by temporarily disabling tree shaking in webpack, related issue seems to be https://github.com/webpack/webpack/issues/7094

Please poke me if you find more discrepancies like these!
