### ISSUE TITLE
PCRE2 Syntax for "napla" and "naplb" not supported

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1476]
## Bug Description

From PCRE2 doc:

These assertions are specific to PCRE2 and are not Perl-compatible.

  (?*...) (*napla:...) (*non_atomic_positive_lookahead:...)               < each token are all the same meaning

  (?<*...)  (*naplb:...) (*non_atomic_positive_lookbehind:...)           < each token are all the same meaning

The website does not seem to support any of it

### Reproduction steps

https://regex101.com/r/TdkuB7/1

### Expected Outcome

No error

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by Davidebyzero** [comment]
I was just about to report this and then I saw you'd already done so. :-)

But I'd like to add that the textual forms of lookaround assertions already supported by regex101 also don't work in regex101:

`(*positive_lookahead:...)` and `(*pla:...)` should work the same as `(?=...)`
`(*negative_lookahead:...)` and `(*nla:...)` should work the same as `(?!...)`
`(*positive_lookbehind:...)` and `(*plb:...)` should work the same as `(?<=...)`
`(*negative_lookbehind:...)` and `(*nlb:...)` should work the same as `(?<!...)`

**Comment by firasdib** [comment]
I'll add these soon. Are there any docs I can use to aid in writing explanations for these tokens?

@working-name We should probably update the quickref with all these new tokens too... the subst area has some new ones.

**Comment by Ouims** [comment]
Here is an example and description of them

The traditional Perl-compatible lookaround assertions are atomic. **That is, if an assertion is true, but there is a subsequent matching failure, there is no backtracking into the assertion.** However, there are some cases where non-atomic positive assertions can be useful.
Consider the problem of finding the right-most word in a string that also appears earlier in the string, that is, it must appear at least twice in total.
This pattern returns the required result as captured substring 1: /^(?x)(*napla: .* \b(\w++)) (?> .*? \b\1\b ){2}/
For a subject such as "word1 word2 word3 word2 word3 word4" the result is "word3". 
How does it work? Inside the assertion, the greedy .* at first consumes the entire string, but then has to backtrack until the rest of the assertion can match a word, which is captured by group 1. In other words, when the assertion first succeeds, it captures the right-most word in the string.
The current matching point is then reset to the start of the subject, and the rest of the pattern match checks for two occurrences of the captured word, using an ungreedy .*? to scan from the left. If this succeeds, we are done, but if the last word in the string does not occur twice, this part of the pattern fails. If a traditional atomic lookhead had been used, the assertion could not be re-entered, and the whole match would fail. The pattern would succeed only if the very last word in the subject was found twice.
Using a non-atomic lookahead, however, means that when the last word does not occur twice in the string, the lookahead can backtrack and find the second-last word, and so on, until either the match succeeds, or all words have been tested.

Two conditions must be met for a non-atomic assertion to be useful: the contents of one or more capturing groups must change after a backtrack into the assertion, and there must be a backreference to a changed group later in the pattern. If this is not the case, the rest of the pattern match fails exactly as before because nothing has changed, so using a non-atomic assertion just wastes resources.

**Comment by firasdib** [comment]
I've been testing this, and they do not seem to act synonymously, @Davidebyzero. For example, `/(?<!a)b/` matches `acb` while `/(?*nlb:a)b/` does not. Quantifiers also seem to behave differently on these tokens.

**Comment by firasdib** [comment]
Added, will be live soon.

**Comment by Ouims** [comment]
It seems only (?*) and (?<*) has been added.
 (*non_atomic_positive_lookahead:...) same as (*napla:...) and  (*non_atomic_positive_lookbehind:...) same as (*naplb) are not supported,

**Comment by firasdib** [comment]
I missed that. If you, in the future, can please use the formatting it will be easier for me to see what is code and what isn't. I looked at Davids comment, as it was much nicer structured, and implemented that.
