### ISSUE TITLE
Task 22 is broken

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1477]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 22: Tokenized List

### Bug Description
Upon clicking on this task, the quiz page disappears and is replaced with an otherwise blank page with the following message:

**A critical error has occurred**
If possible, open up an issue with as many details as you can here: https://github.com/firasdib/Regex101/issues.
It might be a good idea to take a screen shot of your dev console window, if you know how to open it.

In the console window, I see the following errors:

`Error: Unknown group structure '(?:'`
`Error: Unknown group structure '(?:'`
`Fetch for dependency 'statisticsFetch' aborted because the parent has unmounted`
`Loading failed for the <script> with source “https://sentry.io/api/embed/error-page/?dsn=https://`hash`@sentry.io/102476&eventId=`hash`”.`
`Loading failed for the <script> with source “https://sentry.io/api/embed/error-page/?dsn=https://`hash`@sentry.io/102476&eventId=`hash`”.`

(I removed the hashes because they may contain private info. I also did not include the stack traces for the errors, but can include them if necessary.)

In Firefox, just the above happens. In Chrome, the above happens, as well as an error report box showing up on top of that page, and without the "Loading failed for the <script>" errors in the console.

I believe this new bug may have been introduced upon the introduction of the sentry fetching, which is fairly new (though I did not check if it was already there right after the PCRE2 upgrade).

### Reproduction steps
Click on Task 22 (assuming you've gotten that far in the quiz).

### Expected Outcome
Task 22 was working correctly right after the PCRE2 upgrade, and should still be working.

### Browser
Firefox 84.0.2 (64-bit)
Chrome 88.0.4324.104 (64-bit)

### OS
Windows 7 (64-bit)

**Comment by firasdib** [comment]
Fixed
