### ISSUE TITLE
Long time regex101 user. Light mode sorely missed

### ISSUE THREAD

**Issue by maxwellmckinnon** [firasdib/Regex101#1479]
Please add an option for light mode. The new dark mode is unreadable, and I'm looking for a new solution now that my eyes can read.

I get how a lot of coders find the dark mode easier to read. This is a well known thing. For whatever reason dark mode makes me dyslexic and I can't read anything in dark mode. Please offer the original light mode as an option in settings. Thank you!!

**Comment by maxwellmckinnon** [comment]
Hah go figure, it was in settings after all. Just shows how bad my reading is in dark mode. The setting to enable light mode was almost impossible to see. Nevermind me.

**Comment by working-name** [comment]
Funny part is contrast was recently increased 😂👍 glad you found it!
