### ISSUE TITLE
Supposed Hackers

### ISSUE THREAD

**Issue by Just-A-Student-Net** [firasdib/Regex101#1480]
I'm an A student, our school is public which in turn means the government decides what we do and controls our network. However, one day while going through my email and I got a supposed hacked email. One from Russia (as they say), but while going through the email I noticed the address of the email, 
![image](https://user-images.githubusercontent.com/78035275/105867868-2a695000-5fbb-11eb-8c9b-887a6135e384.png) that's what they sent. It was under the Regex101 email also the financeirolab.com.br I have no idea that either of these, I just want people to go through education without fear. So the internet race is on. I would like help to solve this case and avoid this from happening. I do obviously know it is fake, but fakers are not free from punishment. I would also like help from moderators to stop this from happening on the Regex platform, same time through a man can only hope. I shall continue searching for the aliases behind this and searching for the original poster/person behind this. I have no idea what my ID going for 1135 is. But have a strange feeling behind it. Please contact me if you found out anything or have more information on this issue.

Thank you, from Just-A-Student-Net

**Comment by Just-A-Student-Net** [comment]
Just learned that financeirolab.com.br is a website for collecting and distributing currency.

**Comment by working-name** [comment]
Email headers can be forged very easily, but as you've noticed your google account marked it as spam - something didn't add up. There isn't a dedicated taskforce (as far as I know) for catching people who forge email headers but you may have better luck by looking at the full headers to get the origin IP. After that you can look up the abuse email for the company who operates that IP and forward the full email headers.

The sad reality is that as quickly as you can get their accounts closed they will have opened another.

**In conclusion: if the origin IP is not the same as the IP behind regex101.com then you're wasting your time as there isn't anything one can do about another IP/server.**

If any of the threats in that email worry you personally, start using a password manager like Bitwarden, change your important passwords every 3 mo or less, don't use the same password everywhere, don't open files that are sent to you unless you know and trust the sender, don't click on weird ads on the internet requiring you to install some software to read/watch/download something, and so on. Common sense.

Good luck!

**Comment by Just-A-Student-Net** [comment]
> Email headers can be forged very easily, but as you've noticed your google account marked it as spam - something didn't add up. There isn't a dedicated taskforce (as far as I know) for catching people who forge email headers but you may have better luck by looking at the full headers to get the origin IP. After that you can look up the abuse email for the company who operates that IP and forward the full email headers.
> 
> The sad reality is that as quickly as you can get their accounts closed they will have opened another.
> 
> **In conclusion: if the origin IP is not the same as the IP behind regex101.com then you're wasting your time as there isn't anything one can do about another IP/server.**
> 
> If any of the threats in that email worry you personally, start using a password manager like Bitwarden, change your important passwords every 3 mo or less, don't use the same password everywhere, don't open files that are sent to you unless you know and trust the sender, don't click on weird ads on the internet requiring you to install some software to read/watch/download something, and so on. Common sense.
> 
> Good luck!

Thank you for your feedback on this issue, and I also understand that the password should be changed and do not open any files or reply to any suspicious emails, (which is fake which this is). Also yes, I know it's common sense and I have never done that it is to avoid this happening. Even if in the long run it does not do much, but giving it spot light can help put in more security and internal preventions to avoid this happening.

**Comment by firasdib** [comment]
Unfortunately, there isn't much I can do. I have a SPF record (which might have helped google determine this was illegitimate), but in the end, its inevitable. 

Thanks for your concern though!

**Comment by Just-A-Student-Net** [comment]
> These people spoof (fake) the sender. regex101.com is in no way any part of this. At most, the problem is on the end of "financeirolab.com.br" and they are (ab)using the good name of regex101.
> 
> Only thing that might help a little bit is having an SPF record, but that still won't prevent this from happening.
> 
> The entire contents of the above email is fake, and no hack has actually been done. It is only a scare tactic to make you pay.

Yes, I am aware of all of that and in my first comment I did send out that I said "I obviously know it is fake." But thank you for your comment.

**Comment by Just-A-Student-Net** [comment]
> Unfortunately, there isn't much I can do. I have a SPF record (which might have helped google determine this was illegitimate), but in the end, its inevitable.
> 
> Thanks for your concern though!

Of course, I do know it's inevitable, but of course, it will always be an option to report such issues. Thank you for the response.
