### ISSUE TITLE
translations not working

### ISSUE THREAD

**Issue by zetalpha** [firasdib/Regex101#1481]
## Bug Description

include placeholders Words translations not working
### Browser
Include browser name and version
Vivaldi
### OS
Include OS name and version
Windows 10

![20210128010612](https://user-images.githubusercontent.com/11816197/106026664-10d41f80-6105-11eb-97ce-d51c82e14060.png)

**Comment by firasdib** [comment]
In what way are they not working?

**Comment by zetalpha** [comment]
> In what way are they not working?

Thank you for your reply
switch Language
include placeholders Words 
all Language not working

![20210128214706](https://user-images.githubusercontent.com/11816197/106147187-8813bd00-61b2-11eb-8b21-f31f79010af4.jpg)
![20210128214625](https://user-images.githubusercontent.com/11816197/106147226-9530ac00-61b2-11eb-8176-35c0732011a5.jpg)

**Comment by firasdib** [comment]
I don't think I follow. Can you elaborate a bit further? Maybe write in your native language if necessary, and someone else can help translate.

**Comment by zetalpha** [comment]
> I don't think I follow. Can you elaborate a bit further? Maybe write in your native language if necessary, and someone else can help translate.

![20210209145801](https://user-images.githubusercontent.com/11816197/107328053-12301f80-6ae9-11eb-8fbd-b672d643cc84.jpg)

**Comment by firasdib** [comment]
Do you mean the translations are incorrect? We are working on getting the translation website up

**Comment by zetalpha** [comment]
> Do you mean the translations are incorrect? We are working on getting the translation website up

内容一致但是没有翻译

**Comment by working-name** [comment]
If bing translate served me right, yes, you are correct, the translation is not 100% complete. If you are able to help at all with that please head over to [r101.cf](https://r101.cf). 

Chinese (simplified)
<a href="https://r101.cf/engage/site/zh_Hans/"><img src="https://r101.cf/widgets/site/zh_Hans/regex101-com-2/svg-badge.svg" alt="Translation status" /></a>

**Comment by firasdib** [comment]
Yep, this will have to be managed through r101.cf 

If you can we would much appreciate your help @zetalpha
