### ISSUE TITLE
Unable to enter title on initial saved

### ISSUE THREAD

**Issue by vBread** [firasdib/Regex101#1482]
## Bug Description
When saving an expression for the first time, attempting to enter a title will instantly highlight the share link. However, editing a saved regex afterward works.

**EDIT**: The same thing occurs when trying to enter tags.

https://user-images.githubusercontent.com/60681223/106072375-0ea69c80-60d6-11eb-88f7-befc18638f1a.mp4

### Reproduction steps
Create an expression, save it, and try to enter a title.

### Expected Outcome
A title is able to be entered.

### Browser
Google Chrome v88.0.4324.96

### OS
macOS Catalina v10.15.7

**Comment by firasdib** [comment]
Thank you, this was an oversight by me. Fixed a bunch of related bugs to the account input boxes as well.

Will be live soon!
