### ISSUE TITLE
Clickable 'explanation' text when error and collapsed explanation panel

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1483]
## Feature

When you have the 'explanation' panel collapsed but the match info panel visible and you have error in the expression, giving you the text:
"Your pattern contains one or more errors, please see the explanation section above."

It would be handy to have the portion "explanation section" or similar clickable, which would expand the explanation panel.

Otherwise you're kind of missing the error, but you may want to know the error without expanding the explanation panel, I suppose another idea would be to display the error below that quote above, that's the only reason i would want to see the explanation panel if i had it collapsed to begin with.

**Comment by firasdib** [comment]
Its a bit too cumbersome to add right now and doesn't add too much value imo.
