### ISSUE TITLE
Multi-codepoint unicode parsing in character classes when switching from JS to Go and back

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1485]
## Bug Description
The parser seems to be changing behaviour when switching from JS to Go and back. I noticed this specifically in parsing of a unicode range in a character class.

### Reproduction steps
- Open this link: https://regex101.com/r/5zsZ4J/1
- Switch to PCRE1/PCRE2/Python: parsing error (expected)
- Switch back to JS: no issues
- Switch to Golang: parsing error (expected)
- Switch back to JS: parsing error (unexpected)

### Expected Outcome
The parser should behave consistent, regardless of what other languages you have tried your regex in.

### Browser
Tried in latest Firefox and Chromium

### OS
Arch Linux

**Comment by firasdib** [comment]
This is because you have enabled the `u` flag in JS, but golang has no substitute for that, so it is removed. When you then switch back to JS, that flag is no longer present, and you get the error you are seeing. If you add the `u` flag again, it will work as expected.
