### ISSUE TITLE
[QUESTION] Is translation be maintained now?

### ISSUE THREAD

**Issue by TheInterestingSoul** [firasdib/Regex101#1488]
## Question

The server of https://r101.cf seems down, can i send PRs to the [firasdib/regex101-translations](https://github.com/firasdib/regex101-translations) repo directly?

**Comment by TheInterestingSoul** [comment]
In addition, [firasdib/regex101-translations](https://github.com/firasdib/regex101-translations) contains two file: `zh.json` and `zh_Hans.json`, which one will take effect on the website? confusing😕

**Comment by working-name** [comment]
Hello there,

I was trying to port over the database from the previous weblate instance but the requirements are a bit insane in terms of upgrading from one version to the next - each minor one comes with manual steps and config editing, and I have A LOT of minor versions to go through. 

I arrived at the conclusion that it's not worth saving the prior install, I'll just set up a blank weblate altogether. This weekend is when I'll get some time to devote to that.

As far as `zh` and `_Hans` - beats me; are they the same? Does that mean 2 different dialects? I don't speak it, nor read it so you'll have to be the judge of that; let me know? 😁 

Pull requests work too, just keep in mind that the english side cannot change.

**Comment by TheInterestingSoul** [comment]
> Hello there,
> 
> I was trying to port over the database from the previous weblate instance but the requirements are a bit insane in terms of upgrading from one version to the next - each minor one comes with manual steps and config editing, and I have A LOT of minor versions to go through.
> 
> I arrived at the conclusion that it's not worth saving the prior install, I'll just set up a blank weblate altogether. This weekend is when I'll get some time to devote to that.
> 
> As far as `zh` and `_Hans` - beats me; are they the same? Does that mean 2 different dialects? I don't speak it, nor read it so you'll have to be the judge of that; let me know? 😁
> 
> Pull requests work too, just keep in mind that the english side cannot change.

Thx for replying

**Comment by TheInterestingSoul** [comment]
“zh” means Chinese, and “zh_Hans” means Chinese Simplified.

In a word, after checking, I found that only "zh.json" will take effect in the language switcher. Luckily, the strings of the two files complement each other, so you may merge the two files manually. 😃

发件人: Alan<mailto:notifications@github.com>
发送时间: 2021年2月5日 14:03
收件人: firasdib/Regex101<mailto:Regex101@noreply.github.com>
抄送: TheInterestingSoul<mailto:wangpy01@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [firasdib/Regex101] [QUESTION] Is translation be maintained now? (#1488)


Hello there,

I was trying to port over the database from the previous weblate instance but the requirements are a bit insane in terms of upgrading from one version to the next - each minor one comes with manual steps and config editing, and I have A LOT of minor versions to go through.

I arrived at the conclusion that it's not worth saving the prior install, I'll just set up a blank weblate altogether. This weekend is when I'll get some time to devote to that.

As far as zh and _Hans - beats me; are they the same? Does that mean 2 different dialects? I don't speak it, nor read it so you'll have to be the judge of that; let me know? 😁

Pull requests work too, just keep in mind that the english side cannot change.
