### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by arnowi** [firasdib/Regex101#1489]
## Bug Description
There is a bad formatted link in the quick reference causing the opening of regex101 in a new tab or window instead of following the link. Hovering over it reveals it links to https://regex101.com/https://www.cs.tut.fi/~jkorpela/chars/c0.html instead of https://www.cs.tut.fi/~jkorpela/chars/c0.html

### Reproduction steps
Go to *QUICK REFERENCE* > *Meta Sequences* > *Control Character Y \cY*
Click the link in the description, a new window or tab opens regex101.

**Comment by firasdib** [comment]
Thanks! Fixed, will be pushed live in soon.
