### ISSUE TITLE
Empty capture displayed for Golang

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1490]
## Bug Description

I'm not expert in golang, in this url https://regex101.com/r/yhWa7k/1 the alternative for double quotes matches at least twice.

The last match shows a second empty capture, but the others matches which also have an empty second capture group don't display them with the pinkish dot-lined bar

### Reproduction steps

None

### Expected Outcome

Again, I don't know what's the correct behavior, but it looks wrong that only some of the matches are showing it, is it a bug?

### Browser
chrome 88.0.4324.104
### OS
win7 4ever baby

**Comment by firasdib** [comment]
Look at the indices, they all match at the end of the string. Looks like it works as expected.

**Comment by Ouims** [comment]
uh, golang is weird but ok :)
