### ISSUE TITLE
ECMAScript FLAVOR seems doesn't support set distinct color for different group.

### ISSUE THREAD

**Issue by cesaryuan** [firasdib/Regex101#1491]
## Bug Description
ECMAScript FLAVOR seems doesn't support set distinct color for different group.
Look the pix below.
![image](https://user-images.githubusercontent.com/35998162/107108582-0982e380-6874-11eb-8b47-baf532857a15.png)

### Reproduction steps
Doing like the pic above.

### Expected Outcome
Set distinct color for different group with ECMAScript FLAVOR.

### Browser
Cent Browser.
Version: Chromium 86.0.4240.198

### OS
Microsoft Windows
2004 (OS 19041.746)

**Comment by working-name** [comment]
Please see #533 

Sorry!
