### ISSUE TITLE
Quick Reference: Non capturing group listed twice

### ISSUE THREAD

**Issue by tomasz13nocon** [firasdib/Regex101#1493]
![image](https://user-images.githubusercontent.com/11395615/107214711-98c1ff80-6a0a-11eb-8126-35d5fb9023b8.png)

I'm not sure if this is intended, but `(?:...)` is listed twice with different names in the quick reference of all regex flavors.

**Comment by firasdib** [comment]
Thanks, I've removed the second entry.
