### ISSUE TITLE
Smol typo in explanation text for ECMA/js only 

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#1494]
## Bug Description
```js
\s matches any whitespace character (equal to [^\r\n\t\f\v \u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff])

\S matches any non-whitespace character (equal to [^^\r\n\t\f\v \u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000\ufeff])
```
- a `^` snuck in there making it a negated class, and then 2x `^` exist for `\S`

### Reproduction steps
1. Open regex101.com, select ECMA/js flavor
2. Type `\s` or `\S` in the regex input field and read explanation

### Expected Outcome
Explanation should not include `^` for `\s` but include a single `^` for `\S`

**Comment by firasdib** [comment]
Thanks, fixed. Will be live tomorrow most likely.
