### ISSUE TITLE
full match highlighting regression

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#1495]
## Regression Description
Full match highlighting within `TEST STRING` is not happening when capture groups are represented.

### Reproduction steps
1. Load https://regex101.com/r/U34b6l/2
2. switch flavors - ECMA/js is not affected (probably because there's no positional info)

### Expected Outcome
Highlight the full match in the `TEST STRING`

### Browser
Safari, Chrome, Firefox

### OS
macOS 10.14.4

**Comment by firasdib** [comment]
Oversight by me... I'll try to fix this asap.
