### ISSUE TITLE
Cannot load bundle.css because wrong MIME type

### ISSUE THREAD

**Issue by Sea-n** [firasdib/Regex101#1497]
## Bug Description
> The stylesheet https://regex101.com/static/bundle.68446fd570202445d9d6.css was not loaded because its MIME type, “text/html”, is not “text/css”.

### Reproduction steps
Open https://regex101.com/

### Expected Outcome
Just like normal

### Browser
Firefox 86.0

### OS
macOS 11.1

**Comment by firasdib** [comment]
Thats odd, seems your browser is trying to fetch an old bundle file. Maybe the service worker got confused -- can you try a hard refresh and see if that solves it?

**Comment by Sea-n** [comment]
@firasdib It's fixed now. I just re-open the page without a hard refresh.

At the moment I reported this bug, hard refresh doesn't help.

**Comment by firasdib** [comment]
Thanks for bringing it up @Sea-n -- I hope it was a one time thing :)
