### ISSUE TITLE
The /A flag is incorrectly documented in the Explanation

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1498]
## Bug Description
The /A flag is incorrectly documented in the Explanation pane as "**A**nchored. Pattern is forced to `^`" (which was the same mistake as was made in the quickref before being fixed in issue #1109).

See also #1499.

### Reproduction steps
In PCRE or PCRE2 mode, enable the /A flag, and enter any non-empty regex pattern.

### Expected Outcome
The Explanation of this flag should be similar or identical to its quickref documentation.

### Browser
N/A

### OS
N/A

**Comment by firasdib** [comment]
Adjusted, thanks
