### ISSUE TITLE
Translate PCRE /A flag to ECMAScript /y flag and back when switching modes

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1499]
## Feature
The /**A** "anchored" flag in PCRE/PCRE2 mode does the exact same thing as the /**y** "sticky" flag in ECMAScript mode. Thus, I would propose that regex101 translate /A to /y when switching from PCRE/PCRE2 to ECMAScript, and translate /y to /A when switching from ECMAScript to PCRE/PCRE2.

Also, the Quick Reference and Explanation documentation should be the same for these two flags (except that the PCRE/PCRE2 version of the quickref documentation can mention `\G`). See also #1498.

**Comment by firasdib** [comment]
Thanks for the suggestion! Will release it tonight.
