### ISSUE TITLE
Add a function to change the end of line flavour (LF / CR+LF / ...) on the input test string

### ISSUE THREAD

**Issue by Matioupi** [firasdib/Regex101#1500]
## Feature
Having a button to easily switch/convert the end of line flavour on the test string would be nice to further test robustness of some regex patterns.

I just faced an issue with a multi-line regex in python where the data has CR+LF end of lines.
When copy pasting the sample in test windows, end of lines where converted to LF only and the regex was working.
When dealing with data from Python with a binary data read, the CR+LF where conserved and regex was not working.

**Comment by firasdib** [comment]
Dup of https://github.com/firasdib/Regex101/issues/442

TLDR: Codemirror limitation
