### ISSUE TITLE
Following a saved Unit Tests link doesn't go directly to Unit Tests mode

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1502]
## Bug Description
When you save a regex that has Unit Tests, with the focus being only on the unit tests (and not Match or Substitution), the Test String field will be empty, and the user will have saved the regex while in Unit Tests mode.

But even after doing this, following the resulting regex101 link will open the regex in Match mode, and the person who followed the link will need to click "Unit Tests" to see the actual unit tests (not to mention, they will then need to click "Run Tests").

### Reproduction steps
1. Start from a fresh https://regex101.com/ page
2. Enter a regex
3. Click on "Unit Tests" in the Function menu.
4. Create some unit tests by clicking "Add Test" and saving the tests.
5. Click "Save Regex" and copy the resulting link
6. Follow the link

### Expected Outcome
Regex101 should go directly to Unit Tests mode when the link is followed. (Since already-saved links probably don't store any metadata indicating they were saved in Unit Tests mode, the criteria for doing this can just be: Test String is empty, Substitution mode was not engaged, and there is at least one Unit Test. But for future saved links, adding this to the metadata might be considered.)

It should probably also automatically Run Tests upon loading of the link.

### Browser
Firefox 85.0 (64-bit)
Chrome 88.0.4324.150 (64-bit)

### OS
Windows 7 (64-bit)

**Comment by firasdib** [comment]
This sounds like a good enhancement. I'll look into it.

**Comment by Ouims** [comment]
This has been reported already #1090
