### ISSUE TITLE
Show mouseover information for relative conditionals

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1503]
## Feature
Currently when you mouse over something like `(?(-2)...)`, all that is shown is "If Clause". It would be extremely helpful to show which backref it's conditional upon, something like "If Clause conditional upon 16th capturing group".

This is already done for e.g. relative subroutine calls like `(?-4)`, which shows e.g. "`(?-4)` recurses the 16th subpattern".

In a complex regex such as https://regex101.com/r/GUZl7X/6 the only way currently to see what subpattern a relative conditional is referring to is in the Explanation pane, and it's a real pain to find anything there in a regex such as this.

**Comment by firasdib** [comment]
I understand. What should the tooltip say when you're hovering a lookaround?

**Comment by Davidebyzero** [comment]
I don't think lookaround conditionals such as `(?(?=...)...)` need to do anything differently than they currently do when mouse-hovered.

Here's an alternative idea for relative conditionals: still just show "If Clause" when hovering over the `(?` beginning part or ending `)`, but when hovering over the `(-2)` part, show "True if the 16th capturing group is set". This would be consistent with the mouseover behavior of lookaround conditionals.

**Comment by firasdib** [comment]
Thanks! This is implemented. Will be live soon.
