### ISSUE TITLE
[^] is a valid expression

### ISSUE THREAD

**Issue by PageNotes** [firasdib/Regex101#1512]
I tested [^] as a regular expression, and it caught fire. Things like [^ ] and [^t] work fine. 
So I tried [^] at https://regexr.com/ and was relieved to see that it passed.

My interest in [^] is that it matches every character without the need to remember how to get "." to work.

**Comment by working-name** [comment]
Hello!

I could swear there was another issue which also tackled `[^]` not working, ~~but can't find it!~~

Nevermind, found it! See #1457

TL;DR: javascript is cool with it, PCRE is not. You forgot to switch from PCRE to javascript which happens to be the default flavor on regexr.com.

**Comment by PageNotes** [comment]
Thanks, Alan.
I hadn't noticed the menu at the upper left.
Jim Williams
