### ISSUE TITLE
Make unit tests more color blind friendly

### ISSUE THREAD

**Issue by davidrpalmer** [firasdib/Regex101#1514]
## Feature
The unit results are hard to read for people that struggle to distinguish between red and green. In my case I can usually tell red/green apart fairly easily, unless it's only a small area - then it's a struggle. So the new (#1090) unit test theme that only colourises a small area on the left edge of the row means I now keep missing failed tests. The old style coloured the whole row so it was easier (for me) to see.

Possible solutions:
 * When a test fails make the whole row red.
 * Place a symbol (like `x` or `!`) in the colored edge when a test fails.

**Comment by firasdib** [comment]
Thanks for bringing this to my attention, it was nothing I considered when initially designing this.

Adding an icon seems to be the best way forward, but I am unsure where exactly I would place it.

**Comment by firasdib** [comment]
How do you feel about this?

![image](https://user-images.githubusercontent.com/1335165/108609552-e35e5700-73ce-11eb-9736-2ce159743021.png)

![image](https://user-images.githubusercontent.com/1335165/108609553-e6594780-73ce-11eb-91f5-a6e607455bc3.png)

**Comment by firasdib** [comment]
Im going to push this live, if you feel it isn't enough, reopen and we can discuss options :)

**Comment by davidrpalmer** [comment]
I was thinking of making the colored left edge a bit wider so it had space for a symbol. But this works just as well. Thanks.
