### ISSUE TITLE
Unable to load site with latest google chrome

### ISSUE THREAD

**Issue by MyTechnoHunter** [firasdib/Regex101#1515]
## Bug Description
Site wont load, instead a page appears saying your browser is not supported, update (with a link)
google chrome is the following version (literally just updated today)
Google Chrome is up to date
Version 88.0.4324.182 (Official Build) (64-bit)

### Reproduction steps
load the site with the latest google chrome

### Expected Outcome
to see the site/be able to use it

### Browser
Include browser name and version
Google Chrome
Version 88.0.4324.182 (Official Build) (64-bit)
### OS
Include OS name and version

Windows 10 20H2 (windows 2004 build 19041.746)

**Comment by firasdib** [comment]
Thanks for bringing this to my attention. This was because of the new CSP policy added, which for some reason, worked in firefox but not Chrome. Issue should be resolved now!

**Comment by BryceMorrison** [comment]
Yes, the issue is resolved now.
