### ISSUE TITLE
The "Whats New" button returned un-rendered html text

### ISSUE THREAD

**Issue by reedjones** [firasdib/Regex101#1516]
## Bug Description
The "Whats New" button returns un-rendered html text inside the modal window 

### Reproduction steps
click the 'whats new button' in top right 

### Expected Outcome
show some content in modal window or perhaps load a new page but it loaded like plaining html into the modal

### Browser
chrome, latest version 

### OS
Windows 10

**Comment by firasdib** [comment]
Thank you! Still hunting down tiny bugs after todays upgrade. Should be fixed now

**Comment by anledehai** [comment]
> 谢谢！在今天的升级之后，仍在寻找小错误。现在应该修复

Great, it's normal now，thanks~~~
