### ISSUE TITLE
Language switching is not working

### ISSUE THREAD

**Issue by anledehai** [firasdib/Regex101#1517]
Browser: chrome88
System: windows10
Q:
Go to regex101.com/settings, the language switch is invalid, always English

**Comment by firasdib** [comment]
Thank you, I will fix this soon.

This is the same issue as #1516 due to the new backend.

**Comment by anledehai** [comment]
> Thank you, I will fix this soon.
> 
> This is the same issue as #1516 due to the new backend.

Nice! it's normal now，thanks~~~
