### ISSUE TITLE
Engine error with Flavors PCRE2, PCRE, Python 2.7

### ISSUE THREAD

**Issue by ketanrs** [firasdib/Regex101#1519]
## Bug Description
Matching engine error -  regex with flavors PCRE2 / PCRE / Python giving "Engine Error"

### Reproduction steps
1. Enter a regex `.*?[{]1:.{3}(.{8}).{1}(.{3}).*?[{]2:O900.* `
2. Enter Test String
3. regex options change to /gs
4. In Flavor choose PCRE2 OR PCRE OR Python 2.7
5. Engine shows "Processing" and after sometime shows "Engine error" with following message

"Unable to initialize the regex engine! Please try to reload the web page. If the issue persists, please open an issue here: https://github.com/firasdib/Regex101/issues"

### Expected Outcome
Match OR No match

### Browser
Chrome - Version 81.0.4044.122 (Official Build) (32-bit)

### OS
Windows 10 enterprise

**Comment by firasdib** [comment]
Does the problem occur in an incognito tab? Do you mind taking a screenshot of your console and expanding any potential errors?

**Comment by ketanrs** [comment]
It's a normal tab.  Have attached the image
![regex101-1519bug](https://user-images.githubusercontent.com/16254307/109522249-13df7880-7ad4-11eb-9fd9-f2b424ebd4f3.PNG)


Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 2d 2d @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (https://regex101.com/static/pcrelib.js:1:12173)
    at https://regex101.com/static/pcrelib.js:1:13982
abort @ pcrelib.js:1
(anonymous) @ pcrelib.js:1

**Comment by firasdib** [comment]
Does it happen in an incognito tab also?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by ketanrs** [comment]
Sorry but due to administrative restrictions, can't start browser in incognito mode.

Thanks & Regards
Ketan

**Comment by firasdib** [comment]
Any update @ketanrs ?

**Comment by ketanrs** [comment]
Hi Firas,

I did try after clearing the cookies and the result was the same.

Thanks,
Ketan

**Comment by firasdib** [comment]
Are you behind a corporate network or similar that blocks wasm files?

**Comment by ketanrs** [comment]
Yes, I am behind corporate network.  But another colleague also part of the same network is able to work without issues.  Not sure if it's region specific.

**Comment by firasdib** [comment]
Perhaps it something on your local computer? Hard for me to assess from here, but sounds local to you.
