### ISSUE TITLE
regex error

### ISSUE THREAD

**Issue by Gapin02** [firasdib/Regex101#1521]
## Bug Description
https?://[^/]+            doesnt recognize //

for this
http://website1/blosas/ds
http://website2Ari/satormenta
http://website3/minna_jc_best_pair
https://website4/Cur_va

### Browser
Include browser name and version
Safari

### OS
Include OS name and version

**Comment by working-name** [comment]
![safari](https://user-images.githubusercontent.com/16505052/109678211-66f31300-7b48-11eb-867b-27b92232f04a.png)

Which version of Safari? Which flavor? Did you make sure there's no errors in the explanation pane, like this:
```js
/ An unescaped delimiter must be escaped with a backslash (\)
```

**Comment by Gapin02** [comment]
Safari Versión 13.1.2 (13609.3.5.1.5)



El 2 mar 2021, a las 18:15, Alan <notifications@github.com> escribió:
 <https://user-images.githubusercontent.com/16505052/109678211-66f31300-7b48-11eb-867b-27b92232f04a.png>
Which version of Safari? Which flavor? Did you make sure there's no errors in the explanation pane, like this:

/ An unescaped delimiter must be escaped with a backslash (\)

**Comment by firasdib** [comment]
Can you please take a screenshot of your browser window?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by working-name** [comment]
Sorry @Gapin02 I can't reproduce that in 13.1.2 either. Since Apple killed addons in Safari, I suspect it is a simple thing like you forgot to escape the `/` which happens to be the regex delimiter.

![safari-13 1 2](https://user-images.githubusercontent.com/16505052/109679192-58f1c200-7b49-11eb-904a-d7f0087a8d01.png)

**Comment by Gapin02** [comment]
El 2 mar 2021, a las 18:22, Alan <notifications@github.com> escribió:


Sorry @Gapin02 <https://github.com/Gapin02> I can't reproduce that in 13.1.2 either. Since Apple killed addons in Safari, I suspect it is a simple thing like you forgot to escape the / which happens to be the regex delimiter.

 <https://user-images.githubusercontent.com/16505052/109679192-58f1c200-7b49-11eb-904a-d7f0087a8d01.png>

**Comment by firasdib** [comment]
Any update @Gapin02 ?

**Comment by Gapin02** [comment]
Does work on others regex programs but not in Safari.

**Comment by firasdib** [comment]
Please share a link


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by working-name** [comment]
@Gapin02 ping :)
