### ISSUE TITLE
Generate content that passes Regex

### ISSUE THREAD

**Issue by samuelneff** [firasdib/Regex101#1522]
## Feature
An alternate and really great way to test a regex is to randomly generate values that match the regex and then the user can review and validate that everything is as expected.

Similar to functionality here:

https://www.browserling.com/tools/text-from-regex

Would be great of Regex101 had this functionality built in.

**Comment by Ouims** [comment]
This tool you linked doesn't support lookahead or lookbehind it seems.

**Comment by samuelneff** [comment]
That's even more reason to implement it properly within Regex101.

**Comment by firasdib** [comment]
This is a very hard problem to solve, and I doubt anything I will be able to whip up will be sufficient. There are some genetic algorithms that try to solve this, but they aren't very good.
