### ISSUE TITLE
Update expected to overwrite the regex ID (aka no versioning)

### ISSUE THREAD

**Issue by don922** [firasdib/Regex101#1523]
## Bug Description
There is no way to update an existing version of a regex. Selecting update creates a new version.

### Reproduction steps
Create a regex expression and save it. Modify it and then click update. A new version will be created. 

### Expected Outcome
Existing version should be updated and not a new version created. There should be a way to update the existing version you are working on as well as creating a new version.

See video
https://user-images.githubusercontent.com/79875235/110228571-3278b180-7ed0-11eb-8e11-64dcf3c662df.mp4

### Browser
Microsoft Edge
Version 89.0.774.45 (Official build) (64-bit)
Microsoft Edge is up to date.

### OS
Edition: Windows 10 Pro
Version: 2004
OS Build: 19041.804

**Comment by working-name** [comment]
That's intended behavior. Each change saved is a new iteration. The regex ID is not the number, that's just a revision number of the current regex branch/id. 

As the site works right now:
- you create a new branch or ID by hitting SAVE
- you create a new revision of the same branch or ID by hitting UPDATE

**Comment by don922** [comment]
It might be intended behavior, but IMHO there should be a way to update without creating a new revision. Just my 2 cents worth.

BTW, I am new to regex and love this application. Keep up the good work!

**Comment by working-name** [comment]
I understand your point. By the way, you can always get the latest revision of a regex by linking to `regex101.com/<id>/latest`.

I would not like the behavior you're after mainly because revisions are a very important part of development, and double as a nice live help follow-up on IRC. 

If it would save the latest changes to the same ID I would have to keep a bunch of different links around and organize myself to keep them together. Bit of a struggle on that last part 😁

**Comment by don922** [comment]
I'm not saying that revisions aren't important or needed. They are. I guess I just look at them differently. I look at a revision as a working improvement over the previous revision. The way it works now that is not necessarily the case. For example - I create a regex and save it. It becomes rev 1. Some point in the future I need to change it so I open rev 1 and update it without making any changes. I now have rev 2. While I am making my changes to rev 2, which don't work yet :),  I update it 4 times and I now have rev 3, 4, 5, and 6. I want to save my work while working on it, as any good coder would, so I don't lose my changes. Finally while working on rev 6 I get it to work and do another update creating rev 7. I now have rev 1 which works, revs 2, 3, 4, 5, 6 which don't work and rev 7 which does. It would be much cleaner if there was the option to update an existing rev. In this example I would have created rev 2 and just kept updating that one until I got it working. When I needed to make another change I would create rev 3. If you wanted to create different revisions you would still have that option. Alternately maybe create a way to delete a revision.

**Comment by firasdib** [comment]
What you just described are commits, which are what the versions are. The id is your branch, the number is the commit. The revisions you're talking about sound more like "releases", which is nothing supported. You can always create a new branch/fork of your regex that has no history if you'd like that.
