### ISSUE TITLE
Multi Regex Expressions tester

### ISSUE THREAD

**Issue by konser80** [firasdib/Regex101#1525]
Hi, guys. It's a #featurerequest

Is it possible to make a Multi Regex feature in Unit tests?
Please, take a look at the screenshot attached.

Yes, for now I can combine regex#1 & regex#2 with `*.?` between them.
But I can't write an regex (like #3) that shouldn't match. 

![CleanShot 2021-03-08 at 13 59 11@2x](https://user-images.githubusercontent.com/43511083/110286051-d1a7c100-8016-11eb-8aa0-08c25b9b5943.png)

**Comment by firasdib** [comment]
This question have been raised previously, but this is not something I will be doing. The website would need a complete redesign and tremendous amounts of work to morph it into this.

Sorry!
