### ISSUE TITLE
debugger steps don't match main page steps for PCRE2

### ISSUE THREAD

**Issue by mlfisher1** [firasdib/Regex101#1526]
Example:  https://regex101.com/r/7V9t4R/1

The debugger steps match the main page steps for PCRE (48/48), but not for PCRE2 (48/444).

**Comment by firasdib** [comment]
This is normal, since the debugger runs in an unoptimized environment, to allow for the matching steps to be visible. However, it is very odd that PCRE2 takes that many more steps to fail than what PCRE does.

Perhaps there is an error in the implementation on me end? 

@Davidebyzero What do you think?

**Comment by mlfisher1** [comment]
https://regex101.com/r/7V9t4R/1/debugger

Looks like PCRE2 is counting each character it skips scanning for the next "^" point while PCRE counts the scan as a single step.

Also found this, quite by accident, where the PCRE debugger appears to stop before scanning the last line of input. 

https://regex101.com/r/VHh2Xn/1

The PCRE2 debug does process the whole input.  In this case, I'm not sure I believe the front page step count either.

**Comment by firasdib** [comment]
I don't see a reason why you shouldn't be able to trust the step count, it is accurate.

I must assume that the two different versions have different engine optimizations in place. As to why PCRE1 behaves the way its doing, I cannot say. It is deprecated and buggy, and you are wise to stick to PCRE2.

**Comment by mlfisher1** [comment]
A man with one watch always knows what time it is.  A man with two watches is never sure.  :)

I would normally agree on the PCRE1 bit, but PCRE1 debugger is usually closer to the front page step count, which makes it quicker to find issues/optimizations in many cases.

**Comment by firasdib** [comment]
I don't see a way to proceed with this for now. If you find more concerning issues, please feel free to reopen.

**Comment by Ouims** [comment]
Hello, just a quick feedback on this.

I don't think regex101 is faulty but it does seem to be a regression with pcre2, @mlfisher1 is entirely right.
