### ISSUE TITLE
🐞: The saved title is now no longer displayed

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1527]
## Bug Description

![image](https://user-images.githubusercontent.com/10995302/110717506-2b410300-8244-11eb-86e3-da701471a962.png)

> Previously available displays, now they will not be displayed.

### Reproduction steps

1. https://regex101.com/
2. `Ctrl+S`
3. Editor a title

## test
https://regex101.com/r/xuBCsv/1/

**Comment by firasdib** [comment]
This was intentional: I thought this UX was weird so I moved the title to the actual title of the page. This means you can bookmark the URL and it will have the correct title etc.
