### ISSUE TITLE
🌟Feature request:   `regex101.com/r/xxxx`  can auto to select the latest version !

### ISSUE THREAD

**Issue by dnknn** [firasdib/Regex101#1528]
https://regex101.com/r/xuBCsv/1
	  https://regex101.com/r/xuBCsv/2
	  https://regex101.com/r/xuBCsv/3
	  https://regex101.com/r/xuBCsv/4 (🆕)

# Flavor Request: 

open 👉 [regex101.com/r/xuBCsv](https://regex101.com/r/xuBCsv) 

- ## **Current behavior:** 
　　　👎 redirector to [regex101.com/r/xuBCsv/1](https://regex101.com/r/xuBCsv/1)

- ##  **Expected behavior:**
　　　👍 redirector to [regex101.com/r/xuBCsv/4](https://regex101.com/r/xuBCsv/4)

**Comment by Doqnach** [comment]
https://regex101.com/r/xuBCsv/latest is already a feature.

See #1450 #1295 #924 #843
