### ISSUE TITLE
Can't enter question mark on Firefox for Android

### ISSUE THREAD

**Issue by mklein994** [firasdib/Regex101#1529]
## Bug Description
When I try to enter a question mark in the regex input or test string box, it opens the keyboard shortcuts window. It doesn't let me enter the character directly.

### Reproduction steps
Attempt to enter a question mark in either of the above mentioned text inputs.

### Expected Outcome
A question mark (`?`).

### Browser
Firefox 86.1.1 (stable, Build \#2015794883)

### OS
Android 11

### Additional Information
My keyboard app is Gboard - the Google Keyboard (version 10.2.07.351353117-release-arm64-v8a)

**Comment by firasdib** [comment]
What happens if you use the built in keyboard? Does it work then?

**Comment by mklein994** [comment]
Nope, I encounter the same issue (LG Keyboard). It doesn't happen in Chrome though.

**Comment by mklein994** [comment]
https://user-images.githubusercontent.com/3069239/111015907-a0115b80-8370-11eb-8a99-440b0a9e8634.mp4

Here's a screen recording of me trying to type a question mark. It seems to let me only when it's finishing a word (notice the underline). This behaviour also seems to happen when I have the suggestion strip turned off, for both keyboards.

It might just be a Firefox thing.

**Comment by working-name** [comment]
Confirmed using GBoard on Android 10, 1Password keyboard, and Samsung's keyboard. Looks like on mobile Firefox (beta, and nightly included) the event bubbles up right past CM.

Chrome, Brave (chrome based) unaffected.

**Comment by firasdib** [comment]
Does the same issue appear if you try to type a questionmark into the quickref search box?

**Comment by working-name** [comment]
No, not in my case.

**Comment by sailendrap** [comment]
I am facing the same issue on Chrome 87.0.4280.77 , Safari 14.4.1 and Firefox Daylight 32.1 on my iPad OS.

**Comment by firasdib** [comment]
Should be resolved now.

**Comment by mklein994** [comment]
Yes, it works for me. Thanks!

**Comment by sailendrap** [comment]
Thanks for the quick turn around @firasdib . It’s working :)
