### ISSUE TITLE
Javascript Unicode Property Escapes dont seem to work

### ISSUE THREAD

**Issue by fergiemcdowall** [firasdib/Regex101#1530]
## Bug Description

[Javascript Unicode Property Escapes](https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes) dont seem to work on https://regex101.com.

In my browser console it is possible to write:
`'Düsseldorf, Köln, Москва, 北京市, إسرائيل !@#$'.match(/[\p{L}-]+/ug)` 
...and get:
`[ 'Düsseldorf', 'Köln', 'Москва', '北京市', 'إسرائيل' ]`

### Reproduction steps

**Regular expression:** `/[\p{L}-]+/ug`

**Test string:** `'Düsseldorf, Köln, Москва, 北京市, إسرائيل !@#$'`

### Expected Outcome

`[ 'Düsseldorf', 'Köln', 'Москва', '北京市', 'إسرائيل' ]`

### Browser
Firefox 86.0.1 (64-bit)

### OS
MacOS Big Sur 11.2.1 (20D74)

**Comment by firasdib** [comment]
My mistake. I will push a fix for this later today, meanwhile, you can use `/[\p{General_Category=L}-]+/`

**Comment by fergiemcdowall** [comment]
OK- great! And thanks for giving the world regex101 👍🙂
