### ISSUE TITLE
Second alternative not displaying in explanation

### ISSUE THREAD

**Issue by alexomics** [firasdib/Regex101#1531]
## Bug Description
When using the `|` for alternate matches only the first displays in the explanation

### Reproduction steps
Any regex using `|` seems to be affected. I noticed it with https://regex101.com/r/r6EWPK/1 but for a MWE `a|b` also doesn't show the explanation. In the first line of the explanation doesn't show anything after the first `|`.

![image](https://user-images.githubusercontent.com/30386655/111291446-1c40c300-863f-11eb-8cbb-373e8f37705d.png)

### Expected Outcome

I would expect the alternative patterns to be explained.

### Browser
 - Google Chrome Version 89.0.4389.82 (Official Build) (x86_64)
 - Firefox 86.0.1 (64-bit)

### OS
macOS v11.2.3

**Comment by firasdib** [comment]
Thanks! I'll push a fix for this regression asap
