### ISSUE TITLE
Incorrect issues link on engine error

### ISSUE THREAD

**Issue by dslik** [firasdib/Regex101#1534]
## Bug Description

Was getting JS "Error: Unable to load worker, timeout after 10s".

![image](https://user-images.githubusercontent.com/5757591/111586927-c410da80-877e-11eb-8059-5b158f0ea556.png)

This was resulting in an engine error. ("Unable to initialize the regex engine! Please try to reload the web page. If the issue persists, please open an issue here: https://github.com/firasdib/Regex101/issues")

![image](https://user-images.githubusercontent.com/5757591/111584834-a2faba80-877b-11eb-8214-2c84210fb6b7.png)

The link generated is:

`
<a class="_1k1Ay zA-6I" href="/https://github.com/firasdib/Regex101/issues">https://github.com/firasdib/Regex101/issues</a>
`

![image](https://user-images.githubusercontent.com/5757591/111584930-c9b8f100-877b-11eb-8a39-55ae76856579.png)

Note the extra "/" at the beginning of the href. This results in the browser being redirected to:

https://regex101.com/https://github.com/firasdib/Regex101/issues

instead of

https://github.com/firasdib/Regex101/issues

Took a look through the JS source that generates this error message, and nothing looked incorrect, so this is quite odd.

![image](https://user-images.githubusercontent.com/5757591/111587022-e276d600-877e-11eb-9899-c71c18525f11.png)

It might be because of the baseURI, but react is difficult to debug this way.

![image](https://user-images.githubusercontent.com/5757591/111588515-e60b5c80-8780-11eb-8bc2-630a0b72d018.png)

### Reproduction steps

Unable to reproduce.

### Expected Outcome

Correct link without extra leading "/"

### Browser
Include browser name and version

Safari 13.0.3

### OS
Include OS name and version

MacOS 10.15.1

**Comment by firasdib** [comment]
Thanks for the report, I have this fixed locally, and will push it live later.

I hope the engine error itself was resolved :-)
