### ISSUE TITLE
Regression: pasted replacement regex not populating substitution part

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#1536]
## Bug Description
When pasting `s/./ /g` in the expression input box it will parse everything correctly except the replacement string. It doesn't seem to make a difference if it's a single space or any other character or any number of characters or a different delimiter is used.

### Reproduction steps
1. Open https://regex101.com
2. Paste `s#.+#I like soup#g` in the expression input box
3. Substitution box pulls up but it is not populated.

### Expected Outcome
3. Populate the substitution input box, as it did before.

### Browser
- [x] Chrome/Brave/Firefox (latest)
- [x] Safari 12.1

### OS
macOS 10.14.4

**Comment by firasdib** [comment]
Thanks, fix will be pushed soon.
