### ISSUE TITLE
What is the criteria for blocking a browser

### ISSUE THREAD

**Issue by Feodor2** [firasdib/Regex101#1537]
regex101.com blocks certain browsers and show message "it seems your browser does not meed the criteria". Please elaborate.
Will it hurts to add a close button on the message window for possibility to proceed further.

**Comment by Doqnach** [comment]
what JS engine does MyPal run? Because that can be the limiting factor possibly?

**Comment by firasdib** [comment]
The website checks for web workers and Web Assembly support. I will update the message to reflect this.

You can open your browsers console and display the errors there and I might be able to help, could potentially be an error on my end.
