### ISSUE TITLE
\p{Extended_Pictographic}

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1538]
## Bug Description
The recent implementation of \p{Extended_Pictographic} has some issues
Everything is noted in that thread #1524, to sum up a bit:

-I get a display issue of a glyph in the editor, but the glyph is correct in the match panel info, others are not having such problem:

https://user-images.githubusercontent.com/18450877/111008375-3f464b00-8391-11eb-84b8-963e7f271028.png

-there's a crash of the website if the quantifier * is used after that \p
-I believe that the zero width space (code point 8205) could/should be displayed as non visible char when we have the option to help visualizing invisble char/non printable char

### Reproduction steps
 
https://regex101.com/r/OwAU54/2

### Expected Outcome

no crash, correct glyph

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by firasdib** [comment]
Everything looks to be in order. Multiple characters are combined to make a single emoji (this is the behavior of the browser), but the regex engine matches the characters independently.

It looks like your font is unable to render them correctly, have you tried switching to another?

**Comment by Ouims** [comment]
As i mentioned, the match information panel display the character correctly, so it looks like my font is able to render this particular character and it would be an issue with regex101 in the editor only.

Ok for the crash.

I'd like to talk about the match number 2 in the 'reproduction step' regex101 link. the character that is reported (and displayed correctly anyway) as the match does exist in the string, but the editor also seems to render the string in a way that does not show it, I've mentioned in the linked issue there are invisible char and a 'mark' unicode character, and I was wondering if it could be why it's not showing it in the editor, that maybe it was expected behavior.
Would be great to hear you about non visible chars not appearing as U+N form there as well

**Comment by firasdib** [comment]
Try inserting the text into a regular text area to see how the browser renders it, outside of regex101, to verify the behavior.

I have taken the liberty to show you how regex101 renders for me, and here, in the github textarea. They look the same to me, which indicates that regex101 is rendering everything as expected, and there is nothing to fix.

![image](https://user-images.githubusercontent.com/1335165/112194553-4a0ea480-8c09-11eb-8546-d60add722aa1.png)
![image](https://user-images.githubusercontent.com/1335165/112194608-572b9380-8c09-11eb-8053-0a37c5ac0424.png)

**Comment by Ouims** [comment]
It renders correctly on github and google translate.

**Comment by firasdib** [comment]
Does it render correctly on https://codemirror.net/? If not, consider opening a bug report with them.

**Comment by Ouims** [comment]
I just tried, it's rendered correctly as well as in version 6 of codemirror.
If it uses my own fonts, then it looks like the font rendering in the match info panel is fallbacking 'correctly' to find my segoe ui symbol font, where it's not for the editor, is this a possibility?

**Comment by Ouims** [comment]
no news on this? When I tooltip the glyph, it's displayed correctly as well:

![image](https://user-images.githubusercontent.com/18450877/112731320-c3becf00-8f36-11eb-8fcd-c6bfa496d71f.png)


It doesn't seem to be a codemirror issue imo, is your final verdict so far that it is an issue with codemirror?

**Comment by firasdib** [comment]
Unicode is hard. Sounds like a problem on your end. 

https://hsivonen.fi/string-length/


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Ouims** [comment]
I found someone on win7 which can reproduce the glyph issue.
Something i just found: after the url loads, if i paste the character in either the editor or regex field, it shows up correctly.
