### ISSUE TITLE
Implement a way to select a capture group in the regex input

### ISSUE THREAD

**Issue by don922** [firasdib/Regex101#1539]
Enhancement request. 

Implement a way to select a capture group by positioning the mouse over the start or end of a capture group and clicking on it with the shift key (or control or alt) pressed. Since you already frame the group when the mouse is over the start or end of the group it should be easy to select it. This would make it easier copy or delete a group.

**Comment by working-name** [comment]
Hello there,

Are we discussing the regex input box or the test string here? Can you maybe share a screenshot?

**Comment by don922** [comment]
As you can see from the screen shot I moved the cursor over the third capture group. When you do that a box gets drawn around the group. I'd like to be able to say shift click on the group and have it selected so I can either copy it or delete it. It would be easier than clicking and dragging the cursor in order to select. 

![Capture Group](https://user-images.githubusercontent.com/79875235/112665667-b10ea200-8e31-11eb-9761-59dcdeb44efa.JPG)

**Comment by firasdib** [comment]
I'm not convinced that these shortcuts are going to be intuitive.

**Comment by don922** [comment]
Make the shortcut whatever you want. In the popup description you could put a message to ctrl-click (or whatever) to select.

**Comment by firasdib** [comment]
Well, this is in essence not just a request to highlight capture groups, but rather an editor change to highlight all contextual tokens in a go. The same would be relevant for character classes etc, right?

**Comment by don922** [comment]
It is not a request to highlight anything. It is a request to be able to copy whatever is already highlighted/outlined. In the screen capture I provided the mouse is over the beginning  of the third capture group and as you can see there is outline drawn around the whole group. All I'm asking for is the ability to be able to copy that easily, as an example, by control clicking. You already outline whatever the cursor is over. I just want to be able to copy what ever is outlined.

**Comment by don922** [comment]
Any further thoughts on this?

**Comment by firasdib** [comment]
I see where you're coming from, and I want to like this feature, but it just feels too niche to implement.

**Comment by firasdib** [comment]
Looked into this again, and I believe simply placing a cursor, and shift+clicking yourself at the end, is sufficient. Codemirror has a lot of built in functionality that would otherwise clash, plus, there is no intuitive way to showcase this functionality, which means 99% of all people would never know it existed.
