### ISSUE TITLE
Add Option to Show/Hide Matches

### ISSUE THREAD

**Issue by renecum** [firasdib/Regex101#1541]
Hi, I using regex101 to create a regex that matches a long list of entries.

I would like to know if it is possible that after evaluating the regex, there could be an option to hide the matches, so I can see only the lines that don't match the regex.

**Comment by working-name** [comment]
There is no UI option for that, but you can use substitution. In other words, replace your matches with nothing and all matches will be "hidden" in the substitution panel at the bottom.

**Comment by firasdib** [comment]
The solution provided by @working-name is the best way forward for you :-).
