### ISSUE TITLE
Code generation for Golang produces incorrect regex for Named capture groups

### ISSUE THREAD

**Issue by anandpaithankar1** [firasdib/Regex101#1542]
## Bug Description
The regex uses multiple named capture groups. 
```
/^(?P<sessionKey>session)\/(?<sessionId>[a-zA-Z-0-9_]+)\/?/gm
```
Output

```go
var re = regexp.MustCompile(`(?m)^(?P<sessionKey>session)\/(?<sessionId>[a-zA-Z-0-9_]+)\/?`)
```
Now the `sessionId` should be `(?P<sessionId>[a-zA-Z-0-9_]+)\/?`)`

### Reproduction steps

Use above regex, and use "Code generate" and choose Golang

### Expected Outcome
Correct one 
```go
var re = regexp.MustCompile(`(?m)^(?P<sessionKey>session)\/(?P<sessionId>[a-zA-Z-0-9_]+)\/?`)
```

### Browser
Chromium Version 89.0.4389.90 (Official Build) (x86_64)

### OS
macOS 10.15.4

**Comment by firasdib** [comment]
The code generator does not alter your regex, it simply shows you how to use it in your language. If you use the golang flavor on the website it will show you that your group is invalid.
