### ISSUE TITLE
I tried a RegEx And i works in JS but not in the Website.

### ISSUE THREAD

**Issue by StreetDanceD313** [firasdib/Regex101#1545]
## Bug Description
`RegEx = "/((([E]|[$])(([0-9]{1,3})[.]?)*([,][0-9]*))|((([0-9]{1,3})[.]?)*([E]|[$])([0-9]*)))\n/"`
`Expression Tried = "999.999.999$44350\n$9996665215\n"`
### Reproduction steps
Just put it in there and use PCRE2(PHP>=7.3) and did not work
Just recognize the first Expressions. If you change the string places it finds only the first one.
Tested in JS on Console and it worked.
Code:
```
let matches = "999.999.999$44350\n$9996665215\n".
matchAll("((([E]|[$])(([0-9]{1,3})[.]?)*([,][0-9]*))|((([0-9]{1,3})[.]?)*([E]|[$])([0-9]*)))\n")
matches.next() -> '999.999.999$44350\n';
matches.next() -> '$9996665215\n';
```
### Expected Outcome
999.999.999$44350\n
$9996665215\n

### Browser
Include browser name and version
Google Chrome Versão 89.0.4389.90 (Versão oficial) 64 bits

### OS
Include OS name and version
Windows 10 64 Bits

**Comment by working-name** [comment]
Can you please jsfiddle it? I can't make it work in my chrome.

**Comment by working-name** [comment]
@StreetDanceD313 did you get this sorted out?

**Comment by StreetDanceD313** [comment]
Nope

**Comment by StreetDanceD313** [comment]
Solved.
