### ISSUE TITLE
Engine error on expression

### ISSUE THREAD

**Issue by larkvirtual** [firasdib/Regex101#1548]
## Bug Description
Engine error on expression

### Reproduction steps
1. Open site https://regex101.com/
2. Enter regexp "^    [\.][0-9]+"
3. Wait few seconds during gray "processing..."
4. Gray "processing..." becomes red "Engine error"

### Expected Outcome
No "Engine error"

### Browser
Firefox 78.9.0esr (64-bit)

### OS
Debian 10

**Comment by firasdib** [comment]
Can you take a print screen of your developer console?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by larkvirtual** [comment]
@firasdib 
Here is: "Error: Unable to load worker, timeout after 10s
    _timeout https://regex101.com/static/bundle.9dd39d264d8e680ddfa3.js:1"

**Comment by larkvirtual** [comment]
Looks like it's browser-dependent.
Chromium (Version 88.0.4324.182 (Developer Build) built on Debian 10.8, running on Debian 10.9 (64-bit)) doesn't renders "Engine error".

I see "Engine error" at Debian 10, Firefox 78.9.0esr (64-bit)

**Comment by firasdib** [comment]
I would need to see your full output from both the console and the network tab. Hard to say otherwise. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by larkvirtual** [comment]
@firasdib 
Can't reproduce. Probably local RAM or network error or something.
Sorry for dusturbing.
