### ISSUE TITLE
Clicking on a group in Match Information scrolls and shows the matched group in the Regular Expression

### ISSUE THREAD

**Issue by iaalmeida** [firasdib/Regex101#1549]
## Feature
For long and complex expressions, it's very difficult to find the matched group in the Regular Expression.
It will be nice if clicking on a group in Match Information the Regular Expression scrolls to and emphasizes the matched group.
This way it will be much easier to locate the matched group.

**Comment by working-name** [comment]
Hello! That's a bit confusing, but since you're saying "scrolls to" I assume you mean scroll to the location of the matched string in the `TEST STRING` textarea. That's already implemented, all you need to do is click `Match #` in the `MATCH INFORMATION` panel on the right side.

**Comment by firasdib** [comment]
As @working-name said, this is already implemented. Make sure to click the Match/group (with the border underneath) in the match information pane.

**Comment by iaalmeida** [comment]
> Hello! That's a bit confusing, but since you're saying "scrolls to" I assume you mean scroll to the location of the matched string in the `TEST STRING` textarea. That's already implemented, all you need to do is click `Match #` in the `MATCH INFORMATION` panel on the right side.

I'm talking about `REGULAR EXPRESSION` textarea, not to `TEXT STRING`.

**Comment by iaalmeida** [comment]
> As @working-name said, this is already implemented. Make sure to click the Match/group (with the border underneath) in the match information pane.

Sorry but no, this is already done to `TEXT STRING` area, not to `REGULAR EXPRESSION` area.
I would like to know what is the matched group expression in `TEXT STRING`.
I think it will help to maintain complex regular expressions, using lots of groups (as an example I'm working with more than 200 groups).
