### ISSUE TITLE
Highlight 'not' in the assert message in Unit Test section

### ISSUE THREAD

**Issue by don922** [firasdib/Regex101#1550]
## Feature
In the Unit Test section make the 'not' in the assert message either bold or caps or both. This is to make it stand out that in this test the test string does not match. I prefer CAPS and bold.

Examples:

assert that regex does **not** match

assert that regex does NOT match

assert that regex does **NOT**  match

**Comment by firasdib** [comment]
Personally I feel the all caps to look quite jarring and bold doesn't do much to emphasize the word without caps. I realize the core of your request is still valid, but I am torn on how to proceed with this if I'm honest.

**Comment by don922** [comment]
Change the color of the entire assert message? Make it italic? Could be anything as long as you can easily tell that the assertation is for a negative test.

**Comment by firasdib** [comment]
Those are good ideas, thanks. I'll play with it.

**Comment by firasdib** [comment]
I went with italic, will go live soonish.

**Comment by don922** [comment]
I see it went live but it doesn't really pop. I think if you make the whole assert message italic, which is what is suggested a few messages back, it would be better.
