### ISSUE TITLE
regex101 is reporting no error and no match for an invalid regexp using the Golang flavor

### ISSUE THREAD

**Issue by DZ-TM** [firasdib/Regex101#1551]
## Bug Description
When provided an invalid regexp with flags e.g., `(?ms-)` it is supposed to produce an error, but it does not. It also does not trigger on anything semi-valid for example, `(?i-)a` with "a".

### Reproduction steps
Go onto the Golang flavour and input the regex `(?s-)a` or `(?i-)a` or equivalent - the main point is that it ends in "-" e.g., [this](https://regex101.com/r/qdAlhT/1)

### Expected Outcome
An error saying it is an invalid pattern.

### Browser
Firefox version 87.0

### OS
Windows 10 version 20H2

**Comment by firasdib** [comment]
Thanks for bringing this to my attention, I will adjust this.

**Comment by saedee** [comment]
> ## Bug Description
> When provided an invalid regexp with flags e.g., `(?ms-)` it is supposed to produce an error, but it does not. It also does not trigger on anything semi-valid for example, `(?i-)a` with "a".
> 
> ### Reproduction steps
> Go onto the Golang flavour and input the regex `(?s-)a` or `(?i-)a` or equivalent - the main point is that it ends in "-" e.g., [this](https://regex101.com/r/qdAlhT/1)
> 
> ### Expected Outcome
> An error saying it is an invalid pattern.
> 
> ### Browser
> Firefox version 87.0
> 
> ### OS
> Windows 10 version 20H2
