### ISSUE TITLE
PCRE debugger and (*NO_START_OPT)

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#1553]
## Feature

I understand why the pcre debugger is run with NO_START_OPT option, but I would rather control myself if there should be optimization at the start or not.
I would like the debugger to stop running with NO_START_OPT and check if the step count was 0, which should indicate that the pattern was optimized at the start, and display a message about it, explaining why there's no step, etc.
Even better imo would be the message suggesting, via a clickable link, to run the pattern with that NO_START_OPT option to see the steps, if the user so wishes. Maybe a checkbox to toggle the NO_START_OPT option, which could be just putting (*NO_START_OPT) in front of the pattern when enabled.

**Comment by firasdib** [comment]
A better approach might be a toggle button, with default = enabled? Might confuse some users though.
