### ISSUE TITLE
Feature Request: Support string literal patterns for ECMAScript

### ISSUE THREAD

**Issue by ushuz** [firasdib/Regex101#1554]
## Background

Currently, regex101 only supports slash-style pattern for ECMAScript, patterns that contains slash `/` must be escaped:

```
/^https:\/\/xxxx/
```

However, in ECMAScript, you can use string literals with [`RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) to avoid escaping slashes:

```
RegExp('^https://xxxx')
```

## Feature Request

Add an option or flavor to switch to string literal patterns for ECMAScript

Similar requests: #1127

**Comment by firasdib** [comment]
I could add `"`, `'` and backticks as delimiters. Would that suffice? You'd need to start escaping those delimiters instead though.

**Comment by ushuz** [comment]
> I could add `"`, `'` and backticks as delimiters. Would that suffice? You'd need to start escaping those delimiters instead though.

I think that should be enough.
