### ISSUE TITLE
Clicking on a group in Match Information shows the matched group in the Regular Expression area (related to #1549)

### ISSUE THREAD

**Issue by iaalmeida** [firasdib/Regex101#1555]
## Feature

For long and complex expressions, it's very difficult to find the matched group in the `REGULAR EXPRESSION` area.
It will be nice if clicking on a group in `MATCH INFORMATION`, the `REGULAR EXPRESSION` scrolls to and emphasizes the matched group.

This way it will be much easier to locate the matched group.
This is already done to `TEXT STRING` area, but not to `REGULAR EXPRESSION` area.
I think it will help to maintain complex regular expressions, using lots of groups (as an example I'm working with more than 200 groups).

**Comment by firasdib** [comment]
This has now been added. WIll be pushed live in a few days.
