### ISSUE TITLE
A valid and useful alternator construction is treated as an error by regex101

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#1556]
## Bug Description
If an empty alternation is used as anything but the first alternation, regex101 highlights its trailing alternator in red and displays the error message `An alternator at this position effectively truncates the group, rendering any other tokens beyond this point useless` in the Explanation box. If saved as a test case URL and loaded from that URL, the test cases are initially run, but are not re-run when the regex is edited (unless the thing it sees as an error is removed).

However, this construction is useful, and in fact the site doesn't complain about it if the first alternation is the empty one. For example, `a(|b|c)d` is accepted without complaint, but `a(b||c)d` is treated as an error. With that standalone example both expressions behave identically, but in some cases the order makes a difference in behavior. As a contrived example, `(?>a(|b|c))bd` will match `abd`, but `(?>a(b||c))bd`, which the site treats as an error, behaves differently and won't. Also there are matters of aesthetics, which influence how people will want to arrange their regex patterns. So it's not acceptable to force users to order their alternations in a certain way.

### Reproduction steps
I encountered this when solving the code golf puzzle [Solve a 2xN Maze](https://codegolf.stackexchange.com/questions/206957/solve-a-2xn-maze/223037#223037).
https://regex101.com/r/2wI6jW/3 - the site doesn't complain, and accepts the pattern without error.
https://regex101.com/r/2wI6jW/4 - the site treats it as an error, but it's a completely valid and aesthetically pleasing regex

### Expected Outcome
This is a valid pattern and should be accepted without error.

**Comment by firasdib** [comment]
I will remove the error, it was intended to help avoid common errors, but might cause more harm than good.
