### ISSUE TITLE
Preview in browser doesn't provide the expected result in my app

### ISSUE THREAD

**Issue by REInVent650** [firasdib/Regex101#1563]
## Bug Description
Result on website doesn't match output in my Java app.

### Reproduction steps
**regular expression:** `h?t?t?p?s?:?[a-z0-9\/_.\-]+.js\b`
**test string:** `<script src="https://pagead2.googlesyndication.com/pagead/js/r20210415/r20190131/show_ads_impl_fy2019.js" id="google_shimpl"></script>`

### Expected Outcome - browser preview
`https://pagead2.googlesyndication.com/pagead/js/r20210415/r20190131/show_ads_impl_fy2019.js`

### Actual Outcome - in my Java app
`//pagead2.googlesyndication.com/pagead/js/r20210415/r20190131/show_ads_impl_fy2019.js`

### Browser
Include browser name and version
Brave Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (64-bit)

### OS
Include OS name and version
Android 10 - built to target Android 9 API 28

**Comment by working-name** [comment]
@REInVent650 Sorry, don't have an Android 10 dev env to test in. I did however test with JDK 1.8, 9, 10, and 11 and they all return the full URL as expected.

Just a quick note: You could shorten the burden of making each individual character options by using a non-capturing group like so: `(?:https?)?:?` - that would either match nothing, http/http:/https/https:

Sometimes src links are written as `//domain.com` to give the browser leeway in picking between http and https and match the current scheme utilized to reach domain.com

**Comment by REInVent650** [comment]
> Sometimes src links are written as //domain.com to give the browser leeway in picking between http and https and match the current scheme utilized to reach domain.com

sorry for the false alarm - I was using okhttp to get the source code but had only been looking at it in inspect element on Chrome so my regex was getting all it could.

thanks for the tip - i'm still very new to regex :)

**Comment by REInVent650** [comment]
I'm not sure if this is a bug or something else I'm missing... 

`[0-9]+\. .+` on the regex101 website captures parentheses () but in my app regex stops when it gets to one.
What am I doing wrong?
