### ISSUE TITLE
Add icon beside Quick Reference "Substitution" titles

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#1566]
Some characters are used both in matches and substitutions, such as whitespace: `\t`, `\r`, `\n`, `\f`.

When a user selects Quick Reference->All Tokens and search for `\t`, the user sees two results: "Tab ... `\t`" and "Tab ... `\t`" where the titles are identical, but the descriptions differ: `\t ... Matches a tab character. Historically, tab stops happen every 8 characters.` vs. `\t ... Insert a tab character.`

Could the results from the Substitution category show the same "scissors" icon beside them that FUNCTION->Substitution in the left pane uses?

Using an icon instead of text would avoid the need for language translation/i18n.

**Comment by firasdib** [comment]
This is a good point. Perhaps the results should be segregated somehow to distinguish which are for substitution and which are matching.

**Comment by firasdib** [comment]
I've adjusted the wording slightly, thanks for reporting. It will take a while for this update to be released fyi.

**Comment by alialobidm** [comment]
[](url)
