### ISSUE TITLE
Unicode category not valid for Java regex

### ISSUE THREAD

**Issue by msoutopico** [firasdib/Regex101#1570]
# Steps

https://regex101.com/r/d9uqL5/1

# Expected

`\p{Zs}` matches the space.

# Actual

`\p{Zs}` This script is unknown/invalid

**Comment by firasdib** [comment]
Thanks, this is resolved and will be pushed live in a couple of days.

**Comment by 0799393422** [comment]
https://www.facebook.com/groups/elite.of.iraq

**Comment by 0799393422** [comment]
Eliteofiraq [](https://www.facebook.com/groups/elite.of.iraq)
