### ISSUE TITLE
Cannot indent code using Tab key

### ISSUE THREAD

**Issue by qbui-quod** [firasdib/Regex101#1572]
## Bug Description
Tab key does not indent code anymore. It just keeps switching to another section of the website.

Unlikely causal but I just include anyway: I have been using Regex101 and it works fine the whole day. Right before this incident, I accidentally pressed the Tab key + another key nearby (which I don't know which exactly) and this issue happened right away. 

The thing is: now all my co-workers who try to go on Regex101 and press the tab key, they experience the same problem. 

### Reproduction steps
1. Enter any code
2. Press Tab key

### Expected Outcome
1. Tab key does not indent code
2. It tabs other sections of the page

### Browser
Version 90.0.4430.93 (Official Build) (x86_64)

### OS
macOS Catalina
10.15.7

**Comment by Ouims** [comment]
Tab keys' behavior was recently remade #676

**Comment by firasdib** [comment]
This is in order to preserve tab order in the document and allow users to tab freely, without getting "stuck" in a specific place. This helps those with disabilities or those which do not use a mouse.

How do tools normally work around this? Any suggestions?

**Comment by firasdib** [comment]
I don't know, what is commonly used by other tools?

Shift+Tab is reserved for reversing the tab order of the document.

**Comment by Ouims** [comment]
It's been said that regex101 is not meant to be a full featured text editor, I don't see why you would want to indent anything, if you want a tab in your input, paste a tab or generate it with alt or equivalent.
I think most people never need to get a tab character to indent anything.
An idea could be that if you hold the tab key for 2 secs and you started in the editor, it could add a tab character at the position you were and would reset the focus to the editor.

**Comment by firasdib** [comment]
A new option will be added where you can disable the default tab behavior. When disabled, inputs will instead insert a tab character.
