### ISSUE TITLE
Moovweb / Layer0 sponsorship

### ISSUE THREAD

**Issue by savchenko** [firasdib/Regex101#1574]
Hi,

There is absolutely no question that project has to be sustainable one way or another. 
However it is currently promoting Moovweb / Layer0 who prohibit users from publishing benchmarks _(!)_ of their service:

![30-Apr_13-36-46](https://user-images.githubusercontent.com/300146/116647541-f6d30300-a9b9-11eb-84c3-29726f172c0e.png)

![30-Apr_13-36-20](https://user-images.githubusercontent.com/300146/116647572-07837900-a9ba-11eb-86fb-8e86e3a5ef38.png)

Want to compare them with Netlify / Cloudfront / Google Cloud CDN? Share it publicly?! Clear violation of ToS.

**Comment by firasdib** [comment]
This is indeed an interesting find, but not necessarily nefarious. Have you reached out to them and asked about this particular restriction?

**Comment by savchenko** [comment]
Certainly not nefarious, more of a questionable business practise at best.

> Have you reached out to them and asked about this particular restriction?

I have, there was no reply.

**Comment by firasdib** [comment]
@savchenko I've forgot to get back to you - have you tried contacting their layer0 email?
