### ISSUE TITLE
Working with Arabic (RTL language)

### ISSUE THREAD

**Issue by ATablas** [firasdib/Regex101#1576]
## Bug Description
The typing cursor moves inaccurately in Arabic. When you press the "Home" key, the cursor is expected to go back to the beginning even if apparently it's still in the end. But in the app, if you press "Home" and type anything, it will actually still type it in the end.
The highlighting of the matched Arabic characters is also not really accurate.

### Reproduction steps
Expression: /(?<!\S)(?=((?:\w*\h*){0,3}+كتاب(?:\h*\w*\h*){0,3}+))/ug
Test String: بسم الله الرحمن الرحيم وهذا كتاب أنزلناه إليك مبارك  بسم الله الرحمن الرحيم وهذا كتاب أنزلناه إليك مبارك

### Expected Outcome
It is expected to highlight the bolded text:
بسم الله **_الرحمن الرحيم وهذا كتاب أنزلناه إليك مبارك_**  بسم الله **_الرحمن الرحيم وهذا كتاب أنزلناه إليك مبارك_**

### Browser
Chrome 90.0.4430.93 (64-bit) [Latest]
Firefox 88 (64-bit) [Latest]

### OS
Windows 10

Demo:
[https://regex101.com/r/vh4LLD/1](https://regex101.com/r/vh4LLD/1)

**Comment by firasdib** [comment]
This issue raises an interesting problem. The regex engine is always going to be interpreting the input string from left to right, and I don't know of any method of inverting that. Thus, should the input string also always be forced LTR?

**Comment by ATablas** [comment]
Not sure if that would produce natural results.
It could be an option though. So, if someone has the Arabic string already typed aside, they can just copy paste it regardless of how it's going to look--obviously if that isn't going to affect the results.

**Comment by firasdib** [comment]
@ATablas Correct, it would be "unnatural" to type RTL languages into a LTR textfield, but everything else expects it to be LTR. The indices are calculated LTR etc. I can try it out and see if it changes anything, or if the RTL language still ends up reeking havoc.

**Comment by firasdib** [comment]
Seems to work OK!
