### ISSUE TITLE
How to get more insight into execution using the debugger?

### ISSUE THREAD

**Issue by David263** [firasdib/Regex101#1577]
I'm trying to understand how PCRE executes alternation, so I can optimize my searching of a long input string. I understand from reading that alternation patterns are frequently inefficient due to repeated or nested backtracking.

I'm using the test case "cccccadccccabccc" and wish to find matches ad and ab in the string, using the g modifier to simulate the PHP preg_replace_callback function.

I've tried match patterns like "ad|ab", "(ad|ab)*", and "(a(d|b))" and simply cannot understand what operations are being executed using the debugger. In some cases there are match failures whose explanation is unclear, or in the final case the debugger reports more steps than it explains.

What, exactly, is the debugger showing me? Does it show empty string matching? Does it show backtracking? How can I tell whether backtracking is happening? Is there a way to tell whether my pattern is efficient or not? Why does the debugger report many more steps that it shows on the slider?

While I love this tool for helping me find bugs in my more complex search patterns, I would also like to use it to make my searching more efficient.

**Comment by firasdib** [comment]
These are very much the internal workings of the PCRE engine, and nothing I nor the debugger can or aim to answer.

If you want to find out more I would suggest reading the source or speaking with the author. The debugger aims to show exactly what the engine is doing with your expression while trying to match it to the input string.
