### ISSUE TITLE
Specific question about alternation

### ISSUE THREAD

**Issue by David263** [firasdib/Regex101#1578]
I have test cases that include two patterns I wish to detect: backslash followed by a character (an escaped character) AND "/\*" followed by any string followed by "\*/" (a comment).

My question is this: which is less time-consuming:

1. Combining both patterns into a single pattern using alternation, or
2. Doing two scans of the input string using PHP preg_replace_callback, one scan for each pattern?

For the sake of completeness, say that both comments and escaped characters are rare, that escaping characters takes precedence over comments, and that the length of the input string is 4000 characters (600 words), and that multibyte characters are not an issue.

**Comment by OnlineCop** [comment]
By "test cases", do you mean unit tests, or simply lines which you want to match and/or not match?

I typically scan for `/* ... */` (even across multiple lines) with a construct such as this:

    /(?x)  \/ [*]++  (?> [^\\*]+ | \\. | [*]++ (?!\/) )*  [*]++\ /

That is, find a literal `/` chacter followed by one (or more) `*` characters.
Then, repeating an atomic group (zero or more times, possessive), match:
* all characters except a backslash OR an asterisk
* OR, a backslash plus the character immediately after it (so `\n`, `\\`, `\*`, etc. all match); note that if you want to match a backslash followed by a literal newline, change `\\.` to either `\\[\S\s]` or `\\(?s:.)`
* OR, one or more asterisks, as long as they are not immediately followed by a `/` character

Finally, match the `*/` at the end.

If you're looking for escaped characters (backslash followed by any character) outside of the `/* ... */`, a simple `\/.` (or one of the above constructs to handle a literal newline: `\/[\S\s]` or `\/(?s:.)`) could work.

Now, as far as performance goes: if the first character is a character class such as `[\\\/]`, then PCRE typically does some optimizations (like just using a typical `indexOf()`). But if the PCRE engine sees a group, like `(?> ... )`, then it doesn't do the same optimizations, so it really depends on what you're trying to do.

**Comment by firasdib** [comment]
This tracker is only for bugs and features with regard to regex101. Please move your questions to the appropriate forum. Thanks.
