### ISSUE TITLE
Change title with curl

### ISSUE THREAD

**Issue by Biblos0** [firasdib/Regex101#1580]
## Question
I have many regex, and now I would like to change their title.

I am not familiar with curl (Win10). If a unique ID is "zzzzzz" I was just thinking of making a .bat, like this:

curl -u xxxxxx@gmail.com: yyyyyy https://regex101.com/connect/google
curl -X PUT -H "Content-Type: application/json" -d '{"title":"[02] Test"}' "https://regex101.com/api/user/history/zzzzzz/1/title"
...

If I enter:
curl -u xxxxxx@gmail.com:yyyyyy https://regex101.com/connect/google

it seems accepted.

If I enter:

curl -u xxxxxx@gmail.com:yyyyyy https://regex101.com/connect/google -X PUT -H "Content-Type: application/json" -d '{"title":"[02] Test"}' "https://regex101.com/api/user/history/zzzzzz/1/title"

The identification seems accepted, then I get:

<! DOCTYPE html>
<html lang = "en">
<head>
<meta charset = "utf-8">
<title>Error</title>
</head>
<body>
<pre>Bad Request</pre>
</body>
</html>

What's wrong?

**Comment by firasdib** [comment]
This tracker is only for bugs and features with regard to regex101. Please move your questions to the appropriate forum. Thanks.

**Comment by Biblos0** [comment]
Isn't the API a feature of regex101.com ? You wrote about it in the blog and I try to apply what you wrote.
