### ISSUE TITLE
This tracker is only for bugs and features with regard to regex101. Please move your questions to the appropriate forum. Thanks.

### ISSUE THREAD

**Issue by Biblos0** [firasdib/Regex101#1583]
This tracker is only for bugs and features with regard to regex101. Please move your questions to the appropriate forum. Thanks.

_Originally posted by @firasdib in https://github.com/firasdib/Regex101/issues/1580#issuecomment-837037954_

Isn't the API a feature of regex101.com? You wrote a lot about it in the blog, and I try to apply what you wrote.

**Comment by firasdib** [comment]
The API is not intended for external use, even though it can be used. I don't actively support that, and don't document breaking changes, so use it at  your own discretion! 

You will have to include the cookie created by the authentication request in order to proceed.

**Comment by Biblos0** [comment]
OK.
