### ISSUE TITLE
Add minimap

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#1584]
## Feature
Add a minimap to the side of TEST STRING.

There was an interesting implementation done by https://github.com/alterfan/minimap/, although it appears to have a few bugs. One of the nice features was that clicking the minimap allowed it to be moved from the left to the right of the codemirror object.

Screen real estate would need to be considered, especially on mobile, but it would help visualize where matches occur within the text.

**Comment by firasdib** [comment]
I would have a hard time making this work with the way the text highlighting is implemented unfortunately. Perhaps when codemirror 6 is released this will be easier.
