### ISSUE TITLE
Error running service worker

### ISSUE THREAD

**Issue by david-williams-mpp** [firasdib/Regex101#1585]
## Bug Description

The service worker encounters an error

`Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://regex101.com/static/assets/.DS_Store","status":403}]`

### Reproduction steps

1. Open developer tools and go to Application tab
2. Navigate to regex101
3. Observe error in sw.js (also in console)

### Expected Outcome
Service worker runs without error

### Browser
Edge latest

### OS
Windows 10 latest

**Comment by firasdib** [comment]
Try again, should be fixed now!

**Comment by david-williams-mpp** [comment]
Holy crap! That has to be a record for fastest issue resolution ever! Thanks a lot 👍
