### ISSUE TITLE
LD Unicode Property Is Not Recognized For Java 8

### ISSUE THREAD

**Issue by musiKk** [firasdib/Regex101#1590]
## Bug Description

Entering a Regex containing `\p{LD}` says

> \p{LD} This script is unknown/invalid

### Reproduction steps

Switch to Java 8. Enter the aforementioned Regex.

### Expected Outcome

Does what Java would do. LD matches letters and digits. It seems proprietary and as far as I can tell completely undocumented.

### Browser
Chrome 90

### OS
Mac OS 11.3.1

**Comment by firasdib** [comment]
Thanks. I'll add it.
