### ISSUE TITLE
Sign in with GitHub does not work

### ISSUE THREAD

**Issue by CallumWatkins** [firasdib/Regex101#1591]
## Bug Description
Sign in with GitHub does not work.

### Reproduction steps
1. Click sign in
2. Click GitHub

### Actual Outcome
I'm redirected back to the homepage with this URL:
https://regex101.com/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider

### Browser
Chrome 90.0.4430.212

### OS
Win10

**Comment by firasdib** [comment]
Should be back in business! Thanks for notifying me.
