### ISSUE TITLE
SSL certificate expiration

### ISSUE THREAD

**Issue by S-Mann** [firasdib/Regex101#1592]
## Bug Description
The SSL certificate for [regex101](https://regex101.com/) has expired.

### Reproduction steps
Try loading [regex101](https://regex101.com/)

### Expected Outcome
SSL certificate is valid and https works.

### Browser
Chrome 90.0.4430.212

### OS
Windows 10

**Comment by firasdib** [comment]
Should be back in business! Thanks for notifying me.
