### ISSUE TITLE
No graphical representation for newline matches under certain circumstances

### ISSUE THREAD

**Issue by AlejandorLazaro** [firasdib/Regex101#1593]
## Bug Description

While using a regex to validate matches, I determined that there are times when a newline matches a given regex and appears in the Match Information display, but the Test String view has no graphical change to denote a match for those otherwise empty lines.

### Reproduction steps

Link: https://regex101.com/r/M0uzWr/1

Video: 
https://user-images.githubusercontent.com/1635011/120051277-d5733000-bfd4-11eb-8dc6-71a4da28e8c0.mov

Regex Expression: `^(\n|[^a-z-].*\n)`

Test String:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile RestoreTask/requirements.in

--index-url https://foo.google.com/simple

agent-diagnostics==0.1.1
    # via -r RestoreTask/requirements.in
google-certifi==1.1.1
    # via pytoolkit
urllib-ext==4.0.2
    # via knox-image-lib
unixcommand==0.8.3
urllib-ext==2.0.3
urllib3==1.26.5
videogenerator==0.2.2
wrapt==1.12.1


```

### Expected Outcome

I expect to see some graphical indicators that show a match, even for characters that don't have traditional space usage.

### Browser
Safari 13.1.2

### OS
macOS Catalina 10.15.6

**Comment by Ouims** [comment]
Seems to be on purpose, however if you use the option to visualize whitespace etc, there is a glyph used for the newline, and it would be possible to highlight that character, maybe that's a bug.

You said there are times where it doesn't do it, implying there are times where it does. Are you talking about when the newline is not the last character to match?
If you use /ab\nz/ on the string "ab\nz" where \n represent the newline, the highlight occurs on the first line until the end of the textarea before highlighting "z", to illustrate that the match is on multiple lines, I can't seem to find a case where it does highlight the newline on a single line match, do you have an example? https://regex101.com/r/M0uzWr/4

**Comment by firasdib** [comment]
Yeah, this makes sense. I think adding a small indicator (2px line) to show there is infact a match there is enough. This happens because the newline occupies no width in the document, but is in fact a matched character. This is unlike empty groups, which match null, and are handled separately.

Thanks for your feedback!
