### ISSUE TITLE
The "Python 2.7" name is misleading

### ISSUE THREAD

**Issue by nedbat** [firasdib/Regex101#1594]
## Bug Description

The Python flavor is called "Python 2.7", but it is not limited to 2.7.  These days, 2.7 is considered ancient and bad.  Python people coming to regex101.com see "2.7" and wonder if it will work for their Python 3 regexes.  It will, so the label should be changed.  Perhaps just label it "Python" until finer distinctions are available?

**Comment by salty-horse** [comment]
It's also misleading because the `re.ASCII` flag doesn't exist in 2, and regex101 allows enabling it.
Conversely, in Python 3, the `re.UNICODE` does nothing, but regex101 allows toggling it.

**Comment by swfarnsworth** [comment]
I concur with nedbat. I help curate the resources page for pythondiscord.com, and while I plan to feature regex101 regardless, it would be less confusing for our users if the Python flavor were simply named "Python".

Regardless, thank you for making such a useful website!

**Comment by firasdib** [comment]
Thanks for the feedback. The python flavor needs some love, and I will hopefully be able to spend some time looking into a better solution in the near future. I'll remove the 2.7 part for now.
