### ISSUE TITLE
Documentation spelling issue with Character Class Intersection

### ISSUE THREAD

**Issue by madebyjeffrey** [firasdib/Regex101#1598]
## Bug Description

In the documentation for Character Class Intersection, broader is spelled incorrect: 

"Matches the intersection between the two character classes. Useful if you want to white or blacklist certain characters from a *borader* class." 

### Reproduction steps

1. Go to quick reference.
2. Select Character Classes
3. Click on Character Class Intersection
4. Find the spelling error near the end of the description.

### Expected Outcome

Should be spelled "broader".

### Browser
Edge 91

### OS
Windows 10 (21H1)

**Comment by working-name** [comment]
Hello! Thank you very much for your report. It will be taken care of.

**Comment by firasdib** [comment]
Thanks!
