### ISSUE TITLE
Javascript generate code Bug for complete match

### ISSUE THREAD

**Issue by jobdiogenes** [firasdib/Regex101#1600]
## Bug Description
In generate code for Javascript,  to refer a full match, are using $0, but need to be $&

### Reproduction steps 
express any expression with some groups.  with replace
For example: /(good|bad)(work|habits)/gm
in replace use:  Some $0 are found

### Expected Outcome
The generate code for javascript need to replace $0 with $& to work.

### Browser
 any.

### OS
any

**Comment by working-name** [comment]
HI @jobdiogenes,

Unless I'm mistaken the codegen does not suggest any replacement string, it just copies what you had in the field. If you leave the field blank, the replacement string in code will follow suit.

Maybe it was leftover from a different flavor?

**Comment by working-name** [comment]
@jobdiogenes what's the word on this?

**Comment by working-name** [comment]
Please feel free to update this with a way to reproduce it. Closing for now.
