### ISSUE TITLE
Add API to generate code

### ISSUE THREAD

**Issue by x0f5c3** [firasdib/Regex101#1602]
## Feature
It would be extremely helpful to have an api method added that would generate code from a regex provided.

I'm currently at a point where I have to translate 1000 regex strings from Python to Rust 
and having an api to do it by script would be awesome.

**Comment by working-name** [comment]
Just FYI: the code generator doesn't change your regex string - if it doesn't work in the tester it will just as much not work in the codegen as well. It does not correction, no translation.

**Comment by firasdib** [comment]
The code generation happens on client side, so there is no way to do that unfortunately.
