### ISSUE TITLE
Clarify API for page request in wiki

### ISSUE THREAD

**Issue by michaelmior** [firasdib/Regex101#1604]
The wiki states that the URL format for requesting a page of results is /api/library/**page#**. Without an example, I assumed that this meant something like `/api/library/page1` instead of `/api/library/1` In retrospect, that probably should have been clear, but given that someone else may have the same misunderstanding, an example or a clarification might be helpful here.

**Comment by working-name** [comment]
Done.

**Comment by michaelmior** [comment]
Thanks! I had a scan over the wiki again and I think I wouldn't have made the same mistake reading what's there now :)
