### ISSUE TITLE
Multiple text string inputs - with reasoning as to why the alternatives are inconvenient

### ISSUE THREAD

**Issue by hi2u** [firasdib/Regex101#1608]
## Feature

I know this has come up in many other tickets, but the suggestion is always to "just do it the harder way".

Something that I've found frustrating in every regex tool I've tried over the last ~20 years is that they only let you test one sample at a time, and require fiddling with the global/multiline flags when you want to test multiple.  99% of the time I just want to quickly test a bunch of sample strings all at once, and in real-time as I'm editing it all, which won't be using these flags.   

Yes I know that I can:

* Fiddle with the global and multiline flags... but I've always just found this confusing... I want to use the exact same flags in my code that I use in your tool, without having to think about and translate the differences between how I was testing vs actually programming in my project.  It would be so much nicer to just simply have a bunch of separate `<textarea>` inputs on screen that are clearly separated, and without me having to think about fiddling with flags inconsistently. 
    * It would also allow for visually lining up the "MATCH INFORMATION" over on the right with each input sample, rather than having to mentally correlate each line in the one-and-only textarea with "Match X" numbers.  You could even make each input textarea's background color red or green depending on whether that sample matches or not... max efficiency!
    * Plus when you're testing regexes where each sample does actually include internal newlines, things get even more confusing/unusable.  I'm not even sure if that's possible right now at all? (hurts my brain to even think about haha)
* Use the unit tests: this is a cool feature, but for quick testing of a few strings, it's too cumbersome to set up, and also having to click "Run tests" every type I change a single character anywhere is tedious compared to the alternative: I just want to see results instantly as I type my edits, like you do on the main "Match" screen.  

Anyway, up to you if you want to add this or not... it will drastically improve the efficiency and usability of the tool, and help you stay on top long term.  A lot of the time I start out using your tool, and then just give up and write some code to loop over an array of test samples, because I don't want to deal with the flag inconsistencies and confusion that I get with all of these tools that only have a single input for samples.  I'd love to just be able to quickly use your tool in this efficient manner rather than having to go build/release my own just over this one usability difference.

See the book on interface design called "Don't make me think"... relevant here!

Thanks for making the tool!  It's great!  (but could be even greater with this minor change 😄 !)   Hope this all doesn't sound too ranty... it's just something that many people have been wanting, and I've been wanting 20+ years... so seems like a no brainer to me!

**Comment by hi2u** [comment]
And just to add... I've thought about posting this ticket in the past, but today I've been working on a regex where enabling the global/multiline flags was causing problems.  Thinking it was wrong: I spent a bunch of time trying to fix my regex, only to then turn the flags off and remove all samples but one, and it turns out my regex was fine.  

My only problem, again, was this additional confusion that comes with having to turn these flags on and off, even though I won't actually be using them at all in my real code.

**Comment by working-name** [comment]
It might be nice to have, but in my mind I can't get over the fact that I would have to paste each case in a new box... it's much faster to paste it all in 1 box and then use `/m` with `^` and `$`.

It almost feels like you'd be better off copy pasting in in the unit tests interface - same amount of copy pasting and switching between software to grab the string.

Anyway that's just my take on it :)

Related: #359, #282, #195, #1009, #795

**Comment by hi2u** [comment]
> It might be nice to have, but in my mind I can't get over the fact that I would have to paste each case in a new box... it's much faster to paste it all in 1 box and then use /m with ^ and $.

You wouldn't have to do that.  There would be nothing stopping you continuing to do that if you like.  Just carry on doing it that way in the 1st sample box.  

If you don't want the multiple boxes taking up screen space, maybe make the 2nd+ ones hideable/optional.

But for the rest of us (as also explained in many of those other ticket numbers, and again here), having separate inputs and not having to fiddle with the flags would be much easier to use.  This can waste a lot of time, e.g. like today when I wasted a bunch of time trying to fix a regex that already fine, but only making me think it was broken due to flag inconsistencies/confusion.

Plus the additional confusion I mentioned when each sample contains internal newlines.

> It almost feels like you'd be better off copy pasting in in the unit tests interface - same amount of copy pasting and switching between software to grab the string.

* It's too fiddly/tedious to bother with.  Not sure why they're minimized by default.  The expanded version just wastes a lot of screen space anyway... not really sure why it even needs to expand/collapse anyway?  If it was simply just a fixed table that wasn't fiddly then it would be more usable at least.  I'm not sure why simple tables with columns have gone out of fashion in modern design, it's a huge usability regression, haha.
* It doesn't show the matched parts.
* You have to click "Run tests" every time you make any change - makes sense if you have 1000s of samples, but like 99% of the time I normally only have about 3-5 I'm testing, and just want instant results as-I-type like the match screen gives.

Anyway, obviously there's a bit work of work in adding this improvement, but I don't see any downsides that would reduce functionality for people who don't use it.  It's just a good usability improvement and will help keep the tool popular long term.

But if it's there... I reckon most people will use it the majority of the time, because it's so much easier that dealing with cognitive overhead of inconsistent flag flipping in different contexts.

**Comment by firasdib** [comment]
My stance on this hasn't changed: this is too much work for a niche feature.

FWIW, the unit test auto run.

**Comment by working-name** [comment]
Closing for now, please comment should you deem it should stay open.

**Comment by northamerican** [comment]
this would be useful for my use case, testing many different strings against a regex i'm fine tuning with several groups.

**Comment by firasdib** [comment]
@northamerican Have you tried the unit testing feature?

**Comment by northamerican** [comment]
@firasdib i have, but for the reasons described here: https://github.com/firasdib/Regex101/issues/1608 in addition to not seeing what each group has captured as i fine tune the regex, it isn't feasible. 

related: https://github.com/firasdib/Regex101/issues/795

**Comment by CarlitoGil** [comment]
Hi.
I would also like to add my opinion to this, as I very much agree that this would be very helpful.

My input, in production, does not contain "`\n`".
I use patterns like this:

```
^[A-Z]+[ ]          # get some letters followed by a space.
(?![^([{<]*         # look-ahead, but not inside comments.
\b(20|19)\d{2}\b    # no year found.
)                   # blah...
```
But when I develop and test in Regex101 I have to add "`\n`" to the negated character class.

```
(?![^([{<\n]*         # look-ahead, but not inside comments.
\b(20|19)\d{2}\b    # no year found.
```

Or this:
```
\((?<c>[^()\d]+)\)  # get comments between parentheses.
```
Since there the right parenthesis could be missing, I must develop like this:
```
\((?<c>[^()\d\n]+)\)  # get comments between parentheses.
```

The "`\n`" is not necessary or desired in production... or then somebody will wonder why it is there.
I'd have to remove each "`\n`" before copying the pattern, many more than in these examples.
...then I have to realign the comments.
And, if they paste that back to Regex101 without "`\n`" it might fail on their Test String. Gotta tell them to add them back.


Doable? Yes. But it seems inelegant that we have to develop for and around the tool's limitations, and kinda thinking that it's a hassle.
Don't get me wrong. Regex101 is hand-down the best there is. But I miss the "line by line" feature.

Could I use Unit Tests? Yes and no. They are not anywhere nearly as useful to me as visualizing the captured groups on many lines. Plus, adding so many strings manually to the unit tests is just too much.

Also, while developing, before being able to add unit tests, I have to figure out what are the best patterns to match by analyzing a large number of cases, and I would have to change the unit tests back and forth, and mix the valid tests with sample strings that haven't been determined if they should match or not, or if they should stay as unit tests, then forgetting which are which.
The samples should stay separated in Test String until they are ready for Unit Tests.


I don't really get the argument that this would be hard to implement. Just split the Test String by "`\n`" and loop through them to feed the regex.


Please reconsider adding this feature. Seems simple enough to implement, and obviously, some users care about it.

Please let me know if I can explain further.
Thank you for Regex101.
Regards.

**Comment by edswangren** [comment]
> It almost feels like you'd be better off copy pasting in in the unit tests interface - same amount of copy pasting and switching between software to grab the string.

--- Unit test UI ---
  click add new (1)
  click to expand (2) 
  click to enter text area (3)
  paste (4)
  edit (5)
  click to collapse (6) and scroll after 3 or so as your list is full.

--- multi line input text area ---
press enter (1)
paste (2)
edit (3)

I'm searching for the value in your unit test UI and not finding any. 

This isn't to mention I can see at a glance every issue in detail using your default UI while those cards will require more tedious clicking an expanding and collapsing and scrolling.

adding modifiers to the regex is not 1:1. I'm trying to understand the logic in this. It's the difference between a practiced and skilled terminal user and your typical web dev who knows git as three buttons and writes a UI for cron jobs and simple processing tasks. 

I'm also annoyed in general atm so all that said thank you very much for providing this tool that I do in fact find very useful and at no charge to me. really, thanks all. criticism given with love and respect :D

Oh and for the love of God expand those test case rows by default jfc I can't even with those.

**Comment by Calorion** [comment]
> But when I develop and test in Regex101 I have to add "`\n`" to the negated character class.

This is my specific issue. I'm developing Siri Shortcuts, and I leave RegEx101 links in comments so users can understand what I'm doing. I'm left with either taking the `\n`s out, making the linked regex different from the one in use, or leaving them in for no other reason than to avoid confusion.

**Comment by firasdib** [comment]
Multiple text strings will be supported in the next release.
