### ISSUE TITLE
Katakana unicode range is incomplete

### ISSUE THREAD

**Issue by jhadwen** [firasdib/Regex101#1609]
## Bug Description

When specifying a Katakana unicode range in the regex, the range appears to arbitrarily stop matching at U+30FA, even though U+30FB to U+30FF are characters specified in the Katakana unicode block (and commonly used).

https://en.wikipedia.org/wiki/Katakana_(Unicode_block)

Somewhat related, I don't quite understand why ECMAScript flavor doesn't recognize the unicode range at all, given that it's supposed to be using the browser's regex engine?

### Reproduction steps

https://regex101.com/r/eRz4G2/3

### Expected Outcome

Should match. A possibility is that this is a bug within a dependency (e.g. PCRE) but given the inability to compare against ECMAScript (within the tester) I though it prudent to raise the issue here first.

### Browser
Chrome 91.0.4472.106

### OS
Windows 10

**Comment by firasdib** [comment]
I just tried this out, and can't reproduce the expected outcome.

If you run this in javascript `/^\p{Katakana}*$/u.test('カタゾー')`, firefox throws an error (you need `u` flag for unicode properties btw).

**Comment by jhadwen** [comment]
Yes that produces the same error in Chrome, working version would be  `/^\p{Script_Extensions=Katakana}*$/u.test('カタゾー')` but that doesn't work in the tester https://regex101.com/r/0CydFF/1 (any flavor) because there is an implementation difference in terms of defined property names  (.NET is IsKatakana for example).

It's seems that PCRE(2) has the propertyname/value as just 'Katakana', or at the very least has implemented something that works with that property value (as 'カタゾ' matches fine https://regex101.com/r/2d0bsm/1).

I could speculate that PCRE attempts to mimic ECMA2018 unicode properties in implementation, and the range that's been coded isn't the full unicode block or has been taken from elsewhere. I don't really want to dive that deep into the rationale and if that's the case, then the tester is replicating the fuctionality of PCRE and the bug is third party.

This does however highlight again why these property ranges don't work on the ECMAScript flavor https://regex101.com/r/0CydFF/2

**Comment by firasdib** [comment]
Please use the unicode flag in the editor for evmascript. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by firasdib** [comment]
Feel free to file an issue with the PCRE maintainer if you believe there is a bug in the library. I have not modified that behavior myself.

**Comment by jhadwen** [comment]
Thanks, makes sense and works as expected under ECMAScript.

Looking deeper the answer lies within https://www.unicode.org/reports/tr24/tr24-31.html#Multiple_Script_Values which uses this very character as an example. It's seems that U+30FC is so "common" that it's marked as "Common", this would mean that in order to match it would needs something like Katakana | Common.

The reason it works in the ECMAScript test is that 'Script_Extensions=Katakana' is different to 'Script=Katakana' which is the actual equivalent of PCRE's Katakana. 

I haven't quite worked out what the set 'Script_Extensions=Katakana' is because it's not defined in https://unicode.org/Public/UNIDATA/ScriptExtensions.txt. Regardless, PCRE doesn't support it.

Thanks for the help and sorry for troubling you.
