### ISSUE TITLE
Bug Regex101

### ISSUE THREAD

**Issue by Regex118** [firasdib/Regex101#1610]
^[A-Za-z]*\sflies\s[A-Za-z]*

That was the regex code used to find what animals fly
When I removed the A-Z near the end the code worked perfectly and I'm not sure why.

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by working-name** [comment]
Hello there! This is a bug reporting platform rather than help with regexes. Please join us on IRC and ask the question there (the live help icon is the 6th round icon from the top). It's free, doesn't require registration, and you get to chat live.

Thank you!

**Comment by Regex118** [comment]
Im actually new to regex so I was wondering what the issue was.

**Comment by Regex118** [comment]
Is there anyone who can help me out?

**Comment by working-name** [comment]
Sure!

Step 1: go to https://regex101.com
Step 2: click Live Help button on the left sidebar
Step 3: follow instructions to join the live chat channel
Step 4: ask your question by answering this question: What what is your source text and what should regex do with it?
Step 5: be patient and wait.

![click-me](https://user-images.githubusercontent.com/16505052/124529096-c18ecb00-ddd7-11eb-9939-29e31f60fc51.jpg)

**Comment by Regex118** [comment]
Ok, Thank you!
