### ISSUE TITLE
Regex star and plus

### ISSUE THREAD

**Issue by Regex118** [firasdib/Regex101#1612]
What is the difference between the star and plus in regex?

**Comment by working-name** [comment]
Please understand that this is not a forum for regex help, it's a platform for issue reporting regarding the site. That being said, you are double encouraged to join us via IRC for live (as in you type now, we read now) help, as I replied in your other bug report #1610.

Regex101.com has a section on the right sidebar called Quick Reference. It provides an explanation for almost all regex it, items. You can also simply try using the items and read the explanation on the right hand side which updates based on your regex. Then there's always good olde google to search for stuff: https://stackoverflow.com/questions/10763820/difference-between-and-regex

**Comment by working-name** [comment]
Closing for now, hope you decided to pay us a visit on IRC 😄
