### ISSUE TITLE
pattern cause website to crash \Q.

### ISSUE THREAD

**Issue by moaaz-nashawi** [firasdib/Regex101#1614]
The website crash when I tried to use this Pattern with Java 8 Selected

The pattern cause the crash is:  \Q.

once you write it the website crash.

**Comment by firasdib** [comment]
Could you open your console and take a screen shot of it? Does it happen in incognito mode?

**Comment by firasdib** [comment]
I've located the issue, I'll fix and push it live asap.

**Comment by Shahinbagerzadsaid** [comment]
@OnlineCop

**Comment by Shahinbagerzadsaid** [comment]
![Uploading 20210712_221309.jpg…]()
