### ISSUE TITLE
Localized Regex 101 fails to run

### ISSUE THREAD

**Issue by transmuse** [firasdib/Regex101#1616]
## Bug Description
when running .```./runLocalRegex101.sh``` the wget (recursive) runs forever and never ends.  

### Reproduction steps

```bash
git clone https://github.com/ibaaj/Regex101.com-offline-app.git regex101
cd regex101
./runLocalRegex101.sh
```
### Expected Outcome
Server starts running and is accessible via default port (8000)

### Browser
Include browser name and version
N/A (service never starts)
### OS
Include OS name and version
MacOS (Catalina)

**Comment by firasdib** [comment]
That is a unaffiliated third party. I do not maintain nor encourage its use. I advise you to stick to the website. If you want it as a standalone app, you can install it through chrome.

**Comment by transmuse** [comment]
@firasdlb  Thank you for the prompt response.   I completely respect your concerns.  I have chosen this option due to the fact that the data I put into the tool is proprietary and must remain secret.   Can I be assured that the Chrome app will adhere to this requirement?  Thank you again for all of your hard work on this. It is an incredible tool I rely on regularly. I would just use the website if I could!  Thank you!

**Comment by firasdib** [comment]
@transmuse None of the information you input is shared with any third party unless you hit the save button. The website runs on your client only, and it functions offline. Load the site, pull your internet cord, and continue to use it.

**Comment by transmuse** [comment]
@firasdlb  Thank you for the clarification.  It's not practical for me to "pull my internet cord" but what I'm hearing is that no data is sent to a server to process the request.  If that's true, I should be able to load the site and use it without fear of sending data anywhere.   Please correct me if I'm wrong.   Again, thank you for such a great tool!

**Comment by firasdib** [comment]
@transmuse You're correct.

You can disable internet for a given website in chrome, too, if you'd like.

**Comment by transmuse** [comment]
@firasdib  Thank you!  You've given me a new way to look at things!   I'll still have to get approval from my InfoSec team due their rather aggressive concerns for secrecy, but I hope this thread will help them allow me to use it.   I'll also look into the disabling of internet for a given website.  I did not know that was possible.   Great information.  Thanks.
