### ISSUE TITLE
Inactive link "open regex in editor" when regex is opened in new tab from Regex Library

### ISSUE THREAD

**Issue by anthonyaxenov** [firasdib/Regex101#1618]
## Bug Description
Inactive link does not allow to open somebody's regex in new tab.

### Reproduction steps
Scenario 1 (bad):
1. Open Regex Library
2. Right click on any regex and choose "Open in new tab" (or just click mouse wheel) -- a new tab with some data about regex will be opened
3. Move mouse over the "open regex in editor" -- style of that link and system cursor will not change, also the link is not clickable.

Scenario 2 (ok):
1. Open Regex Library
2. Left click on any regex -- new fullscreen modal with some data about it will be opened
3. Right click on the "open regex in editor" link and choose "Open in new tab" (or just click mouse wheel) -- and fully functional editor with that regex will be opened in new tab

### Expected Outcome
The "open regex in editor" link should be clickable in scenario 1.

### Browser
Google Chrome 91.0.4472.114 x64

### OS
Ubuntu 20.04.2 LTS

**Comment by firasdib** [comment]
I'm not sure I follow/can reproduce. Could you record it?

**Comment by firasdib** [comment]
What happens if you hit `ctrl+shift+r` on the library entry that you opened in a new tab?

**Comment by firasdib** [comment]
Thanks for your report. This was a tricky race condition, but its fixed now.
