### ISSUE TITLE
Task 1 can't continue

### ISSUE THREAD

**Issue by TechCraft09** [firasdib/Regex101#1619]
# Task 1 can't continue
### Task
1. Word Boundaries

### Bug Description
`word` doesn't work. Error: "The string is case insensitive! `WORD` and `wOrD` should match as well as `word`."
`/word/` doesn't work. Error: "`/` An unescaped delimiter must be escaped with a backslash (\)"
`/word/` with escaped slashes doesn't work. Error: "You are not even matching word. Use the example given in the task description."

(There are no extra spaces)

If entered incorrectly you can't continue with the quiz.

### Reproduction steps
Type `word` and click Submit
Type `/word/` and click Submit

### Expected Outcome
If entered incorrectly you should be able to continue with the quiz.

### Browser
Firefox 89.0

### OS
Windows 10 (21H1 Build 19043.1110)

**Comment by firasdib** [comment]
You need to insert the correct answer in order to proceed with the quiz. The error message is trying to tell you what you're failing to match...
