### ISSUE TITLE
dot always matches new line

### ISSUE THREAD

**Issue by k-dovan** [firasdib/Regex101#1620]
## Bug Description
Dot matches new line functionanlity always on.

### Reproduction steps
`.*` catches new line always

### Expected Outcome
.* does not catch new line

### Browser
Firefox 90.0.1

### OS
Windows 10

**Comment by working-name** [comment]
Hello! 

What flags do you have on while testing this and which flavor? Please share a link if you have one.

**Comment by Mlkjhgf11** [comment]
Www

**Comment by Mlkjhgf11** [comment]
Www

**Comment by Mlkjhgf11** [comment]
Ww

**Comment by working-name** [comment]
@k-dovan if this is still an issue please help us recreate the issue so we can fix it. Closing for now.
