### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by martinjack** [firasdib/Regex101#1622]
![Снимок экрана от 2021-07-23 17-55-44](https://user-images.githubusercontent.com/11950689/126800919-aac11dc2-e9a9-4d4f-89c9-cf34a90a3cef.png)

**Comment by martinjack** [comment]
![Снимок экрана от 2021-07-23 17-55-44](https://user-images.githubusercontent.com/11950689/126800647-8d8eef35-2926-45bc-9853-ced4c846e6ac.png)

**Comment by 0xbalazstoth** [comment]
Yeah :(

**Comment by martinjack** [comment]
Cool, is fix
