### ISSUE TITLE
Critical error when tried to use any character range containing dash (-) in the middle

### ISSUE THREAD

**Issue by bartlomiej-k** [firasdib/Regex101#1633]
## Bug Description
When I tried to use [a-z] character range, the app crashed on typing the dash. Tried on three different browsers (Firefox, Edge, mobile Firefox) and two internet connections (wired with PiHole, wireless without PiHole). Turned off all plugins and Enhanced Tracking Protection mechanism in Firefox.

### Reproduction steps
Open the app and type [a- in the regular expression text area.

### Expected Outcome
The app does not crash and allows using character ranges (like [a-z], [0-9]).

### Browser
Firefox 90.0
Edge 91.0.864.71, Edge 92.0.902.67 

### OS
Windows 10 Home, build 19042.1052

### Stack traces
Edge:
![obraz](https://user-images.githubusercontent.com/49535453/128598570-9a61dfe9-cef8-49d3-ad17-07f507ae2550.png)
Firefox:
![obraz](https://user-images.githubusercontent.com/49535453/128598760-6b1f5212-5b80-4424-9749-0f852cf746e1.png)

**Comment by Kaporos** [comment]
Same for me !

**Comment by Kaporos** [comment]
I just tested to copy paste [A-z] in the field and it works

**Comment by exSnake** [comment]
Test string:
Id 987655 
Id 987656

test regex with **"Id [0"** adding dash after **0** will make regex crash

**Comment by firasdib** [comment]
Woah, sorry about that. Sloppy mistake, fixed now.
