### ISSUE TITLE
(Quick Reference) Java substitution using \0 \1 (backslash)

### ISSUE THREAD

**Issue by PAC-X** [firasdib/Regex101#1635]
## Bug Description
The Quick Reference for Java describes substitution (complete match contents) using the code \0, in addition to using $1 (contents of capture group 1). With the dollar sign it works, with the backslash it does not work.  

### Reproduction steps
Regex: `([0-9]{3,4})x([0-9]{3,4})`
Substitution pattern: \1 pix by \2 pix \0

Text String: 
1280x720
1920x1080
1600x900
1280x1024
800x600
1024x768

### Expected Outcome
1280 pix by 720 pix 1280x720
1920 pix by 1080 pix 1920x1080
1600 pix by 900 pix 1600x900
1280 pix by 1024 pix 1280x1024
800 pix by 600 pix 800x600
1024 pix by 768 pix 1024x768

### Browser
Chrome 92.0.4515.131 (Official Build) (64-bit)

### OS
Windows 10

**Comment by working-name** [comment]
Hello,

Thank you for the report!
