### ISSUE TITLE
Is there only a single public library and not personal private libraries?

### ISSUE THREAD

**Issue by ScottChapman** [firasdib/Regex101#1636]
## Question
I'd like to be able to curate my own regex's without having to contribute them to a public library (some might be publicly useful, but many would not).

**Comment by working-name** [comment]
Hello there,

Yes, that's correct, Library is a publicly accessible repository of regexes. You can still curate own regexes using the same tools but they go under "my regexes", or if you wish you can dedicate "my favorites" to become your personal library.
