### ISSUE TITLE
This would be an amazing feature. Just tried to convert PCRE2 to ECMA.

### ISSUE THREAD

**Issue by Abdui68** [firasdib/Regex101#1640]
This would be an amazing feature. Just tried to convert PCRE2 to ECMA.

_Originally posted by @angusryer in https://github.com/firasdib/Regex101/issues/1629#issuecomment-907486823_

**Comment by working-name** [comment]
Thank you for the vote! Please use comments in the original thread that way we keep it all in one spot 😉
