### ISSUE TITLE
Focus on the "Test string" field instead of the "Regular expression" on starts

### ISSUE THREAD

**Issue by tnthhp96** [firasdib/Regex101#1643]
## Feature
Maybe since I'm a beginner, I tend to start by looking at the test string before I can come up with any RegEx. So if the focus is on the `Test string` field at the beginning, I can paste the text right away, then go on with the expression. Also it appears there's a bug that sometimes prevents me from typing into the `Regular expression` field unless I first type something in the `Test string` field.

**Comment by working-name** [comment]
Hello there,

Good suggestion. As far as the bug is concerned, can you let us know which browser (and its version) you're using and maybe see if there's any errors in the console when you happen upon an unresponsive regular expression input field?

**Comment by tnthhp96** [comment]
Currently, I cannot reproduce the issue. Maybe the developers have fixed it recently?

**Comment by working-name** [comment]
Closing this as it seems it was resolved. Please feel free to update this ticket should you bump into it again.
