### ISSUE TITLE
Provide an easy way to override fonts

### ISSUE THREAD

**Issue by intrnl** [firasdib/Regex101#1644]
## Feature

I have slight difficulties reading both the interface font (Open Sans) and code font (Source Code Pro), and I'm sure that there are many who would like the ability to use their own fonts so they can read comfortably while messing around with regex.

At the very least, I think providing `--font-interface-override` and `--font-code-override` as CSS variables would be good enough as a starter.

**Comment by intrnl** [comment]
Currently, I have this custom CSS. It works for sure, but due to the nature of CSS modules then I would have to keep modifying the custom CSS whenever the styling updates.

The styling might not change as often, but it still doesn't address that we'd have to dig through inspector just so we can use our fonts.

```
body, html {
  font-family: sans-serif;
}

._1UVmI {
  font-weight: 400;
}

.CodeMirror,
.RJ8Yc,
._1TmfU, ._2NHf3,
._1oJra, ._2eKh2, ._2GUpi, ._2NAWB, ._3ymFJ, ._23E7Q, .HWkrS,
._20RCA,
._3CIoN {
  font-family: monospace;
}
```

**Comment by firasdib** [comment]
The new release will use css variables and this will be adjustable by the user.
