### ISSUE TITLE
Option to disable keyboard shortcuts

### ISSUE THREAD

**Issue by eugenesvk** [firasdib/Regex101#1646]
## Feature

I use <kbd>⌘</kbd><kbd>1</kbd>/<kbd>2</kbd> for tab navigation, and the default Regex101 shortcuts use it for something that I never use — switching between functions, but they block my convenient switching back&forth between tabs.
Would you please add an option to **disable** these **shortcuts** completely so they don't interfere (even a crude option to disable **all** the shortcuts is fine)?
Thanks

**Comment by firasdib** [comment]
This has been implemented in the new release.

**Comment by disraelig444** [comment]
@[/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/gm]() `-$$#`
