### ISSUE TITLE
hint for https://regex101.com/quiz

### ISSUE THREAD

**Issue by arashnz** [firasdib/Regex101#1658]
## Question
Hello,
are there any hint for https://regex101.com/quiz?
some of them is really hard for me to solve so I'm looking for help or hints for some of them.

**Comment by mwagnerEE** [comment]
I think maybe a "topics covered in this question" may be a good way to point to what we should do for homework. Like you said the later questions are harder and require knowledge of the topics before them. It's nice to have the reference there but it's like giving someone a textbook but with all the chapters in a random order. I could be trying to struggle to learn calculus (control verbs) before I learned algebra (alternates).

**Comment by firasdib** [comment]
I would appreciate if someone could help me add appropriate hints to the quiz tasks, as I do not have enough time on my hands to go through it all. One idea could be to add links to regular-expressions.info

**Comment by LaniakeaS** [comment]
> Hi @shahreahang the quiz is meant to teach regex fundamentals in an interactive and possibly fun way. There are no hints outside of what the quiz itself provides.
> 
> If they're really hard then it's probably because you may not yet grasp the concept that's required to solve that particular task. This would be the prompt to get you to do some homework and try to fill any gaps in your knowledge before trying the task again.
> 
> In addition, if you can't solve the earlier tasks, it's highly unlikely that you'll be able to solve the later ones because they get increasingly more difficult as you advance, and since regex knowledge builds upon itself you'd be dealing with even more gaps in knowledge.
> 
> While things definitely get competitive, there's no "cheat sheet" that I know of to solve a task or get the shortest answers. And I hope there won't be one because that would ruin the point of the quiz - to get you thinking about and playing with regex until you understand it.

well... I strongly disagree. One of the most import thing about the education is guiding. There has to be something that can teach you. If nothing tells you how to improve after your long-time thinking, it will take a significant time to drag you to get improvement, which is, I think, really unnecessary.

Please remember, there are large amount of people between the ones who wants to cheat and the ones who can figure things out in a quick time..
