### ISSUE TITLE
Enhancement for Python Substitution Bar

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#1664]
Please focus on the difference of replacement between the following two examples , one is `"\\n"`, the other is `r"\\n" `.

```python
>>> import re
>>> re.sub('b', '\\n', 'abc')
'a\nc'
>>> re.sub('b', r'\\n', 'abc')
'a\\nc'
```
When I type ``\\n`` in the Substitution Bar, the behavior is the same as second example ``re.sub('b', r'\\n', 'abc')``.
So I wonder if it is better to adding a `r"` marker to the left of the Substitution Bar? Just as the Regex Bar like.

**Comment by firasdib** [comment]
The substitution box does not work in accordance with raw strings, so it would not be correct to place it there.

**Comment by Serious54088** [comment]
> 



> The substitution box does not work in accordance with raw strings, so it would not be correct to place it there.

Oh, now I think I've puzzled out how regex101 handles replacement text.

I don't have to consider what characters the regex engine will eventually receive and how it handles the escape sequence.

As a user, I just need to remember that entering \t in subs box will always get a tab character, regardless of what regex flavor you use -- regex101 will handle the flavor differences for you.

This is very different than the RegexBuddy. In RegexBuddy, what you enter is what the regex engine receives.
