### ISSUE TITLE
Quick Reference: "Between 3 and 6 of a" example wrong

### ISSUE THREAD

**Issue by DywiTom** [firasdib/Regex101#1665]
### Bug Description
Highlighting of matches are wrong in the example.

### Reproduction steps
1.) Go to https://regex101.com/r/Wyn4gD/1
2.) Compare matches with the matches in the Quick Reference: "Between 3 and 6 of a".

### Expected Outcome
They should be the same.

**Comment by firasdib** [comment]
Fixed this and a few other entries. Its in the branch for the new major version, so might take some time for it to go live.
