### ISSUE TITLE
Add option for sidebar collapse preference

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#1667]
## Feature
Add a "Prioritize [left/right] sidebar when collapsing" option to [user settings](https://regex101.com/settings).

The user settings page has options for "Always collapse [left/right] sidebar."

If neither of those "always collapse" options selected and I shrink the window, the left sidebar collapses first. Then if I continue shrinking the window, right sidebar collapses next.

I'd like to have the right sidebar collapse first instead, and an option to allow user preference might be a good middle-ground.

**Comment by firasdib** [comment]
I suppose this could be added, but it doesn't sit quite right with me. The option seems "complicated" somehow. Is this problem a symptom of a larger issue? What is the reason you want that specific behavior?

**Comment by OnlineCop** [comment]
If it were simply changed to collapse the sidebars in a different order, then someone else may complain that they prefer it the original way.

At least with a user-facing option, they can select the style that works for them the best.

From what I can tell, the resizing/collapsing logic is already there; based off one more client-side preference/cookie, it would just choose which of those events to fire first vs. second. I don't believe there are more than just 2 sidebars that collapse, are there?

**Comment by firasdib** [comment]
I was curious why you wanted to switch order.

**Comment by OnlineCop** [comment]
I don't need/use the right sidebar (explanation, match info, quick ref) nearly as often as I need the left sidebar. I switch flavors, function (match -> substitution), or use the code generator much more often when helping in the #regex channel, since I often switch those (as new information comes in). When I have the window small enough where one of the sidebars collapse, I'd prefer the left one to be visible longer.

I realize that I could just toggle the right sidebar, but when I expand the window again, I like having the right sidebar visible again. It's just in the semi-compact layout that I prefer one sidebar over the other.

**Comment by firasdib** [comment]
I understand.

Personally, I feel this is such a niche use case that the added complexity might not be worth it. I will keep it in mind though, in case I find the extra time and energy to do it.

**Comment by firasdib** [comment]
I've looked into this a bit more @OnlineCop, but I don't think I can commit to this. It's quite a bit of work to make this work, since I reply on media queries in CSS, and I'd have to add some logic in the JS code to know which breakpoints to switch up etc.

It can be done, but the amount of work it surmounts to is not worth it at this point. If this is a pain point for many users, I might reconsider it, but at this point in time, I'll close.

**Comment by firasdib** [comment]
The new version will allow you to adjust the breakpoints :)
