### ISSUE TITLE
Test string pane won't highlight matches after browser window stays idle for too long

### ISSUE THREAD

**Issue by gabrielsanchez5985** [firasdib/Regex101#1669]
## Bug Description

regex101 does not highlight matches if window becomes active again after some time idle. Happens in Chrome. See the following image.

![image](https://user-images.githubusercontent.com/41697831/142481051-1bdc8a3c-6624-41e4-a636-7404ec8b32ef.png)

### Reproduction steps

Open regex101. Let window sit idle for quite some time. Go back to the window and enter any valid regex to match characters. You can see the matches in **Match information**, but **Test string** does not highlight matches.

### Expected Outcome

**Test string** should highlight the matches.

### Browser
Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)

### OS

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"

**Comment by working-name** [comment]
Hi @gabrielsanchez5985,

Can you by chance try to reproduce it and get a screenshot or dump of the console messages?

Just FYI: the app itself does not depend on a server once it's loaded in your browser. Essentially it works "offline", everything happens in your browser.

**Comment by firasdib** [comment]
Could you try an incognito window, does it happen there too? This sounds similar to a bug I had a few releases back. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by gabrielsanchez5985** [comment]
> Hi @gabrielsanchez5985,
> 
> Can you by chance try to reproduce it and get a screenshot or dump of the console messages?
> 
> Just FYI: the app itself does not depend on a server once it's loaded in your browser. Essentially it works "offline", everything happens in your browser.
> 
> Edit: I have 2-3 browsers open generally speaking, each with 2-3 windows with anywhere between 10 and 50 tabs per window. 2 of the browsers I use are chrome based. I also very seldom shut down, so I should have bumped into this issue by now if that's all it takes to reproduce it. Anyway, I'll keep an eye out on a vanilla chrome regex101 tab.

Log attached to this message. Nothing visually stood out on a quick scan.

[regex101.com-1637335520161.log](https://github.com/firasdib/Regex101/files/7571212/regex101.com-1637335520161.log)

**Comment by gabrielsanchez5985** [comment]
> Could you try an incognito window, does it happen there too? This sounds similar to a bug I had a few releases back. Vänliga hälsningar / Best regards, Firas Dib
> […](#)
> On 18 Nov 2021, at 20:38, Alan ***@***.***> wrote: ﻿ Hi @gabrielsanchez5985, Can you by chance try to reproduce it and get a screenshot or dump of the console messages? Just FYI: the app itself does not depend on a server once it's loaded in your browser. Essentially it works "offline", everything happens in your browser. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Will do.

**Comment by gabrielsanchez5985** [comment]
It happened in incognito window too.

![image](https://user-images.githubusercontent.com/41697831/142727579-fe648522-5569-4f28-824d-1a25038537a5.png)

No errors in log other than the ones I've sent before.

**Comment by gabrielsanchez5985** [comment]
It happens after you take the computer from hibernation mode from being idle too long, apparently.

**Comment by firasdib** [comment]
Interesting. I am currently working on a major rewrite, which might fix this. I haven't been able to reproduce, so best we can do is wait and see.

**Comment by gabrielsanchez5985** [comment]
Sounds good to me. Just glad to report for improving this great tool.

**Comment by firasdib** [comment]
I'm fairly confident I've resolved this issue now. Feel free to reopen when the release is out and you've had a chance to try it out.

**Comment by Flow2908** [comment]
I face the same issue. Regex matches are not higlighted by color in the regex101 tool. It's independet of the browser that I use. Even a restart of my computer did not change anything. Anyone has any hints on the cause or how I can fix it?

**Comment by working-name** [comment]
@Flow2908 does this happen after your browser has been idling or after your computer comes out of hibernation, or both?

I'm asking for clarification because there's a similar bug that was just resolved. It might require a hard refresh (clear browser's cache) to get the latest compiled assets vs the ones cached by your browser.

**Comment by Flow2908** [comment]
Thanks for your quick reply.

**Comment by Flow2908** [comment]
@working-name Thanks for your quick reply. I have tried to shut down and re-start my system and it didn't help. Now, that the computer was hibernate for a while, the highlights came back after simply having refreshed my browser. It seems that the hibernation helped fix the issue 👍

**Comment by working-name** [comment]
Quite interesting, I've been trying to recreate this but even after days of regex101.com being idle in chrome and in brave I have had no luck. I don't reboot often, nor does my computer hibernate, so that might be why I can't catch it in the act.
