### ISSUE TITLE
Unicode seems to be always on for PHP Regexes, at least for quantifiers {n,}

### ISSUE THREAD

**Issue by Ninili** [firasdib/Regex101#1670]
I was a bit dissappointed, when my rather complex regex here: https://regex101.com/r/Hu223Z/1
...didn't work out in PHP.

...after setting the repetition-counter to {3} instead of {2} (2 already matched just one occurance), I thought that this could be a multibyte-issue.

Only after adding "/u" in my PHP code, the regex behaved the same, and only after 2 occurrances, a match has been found.

So maybe the quantifiers with brackets don't yet behave like in PHP if not explicitly set in unicode?

**Comment by firasdib** [comment]
There are no implicit unicode flags being added, but this could be a Unicode discrepancy. I use UTF16, PHP uses UTF8. Looking at your regex, the php result makes little sense, unless it is treating your `äöüÄÖÜ` as multiple codepoints, and not one.
