### ISSUE TITLE
Task 8 Test 5 overchecking

### ISSUE THREAD

**Issue by cubruce1103** [firasdib/Regex101#1671]
## Bug Description

Task8 Test5 says I stripped too much, but at least for the "before<br>after" case I did not.

### Reproduction steps

`/<.*?>|<.*|\A.*>/gm
`
### Expected Outcome

beforeafter

### Browser

Chrome 96.0.4664.45

### OS

Win10 19042.1348

**Comment by firasdib** [comment]
Looks right to me.
