### ISSUE TITLE
Code generator generates wrong syntax for a capture group in Python

### ISSUE THREAD

**Issue by epiecs** [firasdib/Regex101#1672]
## Bug Description
Capture group generated for Python uses the wrong syntax

### Reproduction steps

1. use regex `(?<gr>test)` with string `test`.
2. use the code generator to generate the Python code

### Expected Outcome

`regex = r"(?P<gr>test)"` instead of `regex = r"(?<gr>test)"`

the `P` is neccesary for a Python capture group to work.

(https://stackoverflow.com/questions/10059673/named-regular-expression-group-pgroup-nameregexp-what-does-p-stand-for)

### Browser
Edge chromium

### OS
Win 11 enterprise, tested with Python version 3.10.0

**Comment by working-name** [comment]
Hello @epiecs,

The site doesn't parse your regex to make it correct based on the code generator you choose. If you do choose python as the flavor and attempt to use `(?<name>...)` you'll get an error in the explanation tab:

```
(? Incomplete group structure
) Incomplete group structure
```

You can get more info about capture groups and the way they show up in different regex engines here: https://www.regular-expressions.info/named.html

Hope this helps!

**Comment by epiecs** [comment]
Yes I see now, sorry to bother!

**Comment by working-name** [comment]
No bother at all. 👍
