### ISSUE TITLE
Better reading experience on [EXPLANATION]

### ISSUE THREAD

**Issue by MarvinXu** [firasdib/Regex101#1673]
## Feature
Improve reading experience on EXPLANATION section. 

Problems:
1. too crowded, too much words
2. hard to collapse the tree (only the small triangle is clickable)

![image](https://user-images.githubusercontent.com/7382357/142959399-683420ea-4bbd-4851-b10c-03746b71268b.png)

Suggestions:
Not sure how to describe, maybe add line space at first? Or maybe reference RegExr.com?

![image](https://user-images.githubusercontent.com/7382357/142960309-d10bd971-ab5e-44d3-97ae-2fa49acc72dd.png)

**Comment by firasdib** [comment]
Thanks for your feedback. I can understand where you are coming from. Regex101 tries to be more of a power tool in comparison to regexr, and converys a bit more information, which comes at the expense of "clutter".

Do you have any tangible suggestions on how to reduce the clutter, e.g., rewriting texts? More vertical spacing perhaps?

As for collapsing the tree, should the arrows be larger? Have an even bigger hit area? The entire label could be clickable too I suppose.

**Comment by MarvinXu** [comment]
I am learning Regex recently and found this excellent tool, thanks for your great work!

> Do you have any tangible suggestions on how to reduce the clutter, e.g., rewriting texts? More vertical spacing perhaps?
> 
> As for collapsing the tree, should the arrows be larger? Have an even bigger hit area? The entire label could be clickable too I suppose.

Sounds good. But you can leave it as it is for now, collect more ideas, and see what others feel about this.

Maybe I'll have more ideas after using it for a longer time 😉

**Comment by firasdib** [comment]
@MarvinXu I'll close this for now. If you have any feedback, feel free to post it here or create a new issue.

I hope you've gotten a bit more accustomed to the UI :)
