### ISSUE TITLE
Lazy Quantifier example code transfers incorrectly

### ISSUE THREAD

**Issue by Bejoscha** [firasdib/Regex101#1679]
## Bug Description
The Quick reference for the "Lazy quantifier"  does not copy the example correctly, when the arrow-button is pressed.
the /g mode switch gets removed, resulting in a different outcome than the one of the example.

### Reproduction steps
Access "Quick Reference" -> Lazy Quantifier
Then press the arrow-icon to copy the example

### Expected Outcome
Same selection as in the example, i.e. 

**r** **r**e **r**egex

### Browser
Firefox 94.0.2

### OS
Windows10

**Comment by firasdib** [comment]
Thank you, I will have this resolved in the next major release.
