### ISSUE TITLE
Wrong doc examples

### ISSUE THREAD

**Issue by rentalhost** [firasdib/Regex101#1681]
## Case 1
`\X` meta character is described wrong on doc:

![image](https://user-images.githubusercontent.com/421851/144885580-c736ce3a-57b1-4ba9-b395-bd3816930c63.png)

Docs mean that it is similar to `(?:s.)`, but actually is similar to `(?:\s|.)` or just `\s|.`.

## Case 2
`\Q ... \E` (quote; treat as literals): on click on example arrow, it will create that:

![image](https://user-images.githubusercontent.com/421851/144886657-5cab2435-7d61-4551-91d9-6ec702d09a99.png)

But the correct example text must be:

```
everything \w is ^ literal
```

**Comment by firasdib** [comment]
Thank you, I've fixed both. It will be released in the next major version.
