### ISSUE TITLE
Golang: Failed code generation for negative lookaround

### ISSUE THREAD

**Issue by e-loughlin** [firasdib/Regex101#1686]
## Bug Description
The code generated for Go given the following regex:

^((?!(CannotContainThisString)).)*$

fails to compile.

### Reproduction steps
1. Write the following regexp in the regexp entry: ^((?!(CannotContainThisString)).)*$
2. Generate Go code, and attempt to compile it:
[https://go.dev/play/p/qSGgd7MSd2E](https://go.dev/play/p/qSGgd7MSd2E)

3. You will get this error:
`panic: regexp: Compile(`(?m)^((?!(CannotContainThisString)).)*$`): error parsing regexp: invalid or unsupported Perl syntax: `(?!``

**Comment by firasdib** [comment]
The code generator simply generates code in the syntax of the selected language. If you want error detection, you'll have to check the editor, where it will tell you that construct is invalid when using the golang flavor.
