### ISSUE TITLE
How to participate in Chinese translation?

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#1690]
Hi, 
I noticed that the Chinese translation of the website is not yet complete, and some of the translations need to be optimized.
Is it possible to take part in translation work?

**Comment by firasdib** [comment]
Yes, you can visit this url: https://r101.cf/projects/site/regex101-com-2/

Thank you!

**Comment by Serious54088** [comment]
Thanks for your help.

There is a place in the settings that I don't fully understand.

> Include non-participating groups in match result

What effect does this setting have? As fas as I know, it will determines whether the non-participating groups should be showed in MATCH INFORMATION.  Is there any other effects?

**Comment by firasdib** [comment]
You're right, that's the only difference.
