### ISSUE TITLE
incorrect explanation for \Z (Python)

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#1691]
EXPLANATION (Python)

> **\Z** asserts position at the end of the string, or before the line terminator right at the end of the string (if any)

Reference:

| Flavor/Anchor | \Z                                                           | \z                                             |
| ------------- | ------------------------------------------------------------ | ---------------------------------------------- |
| PCRE         | assert position at the end of the string, or before the line terminator right at the end of the string | assert position at the very  end of the string |
| Python        | assert position at the very end of the string                | not support                                    |

**Comment by working-name** [comment]
Hi @Serious54088 

I'm assuming we're talking about the `re` module. In that case, yes, you are right, it matches the end of a string irrespective of `/m` flag and so on for both python 2 and 3. `\z` does not exist in py and I checked the quick ref, it doesn't seem to be listed there either which is good.

We'll get the python specific explanation in there with the next update.

Thank you!

**Comment by firasdib** [comment]
This will be fixed in the next release. Thank you.

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!
