### ISSUE TITLE
Add oniguruma regular expression syntax

### ISSUE THREAD

**Issue by Yash-Singh1** [firasdib/Regex101#1693]
This is the regexp syntax used when writing textmate grammars, used by vscode, atom, github linguist, textmate, and more. It's written in C, so you can transpile it using WebAssembly: https://github.com/kkos/oniguruma. VScode already exports a transpiled version of oniguruma: https://github.com/microsoft/vscode-oniguruma.

**Comment by firasdib** [comment]
Thank you for this. Is the same engine as Ruby uses?

The VSCode bindings look simple enough to use, but perhaps incomplete. I see no simple means of setting any regex flags, or performing any substitutions.

Do you have any insight in how those shortcomings could be resolved using the vscode bindings?

**Comment by Yash-Singh1** [comment]
> Thank you for this. Is the same engine as Ruby uses?
![ruby-regex-engine-info](https://user-images.githubusercontent.com/53054099/147859703-3fa28c7e-ab8a-4fb4-9052-1ce57a2b5387.jpg)
So it looks like Ruby used oniguruma in 1.9 and switched to its fork Onigmo in 2.0 and above

> The VSCode bindings look simple enough to use, but perhaps incomplete. I see no simple means of setting any regex flags, or performing any substitutions.

Probably makes sense that they didn't add flags or substitutions because TextMate grammars don't need that.

> Do you have any insight in how those shortcomings could be resolved using the vscode bindings?

I found this table: https://rrthomas.github.io/lrexlib/manual.html#notes, that maps flags to the `oniguruma`'s options (they have options instead of flags). There are more options, so in the UI, there will probably have to be custom names. Looking at `vscode-oniguruama`'s typings, there isn't any way to provide options. One solution could be to make a fork of `vscode-onigururama` that makes the library configurable. `oniguruama` doesn't support substitution/replacing, so that would be something to write in the fork too.

**Comment by firasdib** [comment]
I've looked into the details of this engine a bit more. Do you see any practical reason for implementing this on regex101? From my understanding, its very similar to PCRE, which has very wide support on the website already.

**Comment by Yash-Singh1** [comment]
> Do you see any practical reason for implementing this on regex101?

My use case was that when writing Visual Studio Code extensions with grammars, I have to debug my regular expressions. That can be really painful given that I have to edit regular expressions in a JSON file and keep reloading the code editor to see if my expected results are highlighted without intersecting styles taking over. If this could be on `regex101`, then it could be way easier, because I can focus on the regular expression mainly and less on debugging the grammar.

**Comment by firasdib** [comment]
Could you not do that using the PCRE flavor?

I understand there are some differences, but they are both backtracking engines, so should be quite similar.

**Comment by Yash-Singh1** [comment]
Sure, I can use that.

**Comment by oleedd** [comment]
@firasdib
>Do you see any practical reason for implementing this on regex101?

It supports advanced recursion features: https://rbuckton.github.io/regexp-features/engines/oniguruma.html#feature-recursion
Also, only it supports Text Segment Boundaries.
There are probably more exclusive features.
