### ISSUE TITLE
[Unit Tests] Show quick count of pass/fail tests

### ISSUE THREAD

**Issue by douglascayers** [firasdib/Regex101#1696]
## Feature
As an avid user with over 1,600 tests, when I run my tests I want to know how many have passed or failed so that I know how large of an impact my regex change had on my test suite without scrolling through and counting them manually.

Perhaps the pass/fail counts could be shown in the bottom bar with the buttons to expand/collapse/run tests?

![image](https://user-images.githubusercontent.com/4142577/148891485-1c8a0672-e653-474a-b0b9-d55168239738.png)

Thanks!

**Comment by firasdib** [comment]
I think both this and your suggestion in #1697 are great, but the space you've highlighted is typically dependent on the screen size. Adding text + buttons there will quickly get crowded. What do you think about moving all filtering functionality into a hamburger-style menu in that same location, with text regarding the pass/fail count?

**Comment by KatoakDR** [comment]
Thanks for the quick follow up. I'm happy with however you'd like to do it. 

Thanks for a wonderful website!

**Comment by douglascayers** [comment]
Thanks for the quick follow up. I'm happy with however you'd like to do it. 

Thanks for a wonderful website!

**Comment by firasdib** [comment]
Thanks, I'll have this live soon.

**Comment by douglascayers** [comment]
Thanks so much, this is great!

![image](https://user-images.githubusercontent.com/4142577/149058265-cc911749-4fab-428d-904a-2ff71fd2ef62.png)
