### ISSUE TITLE
[Unit Tests] Filters to show/hide pass/fail tests

### ISSUE THREAD

**Issue by douglascayers** [firasdib/Regex101#1697]
## Feature
As an avid user with over 1,600 tests, when I run my tests I want to filter to just the errors so that I can better focus on, analyze, and fix the errors without scrolling through the long list looking for them manually.

Perhaps the pass/fail show/hide toggles could be shown in the bottom bar with the buttons to expand/collapse/run tests?

![image](https://user-images.githubusercontent.com/4142577/148891485-1c8a0672-e653-474a-b0b9-d55168239738.png)

Thanks!

**Comment by firasdib** [comment]
Thanks, I'll have this live soon.
