### ISSUE TITLE
Specific Unicode range is not parsed correctly

### ISSUE THREAD

**Issue by randy** [firasdib/Regex101#1699]
## Bug Description
When two specific unicode character ranges are given in a specific order, as part of the same range/class, the Explanation incorrectly parses them and thereby provides incorrect information about the pattern.

This issue is present when the range is included in a larger pattern as well. However, it goes away by simply reversing the sequence of the two ranges. 

Note: I have not really been able to test whether the matching works 100% or not as most of these codes are beyond what we use day-to-day in the States. But matching is not necessarily part of this bug report.

### Reproduction steps
1. Select Java 8 from the FLAVOR menu
2. Include "Unicode matching" in the REGEX FLAGS menu
3. Enter the following in the REGULAR EXPRESSION field: `[\ud800-\udbff\udc01-\udfff]`

### Expected Outcome
EXPLANATION shows that there are two ranges, just as it would if you entered `[a-zA-Z]`, rather than 1 weird range, plus the hyphen (-) character and the `\udfff` character. See screenshot:

![image](https://user-images.githubusercontent.com/22246488/149328164-10af755d-d697-4d89-a3c0-bfafa527ee18.png)

### Browser
Vivaldi 5.0.x (chromium-based), Chrome 97.0.x

### OS
Mac 10.15.7

**Comment by birjolaxew** [comment]
I believe this to be intended behavior. Unlike e.g. Ecmascript, the Java 8 regex engine supports unicode escape sequences. This is illustrated in [the documentation](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) using the example of `\uD840\uDD1F` being an equivalent pattern to `\x{2011F}` (both matching the character 𠄟).

The regex engine interprets your pattern as `[\uD800-\x{10FC01}-\uDFFF]` (i.e. not as two ranges, but as one range plus the character `-` and the unicode point `\uDFFF`). You can verify this by trying to match the character `-`.

**Comment by firasdib** [comment]
@birjolaxew Is correct, `\udbff\udc01` is a surrogate pair, and interpreted as one character.

**Comment by randy** [comment]
> This is illustrated in [the documentation](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) using the example of `\uD840\uDD1F` being an equivalent pattern to `\x{2011F}` (both matching the character 𠄟).
> 
> The regex engine interprets your pattern as `[\uD800-\x{10FC01}-\uDFFF]` (i.e. not as two ranges, but as one range plus the character `-` and the unicode point `\uDFFF`). You can verify this by trying to match the character `-`.

Ok. Unicode jazz is obviously not my wheelhouse and a highly specialized thing. I had half a dozen questions I managed to Google, so I've got a better understanding of this, but of course I'm not going to be an expert in 20 minutes... So why not include that information in the explanation? I think that would be a great improvement and assist users that forget about surrogate pairs when they are actually aiming for two separate characters.

**Comment by birjolaxew** [comment]
There is no need to defend yourself. We are simply explaining why your regex doesn't parse the way you expect it to - a completely fair misunderstanding, and getting it explained is little more than an opportunity for learning.

The explanation did in fact include that information. It told you that `\ud800-\udbff\udc01` is a range from `U+D800` to `U+10FC01`, that `-` is a character (which might be confusing since it's usually used for ranges), and that `\udfff` matches the character `U+DFFF`.

**Comment by randy** [comment]
Right, but it doesn't explain _why_ the range ends with `\udbff\udc01` and not `\udbff`. And when the pattern is such that you expect two ranges instead of one, without a mention of surrogate pairs, one is lead to believe something is up with this app. This is misunderstanding is further supported when you switch the FLAVOR to an interpreter that _doesn't_ use surrogate pairs and see a result more in line with what you expect. Just a small hint that a surrogate pair has been recognized would be sufficient.
