### ISSUE TITLE
Multiple-Match Mode

### ISSUE THREAD

**Issue by boolbag** [firasdib/Regex101#17]
There is one usability feature I have been meaning to write to you about. I realize that you can tell the tester to try multiple matches by adding a 'g' flag. However, that will not be obvious for many users because unlike JavaScript, PHP does not have that flag. For this reason, I would suggest adding that feature as a toggle in settings or at the top of the pattern box.

What do you think?

**Comment by Thomas131** [comment]
I would say set g-Flag all the time in pcre-mode and hide it. The Website should give as much the same result, as possible.

Thomas

**Comment by nolanhergert** [comment]
+1 for an obvious hint that it's not on by default in most programs. Especially if it's obvious they're doing multiple matches (like multiple \n in a short period of time)
