### ISSUE TITLE
Can't change regex flags

### ISSUE THREAD

**Issue by Jhall1990** [firasdib/Regex101#1701]
## Bug Description
When clicking on the "Set Regex Options" button nothing happens. In the past a box would pop up allowing the user to select the regex flags they would like to enable/disable.

### Reproduction steps
Click "Set Regex Options"

### Expected Outcome
Regex options dialog opens allowing for selection of regex flags.

### Browser
Include browser name and version
Firefox - 96.0 (64-bit) for Linux Mint
Chromium - Version 97.0.4692.71 (Official Build) for Linux Mint (64-bit)
Firefox - 96.1.1 for Android

### OS
Include OS name and version
Linux Mint
Android

**Comment by tripb** [comment]
Colleagues encountering the same issue on Windows (Chrome, Edge) and Mac (Chrome, Safari, Firefox) (they are new users).  I have been using this tool for a while and am not having the issue (Mac, Chrome).

**Comment by dhb33** [comment]
This is all of the subden. It seems to me that it was working well Yesterday.

**Comment by jdswed** [comment]
Experiencing it myself, was working fine last night.

**Comment by GiovanH** [comment]
Can confirm.

**Comment by working-name** [comment]
Confirmed: the listeners for delimiter and flags (both in the regex input field) are not firing the appropriate action, recent regression as you've already figured out. It should be fixed shortly. Thank you everyone for reporting!

**Comment by working-name** [comment]
As a workaround until this is resolved, try passing `?flags=gmx` in the URL itself: [https://regex101.com/?flags=gmx&flavor=python](https://regex101.com/?flags=gmx&flavor=python). I'd go for a new tab and copy paste the stuff over.

**Comment by firasdib** [comment]
Apologies, silly error on my end. I've resolved the issue, and pushed it live.
