### ISSUE TITLE
Posix character class not properly detected within character class

### ISSUE THREAD

**Issue by ralfbergs** [firasdib/Regex101#1707]
## Bug Description
I used an expression like `[:.[:xdigit:]]+` that was treated as an error. The message I got was: "A posix character class may only appear inside a character class".

Slightly modifying the above expression to read `[[:xdigit:]:.]+` made the parser happy.

I believe that both variants should be acceptable.

Here you can find an example exactly like mine that's supposedly correct: https://www.regular-expressions.info/posixbrackets.html (first paragraph under "Character Classes")

My SMTP server, Exim, is also happy with my expression. It's using PCRE.

### Reproduction steps
Copy the below string as your regular expression:

`[:.[:xdigit:]]+`

You will immediately get the below error message:

`[:.[:xdigit:] A posix character class may only appear inside a character class`

This happens regardless of whether you use PCRE or PCRE2 as the flavor.

### Expected Outcome
My original expression should have been accepted with no errors.

### Browser
Firefox 96.0.1 64-bit

### OS
Windows 10, 21H2

**Comment by firasdib** [comment]
The parser is a bit overzealous to detect invalid posix constellations. I have adjusted this in order to fix this problem. 

Thanks for your report.

**Comment by ralfbergs** [comment]
Many thanks for looking into this so quickly and taking action.

**Comment by Jes2150** [comment]
We can build you anything but drive at your own risk currently have a 2 wheel hub dyno and a 4 wheel drive roller dyno do lots of engine modifications no matter the engine you want horse power we will give you horse power with the paper work to prove it or your money back garunteed
