### ISSUE TITLE
List function displays result as a vertical list

### ISSUE THREAD

**Issue by wabiloo** [firasdib/Regex101#1708]
## Feature
It would be good to have the option in the "list" function to show the results as a vertical list (such as bullet points).

It's possible currently by adding "\n" at the end of the substitution string, but seems it could be made simpler for some use cases

**Comment by firasdib** [comment]
You can make it return whatever you need. Forcing it to be a list would limit the functionality, even though it aligns with the name. I've yet to come up with a better name though.
