### ISSUE TITLE
Match highlights are invisible

### ISSUE THREAD

**Issue by jespertheend** [firasdib/Regex101#1710]
## Bug Description
![image](https://user-images.githubusercontent.com/2737650/151678417-a1c3b54d-ba98-4b6a-94bd-2ba82d429c66.png)
If I hover over `abc` it does show a tooltip of the fact that the match exists. But now match highlights are shown.

### Reproduction steps
Not sure if I have an uncommon environment, I can reproduce this in both Chrome and Firefox.

### Expected Outcome
Border highlights are visible

### Browser
Chrome 97.0.4692.99
Firefox 95.0.2

### OS
macOS 12.1

**Comment by working-name** [comment]
Hi @jespertheend,

Thank you for the notification, I can confirm the same happens in Brave Version 1.28.106 ( Chromium: 92.0.4515.159 ). 

Recent regression, it'll be fixed soon.

**Comment by firasdib** [comment]
Should be resolved!

**Comment by jespertheend** [comment]
Thanks for the quick fix!
