### ISSUE TITLE
Regex101 output not matching Python Interpreter

### ISSUE THREAD

**Issue by coding-girl314** [firasdib/Regex101#1712]
## Bug Description
I entered my regex expression "(((\w)+\w*\3){2}|(\w)+(?=\w*\4)\w*(?!\4)(\w)\w*\5)\w*" (without the quotes) into the regex101 tester (with the python flavor selected) using the test string: Alabama and Mississippi are next to each other. I had the global and case-insensitive flags on. The goal of my expression is to match any words with two sets of duplicate letters, allowing for four of the same letter as well. Both 'Alabama' and 'Mississippi' were matched in regex101, which was my desired output, however, in my python interpreter I only got a match on 'Mississippi'. I was using python version 3.8.10. What might be causing this difference?

### Reproduction steps
To test the source of this issue, I focused on the first half of the expression, and I eventually realized that by changing the start from "(((\w)+\w*\3){2}|" to "((\w)+\w*\2(\w)+\w*\3" to get the final expression "((\w)+\w*\2(\w)+\w*\3|(\w)+(?=\w*\4)\w*(?!\4)(\w)\w*\5)\w*" I was able to get successful matches on both "Alabama" and "Mississippi", as intended, in regex101 and my python interpreter. For some reason, by eliminating the use of the {2} quantifier, and instead writing out the expression twice, I was able to get favorable results. These two expressions should be equivalent, so I was wondering what is causing the difference in results?

### Python Interpreter Input
>>> import re
>>> reString = r"(((\w)+\w*\3){2}|(\w)+(?=\w*\4)\w*(?!\4)(\w)\w*\5)\w*"
>>> searchStr = "Alabama and Mississippi are next to each other."
>>> re.findall(reString, searchStr, re.I)
**[('Mississipp', 'ipp', 'p', '', '')]**

This first test only matched on Mississippi and not Alabama. I tested just the part of my expression that was supposed to match Alabama next, and made Alabama lowercase to ensure that was not the issue.

>>> searchStr="alabama"
>>> reString = r"((\w)+\w*\2){2}\w*"
>>> re.search(reString, searchStr, re.I)

Still, there was no match, so I expanded my expression and tried again. Instead of using {2}, I simply copied the part of the expression that was intended to be duplicated and wrote it out explicitly. This gave me my desired output.

>>> reString = r"^((\w)+\w*\2)((\w)+\w*\4)"
>>> re.search(reString, searchStr, re.I)
**<re.Match object; span=(0, 7), match='alabama'>**

### Expected Outcome
My regex expression is supposed to match all words that contain at least two sets of duplicate letters, such as the word "depends" (two 'e's and two 'd's), also allowing for four of the same letter to be repeated to satisfy this expression. This is case insensitive. I expected my expression to work the same on my python interpreter as it did in regex101, but this was not the case.

### Browser
Firefox Browser, version 96.0.3 (64-bit)

### OS
Windows 11, version 21H2.

**Comment by working-name** [comment]
Hi @coding-girl314,

I think it's rather easy to overlook the default flags if you're not used to the site. By default you get `/gm` but not i. You have to toggle that on manually.

The difference between getting and not getting a match on Alabama has to do with the fact that you're using backreferences (aka calling `\1` or `\4`) which will match _the same_ text that was previously matched and captured by the group you're referencing. When the `/i` flag isn't there, the expectation is to find another capital `A` in Alabama, which of course isn't there.

Here's an isolated, PCRE-selected link to play around with: (by the way, your original whole patterns works in all flavors except golang because it does not implement backreferences `\1`)

https://regex101.com/r/ncW7iG/3
Hit Debugger and follow along with the engine to see what it tries to do and why in the end it fails to return a match.

**Comment by coding-girl314** [comment]
Thank you for your response! I had selected the /i flag in Regex101, and my desired results were achieved on the website. However, my question is why I wasn't getting the same match in my python interpreter that I got on the website. 

On another note, the expression "(((\w)+\w*?\3){2}|(\w)+(?=\w*\4)\w*(?!\4)(\w)\w*\5)\w*" works as intended on both Regex101 and my python interpreter, however my original expression, "(((\w)+\w*\3){2}|(\w)+(?=\w*\4)\w*(?!\4)(\w)\w*\5)\w*", does not work on my python interpreter. By adding a '?' to change the greediness of the first '\w*', this expression works. However, I thought that the original expression should have worked as well, because the first '\w*', although greedy, is supposed to backtrack as needed. What could explain the difference in results for these expressions? And why does this difference only occur in my python interpreter while matching on both "Alabama" and "Mississippi", as expected, in Regex101?

**Comment by working-name** [comment]
Closing this for now, but would be more than happy to reopen and continue troubleshooting.
