### ISSUE TITLE
Incorrect example in Recurse Subpattern explanation

### ISSUE THREAD

**Issue by AharonSambol** [firasdib/Regex101#1714]
## Bug Description
The documentation under "RECURSE SUBPATTERN CALLED 'NAME'" states:
(?P>name)  Recursively matches the given named subpattern or capture group.

and provides the following example:
/((?P>who)) or (?<who>[a-z]+)/
123 or 789

This example is incorrect: where it says [a-z] that should instead be [0-9]

### Reproduction steps
Test the example using https://regex101.com/  - it won't work. Changing a-z to 0-9 corrects the error.

### Expected Outcome
A working example :)

**Comment by firasdib** [comment]
Thank you, I've adjusted this.
