### ISSUE TITLE
[Feature Request] Click the TEST STRING and jump to MATCH INFORMATION

### ISSUE THREAD

**Issue by Symbolk** [firasdib/Regex101#1716]
## Feature

When there are capture groups in regex, it is very nice to click group in MATCH INFORMATION to jump and highlight corresponding content in TEST STRING!

However, what about vice versa? Now there is a popover, maybe this feature is unwanted due to the conflict with text editing operations?

**Comment by firasdib** [comment]
I think you hit the nail on the head, if I add a click event in the text area, selecting/modifying text will cause the match info pane to jump about, which might not be what you want.

Could you explain the use case for me?

**Comment by Symbolk** [comment]
> I think you hit the nail on the head, if I add a click event in the text area, selecting/modifying text will cause the match info pane to jump about, which might not be what you want.
> 
> Could you explain the use case for me?

Thanks for your response. 

Today I am crafting a regex to match method calls in code strings, and capture method name, arguments, output, etc. at the same time, so lots of groups are used. I have 100 test cases in TEXT STRING, if I need to check the 50th method call, I need to scroll a lot in MATCH INFORMATION. Although popover can help to see the capture group results too, certainly MATCH INFORMATION provides a more clear view and more information in lists.

**Comment by firasdib** [comment]
@Symbolk I completely understand.

Have you tried using the unit test feature instead? It might help you isolate your cases better and get a better overview.

As to your original request, I can't think of a great way of implementing it without causing weird/unintended behavior. I hope you understand.

**Comment by Symbolk** [comment]
@firasdib Good, I am trying to use the test case feature, thanks for such a nice tool!
