### ISSUE TITLE
java 8: (*) should capture empty string, it does not

### ISSUE THREAD

**Issue by fidukered** [firasdib/Regex101#1720]
java regex 101
regex = `"(?<grp>a*)"`
input string = new String();
<actual>
capture: grp = null

<should>
capture grp="" (empty string)

from javadoc: 

```
public String group (String name)
Returns the input subsequence captured by the given named-capturing group during the previous match operation.
If the match was successful but the group specified failed to match any part of the input sequence, then null is returned. Note that some groups, for example (a*), match the empty string. **_This method will return the empty string_** when such a group successfully matches the empty string in the input.
```

**Comment by firasdib** [comment]
I see an empty group captured here: https://regex101.com/r/AoZUxj/1

**Comment by fidukered** [comment]
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class TestRegex101 {

  public static void main(String[] args) {
	System.out.println();
	System.out.println("Matcher.group(String name) javadoc:");
	System.out.println();
	System.out.println(javadoc);
	System.out.println();
	System.out.println("Test This:");
	System.out.println();

	String regex1 = "(?<grp>a)*";
	Pattern pattern1 = Pattern.compile(regex1);
	Matcher matcher1 = pattern1.matcher("");
	matcher1.find();
	String match1 = matcher1.group("grp");
	System.out.println("regex1 = " + regex1);;
	System.out.println("matcher1.group(\"grp\") grp should match null");
	System.out.println("matcher1.group(\"grp\") = " + match1);

	System.out.println("--------------------");
	System.out.println();

	String regex2 = "(?<grp>a*)*";
	Pattern pattern2 = Pattern.compile(regex2);
	Matcher matcher2 = pattern2.matcher("");
	matcher2.find();
	String match2 = matcher2.group("grp");
	System.out.println("regex2 = " + regex2);
	System.out.println("matcher2.group(\"grp\") grp should match empty String");
	System.out.println("match2.length() = " + match2.length());

	System.out.println();
	System.out.println("====================");
	System.out.println("Above confirms javadoc behavior");
	System.out.println();
	System.out.println("https://regex101.com/r/vLQ3MB/1 gets this right (matches null)");
	System.out.println("https://regex101.com/r/KnDQLE/1 gets this wrong (should match empty String, but, instead matches null");
  }

  static String javadoc = """
	  public String group(String name)
	  Returns the input subsequence captured by the given named-capturing group during the previous match operation.
	  If the match was successful but the group specified failed to match any part of the input sequence, then null is returned. Note that some groups, for example (a*), match the empty string. This method will return the empty string when such a group successfully matches the empty string in the input.""";
}

**Comment by fidukered** [comment]
understood.

 

thanks!

 
 

Sent: Wednesday, February 16, 2022 at 12:26 PM
