### ISSUE TITLE
Does Go have [[:<:]] as "start of word"?

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#1722]
## Bug Description
When Go is selected as regex flavour, the quick reference lists `[[:<:]]` as "Start of word". When I try to use it, however, the explanation tells me:
```
[:<:] POSIX Word Boundaries must be the only item inside a character class
```

I honestly don't know Go, so I looked up the [regex syntax](https://github.com/google/re2/wiki/Syntax) and "Start of word" is not mentioned anywhere. Does Go support this?

### Reproduction steps
https://regex101.com/r/kK53r2/1

### Expected Outcome
Either it should not be in the quick reference, or it should work

### Browser
Reproducible on both Gecko and Blink.

### OS
_Probably_ OS independent as well.

**Comment by firasdib** [comment]
I can now confirm this is not supported by GO, and have as such removed them from the quickref and improved the error message.
