### ISSUE TITLE
Regex doesn't match Python's behavior

### ISSUE THREAD

**Issue by kurifu** [firasdib/Regex101#1723]
## Bug Description
An expression in python on regex101 does not match the behavior in a local python 3.9.10 REPL

### Reproduction steps
1. Go to reg101.com
2. Enter the following for the regular expression: [\?\*]
3. For test strings, enter the following:
site:youtube.*
site:yout?be.com
site:yout?be.*

### Expected Outcome
4. There are 4 matches; one for the first line with *, one for the second line with ?, and two for the third line for ? and *

Actual Outcome:
4. Only a single match is found for the first line with *. The question mark character is never matched. As soon as you remove \* from the regex, question marks are matched.

![Screen Shot 2022-02-24 at 2 42 40 PM](https://user-images.githubusercontent.com/410314/155619840-7d07b8f9-2114-4de0-8133-952ff2eca884.png)
![Screen Shot 2022-02-24 at 2 45 20 PM](https://user-images.githubusercontent.com/410314/155620092-c039eccb-76c7-4149-a005-94c7b6c6f7bb.png)

### Browser
Include browser name and version
Chrome 98.0.4758.102

### OS
Include OS name and version
Mac 11.6.1 Big Sur

**Comment by working-name** [comment]
Hi @kurifu you are using findall which suggests `/g` flag, while in the browser you are not enabling the global flag. That's what instructs the regex engine to keep going after the first successful match.

**Comment by working-name** [comment]
Closing this for now, please feel free to continue the conversation, will reopen if necessary.
