### ISSUE TITLE
Verb `(*NO_JIT)` is valid, but not recognized in PHP flavour

### ISSUE THREAD

**Issue by Danon** [firasdib/Regex101#1724]
## Bug Description

![image](https://user-images.githubusercontent.com/13367735/155699033-15b554fa-f35a-404f-bbdf-f0c0015fe613.png)

### Expected Outcome

Verb `(*NO_JIT)` is a valid verb, and disables JIT in PCRE.

**Comment by firasdib** [comment]
Thank you, I'll add support for this. It will be in the coming release.
