### ISSUE TITLE
Quizz Task 2 - Capitalize I

### ISSUE THREAD

**Issue by eric13500** [firasdib/Regex101#1726]
## Bug Description
Solution fonctionnelle non reconnue :

### Reproduction steps
**Removed**: please do not post quiz solutions publicly.

Résultat : _Test 1/9: You are not replacing i at all! Start with /i/g and replace the match with I._

/i/g n'est pas une RegEx...

Ma solution fonctionne dans le simulateur :

Chaîne de test :
i'm replacing it. am i not?

Substitution :
**I**'m replac**i**ng **i**t. am **I** not?

### Expected Outcome
Validation de ma réponse, ainsi que la meilleure solution si elle est différente de la mienne.

### Browser
Chrome Version 98.0.4758.102 (Build officiel) (64 bits)

### OS
Windows 10 Pro x64

Merci beaucoup pour cet outil absolument génial non-seulement pour tester ses RegEx, mais surtout en ce qui me concerne pour les apprendre et mieux les comprendre !

**Comment by Mostuniqu3** [comment]
/i/g est une RegEx, c'est juste que le premier /, et que le /g sont pré-remplis sur le site.
Aussi, la phrase donnée en exemple dans l'énoncé n'est pas la même que celle du premier test, or, vous essayez de trouver "i'm replacing it. am i not?", alors l'engine ne trouve aucun match et ne fait pas de substitution, d'ou le message d'erreur.

/i/g est en effet une meilleure réponse mais elle ne sera pas suffisante pour compléter ce test.

**Comment by firasdib** [comment]
Please post in english.

**Comment by structuredDesigner** [comment]
I've used the following regexp for this Quiz task:

"<redacted>"

and "I" as replacement. Yet I get 1/9 "You are not replacing i at all! Start with /i/g and replace the match with I.".

However, when I test that regexp on your regexp builder, it works perfectly. Seems like there's a bug on the quiz.
