### ISSUE TITLE
Long subpattern reset syntax is supported, but short isn't

### ISSUE THREAD

**Issue by Danon** [firasdib/Regex101#1728]
Syntax `(?:(?^i)welcome)` is supported

![image](https://user-images.githubusercontent.com/13367735/155888719-05c6a043-911a-4168-81ad-82997321b65d.png)

But shorter syntax, which spells `(?^i:welcome)` isn't

![image](https://user-images.githubusercontent.com/13367735/155888735-40d37206-5acc-4284-86a5-80bb9437cc7a.png)

But it's equally valid.

**Comment by working-name** [comment]
Hey @Danon,

Nice find there!

When I read through the section in pcre2.txt it wasn't obvious at all that `?^` could be used in the shorthand version. But PHP 8.0 doesn't scream about it so I guess it is allowed.

```
       As  a  convenient shorthand, if any option settings are required at the
       start of a non-capturing group (see the next section), the option  let-
       ters may appear between the "?" and the ":". Thus the two patterns

         (?i:saturday|sunday)
         (?:(?i)saturday|sunday)

       match exactly the same set of strings.
```

I guess `any option settings` really means any 😆.

**Comment by Danon** [comment]
@working-name It wasn't really a finding, I was developing my library https://github.com/T-Regx/T-Regx and it so happened I wanted to check something.

Glad I could help.

**Comment by Danon** [comment]
@working-name For completeness, I think `(?)` is also valid, but redundant. I think Regex101 should handle it as well.

**Comment by firasdib** [comment]
Thanks, will be fixed shortly.
