### ISSUE TITLE
Callouts aren't supported by PHP, but aren't invalid

### ISSUE THREAD

**Issue by Danon** [firasdib/Regex101#1729]
## Bug Description

PHP uses PCRE2 under the hood, and PCRE allows for callouts. PHP doesn't use them, so it's understandable that you don't support them; but never the less they are valid in expression.

### Reproduction steps

![image](https://user-images.githubusercontent.com/13367735/156145215-c9f4a3cc-b421-46c7-9ce2-b7412fdc9471.png)

### Expected Outcome

But when you actually run the pattern, it isn't reported as invalid. Of course `(?C)` is ignored, but it runs.

![image](https://user-images.githubusercontent.com/13367735/156145427-d2954a6f-9b75-4a8d-9df7-44293acd252f.png)

### Conclusion

You can mark `(?C)` (and also `(?C0)`, `(?C1)`, etc.) as comments, or decorate them some other way; but I think marking them as invalid is misleading.

Regex101 tells me the regex is invalid, I plug it in and it works. Wierd.

**Comment by firasdib** [comment]
This is intentional, since you can't use them in any meaningful way on the website, and their use in their wild is so uncommon that this issue has taken nearly 10 years to pop up ... :)

**Comment by Danon** [comment]
@firasdib Well, I'm developing a library for regular expressions, and I need to handle every such case. I support myself both with unit tests and your genius https://regex101.com/ tool, which is awesome.

And when I plugged in value from my unit into https://regex101.com/ and saw it as invalid, I honestly thought "waidaminute, is there a bug in my library?" :O And then I went and checked, and it turned out that `(?C)` is valid indeed.

> This is intentional, since you can't use them in any meaningful way on the website, and their use in their wild is so uncommon that this issue has taken nearly 10 years to pop up ... :)

I agree that it's useless and meaningless. 

But nonetheless, I expect that if I plug in in an expression accepted by PCRE into the regex101, it would be marked as valid. This error suggests that the expression would not run, but it does.

**Comment by firasdib** [comment]
@Danon Since I use callouts internally, these (to you) useless callouts, will ruin the assumptions made by regex101. For that reason, they will remain this way. I can add a special message for this if that helps.

**Comment by Danon** [comment]
@firasdib I'm sorry, I didn't mean to offend you. When I said "useless" I mean, there's no way to use them from PHP code, since PHP doesn't provide any way to use them.

> will ruin the assumptions made by regex101

Out of curiosity, what is the assumption? :>

> I can add a special message for this if that helps.

I think it would help.

**Comment by firasdib** [comment]
They are used to understand the execution flow of the regular expression and display useful information, such as debugging etc.

I will look into adding a message for this token when its encountered.

**Comment by Danon** [comment]
> They are used to understand the execution flow of the regular expression and display useful information, such as debugging etc.

Yes, but not from PHP, right? Unless there's some special API for that which I don't know of.

> I will look into adding a message for this token when its encountered.

Okay, thanks.

**Comment by firasdib** [comment]
PHP is not used by regex101, the flavor mentions PHP to help people understand a common use case.

**Comment by Danon** [comment]
> PHP is not used by regex101, the flavor mentions PHP to help people understand a common use case.

Yes, so can't we make `(?C)` reported as valid, though redundant in PHP flavor?

**Comment by Danon** [comment]
OOOOOOOOOOOOHHHHH, I think I know what you mean.

You're saying you don't allow users to add `(?C)` in the input patterns, because the application then inserts callouts into the pattern that are used to debug the pattern? Is that it?

**Comment by Danon** [comment]
I undestand.

Isn't there a way to allow and ignore user-supplied `(?C)` in the pattern? The callouts can be specified either by index or by name using `C0`,`C1` or `C{abc}`, `C{def}`. 

It would seam it would be possible to achieve, simply add other callouts in you pattern, such that don't appear in the user pattern, and after the callout ignore those from user.

Whether that's worth your time and development is another issue, but it is possible, right?

**Comment by firasdib** [comment]
Anything is possible, but the cost/benefit ratio is very low, plus, manipulating the regex this way will impact performance.

regex101 tries to be a complete tool, but it's opinionated.

**Comment by Danon** [comment]
> Anything is possible, but the cost/benefit ratio is very low, plus, manipulating the regex this way will impact performance.

But it already is manipulated isn't it? Because of the added callouts used for debugging?

**Comment by firasdib** [comment]
An error will be included for this token in the next release.
