### ISSUE TITLE
Incorrect Generated Code for C# 

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#1734]
## Bug Description

Enter escape sequence in SUBSTITUTION, the generated code is incorrect.

#### EDITOR

FLAVOR: `.NET(C#)`

REGULAR EXPRESSION `b`
TEST STRING `abc`
SUBSTITUTION `\t`

RESULT `a	c`

#### GENERATED CODE

The output of the GENERATED CODE is different from that of the editor, 
I have described the specific problems in the comments.
Try on [Try .NET](https://try.dot.net/)

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
    public static void Main()
    {
        string pattern = @"b";
        string substitution = @"\t";  // here should not use verbatim string
        string input = @"abc";
        RegexOptions options = RegexOptions.Multiline;
        
        Regex regex = new Regex(pattern, options);
        string result = regex.Replace(input, substitution);

        //Print the result
        //Console.WriteLine($"{result} {result.Length}");
        //a\tc 4
    }
}
```

**Comment by firasdib** [comment]
Thank you for this.

Is it sufficient to just replace `string substitution = @"\t";` with `string substitution = "\t";` in the generated code?

**Comment by Serious54088** [comment]
> 

Yes, I this it's sufficent for escape sequence.

If using normal string, the double quote and backslash might also want to consider.

typing `\\` in SUBSTITUTION, the code should be

```c#
string substitution = "\\\\";
//string substitution = @"\\";
```

typing `"` in SUBSTITUTION, the code should be

```c#
string substitution = "\"";
//string substitution = @"""";
```

**Comment by firasdib** [comment]
Thank you. What do you think is the best approach? I can also replace the escape sequences with their corresponding value in the verbatim string.

**Comment by Serious54088** [comment]
> I can also replace the escape sequences with their corresponding value in the verbatim string.

If user enter `a\nb` in SUBSTITUTION, generate the code:

```c#
string substitution = @"a
b";
```
Is that what you mean? I think it's great.

user input => verbatim string

`a\\b` => `@"a\b"`  
`a\tb` => `@"a	b"`  
`a\x20b` => `@"a b"`

**Comment by firasdib** [comment]
Hi, would you please verify and see if the new version is better?

**Comment by Serious54088** [comment]
Hi, 
According to my test, everything works well except double quotes.
If user enter a `"` , the correct code is
```csharp
string substitution = "\""
// or 
// string substitution = @""""
```

And I just found a problem, there is an extra null character at the end of the result text.
![image](https://user-images.githubusercontent.com/28971568/157059028-0023d02f-a9be-4a2b-b364-31a750df8a01.png)

**Comment by firasdib** [comment]
Thank you for verifying. I will fix the quotes.

The null byte is a by-product to #1737, I hope to have it fixed soon.
