### ISSUE TITLE
C# engine error

### ISSUE THREAD

**Issue by hockeyguy2** [firasdib/Regex101#1736]
I tried a straightforward regex with the C# engine and it shows an "engine error" with no additional explanation.

Here's the regex (quoted here, as per the UI):
```
"^@([^:]+)(?:[:](.*))?$"
```

The intent is to match a basic "directive" line in a text file, in one of the following forms:
```
    @directive
    @directive:value
```

This works as expected in C# (LINQPad), but I can't it to get to work at all with Regex101.

**Comment by firasdib** [comment]
I am unable to replicate this. Could you please save a permalink on regex101 and share the link here?

**Comment by hockeyguy2** [comment]
Here's the link: https://regex101.com/r/vyXRXM/1

And the error message in the "Match Information" panel is:
```
   Unable to initialize the regex engine! Please try to reload the web page. If the issue persists, please open an issue
```
(along with the red "engine error" bubble to the right of the regex entry textbox)

**Comment by firasdib** [comment]
Have you tried in an incognito window?

Can you also take a screenshot of your console? 




Vänliga hälsningar / Best regards,

Firas Dib

**Comment by hockeyguy2** [comment]
Yes, I have tried an incognito window, with the same results.  However, I hadn't looked at the JavaScript console until just now, and I think it explains the problem:

```
Access to fetch at 'https://gateway.zscloud.net/...' (redirected from 'https://regex101.com/static/Microsoft.JSInterop.WebAssembly.dll') from origin 'https://regex101.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I removed the exact ZScaler URL, as I don't know whether it contains any private information, but the upshot is that there seems to be some kind of problem/conflict between ZScaler and the CORS policy.  I don't know whether this is a problem with the ZScaler configuration (which I have no visibility into), or the CORS policy for the site/page, or both.

**Comment by firasdib** [comment]
There is no CORS request happening, since its served by the same domain. Likely your local software is blocking the .dll files since it thinks they are somehow dangerous.

Try to see if you can whitelist it.
