### ISSUE TITLE
c# flavor does not match $ to end of string

### ISSUE THREAD

**Issue by CottageDwellingCat** [firasdib/Regex101#1737]
## Bug Description
The editor only matches the $ character to a newline, instead of the end of a string. Actually testing the regex in a c# app shows that $ matches the end of a string with the same expression.
![image](https://user-images.githubusercontent.com/80918250/156893934-01e4e61e-4281-49ba-b27b-224264c64b42.png)
![image](https://user-images.githubusercontent.com/80918250/156893970-86412597-6170-45ed-a0d4-cfe3f784f545.png)

### Reproduction steps
- write a regex containing a $ in the editor ([test expression](https://regex101.com/r/769tHt/2))
- include matches on multiple lines 
- note the match on the last line is not highlighted.
- run the expression and input in a c# program
- note the last match is included ([sample gist using .net6](https://gist.github.com/CottageDwellingCat/e27d04df67b45e7fdb3bb7159a286d6c))

### Expected Outcome
the editor highlights both matches.

### Browser
Firefox Nightly 99.0a1 (2022-03-05) (64-bit)
Firefox Stable 97.0.2 (64-bit)

### OS
Ubuntu 20.10 (64-bit)

**Comment by firasdib** [comment]
Thank you. The upstream issue is https://github.com/dotnet/runtime/issues/66212

Once this lands I will be able to update regex101 and ensure all related cases work as they should.

**Comment by stephentoub** [comment]
> Thank you. The upstream issue is https://github.com/dotnet/runtime/issues/66212

I don't believe that's the same issue... but I also can't repro on the latest in dotnet/runtime main.

**Comment by firasdib** [comment]
@stephentoub It is, I had to add a null byte at the end of each string to avoid out of bounds exceptions being thrown. Consequently, some regexes (like the one in this issue) stops working. When that issue lands, the out of bounds errors won't be thrown, and I can remove the trailing null byte.

If you know of a better workaround while we wait for the fix to land, please enlighten me :-)

**Comment by stephentoub** [comment]
> It is

The repro in this issue produces the correct result with dotnet/runtime main, without the fix from https://github.com/dotnet/runtime/issues/66212.

**Comment by firasdib** [comment]
Im using .net 7


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by firasdib** [comment]
@stephentoub I don't follow what you're saying.

The reason the issue described in this repo exists is because I pad the string with a null byte to avoid the issue described in the .NET repo. When that is merged, I can remove my temporary fix and deploy a new version that uses a new build from .NET

**Comment by stephentoub** [comment]
> I pad the string with a null byte to avoid the issue described in the .NET repo

Ah, you're saying in order to work around https://github.com/dotnet/runtime/issues/66212, you explicitly broke the behavior of end anchors by padding the input string, and once you have the fix for https://github.com/dotnet/runtime/issues/66212, you can revert your breaking behavior.  I misunderstood what you were saying.

**Comment by firasdib** [comment]
@stephentoub Do you know when preview 2 will be out (with this fix)? Or is there a simple way for me to compile my code with the fix included?

**Comment by stephentoub** [comment]
> Do you know when preview 2 will be out (with this fix)? Or is there a simple way for me to compile my code with the fix included?

It'll be in preview 3.  It's also in nightly builds: https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries.

**Comment by firasdib** [comment]
@stephentoub thank you, I'll use a nightly build then!

**Comment by stephentoub** [comment]
> the bug still looks to be present

Something else is going on then, as the fix definitely addressed the cited inputs; they were all included as test cases for the fix.

> Also, the output was increased by ~500kb

System.Text.RegularExpressions.dll, untrimmed, is only 375kb, so something else is going on there as well. @eerhardt, are there known increases in blazor wasm size in .NET 7 recently?  Do nightly builds differ in trimming from official builds?

**Comment by firasdib** [comment]
As for the matching issue, I cross-posted in both these issues. Lets keep that discussion in 

As for the size issue, I compared the built between the two (official preview1 and preview3 from nightly):
```
-rw-r--r-- 1 firas 1,5K 15 mar 18.00 out.preview1/wwwroot/blazor.boot.json
-rw-r--r-- 1 firas 234K 15 mar 18.00 out.preview1/wwwroot/dotnet.7.0.0-preview.1.22076.8.13ek1r2czw.js
-rwxr-xr-x 1 firas 5,0M 15 mar 18.00 out.preview1/wwwroot/dotnet.wasm*
-rw-r--r-- 1 firas 6,0K 15 mar 17.59 out.preview1/wwwroot/Microsoft.JSInterop.WebAssembly.dll
-rw-r--r-- 1 firas 8,0K 15 mar 17.59 out.preview1/wwwroot/Regex101.dll
-rw-r--r-- 1 firas  21K 15 mar 17.59 out.preview1/wwwroot/System.Collections.Concurrent.dll
-rw-r--r-- 1 firas  13K 15 mar 17.59 out.preview1/wwwroot/System.Collections.dll
-rw-r--r-- 1 firas 823K 15 mar 17.59 out.preview1/wwwroot/System.Private.CoreLib.dll
-rw-r--r-- 1 firas  21K 15 mar 17.59 out.preview1/wwwroot/System.Private.Runtime.InteropServices.JavaScript.dll
-rw-r--r-- 1 firas  61K 15 mar 17.59 out.preview1/wwwroot/System.Private.Uri.dll
-rw-r--r-- 1 firas 2,5K 15 mar 17.59 out.preview1/wwwroot/System.Runtime.CompilerServices.Unsafe.dll
-rw-r--r-- 1 firas 5,0K 15 mar 17.59 out.preview1/wwwroot/System.Runtime.dll
-rw-r--r-- 1 firas 276K 15 mar 17.59 out.preview1/wwwroot/System.Text.RegularExpressions.dll

-rw-r--r-- 1 firas 1,4K 15 mar 17.59 out.preview3/wwwroot/blazor.boot.json
-rw-r--r-- 1 firas 216K 15 mar 17.59 out.preview3/wwwroot/dotnet.7.0.0-preview.3.22151.6.13ek1r2czw.js
-rwxr-xr-x 1 firas 5,7M 15 mar 17.59 out.preview3/wwwroot/dotnet.wasm*
-rw-r--r-- 1 firas 6,0K 15 mar 17.58 out.preview3/wwwroot/Microsoft.JSInterop.WebAssembly.dll
-rw-r--r-- 1 firas 8,0K 15 mar 17.58 out.preview3/wwwroot/Regex101.dll
-rw-r--r-- 1 firas  21K 15 mar 17.58 out.preview3/wwwroot/System.Collections.Concurrent.dll
-rw-r--r-- 1 firas  13K 15 mar 17.58 out.preview3/wwwroot/System.Collections.dll
-rw-r--r-- 1 firas 851K 15 mar 17.58 out.preview3/wwwroot/System.Private.CoreLib.dll
-rw-r--r-- 1 firas  21K 15 mar 17.58 out.preview3/wwwroot/System.Private.Runtime.InteropServices.JavaScript.dll
-rw-r--r-- 1 firas  61K 15 mar 17.58 out.preview3/wwwroot/System.Private.Uri.dll
-rw-r--r-- 1 firas 2,5K 21 feb 14.52 out.preview3/wwwroot/System.Runtime.CompilerServices.Unsafe.dll
-rw-r--r-- 1 firas 5,0K 15 mar 17.58 out.preview3/wwwroot/System.Runtime.dll
-rw-r--r-- 1 firas 294K 15 mar 17.58 out.preview3/wwwroot/System.Text.RegularExpressions.dll
```

Looks like `dotnet.wasm`, `System.Private.CoreLib.dll` and `System.Text.RegularExpressions.dll` increased quite a bit in size. The options for the project are identical between the two.

**Comment by firasdib** [comment]
This will be fixed in the next release. Looks like size increase is inevitable, but its better to have a fully functioning lib.
