### ISSUE TITLE
Python does not have a "global flag"

### ISSUE THREAD

**Issue by mangelozzi** [firasdib/Regex101#1739]
## Bug Description
When using the python regex, it provides an option for a global flag, but there is no such thing in python.

Refer to https://docs.python.org/3/library/re.html#module-contents

**Comment by firasdib** [comment]
This is on purpose to align the flavors, otherwise it would be very weird working with the different flavors in the same UI. If you open the code generator, it will show you appropriate code.

The `g` flag is borrowed from Perl.
