### ISSUE TITLE
Verbs (*CR) and (*LF) are valid in PCRE2, but aren't supported

### ISSUE THREAD

**Issue by Danon** [firasdib/Regex101#1740]
They are supported in PCRE1:
![image](https://user-images.githubusercontent.com/13367735/157476587-8c2712d4-cf8d-4055-8fa1-243334668090.png)

But aren't in PCRE2:
![image](https://user-images.githubusercontent.com/13367735/157476642-4ed7fccd-e0f2-466a-a34b-db391cdd82bd.png)

However PCRE2 and PHP with PCRE2 both support these verbs: `(*CR)`, `(*LF)`, `(*CRLF)` at the start of the pattern.

**Comment by firasdib** [comment]
Thanks, this will be fixed in the upcoming release.
