### ISSUE TITLE
JavaScript: braces are rejected in character class

### ISSUE THREAD

**Issue by kevinushey** [firasdib/Regex101#1742]
The following regular expression is considered invalid for JavaScript in unicode mode:

```
[{}]
```

The following error is shown:

```
{ This token must be escaped when the u flag is enabled unless they form a valid quantifier
} This token must be escaped when the u flag is enabled unless they form a valid quantifier
```

even though node / browsers accept it in unicode mode; e.g. `/[{}]/u` is a valid regular expression.

**Comment by firasdib** [comment]
Thank you, this will be resolved in the next update.
