### ISSUE TITLE
Right to left matching

### ISSUE THREAD

**Issue by bburgess19** [firasdib/Regex101#1744]
## Feature
I use Regex in .NET, among other features, I find the use case for right-to-left matching comes up semi-regularly. Unfortunately, I don't believe there is a way to use that functionality within Regex101 right now, so it would be great if it could support it! It's the only reason I begrudgingly trudge over to .NET storm from time to time.

**Comment by firasdib** [comment]
I have added a flag for this in the dropdown, `R`. Officially there is no shortcut for it, but to follow the semantics of regex101, I added this "custom" flag.

Hope that helps.
