### ISSUE TITLE
The image representing the LF character should be colored when it matches the regular expression.

### ISSUE THREAD

**Issue by jgomezprada** [firasdib/Regex101#1747]
![image](https://user-images.githubusercontent.com/26471671/158677694-2ba1a65b-ae18-4b1e-9ac7-27c070c04538.png)

**Comment by firasdib** [comment]
My bad, I can see you have enabled the `s` flag in your previous issue.

I will explore the possibility of improving this, but its notoriously difficult since newlines are zero width.

**Comment by firasdib** [comment]
There is no easy way for me to do this, so I will close this issue.
