### ISSUE TITLE
"Engine Error" - Unable to initialize the regex engine!

### ISSUE THREAD

**Issue by dawalters1** [firasdib/Regex101#1751]
When typing any form of regular expression, "engine error" pops up.

The following is displayed in the console numerous times:

![image](https://user-images.githubusercontent.com/28631585/159507545-61d0932c-92f4-4570-a985-3b96ba30c8bf.png)

**Comment by firasdib** [comment]
Could you try an incognito window?

Can you show the network tab and highlight the failed requests?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by firasdib** [comment]
@dawalters1 any update?

**Comment by dawalters1** [comment]
Meant to post an update the same day however completely forgot.

This started working normally later that day.
I can see about the failed requests shortly

**Comment by dawalters1** [comment]
No requests are failing now.
