### ISSUE TITLE
Valid regex gets critical error

### ISSUE THREAD

**Issue by Pirotom** [firasdib/Regex101#1752]
## Bug Description
The page crashes.

### Reproduction steps

In the python flavor, insert the expression 

(<)?(\w+@\w+(?:\.[a-z]+)+)(?:(1)>|$)

Then, remove the last : so it changes to

(<)?(\w+@\w+(?:\.[a-z]+)+)(?(1)>|$)

### Expected Outcome
'A critical error has occurred' message

### Browser

GoogleChrome 
Versión 99.0.4844.51 (Build oficial) (64 bits)

### OS

Microsoft Windows 7 Home Premium - Service pack 1 - 64 bits

**Comment by working-name** [comment]
![image](https://user-images.githubusercontent.com/16505052/159624488-64f866c0-02d3-4f50-ba8a-f2f992066804.png)
Confirmed. Brave based on Chrome 92 on Windows 11.

**Comment by firasdib** [comment]
Thank you, I'll look into this tonight.

**Comment by firasdib** [comment]
Thank you, I'll push a fix soon.
