### ISSUE TITLE
Major simple regex error

### ISSUE THREAD

**Issue by Just1truc** [firasdib/Regex101#1754]
## Bug Description

Critical error on stupid regex

### Reproduction steps

```c
^[#|~]|[#|~|"\.\o"]
```

### Expected Outcome
flag "#", "~" at end or begin of str

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by firasdib** [comment]
Thank you, I'll push a fix soon.

**Comment by Tesbarmix1** [comment]
> ## Bug Description
> 
> Critical error on stupid regex
> 
> ### Reproduction steps
> 
> ```c
> ^[#|~]|[#|~|"\.\o"]
> ```
> 
> ### Expected Outcome
> flag "#", "~" at end or begin of str
> 
> ### Browser
> Include browser name and version
> 
> ### OS
> Include OS name and version
>
