### ISSUE TITLE
Backslash matching problems with Javascript

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [firasdib/Regex101#1755]
## Bug Description

Matches only 1 backslash instead of 2.

![Screenshot 2022-03-24 195638](https://user-images.githubusercontent.com/16936908/159994115-bff89faa-8004-466a-9576-7e20d2224b3e.png)

Some odd unicode interpretation happening during substitution.

![Screenshot 2022-03-24 201512](https://user-images.githubusercontent.com/16936908/159994170-cfe0fe58-6ee7-447e-af57-62ef3a369e97.png)

### Reproduction steps

https://regex101.com/r/xeKLG5/1

### Expected Outcome

Backslashes should be matched and substituted as they are in Javascript engines.

### Browser
Chrome 99.0.4844.82

### OS
Windows 11

**Comment by firasdib** [comment]
What exactly is the problem? The output looks correct to me.

![image](https://user-images.githubusercontent.com/1335165/160019557-c20cf0f9-f6de-4a46-a9f4-80158548a2f8.png)

**Comment by firasdib** [comment]
I think I see the confusion.

The "TEST STRING" is a raw string, it does not evaluate any string escapes. That means, `\\b` is literally representing three characters, `\`, `\`, and `b`.

You can look at the code generator to find the correct code:

```js
const regex = /\\b/gm;
const str = `foo\\\\bar`;
const subst = `\b`;

// The substituted value will be contained in the result variable
const result = str.replace(regex, subst);

console.log('Substitution result: ', result);
```

**Comment by s-h-a-d-o-w** [comment]
Ohhh, right. Thanks and sorry about that!
