### ISSUE TITLE
Possessive Quantifier displays incorrect example

### ISSUE THREAD

**Issue by c-eg** [firasdib/Regex101#1756]
## Bug Description
Possessive Quantifier `a*+` displays incorrect example
Example shows:
```regex
/\d++./
123
```

### Reproduction steps
See POSSESSIVE QUANTIFIER example.

### Expected Outcome
```regex
/\d*+./
123
```

### Browser
Firefox Version 98.0.1 (64-bit)

### OS
Include OS name and version
Windows 11 Pro (10.0.22000 Build 22000)

**Comment by working-name** [comment]
Hello, thank you for letting us know! I'm sure you already know, it's the second quantifier that's the possessive one. We'll get this sorted out.
