### ISSUE TITLE
.NET (C#): Fake match with \W

### ISSUE THREAD

**Issue by jgomezprada** [firasdib/Regex101#1760]
![image](https://user-images.githubusercontent.com/26471671/160848131-65d5d61c-867b-402b-8aa0-34c4f5fea0ec.png)

**Comment by working-name** [comment]
Hi @jgomezprada,

Which one of them is a fake match? Does .NET treat things differently in this case?

I don't .NET so I can't test it out, but is there a difference if you run this in the actual code? Probably easier to see if you do a replacement with `#` or something. If you get anything other than 3 of them, please let me know.

**Comment by firasdib** [comment]
It’s related to #1737, I’ll revisit this this weekend and see if the issues I stumbled upon are fixed. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by jgomezprada** [comment]
Match 3 references positions 2-3, but position 3 does not exist. Also, in a null match, the starting position and ending position should be the same.

**Comment by firasdib** [comment]
Thank you, this will be fixed in the next release.
