### ISSUE TITLE
Negative `\\` lookbehind works in regex101 but not in PHP 

### ISSUE THREAD

**Issue by cyrillbolliger** [firasdib/Regex101#1762]
## Bug Description
The pattern `(?<!\\)foo` works regex101 but not in PHP.

### Reproduction steps
Test `(?<!\\)foo` on regex101:
![image](https://user-images.githubusercontent.com/12530490/161228175-f01d257d-144c-47fa-8976-9f83aaf25c5d.png)

Test `preg_match( "/(?<!\\)foo/", "foo" );` in PHP:
```bash
$ php -r 'preg_match( "/(?<!\\)foo/", "foo" );'
Warning: preg_match(): Compilation failed: missing closing parenthesis at offset 9 in Command line code on line 1
```
Tested with PHP 5.4.34, PHP 8.0.9 and PHP 8.1.3

### Expected Outcome
Pattern fails in regex101 as well.

### Browser
Firefox 98.0.2 (64-bit)

### OS
```bash
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -r
5.13.0-39-generic

$ php --version
PHP 8.0.9 (cli) (built: Jul 30 2021 00:37:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies
    with Xdebug v3.1.1, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by firasdib** [comment]
In the menu on the left there is a "code generator" button, click that and copy the code. Your PHP implementation is not correct.
