### ISSUE TITLE
C# implementation of regular expressions seems to be stricter than the one in Regex101 service. Not always expression which works here, works also in real code.

### ISSUE THREAD

**Issue by polek81** [firasdib/Regex101#1763]
### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by firasdib** [comment]
Could you please elaborate with a real example? The website runs the .NET regex engine natively, so it should be identical.

**Comment by firasdib** [comment]
Can you please provide more info?

**Comment by polek81** [comment]
Hi there,

Yes, i will. I will provide it tomorrow morning, if I have access to my
computer. But in general, the problem is related to quantifiers, I think.
Sometimes expression works and after placing it into c# code, it fails. The
reason is lack of, or improper (as it appeaes) quantifiers. I think, that
it should work the same way at site and in code. But, if I attach the
example You'll see.

Thanks for reply.
---
Grzegorz

wt., 5 kwi 2022, 18:29 użytkownik Firas Dib ***@***.***>
napisał:

**Comment by firasdib** [comment]
@polek81 sure, thank you. Please include a permalink to regex101.com as well

**Comment by firasdib** [comment]
Closing since there is no reply.
