### ISSUE TITLE
Allow specifying regex as a complete Python string literal (not just the part between quotes)

### ISSUE THREAD

**Issue by vbrozik** [firasdib/Regex101#1765]
### Python's string literals
Regex101 is a very useful tool not just for creating new regular expressions but also (maybe more often) for troubleshooting existing regular expressions. For this you need to copy the regex from an existing program.

Complex regexes are often split to multiple lines of code which are most often being delimited by multiple pairs of quotes in Python:
```Python
if match := re.fullmatch(
        r'(?P<hostname>.+)'
        r'_(?P<type>[A-Z]{{2}})(?P<number>\d{1,3})'
        # example: _VS18
        r'.*', base_name):
    ...
```

Modifying the string literal to a single pair of quotes and after troubleshooting modifying it back to a multiline string literal can be complicated and can introduce new bugs into the regex. In addition splitting a regex to multiple lines and inserting comments allow much better structuring and readability without need to use the verbose regex variant. **I think Regex101 should support Python's string literals.** For example it could be a literal like this (the surrounding parentheses needed for the multiline literal can be probably implied):
```Python
        r'(?P<hostname>.+)'
        r'_(?P<type>[A-Z]{{2}})(?P<number>\d{1,3})'
        # example: _VS18
        r'.*'
```
### Python's f-string literals
Next very useful feature would be support of Python's f-strings. Complex regexes are often composed of multiple simple regexes and the natural way of doing this composition in Python is use of f-strings. I think that **it would be really great if Regex101 supported (simplified) variable assignments and (simplified) f-strings** with variable substitutions. The last statement-expression (here between the parentheses) would be the regex to troubleshoot:
```Python
RE_ISO_DATE = r'\d{4}-\d{2}-\d{2}'
RE_ISO_D_TIME = r'\d{2}-\d{2}(?:-\d{2})?'
(
        fr'(?P<hostname>.+)'
        fr'_(?P<type>[A-Z]{{2}})(?P<number>\d{{1,3}})'
        # example: _VS18
        fr'_(?P<date>{RE_ISO_DATE})-(?P<time>{RE_ISO_D_TIME})'
        # example: _2019-12-31-23-59-59
        fr'.*'
)
```

I had to modify the last example to [this in Regex101](https://regex101.com/r/Vz84BN/1):
```Python
r'\A(?P<hostname>.+)_(?P<type>[A-Z]{2})(?P<number>\d{1,3})_(?P<date>\d{4}-\d{2}-\d{2})-(?P<time>\d{2}-\d{2}(?:-\d{2})?).*\Z'
```

**Comment by working-name** [comment]
Hello!

I'd like to preface my comment with the following: I'm personally triggered, so I may be harsher than needed.

The site implements many flavors used in various programming languages. The amount of added maintenance needed to support all ways of writing regexes in each language is most likely not feasible, and bound to grow as flavors expand and languages evolve. That being said, it's firasdib's opinion and decision that matters.

Additionally, I see your examples as more of a developer's choice on how to structure their code. No one should have a say in it, but at the same time, I don't think it's fair to expect tools to understand your structure. It's convenient, I understand that part, and I'm not against it.

The personal rants:

For suggestion 1, I have a question: why do people do such ungodly things to regexes in python? I see the same thing in go programs. Regex has its own `/x` which allows for comments and ignoring of spaces (python feature, but for go it's a no go 😉 ). I find that option much more desirable for ease of debugging, portability, and readability.

If this way of splitting regexes is a ubiquitous way of handling it in the python world, I think it may not have been thought through properly.

Suggestion 2: I see why you'd probably want to have a variable containing a regex injected into a regex - to avoid duplication of the same pattern. PCRE has `(?(DEFINE)...)` for that as part of the regex engine itself. A second option might be to insert a dynamic string in there, escaped for regex. But in this particular example it only appears once, I don't find much use for having variables that are regex themselves included in a larger regex. It just gets in the way of reading the regex.

**Comment by firasdib** [comment]
@working-name hit the nail on the thread really.

You should be using the free-spacing mode (where you can add comments). See this example with your regex: https://regex101.com/r/nVWfdt/1

**Comment by vbrozik** [comment]
Thank you for your replies. Now I understand that it is not your goal to implement better support for specific features of individual programming languages. I also understand that Python support is included mainly for its popularity not because the language is close to you. I am adding some points just to try to better explain what I meant:

* I really see Regex101 as a great tool for troubleshooting existing regexes - this includes regexes in programs written by someone else where I did not chose the programming style.
* Regular expressions is just a tool used in many programming languages (tools and programs are a different story) the overall writing style should at the first place follow the style of the programming language.
* Indeed the shown way of splitting a long string literal to multiple lines is in most cases the preferred way in Python. I really do not understand what "ungod" things you see happening there. It is just a string literal, nothing harming the regex inside.
* It feels soo awkward that in Regex101 **you have to select the string literal delimiters** but you cannot simply write or paste the string literal itself.
* I know about the verbose regexes and how they work. I have even mentioned them in my original post. They have some drawbacks:
    * In some cases an escaped space is difficult to identify without detailed inspection (if the backslash is followed by a space or not).
    * Escaped spaces can be too distractive for someone in some cases.
    * When you structure regex using whitespace it is difficult to maintain the structuring indentation of the regex.
    * Regarding portability:
        * I see the opposite :) There are regex implementations which do not support verbose regexes.
        * When you need to transfer regex from one language to a different one you must solve also other things so changing the string literal delimiters and comment markers is just an insignificant detail in my opinion.
    * Nowadays programmer text editors with lexical analysis help a lot (syntax highlighting, interactive help, code completion, code refactoring). Support of there features for nested languages (like regex, SQL, HTML) is extremely difficult and in many cases probably impossible so it really makes sense to use the constructs of the main language - like comments and string substitutions (using f-strings in Python).
* Regarding f-strings: The `(?(DEFINE)...)` construct is only for the single regex it is used in. The use of string composition / substitution (e.g. Python f-strings) is to compose a more complex regex from multiple simple regexes which could be generic and reusable. It is to be used across multiple regexes (not just in a single one). Of course in my example I showed just a single final regex so you could not see how the simple regexes are reused. The aims are:
    * Avoid code duplication. This brings multiple advantages most programmers are avare of.
    * Increase readability by replacing implementation details by descriptive identifier.

Maybe I will implement a preprocessor which would convert a Python's string literal to the string content acceptable by Regex101. Will you be willing to include such an opensource preprocessor into Regex101?
