### ISSUE TITLE
re.error: look-behind requires fixed-width pattern

### ISSUE THREAD

**Issue by troykel** [firasdib/Regex101#1767]
/(?<=www.|\/\/)[^www.]*/gm

The above regex appears to work on your site, but when I use the same exact regex on codewars I get the above error.
Why is that?

On your site it matches domain names and a couple null chars (I don't want the null chars, but I haven't figured that out yet), but on codewars I don't even get that far, I get the error shown above.

**Comment by working-name** [comment]
Hi @troykel 

That sounds like you may be trying this regex in another flavor than python on the site. If I try your regex with python selected I get the same message python 2.7 and 3.8 spit at me which is this ticket's title.

Also, FYI `[^www.]*` does not mean "match anything that is not www. 0 or more times", it actually means "match any character that is not a `w` or a `.` 0 or more times".

The null match is a positional match which is normal given your regex comprised of a lookbehind which does not consume/match but just peeks, and the option  to match 0 characters.

Hope this helps. For further regex questions please click the live help icon on the left sidebar.

**Comment by troykel** [comment]
@working-name You're right! Apparently, the default flavor used was PCRE2, but I was coding in Python, and with it set at Python, it gives the same exact error!  Thank you for the tips you gave me!  I'll keep that in mind!  Would you happen to know how to accomplish the same thing in Python regex?

**Comment by working-name** [comment]
You could try alternating 2 positive lookbehinds `(?:(?<=www.)|(?<=//)` but since I don't have the full picture this may be relatively useless. Please visit us in the live chat if you need help coming up with a regex - no registration required.

**Comment by troykel** [comment]
I'm trying to match only the domain name part of a URL, so https://www.sololearn.com/python would match sololearn only.

**Comment by troykel** [comment]
So far I have "[^'https://www.'] [a-z]+(?>=[.a-z]+)"

**Comment by working-name** [comment]
Please click the live chat icon on the left sidebar and you'll get a new tab with a web IRC client. Once you join you can paste your regex101 link with an explanation of what you're trying to achieve and someone will help out.

We're trying to keep github issues focused on site-related bugs and issues rather than regex help.

Thank you for understanding!
