### ISSUE TITLE
Negative lookahead is shown as negative lookbehind

### ISSUE THREAD

**Issue by aljohnston112** [firasdib/Regex101#1768]
## Bug Description
Negative lookahead is shown as negative lookbehind in the explanation and when hovering over it in the expression.

### Reproduction steps
I am using this regex
(?<![^ ])\\(?=[1-9])(?![^ ])
and being told that (?![^ ]) is a negative lookbehind

### Expected Outcome
Being told that (?![^ ]) is a negative lookahead

### Browser
Firefox 98.0 (64-bit)

### OS
Fedora 34 (Workstation Edition)

**Comment by working-name** [comment]
Thank you, we'll get this sorted shortly.

By the way that's an invalid regex, can't escape the `(` that should be part of the positive lookahead. 😬

**Comment by firasdib** [comment]
Thank you, typo on my part.
