### ISSUE TITLE
Browser sniff redirect to browsehappy traps browsers like Edge Dev

### ISSUE THREAD

**Issue by enwinn** [firasdib/Regex101#1769]
Running Microsoft Edge Dev Version 101.0.1210.2 (Official build) dev (64-bit) results in being incorrectly shown your Happy Browser nag page:

```
Unfortunately it seems your browser does not meed the criteria to properly render and utilize this website. You need a browser with support for web workers and Web Assembly.

[Please upgrade your browser and come back](http://browsehappy.com/)

```
This kind of browser sniff redirect is always fraught with problems like this. Suggest you remove it as it will require constant vigilance and changes to accommodate not only bleeding edge browser versions but current stable and LTS browser versions so you do not inadvertently display this page to visitors with perfectly valid browsers.

You should also note you have a misspelling with the word "meet".

**Comment by working-name** [comment]
Hi @enwinn,

Is there maybe something running like an add-on or maybe web workers/assembly are not allowed to run?

![image](https://user-images.githubusercontent.com/16505052/161616972-a6588c6a-bfc5-4a5c-8872-89dc6fbc97df.png)

I'm not entirely sure but I don't think the useragent is a determining factor in displaying the message. It's just your browser capabilities - either artificially crippled, or normally unavailable.

**Comment by firasdib** [comment]
There is no browser detection, its a feature detection, which ensures that webassembly, web workers and promises exist. 

Some of the security modes in Edge disable web assembly, which has been the reason for this previously.

**Comment by enwinn** [comment]
> Hi @enwinn,
> 
> Is there maybe something running like an add-on or maybe web workers/assembly are not allowed to run?
> 
> ![image](https://user-images.githubusercontent.com/16505052/161616972-a6588c6a-bfc5-4a5c-8872-89dc6fbc97df.png)
> 
> I'm not entirely sure but I don't think the useragent is a determining factor in displaying the message. It's just your browser capabilities - either artificially crippled, or normally unavailable.

Yes, confirming Edge's "Enhanced" or "Added" security setting is apparently triggering this. My basic critique still stands as the redirection to Happy Browser is not relevant in this use case.

If you want to incorporate a helper like this, then I would recommend following the example at https://nodejs.dev/learn to see how they do it with the StackBlitz API:

![image](https://user-images.githubusercontent.com/11488937/161630360-8c09b666-983f-46d2-a6d5-12ee2ac10b2d.png)

The referenced URL in the image is: https://developer.stackblitz.com/docs/platform/browser-support/ but their Cookie Blockers and other mitigations page is more helpful: https://developer.stackblitz.com/docs/platform/third-party-blocker

Much better than a generic scolding about using the "wrong" browser.

-Eric

**Comment by firasdib** [comment]
@enwinn I don't follow, are you upset by the wording of the message?

**Comment by enwinn** [comment]
@firasdib No, just pointing out that the problem is with a setting in this scenario but you are redirecting to a page that tells people they are using a browser that is out of date. It isn't helpful and actually adds confusion.

I really like this site. I think you will upset people with this redirect. Instead just display a message like "web assembly support not detected - some features may not work", or similar for whatever feature checks you are running.

Better to keep them on your site rather than redirect to browserhappy.com

**Comment by designgears** [comment]
I realize this is a closed topic but I started running into this as well with version 100+. Clicking "Added Security" left of the URL and disabling it for the site resolves the issue. Maybe add some basic settings to check based if the browser version is known to support what is needed.

**Comment by working-name** [comment]
> Maybe add some basic settings to check based if the browser version is known to support what is needed.

"Added Security" disables something in the browser, meaning the feature detection is correctly identifying a browser that does not have what it needs to run the site. 

If it was browser-based detection you would not be able to turn off added security and have the site accept the same browser it rejects. Similarly, whitelisting a browser is going to confuse people even more because they would just have a seemingly broken site with little indication as to why.

**Comment by designgears** [comment]
> > Maybe add some basic settings to check based if the browser version is known to support what is needed.
> 
> "Added Security" disables something in the browser, meaning the feature detection is correctly identifying a browser that does not have what it needs to run the site.
> 
> If it was browser-based detection you would not be able to turn off added security and have the site accept the same browser it rejects. Similarly, whitelisting a browser is going to confuse people even more because they would just have a seemingly broken site with little indication as to why.

Just add some basic messaging to let the user know what the issue probably is. Not sure what you're going on about over thinking what I said.

**Comment by firasdib** [comment]
I’ve seen this from more Edge users. I will look into adding an additional message on the subject. 

Thank you. 


Vänliga hälsningar / Best regards,

Firas Dib
