### ISSUE TITLE
"^printf" throws critical error

### ISSUE THREAD

**Issue by xhamyd** [firasdib/Regex101#1770]
## Bug Description
![image](https://user-images.githubusercontent.com/13244158/161874528-9d34610e-7f1c-4dcd-8cea-c2351baf6fd5.png)

### Reproduction steps
I set up several unit tests for Python regex testing, then typed (incomplete entry) `^printf` into the regex bar. Screen then immediately crashed, and so took screenshot.

### Expected Outcome
Site shouldn't crash in the middle of entering a regex

### Browser
Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### OS
Windows 10 Pro Version 21H2, build 19044.1586

**Comment by firasdib** [comment]
Thank you! I will look into this later tonight.

**Comment by firasdib** [comment]
Thank you, I have a fix lined up for the upcoming release.
