### ISSUE TITLE
identifying lookaheads as lookbehinds

### ISSUE THREAD

**Issue by RedDragonWebDesign** [firasdib/Regex101#1771]
## Bug Description
![2022-04-06_030708](https://user-images.githubusercontent.com/43397938/161951796-740f02f7-d5d3-4e19-9e2d-6af9ddd38c67.png)
`?!` is negative look**ahead**, right? But hovering over it is identifying it as negative look**behind**. 

### Reproduction steps
1) Choose any flavor except Golang
2) Enter `/(?<!')'(?!s)[A-Za-z][^']{3,40}'/gm`
3) Hover over `(?!s)`

### Expected Outcome
Should say negative lookahead, not negative lookbehind

### Browser
Chrome 100.0.4896.60 (Official Build) (64-bit)

### OS
Windows 10 Home 19043.1586

**Comment by vincelord** [comment]
I can confirm this, wanted to file a bugreport myself today.

**Comment by vincelord** [comment]
![chrome_x7jsKZpb0x](https://user-images.githubusercontent.com/5861148/161953256-2087bbec-fa79-4908-ab7c-2b08b3e45088.png)

**Comment by vincelord** [comment]
![chrome_x7jsKZpb0x](https://user-images.githubusercontent.com/5861148/161954235-6bd9be72-31c9-4942-9d61-acfbc62eacc1.jpg)

**Comment by working-name** [comment]
Thank you so much for the report!

Potentially the same as #1768 - will be addressed with the next pushed update.

**Comment by firasdib** [comment]
Thank you, will be fixed in the upcoming release.
