### ISSUE TITLE
restart every line (like grep) because `(*COMMIT)^\+* \. \K.*?$` will fail the rest of the lines

### ISSUE THREAD

**Issue by FuPeiJiang** [firasdib/Regex101#1773]
## Feature
```
+ '[' -f /etc/bash.bashrc ']'
+ . /etc/bash.bashrc
```
`(*COMMIT)` will fail, and the next line(s) won't be matched/attempted

grep would split the lines, and attempt matching `(*COMMIT)^\+* \. \K.*?$` on every line
attempt
`+ '[' -f /etc/bash.bashrc ']'`
failed

attempt
`+ . /etc/bash.bashrc`
matched `/etc/bash.bashrc`

the regex engine at any time does not see multiple lines, grep splits the lines and calls the regex engine once per line
___
maybe this should be a custom regex flag, for it work on every flavor ?
called `custom: restart every line`

**Comment by working-name** [comment]
Hi @FuPeiJiang,

I don't think I get what you're trying to say here. But allow me to ask a few questions:

1. do you expect `(*COMMIT)^\+* \. \K.*?$` to match `+ '[' -f /etc/bash.bashrc ']'` ? It won't because there isn't a space and a period after the + at the beginning of the line. Regardless of the COMMIT verb.
2. grep itself reads files line by line, therefore the regex is constrained to that. If you want to try a regex on a whole file have you tried some other tool like `perl -pe -0777` ?
3. If the custom regex flag is supposed to mirror reading a file line by line, then you can already do that with `/gm` and your current regex which uses `^` (beginning of line due to `/m`) and `$` (end of line due to `/m`). Does that behave as you expect?

**Comment by FuPeiJiang** [comment]
@working-name 
> 3. If the custom regex flag is supposed to mirror reading a file line by line, then you can already do that with `/gm` and your current regex which uses `^` (beginning of line due to `/m`) and `$` (end of line due to `/m`). Does that behave as you expect?

normally, `/gm` correctly mirrors 'executing regex on each line'
but once `(*COMMIT)` fails, all the rest of the lines are skipped
so it doesn't 'execute regex on each line', **it skipped lines!**

___
bash
```bash
printf "+ '[' -f /etc/bash.bashrc ']'
+ . /etc/bash.bashrc" | grep -oP '(*COMMIT)^\+* \. \K.*?$'
```
output:
`/etc/bash.bashrc`

**Comment by FuPeiJiang** [comment]
if there's a way for `(*COMMIT)` to fail to the next line, instead of failing all the rest, that'd be great

I think I can remove the `^` since with `(*COMMIT)`, it can't backtrack
```bash
printf "+ '[' -f /etc/bash.bashrc ']'
+ . /etc/bash.bashrc" | grep -oP '(*COMMIT)\++ \. \K.*?$'
```
___
I don't know why I landed in `(*COMMIT)`, I don't think I even need it

**Comment by FuPeiJiang** [comment]
> Please refer back to point 1 of my initial reply. + ' will never be matched by \+* \. - those are two different characters. It has nothing to do with commit.

this is intended behavior, that the 1st line doesn't match
but I want the 2nd line to match

___

I don't know how to explain this, run both, on regex101, on grep, observe different output

regex101: no match
grep: `/etc/bash.bashrc`

why does grep report a match and regex101 doesn't ?

> it has nothing to do with commit.

then can you explain why different output ?

> grep doesn't tackle more than 1 line at a time.

the feature I want is a custom flag to only tackle 1 line at a time

**Comment by working-name** [comment]
@FuPeiJiang grep only sees one line at a time, the site sees the whole input, therefore regex also acts on the whole string. 

#### For the site:
The verb *COMMIT will cause the whole match to fail, as in give up EVERYTHING, so long as the pattern fails to match once. As you already stated, the first line is expected NOT to match, therefore at that point the whole match is dropped. If you flip the lines, and you already have a match on `+ . /etc/bash.bashrc` but the second line is considered, again, everything gets dropped regardless.

#### For grep:
Only one line of text is considered at a time, irrespective of however many lines before or after this one. Therefore you could infer that the verb has some effect on the next line, but it's not correct. To the regex, there was never any other text than the current line, nor does it expect another line after this one.

Maybe you're looking for something like an atomic group `(?>...)` instead?

---

I get why you'd want a custom flag to treat each line as a test string of its own, it's been requested in the past (see #1608 ). However, the response has generally been that the amount of work required for such a feature is not quite feasible. Additionally, unit tests are built to do just that - i.e. https://regex101.com/r/WOf8wl/1

There are some ease-of-use concerns quoted by many, feel free to make your case again for the feature if that's the case for you as well.

**Comment by FuPeiJiang** [comment]
`https://github.com/firasdib/Regex101/issues/1608#:~:text=bunch%20of%20separate%20%3Ctextarea%3E`

I don't want a bunch of separate `<textarea>`
or else I can't copy paste

I'll have to copy paste line by line

oh lol
> It might be nice to have, but in my mind I can't get over the fact that I would have to paste each case in a new box... it's much faster to paste it all in 1 box and then use /m with ^ and $.
https://github.com/firasdib/Regex101/issues/1608#issuecomment-867265460

___
> It is not really the same since expressions like this [^>]* wraps to the next line
https://github.com/firasdib/Regex101/issues/282#issuecomment-102152579

that's a good other case (where output is different)
___
it is a duplicate of
https://github.com/firasdib/Regex101/issues/359, https://github.com/firasdib/Regex101/issues/282, https://github.com/firasdib/Regex101/issues/795
___
so now we're stuck at : hard to implement..

**Comment by working-name** [comment]
Seems we have come to the same point as 795 😬 will close this in favor of the other ticket to make it easier to track progress/decision making.

Speaking of that `[^>]*` wrapping to the next line, just stick an `\n` in there, problem solved 👍
