### ISSUE TITLE
I think you have a bug 

### ISSUE THREAD

**Issue by javautil** [firasdib/Regex101#1774]
### Reproduction steps
Regex

(?<leftparen>\()|(?<rightparen>\))|(?<command>with|select|update|delete|drop|alter|create)|(?<literal>['][^']*')|(?<comma>[,])|(?<op>[-|&|=\*\+]|\|\|)|(?<text>[\w\s]*)|(?<bind>:\w*[^':]*)|(?<concat>\|\|)|(?<semi>[;])

expression

with customer_no_sale as (select  etl_file_id, ship_to_cust_id\n 
                      from etl_customer\n 
                      where etl_file_id = :etl_file_id - \n
                      except || 
                      select nvl(dog),etl_file_id, * ship_to_cust_id\n 
                      from etl_sale\n  +
                      where etl_file_id = :etl_file_Id\n
                    )\n
                      select etl_file_id, count(*) row_count\n 
                     from customer_no_sale\n
                      group by etl_file_id;;
                      
java parser

### Expected Outcome

should find leftparen.  Left paren is found when I run in java

### Browser
google chrome

### OS
linux

**Comment by working-name** [comment]
Hi @javautil 

Could you provide a regex101.com link showing the behavior? What you pasted does not reproduce not matching a left parenthesis.

Thanks!

**Comment by working-name** [comment]
@javautil Please feel free to reply when ready, will reopen then.
