### ISSUE TITLE
What does `null` mean in the explanation?

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#1775]
- fail to match (no match)
- find a zero-length match

Which meaning is the right meaning? 

I think there are several inaccurate token explanation on the website:

> **(?=)** — *null*, matches any position

According this explanation, `null` means zero-length match.

> **(?!)** — *null*, matches any position

This explanation is incorrect, `(?!)` or `(?<!)` always fails to match, no match is found.

> **[]** empty character class — matches *null*

`[]` never matches anything, no match is found.  If `null` means zero-length match, this is not a correct explanation.

**Comment by Silverfishnet** [comment]
Zero length match
