### ISSUE TITLE
"Portuguese (Brazil)" is misspelled in language select field in settings

### ISSUE THREAD

**Issue by geekley** [firasdib/Regex101#1776]
## Bug Description
`Portuguese (Brazil)` is misspelled in language select field in settings. It appears as `Portogueze (Brazil)` (o and z are wrong).
This string does not appear in the translation JSON file downloaded from https://r101.cf/projects/site/regex101-com-2/pt_BR/#information so it's likely hard-coded.

### Reproduction steps
Click the first field "Language" at https://regex101.com/settings
I don't know if this typo appears in other places.

### Expected Outcome
Should be `Portuguese (Brazil)`.

### Browser
Irrelevant

### OS
Irrelevant

**Comment by firasdib** [comment]
Thanks, will be fixed in the next release.
