### ISSUE TITLE
CodeMirror highlights not updating after modification

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#1777]
## Bug Description
Changes to the dimensions of the REGULAR EXPRESSION box do not update code highlighting within TEST STRING, which can leave visual artifacts.

https://regex101.com/r/7lZI4m/1

### Reproduction steps
1. Create a multiline pattern; ideally, it should span 4 or more lines so the REGULAR EXPRESSION box enlarges.
1. Fill the TEST STRING with enough text that scrollbars appear. The pattern should match some or all of the visible text.
    ![7lZI4m 1](https://user-images.githubusercontent.com/1168697/163452719-008cba28-510e-4811-9b6f-4eef79227012.png)
1. Modify the pattern until the REGULAR EXPRESSION box shrinks. For example, remove newlines from the pattern so the box shrinks from 5 lines to 1. This should not change the meaning of the pattern, so the text is still highlighted.
    ![7lZI4m 2](https://user-images.githubusercontent.com/1168697/163452961-6eb12cec-8283-43f3-814d-e9d98327c7a2.png)
1. Scroll down the TEST STRING; observe the bottom lines.
    ![7lZI4m 3](https://user-images.githubusercontent.com/1168697/163453266-9461fcd3-e892-41f7-a525-4cad1e1a2dd7.png)

### Expected Outcome
1. When the REGULAR EXPRESSION box resizes, code highlighting should probably be refreshed.
    - The highlight recalculation probably does not need to fire each time the pattern is modified unless the box dimension is also resized as a result.

### OS and Browser
* Windows 10: Chrome 100.0.4896.88
* Windows 10: Vivaldi 5.2.2623.33 (Chromium variant)
* Windows 10: Edge 100.0.1185.39
* MacOS 12.3.1: Chrome 100.0.4896.88
* Arch Linux: Firefox 99

**Comment by firasdib** [comment]
I have a fix locally for this, will be released in the next update.
