### ISSUE TITLE
Unit Test groups are incorrect for C# Expressions

### ISSUE THREAD

**Issue by bburgess19** [firasdib/Regex101#1779]
## Bug Description
When using a C# expression with the pattern whitespace and explicit capture flags on, the unit test doesn't correctly report the groups that participated in the match. In my expression, there are two named capture groups that have the same name: "Qty" and "UM." When using the test to check the result of the group "UnitPrice," the test reports, "Group 7 [UnitPrice] no longer exists in the pattern or did not participate in the match." When looking inside the duplicate group "Qty," inside of the test explorer, it reports the unit price's value.

### Reproduction steps
I made my expression public for analysis here [https://regex101.com/r/kYuxbz/1](url). The error can be reproduced using the last test in the list.

### Expected Outcome
I would expect all of the groups to be captured in one group, even if there is a duplicate named group.

### Browser
Safari 15.4

### OS
Mac OS Monterey 12.3

**Comment by working-name** [comment]
It may have something to do with the group IDs/group name mapping for the dropdown.

Given the particular string in Unit Test `File name: 23712901. Foreign currency—unit price and value go to three decimal places` (last one), it should have 5 capture groups, and therefore capture group 4 is really `unitPrice` but the dropdown selection of the unit test offers something different.

If one manually selects Group 4 from the unit test dropdown, then the unit test will succeed in `starts with` `0.080`.

![image](https://user-images.githubusercontent.com/16505052/164304038-44f20084-f973-4f69-a646-47e0cb0ebb19.png)

**Comment by bburgess19** [comment]
That's very interesting. I'll use that workaround for now. Thank you!

**Comment by firasdib** [comment]
The URL you posted seems to be deleted.

**Comment by firasdib** [comment]
I'm fairly sure this will be related to https://github.com/firasdib/Regex101/issues/1861 which is now fixed.
