### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by jumbojing** [firasdib/Regex101#1780]
## Bug Description

如图

![image](https://user-images.githubusercontent.com/10215735/164340357-39ba72a1-a150-49ef-99dd-16f094e8f937.png)

<img width="803" alt="image" src="https://user-images.githubusercontent.com/10215735/164340431-6defec82-5020-4ad2-bcf4-a0cf08ddd310.png">

![image](https://user-images.githubusercontent.com/10215735/164340614-1e63cce1-3767-411f-bf49-21bb963cc4f7.png)

**Comment by jumbojing** [comment]
https://regex101.com/r/xvStkx/1

**Comment by working-name** [comment]
Hi @jumbojing,

Simply put, nothing is wrong. Your debuggex link shows the same match end if you scrub the position.
![image](https://user-images.githubusercontent.com/16505052/164370367-a79c3008-2a30-479a-a7d5-2c86da764637.png)

The rest of the stuff is highlighted as if `/g` was on, but not sure why. Enable the same flag on regex101 to see the same matches.

**Comment by working-name** [comment]
Closing for now, please feel free to continue the discussion, will reopen if necessary.
