### ISSUE TITLE
Allow list of strings/texts

### ISSUE THREAD

**Issue by Akxe** [firasdib/Regex101#1786]
## Feature
Instead of using single input for "test string" we could have multiple of them. This way you can easily test regulars that need not to be global and multiline while preserving the convenience of just pasting in an expression that ou need to test with multiple strings.

**Comment by working-name** [comment]
Hi @Akxe,

Please follow and/or add your voice to #795 

Just FYI, unit tests can do that already, albeit with a little more work - copy pasting each "input" in its own box.

**Comment by firasdib** [comment]
Multiple text strings will be supported in the next release.
