### ISSUE TITLE
Sometimes we are not able to check password we entered on new line using it on monzilla ubuntu

### ISSUE THREAD

**Issue by Joy20-learner** [firasdib/Regex101#1787]
## Bug Description
at times  they dont check password entered in next line this is a serious issue as we need to check more than one passwords

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by working-name** [comment]
Hi @Joy20-learner are you sure you're in the right spot?

**Comment by Joy20-learner** [comment]
This is one example according to my  regex this all of my passwords are
match but in this they are not shown as match

**Comment by working-name** [comment]
Sorry but I don't see anything if you meant to post a regex101.com link or something. Try again?

**Comment by Joy20-learner** [comment]
What i am trying to say is i am not able to test more than one password so
i had raised this issue after refreshing the webpage also tried after
clearing all cookies

**Comment by working-name** [comment]
This site doesn't test passwords, it allow you to write, test, and debug regular expressions. So unless you wrote a regex, it doesn't come with one.

If you're having issues coming up with a regex, click the live help icon in the left sidebar - that will take you to a public channel with volunteers who like helping out.

If you believe the site is misbehaving, please follow this up with a saved link (left sidebar, top) showing that problem.
