### ISSUE TITLE
Regex Debugger: edit regex in Debugger, add < & > buttons for debug, max steps per Match #

### ISSUE THREAD

**Issue by stefan123t** [firasdib/Regex101#1788]
## Feature

Thanks @firasdib for creating and maintaining this cool, educational and very useful tool in the first place!

---

I have just discovered the RegEx Debugger and found it truly invaluable for understanding lazy against greedy qualifiers.
I want to create a couple of regex for lnav a Logfile Navigator tool which should run as fast as possible. hence I would like to debug them.

I have used the following regex: **/**`^.*?some-field:.*(\n[^2].*$)*`**/gm**
and this example logfile:
```
2022-08-29 10:11:12,123 some-field: found, another-field: not found
blabla
bla bla
bla
bla bla bla
2022-08-29 10:11:12,123 another-field: not found
blabla
bla bla
bla
bla bla bla
2022-08-29 10:11:12,123 another-field: not found, some-field: found something
blabla
bla bla
bla
bla bla bla
```

This allows me to scan **multiline** log-messages and includes all following lines where the next line does not start with a "timestamp" `(\n[^2].*)`. Should work until Futurama :rocket: becomes a Reality Show or someone logs a 2 as the first character in his multiline log.

---

Anyway here are the feature requests in order of difficulty to implement:

1. In order to change the regex I am debugging / simulating I have to close the dialog, change the regex in the main window and open the debugger again.
It would be nice to either 
* add an input box (above the slider, just like on the main window) that lets you change the current regex. 
Upon changes to this box the Matches and Steps would need to be recalculated and the other dialog updated.
* have the debugger integrated in the main window / UI by showing the debugger progress of the string e.g. with a dashed box overlay. 
This is probably much more difficult, but would possibly allow to keep the coloring from the main UI for matches and groups too.

2. I have found out that I can use the cursor keys to navigate to the next / previous step of the Debugger. 
To make this more obvious, please add two buttons to the toolbar below the slider: 
* `|<` (go to beginning) 
* `<<` (decrease speed) 
* `<` (-1 step) **added**
* (`>/[]`) (play/pause) *blue*
* `>` (+1 step) **added**
* `>>` (increase speed)
* `>|` (go to end)

3. The example has calculated the number of steps it takes for each Match to either Match / fail.
Now I can switch debugging between the Matches and all looks good until I have a Match found/failed which takes more than the default max 200 steps in the debugger.
Here I can insert a number higher than the actual steps, eg. 500 and the Debugger would already enforce the max of 253 steps for Match 2.
Please adjust that the max for the slider always is set to the number it took for each Match to be found/failed from the list on the left.
This way the slider can use the full range for each Match whilst debugging.   
* Match 1 found in 62 steps
* Match 2 found in 253 steps
* Match 3 failed in 1 steps

**Comment by firasdib** [comment]
I've made some changes to reflect your ideas. You will not be able to edit the regex in the debugger, but the rest will be available.
