### ISSUE TITLE
Python flavor doesn't recognize multi-digit group references of the form \xx in replacement string

### ISSUE THREAD

**Issue by yanqui-uxo** [firasdib/Regex101#1790]
## Bug Description
Same as title, it's parsed as an octal digit in regex101.com, which does not happen in Python when a raw string is used

### Browser
Firefox 99.0.1 (64-bit)

### OS
Windows 11

**Comment by Netxmay** [comment]
Hai children of God.any one to show me how regex101 works please

**Comment by firasdib** [comment]
I'm unable to reproduce this on the website, perhaps it has been fixed. Closing.
