### ISSUE TITLE
IP address validation fails during capture group and quantifier

### ISSUE THREAD

**Issue by avinashjeevanandham** [firasdib/Regex101#1791]
## Bug Description
Capture group and quantifier not working as expected

### Reproduction steps
Try out the regex
^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$

### Expected Outcome
All valid ip address must be matched

### Browser
chrome 100

### OS
Mac OS

**Comment by working-name** [comment]
@avinashjeevanandham 

Hello, please provide a regex101.com link with an example of strings that should have matched but did not.

**Comment by avinashjeevanandham** [comment]
To my surprise now it works fine.

**Comment by working-name** [comment]
My guess is flags - if you do not have `/g` turned on, it'll only match the first one. Additionally, if you have multiple IPs, one per line, without `/m` the regex will again not match because the `^` and `$` stand for beginning and end of input respectively without the `/m` flag.

Glad it works!
