### ISSUE TITLE
Debugger for C# Engine

### ISSUE THREAD

**Issue by bburgess19** [firasdib/Regex101#1793]
## Feature
I would love it if the C# engine had a debugger! I constantly have to change back to PCRE to find out why my regices fail, and while it's a functional workaround, it's certainly not ideal (not to mention there are idiosyncrasies between the two engines).

**Comment by firasdib** [comment]
Does the .net engine allow for this type of information? I would need to know where the engine is positioned both in the regex and the input string.

**Comment by bburgess19** [comment]
I'm not sure if it offers this information... does the .NET regex engine have to be open sourced in order for you to implement a solution?

**Comment by firasdib** [comment]
@bburgess19 I don't think that parts relevant, only if it can produce the information I need or not ... :) 

Do you want to investigate?

**Comment by nanikit** [comment]
> Does the .net engine allow for this type of information? I would need to know where the engine is positioned both in the regex and the input string.
Where can I find this in PCRE? I want debugger in .net regex too because it is pretty complicated.
