### ISSUE TITLE
Generated SED code does not execute successfully

### ISSUE THREAD

**Issue by suuuehgi** [firasdib/Regex101#1795]
## Bug Description
The `sed` code generated from the Code Generator results in `Invalid preceding regular expression`.

### Reproduction steps

_Test String_
```
\pgftext[left,bottom]{\includegraphics[interpolate=true,width=4.958333in,height=4.763889in]{My_file-name0.png}}
```
_Regular Expression_
```
((?<={)[\w-]+?\.png(?=}))
```
_Substitution_
```
images/$1
```
Click `Code Generator` -> `SED`:

```
sed -E 's/((?<={)[\w-]+?\.png(?=}))/images\/$1/gm;t;d' <<< "\pgftext[left,bottom]{\includegraphics[interpolate=true,width=4.958333in,height=4.763889in]{My_file-name0.png}}"
```

### Expected Outcome
```
\pgftext[left,bottom]{\includegraphics[interpolate=true,width=4.958333in,height=4.763889in]{images/My_file-name0.png}}
```

_Instead_
```
sed: -e expression #1, char 42: Invalid preceding regular expression
```

### Browser
Firefox v. 99
sed (GNU sed) 4.7
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

### OS
```
uname -a
Linux hostname 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by working-name** [comment]
Hi @suuuehgi,

While the code generator is for sed, it does not check that your regex is going to run correctly or not. It just takes what you type, and escapes it for sed to understand.

If we had a sed flavor, then you would get hints that the syntax you're using is not supported. Please refer to sed documentation to figure out what you can and cannot use for sed -E.

Or, maybe one of these things contains what you're trying to do:

- https://quickref.me/sed
- https://devhints.io/sed
- https://gist.github.com/ssstonebraker/6140154

And then of course there are healthier options like using `perl -i.backupmyshit -p -e` or `python -c 'import sys,re;input=sys.stdin.read();#do some regex on your input here...'`

**Comment by suuuehgi** [comment]
Thank you very much for your answer! I'll have a look at python or perl then since I just want it to work and don't feel like learning SEDs own regex syntax is worth the time. I would forget it anyway before I need it the next time.

Maybe you could add a hint that it's merely escaping the command instead of converting it for SED (and probably for the others as well).
