### ISSUE TITLE
QUICK REF description: Java 8, named capture group

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#1804]
When selecting the JAVA 8 flavor, the Quick Reference text states:

    (?<name>...)
    This capturing group can be referred to using the given name instead of a number. Alternative notation for (?'name'...).

The (?'name'...) notation does not appear to be valid, so should probably be removed.

Also, names with underscores appear to give an error:

    (?<foo_bar>

![image](https://user-images.githubusercontent.com/1168697/169871561-8710c24d-19f2-49a7-ad44-0e47c13eb18f.png)

It might be nice if the Quick Reference tip could indicate which characters are allowed (probably just `[a-zA-Z0-9]`).

**Comment by Jesilh** [comment]
Hola

**Comment by firasdib** [comment]
Thank you, this has been fixed.
