### ISSUE TITLE
Minor UI Tweaks

### ISSUE THREAD

**Issue by TonyValenti** [firasdib/Regex101#1805]
## Feature
It would be really nice if the following happened:
1.  The regex box was multi-line.
2. If "Ignore Pattern Whitespace" was toggled, then  the * in the pattern text box would not show.

Here's a mockup of what i'd like:
![image](https://user-images.githubusercontent.com/13609558/170238621-39e56f92-2ca2-4247-9b76-572b19c1d9a6.png)

**Comment by working-name** [comment]
Hi @TonyValenti 

1. I think it already is, unless I'm missing something
![image](https://user-images.githubusercontent.com/16505052/170245697-e54e4964-3179-4768-9ebf-f0242b9a7851.png)

2. I don't quite get it. By the way when you toggle /x you must escape your literal whitespace if you want it to be considered part of the regex.

**Comment by TonyValenti** [comment]
@working-name You're right!  Multiline is already there!  I didn't realize that.

**Comment by working-name** [comment]
@TonyValenti can you help me understand point number 2?

**Comment by working-name** [comment]
I'd be happy to continue the conversation and reopen the ticket - closing for now.
