### ISSUE TITLE
Conditional using positive lookahead appears not to be working

### ISSUE THREAD

**Issue by rotorboy** [firasdib/Regex101#1812]
## Bug Description

Positive lookahead that succeeds when used in "stand-alone", fails when placed into conditional.

### Reproduction steps
test string: "H2K 101"
lookahead and match: <code>(?=\d{1,8}$)(\d{1,8}$) </code>lookahead succeeds and match is found in capture group 1 
lookahead conditional: <code>(?(?=\d{1,8}\z)(\d{1,8}\z)|([a-zA-Z]+[\d_-]{1,8}[a-zA-Z]+)) </code>lookahead now fails, and second pattern is used, matching "H2K" 

if the test string has the "2" swapped for a letter
test string: "HKK 101"
then the lookahead conditional works correctly

### Expected Outcome

expected that lookahead would succeed, the first pattern would be used and the match would be "101"

### Browser
Include browser name and version

Chrome Beta 103.0.5060.33 (Official Build) beta (arm64)

### OS
Include OS name and version

MacOS 12.1

**Comment by rotorboy** [comment]
I tested this several places and getting the same result, so clearly not a regex101 bug... if you happen to know the reason why this is happening, let me know ;-)

**Comment by working-name** [comment]
Hey @rotorboy,

Here's what's going on: https://regex101.com/r/3tqexi/1

To summarize: the condition failed, and it's therefore matching what's after the `|`. The reason for the failure is that you're at the beginning of the input asserting that 1-8 digits should follow which is not the case.

Hope this helps.

**Comment by rotorboy** [comment]
Hey Alan;

Yes, I realized after I closed ticket that I wasn’t paying attention to the fact that lookahead starts at beginning of string; thus it “fails” on first char, which of course triggers the “else” clause. 

Thanks for getting back to me.

-Avi
