### ISSUE TITLE
php code generator

### ISSUE THREAD

**Issue by 4iloveg** [firasdib/Regex101#1815]
## Question
https://regex101.com/r/WgvrOx/1
https://onlinephp.io/c/b3ef1

Please tell me why in this simple example (finds the necessary groups in the editor), but the execution of the code returns emptiness.
What am I missing for identical regex to work in php?

**Comment by working-name** [comment]
@4iloveg hello there,

It's all about line terminators, to be safe cross-platform a `[\r\n]` might serve you better. Keep in mind that the site itself cannot handle/display `\r` because codemirror itself does not support it.
