### ISSUE TITLE
Page blinks when in Print mode

### ISSUE THREAD

**Issue by nofacez** [firasdib/Regex101#1817]
## Bug Description
When you enter Print mode, page starts blinking from light to dark background and it stops only after page reload. 
Print mode with Light theme selected in settings changes theme to Dark

![ezgif-2-eaaeb08cba](https://user-images.githubusercontent.com/64412368/174358585-3fe5b38d-8f05-4d26-9db5-b5fc13a570c3.gif)

### Reproduction steps
1. go to https://regex101.com/
2. set theme style to Automatic
3. press Cmd + P, or Right-click -> Print
...
4. Welcome to a rave party

### Expected Outcome
Not to cause epilepsy 

### Browser
Chrome 102

### OS
MacOS Monterey 12.0.1 with dark mode

**Comment by working-name** [comment]
Confirmed, it only happens when the system is in dark mode and then you open the print dialog. This could be a Monterey issue and the browser craps itself.

**Comment by nofacez** [comment]
Yep

**Comment by firasdib** [comment]
I still can't reproduce, really odd.

**Comment by working-name** [comment]
I tested on a non-apple gpu as well (aka not an M1) and it still happens there too with latest chrome.

**Comment by firasdib** [comment]
@working-name Is your system setup with a specific theme? Light/Dark/Auto? And does it correlate somehow with the setting on the website?

**Comment by working-name** [comment]
Essentially whenever both the OS and the site have the Dark theme on - either from Auto or explicitly selected - the bug exhibits.

**Comment by firasdib** [comment]
I managed to reproduce it. Chrome is doing something funky that causes this, but I have a workaround. Thanks for reporting.
