### ISSUE TITLE
Error in Russian tranlation

### ISSUE THREAD

**Issue by WinterSilence** [firasdib/Regex101#1818]
## Bug Description
Error in Russian tranlation

### Reproduction steps
`вставьте здесь своё значние замены`

### Expected Outcome
`вставьте здесь своё значение для замены`

### Browser
-

### OS
-

**Comment by WinterSilence** [comment]
@working-name done

**Comment by firasdib** [comment]
Thank you, this will be picked up as soon as a new release is made.
