### ISSUE TITLE
[UI] Hamburger icon overlaps with site name in specific window width

### ISSUE THREAD

**Issue by shufo** [firasdib/Regex101#1819]
## Bug Description

The site name and the hamburger button in the UI overlap in specific browser window width, which gives a bad impression.

![image](https://user-images.githubusercontent.com/1641039/175756093-011ea01f-c1d3-493e-b39d-979e985faf4e.png)

### Environment

- Chrome: 102.0.5005.115（Official Build）
- window dimension: 1080x1920

### Reproduction steps

1. Open Dev Tools
2. Set Width to 1080px
3. Reload site (F5 or Ctrl+R)
4. Hanburger icon overlaps with site name

![image](https://user-images.githubusercontent.com/1641039/175756422-ce65bf84-97b0-423a-958f-5591d9bf87a8.png)

### Expected Outcome

Site name and hamburger icon don't overlap.

### Browser

- Chrome: 102.0.5005.115（Official Build）

### OS

```
OS: elementary OS 5.1.7 hera
Kernel: x86_64 Linux 5.4.0-91-generic
```

**Comment by firasdib** [comment]
Thank you, fixed in next release.
