### ISSUE TITLE
PCRE2 Implied 0 minimum quantifier will parse the quantifier string as all literals

### ISSUE THREAD

**Issue by jeffmcneely** [firasdib/Regex101#1822]
## Bug Description
PCRE2 Implied 0 minimum quantifier will parse the quantifier string as all literals

### Reproduction steps
Use regex fo{,2}
Test string "foo"

### Expected Outcome
{,n} should behave the same as {0,n}

### Browser
Chrome 103.0.5060.53
Firefox 100.0.2
Safari 15.4

### OS
macOS 12.3.1

**Comment by working-name** [comment]
Hi @jeffmcneely,

Do you happen to have a link to the spec for that? I'm unable to [find a mention](http://pcre.org/pcre2.txt) of the implied minimum, I only know of the implied infinity for the max position `{1,}`

I also tried it out in pcre2test and it doesn't seem to imply a minimum either:

```py
$ pcre2test -d
PCRE2 version 10.34 2019-11-21
  re> /a{,5}/
------------------------------------------------------------------
  0  13 Bra
  3     a{,5}
 13  13 Ket
 16     End
------------------------------------------------------------------
Capture group count = 0
First code unit = 'a'
Last code unit = '}'
Subject length lower bound = 5
data> aaaaaa
No match
data> aa
No match
data> a
No match
data>
```

**Comment by jeffmcneely** [comment]
Interesting. The [pcre2 page](http://pcre.org/pcre2.txt) seems to differ from perl itself on this issue.

> An opening curly bracket that appears in a
       position where a quantifier is not allowed, or one that does not  match
       the  syntax of a quantifier, is taken as a literal character. For exam-
       ple, {,6} is not a quantifier, but a literal string of four characters.

The [perlre page](https://perldoc.perl.org/perlre) has this bit
> {,n}        Match at most n times

I was testing with this.
`$ perl -e 'print "match" if "foo" =~ /^fo{,2}$/'`

**Comment by working-name** [comment]
I see, [that makes sense](https://metacpan.org/release/XSAWYERX/perl-5.34.0/view/pod/perldelta.pod#qr/%7B,n%7D/-is-now-accepted). It was introduced in 5.34, so fairly new. I don't know if it will get adopted by PCRE2 as well but nice catch!

**Comment by firasdib** [comment]
Since its not supported by PCRE, this is the intended behavior for now.
