### ISSUE TITLE
Third match hard to spot

### ISSUE THREAD

**Issue by P2Beauchene** [firasdib/Regex101#1823]
Sorry to bother you with a style-related issue.
The highlighting color of the third captured match's is so close to that of the non-captured matches, that it sometimes makes it really hard to spot the third match in the test string (especially in dark mode).

**Comment by firasdib** [comment]
I agree, primarily in dark mode. In light mode I don't have this issue personally, but in dark mode, I do. I should brighten it up slightly. 

Thanks for your feedback!
