### ISSUE TITLE
C# quote `"..."` has incorrect escapes; also add verbatim `@"..."` and raw option

### ISSUE THREAD

**Issue by geekley** [firasdib/Regex101#1842]
## Bug Description
The quoting system used for C# regexes is inconsistent. By what it's implying, this is a bug.

Here's how C# works.
In regular quotes `"..."` things like backslash, quote, etc must be escaped:
```cs
new Regex("\\\\s\"") // pattern /\\s"/ matches 3 chars literally: \s"
```
In verbatim quotes `@"..."` nothing is escaped, except quotes by doubling it:
```cs
new Regex(@"\\s""") // pattern /\\s"/ matches 3 chars literally: \s"
```
The problem is that the regex field for .NET acts like it should be regular quotes `"..."` (it seems to expect quotes to be backslash-escaped inside the pattern), however, if that's the case, then `\\` should be a single `\` in the string, meaning a `\s` pattern should be `"\\s"` and a pattern matching a single backslash `\\` should be `"\\\\"`, not `"\\"`.

### Reproduction steps
Select .NET (C#) and look at the REGULAR EXPRESSION field. Enter a pattern like `"\\\\"gm`.
Notice that a backslash pattern is made with just 2 slashes `\\` instead of 4 `\\\\`.
If you use 4, it matches 2 backslashes instead of 1.

### Expected Outcome
Ideally, there should be options for the starting quote (like in js):
- Normal quote `"(regex)"gm`: `"` must be escaped as `\"` AND `\` must be escaped as `\\`, etc
- Verbatim quote `@"(regex)"gm`: `"` must be escaped as `""` AND everything else must NOT be escaped
- Raw string: nothing is escaped
  It uses 3+ quotes (e.g. `""""...""""`), but better to represent it using something else like an icon, e.g.: `🔽(regex)🔽gm`

I personally suggest verbatim style as the default, since it's what is easier to understand. Raw string is a new feature and it's more intended for multiline, also the amount of quotes necessary can depend on content which is bad. But it's useful as an option just so you can understand the raw "logical" pattern.

**Comment by geekley** [comment]
One more thing: it would be nice if the names of the flags matched exactly the constants in [RegexOptions](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regexoptions), since that's what you'll search to use in the code. Or at least mention both, e.g:
- **i**nsensitive / IgnoreCase
- **n**on-capturing / ExplicitCapture
- e**x**tended / IgnorePatternWhitespace
- etc...

Not that it's hard to understand, it's just so that you can see it right away without having to think.

**Comment by firasdib** [comment]
The input field is in fact a raw field and bypasses any string parsing done by the .NET compiler entirely, so the visual is merely semantic. The quotes are just to stay in line with the UI of the website. The code generator aims to be correct though.

Do you have any suggestion on how to improve this (visually)?

**Comment by geekley** [comment]
> The input field is in fact a raw field and bypasses any string parsing done by the .NET compiler entirely

OK, so if the field is just meant as a raw "logical" pattern, then **it must allow unescaped `"` inside the field**. Because if you're disregarding string escaping, then you can't require `\"` because a user may want to use verbatim strings `@"..."` instead (in fact it's often used for regexes) and escape it like `""`. So if user is responsible for string escaping, then all quotes and backslashes must be interpreted literally, and `\"` should input 2 chars in the pattern.
That's why **this is a bug** too. A single `"` in the pattern currently gives error:
> `"` An unescaped delimiter must be escaped with a backslash (`\`)

Which implies it's doing C# string escaping, but it's not; except for this character. This is inconsistent.
If pattern is raw, better to just not use a delimiter.

---
> The quotes are just to stay in line with the UI of the website. Do you have any suggestion on how to improve this (visually)?

If you'll have just raw pattern and won't allow delimiter options, then I suggest:
`^some regex$ ⋮gm` instead of `"^some regex$"gm`
- Remove opening quote (or make it invisible), to avoid implying any C# string escaping
- Since something needs to replace the closing quote, use an icon or character like a dropdown arrow ⏷ (U+23F7) or vertical ellipsis like you already use ⋮ (U+22EE), so that flags selector is more clear and always visible even when none is selected

Then users can confidently know that pattern is raw and handle string escaping themselves.

- If you later decide to implement delimiter options, you can use the ⋮ ellipsis in beginning too, so the options would be:
    - <code>⋮&nbsp; ^...$ ⋮gm</code> (raw)
    - `⋮ "^...$"⋮gm` (backslash-escaped)
    - `⋮@"^...$"⋮gm` (verbatim)

**Comment by firasdib** [comment]
If I've understood your post correctly, the best way forward (without too large modifications right now) would be to use `@"..."`, is that correct? If so, I'll adjust the UI to that.

**Comment by geekley** [comment]
Yes, as long as you make `@"..."` require escaping `"` as `""`, and everything else goes raw into the pattern, unescaped.
The other easier option is raw, where everything is unescaped, in this case, you'd use (blank) instead of quote delimiter to avoid confusion. I think this option is better, but either is fine.

In either case, you have to change whatever is giving the error above requiring `\"`.

**Comment by firasdib** [comment]
This will be resolved in the next release. Thank you.
