### ISSUE TITLE
ECMA Script RegEx does not allow duplicate names for named capture groups

### ISSUE THREAD

**Issue by hnravn** [firasdib/Regex101#1843]
## Bug Description
RegEx with ECMA regex selected does not complain about duplicate names for named capture groups

### Reproduction steps
`^\${(?<name>\w+) (?:(?:\['(?<defaultvalue>.*)'\])|(?:\[(?<defaultValue><no default>)\]))}$`

### Expected Outcome
Error message that duplicate named capture groups are not allowed

### Browser
Firefox 102.0.1 (64-bit)

### OS
 System Version:	macOS 12.4 (21F79)
  Kernel Version:	Darwin 21.5.0

**Comment by hnravn** [comment]
^\${(?<name>\w+) (?:(?:\['(?<defaultvalue>.*)'\])|(?:\[(?<defaultValue><no default>)\]))}$

**Comment by firasdib** [comment]
As far as I know, this is allowed by the specification. Your browser should otherwise throw an error.

**Comment by hnravn** [comment]
I'm running node v17.6.0

Venligst
Henrik

Den tor. 14. jul. 2022 kl. 17.09 skrev Henrik Nissen Ravn <
***@***.***>:

**Comment by firasdib** [comment]
```
Welcome to Node.js v18.6.0.
Type ".help" for more information.
> /^\${(?<name>\w+) (?:(?:\['(?<defaultvalue>.*)'\])|(?:\[(?<defaultValue><no default>)\]))}$/.test('${foo [bar]}')
false
>
```

No error in node 18.

**Comment by hnravn** [comment]
Nodejs throws an error and as far as I know Nodejs is ECMA compliant.

Venligst
Henrik

Den tor. 14. jul. 2022 kl. 15.23 skrev Firas Dib ***@***.***>:
