### ISSUE TITLE
Finds only first match of regex after intensive prior use

### ISSUE THREAD

**Issue by widike** [firasdib/Regex101#1844]
## Bug Description
When I work with the same regex101 browser tab a lot, after some time the flag "global" gets disabled unintentionally.

### Reproduction steps
Paste different regex expressions and texts into the tab over a period of a couple of hours. Modify expressions and texts in the tab a lot. Eventually, only one match is found even though an expression and text should result in multiple matches.

This is caused by the flag "global" no longer being active. I never intentionally disable the flag. Re-enabling the flag solves the issue.

Please close the bug report if this is just me clicking by accident or a wrong keyboard shortcut when I copy/paste. Issue happens once or twice a day to me.

### Expected Outcome
Selected flag global stays active.

### Browser
Version 103.0.5060.114 (Offizieller Build) (x86_64)

### OS
Mac OS 12.4

**Comment by working-name** [comment]
Hi @demux79,

To be clear, I have not tested the bug as you described it, but I do work with regex101.com in the same tab sometimes for weeks at a time (until I reboot). I have not bumped into that behavior yet.

That being said, are you aware that the expression you paste in is interpreted? For example `/no g/m` will have no g flag, while `/this one has g/gm` and you can also do substitution patterns like so `s/find/replace/gmsi`. Maybe this is what you're experiencing, which is very plausible especially if you work with PHP.

Note: not all flavors support all flags.

**Comment by working-name** [comment]
The point I was trying to make is that the site will overwrite the existing regex if you paste another one in. If the pattern is perl-like (`/a regular one/mg`) then it will be parsed and will automatically select flags `/mg` from your paste, ignoring what was in there before. So it's not so much an accident but an actual site feature.

Hope that made more sense 😬
