### ISSUE TITLE
The Quick Reference for `ECMAscript < Substitution < Contents in Capture Group 1` is wrong

### ISSUE THREAD

**Issue by brimwd** [firasdib/Regex101#1845]
## Bug Description
In the Quick Reference section for ECMAscript…
**Substitution** < **Contents in Capture Group 1** says `$1` will match the contents.
The correct syntax is `\1`.

**Comment by firasdib** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter you are wrong, and `$n` is the correct syntax.
