### ISSUE TITLE
Hide Function Panel

### ISSUE THREAD

**Issue by CarlitoGil** [firasdib/Regex101#1847]
Hi.
Could you please add an option to hide the function panel below the regex?
Long multiline regexes with the x flag are hard to visualize and scroll up and down.
After scrolling, group highlights disappear.
Thanks!

**Comment by firasdib** [comment]
Could you elaborate on what you mean by "function panel"? Do you have a screenshot?

What do you mean group highlights disappear after scrolling?

**Comment by CarlitoGil** [comment]
In this image, I marked in orange the part I would like to hide, usually called "TEST STRING".
![image](https://user-images.githubusercontent.com/5706999/179836235-fe51bc11-d7c2-4d75-81a3-3338d7c10b65.png)


In this next one, I have highlighted the closing of GROUP**2**. The whole group is inside the textbox, and I can see the opening highlighted in blue. That's OK.
![image](https://user-images.githubusercontent.com/5706999/179836785-1d0ea374-a97e-4540-9b0a-4d6f70739101.png)


But here I have highlighted the closing of GROUP**1**, and since the opening is not in view due to the max height of the textbox, I have to scroll up.
![image](https://user-images.githubusercontent.com/5706999/179836992-4b70f99a-e356-42c5-8043-b8e71ce04499.png)


As soon as I scroll up, the blue highlight disappears, even though I haven't moved the cursor. It makes it difficult to find the opening of the group when there is a lot of code inside.
![image](https://user-images.githubusercontent.com/5706999/179837792-0305a441-04d2-462b-bff5-0ffd1cdf4eb1.png)


I would like to hide the "TEST STRING" panel, or textbox, to visualize long code as I write it.
And If possible, the blue highlight for groups should remain active after scrolling.

Please let me know if I can explain anything further.

**Comment by firasdib** [comment]
Thanks.

If I would make the blue highlight stay when you scroll, would that be OK?

**Comment by CarlitoGil** [comment]
Thank you. Yes. That would great, and make it much easier to work with large regexes.

Only if possible, please also consider more height for the textbox. CTRL+F doesn't seem to find the out-of-view code.

Or perhaps I have another idea. If words or multiple characters are selected, what about highlighting any other repeated in the code?
