### ISSUE TITLE
Page rapidly switches from light to dark mode

### ISSUE THREAD

**Issue by acyanes** [firasdib/Regex101#1849]
## Bug Description
Page rapidly switches from light to dark mode and makes the page unresponsive

### Reproduction steps
Press Command + P 

### Expected Outcome
N/A

### Browser
Include browser name and version
Version 103.0.5060.134 (Official Build) (arm64)

### OS
Include OS name and version
macOS Monterey

**Comment by firasdib** [comment]
Thanks for your report. This has been fixed, and will be included in the next release. See https://github.com/firasdib/Regex101/issues/1817
