### ISSUE TITLE
Task 3: ASCII 0-31 check is faulty and inappropriately placed

### ISSUE THREAD

**Issue by Voileexperiments** [firasdib/Regex101#1852]
Related: #1177

Currently the tests are blocking on ASCII 0-31 check before everything else, even before checking if all consonants are counted, which is super inappropriate.

e.g Trying `/[T]/g`, among other sensible things, give

```
Test 5/10: Your regex is matching characters in the range 0-31, and I''m quite certain those are not consonants!
```

which is just absurd as the regex clearly **did not** match ASCII 0-31. It only matches `T`.

Besides, I believe the test aren't even working as intended, as when I try `/[T]/gA` it passes Test 5, until it fails at Test 9 with

```
Test 9/10: You are not counting all consonants. There is a total of 21 consonants in the alphabet.
```

which is expected, but when I try `/[CT]/gA` it fails at Test 5 again.

Test 9 clearly should be before Test 5 (in fact I'd say Test 5 should be moved to Test 10). Also what is Test 5 actually testing? It's producing a lot of ridiculous false positives.

**Comment by firasdib** [comment]
I'll look into it. All tests were remade recently, so there can be a typo somewhere.

**Comment by firasdib** [comment]
Thank you, fixed.
