### ISSUE TITLE
.NET flavor substitutions don't allow referencing named capture-groups alternatively positionally

### ISSUE THREAD

**Issue by mklement0** [firasdib/Regex101#1853]
## Bug Description

Note: I don't know how often this will arise in practice, but it's a deviation from the .NET regex engine's native behavior, so I thought I'd point it out.

### Reproduction steps

```powershell
# In PowerShell, demonstrates native .NET behavior.
[regex]::Replace('bar', '(?<lettera>a)(r)', '[$1][$2]')
```

### Expected Outcome

```
b[r][a]
```

That is, the .NET regex engine does the following:

* it reorders the capture groups to place the named ones _after_ the unnamed ones
* even the named ones can _alternatively_ be referenced _positionally_, based on the reordering above.

https://regex101.com/r/2kngzK/1 shows that this site currently doesn't allow referencing the _named_ capture groups _positionally_ - an error is reported.

### Browser

Brave Version 1.41.99 Chromium: 103.0.5060.134 (Official Build) (arm64)

### OS

macOS 12.4

**Comment by firasdib** [comment]
Thank you. This has been fixed locally.

**Comment by firasdib** [comment]
It will be patched with the next release. 


Vänliga hälsningar / Best regards,

Firas Dib
