### ISSUE TITLE
Task 17: Ambiguous specs

### ISSUE THREAD

**Issue by Voileexperiments** [firasdib/Regex101#1855]
The task description of Task 17 is "Only match lines with the text `start`, unless the text `end` is before that (`end` may or may not be in the string)". However Test 17 expects that `aaa start end start` should be matched.

What does "that" mean in "unless the text `end` is before that"? A reasonable read is "any `start` in the text", but it actually expects "the first `start` in the text". This is very ambiguous and should be clarified in the task description.

**Comment by firasdib** [comment]
How would you suggest I should clarify it?

**Comment by willeccles** [comment]
I would recommend perhaps doing something along the lines of "unless `end` appears prior to `start`" if I am understanding the meaning right.

**Comment by firasdib** [comment]
I've clarified this and will release it soon.
