### ISSUE TITLE
closes by adding an at sign

### ISSUE THREAD

**Issue by macajo9611** [firasdib/Regex101#1856]
## Bug Description
I get the screenshot error using mozilla firefox

### Browser
firefox 103.0 (64-bit)

### OS
Windows 10

![errorRegex101](https://user-images.githubusercontent.com/109444075/181984977-b188ac01-5a6d-4a31-aec8-e96d65367165.PNG)

**Comment by firasdib** [comment]
What flavor and flags? What mode was selected (match, subst, etc)? Does this happen in an incognito tab?

Can you record it, if possible? With the console open.

**Comment by firasdib** [comment]
@macajo9611 Can you please provide more details?
