### ISSUE TITLE
Visualize Tab Character

### ISSUE THREAD

**Issue by CarlitoGil** [firasdib/Regex101#1857]
## Feature
Hi.
Spaces are visualized with a middle dot.
Could you please add a visualization for the Tab character?
I suggest an arrow like this: "`--->`"

**Comment by firasdib** [comment]
There is one. What browser are you using that isn’t showing it?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by CarlitoGil** [comment]
>What browser are you using that isn’t showing it?

This is Google, Chrome 103.0.5060.134 64-bit
![image](https://user-images.githubusercontent.com/5706999/182464209-22b34cf1-cbe0-4d6e-84b0-dd90526b0dc2.png)

This is Edge, version 103.0.1264.77 64-bit
![image](https://user-images.githubusercontent.com/5706999/182463850-0342967e-1aa8-46e0-a973-849e73b15262.png)

Running on Windows 10, 64-bit build 19044.1826

I'm not seeing it in any flavor, light or dark.

**Comment by firasdib** [comment]
Thank you, looks like a bug with my webpack config. I have resolved it, and it will be visible in the future releases.
