### ISSUE TITLE
Quiz Task 24

### ISSUE THREAD

**Issue by Delattre-Remi** [firasdib/Regex101#1858]
## Quiz Bug

I input a Regex for the Quiz task 24 and the result message it outputs is questionable.

### Task
Task 24 : Outermost Brackets

### Bug Description

I input a Regex for the Quiz task 24 and it outputs :

> Test 4/14: It's not working. Try with the example I gave you!

While when I test the example you gave, it sets the backreferences it should.

### Reproduction steps

Input the Regex I wrote (not sure I can share it here) in test 24.

### Expected Outcome
Validate the task or fail on another test.

### Browser
Edge

### OS
Windows 10

**Comment by working-name** [comment]
Hi @Mostuniqu3 please send your regex to contact@regex101.com so we can take a closer look. Thank you!

**Comment by firasdib** [comment]
Thanks for reaching out. The error is telling you to try your regex against the examples given in the task description, which I think seems fair. When I tried it, it showed where your regex failed to match.

How would you suggest to improve the error message?
