### ISSUE TITLE
.NET/C# engine saying \" is erroneous

### ISSUE THREAD

**Issue by gwillgues** [firasdib/Regex101#1859]
## Bug Description
When writing regex in .NET/C# syntax, the engine says that \" is not valid. This means there is no way to directly reference a double quote character literally.

### Reproduction steps
Type \" into the engine for .NET/C#

### Expected Outcome
Allow method to reference literal double quote character

### Browser
Include browser name and version
Firefox
### OS
Include OS name and version
Linux

**Comment by firasdib** [comment]
In .NET you need to use `""` to escape quotes.
