### ISSUE TITLE
.NET Named Group Not Available As Unit Test Target

### ISSUE THREAD

**Issue by CarlitoGil** [firasdib/Regex101#1861]
## Bug Description
With .NET flavor, doesn't allow to add a named group as Unit Test target.

![image](https://user-images.githubusercontent.com/5706999/183509215-bf014f83-9683-4436-8b8d-3254de325ed8.png)

### Reproduction steps
Use .NET flavor.
Add named group to pattern.
Create unit test.
Try to "SELECT TARGET" after "assert that".

If the flavor is changed, the named group added as target, and the flavor changed back to .NET, it works.

### Expected Outcome
.NET named groups should be included as possible Unit Test targets, as they are for other favors.

### Browser
Chrome 104.0.5112.81 x64

### OS
Windows 10 x64

**Comment by firasdib** [comment]
Thank you. This highlighted some major issues in my code, since .NET handles capture groups completely differently.

I've done quite a bit of refactoring, but it looks to be working. I'll write some more tests and release this in the coming days.
