### ISSUE TITLE
Unit tests on capture groups passes in all instances

### ISSUE THREAD

**Issue by northamerican** [firasdib/Regex101#1863]
## Bug Description

Creating a unit test on a capture group passes no matter what content is provided.

### Reproduction steps

See: https://regex101.com/r/znSeMG/1

String groups are correctly identified:
<img width="179" alt="Screen Shot 2022-08-12 at 1 12 04 PM" src="https://user-images.githubusercontent.com/6657634/184435469-c3d28b5c-e53d-489e-8fce-131896364e2a.png">

Unit tests pass no matter what group or text string is tested:

<img width="346" alt="Screen Shot 2022-08-12 at 1 12 35 PM" src="https://user-images.githubusercontent.com/6657634/184436366-7264bc7e-c278-415d-9500-730cb3822947.png">

https://regex101.com/r/znSeMG/1

### Expected Outcome

Unit test should fail if the group's text does not match. 

### Browser
Chrome 100+

**Comment by firasdib** [comment]
Thank you, I'll push a fix immediately.
