### ISSUE TITLE
Quiz 6: spelling mistake

### ISSUE THREAD

**Issue by ZhukDmitryOlegovich** [firasdib/Regex101#1865]
## Bug Description
Quiz 6: spelling mistake

<img width="758" alt="Снимок экрана 2022-08-15 в 20 34 17" src="https://user-images.githubusercontent.com/93006259/184686034-28cf39ba-dce7-408f-9115-f600853c5436.png">

Replace from
```
That wasn''t too hard, right?
```
to
```
That wasn't too hard, right?
```

**Comment by firasdib** [comment]
Thank you, I'll push the fix asap.
