### ISSUE TITLE
Critical error when entering a URL in Regular Expression field

### ISSUE THREAD

**Issue by duarte-pompeu** [firasdib/Regex101#1867]
## Bug Description

Wanted to experiment a regex that would match the ID in `https://www.imdb.com/list/{id}/export` but the website crashed when removing the `https://` portion.

### Reproduction steps

1. Type `https://www.imdb.com/list/` in **Regular Expression** field.
2. Remove `https://`
3. Receive **A critical error has occurred**

### Expected Outcome

No critical error.

### Browser

Firefox 103.0.2 (64-bit)

### OS

Windows 10 Education 64-bit (10.0, Build 19044)

Screenshot:

![image](https://user-images.githubusercontent.com/7232812/184954402-ba056030-2878-4db5-bf50-158a590bdb13.png)

![image](https://user-images.githubusercontent.com/7232812/184954145-7cdf25de-4713-44ee-87b1-97d4f81185e2.png)

**Comment by firasdib** [comment]
I cannot reproduce. 

Does this happen in an incognito tab as well?

**Comment by duarte-pompeu** [comment]
It happened both in normal browsing and incognito, but I found the problem: an extension.

I tried the troubleshoot mode without any extension and it stopped happening. After a bit of trial and error, I found it was caused by this extension: https://github.com/MarkaPola/Linkificator

So I guess we can close the report! Sorry for troubling you - and thanks for the website, it's very useful!

**Comment by working-name** [comment]
Glad to hear you found the culprit!
