### ISSUE TITLE
Import/Export Unit Tests

### ISSUE THREAD

**Issue by CarlitoGil** [firasdib/Regex101#1868]
## Feature

Please add Import/Export to Unit Tests.

**Comment by firasdib** [comment]
What format would the export be in?

**Comment by CarlitoGil** [comment]
> What format would the export be in?

I think JSON should be fine.

**Comment by firasdib** [comment]
Okay, so this is just an import/export for the website, not in a coding language. Why do you want this feature if I may ask?

**Comment by CarlitoGil** [comment]
1. Copy many Unit Tests between different regexes on Regex101, keeping/modifying what's needed for each.
2. Have separate development/shared Regex101 links without manually adding tests.
3. Manipulate JSON to create bulk tests on Regex101.
4. JSON can be manipulated to transfer the Unit Tests back and forth between a programming language, such as C#.

I think JSON would work, but really any text format would do.

**Comment by firasdib** [comment]
I've looked into it, and this is quite a bit of work to not just become a sloppily implemented, buggy, feature. I'm not sure its worth the time right now, but I will keep it around.

**Comment by OnlineCop** [comment]
Does the [API](https://github.com/firasdib/Regex101/wiki/API) already support this?

**Comment by firasdib** [comment]
@OnlineCop It does, and its a good workaround. I suspect the author wanted something easier using the UI, but this is a good solution.
