### ISSUE TITLE
Task 8 my regex is work,but tip error

### ISSUE THREAD

**Issue by lgldlk** [firasdib/Regex101#1869]
## Bug Description
<img width="502" alt="image" src="https://user-images.githubusercontent.com/57523724/185531234-2cfd25d2-a8ae-41b9-b64d-28dda7132a1f.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/57523724/185531207-5c9c0742-cc15-4999-86e5-a4db815972dd.png">

what is true regex

**Comment by firasdib** [comment]
I would recommend you ask in the IRC channel (Click "Live Help") on the website for support on the matter.
