### ISSUE TITLE
.NET replace breaks with double quotes

### ISSUE THREAD

**Issue by ItItaca** [firasdib/Regex101#1870]
## Bug Description
.NET substitution doesn't work in a string with an escaped double quote

### Reproduction steps
set flavor to .NET
regular expression = bug\\\\""
test string = doublequotesbug\\"
substitution
substituteplease

### Expected Outcome
doublequotessubstituteplease
but instead substitution doesn't happen, even if the editor correctly highlights the occurred match

### Browser
Include browser name and version
Firefox 102

### OS
Windows 10 22

**Comment by firasdib** [comment]
Thank you. I have a fix locally, will push soon.
