### ISSUE TITLE
Regular matching verification error

### ISSUE THREAD

**Issue by lgldlk** [firasdib/Regex101#1873]
## Bug Description
My regex works, but it doesn't let me submit
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/57523724/186068281-1ea65442-a3d5-415c-9323-0c49bbb06729.png">

**Comment by firasdib** [comment]
The quiz uses PCRE as its engine, which does not allow for variable width lookbehinds. You're testing it in javascript, which does. You'll have to find an alternative way to construct your regex!
