### ISSUE TITLE
QUICK REFERENCE > Qualifiers is missing lazy versions of curli repeats

### ISSUE THREAD

**Issue by jho1965us** [firasdib/Regex101#1874]
## Bug Description

QUICK REFERENCE > Qualifiers should list at least 2 and 3 from the following list:

1.   a{3}?     # this one is correct syntax but lazy vs greedy make no difference
2.   a{3.}?
3.   a{3,6}?

### Reproduction steps
noting to reproduce missing documentation

but checked valid syntax by trying the following in console:
/x{3}?/.exec("x") === null
/x({3})?/.exec("x") === ""

### Expected Outcome
There are no out come from documentation

### Browser
Include browser name and version

tested on Chrome  104.0.5112.81

### OS
Include OS name and version

tested on windows 10

**Comment by firasdib** [comment]
I'm not sure if its worth adding every permutation possible, but I added a note to the existing description that any quantifier can be made lazy with the question mark.
