### ISSUE TITLE
C# code generator doesn't escape double-quote

### ISSUE THREAD

**Issue by strout** [firasdib/Regex101#1875]
## Bug Description

C# code generator produces invalid code when regex contains the character `"`.

### Reproduction steps

1. Input the regex `/"/`
2. View generated C# code. It generates:

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
    public static void Main()
    {
        string pattern = @""";
        string input = @"";
        
        Match m = Regex.Match(input, pattern);
        Console.WriteLine("'{0}' found at index {1}", m.Value, m.Index);
    }
}
```
which [does not compile](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYBGAWACgKAGAAgpoDoAVGBDTgCUYAcxwAbAIZQAoggAOsAM5KAlhDxKA3I0YUAzOyqs5kgLbzxMRgG9GrB0ar3Hdho4/sabeZIwYYKDxWAF52CgAiKJ13TwcONlU8eRwMUPDolziszwBZPzAAC1YzdOERPk58jCKACiSUjDRWX39AvABKGLj4mgBOWoiAchtmAF8h1gAzCHxCVj9WJMI+VhsaMYjms04ANUlxHBhtzgBJPBWELpyxxjGgA===)

### Expected Outcome

It should turn `"` into `""`; that's how `"` is escaped inside [Verbatim string literals](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#verbatim-string-literals) (`@"string"` syntax).

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
    public static void Main()
    {
        string pattern = @"""";
        string input = @"";
        
        Match m = Regex.Match(input, pattern);
        Console.WriteLine("'{0}' found at index {1}", m.Value, m.Index);
    }
}
```
This [compiles](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYBGAWACgKAGAAgpoDoAVGBDTgCUYAcxwAbAIZQAoggAOsAM5KAlhDxKA3I0YUAzOyqs5kgLbzxMRgG9GrB0ar3Hdho4/sabeZIwYYKDxWAF52CgAiKIidd08HDjZVPHkcDFDwqNj4hxd4gFk/MAALVjMM4RE+TkKMEoAKZNSMNFZff0C8AEpsnI4ATnqIgHIbZgBfYdYAMwh8QlY/VmTCPlYbGnGI1rNOADVJcRwYHc4ASTxVhB681nHGcaA=) (though I notice its output isn't quite right; it's not checking that `m.Success` is true).

### Browser
Firefox 103.0.1

### OS
Windows 10

**Comment by firasdib** [comment]
If you use the .NET flavor this should produce an error in the editor. Does it not?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by strout** [comment]
Ah yes it does behave properly there. I had assumed it would convert the syntax from PCRE to C# strings. Is there an indication that the code generators depend on which regex flavor you start with? I didn't notice one.

**Comment by working-name** [comment]
Great to hear. The code generators spit out example code for whatever language you select, but it _does not change your regex at all outside of escaping_. 

Essentially if your regex functions in the flavor you selected (that's where syntax checking happens), it should be properly escaped when you open the code generator and you're good to go.

The main idea is that regex has a universal syntax up to a certain point, but then there's differences in implementation and available features depending on the engine. That's where the need arises to adapt the specific syntax or make sure you are using features that are supported by the language you're targeting.

**Comment by strout** [comment]
I just want to clarify, this _is_ only about escaping.

Changing `"` to `""` in C# verbatim strings is equivalent to changing `"` to `\"` in other languages (and in regular C# strings). It happens to work fine with .NET regex input because the user is made to manually escape them :slightly_smiling_face:.

For an example of where this works correctly:

1. Write a PCRE `hi"there`.
2. View the generated Python code: `r"hi\"there"` -- note that it escapes the `"` as `\"`
3. View the generated C# code: `@"hi"there"` -- note that it _does not_ escape the `"` as `""`.

A few other combinations I tried worked fine too (like escaping a `/` when outputting Ruby) but some others did not.

Again, this _isn't_ about different regex flavors being incompatible, it's just about escaping the string literal. I'd expect this to work (produce a valid string literal) regardless of codegen language. Does that seem reasonable?

**Comment by working-name** [comment]
Got it. So the way I see it is if your regex works correctly on the site, it'll work ok in the code generator as well. So if my regex is simply `"` while I have `.net` selected as the flavor, the site tells me I have a pattern error where a delimiter was not escaped.

Similarly, if I switch to PCRE on a fresh load of regex101.com, and I type in `/` which is also the default delimiter, I'll get the same error.

That's fairly universal across all flavors: you want to escape your delimiters if you need to use them as tokens within the regex.

Does this make sense?

**Comment by strout** [comment]
Yes that's right. But it seems like generating in a different language _sometimes_ handles difference in delimiter escaping, sometimes not, which makes me think this still might be a valid bug.

For context, I came to the site because I wanted to double-check my escaping (of both backslashes and quotes), so I wrote it as a PRCE because neither of those needs escaped. Then when I tried to generate C#, and was surprised that it didn't output a valid string.

**Comment by working-name** [comment]
Yes I can see where it might appear like it's doing something more than escaping the characters that are defined for that code generator. You can see some of the code behind it [here](https://github.com/firasdib/Regex101/wiki/Writing-a-Code-Generator).

The reality is that this is an isolated use case: escaping the delimiter itself. I'm not against auto-escaping it if that's what you expect to be normal behavior, but it's by no means a bug. The assumption is that you have a valid regex, and if you use the delimiter within your regex, you must escape it no matter what.

**Comment by firasdib** [comment]
I agree, its a bit confusing that .NET doesn't fix mismatched quotes but other flavors fix mismatched backslashes.

I've added a small fix for this. Thanks
