### ISSUE TITLE
Search Reference Issue

### ISSUE THREAD

**Issue by Attacktive** [firasdib/Regex101#1876]
## Bug Description
Searching for `Character Classes` does not show the item with the very title.

The keyword `Character` still works but not `Class(es)`.

![image](https://user-images.githubusercontent.com/66462458/186574329-3f6b234c-b390-442a-94fb-bb589d833737.png)
![image](https://user-images.githubusercontent.com/66462458/186574301-2ccd552e-6ea5-49cd-b3b8-d25c7055061e.png)

### Reproduction steps
Type
> Character Classes

or simply
> class

in the Reference search input.

### Expected Outcome
The filtered list should contain the item titled 'Character Classes'.

### Browser
Firefox (104.0)
Google Chrome (Version 104.0.5112.101 (Official Build) (64-bit))
Microsoft Edge (Version 104.0.1293.47 (Official build) (64-bit))

### OS
Ubuntu 22.04.1 LTS

**Comment by working-name** [comment]
Thank you! We'll add some more keywords. I noticed `Character` alone doesn't bring up normal character classes either.

**Comment by firasdib** [comment]
Thank you, I've improved this and will have it released soon.
