### ISSUE TITLE
Incorrectly interprets "except"  [A-Z-[QVX]]

### ISSUE THREAD

**Issue by Ian1971** [firasdib/Regex101#1877]
## Bug Description
Seems to incorrectly interpret [A-Z-[QVX]] which should be a char A-Z except Q, V or X

### Reproduction steps
1. Set reg ex as [A-Z-[QVX]]
2. Try and match it

### Expected Outcome
It should match all chars A-Z but not Q V or X

### Browser
Edge 104.0.1293.63

### OS
Window 10

**Comment by working-name** [comment]
Hi @Ian1971 

Can you please share a regex101.com link with an example? I tried it out myself and cannot reproduce it yet.

**Comment by Ian1971** [comment]
https://regex101.com/r/Znl2Hv/1

**Comment by firasdib** [comment]
You need to select a flavor that supports the syntax, like Java. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by working-name** [comment]
Or .NET.

**Comment by Ian1971** [comment]
ah yes. Thanks I'll close the issue.
