### ISSUE TITLE
For PCRE2 , is there a way to pass PCRE2_SUBSTITUTE_EXTENDED to the subsitution?

### ISSUE THREAD

**Issue by jerryjeremiah** [firasdib/Regex101#1878]
Using PCRE2, if I set the substitution to `${1:+matched:unmatched}` as described by https://www.regular-expressions.info/replaceconditional.html then regex101 just says "pattern error" 

That documentation is clear that PCRE2_SUBSTITUTE_EXTENDED needs to be passed to pcre2_substitute but there doesn't appear to be any way to do that with regex101.

Is it possible?

**Comment by firasdib** [comment]
I cannot seem to reproduce: https://regex101.com/r/6YQp20/1

Feel free to reopen if the issue persists!

**Comment by jerryjeremiah** [comment]
Ok,  I have no idea what I was doing wrong.
This is what I was trying to do: https://regex101.com/r/lzWlxc/1
And it works fine...

**Comment by firasdib** [comment]
Perhaps you had the wrong flavor selected :).

This only works with PCRE2

**Comment by CarloMoretti-Repa** [comment]
.. But this conditional substitution won't work using PHP, see https://bugs.php.net/bug.php?id=77756. How is it working in regex101?
