### ISSUE TITLE
Regex Debugger: show wrong steps for failed atomic group / possessive quantifiers 

### ISSUE THREAD

**Issue by liudongmiao** [firasdib/Regex101#1879]
## Bug Description
For non-matched "atomic group", "regex debugger" show wrongs steps.

### Reproduction steps

For atomic group:
- Regex: ^(?>a+)$
- Input: aaaaaaaaaab
- PCRE2: show no match, 5 steps
- Debugger: show no match, 16 steps
- Demo: https://regex101.com/r/1tlLsi/1

For possessive quantifiers:
- Regex: ^a++$
- Input: aaaaaaaaaab
- PCRE2: show no match, 3 steps
- Debugger: show no match, 14 steps
- Demo: https://regex101.com/r/1tlLsi/2

### Expected Outcome
Debugger show the same steps as PCRE2.

### Browser
N/A

### OS
N/A

**Comment by firasdib** [comment]
This is because the debugger disables some of the native optimizations in the engine, in order to produce the information it does. You should not read into the step counts _too much_
