### ISSUE TITLE
Remove the stay on page popup.

### ISSUE THREAD

**Issue by Zafrusteria** [firasdib/Regex101#1880]
Can you please remove the really annoying "stay on page" popup. It will be an extra step for most people as only a few will ever close the window by mistake, due to the topic of the page.
Thanks
Richard

**Comment by firasdib** [comment]
There is an option for this in the settings

![Screenshot 2022-08-29 at 13 04 54](https://user-images.githubusercontent.com/1335165/187187538-533a81d7-28d8-4f2c-8fbb-9cd8de4b6640.png)
