### ISSUE TITLE
Shows Parent Group's Tooltip Instead of Child's

### ISSUE THREAD

**Issue by CarlitoGil** [firasdib/Regex101#1881]
## Bug Description
.NET allows multiple groups to use the same name.
When hovering over the captured text in TEST STRING, the second group of the same name is placed below its parent group, if the first one is outside the parent, and can't be hovered.

### Reproduction steps
Choose .NET
Use this pattern:
`(?<word>\w+)\s(?<text>(?<word>\w+)\s\w+)`
Use this test string:
`WORD1 WORD2 WORD3`

Try to hover each word of the test string.
The coloring makes you expect WORD1 and WORD2 to behave the same when hovered, but WORD2 behaves like WORD3 instead of WORD1.

Notice that there are 2 groups named "word" in the pattern.
The first has no parent group.
The second is inside another group, named "text".

### Expected Outcome
Be able to hover over WORD2 and get the tooltip for the group "word" instead of "text".

### Browser
Chrome, version 104.0.5112.102 (64-bit)

### OS
Windows 10 x64

**Comment by firasdib** [comment]
This is because of the way the tokens are being painted by the editor, which in effect is because of the order they are received from the engine. Since its the same group name, the order messes things up. If you would have renamed the group, it would behave as expected.

This edge case is something we will have to accept.

**Comment by CarlitoGil** [comment]
Hi @firasdib 

I understand.
The problem with renaming the groups is that I have so many that the colors repeat themselves and there's no control over the colors for each group.

I have another request then:
How about assigning the colors of the groups in the matches based on their root words.

For example:
`(?<group_1>[A-Z])(?<group_2>[0-9])`
Since both group names start with `group_` (split by the first underscore) could they have the same color?

Or maybe right-clicking the group in the pattern lets the user choose the color?

**Comment by firasdib** [comment]
Groups with the same name will already have the same color in .NET

Adding the ability to customize is a bit too much work for this niche case, I think
