### ISSUE TITLE
Text selection is clipped on mobile

### ISSUE THREAD

**Issue by vwkd** [firasdib/Regex101#1882]
## Bug Description

When copying text in the Test String (or Substitution output) text field on mobile, the selection is clipped to approximately the height of the viewport.

This results in not being able to copy all text of a substitution and the user can’t get at their results.

### Reproduction steps

1. Open Regex101 in a mobile browser
2. Paste a long text in the Test String text field that is longer than the height of the viewport
3. Select all text in the Test String text field (or Substitution output text field)
4. Scroll
5. Notice the text is clipped to approximately the size of the viewport.

You can also observe it by copying the selection and pasting it somewhere.

https://user-images.githubusercontent.com/33468089/187667429-a2d9373e-6323-42a7-8bbb-464c8b1f782b.MOV

### Expected Outcome

All text is selected.

### Browser
Mobile Safari on iOS 15.6.1

### OS
iOS 15.6.1

**Comment by firasdib** [comment]
This would be a codemirror bug. Can you reproduce the problem on https://codemirror.net/5/ (with the scroll visible)?

**Comment by firasdib** [comment]
Were you ever able to verify this?

**Comment by vwkd** [comment]
Yes, I can reproduce it with Codemirror 5 though not with Codemirror 6. Can Regex101 upgrade?

**Comment by firasdib** [comment]
Okay. No, I cannot upgrade without a major rewrite at this point. It will have to come in the future some time.

**Comment by firasdib** [comment]
This should be resolved with the upcoming update using Codemirror 6.
