### ISSUE TITLE
Faulty test result

### ISSUE THREAD

**Issue by SuperSnajd** [firasdib/Regex101#1883]
## Bug Description
Running this simple example seems to give a faulty result. I would expect no match.

### Reproduction steps
Using .Net C#
Pattern: (?>a+)ab
Test String: aaaaaaaaaaab

### Expected Outcome
No Match

### Browser
Google Chrome 104.0.5112.102 64-bit

### OS
Windows 10 Pro, 19044.1889

**Comment by firasdib** [comment]
This could be an error with the .NET engine. I would suggest you contact them and see what they have to say about it.

**Comment by firasdib** [comment]
This seems to be fixed in .NET 7 RC1. I'll push it with the upcoming update.
