### ISSUE TITLE
C# An option to choose how to escape literals (quotes, backslash, etc...)

### ISSUE THREAD

**Issue by w4po** [firasdib/Regex101#1884]
Hello,
I am using the `.NET` flavor and I would like to be able to choose to escape double-quotes (") with backslash `\"` instead of `""`,
As I am used to escaping it like that and an option to switch between different escaping systems would be great.

This has been mentioned in:
[C# quote "..." has incorrect escapes; also add verbatim @"..." and raw option](https://github.com/firasdib/Regex101/issues/1842#issue-1304124157)

## Expected Outcome
Ideally, there should be options for the starting quote (like in js):

- Normal quote "(regex)"gm: " must be escaped as \" AND \ must be escaped as \\, etc
- Verbatim quote @"(regex)"gm: " must be escaped as "" AND everything else must NOT be escaped
- Raw string: nothing is escaped
- It uses 3+ quotes (e.g. """"...""""), but better to represent it using something else like an icon, e.g.

Thank you @firasdib  very much for the awesome website/tool.

**Comment by firasdib** [comment]
Its a bit too much work to implement the different behaviors, since they don't act as delimiters in other languages, but as language specific string interpolation.

For that reason it has made the most sense to use the verbatim quote style.
