### ISSUE TITLE
Regex Debugger for ECMAScript (JavaScript) engine

### ISSUE THREAD

**Issue by Davydx7** [firasdib/Regex101#1888]
## javascript
Hello,
This is a request for a regex debugger for the JavaScript regex flavour

The debugger is an essential and useful feature that helps with understanding a piece of regex and helps with visualizing how best to optimize

Given the size of the javascript community, this feature will be useful for a good number of users/projects

I opt for the PCRE debugger where applicable, but the engines differ a lot, especially in look-around support

**Comment by firasdib** [comment]
There is unfortunately, as far as I know, no way of achieving this for Javascript.
