### ISSUE TITLE
ECMAScript (JavaScript) regex number of steps indication

### ISSUE THREAD

**Issue by Davydx7** [firasdib/Regex101#1890]
### javascript

Request for number of steps indicator for the js regex engine

unlike other regex engine flavours, the js engine does not show the number of steps taken to traverse a string with the provided regex (alongside the number of matches and milliseconds)

This piece of information is particularly useful in comparing pairs of regex solutions 

and for optimization purposes

![ecma](https://user-images.githubusercontent.com/69201432/189448997-edc2af4e-a4e5-4852-a485-6c9f238d5fb0.png)

![pcre](https://user-images.githubusercontent.com/69201432/189449071-346976ae-b6b8-4533-af5b-95e8b97408b8.png)

**Comment by Davydx7** [comment]
![image](https://user-images.githubusercontent.com/69201432/189454145-02731a3a-0e98-4c4d-9320-8c11c7ec8daa.png)

in settings, no effects on js

**Comment by working-name** [comment]
Just FYI @Davydx7 #1276 - I have not kept up with new developments on the browser side.

**Comment by firasdib** [comment]
This can't be done due to limitations in the javascript engine. I will update the setting to reflect this.
