### ISSUE TITLE
Several incorrect explanations

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#1891]
Hi, I think there are several places that need to be corrected.

## Empty Negative Lookaround (All Flavor）

   > **Negative Lookahead (?!)** — null, matches any position

   > **Negative Lookbehind (?<!)** — null, matches any position

   "matches any position", this explanation is incorrect. Actually, the empty negative lookaround always fail to match, neither `(?!)` nor `(?<!)` can match any position.

## Shorthand Character Classes (.NET Flavor)

   > \w match any word character in any script (equivalent to [\p{L}\p{N}_])

   > \s matches any kind of invisible character (equivalent to [\p{Z}\h\v])

   > \W match any non-word character in any script (equivalent to [^\p{L}\p{N}_])

   > \S matches any kind of visible character (equivalent to [^\p{Z}\h\v])

   > \D matches any non-numeric character in any script (equivalent to \p{Nd})

   "equivalent to `[unicode property]`", the description of this part is not accurate.   
   Actually, 

   `\w` is equivalent to `[\p{L}\p{Mn}\p{Nd}\p{Pc}]` , see [word character](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#word-character-w).

   `\s` is equivalent to `[\f\n\r\t\v\x85\p{Z}]` , see [white-space character](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#whitespace-character-s).

   `\d` is equivalent to `\p{Nd}` , see [decimal digit](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#decimal-digit-character-d).

   With that, it is easy to know the uppercase shorthand:

   `\W` is equivalent to `[^\p{L}\p{Mn}\p{Nd}\p{Pc}]` 

   `\S` is equivalent to `[^\f\n\r\t\v\x85\p{Z}]` 

   `\D` is equivalent to `\P{Nd}` (capitalized `P`)

**Comment by firasdib** [comment]
Thank you for the improvements, I will incorporate them.

As for the negative lookarounds, they do in fact match at any position, but the effect of them matching is that the match fails at any position.

**Comment by Serious54088** [comment]
> As for the negative lookarounds, they do in fact match at any position, but the effect of them matching is that the match fails at any position.

Thanks the reply. As for the negative lookarounds, I see what you mean, but I think it's best to describe it in a different way. Otherwise, the user may be confused. Let's take a look at  the following EXPLANATIONs.

> **Positive Lookahead (?=)** — *null*, matches any position
>
> **Negative Lookahead (?!)** — *null*, matches any position

`(?=)` always finds a zero-length match, `(?!)` always fails to match—They are diametrically opposed, but share the same description!

**Comment by firasdib** [comment]
Do you have a suggestion for how to improve the explanation?Vänliga hälsningar / Best regards,Firas DibOn 17 Sep 2022, at 06:26, 6C60 ***@***.***> wrote:﻿

As for the negative lookarounds, they do in fact match at any position, but the effect of them matching is that the match fails at any position.

Thanks the reply. As for the negative lookarounds, I see what you mean, but I think it's best to describe it in a different way. Otherwise, the user may be confused. Let's take a look at  the following EXPLANATIONs.

Positive Lookahead (?=) — null, matches any position
Negative Lookahead (?!) — null, matches any position

(?=) always finds a zero-length match, (?!) always fails to match—They are diametrically opposed, but share the same description!

**Comment by Serious54088** [comment]
My English is not very good, only for your reference:

(?=) always matches
(?!) alwasy fails

In addition, I attach the explanations from RegexBuddy:

> Empty positive lookaround always finds a zero-length match
> Empty negative lookaround always fails to match

**Comment by firasdib** [comment]
Thank you, I'll play around with it.
