### ISSUE TITLE
Incorrect octal escape explanation for ECMAScript

### ISSUE THREAD

**Issue by mattco98** [firasdib/Regex101#1899]
## Bug Description
If the three digits after an octal escape are not a valid octal number, then the escape encompasses as much of the number as possible, and the rest of the digits are interpreted literally. If none of the digits are octal, then it is not an octal escape. However, regex101 only half-recognizes this.

### Reproduction steps + Expected Outcome
Try the regex `/\439/` paired with input `#9`. The match succeeds, as it should (throw `/\439/.test('#9')` in the JS console to verify), but the explanation is:
![Capture](https://user-images.githubusercontent.com/28801118/190688428-e1de6fd6-d1c2-49fc-a607-d92a3701532f.PNG)

It gets the escape value right, but lumps the `9` into the input and swallows the second step. 

Additionally, consider `/\999/`. This should be interpreted as three literal `9` characters. but the explanation is:
![Capture](https://user-images.githubusercontent.com/28801118/190688510-d9c9bcf6-ef35-4a3c-a0f0-b85154b77f32.PNG)

Which is wholly wrong, as there is no escape here (which I suppose is why it picks `0` for the value).

**Comment by firasdib** [comment]
Thank you. I have fixed this locally and will push it live soon.
