### ISSUE TITLE
Lone \C fails to advance ahead after encountering supplementary character

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#190]
I'm not sure if this is a bug or not, but based on the behavior of `\C` of PCRE compiled with UTF-8 option on an online tester which runs on PHP, I think it is a bug. It's best to check against the PCRE UTF-16 library, though.

Given pattern `/(\C)/u` and source string `xd🀄abcde`, which contains a supplementary character, the UTF-8 PCRE returns:
```
array (
  0 => 
  array (
    0 => 'x',
    1 => 'd',
    2 => '�',
    3 => '�',
    4 => '�',
    5 => '�',
    6 => 'a',
    7 => 'b',
    8 => 'c',
    9 => 'd',
    10 => 'e',
  ),
  1 => 
  array (
    0 => 'x',
    1 => 'd',
    2 => '�',
    3 => '�',
    4 => '�',
    5 => '�',
    6 => 'a',
    7 => 'b',
    8 => 'c',
    9 => 'd',
    10 => 'e',
  ),
)
```

Since the UTF-8 library match to the end of the string regardless, I think UTF-16 should have the same behavior.

The current behavior of regex101 is that, given same pattern and same string, it stops matching after the first code unit of the supplementary character, although `g` flag is on.

```
MATCH 1
1.	[0-1]	`x`
MATCH 2
1.	[1-2]	`d`
MATCH 3
1.	[2-3]	`�`
```

Link: https://regex101.com/r/dH0tE3/5

I don't know if this is the behavior of PCRE UTF-16 library and I don't have one at hand to test, though.

**Comment by firasdib** [comment]
This is fixed. Please join IRC to confirm!

**Comment by nhahtdh** [comment]
@firasdib Which direction did you choose to fix this issue?

Follow pcretest (which behaves like current behavior, but should return an explicit error), or PHP's buggy implementation?

**Comment by nhahtdh** [comment]
It doesn't seem anything is changed.

https://regex101.com/r/dH0tE3/5

While I think it is a valid implementation to stop on bad offset (same as `pcretest`), I think an error should be raised to inform the user.

**Comment by firasdib** [comment]
@nhahtdh This still relevant?

**Comment by nhahtdh** [comment]
Yes, there should be an error message informing that the match is halted.

**Comment by firasdib** [comment]
This is fixed in v2, it returns the same result as the one you pasted from pcretest.

**Comment by nhahtdh** [comment]
Would you please confirm whether an error is thrown in regex101? As mentioned in the latest comment, I'm fine with the output, but the error should be shown to the user.

```
$ pcretest
PCRE version 8.38 2015-11-23

  re> /(*UTF)(\C)/g
data> xd🀄abcdeg
 0: x
 1: x
 0: d
 1: d
 0: \x{f0}
 1: \x{f0}
Error -11 (bad UTF-8 offset)
data>
```

**Comment by firasdib** [comment]
My bad, I was testing without `(*UTF)`. 

The error was being discarded in the matcher, but will now be included and shown. What should the message say? `Bad UTF-8 offset` isn't too informative. This is what the docs say:

```
 The UTF-8 byte sequence that was passed as a subject  was  checked  and
 found  to be valid (the PCRE_NO_UTF8_CHECK option was not set), but the
 value of startoffset did not point to the beginning of a UTF-8  charac-
 ter or the end of the subject.
```

Perhaps `The match was halted because a token in your expression did not point to a valid UTF-8 character` or something along those lines?

**Comment by nhahtdh** [comment]
I would change a bit to "The match was halted because the offset does not point to the beginning of a valid UTF-16 character".

By the way, this is the output of `pcretest` with 16-bit library:
```
$ pcretest -16
PCRE version 8.38 2015-11-23

  re> /(*UTF)(\C)/g
data> xd🀄abcdeg
 0: x
 1: x
 0: d
 1: d
 0: \x{d83c}
 1: \x{d83c}
Error -11 (bad UTF-16 offset)
data>
```

**Comment by firasdib** [comment]
Yes, I'm producing the correct results now with the right message. Thanks for the help!

**Comment by nhahtdh** [comment]
By the way, you should also catch this error in the debugger - the debugger fails to show anything, and the web console shows this error:

> TypeError: callout_data[match_id] is undefined

**Comment by firasdib** [comment]
Must be specific to the old debugger, I can debug that expression in the new version without seeing that error.
