### ISSUE TITLE
Add new task

### ISSUE THREAD

**Issue by DustinByfuglien** [firasdib/Regex101#1902]
Good day!
I suggest to add one more Quiz task for experienced users:

For every string replace:
   - semicolons ";" with commas ","
   - first unhappy smile ":(" and last unhappy smile ":(" with happy ones ":)"

**Comment by firasdib** [comment]
I appreciate the enthusiasm! These are quite rudimentary tasks for the most experienced regexers, but perhaps you can try out your ideas with the people over in the IRC channel. You can find a link in the left sidebar on the website `Live Help`.
