### ISSUE TITLE
Task 11 wrong solution not rejected

### ISSUE THREAD

**Issue by DustinByfuglien** [firasdib/Regex101#1908]
### Task
TASK 11: VALIDATE FLOATING POINT NUMBERS

### Bug Description
``^[-+]?\d*([.,]?\d+|\d[.,])(e?[-+]?\d+)?$``
This solution must be rejected as it permits "2+5" as valid floating point number.
But it not rejected now.

**Comment by firasdib** [comment]
Thank you, I will have this fixed soon.
