### ISSUE TITLE
Forward slash in character class is interpreted incorrectly

### ISSUE THREAD

**Issue by clupasq** [firasdib/Regex101#191]
Using JavaScript syntax, the regex `[/]` is interpreted as being invalid: **_/ Unescaped delimiter**_

However, in Chrome Console I can succesfully run:

```
'/'.match(/[/]/);
```

which returns

```
["/"]
```

**Comment by lubber-de** [comment]
This is still or again an issue
![image](https://user-images.githubusercontent.com/18379884/207039899-61174239-7fc0-4f04-8f73-d1eef4d2e2b5.png)

**Comment by firasdib** [comment]
@lubber-de select the JS flavor.

**Comment by lubber-de** [comment]
> @lubber-de select the JS flavor.

That did the trick! 😄 Thanks!
