### ISSUE TITLE
Allow Regex101 site to work Fluid Mac

### ISSUE THREAD

**Issue by macdevign** [firasdib/Regex101#1911]
I notice recently that Regex101 site stop working using Fluid Mac (https://fluidapp.com/) (software that turn website into app)
with the following error:

![image](https://user-images.githubusercontent.com/6662383/192692531-954462b4-e820-4d2b-8874-f65a6b866f53.png)

Is it possible to fix this error as it seem to be some kind of js error running on fluid mac. 

thank

**Comment by working-name** [comment]
Hello, that's a third party software that simply caches a site locally as much as possible. That means it has a high chance of being behind in terms of code, or grabbing a version of the site that has a bug, and so on.

What have you tried to fix it?
