### ISSUE TITLE
How to get a share link after you have saved a regex?  

### ISSUE THREAD

**Issue by bbneo** [firasdib/Regex101#1914]
## Question
After you save a regex, the "share/save" link goes gray.

**Comment by working-name** [comment]
Hi there,

The share link is exactly the same as the current URL. If you're not logged in, the delete link will no longer be available once you close the current tab - keep that in mind.

**Comment by firasdib** [comment]
The delete link will be saved in your local storage. If you visit the same url in the future, with the same browser, you will be able to delete it. Vänliga hälsningar / Best regards,Firas DibOn 2 Oct 2022, at 19:42, Alan ***@***.***> wrote:﻿
Hi there,
The share link is exactly the same as the current URL. If you're not logged in, the delete link will no longer be available once you close the current tab - keep that in mind.
