### ISSUE TITLE
Support for PHP bracket style delimiter pairs

### ISSUE THREAD

**Issue by codebymikey** [firasdib/Regex101#1917]
## Feature
It'd be nice if the tool supported [PHP bracket style delimiter pairs](https://www.php.net/manual/en/regexp.reference.delimiters.php)

e.g.
```
(this [is] a (pattern))
{this [is] a (pattern)}
[this [is] a (pattern)]
<this [is] a (pattern)>

{[\{]}
{[}]}
{[\}\{]}
```

Inspired by [this blog post](https://codelegance.com/ideal-regex-delimiters-in-php/#theidealdelimiter) and wanted to test its limitations out with the awesome Regex101 tool.

**Comment by firasdib** [comment]
I can see where this can be useful, but they require some additional work that I'm not prepared to implement. Primarily, they have to be balanced to not be throwing errors, i.e., the pattern `{{}` will throw an error and require the middle `{` to be escaped.

The benefits aren't that great to me, and as such, aren't worth the extra implementation cost.
