### ISSUE TITLE
My working editor is replaced when clicking "Load example in editor"

### ISSUE THREAD

**Issue by dikiprawisuda** [firasdib/Regex101#1920]
## Question
Hi, I was working inside the editor. While reading the "Quick reference" I accidentally clicked the right arrow button that says "Load example in editor". It changes my current working editor with the previously selected "Quick reference". I could not call it back with Ctrl+Z. Was this intended to behave like so?

Thank you.

**Comment by firasdib** [comment]
Yes, this is intentional.

You can click the input box and ctrl+z to go back to the previous input.
