### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by CarlGroth** [firasdib/Regex101#1922]
## Bug Description
"A critical error has occurred"

### Reproduction steps
1. Select ECMAScript
2. enter `aaaaaaa` as your test string
3. enter `(.)\1` as your regular expression
4. hit `0`

### Expected Outcome
Not a crash

### Browser
Include browser name and version
Chrome
Version 106.0.5249.103 (Official Build) (arm64)

### OS
Include OS name and version
macos Monterey 12.6

**Comment by firasdib** [comment]
Thanks. Silly error on my end, I will push a fix.
