### ISSUE TITLE
Unsupported (*MARK) verb, other named verbs and MARK substitution

### ISSUE THREAD

**Issue by DustinByfuglien** [firasdib/Regex101#1923]
## Bug Description
Regex101 don't understand following PCRE2 constructs:
- MARK verb: ``(*:name) or (*MARK:name)``
- other verbs with name, such as ``(*ACCEPT: name)``
- ``$*MARK, ${*MARK}`` replacement constructs

### Reproduction steps
The user [was unable](https://stackoverflow.com/a/74018447) to test his regex by regex101

**Comment by firasdib** [comment]
Thank you. This looks like an oversight on my part w.r.t how verbs are parsed. I have a fix locally and will push it live soon.
