### ISSUE TITLE
Python substitute code generator bug 

### ISSUE THREAD

**Issue by nilsherzig** [firasdib/Regex101#1924]
## Bug Description

Looks like the python substitute generator uses $n to reference capture groups. 

It generated this sub string for me:
`subst = "\"<a href=\"$2.md.html\">$2</a>\""`
this string doesn't work in 3.10.7. 

This works for me
`subst = r"\"<a href=\"\2.md.html\">\2</a>\""`
using a raw string and \ instead of $

**Comment by Genericreqd** [comment]
ttps://semver.org/spec/v2.0.0.html

**Comment by nilsdev** [comment]
@Genericreqd wdym?

**Comment by Genericreqd** [comment]
...

**Comment by firasdib** [comment]
The code generator doesn't translate the regex between flavors, you'll have to pick the correct flavor from the UI and adjust your regex accordingly first.
