### ISSUE TITLE
Why does substitution includes a string that is not part of any group

### ISSUE THREAD

**Issue by serranomorante** [firasdib/Regex101#1935]
## Bug Description

Substitution includes a string that is not part of any group in the replacement.

![Issue with Regex101 substitution](https://i.postimg.cc/52v7Cb7F/msedge-20221030-095238-368.png)

### Reproduction steps

Here's the [public link](https://regex101.com/r/nimpyL/1) to the regex

### Expected Outcome

Instead of `This string before date should not be included 01 oct. 2022 0_00 PM - 000 0000 0000.mp4`, the output should be `01 oct. 2022 0_00 PM - 000 0000 0000.mp4`

### Browser
Edge latest

### OS
Windows 10 Pro latest

**Comment by DustinByfuglien** [comment]
There is no bug. In source string fragment ``01 oct. 2022 0_00 PM AnotherString_ 000 0000 0000`` replaced with ``01 oct. 2022 0_00 PM - 000 0000 0000.mp4``. So source string correctly became ``This string before date should not be included 01 oct. 2022 0_00 PM - 000 0000 0000.mp4``

**Comment by serranomorante** [comment]
> 01 oct. 2022 0_00 PM AnotherString_ 000 0000 0000

Thanks for the quick response!

What should I do to get just `01 oct. 2022 0_00 PM AnotherString_ 000 0000 0000` as the result? Or is it simply not possible?

**Comment by DustinByfuglien** [comment]
You can use ``^.*?`` in the beginning of your regex ``^.*?(\d{1,2}\s\w{1,5}\.\s\d{4}[^_]+_\d{1,2}\s[^\s]+)\s[^_]+_\s(.+)``

**Comment by serranomorante** [comment]
You're right! Thanks!

**Comment by firasdib** [comment]
Try the ”List”-function!Vänliga hälsningar / Best regards,Firas DibOn 31 Oct 2022, at 01:04, Patricio Serrano ***@***.***> wrote:﻿
Closed #1935 as completed.
