### ISSUE TITLE
Website crash - (A critical error has occurred)

### ISSUE THREAD

**Issue by atkvishnu** [firasdib/Regex101#1936]
## Bug Description
**Website crashing after making changes to the REGEX pattern.**

##### Error message
```
A critical error has occurred
If possible, open up an issue with as many details as you can here: https://github.com/firasdib/Regex101/issues.

It might be a good idea to take a screen shot of your dev console window, if you know how to open it.
```

### Reproduction steps
After making minor changes to the Regex pattern, when the regex pattern is getting executed, this crash is occurring.
This has been happening to me from yesterday.
```
Flavor: GoLang
Function: Match
```

### Expected Outcome
Should not crash when making changes to the regex pattern.

### Browser
Include browser name and version - `Chrome 106`

### OS
`Ubuntu 22.04.1 LTS`

### Including SS of dev console.

![image](https://user-images.githubusercontent.com/27785198/200175316-da7cf7f9-84b0-4687-ac9d-d12d79a42938.png)

**Comment by working-name** [comment]
Hi there,

Can you please try with all addons disabled, and if it still crashes can you please share your regex link? I've tried to get 106 but now it's 107 and I can't make it crash - using it in a VM on ubuntu 22.04.1 LTS. I have golang selected.

**Comment by firasdib** [comment]
Closing as there is no info.
