### ISSUE TITLE
Requesting TCL and PERL flavours. Widely used by VLSI engineers.

### ISSUE THREAD

**Issue by thahmidul-nafi-primesilicon** [firasdib/Regex101#1937]
## Flavor Request
Requesting TCL And PERL flavours. Widely used by VLSI engineers.

**Comment by cklim483** [comment]
> 
> 
> ## Flavor Request
> Requesting TCL And PERL flavours. Widely used by VLSI engineers.
-

**Comment by cklim483** [comment]
> 
> 
> ## Flavor Request
> Requesting TCL And PERL flavours. Widely used by VLSI engineers.
> 

[]()

**Comment by firasdib** [comment]
Follow TCL here #1189 
Perl - use PCRE2
