### ISSUE TITLE
Update .NET regex engine to .NET 7.0

### ISSUE THREAD

**Issue by danmoseley** [firasdib/Regex101#1939]
.NET 7 just was released. Could you please update to use it ? 

https://dotnet.microsoft.com/en-us/download/dotnet/7.0

https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/

**Comment by firasdib** [comment]
The website already uses .NET 7. Are there any features you feel are missing?

**Comment by Ernest314** [comment]
@danmoseley I would be interested in support for `RegexOptions.NonBacktracking` as well, +1 for that!

**Comment by danmoseley** [comment]
@Ernest314  great -do you want to open that suggestion? (I have a bias 🙂)

**Comment by firasdib** [comment]
Thanks for opening up the other issue, I will look into it.
