### ISSUE TITLE
Regex debugger: PCRE2 (PHP>=7.3) the greedy quantifier (*) giving back 

### ISSUE THREAD

**Issue by sasky621** [firasdib/Regex101#1940]
## The bug is in the debugger PCRE2 (PHP >=7.3), the greedy quantifier (*) when giving back as needed the debugger does not give back to the matched value.

1- suppose this is our regex pattern:

>/-font:'(\S*)\s*(\S*)';/mg

The problem when the debugger trying to give back specifically at the second **(\S\*)** of the mentioned pattern.

2- this is our string:

>"data-template='Test xxx' root{--primary-font:'XYZSans';--secondary-font:'TestSans1';--hero-background:#ffbe3f;--heade ';r-colour-highlight:#f0591e--header-background:#ffffff;--header-colour-tabs:#1d2130;}"

NOTE: The debugger on PCRE (PHP <7.3) works well.

**Comment by working-name** [comment]
What/why should the regex engine not backtrack at the second \S* ?

**Comment by firasdib** [comment]
Closing as there is no reply.
