### ISSUE TITLE
Immediate site crash on older safari version

### ISSUE THREAD

**Issue by justisr** [firasdib/Regex101#1941]
## Bug Description
Immediate site crash
![](https://i.gyazo.com/43e1ba20321f6d2fb999dc811bd8b33b.png)

### Reproduction steps
Open regex101.com

### Expected Outcome
Page load

### Browser
Safari Version 13.1.3 (15609.4.1)

### OS
macOS Catalina 10.15.7

**Comment by sideshowlol** [comment]
Same issue as @justisr using Safari 13.1.2 on Mac OS X  10.13.6.

**Comment by working-name** [comment]
This happens with addons disabled as well?

I tried to test it out but the lowest system I have runs Safari 14.1 and that doesn't crash.

**Comment by firasdib** [comment]
Thank you. I have identified the issue and fixed it locally. I will push it live soon.

**Comment by sideshowlol** [comment]
> Thank you. I have identified the issue and fixed it locally. I will push it live soon.

**Comment by sideshowlol** [comment]
Many thanks! 🙏 Will have a look this evening.

**Comment by Eleake37** [comment]
Duplicate of #
