### ISSUE TITLE
An option to treat each line as a different input

### ISSUE THREAD

**Issue by MarcTCruz** [firasdib/Regex101#1943]
**An option to treat each line as a different input**
It's a nice feature for when the regex is absent of multiline and global flags but the user needs a lot of rows to be tested against a given pattern.

**Comment by working-name** [comment]
Hello! Thank you for your suggestion, please follow #795 ( for more context please see #1608 ).

**Comment by firasdib** [comment]
Multiple text strings will be supported in the next release.
