### ISSUE TITLE
Add "color-scheme: dark" in ":root[data-theme=dark]"

### ISSUE THREAD

**Issue by const513** [firasdib/Regex101#1945]
## Feature
To solve the problem with light scrollbars in Chrome/Edge and other Chromium browsers in dark mode, I recommend adding the following code :

`:root[data-theme=dark] { color-scheme: dark; }`

For more information follow here : [https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme)

**Comment by firasdib** [comment]
Thank you! I will add this.
