### ISSUE TITLE
Update regex requires adding/removing space at end of 'saved name'

### ISSUE THREAD

**Issue by apsis0215** [firasdib/Regex101#1948]
## Bug Description
Update regex requires adding/removing character in filename

### Reproduction steps
login
save regexp
modify regex
update regexp
save [greyed out]
modify 'personal title' by one character
save [now available]
save successful

### Expected Outcome
Update regexp
Save

### Browser
Version 107.0.5304.122 (Official Build) (64-bit)

### OS
Windows 10 pro
21H2
19044.2251
pack: 120.2212.4180.0

![2022-11-30(chrome) t162801 regex101_Date_Time_strings_-_Google_Chrome](https://user-images.githubusercontent.com/2146809/204930320-6652a7e7-3634-4220-81e8-a469383dc35e.gif)

**Comment by firasdib** [comment]
The regex is updated as soon as the modal is shown, i.e., you don't need to do anything else. The save button is means to save the changes you made to your expressions title and similar. Perhaps this is more of a UX issue than a bug. Any suggestions on how to clarify it?

**Comment by firasdib** [comment]
Would it be better if there was an artificial delay to show that there has actually been a save?

**Comment by firasdib** [comment]
I've done a few ux changes to hopefully alleviate the confusion described in this issue.

**Comment by Emmagodnuel** [comment]
#1940
