### ISSUE TITLE
[Bug] [UX] Substitution output area hardly selectable with touch screen

### ISSUE THREAD

**Issue by MasterInQuestion** [firasdib/Regex101#1949]
Long-click to select won't trigger context menu due to the "&lt;textarea>"'s configuration.
    Double-click to select all meets the same awkwardness.

    Related: [
    |&#x2A;| Select All Substitution
    |&#x2A;| [https://github<i>.</i>com/firasdib/Regex101/issues/12](https://github.com/firasdib/Regex101/issues/12) ]

**Comment by iwancorong** [comment]
[
  [
    {
      "content": "1",
      "isParticipating": true,
      "groupNum": 0,
      "startPos": 5,
      "endPos": 6
    }
  ],
  [
    {
      "content": "2",
      "isParticipating": true,
      "groupNum": 0,
      "startPos": 13,
      "endPos": 14
    }
  ]
]

**Comment by firasdib** [comment]
This should be resolved with the upcoming update using Codemirror 6.

**Comment by MasterInQuestion** [comment]
If not, simply adding a button to copy the full content should also largely address the issue.

    Verified fixed.
