### ISSUE TITLE
incorrect substitute in PHP for adding new line

### ISSUE THREAD

**Issue by jszczypk** [firasdib/Regex101#1950]
## Bug Description

When trying to add new line character using substitution incorrect code is generated for PHP because substitution string is incorrectly escaped - should be using double quotes instead of single quotes.

### Reproduction steps

flavor: PHP (any)
function: Substitution
regular expression: `\|`
test string `a|b`
substitution: `\n`

Preview shows correctly
```
a
b
```

Generated code

```
$re = '/\|/m';
$str = 'a|b';
$subst = '\\n';

$result = preg_replace($re, $subst, $str);

echo "The result of the substitution is ".$result;
```

Output of generated code

```
The result of the substitution is a\nb
```

### Expected Outcome

Generated code

```
$re = '/\|/m';
$str = 'a|b';
$subst = "\n";

$result = preg_replace($re, $subst, $str);

echo "The result of the substitution is ".$result;
```

Output of generated code

```
The result of the substitution is a
b
```

**Comment by OnlineCop** [comment]
Tested this on [onlinephp.io](https://onlinephp.io?s=fY5BCoMwEEX3gncYQsEWih4gLb1ElwFRm5qANSEZdx6-mdgQN3aX_2b-y9weVtmyODkJd6gasTafiofs0RHo1n6LS--x7bsXQSHmHRyNIcrEzAKMKr9Madk6ObZO2qkb5DmMrpBd9EZ34bnzcx2WaJ5bZSEHZYA9lYRNAOYNGBL9HRsaF9RmBu1BMFbvbqtZADwptuOPdPGsfz5aSMIv):

```php
    <?php
    $re = '/\|/m';
    $str = 'a|b';
    $subst_bad = '\\n';
    $subst_good = "\n";
    
    $result_bad = preg_replace($re, $subst_bad, $str);
    $result_good = preg_replace($re, $subst_good, $str);

    echo "The result of the bad substitution is \"".$result_bad."\"";
    echo "\n";
    echo "The result of the good substitution is \"".$result_good."\"";
```
Result:
```
The result of the bad substitution is "a\nb"
The result of the good substitution is "a
b"
```

**Comment by firasdib** [comment]
Thank you, I will change the quotes to double quotes for the substitution text.
