### ISSUE TITLE
Add support for .NET 7 non-backtracking option

### ISSUE THREAD

**Issue by Ernest314** [firasdib/Regex101#1951]
*(continuing the discussion from #1939)*

## Flavor Request

.NET 7 adds a new option to regexes, `RegexOptions.NonBacktracking`. The only currently available documentation seems to be in [this blog post](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#backtracking-and-regexoptions-nonbacktracking), although Microsoft does also have a page that discusses backtracking in general [here](https://learn.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions) (though it makes no mention of this new option, nor is it very relevant).

This would be a nice feature to have so that C# devs can try out their regexes intended for use with this option, and it might be easier to implement than an entirely new flavor since it's supposed to be a subset of current C# regex functionality.

**Comment by firasdib** [comment]
Thank you, I will add this option to the UI.
