### ISSUE TITLE
JavaScript Code Generator: add functions for \U, \L, \E used in replacement string

### ISSUE THREAD

**Issue by MBM1607** [firasdib/Regex101#1956]
## Bug Description
The code generator for javascript creates faulty code when replacement with text case conversion is used

### Example
```
const regex = /([aeiouy])(\s*)([bcdfghjklmnpqrstvwxz])/gmi;

// Alternative syntax using RegExp constructor
// const regex = new RegExp('([aeiouy])(\\s*)([bcdfghjklmnpqrstvwxz])', 'gmi')

const str = `hello world
xaabeuekadii
A quick brown fox jumps over the lazy dog`;
const subst = `$1$2\U$3\E`;

// The substituted value will be contained in the result variable
const result = str.replace(regex, subst);

console.log('Substitution result: ', result);
```

### Reproduction steps
Use `\U` or `\L` in substitution regex and then generate js code

### Expected Outcome
The generator should ideally give the appropriate conversion function in js.

### Browser
> Firefox 108.0

### OS
> Pop!_OS 22.04 LTS x86_64

**Comment by MBM1607** [comment]
I would be willing to take this up, but I couldn't find the js conversion tool source code.

**Comment by working-name** [comment]
Hello!

As far as I know this is not a feature implemented by the javascript regex engine (although there are [workarounds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_function_as_the_replacement)). Are you proposing this as a new, site-only feature?

**Comment by MBM1607** [comment]
Hi, I was proposing that the generator should also generate the relevant replacer function.

**Comment by working-name** [comment]
Got it 👍, so that's a feature request but it's external to javascript's regex implementation aka it doesn't know about `\U` yet.

**Comment by firasdib** [comment]
If you use the JS flavor it will show that this token is unsupported in that flavor.

The code generator does not do any conversions.
