### ISSUE TITLE
sed flavor

### ISSUE THREAD

**Issue by mimi1vx** [firasdib/Regex101#196]

**Comment by CodeMan99** [comment]
Unnecessary, `sed -r` uses extended regular expressions (found in the sed 4.2.2 man page).

Issue #165 is much more important.

**Comment by cheako** [comment]
From what I understand this would be covered by POSIX...  Though when u think of sed you think of substitutions/replacements and I'm not sure regex101 covers these well.

For now I think this should be marked duplicate of #165 and closed to avoid confusion.

**Comment by vktec** [comment]
@CodeMan99 `sed -E` is more portable than `sed -r`.
@cheako re101 covers substitutions fine, though it doesn't use the same syntax as sed.

I agree that this is mostly a duplicate of #165, though it would also be nice to have a POSIX BRE mode.

**Comment by grantwwu** [comment]
I think it would be helpful to have a sed flavor.

Sed's syntax does not appear to match the existing flavors that well.  For example, you use `\1`, not `$1` to reference capturing groups, and `\d` is not supported.  I'm sure there are a lot more differences too.

**Comment by vktec** [comment]
@grantwwu You can use \1 in PCRE afaik. POSIX ERE (which sed supports, as previously mentioned) is, for the most part, a subset of PCRE, so you should be fine testing with that and just not using the extra features.
ERE is quite small and fairly well documented (`man 7 regex`) so it shouldn't be too difficult to figure out what the unsupported features are.

**Comment by firasdib** [comment]
It's in progress. Better late than never: https://github.com/firasdib/Regex101/issues/1230#issuecomment-5133454421
