### ISSUE TITLE
Named Capture Group in Substitution missing in 'Quick Reference'

### ISSUE THREAD

**Issue by dbareis** [firasdib/Regex101#1963]
The reference says how to name a capture group but not how to use one, a lot of googling and trying later I find that it is angle brackets.

Some of the things I tried before (**$&lt;Name&gt;**):

1. $Name
2. $(Name)
3. ${Name}
4. $[Name]

**Comment by firasdib** [comment]
For which flavor? What is it you feel is missing?

**Comment by dbareis** [comment]
Oops, you are correct, the help differs by type :-)

I have worked though the available types and it is missing for:

1. ECMAScript
2. Java 8

By "missing", I mean that the "Group Constructs" for that type says how to create a group but "Substitution" doesn't say how to use it.

**Comment by firasdib** [comment]
Thank you, fixed in the next release.
