### ISSUE TITLE
Unrecognized `\N{U+1234}`

### ISSUE THREAD

**Issue by Danon** [firasdib/Regex101#1967]
## Bug Description

In PHP dialect, notation `\N{U+1234}` matches character of unicode code point `1234`.

### Reproduction steps

```php
$result = preg_match('/\N{U+1234}/u', 'ሴ', $matched);
```
or
```php
$result = preg_match('/\N{U+1234}/u', chr(225) . chr(136) . chr(180), $matched);
```

It should only be recognized with `u` modifier or with `(*UTF)` verb.

According to my understanding, for any `dd`/`ddd`/`dddd` that works for `\x{dd}` it should also work for `\N{U+dd}`.

**Comment by firasdib** [comment]
I am unable to find documentation on this. Do you have a link to share?

**Comment by Danon** [comment]
No, sorry I don't :/

I'm writing a regular expression library (https://t-regx.com/), and I was trying to write a parser for regular expression. I didn't know exactly which parts are recognized by the PHP, so I have writting a script that tries different set of characters and by trial-and-error run it over days. 

Most return false, but `\N{U+1234}` returned true - which means it was recognized, and then I latered checked it and it is in fact recognized by the PHP on all versions, with `u` modifier.

**Comment by Danon** [comment]
@firasdib I found this reference in PCRE source code (it's in C). Maybe it'll be helpful:

https://github.com/PCRE2Project/pcre2/blob/7c49b40e8aed10cc2667dd3c4b7bb692d13ade2a/src/pcre2_compile.c#L1531

**Comment by firasdib** [comment]
`\N` is supported, but I wasn't aware of `\N{U+NNNN}`... I'll see if this is something we want to support, as it seems very undocumented.

**Comment by Danon** [comment]
Yea, but `\N` is something very different to `\N{U+NNNN}`. 

- `\N` is similar to `[^\n]` (not equal, since line convention can change, for example with `(*CR)`, then it's similar to `[^\r]`)
- `\N{U+NNNN}` is similar to `\xNNNN`.

**Comment by firasdib** [comment]
Thank you, I have implemented support for this and it will be included in the next release.
