### ISSUE TITLE
C# range with shorthand escape sequences

### ISSUE THREAD

**Issue by stevenh** [firasdib/Regex101#1969]
## Bug Description
If you create a regexp range with a shorthand escape sequence in C# it incorrectly fails with:
> You cannot create a range with shorthand escape sequences

### Reproduction steps
1. Syntax: `C#`
2. Regexp: `([\d-z]+)` 

### Expected Outcome
Valid regexp

### Browser
Chrome:  108.0.5359.126

### OS
Windows 11 

This can be validated with [fiddler](https://dotnetfiddle.net/fFCdCD)

**Comment by firasdib** [comment]
Thank you for the report, I'll have this fixed in the next release.
