### ISSUE TITLE
Partial Match like Ultrapico Expresso

### ISSUE THREAD

**Issue by JairoMartinezA** [firasdib/Regex101#1970]
## Partial Match
Using Windows, I knew an amazing regular expression tester:
https://ultrapico.com/Expresso.htm

I had to change to MacOS and I was testing Regex101, I want to suggest the possibility to add this feature. In Expresso you only need to SELECT a part of entire expression in order to test only that part:

![image](https://user-images.githubusercontent.com/5806694/212931260-c2b495ed-5fe2-4b07-9142-6e28180a18b0.png)

**Comment by firasdib** [comment]
Not sure this makes as much sense for regex101 as it does for Expresso, as the matches are run automatically on regex101. Thus you should just remove the part you don't want, see what happens, then hit ctrl+z and be back to where you just were.
