### ISSUE TITLE
Warning on refresh

### ISSUE THREAD

**Issue by borissov** [firasdib/Regex101#1973]
## Feature
Sometimes I hit refresh by mistake and it would be quite helpful to have a message and prevent refresh the page or store the regex string in cookie.

**Comment by working-name** [comment]
Hi @borissov,

That's already a feature - can you please let us know which browser you're using and maybe if you have ticked that box that disallows further notifications from the site? 

Maybe try another browser to double check.

If I change either the regex input or the text input and then try to refresh or close the tab the browser's own implementation of the unsaved changes dialog pops up (you trigger it via JS but it's really up to the browser on how to display it and what the message is).

Thanks!

**Comment by firasdib** [comment]
There is also an option for this in the settings on regex101, which by default, is enabled.
