### ISSUE TITLE
dynamic og image

### ISSUE THREAD

**Issue by j4k0xb** [firasdib/Regex101#1975]
## Feature

Would be useful to make the `<meta property="og:image"` for a shared link dynamic, based on the regex and first few lines of the test string.

to preview it in e.g. discord instead of showing the default 
![image](https://user-images.githubusercontent.com/55899582/213530220-87aa8526-86ab-47dd-8827-cdaa2de8792b.png)

**Comment by firasdib** [comment]
While I do think this would have been nice, this seems like a lot of work. The pattern must be highlighted and the matches ran in order to populate the UI, which are quite expensive operations.
