### ISSUE TITLE
Task 11 - Contradictory error messages?

### ISSUE THREAD

**Issue by Startrekzky** [firasdib/Regex101#1977]
#### Question 1

I was doing task 11:

- When I tried this `^[+-]?\d*(?:[\.,]\d*e?[+-]?\d+)?$`, it said `Test 34/93: A trailing dot or comma must be allowed.`
- Then I tried this `^[+-]?\d*[.,]?\d*(?:[\.,]\d*e?[+-]?\d+)?$`. It said `Test 39/93: Multiple dots or commas must not be allowed.`

Aren't these two hints contradictory?

#### Question 2
When I tried another one `^(?:[+-]?\d+(?:[.,]\d*(?:e\d+)?)?|[.,]\d*e?\d+)$`, it kept prompting `Test 45/93: A leading dot or comma must be allowed.` However, all my local tests passed(see below). Can you tell me one of your failed test cases? Thank you.
```
45
3.14159
3,14159
334,399
23.14159
23,14159
3979.141e59
3.e2
3,e2
.11
,11
.e2
,e2
.2e2
,2e2
-1.35
-2.e2
```

**Comment by Startrekzky** [comment]
Bump

**Comment by firasdib** [comment]
How so? You must allow a trailing dot, but not multiple.
