### ISSUE TITLE
Delimiter options are limited - "+" as delimiter

### ISSUE THREAD

**Issue by ericmarceau-rogers** [firasdib/Regex101#1981]
## Expanded set of delimiter specification - User-specified character not in drop-down menu

I use the "+" as a safe delimiter because I have fewer conflicts with that as the choice.  

Can that be offered as a drop-down option?

OR ... can the user be allowed to select any character of their choosing for the delimiter, as per original sed specification?

Thank you.

**Comment by firasdib** [comment]
It becomes complicated when characters which typically have a special meaning in regular expressions, as used as delimiters. While technically possible, I try to avoid it and don't want to cause the additional confusion.
