### ISSUE TITLE
A critical error has occurred

### ISSUE THREAD

**Issue by xjq7** [firasdib/Regex101#1984]
## Bug Description
the application crashes about 10 times a day, when I debug this regular expression, it's not Ininevitable, but it appeared during my repeated revisions
it didn't appear when I open the Console
![1675664969216](https://user-images.githubusercontent.com/42568663/216899541-e8856a79-de16-4c26-b8a7-4d09f7a65e4d.jpg)

### Reproduction steps
my regular expression: (?<=CQ:image,file[^]]*url=).+(?=])
my test string: [CQ:image,file=f8491e5343c51a79139da65cb675e06b.image,url=https://gchat.qpic.cn/gchatpic_new/412709767/638889540-2321296482-F8491E5343C51A79139DA65CB675E06B/0?term=3&is_origin=0,subType=0]

### Browser
Google Chrome 109.0.5414.120

### OS
windows 10

**Comment by firasdib** [comment]
Does it happen in incognito mode? Most times this happens is due to plugins/extensions in your browser.

**Comment by xjq7** [comment]
@firasdib Not happen in incognito mode

**Comment by xjq7** [comment]
What kind of plugins/extensions does this happen?

**Comment by firasdib** [comment]
Normally plugins that manipulate the DOM, e.g. translation plugins

**Comment by xjq7** [comment]
Hmmm, I used relingo translation plugin, I disabled it on this site, then tried
