### ISSUE TITLE
Wont be able to login either with google nor with github

### ISSUE THREAD

**Issue by Gaurav-2803** [firasdib/Regex101#1986]
## Bug Description
While signing in I tried both Google and GitHub but both were not working, it was redirecting to me "This site can’t be reached the webpage at https://regex101.com/connect/google?returnTo=/quiz might be temporarily down or it may have moved permanently to a new web address."

### Expected Outcome
It should let users sign in so they can use the regex quiz.

### Browser
Include browser name and version
Chrome Version - 109.0.5414.120 (Official Build) (64-bit)

### OS
Include OS name and version
Windows 11 22H2

**Comment by firasdib** [comment]
I am unable to replicate this on my end. Have you tried an incognito tab or another browser?

**Comment by Gaurav-2803** [comment]
Sorry for the inconvenience I tried it on incognito, it worked there after that, for the standard window I cleared the cache and cookies and it works for me.
