### ISSUE TITLE
Python substring causes special charactes to appear despite proper group match

### ISSUE THREAD

**Issue by TomKulakov** [firasdib/Regex101#1987]
Link to example here: https://regex101.com/r/4QhFpP/1

**Description**
Env: Python
Regexp: 
`/(^N\d* )(Z-?\d*(\.\d*)?$)\s(^N\d* )((X-?\d*(\.\d*)? Y-?\d*(\.\d*)?))\s(^N\d* )(Z-?\d*(\.\d*)?$)/mg`
Replacement:
`\1(-) \2\n\4(-) \5\n\9(-) \10`
Test String: 
```
N1 Z20.875
N2 X52.685 Y27.106
N3 Z16.875
```
Result:
```
N1 (-) Z20.875
N2 (-) X52.685 Y27.106
N3 (-) 
```
I can't copy it, but the square is U+0008 (which is backspace) and if you use deeper groups it became tab or something else

Excpected:
```
N1 (-) Z20.875
N2 (-) X52.685 Y27.106
N3 (-) Z16.875
```
This works in other similar tools and in my Python code.

**Comment by firasdib** [comment]
Thank you. I have fixed this locally and will push soon.

**Comment by TomKulakov** [comment]
Just adding more facts hoping this will be covered by a fixture - I've noticed that every group equal to 10 or higher causes this error. \10 or \11 ...etc

**Comment by firasdib** [comment]
I'm releasing this now, should be fixed in a few minutes.

**Comment by TomKulakov** [comment]
Tested on two cases. Works like it should! Thank you! 
PS: I find your platform best tool there is. Ultra elastic configuration, great explanation of rules, cozy design. :) Thank you for this!

**Comment by firasdib** [comment]
Thank you!Vänliga hälsningar / Best regards,Firas DibOn 14 Feb 2023, at 06:59, TomKulakov ***@***.***> wrote:﻿
Tested on two cases. Works like it should! Thank you!
PS: I find your platform best tool there is. Ultra elastic configuration, great explanation of rules, cozy design. :) Thank you for this!
