### ISSUE TITLE
Library Regex for Email needs to be corrected.

### ISSUE THREAD

**Issue by gajendhir** [firasdib/Regex101#1988]
## Bug Description
Existing Regex for Email

`\w+[@]+\w+[.]+[a-z]\w+`

This allows multiple consecutive dots (` . `) in an email address after the ` @ `

### Reproduction steps
check it for - emailad@example..com

### Expected Outcome
Not Matched but it matches
![Capture](https://user-images.githubusercontent.com/64296557/218085089-43b6c4ce-4b2c-4aa1-bd3e-19caee197ebc.PNG)

### Solution
A more appropriate regex for email would be

`\w+[@]+(?:\w+[.])+[a-z]\w+`

### Browser
Any

### OS
Any

**Comment by working-name** [comment]
Hi @gajendhir,

Thank you much for your feedback!

The library is open for submissions from anyone. You can vote entries up or down, and the idea is that the good ones would rise to the top. Please use your voting power and please feel free to post better regexes on there.
