### ISSUE TITLE
stray characters in quiz task 18

### ISSUE THREAD

**Issue by patrick-haldi** [firasdib/Regex101#1990]
## Bug Description
Quiz task 18 has some stray special characters:

```
Replace every other character if it''s a \d with * (only those in even positions: 2, 4, 6, etc).

Example: a1b2cde3~g45hi6 should become a*b*cde*~g4*hi6"
```

- first is a double apostrophe in `it''s`
- the other is the stray double quote at the end of the task: `a*b*cde*~g4*hi6"`

also, I'm not able to solve this quiz using `^((?:..)*?)(.)\d(.*)$` --> `$1$2*$3`, but that's probably just my bad

### Reproduction steps
- solve all quizes up to quiz 18

### Expected Outcome
Description should say:
```
Replace every other character if it's a \d with * (only those in even positions: 2, 4, 6, etc).

Example: a1b2cde3~g45hi6 should become a*b*cde*~g4*hi6
```

### Browser
Firefox 109.0.1 (64-bit)

### OS
Linux Kubuntu 22.04

**Comment by firasdib** [comment]
Thank you, I'll fix this asap.
