### ISSUE TITLE
[Suggestion] "+" should present literally (not translated to " ") in HTTP request parameter interpretation

### ISSUE THREAD

**Issue by MasterInQuestion** [firasdib/Regex101#1993]
For example, [ [https://regex101.com/?regex=+](https://regex101.com/?regex=+) ] should interpret to "+" (Plus Sign) (U+002B, 0x2B, &amp;<span>#</span>43;) instead of " " (Space) (U+0020, 0x20, &amp;<span>#</span>32;).

    Interpreting literal "+" as " " in certain request parameters is typically only expected for search queries.

    Related: #414 (already fixed)

**Comment by firasdib** [comment]
Looks to be the default behavior of Javascript unfortunately. Not sure if it can be overridden easily.

```js
new URL('http://localhost:3000/?regex=\w+').searchParams.get('regex') // "\w "
```

**Comment by MasterInQuestion** [comment]
Unrelated with JavaScript.
    It's the server's interpretation of the request query: which may be implemented arbitrarily.

    For more info: https://pastebin.com/raw/YTi5UzLq

**Comment by firasdib** [comment]
@MasterInQuestion I just showed you the implementation.

**Comment by MasterInQuestion** [comment]
Hmm... My apologies.
    Didn't realize that the interoperation of this parameter is implemented entirely on front-end with JavaScript.

    This RegEx should work: /<a href="https://regex101.com/?regex=%5B?%26%5Dregex=(%5B^%26%5D*)&flags=">[?&]regex=([^&]&#x2A;)</a>/ [1] (matching against the full URL string, take only "$1")
[1] Ideally which should be /<a href="https://regex101.com/?regex=%5B?%26%5Dregex=%5CK%5B^%26%5D*&flags=">[?&]regex=\K[^&]&#x2A;</a>/ [Note 1], but JavaScript has compatibility issues with lookbehind.
    .
    Then filter the result with "[decodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent)".
\
\
=== Further reading ===

[ [Note 1]
    More ideally this should be implemented in 2-pass, and typically gathering all parameters at once:
    |1| /<a href="https://regex101.com/?regex=%5C?(%5B^=%5D%2B)(?:=(%5B^%26%5D*))?&flags=">&#x5C;?([^=]+)(?:=([^&]&#x2A;))?</a>/ &&
    |2| /<a href="https://regex101.com/?regex=%26(%5B^=%5D%2B)(?:=(%5B^%26%5D*))?&flags=g">&([^=]+)(?:=([^&]&#x2A;))?</a>/g [ This should start from where |1| ends. ]

    For [Just-in-Time](https://en.wikipedia.org/wiki/Just-in-time_compilation) compiled implementations (like JavaScript): the compilation cost should also be taken into performance consideration. ]
