### ISSUE TITLE
re2 flavor for Google Sheets Regex Needed

### ISSUE THREAD

**Issue by DestoGit** [firasdib/Regex101#2000]
Hello,

Would you please add the re2 Flavor for Google Sheets?
I found the syntax here.
[google
/
re2 Syntax](https://github.com/google/re2/wiki/Syntax)

Many thanks!

**Comment by OnlineCop** [comment]
RE2 has already been added to regex101: (the [Golang](https://regex101.com/static/assets/flavors.md) flavor is RE2).

**Comment by DestoGit** [comment]
Thanks for letting me know!
