### ISSUE TITLE
The inline flag `(?a)` doesn't work (Python)

### ISSUE THREAD

**Issue by Serious54088** [firasdib/Regex101#2003]
Pattern: `(?a)\w+`

String: `你好hello`

![image](https://user-images.githubusercontent.com/28971568/219852831-70fe36b6-ac48-4ad7-a9c8-b9ba5515213b.png)

`(?a)` make `\w` perform ASCII-only matching, the correct result should be: `hello` .

**Comment by firasdib** [comment]
Thank you, this will be adjusted in the next release.

**Comment by Serious54088** [comment]
This is an automatic reply, confirming that your email was received. I will reply as soon as possible. Thank you!
