### ISSUE TITLE
Whitespace-only unit test text is unclear

### ISSUE THREAD

**Issue by alystair** [firasdib/Regex101#2004]
## Bug Description

See screenshot below, text becomes confusing

![image](https://user-images.githubusercontent.com/159109/219977084-e86933d5-87ad-4236-961a-52558ce4dc96.png)

### Reproduction steps

Create a unit test where content consists only of whitespace characters

### Expected Outcome

Unit test text should be modified to better showcase what is included

### Browser
Chrome 110.0.5481.96 (Official Build) (64-bit) (cohort: Stable) 

### OS
Win 11 22H2

**Comment by firasdib** [comment]
Thank you, will be included in the next release.
