### ISSUE TITLE
Remove warning about named capture groups in ECMAScript

### ISSUE THREAD

**Issue by atjn** [firasdib/Regex101#2005]
Hello and thank you for providing this amazing tool! If it was open source I would have committed this as a PR instead of asking you to do it, and I would also have checked for other similar rules that might need to be removed. I hope I will be able to do that sometime in the future :)

When trying to use named capture groups in ECMAScript, the editor warns me `This construct may not be supported in all browsers`. I think you should remove that. All browsers support it, and the last engine to get it was Firefox's Gecko, which has now supported it for 2.5 years. Reference: https://caniuse.com/mdn-javascript_regular_expressions_named_capture_groups

**Comment by OnlineCop** [comment]
When ECMAScript is selected, the browser's own Javascript engine is used, and that isn't always consistent (Safari, some Firefox versions, Edge, Internet Explorer, etc. may not fully support all features -- like lookbehinds). Until those browsers can actually get their act together, this was the best trade-off.

**Comment by atjn** [comment]
@OnlineCop I understand that, and I am saying that the browsers got their act together when it comes to named capture groups, so it is safe to remove this warning.
Lookbehinds are a different story, but it should also be possible to remove that warning within the next year.

**Comment by firasdib** [comment]
You're right, there's almost 95% coverage, so it should be sufficient to remove this warning now. Thank you.
