### ISSUE TITLE
.NET: swap "null" for "empty string" or similar on empty matches

### ISSUE THREAD

**Issue by qrjo** [firasdib/Regex101#2008]
## Bug Description
When a regex or subgroup matches an empty string this shows up in the match information panel as "null" (in italics). However, .NET doesn't actually return null as value for the match, but an empty string. This is confusing. I think it would be clearer if the match information showed "empty string" in italics or something similar.

### Reproduction steps
1. Set flavor to .NET (C#)
1. Set regex to `a?`
1. Check the match information panel: it shows match 1 as _null_

[https://regex101.com/?flavor=dotnet&regex=a?](https://regex101.com/?flavor=dotnet&regex=a?)

### Expected Outcome
The match should show as _empty string_ or something similar.

**Comment by Assistedout** [comment]
Cody Cody Cody Cody hahahahahah

**Comment by firasdib** [comment]
Thank you for the suggestion, I will update this in the next release.
