### ISSUE TITLE
Generate regex for a specific string in /var/log/drupal.log file

### ISSUE THREAD

**Issue by kaushalshriyan** [firasdib/Regex101#2009]
Hi Team,

I have the below strings in the /var/log/drupal.log file. Is there a way to create regex for the below strings? 

```
Jan 25 17:35:05 testbase drupal #1 [internal function]: _drupal_error_handler()
Jan 25 17:35:05 testabase drupal: #2 /var/www/html/localdev/web/modules/contrib/mimemail/src/Utility/MimeMailFormatHelper.php(521): parse_str()
Jan 25 17:35:05 testbase drupal: #3 /var/www/html/localdev/web/modules/contrib/mimemail/src/Utility/MimeMailFormatHelper.php(183): Drupal\mimemail\Utility\MimeMailFormatHelper::mimeMailUrl()
```

I need some guidance. Thanks in advance. 

Best Regards,

Kaushal

**Comment by kaushalshriyan** [comment]
Checking in again if someone can pitch in for my post here. Thanks in Advance.

**Comment by working-name** [comment]
@kaushalshriyan Hi,

We have a live regex help feature on the site, in the sidebar:
![image](https://user-images.githubusercontent.com/16505052/222811601-fb265c2c-d2da-4ed9-a4ba-7778082a85b8.png)

It's much faster to get help there, plus, github repo is more for bug reporting and feature requests.

Looking forward to seeing you there! Just post this github issue link when you arrive and explain what you would like matched from the string.
