### ISSUE TITLE
Pretty-Print regexes with /x style option for all flavors

### ISSUE THREAD

**Issue by BobPritchett** [firasdib/Regex101#2010]
## Feature
It's hard to read complex regexes... support an 'ignore whitespace' option even for flavors that don't have the /x format.

Offer to pretty-print a regex, converting existing spaces to `\x20`, and an option to 'collapse' back to JavaScript-compatible version with no spaces.

(Bonus: Support a flavor of white-space supporting regex template literals for JavaScript, like https://github.com/shannonmoeller/regx)

Pretty-print logic could be a newline and four-space tab at each ( that has more than 6(?) characters before the closing ), space or newlines around |, etc. For example:

`(?<country \+?1[-\s]?)?(?<number>(?:\(\d{3}\)*\s\d{3}-\d{4})|(?:\d{3}(?:-|\s*)\d{3}-\d{4})|(?:\d{10}))(?<extension>(?:(x|ext)\.?))`
is rendered:
```
(?<country> \+?1[-\s]? )?
(?<number> 
    (?: \(\d{3}\)*\s\d{3}-\d{4}) 
        | (?:\d{3}(?:-|\s*)\d{3}-\d{4}) 
        | (?:\d{10} )
    )
(?<extension> (?: ( x | ext ) \.? ) )
```

but

`(automobile(s?)|motorcar(s?))`
is
```
( 
    automobile(s?)
    | motorcar(s?)
)
```

(no newline for the small `(s?)` groups...)

**Comment by BobPritchett** [comment]
^(?<Name>(?<=^)(?:(?<Domain>(?:(?:localhost|[\w-]+(?:\.[\w-]+)+)(?::\d+)?)|[\w]+:\d+)\/)?\/?(?<Namespace>(?:(?:[a-z0-9]+(?:(?:[._]|__|[-]*)[a-z0-9]+)*)\/)*)(?<Repo>[a-z0-9-]+))[:@]?(?<Reference>(?<=:)(?<Tag>[\w][\w.-]{0,127})|(?<=@)(?<Digest>[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][0-9A-Fa-f]{32,}))?

becomes (something like... quick mockup:)

^(?<Name>
    (?<=^)
    (?:
        (?<Domain>
            (?:
                (?:localhost
                | [\w-]+
                  (?:\.[\w-]+)+
                )
               (?::\d+)?
            )
            | [\w]+:\d+
        )\/
    )?\/?
(?<Namespace>
    (?:
        (?:[a-z0-9]+
            (?:
                (?:[._]|__|[-]*)
                [a-z0-9]+
            )*
         )\/
    )*
)
(?<Repo>
    [a-z0-9-]+
)
)
[:@]?
(?<Reference>
    (?<=:)
    (?<Tag>[\w][\w.-]{0,127})
    | (?<=@
)
(?<Digest>
        [A-Za-z][A-Za-z0-9]*
        (?:
            [-_+.][A-Za-z][A-Za-z0-9]*
        )*[:][0-9A-Fa-f]{32,}
    )
)?

**Comment by firasdib** [comment]
Dup of https://github.com/firasdib/Regex101/issues/1283
