### ISSUE TITLE
Task 20, Test 13 extraneous backslash?

### ISSUE THREAD

**Issue by patrick-haldi** [firasdib/Regex101#2012]
## Quiz Bug
DO NOT POST QUIZ SOLUTIONS!

### Task
Task 20: Quoted text with escapes

### Bug Description
The hint says:
`Test 13/18: A \ escapes only one character. Therefore, the text "balanced \\\\" quotes" should be valid. It contains an escaped \ and a escaped "`

But there are four backslashes. That would be two escaped backslashes, followed by an unescaped quote, right? 

Or am I completely off?

### Expected Outcome
IMHO, it should be
`"balanced \\\" quotes"`

### Browser
Firefox 110.0.1 (64-bit)

### OS
Windows 10

**Comment by firasdib** [comment]
Thank you. The test was correct, but the message wasn't. I've fixed this and will push it live soon.
