### ISSUE TITLE
double apostrophes

### ISSUE THREAD

**Issue by patrick-haldi** [firasdib/Regex101#2013]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
replace text, not code, Task 21

### Bug Description
there are two instances of double apostrophes (in the don't):
`In an HTML page, replace the text micro with &micro;. Oh, and don''t screw up the code: don''t replace inside <the tags> or &entities;`
### Expected Outcome
`In an HTML page, replace the text micro with &micro;. Oh, and don't screw up the code: don't replace inside <the tags> or &entities;`

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by OnlineCop** [comment]
This is by design. Unless you replace instances globally, only the first match will be modified.

**Comment by OnlineCop** [comment]
Actually, I think I misread the problem. It looks like the *instructions* for the quizzes have double apostrophes; the quiz itself (and its solution) isn't the problem here.

**Comment by patrick-haldi** [comment]
Sorry if it was ambiguous. I'll try to be clearer next time. Cheers

**Comment by firasdib** [comment]
Thank you, I've fixed this locally. Will push it live soon.
