### ISSUE TITLE
Java: Update explanation when "Unicode matching" is enabled (or disabled)

### ISSUE THREAD

**Issue by Marcono1234** [firasdib/Regex101#2022]
## Feature

For Java, when the "Unicode matching" flag is enabled some of the character classes behave differently, see [`java.util.regex.Pattern` documentation](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html), table below the paragraph "The following Predefined Character classes...".

It might be useful if Regex101 could adjust the description of the character classes in the "Explanation" tab depending on whether "Unicode matching" is enabled (or disabled). For example, when "Unicode matching" is enabled `١` (U+0661) matches the pattern `\d`, but the "Explanation" claims "equivalent to [0-9]":
![Match screenshot](https://user-images.githubusercontent.com/11685886/226198199-ede4055d-02ab-4832-8b95-fbe09fe9347f.png)

Note that this affects more than just `\d`, see the table in the `Pattern` documentation mentioned above.

**Comment by working-name** [comment]
Relevant portion:

The following Predefined Character classes and POSIX character classes are in conformance with the recommendation of Annex C: Compatibility Properties of [Unicode Technical Standard #18: Unicode Regular Expressions](http://www.unicode.org/reports/tr18/), when [UNICODE_CHARACTER_CLASS](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html#UNICODE_CHARACTER_CLASS) flag is specified.

\d | A digit: \p{IsDigit}
-- | --

**Comment by Marcono1234** [comment]
> Relevant portion:
> ...

Though as mentioned, this affects more than just `\d`:
- `\d`: "... [0-9]"
- `\D`: "... [^0-9]"
- `\s`: "... [\r\n\t\f\v ]"
- `\S`: "... [^\r\n\t\f\v ]"
- `\w`: "... [a-zA-Z0-9_]"
- `\W`: "... [^a-zA-Z0-9_]"

This list might be incomplete, please verify this yourself as well.

**Comment by firasdib** [comment]
Thank you, I will fix this in the next major release.

**Comment by Marcono1234** [comment]
Thanks a lot!

Just to clarify, is it intended (maybe due to technical limitations) that the description for Unicode mode differs from the `Pattern` documentation?

| Class | `Pattern` | regex101 |
| - | - | - |
| `\d` | A digit: `\p{IsDigit}` | a digit zero through nine in any script except ideographic scripts (equivalent to `\p{Nd}`) |
| `\s` | A whitespace character: `\p{IsWhite_Space}` | any kind of invisible character (equivalent to `[\p{Z}\h\v]`) |
| ... | ... | ... |
