### ISSUE TITLE
wrong match in Java regex

### ISSUE THREAD

**Issue by panda-on** [firasdib/Regex101#2025]
### Bug Description

the following regex "(dt)?+.+" in Java should match any strings except "dt", but it turns out matched "dt" on the web page;

### Reproduction steps

use the preceding regex in Java, will get the result.

### Expected Outcome

If input "dt", "dts", "flower", the matched output string are "dts","flower"

### Browser

Include browser name and version

### OS
Edge 111.0.1661.51

**Comment by working-name** [comment]
https://regex101.com/r/LojuWO/1

https://onecompiler.com/java/3z3t3j5hs

**Comment by firasdib** [comment]
Works as expected
