### ISSUE TITLE
Wrong match in Javascript

### ISSUE THREAD

**Issue by virtuecoder** [firasdib/Regex101#2026]
## Bug Description
The is the regular expression:
`/(?<chapter>\d+)\s*:(?<verses>.*?(?:(?=\d+:)|(?=$)))/gi`
And the test string:
`'1:2-33; 333:4-55, 66:7-8'`

regex101.com does not match the third group, while node js matches all three groups:
<img width="1239" alt="Screenshot 2023-03-26 at 09 34 58" src="https://user-images.githubusercontent.com/1092912/227762203-21693f34-9e35-45d3-bd54-f1dffadf9e0b.png">

### Reproduction steps
This program works:
```
const input = '1:2-33; 333:4-55, 66:7-8';
const regex = /(?<chapter>\d+)\s*:(?<verses>.*?(?:(?=\d+:)|(?=$)))/gi;

let match;
while ((match = regex.exec(input))) {
  const { chapter, verses } = match.groups;
  console.log({ chapter, verses });
}
```

### Expected Outcome
Matching all three groups:
<pre>
{chapter: '1', verses: '2-33; '}
{chapter: '333', verses: '4-55, '}
{chapter: '66', verses: '7-8'}
</pre>

### Browser
Include browser name and version
Chromium Engine Version 111.0.5563.110

### OS
Include OS name and version
13.2.1 (22D68)

**Comment by working-name** [comment]
Hello!

The problem might be an extra newline at the end of your input. Since you're not utilizing `/m`, the `$` means end of input. Not accounting for a newline before the end of input should be the culprit.

**Comment by virtuecoder** [comment]
Sorry, Alan was right saying:

> The problem might be an extra newline at the end of your input. Since you're not utilizing /m, the $ means end of input. Not accounting for a newline before the end of input should be the culprit.

I need better glasses

**Comment by virtuecoder** [comment]
You're right, I closed the issue.
Thanks, regex101 is great! :-)
Jacek


niedz., 26 mar 2023 o 17:49 Alan ***@***.***> napisał(a):
