### ISSUE TITLE
Rust regex with literal quote (") not working

### ISSUE THREAD

**Issue by Ophirr33** [firasdib/Regex101#2033]
## Bug Description
The following regex works when running within a rust program ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2eb64c3c101597a72a0fc1fb10c08392)):
```
r#""hello""#
```

But it fails in the regex101 app with the following error:
```
pattern '"' may not be contained in raw strings {"start":{"offset":0,"line":1,"column":0},"end":{"offset":1,"line":2,"column":1}}
```

### Reproduction steps

1. Navigate to https://regex101.com/
2. Select Rust as the regex engine
3. Select the raw delimiter mode `#`
4. Paste in the regex `"hello"`

### Expected Outcome

No error is given and text such as `"hello" is an english greeting` reports a match.

### Browser

Firefox 111.0.1

### OS

Pop!_OS 22.04 LTS

**Comment by firasdib** [comment]
This will be resolved in the next release.
