### ISSUE TITLE
[Rust]Escaping "

### ISSUE THREAD

**Issue by ItalyToast** [firasdib/Regex101#2035]
## Bug Description
I cant use either " or \" to match with the rust flavor. " spits out an error:
" This token is either not supported by the selected flavor or by regex101
and \\" spits out:
\\" This token has no special meaning and has thus been rendered erroneous

It makes sense to not support a naked " but a escaped " should be supported.

### Reproduction steps
Regex input: \\"(\w*)\\"
Text input: name: "Hours_fmt",

### Expected Outcome
Expected a match of:
"Hours_fmt"

### Browser
Version 111.0.5563.65 (64-bit)

### OS
Windows 10 64-bit

**Comment by firasdib** [comment]
You will have to change delimiter in order to insert a literal quote in Rust.

**Comment by ItalyToast** [comment]
Never knew that was a thing, the more you know. 👍
