### ISSUE TITLE
Default text "insert your regular expression here" visible in both textboxes

### ISSUE THREAD

**Issue by eduarddejong** [firasdib/Regex101#2036]
## Bug Description
The default text "insert your regular expression here" is visible in both the actual regex input box as well as in the text area for the text strings to test with.

### Reproduction steps
Visit [regex101](https://regex101.com/) with new page with empty textboxes.

### Expected Outcome
To see a default text like "insert your **test string** here" in the second text area instead.

### Browser
Firefox version 111.0.1 (64-bits)

### OS
Arch Linux

**Comment by firasdib** [comment]
Whoops, thank you!
