### ISSUE TITLE
\B in character class should mean match character B

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#204]
`[^\B]` matches any character that is not capital B. However, the explanation of the regex is dangerously ambiguous and confusing:

    /[^\B]/g
        [^\B] match a single character not present in the list below
            \B assert position where \b doesn't match
        g modifier: global. All matches (don't return on first match)

The explanation should be:

    \B matches the character B literally (case sensitive)

https://regex101.com/r/rK4cT5/1

**Comment by firasdib** [comment]
Fixed.
