### ISSUE TITLE
Some issue with match functionality 

### ISSUE THREAD

**Issue by itsmebhaskar** [firasdib/Regex101#2042]
![C4205EA2-F24A-4DAB-A4A8-C903E090D4F8](https://user-images.githubusercontent.com/55789680/232727318-11153852-8f8f-4ddc-bc08-5de205130f86.png)
### Reproduction steps
Refer screenshot

### Expected Outcome
Should match

### Browser
Include browser name and version
Chrome 

### OS
Include OS name and version
Windows

**Comment by firasdib** [comment]
You have a trailing newline in your patternVänliga hälsningar / Best regards,Firas DibOn 18 Apr 2023, at 10:59, itsmebhaskar ***@***.***> wrote:﻿

Bug Description
Reproduction steps
Refer screenshot
Expected Outcome
Should match
Browser
Include browser name and version
Chrome
OS
Include OS name and version
Windows

**Comment by working-name** [comment]
@itsmebhaskar Please do reply here if this is still an issue. Closing for now.
