### ISSUE TITLE
"Compress" (align) tabs in extended mode (/x)

### ISSUE THREAD

**Issue by alhimiker** [firasdib/Regex101#2044]
## Feature
I have read #1283 and closed #1448, #2010
I apologize if this has already been discussed elsewhere.

This issue has been observed presumably since version 9.0.0 (3rd of April, 2023) at least when running the PCRE2 flavor.

I work in extended (/x) mode with comments at the end of almost all lines. Previously, using tabs, I could neatly place the start of a new comment on the current line exactly below the start of the previous comment (on the previous line). At the time it looked like this:
![1  Earlier](https://user-images.githubusercontent.com/63483735/232847149-7e9fae90-4b02-49ce-9b83-8ff05e08f9bb.png)

Now it looks like this:
![2  Now](https://user-images.githubusercontent.com/63483735/232847427-8a667e6f-e21e-4f2a-b0da-05a352a1fb2d.png)
Do you know about this feature? Is this done on purpose and will it stay that way, or is it a bug?

**Comment by firasdib** [comment]
Thank you, this is indeed a bug. I have fixed it locally, will be live soon.
