### ISSUE TITLE
Task 7 wrong solution not rejected 

### ISSUE THREAD

**Issue by Cyrillev91** [firasdib/Regex101#2048]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 7 VALIDATE AN IP

### Bug Description

A 42 characters solution is not rejected even though it accepts an invalid IP address:
```
100.100.2550.100
100.100.2559.100
        ^^^^

```

**Comment by firasdib** [comment]
Thank you, I have added more tests to cover these edge cases.

**Comment by liudongmiao** [comment]
@Cyrillev91 Could you tell me your best solution for this Task, 42 or more shorter? My best solution is still 43, and I cannot figure out any shorter solution.
