### ISSUE TITLE
Bug in Regular Expression Tooltip

### ISSUE THREAD

**Issue by UsamaButt1593** [firasdib/Regex101#2052]
## Bug Description
**The ToolTip appears on top of Regular Expression input element. Consequently, the text inside the input is not visible.**

### Reproduction steps
Move your cursor to the input element where one enters the regular expression

### Expected Outcome
The ToolTip should appears **above** or **below** Regular Expression input element. So, the text inside the input is visible.

### Browser
Google Chrome Version 112.0.5615.138

### OS
Windows 10 version 22H2

![The ToolTip hides the text in the box](https://user-images.githubusercontent.com/75769141/235393787-41aec8f7-40d0-4e78-823e-ff5dc1c36767.gif)

**Comment by firasdib** [comment]
I can't reproduce this on my end. Does the same problem happen in an incognito window?

**Comment by UsamaButt1593** [comment]
> I can't reproduce this on my end. Does the same problem happen in an incognito window?

I can't reproduce the issue also. Maybe, it was a one time thing. So, I'm gonna close this issue🙃
