### ISSUE TITLE
Old feature the best 

### ISSUE THREAD

**Issue by 9131135279** [firasdib/Regex101#2053]
## Feature
I don't like the new feature you have got. I am watching **code_with_harry** JavaScript video which is episode 99 (regular expression) and he tell me to go and learn regular expression At your website but what exactly he show us and what is in your website. i don't find any thing helpful please make a button where we change change your website like classic and the old type 
if you don't understand what i am saying go and see play.typeracer.com website where you can relate with my idea
thanks...…('_')

**Comment by working-name** [comment]
Hello! What do you mean exactly - there's a missing feature? Would you share some screenshots please?

**Comment by 9131135279** [comment]
I want this theme, but I can't seem to find it on your website. I looked
for the menu option and cheatsheet option, but still couldn't locate it.
Because of this, I am unable to practice my JavaScript code. If there is
anything you can do to assist me, it would be greatly appreciated. 🙇

**Comment by working-name** [comment]
Can you please include a screenshot of what you're referring to?

As far as the cheatsheet - if you mean the quick reference, that has not gone away, it's at the bottom on the right sidebar.
![image](https://user-images.githubusercontent.com/16505052/236042628-00dd7c6d-c545-4e66-b97b-b07b08adf21f.png)

**Comment by 9131135279** [comment]
Thankyou for your concern, This helped me a lot.🙂
