### ISSUE TITLE
Pattern error when escaping whitespace in .Net

### ISSUE THREAD

**Issue by AXRO-BentonCulp** [firasdib/Regex101#2054]
## Bug Description
Can't escape whitespace in .Net emulator without catching an immediate pattern error, exactly as title says.

### Reproduction steps
Open a new regex, set the flavour to .Net, and paste the following regex:
 @"(?mnsx-i)\ "
Mind the space at the end of the pattern.

### Expected Outcome
No pattern error (The pattern works in C#)

### Browser
Chrome, 112.0.5615.139

### OS
Windows 10, 19043.2364

**Comment by firasdib** [comment]
Thank you, will be fixed in the next release.
