### ISSUE TITLE
Request: Option to not display Octal/Base-8 char codes in hover tooltips and Explanation help.

### ISSUE THREAD

**Issue by ZStoner** [firasdib/Regex101#2055]
## Feature Request

💡 <ins>**Settings Option**</ins>: Add an option to not display the Octal/Base-8 char codes via the Settings options.

**_Example of Current Display_**:
| _Explanation Text_ |
| :-- |
|  `/ (\!\[)(?<ArrayList>.+?)(\]) / gi`  |
|  **1st Capturing Group** `(\!\[)`  |
|  `\!` matches the character `!` with index **33**<sub>10</sub> (**21**<sub>16</sub><ins> or **41**<sub>8</sub></ins>) literally (case insensitive)  |
|  `\[` matches the character `[` with index **91**<sub>10</sub> (**5B**<sub>16</sub><ins> or **133**<sub>8</sub></ins>) literally (case insensitive)  |

> **Note**: The "Octal/Base-8" parts I <ins>**underlined**</ins> to highlight the parts I'm referring to.
<BR/>

_Other Notes_:
*  I know Octal format is supported in RegEx, but I have no idea how many folks out there are still _actively using it_.  😃 
*  Having an option to remove the extra "Base-8" variants from display could make things more readable and less cluttered for those that never intend to use it.
*  Of course, those that would prefer keeping Octal is fine, and displaying it would be the default.

--------

**_Example if the Feature was implemented_**:
|  | _Explanation Text_ |
|--|:--|
| _Before_ |  `\!` matches the character `!` with index **33**<sub>10</sub> (**21**<sub>16</sub> or **41**<sub>8</sub>) literally (case insensitive)  |
| _After_  |  `\!` matches the character `!` with index **33**<sub>10</sub> (**21**<sub>16</sub>) literally (case insensitive)  |

<BR/>

Thanks,
----Z.

**Comment by firasdib** [comment]
I could implement a select option in the settings where you can pick:

- Octal + Hex
- Octal only
- Hex only
- None

Would that be good?

**Comment by firasdib** [comment]
This has been added, check the settings menu.
