### ISSUE TITLE
Which flavour to use for C POSIX.2 regexes?

### ISSUE THREAD

**Issue by halloleo** [firasdib/Regex101#2056]
## Question

I use regex101.com a lot to test out more complicated regexes. It is wonderful! Thanks.

At the moment I need to develop a regex for use with Haskell's [Text.Regex.Posix](https://hackage.haskell.org/package/regex-posix-0.96.0.1/docs/Text-Regex-Posix.html). They implement the [C POSIX.2 regex API](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/regex.h.html). 

Which regex flavour on regex101.com reflects this type of regexes?

Many thanks for pointers!

**Comment by UrsineRaven** [comment]
I don't think they have one yet (ref. #165)

**Comment by firasdib** [comment]
Let's follow this in #165
