### ISSUE TITLE
Golang engine fails to start

### ISSUE THREAD

**Issue by jxsl13** [firasdib/Regex101#2057]
## Question

Hi,
I'm currently using the website and the Golang regex engine does not seem to start.

**Comment by working-name** [comment]
Hi @jxsl13 I tried to reproduce is but on my macOS computer I cannot in 3 browsers. Are you able to reproduce it in an incognito window or another browser as well?

**Comment by jxsl13** [comment]
I'm on an old macOS, Safari 14.1.2.
Opening regex101.com
Clicking o Golang
Pasting this regex
```
((?:0[1-46-9]\d{3})|(?:[1-357-9]\d{4})|(?:[4][0-24-9]\d{3})|(?:[6][013-9]\d{3}))
```

**Comment by jxsl13** [comment]
<img width="1463" alt="Bildschirmfoto 2023-05-07 um 00 02 33" src="https://user-images.githubusercontent.com/371944/236648224-3c35b933-03a2-47a9-8a39-db9bf8fa3667.png">

**Comment by jxsl13** [comment]
seemingly only a Safari issue (maybe even only my version)

**Comment by jxsl13** [comment]
Updated Safari to 16.4.1 and it is working.

**Comment by jxsl13** [comment]
references are not enabled whatever that means.

**Comment by working-name** [comment]
That is probably the browser trying to say it does not support webassembly or a feature thereof. That's how the golang engine runs in your browser, in javascript.
