### ISSUE TITLE
Save current regex when exiting the website, restore when you come back

### ISSUE THREAD

**Issue by Jakobud** [firasdib/Regex101#206]
Make the site so that when you leave the page or close the browser it saves your work (regex, examples, substitutions, etc) and when you come back to the page later, it will automatically local up the last thing you had in there.

This would actually be really, really easy with localStorage and a window.onbeforeunload event handler. When In that page, simply save everything to localStorage. Then restore them when you come back to regex101.com later.

**Comment by nhahtdh** [comment]
I imagine it would be problematic when you have more than 1 tab of regex101 on. And I'm not sure, but I think it may cause problem when you close more than 2 tabs of regex101 and restore both of them from recently closed tab.

**Comment by Jakobud** [comment]
Oh yeah that would be an issue, unless you had a way to easily distinguish between the regex's before saving...

**Comment by firasdib** [comment]
Feels like this would introduce more problems than it would solve. Perhaps it would be wiser to popup and ask if you are sure you want to exit with an unsaved regex?

**Comment by Jakobud** [comment]
Yeah that would be a good alternative. For example, StackOverflow does stuff similar to this if you get on there and start filling out a question and then leave before finishing. It will ask you if you are sure you want to leave and it will also save your question so the next time you go back and ask a question, its already filled out with what you left.

It works for that site though because people probably aren't filling out multiple questions at once, where on regex101 people could easily have multiple windows open at once for a variety of tests.

**Comment by firasdib** [comment]
I added a little popup to notify you of unsaved changes.
