### ISSUE TITLE
Broken handling of Unicode surrogate pairs on regex character hover

### ISSUE THREAD

**Issue by jhmaster2000** [firasdib/Regex101#2061]
## Bug Description
On all Regex flavors except Rust and Golang, inserting a character (the actual character itself, *not* an escape sequence for it) in the Regex Editor regex field which has a Unicode codepoint higher than `U+FFFF`, in other words within the highest range of Unicode `\u10000-\u10FFFF`, will cause the character to display normally but when hovered over it will be broken apart into its two surrogates.

The character itself will be the first surrogate, and if you very carefully nearly pixel-perfectly align your cursor to the very right edge of the character, you can hover over its second surrogate.

### Reproduction steps
1. On Regex Editor, select any Regex flavor that is NOT Rust or Golang, flags don't matter.
2. In the regex field, paste the following character: `𐌐` (codepoint `U+10310`)
3. Hover over the character, notice how the character displayed in the explainer is the surrogate `U+D800`
4. (bonus) Try hovering over the very right edge of the character, see if you can get the hover for the second surrogate `U+DF10`

### Expected Outcome
Still with the character on the regex field, switch the Regex flavor to Rust or Golang, then hover over it. It will work as expected, which should be the behavior on all Regex flavors.

### Browser
Chrome 113.0.5672.93 (Official Build) (64-bit)

### OS
Windows 10 Pro Build 19045

**Comment by firasdib** [comment]
Can you save a permalink where I can reproduce this?

**Comment by firasdib** [comment]
I've looked into it, and it's by design. In the flavors (like PCRE) which don't natively match using Unicode, the regex is actually matching the code points individually: 
![image](https://github.com/firasdib/Regex101/assets/1335165/3d2835ee-8753-4e12-86ad-7ca8d11e38ce)

It would be better if codemirror could render them out like in the screenshot, but it's not always possible. If you enable unicode in PCRE, you get the same behavior.

**Comment by jhmaster2000** [comment]
@firasdib Ah I see, I understand that it's how the regexes are working under the hood, but it still isn't intuitive to hover over the second surrogate of the character when the character itself is rendered as one, it is literally a 1-pixel wide hitbox to get the hover for the 2nd surrogate.

What if instead you made it display both surrogates for hovering the multi-surrogate character? i.e. hovering over the example character used `𐌐` in a non-Unicode regex flavor could show a unified hover like this:

> **Text -** matches literally (case-sensitive) the character pair: � with index 55296₁₀ (D800₁₆ or 15400₈) followed by � with index 57104₁₀ (DF10₁₆ or 157420₈)

This way the regex decomposition of the displayed Unicode characters is easily viewable and also prevents potentially misleading users unaware of Unicode semantics into thinking their Unicode characters equal to only the first surrogate they see on the current hover.

**Comment by java08800** [comment]
> @firasdib Ah I see, I understand that it's how the regexes are working under the hood, but it still isn't intuitive to hover over the second surrogate of the character when the character itself is rendered as one, it is literally a 1-pixel wide hitbox to get the hover for the 2nd surrogate.
> 
> What if instead you made it display both surrogates for hovering the multi-surrogate character? i.e. hovering over the example character used `𐌐` in a non-Unicode regex flavor could show a unified hover like this:
> 
> > **Text -** matches literally (case-sensitive) the character pair: � with index 55296₁₀ (D800₁₆ or 15400₈) followed by � with index 57104₁₀ (DF10₁₆ or 157420₈)
> 
> This way the regex decomposition of the displayed Unicode characters is easily viewable and also prevents potentially misleading users unaware of Unicode semantics into thinking their Unicode characters equal to only the first surrogate they see on the current hover.
