### ISSUE TITLE
literal " can't be inserted in .NET 

### ISSUE THREAD

**Issue by qlikTERror** [firasdib/Regex101#2063]
## Bug Description

Trying to write this regex \"\d in .NET flavor but the site complains that **\" This token has no special meaning and has thus been rendered erroneous**

### Expected Outcome

It should be possible to insert a **"** escaping it with **\**

### Browser

Chrome latest

### OS
Windows 11 latest

**Comment by firasdib** [comment]
You need to escape using `""`
