### ISSUE TITLE
Question 2

### ISSUE THREAD

**Issue by jasiukiewicztymon** [firasdib/Regex101#2064]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task

2: I CAPITALIZING

### Bug Description

I don't understand why the website says that:

![image](https://github.com/firasdib/Regex101/assets/73474137/f4ad09c2-785c-4fd4-a23a-6cbd0bddfad6)

And in my regex test file it works

### Reproduction steps

https://regex101.com/r/8rApRh/1

### Expected Outcome
If there are any test cases you think need to be added, you can write that here as well.

### Browser

Chromium 113

### OS

Windows 11

**Comment by firasdib** [comment]
Your best bet would be to ask on IRC for help on this matter
