### ISSUE TITLE
Double escapes

### ISSUE THREAD

**Issue by James-Bennett-295** [firasdib/Regex101#2067]
## Feature
When regular expressions are stored in a config file, they will sometimes need to be double-escaped.

Example: `\\d+` to match a string of digits.

My suggestion is that a toggle is added for double escapes, so that when enabled, the example above would act like `\d+`.

**Comment by firasdib** [comment]
The website always works in raw string mode for all flavors to avoid this problem. If you want to get a pre-formatted string with double escapes, please consult the code generator instead.
