### ISSUE TITLE
-> causes critical error for Rust

### ISSUE THREAD

**Issue by vallentin** [firasdib/Regex101#2068]
Added the `->` as the regular expression, then switched flavor from PCRE to Rust, and it resulted in "A critical error has occurred".

**Browser:** Firefox 112.0.2 (64-bit)
**OS:** Windows 10

Console:

![image](https://github.com/firasdib/Regex101/assets/17464404/5bf481b3-3b19-485f-b694-901d7a377010)

Copy paste:

```console
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&family=Source+Code+Pro:wght@400;500;700&display=swap [css2](https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&family=Source+Code+Pro:wght@400;500;700&display=swap)
App initialized - version 9.0.7 [bundle.53c0999bedc658419743.js:1:399361](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Loaded initial state [bundle.53c0999bedc658419743.js:1:399509](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Store configured [bundle.53c0999bedc658419743.js:1:400205](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Loading failed for the <script> with source “https://analytics.regex101.com/js/plausible.js”. [regex101.com:79:1](https://regex101.com/)
Successfully registered service worker [bundle.53c0999bedc658419743.js:1:162746](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://srv.buysellads.com/ads/CESIEKJM.json?callback=jsonp_1684667283688_61987 [vendors-bundle.8bab2cf8488f35e78d0f.js:2:47365](https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js)
Loading failed for the <script> with source “https://srv.buysellads.com/ads/CESIEKJM.json?callback=jsonp_1684667283688_61987”. [regex101.com:1:1](https://regex101.com/)
Unable to load sponsor data Error: JSONP request to https://srv.buysellads.com/ads/CESIEKJM.json failed
    onerror https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
[bundle.53c0999bedc658419743.js:1:163591](https://regex101.com/static/bundle.53c0999bedc658419743.js)
make reader 2 [vendors-sentry.8297ed8fd1b6cf998129.chunk.js:1:261864](https://regex101.com/static/vendors-sentry.8297ed8fd1b6cf998129.chunk.js)
TypeError: d is null
    d https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    a https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    r https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    _t https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    A https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    $a https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    Cs https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Oa https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Ca https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Cl https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    wu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    yu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    vu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    su https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    uu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Fi https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    iu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
```

**Comment by firasdib** [comment]
Thanks, will push a fix asap

**Comment by Moonligth1995** [comment]
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&family=Source+Code+Pro:wght@400;500;700&display=swap [css2](https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&family=Source+Code+Pro:wght@400;500;700&display=swap)
App initialized - version 9.0.7 [bundle.53c0999bedc658419743.js:1:399361](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Loaded initial state [bundle.53c0999bedc658419743.js:1:399509](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Store configured [bundle.53c0999bedc658419743.js:1:400205](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Loading failed for the <script> with source “https://analytics.regex101.com/js/plausible.js”. [regex101.com:79:1](https://regex101.com/)
Successfully registered service worker [bundle.53c0999bedc658419743.js:1:162746](https://regex101.com/static/bundle.53c0999bedc658419743.js)
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://srv.buysellads.com/ads/CESIEKJM.json?callback=jsonp_1684667283688_61987 [vendors-bundle.8bab2cf8488f35e78d0f.js:2:47365](https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js)
Loading failed for the <script> with source “https://srv.buysellads.com/ads/CESIEKJM.json?callback=jsonp_1684667283688_61987”. [regex101.com:1:1](https://regex101.com/)
Unable to load sponsor data Error: JSONP request to https://srv.buysellads.com/ads/CESIEKJM.json failed
    onerror https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
[bundle.53c0999bedc658419743.js:1:163591](https://regex101.com/static/bundle.53c0999bedc658419743.js)
make reader 2 [vendors-sentry.8297ed8fd1b6cf998129.chunk.js:1:261864](https://regex101.com/static/vendors-sentry.8297ed8fd1b6cf998129.chunk.js)
TypeError: d is null
    d https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    a https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    r https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    _t https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    A https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    $a https://regex101.com/static/bundle.53c0999bedc658419743.js:1
    Cs https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Oa https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Ca https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Cl https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    wu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    yu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    vu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    su https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    uu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    Fi https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
    iu https://regex101.com/static/vendors-bundle.8bab2cf8488f35e78d0f.js:2
