### ISSUE TITLE
Task 18 unintended solution?

### ISSUE THREAD

**Issue by Michiocre** [firasdib/Regex101#2069]
## Question

I just solved task 18 and the result tells me I should have used `\G`.
Is solving it without an intended way to solve this task?

Regex: `redacted`
Substitution: `redacted`

**Comment by firasdib** [comment]
I've redacted your inputs. There is no requirement to use `\G`, but please, feel free to discuss this on IRC with everyone else and find out if there is a bug. if there is, I can fix it then.
