### ISSUE TITLE
javascript code not working

### ISSUE THREAD

**Issue by wayann** [firasdib/Regex101#207]
https://www.regex101.com/r/pT4xI1/1
I tried the javascript code in the chrome console and m[0] gives Uncaught TypeError: Cannot read property '1' of null
is this related to https://github.com/firasdib/Regex101/issues/56 
or am I missing something?

**Comment by paninRAFAELIT** [comment]
Remover  Arduino Pithon  que lee pensamientos  eliminar  tipo de programa proyecto o apps con datos  que rrevela códigos .
