### ISSUE TITLE
PCRE2: substitution given the expression "$\K" works when it shouldn't.

### ISSUE THREAD

**Issue by PS1Online** [firasdib/Regex101#2073]
Using perl this works in the substitution:

`perl -0777spe 's/\A.*?^text1.*?\K$/ text8/gms' -- file.txt`

and this not:

`perl -0777spe 's/\A.*?^text1.*?$\K/ text8/gms' -- file.txt`

On the other hand, both ways work on the site, when it shouldn't be like this:

https://regex101.com/r/XFMo1F/1

**Comment by firasdib** [comment]
Perl is not PCRE. From my tests, this looks to be the intended behavior in PCRE. If you believe it to be a bug with the library, I suggest you open an issue in the official PCRE repository so it can be fixed there.
