### ISSUE TITLE
trim tag space

### ISSUE THREAD

**Issue by tonybala** [firasdib/Regex101#2075]
## trim tag space
View returns different

### Reproduction steps
#error 
![image](https://github.com/firasdib/Regex101/assets/25241647/83e0c197-6bd0-438f-b83d-8b7078d7fec8)
#ok 
![image](https://github.com/firasdib/Regex101/assets/25241647/a1ecf36c-d7fd-4fb6-ab55-930baf6c1324)

### Browser
chrome

### OS
windows

**Comment by working-name** [comment]
Please feel free to reply here if this is still a problem. Will reopen the issue.
