### ISSUE TITLE
Where is the debugger?

### ISSUE THREAD

**Issue by Adrian-Hawryluk** [firasdib/Regex101#2078]
I know that there used to be a debugger button here.  Going to Google and typing in `site:regex101.com debugger` does get me to a debugger screen, but for the life of me, I can't find a debugger link on the page!

Can it be made more prominent please?

Thx.

**Comment by working-name** [comment]
Hello @Adrian-Hawryluk 

The debugger link is only going to be active on the left hand sidebar if you have PCRE selected. The other engines do not provide a debugging feature.

<img width="295" alt="image" src="https://github.com/firasdib/Regex101/assets/16505052/0e4e90ed-ac25-4245-8659-a9cb50a8d796">

**Comment by firasdib** [comment]
@Adrian-Hawryluk Great point, I will add a tooltip.

**Comment by tomhundt** [comment]
OMG.  This has been driving me nuts!!  I've been working on Python, mostly, so this makes me sad.
