### ISSUE TITLE
Resizer defaults to collapsed when the website is first loaded

### ISSUE THREAD

**Issue by kananga** [firasdib/Regex101#208]
I'm referring to the container at the right side of the site, which contains the Explanation, Match information, and Quick reference expanders. If this was my first time to the site I wouldn't have known those tools existed.

In case it's relevant, my monitor resolution is 1080 x 1920, font size is default, and the monitor is oriented vertically (1920 high, 1080 wide).

**Comment by firasdib** [comment]
Hmm, it does not do that for me. Which browser and OS are you using? Can you reproduce this?

**Comment by firasdib** [comment]
Can not reproduce.
