### ISSUE TITLE
Valid Java 8 regex is not accepted

### ISSUE THREAD

**Issue by karl-riley** [firasdib/Regex101#2080]
## Bug Description
When providing a valid Java 8 regex for email validation and selecting 'Java 8', regex101.com rejects it with the following error message printed twice:
"- You cannot create character ranges with the terminating character class token"

### Reproduction steps
Select 'Java 8' on left-hand menu
Enter this regex: ^[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$
Enter this test string:  username@domain.co.in

Regex matches test string with actual Java code, and can also be validated here https://www.freeformatter.com/java-regex-tester.html

### Expected Outcome
Matched

### Browser
Chrome on Windows 11, 114.0.5735.110 (Official Build) (64-bit)

### OS
Windows 11

**Comment by working-name** [comment]
Hello @karl-riley 

Could you please share a regex101.com link? I cannot seem to reproduce the problem.

**Comment by karl-riley** [comment]
https://regex101.com/r/IQvDN9/1

Also a screenshot:
[image: image.png]

**Comment by firasdib** [comment]
I can see there is a clear case to handle this in the code, but I don't know why. I'll have to investigate this a little bit further.

**Comment by firasdib** [comment]
I'll have this resolved in the next release.
