### ISSUE TITLE
Set RegEx flavor using URL query string/parameter

### ISSUE THREAD

**Issue by wdzajicek** [firasdib/Regex101#2090]
## Feature

It would be wonderful if the RegEx flavor could be specified in the URL using a query string.

For example, going to the URL `https://regex101.com/?flavor=ecmascript` would load regex101 with the "ECMAScript (javascript)" flavor already chosen and ready to go.

**Comment by firasdib** [comment]
See this: https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url

**Comment by wdzajicek** [comment]
> See this: https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url

There's no option for what my original request was — **to specify the flavor of RegEx**.

**Comment by aesy** [comment]
The link doesn't mention flavor at all. This used to work, why was it removed?

Edit: Actually, it does work, there just seem to be some overly aggressive caching going on.
