### ISSUE TITLE
Are there any specific reasons for why Regex101 hasn't been open sourced?

### ISSUE THREAD

**Issue by YousufSSyed** [firasdib/Regex101#2091]
## Question
I know this question has been asked a lot, and the author would open source it if they feel like doing so. While I have looked at the various issues where the author doesn't want it open sourced, I'm wondering if there are any reasons in particular for why they wouldn't want to do so.

I saw the site was down on the 25th and had trouble finding alternative websites, that's why it would be nice to self-host it.

**Comment by KaKi87** [comment]
Considering what also happened today, I've been wondering too.
@firasdib Would you please answer this ?
Thanks

**Comment by firasdib** [comment]
The reason right now is because I don’t want to, I will elaborate more in the future. 

i will investigate todays outage and do my best to prevent it in the future.
