### ISSUE TITLE
Missing LICENSE.txt

### ISSUE THREAD

**Issue by pl4nty** [firasdib/Regex101#2092]
## Bug Description
Some JavaScript files loaded by the frontend have the following statement, but return a 404 when accessing the txt file.
`/*! For license information please see <filename>.LICENSE.txt */`

### Reproduction steps
1. Visit https://regex101.com/static/vendors-bundle.bb3c5ea5fa667a8da99d.js
2. Note license at vendors-bundle.bb3c5ea5fa667a8da99d.js.LICENSE.txt
3. Visit https://regex101.com/static/vendors-bundle.bb3c5ea5fa667a8da99d.js.LICENSE.txt
4. See 404 Not Found from nginx.

This file has a similar issue: https://regex101.com/static/dotnet.worker.06bac0030b38b6787d42.js

### Expected Outcome
A LICENSE.txt file should be returned. Some licenses may require the LICENSE.txt to be available as a condition of using the licensed code.

### Browser
Firefox 114.0.1

### OS
Windows 11 22H2 23481.1000

**Comment by firasdib** [comment]
Thank you, fixed.
