### ISSUE TITLE
A critical error has occurred while writing pattern in Regular Expression text box

### ISSUE THREAD

**Issue by zack-aman** [firasdib/Regex101#2098]
## Bug Description
Writing pattern `^.*\Qaman@gmail.com\E.*$` in Regular Expression text box resulted in white screen with message `A critical error has occurred`

### Reproduction steps
Write `^.*\Qaman@gmail.com\E.*$` in Regular Expression text box

### Expected Outcome
Process pattern successfully

### Browser
Include browser name and version
Safari Version 16.4

### OS
Include OS name and version
macOS ventura 13.3.1

**Comment by Yaronkr** [comment]
Seems like this error is for any pattern
