### ISSUE TITLE
Whitespace character (\s) working in js where it should be \\s

### ISSUE THREAD

**Issue by AustinHeard** [firasdib/Regex101#2099]
## Bug Description

A whitespace character (\s) working in js where it should be \\s

### Reproduction steps

![image](https://github.com/firasdib/Regex101/assets/70654710/60ca437e-f9d3-479e-ba48-6b589f01af28)

When I use this expression in a js file it does not match but when I add the second \ it works

![image](https://github.com/firasdib/Regex101/assets/70654710/de8942d4-8222-4aeb-a6c4-e1f1a2dc7913)

### Expected Outcome

no matches

### Browser

Chrome 114

### OS

Pop!_OS 22.04 LTS

**Comment by working-name** [comment]
Hey @AustinHeard 

This has to do with javascript's string processing. By the time `\s` gets to regex, it's just `s` because the `\` before `s` escapes the character `s` itself. That's why when you add a second `\` regex finally gets `\\`

Try it out:

```js
'USBsCamera'.match(new RegExp('(?:USB\sCamera)'));
```

**Comment by AustinHeard** [comment]
Thanks for the reply! 

I was just wondering if the expression field should require both / s if JavaScript is selected, or maybe when you copy it is copies with 2?

**Comment by working-name** [comment]
The site's regex input field **is just regex**, not a javascript string - and this applies across the board. There's no string processing in the style of the regex engine selected.

But you can get a properly escaped version of it to plop into JS if you click code generator in the left sidebar.

**Comment by AustinHeard** [comment]
Oh I didn't know that button was there. Thank you!
