### ISSUE TITLE
Is there a way to report a saved regex as incorrect or wrong?

### ISSUE THREAD

**Issue by benlk** [firasdib/Regex101#2102]
## Question

Is there a way to report an issue with a saved regex on regex101 that is getting listed in search results?

Reasons someone may want to report a saved regex include:

- non-regex content saved in the file (e.g., warez links; use as a pastebin)
- the given regex does not comply with the specified use case's standards
- the given regex is dangerously incorrect

### Example: 

Searching for "email validator regex" on DuckDuckGo, I received a link to https://regex101.com/r/lHs2R3/1 (https://regex101.com/library/lHs2R3)

The problem is that this regex is factually incorrect. It doesn't accept all valid email addresses, including emails with a `+` character in the local part. The 99% correct validation regex is at https://emailregex.com/ — but it's not actually possible to match 100% of valid email addresses; see https://www.regular-expressions.info/email.html

**Comment by firasdib** [comment]
No, the library is maintained by the community. Voting it up or down is the only thing you can do.

**Comment by benlk** [comment]
The library reputation of a saved regex is not visible in the per-regex screen https://regex101.com/r/lHs2R3/1 , so there's no benefit to doing that.
