### ISSUE TITLE
Missing " in C# code generator

### ISSUE THREAD

**Issue by NCC1701M** [firasdib/Regex101#2104]
## Bug Description
The code generator for C# removes " in the substitution string.

### Reproduction steps
Lets say I have a file, containing text like this:
```
version: 3
version: 4
version: "5"
```

and I want to change the version representation to a uniform representation like

```
version: "3"
version: "4"
version: "5"
```

So I write this regex:
```regex
^version:\s*(?<version>\d+(?:\.\d+)*)$
```

and the following substitution:

```
version: "${version}"
```

When I test this in the Regex101 environment I get the expected results. But when I export it to C# code using the code generator, I get this code:

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
    public static void Main()
    {
        string pattern = @"^version:\s*(?<version>\d+(?:\.\d+)*)$";
        string substitution = @"version: ${version}";
        string input = @"version: 3
version: 4
version: 5";
        RegexOptions options = RegexOptions.Multiline;
        
        Regex regex = new Regex(pattern, options);
        string result = regex.Replace(input, substitution);
    }
}
```
As you can see in the line where the variable `substitution` is declared, the string does not contain ", which causes the regex substitution to be incorrect.

### Expected Outcome
The substitution variable should either be `string substitution = @"version: ""${version}""";` or `string substitution = "version: \"${version}\"";`.

**Complete code**

```csharp
using System;
using System.Text.RegularExpressions;

public class Example
{
    public static void Main()
    {
        string pattern = @"^version:\s*(?<version>\d+(?:\.\d+)*)$";
        string substitution = @"version: ""${version}""";
        string input = @"version: 3
version: 4
version: 5";
        RegexOptions options = RegexOptions.Multiline;
        
        Regex regex = new Regex(pattern, options);
        string result = regex.Replace(input, substitution);
    }
}
```

### Browser
Browser | Version
---------|---------
Firefox: |114.0.2
Chrome | 114.0.5735.199
Edge | 114.0.1823.67

### OS
Windows 11 22H2

**Comment by firasdib** [comment]
Thank you for the detailed report. Oversight on my part, adjusted locally, and will be pushed soon.
