### ISSUE TITLE
Regex Library: Add flag-for-removal icon

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#2106]
## Feature

When viewing the [Library](https://regex101.com/library), there is an "Add to favorites" icon on the right side of each entry.

I propose a "Flag for removal" icon.

## UX

The "Add to favorites" and "Flag for removal" would be mutually-exclusive.
- If the user had favorited an entry, it makes little sense to me why they would then want it removed permanently from the library.

## Side Notes

1. There is no guarantee that a heavily-flagged entry will ever get removed; it's up to the site owner and/or any designated moderators to choose how/when items get removed from the library.
2. Similar to #2105, a filter for "Show/hide flagged entries" might be useful for quick/mass removal for moderators.
3. I don't know that it would be useful to see how *many* flags any entry has received (maybe a moderator could see this, or have it accessible only via the API); its downvote count would probably be sufficient to make a decision.

**Comment by firasdib** [comment]
I have added a new moderator user group for the regex library, these people will be able to delete entries.
