### ISSUE TITLE
Minor typo in the "explanation" when evaulating [\/]

### ISSUE THREAD

**Issue by aruametello** [firasdib/Regex101#2107]
## Bug Description
when using something like this [abc\\/]

in the explanation it currently says about the '/' in the list:
\\/ matches the character \\/ with index 4710 (2F16 or 578) literally

fairly sure it should be 
\\/ matches the character / with index 4710 (2F16 or 578) literally

relevant: it is currently correct for '\\\\'

### Reproduction steps

some regular expression like:
.*[\\\\\/]rios.*

### Expected Outcome

(in the explanation box)
\\/ matches the character / with index 4710 (2F16 or 578) literally
(and probably within the "Match a single character present in the list below" tree list)

### Browser
Include browser name and version

Firefox 114.0.2

### OS
Include OS name and version

Windows 10 x64 21H2 build 19044

**Comment by firasdib** [comment]
Thank you, I'll have this fixed in the next release.
