### ISSUE TITLE
regex101.com is down

### ISSUE THREAD

**Issue by KaKi87** [firasdib/Regex101#2108]
## Bug Description
regex101.com is down

### Reproduction steps
Visit regex101.com

### Expected Outcome
regex101.com is up

### Browser
Brave 1.52.129 (irrelevant here though)

### OS
Ubuntu Unity 23.04 (irrelevant here though)

**Comment by darnfish** [comment]
+1

**Comment by akhilerm** [comment]
+1

**Comment by KaKi87** [comment]
Thanks for confirming but please consider reacting with :+1: instead of commenting.

**Comment by firasdib** [comment]
The site is back up. I'm not sure what caused the downtime as of right now, but I will investigate. Thank you.
