### ISSUE TITLE
Negative Lookbehind broken?

### ISSUE THREAD

**Issue by webhamster** [firasdib/Regex101#211]
The following regex: (?<!Bart )Simpson
should, in the following text:
"""Homer Simpson, Bart Simpson, Marge Simpson""" as well as in the following text:
"""Ned⋅Flanders
Bart⋅Simpson
Mr.⋅Burns
Marge⋅Simpson
Homer⋅Simpson"""
match the "Simpson" after Marge and Homer. Instead, it maches the first "Simpson", which is opposite to the expected behavior. Tested in Python:

>>> import re
>>> re.sub(r"(?<!Bart )Simpson", "test", "Homer Simpson, Bart Simpson, Marge Simpson")
'Homer test, Bart Simpson, Marge test'
>>> re.sub(r"(?<!Bart )Simpson", "test", "Homer Simpson\nBart Simpson\nMarge Simpson")
'Homer test\nBart Simpson\nMarge test'

**Comment by firasdib** [comment]
Seems to work for me? https://regex101.com/r/yR5cB1/1

**Comment by webhamster** [comment]
Indeed. Apparently I had some exotic unicode character in either the regex or the text. I'll close this bug.
