### ISSUE TITLE
regex101.com is down

### ISSUE THREAD

**Issue by KaKi87** [firasdib/Regex101#2112]

**Comment by firasdib** [comment]
Working on it, deploy that went slightly bonkers. Feel free to join [Discord](https://discord.gg/wUA6F6YqSs) to get live updates :).

**Comment by KaKi87** [comment]
How about a public status page, i.e. that doesn't require login ?

Since you like GitHub, I can recommend a FLOSS one based on GitHub's CI : https://github.com/upptime/upptime

**Comment by firasdib** [comment]
Thank you, that's a great suggestion!
