### ISSUE TITLE
match does not capture text

### ISSUE THREAD

**Issue by fabiocs8** [firasdib/Regex101#2115]
## Bug Description
The engine does not capture the following regex whemn applied to specific text

### Reproduction steps
rewgex: 
\bC[OM\/]{0,3} ?(\d+) ?(\%|\,|M?G?|L)

Text: 
AMONIO PA 28-30% - FRASCO COM 1L.

### Expected Outcome
COM 1L

### Browser
Include browser name and version
chrome Version 115.0.5790.102 (Official Build) (64-bit)
### OS
Include OS name and version
Edição	Windows 10 Home Single Language
Versão	22H2
Instalado em	‎27/‎08/‎2020
Compilação do SO	19045.3208
Número de série	PE02U1N8
Experiência	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by firasdib** [comment]
Seems to work for me. What is the problem exactly?On 25 Jul 2023, at 22:49, FABIO CORREA DA SILVA ***@***.***> wrote:﻿
Bug Description
The engine does not capture the following regex whemn applied to specific text
Reproduction steps
rewgex:
\bC[OM/]{0,3} ?(\d+) ?(%|,|M?G?|L)
Text:
AMONIO PA 28-30% - FRASCO COM 1L.
Expected Outcome
COM 1L
Browser
Include browser name and version
chrome Version 115.0.5790.102 (Official Build) (64-bit)
OS
Include OS name and version
Edição	Windows 10 Home Single Language
Versão	22H2
Instalado em	‎27/‎08/‎2020
Compilação do SO	19045.3208
Número de série	PE02U1N8
Experiência	Windows Feature Experience Pack 1000.19041.1000.0
