### ISSUE TITLE
Code Generator: sed should not append ;d

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#2116]
## Bug Description
The Code Generator for SED appends `;d` which is deleting non-matching lines.
Without the `;d` at the end, non-matching lines are preserved.

### Reproduction steps
Example code, where substitution is empty to simply remove the text at the end of the lines: https://regex101.com/r/HNAF9L/1
Code Generator with SED selected: https://regex101.com/r/HNAF9L/1/codegen?language=SED

Current output:
```bash
$ sed -E 's/-[0-9][0-9]*(\.[0-9][0-9-]*|\.[a-z0-9][a-z0-9]*)*//gm;t;d' <<< "no-match
keep-only-this-text-1.1.2-7.el7.noarch
no-match-1.4.8-3.el7_4.1.i686
keep-this-text-1.4.8-3.el7.1.x86_64
match-1.4.8-3.el7_2.1.x86_64
no-match-svn.x86_64
"

keep-only-this-text
no-match_4.1.i686
keep-this-text_64
match_2.1.x86_64
```

### Expected Outcome
The Code Generator should produce output which does not remove non-matching lines, or at least adds a note on how the end user can include/omit that `;d` to display/suppress those lines as needed:

```bash
$ sed -E 's/-[0-9][0-9]*(\.[0-9][0-9-]*|\.[a-z0-9][a-z0-9]*)*//gm;t' <<< "no-match
keep-only-this-text-1.1.2-7.el7.noarch
no-match-1.4.8-3.el7_4.1.i686
keep-this-text-1.4.8-3.el7.1.x86_64
match-1.4.8-3.el7_2.1.x86_64
no-match-svn.x86_64
"

no-match
keep-only-this-text
no-match_4.1.i686
keep-this-text_64
match_2.1.x86_64
no-match-svn.x86_64
```

**Comment by firasdib** [comment]
So `;d` should only be used in list-mode?

**Comment by OnlineCop** [comment]
Possibly, but list-mode doesn't allow Code Generator to be selected.

**Comment by OnlineCop** [comment]
The code generated for SED seems to be missing comments that other languages tend to include:

`# The below will remove non-matching lines from the result; if you wish to preserve those lines, remove the ';d' from the end of the sed command:`

or similar could be added right before it.

**Comment by firasdib** [comment]
I'll fix this, thank you!
