### ISSUE TITLE
.NET regex debugger doesn't work despite being shown as available

### ISSUE THREAD

**Issue by InSyncWithFoo** [firasdib/Regex101#2117]
## Bug Description
.NET regex debugger doesn't work despite being shown as available.

### Reproduction steps
* Choose the .NET flavor and input an arbitrary regex.
* The *Regex Debugger* button is enabled/clickable. Click it.

That results in `/debugger` being appended to the URL; however, it is removed shortly afterwards. The popup shows itself in a moment but closes immediately.

### Expected Outcome
Either disabled button, or working debugger.

### Browser
Reproducible on Chrome 115, Firefox 115, Edge 115.

### OS
Windows 10

**Comment by firasdib** [comment]
Thank you, I'll fix this. It shouldn't be enabled.
