### ISSUE TITLE
.NET balancing group does not recognize a named balancing group

### ISSUE THREAD

**Issue by InSyncWithFoo** [firasdib/Regex101#2123]
## Bug Description
.NET balancing group (`(?<-b>)`) does not recognize a named balancing group (`(?<b-a>)`).

### Reproduction steps
Input [`(?<a>a)+(?<b-a>b)+(?<-b>c)+`](https://regex101.com/r/BkpkxO/1).

### Expected Outcome
No errors.

### Browser
Chrome 115.

### OS
Windows 10

**Comment by firasdib** [comment]
Thank you for the report! I can see this was a silly error on my end, I'll have it fixed asap.

It will be in the coming release, which you can expect some time next week.
