### ISSUE TITLE
Some special Unicode characters cannot be displayed correctly in the regular input box

### ISSUE THREAD

**Issue by 821938089** [firasdib/Regex101#2124]
## Bug Description
Some special Unicode characters cannot be displayed correctly in the regular input box

### Reproduction steps
In the regular input box, enter "𝐧𝑶𝒱𝑒𝑙𝗎𝗌𝕓. 𝑪𝑶𝓂"

![image](https://github.com/firasdib/Regex101/assets/8674809/e26fdc23-ed89-43da-a3bf-17804d628f50)

### Expected Outcome
show "𝐧𝑶𝒱𝑒𝑙𝗎𝗌𝕓. 𝑪𝑶𝓂"

### Browser
chrome 115.0.5790.171

### OS
win 10 22H2

**Comment by firasdib** [comment]
This is the result of not having unicode mode enabled, try enabling the `u` flag and it should look as you expect.
