### ISSUE TITLE
Quiz stores most recent attempt instead of shortest

### ISSUE THREAD

**Issue by Timvde** [firasdib/Regex101#2127]
## Bug Description
I just saw that when trying a longer solution than the shortest one I had, the quiz told me that my current shortest solution is <length of the new one> instead of <length of the actual shortest one>.

### Reproduction steps
Submit a longer solution than the shortest one you have. The quiz saves the newest one.

### Expected Outcome
The quiz keeps the shortest one.

### Browser
Firefox 116

### OS
Arch Linux

**Comment by firasdib** [comment]
Thanks, will push fix
