### ISSUE TITLE
Can't open regex gJ7pU0 from library in editor

### ISSUE THREAD

**Issue by LanguidBasil** [firasdib/Regex101#2128]
## Bug Description
Can't open regex gJ7pU0 from library in editor
![image](https://github.com/firasdib/Regex101/assets/72715882/44f8d8ca-68c3-4ef4-b6ea-f8ba125a96f6)

### Reproduction steps
Go to [this address](https://regex101.com/library/gJ7pU0?orderBy=MOST_UPVOTES&search=email) and click button [open regex in editor](https://regex101.com/r/gJ7pU0/1)

### Expected Outcome
Regex opened in the editor

### Browser
Google Chrome
Version 115.0.5790.171 (Official Build) (64-bit)

### OS
Windows 10 Home Single Language
Version 22H2
OS build 19045.3324

**Comment by firasdib** [comment]
Thank you, pushing fix now.

**Comment by LanguidBasil** [comment]
🔥
