### ISSUE TITLE
"Is Null" does not appear to work

### ISSUE THREAD

**Issue by jimw54321** [firasdib/Regex101#2129]
## Bug Description
The "is null" functionality does not appear to work for "lazy" regex.

### Reproduction steps
1. Create a testcase
2. Create a regex    (a??)
3. Choose "capture group one"
4. Choose "is null"
5. Create another testcase
6. Create a regex   a??
7. Choose "fullmatch"
8. Choose "is null"

### Expected Outcome
Both testcases should pass.

### Browser
Include browser name and version
Google Chrome Version 115.0.5790.170

### OS
Include OS name and version
AlmaLinux release 9.2

**Comment by firasdib** [comment]
Thanks for the report, I've fixed the bug.

But thinking about it, can `full match is null` is equivalent to `regex does not match`, and the unit test will always fail if the unit test never matches anything (unless "does not match" is selected). Perhaps I should disable `is null` for `full match`?

Edit:
Would seem my code was doing that before, but another bug came in the way. I'll adjust :)
