### ISSUE TITLE
Allow the passing of a regex as a URL parameter

### ISSUE THREAD

**Issue by dfpomeroy** [firasdib/Regex101#213]
I have a web application that requires the configuration of many regexes.  I'd like to be able to configure a link from my application to regex101.com in such a way that I can start testing my regexes right away and I don't have to copy and paste. 

Example:

https://www.regex101.com/?r=^(?:(?:\+?1\s*(?:[.-]\s*)?)?(?:\(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s*\)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})(?:\s*(?:#|x\.?|ext\.?|extension)\s*(\d+))?$

(The above would have to be URL encoded of course)

Does this capability already exist?  Thanks.

**Comment by dfpomeroy** [comment]
This link format seems to work: https://regex101.com/?regex=^%28?:\+?1%29?%28800|866%29[0-9]{7}&options=gm.  Will this always be supported?  Thanks.

**Comment by firasdib** [comment]
There is legacy support for this, since way back. I have kept it there but it's not as extensive as using the actual permalink feature. You can use that link just fine.
