### ISSUE TITLE
[FR] Add a notes section to regular expression page

### ISSUE THREAD

**Issue by claudio-salvio** [firasdib/Regex101#2136]
Hello @firasdib 

It seems to me that on many occasions it is necessary or convenient to write **notes about the regular expression**.
I think it would be very useful to have **a section on the regular expression page** where you can write those notes and save them using the usual mechanism (<kbd>CTRL</kbd>+<kbd>S</kbd>).

The requirement is similar to [Add notes as optional on tests #299](https://github.com/firasdib/Regex101/issues/299) but with a more general scope.

🙏 Thank you very much for making this service available!

Kind regards,
Claudio Salvio

**Comment by firasdib** [comment]
Hi @claudio-salvio 

Typically, in regex, you'd use comments to write those notes. By using the `(?x)` flag, you enable comments (and also ignore superfluous whitespace). See [this](https://regex101.com/r/ZaA9eI/1) example.

I hope this helps.
