### ISSUE TITLE
Make a tab to export all current matches

### ISSUE THREAD

**Issue by alexeckardt** [firasdib/Regex101#2137]
## Feature
A Separate tab to use a regex, and grab all match groups put the test box

**Comment by working-name** [comment]
![image](https://github.com/firasdib/Regex101/assets/16505052/7d324724-d1aa-4f6a-a7b6-d54b955da2ed)
![image](https://github.com/firasdib/Regex101/assets/16505052/dc09a2d8-3c63-4f74-b20f-f9bb726f7c91)

Hello @alexeckardt,

There's an export icon in the matches information sidebar. Is that what you needed?

**Comment by alexeckardt** [comment]
Yeah, that is exactly what I was looking for! I remembered that existed before a lot of things got rearranged, but just couldn't find it afterwards. Thanks so much!

Just as a side thought, it seems kind of strange to have the export button on the first match -- especially because that tab can get quite noisy with all the matches. I wonder if it could be its own button under the Tool bar for ease of access?

Cheers, thanks again.

**Comment by firasdib** [comment]
That makes sense, perhaps it's better to place it in the left sidebar.

**Comment by alexeckardt** [comment]
Perhaps keep the current placement, but add it additionally to the left sidebar? I think there wouldn't be any harm in keeping it under matches as well.

**Comment by firasdib** [comment]
Yeah, I’ll do that :-). Thank you!Vänliga hälsningar / Best regards,Firas DibOn 29 Aug 2023, at 19:12, Alex Eckardt ***@***.***> wrote:﻿
Perhaps keep the current placement, but add it to the left bar as well? I think there wouldn't be any harm in keeping under matches as well.
