### ISSUE TITLE
Support Perl flavor in replacement i.e. s/FOO/\L$&/

### ISSUE THREAD

**Issue by nowox** [firasdib/Regex101#214]
A least it would be great to convert the casing

**Comment by nhahtdh** [comment]
I think there is no point in support a single feature. The important thing is whether you can use it in your language/library or not. Rather than supporting a feature, it is more sensible to support the whole flavor instead.

**Comment by firasdib** [comment]
What @nhahtdh said.

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/317
