### ISSUE TITLE
@"[\u20ad-\u3300]"i is matching the letter k (\u006B) incorrectly.

### ISSUE THREAD

**Issue by ceelix** [firasdib/Regex101#2143]
## Bug Description
The following regex "[\u20ad-\u3300]" with case insensitive match flag "i" is matching the letter k (\u006B) and is well outside those bounds. Why does this happen?
![B1Wm6dCX9oq0h410](https://github.com/firasdib/Regex101/assets/9885722/6802e190-0cd6-4b6b-a7bc-225caa6c852e)

I tested this match on my own on a .Net Framework 4.8 application and the same regex does not match (which is correct). However when testing in .Net Core 7 I get a match just like in here at Regex101. This might be a problem with Microsoft .Net

Case insensitive flag should not have any effect on the outcome but it does.
Is this an incorrect match? Or is my assessment of the expected outcome incorrect?

### Reproduction steps
1. Select flavor .NET (C#)
2. Select function Match
3. Add the regex "[\u20ad-\u3300]"
4. Add the test string "skiing"
5. Select regex options "insensitive" and uncheck everything else
6. The letter k is matched incorrectly

### Expected Outcome
It is expected to not match the letter k when using the regex "[\u20ad-\u3300]" with "i" modifier

### Browser
OperaGX LVL5 (core: 100.0.4815.82)

### OS
Windows 11 Pro Version	10.0.22621 Build 22621

**Comment by firasdib** [comment]
I'm not sure, it seems to do the same in Python and Rust, too. I don't think it's a bug with regex101 though.

**Comment by firasdib** [comment]
Few fellas on IRC helped me debug this. Turns out `K` is a part of that range (capital case `k`), likely due to the upper case category `Lu`.
