### ISSUE TITLE
Quick reference  -> Quantifier -> Possessive quantifier 

### ISSUE THREAD

**Issue by inxeoz** [firasdib/Regex101#2145]
## Bug Description
regex is misspelled like "\d++." but the regex tends to be "a*+"

### Reproduction steps
change regex as it should shown "a*+"

### Expected Outcome
i don't know too much about it.

### Browser

microsoft edge Version 116.0.1938.81 (Official build) (64-bit)

### OS
windows 11

**Comment by working-name** [comment]
Hi there,

Thank you for your feedback. That's not a typo, `+` means 1 or more times, and `*` means 0 or more times. It can also be something like `{5,10}` which means between 5 and 10 times. That's the quantifier. 

The `+` following it is the possessive quantifier.
