### ISSUE TITLE
Support for creating a .NET flavoured post via the API

### ISSUE THREAD

**Issue by RalfReddings** [firasdib/Regex101#2149]
Unless I am mistaken, it is not possible to create a post with a **.NET** flavour. The following example creates a post on the website for PCRE flavour. I can do the same with Python and JavaScript:
    
    $body	= @{
    	regex	= "hello"
    	flags		= "i"
    	delimiter	= "~"								
    	flavor		= "pcre"						
    	testString	= "hello world, pcre"
    }
    Invoke-RestMethod -Method Post -Uri "https://regex101.com/api/regex"  -Body $body
    

but trying to create a post a for **.NET** flavour fails:

    
    $body	= @{
    	regex		= "hello"
    	flags		= "i"
    	delimiter	= """"   # I have also tried 	==>  delimiter	= """"""""										
    	flavor		= ".net"						
    	testString	= "hello world, .net"
    }
    Invoke-RestMethod -Method Post -Uri "https://regex101.com/api/regex"  -Body $body
    
I get this error:
    
    Invoke-RestMethod: 
    Line |
       8 |      Invoke-RestMethod -Method Post -Uri "https://regex101.com/api/reg …
         |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         | {"error":"Invalid flavor","errorId":"069212bd-d333-49c0-bb57-7752757deba0"}
    

The website itself has full .NET support, so this does not make sense. Perhaps I am doing something wrong here?

If not, please consider adding .NET support. It would mean allot.

**Comment by firasdib** [comment]
Use `dotnet` and not `.net` for the flavor.
