### ISSUE TITLE
Support for the | separator

### ISSUE THREAD

**Issue by nowox** [firasdib/Regex101#215]
Like s|foo|bar|g

**Comment by firasdib** [comment]
This would introduce some annoyances and would make it harder for me to parse, seeing as how | is a metacharacter commonly used in regex. Wont any of the other ones work?

**Comment by nowox** [comment]
They do most of the time, but I usually use Perl and commonly choose | as
metacharacter since I usually match / \ and #. @ is to my opinion too
strong and creates readability issues. Otherwise it is not a big deal.

(In between the support of | or the availability for the Perl flavor, I
would definitely chose the Perl flavor :) )
