### ISSUE TITLE
Rust flavor produces error for valid regex

### ISSUE THREAD

**Issue by gammelalf** [firasdib/Regex101#2151]
## Bug Description
I'm assuming your using `rust-lang/regex` as your rust library.
(I couldn't find verification in your docs but that's what your code generation uses.)

One of its examples doesn't work on you're page.
`(?-u)(?<cstr>[^\x00]+)\x00` taken from its [README](https://github.com/rust-lang/regex#usage-match-regular-expressions-on-u8)

### Reproduction steps
Enter `(?-u)(?<cstr>[^\x00]+)\x00`

### Expected Outcome
The ability to test strings againts this valid regex.

**Comment by working-name** [comment]
Seems to do well in stable all the way up to nightly, but I know nothing about rust: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a092013a1d3d4580339ac2e481e33420)

**Comment by firasdib** [comment]
You cannot disable unicode in Rust, since that caused a lot of issues. See #1208 

If you have a good solution for it, I'd be happy to implement it.

**Comment by InSyncWithFoo** [comment]
@firasdib I don't know Rust, but it seems that _rust-lang/regex_ [accepts both `(?P<foo>)` and `(?<foo>)`](https://github.com/rust-lang/regex/blob/11b44439786499014f61afe6e294650fb01550be/regex-syntax/src/ast/parse.rs#L1206). Currently regex101 only allows the former.

**Comment by firasdib** [comment]
I get an error with the Rust version running on regex101 - maybe I've compiled an older version?

**Comment by InSyncWithFoo** [comment]
@firasdib Probably. [This snippet](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a6126d0f88a8e92879a7dc51e7df7f90) (written by ChatGPT) runs just as fine with either `(?P<foo>)` or `(?<foo>)`.

**Comment by InSyncWithFoo** [comment]
It seems that this feature was added recently in issue [#955](https://github.com/rust-lang/regex/issues/955) and corresponding PR [#956](https://github.com/rust-lang/regex/pull/956). Oh, and you might want to modify the Go flavor too, since [_re2_ now supports `(?<foo>)` as well](https://github.com/rust-lang/regex/issues/955#issuecomment-1675238715).

**Comment by firasdib** [comment]
Thank you for the info. I'll try to get to this when I get more time on my hands. Closing in favor of https://github.com/firasdib/Regex101/issues/2167
