### ISSUE TITLE
Add messages for non-backslash escapes in some flavors

### ISSUE THREAD

**Issue by kwon0408** [firasdib/Regex101#2157]
## Feature
I suggest to add messages and hints for non-backslash escapes in some flavors, such as `""` for `"` in C#.

In this issue tracker, many people have shown they have felt confusing when the escape sequence is not backslash-and-then-itself (like `\"`). Issues #2017 and #2085 are the example. (And sometimes I get confused too.)

But for now, the Quick Reference search box suggests `\"` only, even for C# flavor, where `""` is valid and `\"` is not.

**Comment by firasdib** [comment]
I have added a unique entry to the quickref for .NET regarding this. Thank you!
