### ISSUE TITLE
Recognize `r'^\w+\S+[@:]\S+'` akin to `/^\w+\S+[@:]\S+/`

### ISSUE THREAD

**Issue by stdedos** [firasdib/Regex101#2158]
## Feature

Pasting `r['"]^\w+\S+[@:]\S+['"]` should recognize it similarly to pasting `/^\w+\S+[@:]\S+/`.

_Flags parsing might be more complicated (e.g. `, re.UNICODE`), but it can be ignored hopefully?_

**Comment by working-name** [comment]
Hi @stdedos 

Just FYI, if you paste it without the `r`, with the python flavor selected, it parses the regex correctly.

**Comment by InSyncWithFoo** [comment]
@working-name's correct. It will also accept trailing flags: `"fo[ob]+ar"gmu`. Invalid flags are ignored instead of falling back to verbatim pasting, however.

**Comment by stdedos** [comment]
I was hoping that `r['"]^\w+\S+[@:]\S+['"]` would be "uniquely" identified as:
1. Regex
2. Python regex

_and DWIM automatically_. But since there's already support - and if you are not planning to expand it, I'm fine closing this as won't-do 🙃

**Comment by firasdib** [comment]
Currently it just pastes the regex into the input box, no additional magic. Multiple languages share a common string format, so it would be non-trivial to switch automagically in any meaningful way.
