### ISSUE TITLE
Issue with multiple named group

### ISSUE THREAD

**Issue by nowox** [firasdib/Regex101#216]
In this example: 
https://regex101.com/r/tQ5qT2/2

The match 15 is never treated

**Comment by nhahtdh** [comment]
Referring to captured text in replacement string is not supported in PHP (and R also). PCRE library itself also doesn't have a straight replacement API.

However, it seems preg wrapper in PHP works in this case, if you use preg_replace_callback:
http://ideone.com/gRGVUG

So it is worth looking into the implementation of this function in PHP:
https://github.com/php/php-src/blob/bf59acdea75cf13d179f10ce89d296a30f38676d/ext/pcre/php_pcre.c#L1097

**Comment by CasimirEtHippolyte** [comment]
You can't indeed refer to a capture by its name in a replacement pattern, however all named captures are at the same time a numbered capture, and you can always use the associated number**(s)**.

**About the `J` modifier in pcre**
 *(Note that it is only an inline modifier and not a global modifier in the PHP implementation, so you need to write `(?J)` and `(?-J)` in the pattern to switch it)*.

When you use it, you are allowed to use the same name for several captures. It is useful if you want to add semantic to your pattern and it is handy if you need to use a backreference inside the pattern.

This feature highlights an issue related to how pcre manages duplicated named captures. Named captures are only aliases for one group and for one match. But if you perform a global research the named capture is alternately the first or the second capture group (in your pattern). So you can't define a bijective relation between a name and a number. If you use `preg_match_all` in PHP, you can see that the named capture contains only the matches of the last defined group in the pattern. It seems that regex101 has choosen the first. Is it a bug, I can't say it. At least it is a difference of implementation. Note that I don't have tested with R language or boost to compare.

The only way to obtain a many-to-one relation between numbered groups and a named group in your case is to use the branch reset feature:

    (?|
        (?&R)\K\s*(?<sign>[=+*-])\s*(?=(?&R))
      |
        (?&R)\s*\K\s*(?<sign>=)\s*(?=-(?&R))
    )

    (?(DEFINE)
        (?<R>(?<!\w) ( (?:f|r|s) (?:1[0-5]|[0-9]) | CI | 1))
    )

**Comment by firasdib** [comment]
As previously discussed, this is a tricky edge case. Adjusting it one way or the other will only eliminate one case and introduce another.

This is all custom implementation by me, as PCRE has no support for any form of substitution or such. Every language has their own way of doing it. To be safe, you should design your pattern more carefully to avoid falling into problems like these.

**Comment by nhahtdh** [comment]
@firasdib: Just in case you missed my comment, you might want to look at how PHP implementation of preg_replace handles this case, since it kinda works, as shown in the demo (I haven't taken a closer look at the code to see how it actually works, though).

**Comment by firasdib** [comment]
I just read this in the perldoc:
```
When different groups within the same pattern have the same name, any reference to that name assumes the leftmost defined group.
```

**Comment by martin0018** [comment]
> En este ejemplo: https://regex101.com/r/tQ5qT2/2
> 
> El partido 15 nunca se trata

**Comment by totalavatar** [comment]
> In this example: https://regex101.com/r/tQ5qT2/2
> 
> The match 15 is never treated
