### ISSUE TITLE
Saved Regex urls does not work anymore

### ISSUE THREAD

**Issue by bertrandjamin** [firasdib/Regex101#2161]
## Bug Description

I have a saved regex url (ex: https://regex101.com/r/rh9AIu/1) 
When clicking on it I'm redirected on an empty regex screen and I ha ve no more access to the saved Expressions

### Reproduction steps
* Fill a regex screen
* Saved it
* Copy the saving link
* Paste it on an other tab
* The saved Expressions is not available

### Expected Outcome

The saved link should work as usual

### Browser
Include browser name and version

### OS
Include OS name and version

Thanks

**Comment by working-name** [comment]
Hi @bertrandjamin 

The behavior you describe is normal in cases where the regex was deleted (you're offered a link to delete when you save something). If you're not logged in, you will never see that delete link again.

That being said, I followed your steps and went even further switching between a few browsers on the macOS platform. I cannot reproduce the behavior described.

Can you help me out with the OS/browser you're using? I'll try to reproduce your environment in a VM or something.

**Comment by bertrandjamin** [comment]
@working-name I have just tested it few minutes ago and it works nicely now... 

I toughts you have fixes something... 

BTW saved links works well now. 

I close the issue

Thanks

**Comment by firasdib** [comment]
The site is being ddosed, so sometimes it may act a little weird
