### ISSUE TITLE
Case sensitive/insensitive not functioning. 

### ISSUE THREAD

**Issue by OldSkoolCoderGuy** [firasdib/Regex101#2162]
## Bug Description
Irrespective of the /*/i matches always work

### Reproduction steps
/G\*S\*/ or /G\*S\*/i
On Guy schwartz

### Expected Outcome
No Match and Match

### Browser
Include browser name and version
Firefox 118.1.1

### OS
Include OS name and version
Android 13

**Comment by working-name** [comment]
![image](https://github.com/firasdib/Regex101/assets/16505052/bfedc6ca-5910-4bc7-9dd9-6abbfeb1afd9)
![image](https://github.com/firasdib/Regex101/assets/16505052/1e0c6529-1574-4f4a-afcf-2a4163825c4a)

Hi @Zeiss2020,

It seems to behave normally on my end, but I have 118.2, not 118.1.1.

Do these screenshots match what you see?

**Comment by OldSkoolCoderGuy** [comment]
Possibly I don't understand the expression. 
I'm looking for a Capital G [anything]  Capital S [anything] so Insensitive should fail on Guy schwartz.
Something like G[a-z]{\*}S[a-z]{\*}

**Comment by working-name** [comment]
Oh I see. `*` means 0 or more of the previous thing. So in your case you asked the engine to match 0 or more capital `G`, then 0 or more capital `S`, anywhere in the string, and not care about where the string starts or ends. When you add the `/i` flag you tell the engine it's ok to find a capital `G` or a lowercase `g` 0 or more times, and so on.

So, if that "anything" can really be anything, then that would include spaces, and newlines, and weird characters and emoji and so on. You get the point.

If I were to guess you are probably looking for something similar to this: `/G[a-z]+ S[a-z]+/g` or `/^G[a-z]+ S[a-z]+$/mg`.

I would highly recommend you either join us on IRC or Discord for help coming up with an expression that does what you need. It's instant (almost) communication, likely more useful than a github issue.

**Comment by OldSkoolCoderGuy** [comment]
Could I get a invite for discord? I'll try irc in the meantime.

Thank you.

**Comment by working-name** [comment]
Sure! https://discord.gg/wUA6F6YqSs

(for the future googler: the updated link is under Live Help on the left sidebar, last icon at the bottom)
