### ISSUE TITLE
[Rust] Support for the latest version of Regex crate

### ISSUE THREAD

**Issue by fukusuket** [firasdib/Regex101#2167]
## Flavor Request
Hello, Thank you so much for awesome tool :)
There are several new grammars supported in recent Regex create releases. for example:
- [1.8.0 (2023-04-20)](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#180-2023-04-20)
  - https://github.com/rust-lang/regex/issues/501
  - [Regex code example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b8e1adef0655e31be2473e05a1e56472)
- [1.10.0 (2023-10-09)](https://github.com/rust-lang/regex/blob/master/CHANGELOG.md#1100-2023-10-09)
  - https://github.com/rust-lang/regex/issues/469
  - [Regex code example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0561ce7cdfdfc9e123bfb7b0eaa3c015)

Currently, the above regular expression causes an error in `regex101`, so I would be very happy if you could support the latest version of Regex crate.

Regards,

**Comment by firasdib** [comment]
This will be included in the next version
