### ISSUE TITLE
regex101.com (without www.) stopped working

### ISSUE THREAD

**Issue by Bartvds** [firasdib/Regex101#217]
I have a bookmark on https://regex101.com but the page goes blank (somewhere today or yesterday).

When I prepend www it works fine, like  https://www.regex101.com

Just a heads-up :wink:

**Comment by firasdib** [comment]
Very weird. Seems to work perfectly fine for me. Can anyone else reproduce this?

**Comment by emilien-puget** [comment]
Work fine for me.

**Comment by Bartvds** [comment]
Works fine for me again. There was definitely a short outage (and mild panic :) but let's blame the tubes.
