### ISSUE TITLE
why it recognize it ? this is very strange  because they are the same

### ISSUE THREAD

**Issue by drLacheheb** [firasdib/Regex101#2179]
## Bug Description
![Screenshot 2023-11-08 070139](https://github.com/firasdib/Regex101/assets/114362983/bdb99930-06e8-40dd-8280-2b9072fc0912)

### Browser
Google chrome

### OS
windows 10

**Comment by working-name** [comment]
Hello, 

Could you please share a link (save regex on the left sidebar), or give some more details? What flavor? What flags?

**Comment by firasdib** [comment]
That's strange. Can you provide an URL to reproduce it?
