### ISSUE TITLE
Support pasting /regex/replacement/flags strings

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#218]
Currently, pasting in a regex in the  /regex/flags  format inserts the expression and flags into the page. Adding a /replacement/ field to insert into the SUBSTITUTION box would be nice.

**Comment by firasdib** [comment]
This is not a bad idea, but the problem arises in the following situation:

If you paste `/bad/regex/g`, did you forget to escape the slash or did you mean to insert a replacement? Perhaps this is a viable option if we follow the typical syntax of prepending the string with an `s`, such as `s/regex/repl/flags/`. What do you think?

**Comment by firasdib** [comment]
My idea above has been implemented anyway.
