### ISSUE TITLE
Enlarge the font size of the regular expression edit field 

### ISSUE THREAD

**Issue by juarezr** [firasdib/Regex101#2181]
### Motivation

Regular expressions are complex sequences of characters and symbols that are very hard to read, understand, and correlate with the text they should match or replace.

This is due to the fact that they are very compact way they are structured by just using a short symbol to represent an action or meaning and by abusing of nesting, escapes, lookahead, and lookbehinds.

Besides that, the bigger current screen resolutions and the age also contribute to making it hard to read, understand, and debug.

## Suggestion

- Add an option for increasing or decreasing the font size of the regular expression.
- It should only affect the size of the field where the regexp is typed
   - For the other text on the page, one can use the browser's own shortcuts: <kbd>Ctrl</kbd> + <kbd>+</kbd>  and <kbd>Ctrl</kbd> + <kbd>-</kbd>

### Example

A button for increasing/setting the font size:

    [<kbd><b> <br>  A  🡙  <br> </b></kbd>][KBD]

**Comment by firasdib** [comment]
The fonts are hard coded, based off of a base size of 16px. Your best bet is simply to use <kbd>Ctrl</kbd> + <kbd>+</kbd> to increase the base font size and have the website scale along with it.
