### ISSUE TITLE
Wrong description for optional lookahead/behind

### ISSUE THREAD

**Issue by User4martin** [firasdib/Regex101#2183]
## Bug Description

`1(?=(2))?` reports 

> A quantifier following a lookaround serves no purpose, and can safely be removed from the regular expression

But that is not correct `1(?=(2))?` will match a "1" regardless of it being followed by a "2" or not. But the capture group will be set.

### Reproduction steps
https://regex101.com/r/TgvrXE/1

### Expected Outcome
Different message, at least if the look ahead does something that may change the overall state.

**Comment by firasdib** [comment]
Thank you, I will fix this.
