### ISSUE TITLE
Wrong description for possesive `{1,1}+`

### ISSUE THREAD

**Issue by User4martin** [firasdib/Regex101#2184]
## Bug Description

`(.*){1,1}+b` reports
> {1,1}+ matches the previous token exactly one time (meaningless quantifier)

**"meaningless quantifier"** is not correct. It turns the previous token (group) into a possessive group.

Add/Remove the `+` will make the expression match or not match. 

`{1,1}` without the `+` is indeed meaningless.

### Reproduction steps
https://regex101.com/r/bpGBxG/1

### Expected Outcome
Remove the "meaningless quantifier".
Add info that the group becomes possessive.

**Comment by firasdib** [comment]
Thank you, I'll fix this description.
