### ISSUE TITLE
Dotnet engine not working

### ISSUE THREAD

**Issue by JohnLeyva** [firasdib/Regex101#2185]
![image](https://github.com/firasdib/Regex101/assets/1241530/158f0eb5-e737-4a32-9b16-fd5e26e45022)

Unable to initialize the regex engine! Please try to reload the web page. If the issue persists, please open an issue here: https://github.com/firasdib/Regex101/issues

**Comment by working-name** [comment]
Hi @JohnLeyva 

Could you try to reproduce it but with console open to see if there's any errors? Please do it in an incognito window or using a browser without add-ons to remove those out of the equation.

It would also be super helpful to know what OS you're on, which browser version so I can try to reproduce it. So far I cannot make it crack using Chrome based browsers.

Thanks for your help!

**Comment by aherbage** [comment]
EDIT: I didn't look closely enough at the original post. I'm not sure it actually is the same problem. The site doesn't load initially (see image), but then I guess it falls back to a locally cached version? Sorry for any confusion.

I'm having the same problem, though the offline version loads for me about 30 seconds after the error appears, so I'm able to do what I need. Windows 10, Chrome Version 119.0.6045.160 (Official Build) (64-bit). Thanks for looking into this.

![image](https://github.com/firasdib/Regex101/assets/586607/5d7f7e8d-1ace-4749-8d8e-85e5be52c470)

**Comment by aherbage** [comment]
I also get a "DNS request timed out" message when I run nslookup.

**Comment by working-name** [comment]
@aherbage I inquired google, cloudflare, controlD - all of them respond quickly and with the same A record. Mind directing nslookup to 8.8.8.8 `nslookup regex101.com 8.8.8.8`?

**Comment by aherbage** [comment]
Looks like the nslookup thing was a temporary blip, it resolves now with or without 8.8.8.8, though the site still doesn't load normally.

**Comment by working-name** [comment]
@aherbage would you mind opening console up and go to networking tab (then refresh the site to see the network requests, it doesn't log by default). See what's red - those are generally not loading. See if there's a reason given or if you can resolve those URLs. I've been trying to load the site from different locations in the US, as well as cell data, no issues.

**Comment by aherbage** [comment]
![image](https://github.com/firasdib/Regex101/assets/586607/3cc826a8-5282-4f81-8320-edbbcef5867a)
![image](https://github.com/firasdib/Regex101/assets/586607/e8149d04-41e7-4e70-af75-db016e35acf1)

**Comment by aherbage** [comment]
It's working on my phone, which is on the same wifi network as the laptop these screenshots are coming from, so I think it's safe to assume it's a hardware issue or something on my end. Thanks again for looking into it, but as far as my error is concerned, I'm comfortable dropping it. I don't think there's anything for you to do. Sorry to waste your time!

I'll point out, though, that I hijacked @JohnLeyva's issue, which presumably is something different and still needs attention. I apologize as well for my poor etiquette.

**Comment by working-name** [comment]
Yeah no worries. It's usually the browser that incessantly caches DNS responses and tries to go behind your back to use "secure DNS" type crap. I'm not a fan. If you restart the browser and `ipconfig /flushdns` before you start it, you should be back in business. 

No worries about hijacking I'll mark all of our conversation as off-topic.

**Comment by JohnLeyva** [comment]
Other engines such as Java an JS work without issues

This is the console output

![image](https://github.com/firasdib/Regex101/assets/1241530/4470bcb6-410e-4061-b0f3-442606a70312)

ipconfig /flushdns

did not work neither

**Comment by firasdib** [comment]
Does it work in incognito? Do you have an ad blocker? Looks like something is blocking the network requestsOn 23 Nov 2023, at 10:12, John Leyva ***@***.***> wrote:﻿
This is the console output

ipconfig /flushdns
did not work neither

**Comment by firasdib** [comment]
Closing due to no response. Reopen if this is still an issue
