### ISSUE TITLE
Other way to show Java flags

### ISSUE THREAD

**Issue by ramirobrescia** [firasdib/Regex101#2187]
I will explain the case with an example. Match a file name pattern using `String::matches`.

Filename pattern: ABC_27112023.txt `<3 letter code>_<date ddmmyyyy>.txt`
regex by you: `"^([a-z]{3})_([0-9]{2}[0-9]{2}[0-9]{4})\.txt$"gi`
Final regex: `(?i)^([a-z]{3})_([0-9]{2}[0-9]{2}[0-9]{4})\\.txt$`

## Feature
Show the flags changing the ending `gi` to start with `(?i)` and so on here....
![imagen](https://github.com/firasdib/Regex101/assets/1976911/b10113f8-ea25-40a8-bbd9-ca24212a73d3)

or mention that has to be write differently here....
![imagen](https://github.com/firasdib/Regex101/assets/1976911/ed6594c1-421c-4b0d-95c1-273e0880df4d)

[Java 8 CASE_INSENSITIVE](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#CASE_INSENSITIVE)

Thank you very much for the tool!

**Comment by firasdib** [comment]
The UI is standardized as much as possible across flavors. Perhaps you're looking for the Code Generator in the left sidebar?
