### ISSUE TITLE
Error message is erroneous

### ISSUE THREAD

**Issue by mogando668** [firasdib/Regex101#2189]
TASK : 4 Retrieve Numbers 

Please write both task name and number.

Bug Description :  The regex I entered 

`^0*$|^([1-9][0-9]*, )*[0-9]+$`

Received this error message : 

`Test 15/20: Don't match non-integer values (such as 3.14159) as a single value. That's for a later task!
`

However, I do not believe my entry would indeed be matching floating point pi. 

This is just no-frills `ERE `regex syntax, and I've cross tested via` gnu gawk`,  `gnu-grep`, `bsd-grep`, and also `perl` to affirm my understanding.

Reproduction steps : Task 4, using the full regex above.

Expected Outcome :  expected not to be erroring due to matching partial integers within a floating point input.

If there are any test cases you think need to be added, you can write that here as well.

Browser : Safari 16.3 
Include browser name and version

OS
Include OS name and version 

Apple macOS Ventura 13.2.1 on Apple Silicon M1 MAX

**Comment by firasdib** [comment]
Thank you, this will be resolved in the next release.
