### ISSUE TITLE
buggy variable length lookbehind with pcre

### ISSUE THREAD

**Issue by CasimirEtHippolyte** [firasdib/Regex101#219]
If variable length lookbehinds like `(?<=.+)` or `(.)(?<=\1)` are not supported by a pcre regex engine, a variable length lookbehind containing an alternation where all branches have a fixed length is allowed. So, if you write something like `(?<=abc|d|efgh)`, it works well.

But if one of the branches is an anchor (that is allowed), you obtain the error: *"lookbehind assertion is not fixed width"*.
example: `(?<=abc|\A).` or `(?<=abc|^).`
Note that it works if the other branches are empty: `(?<=|\A).` or `(?<=\A|).` or `(?<=|\A|).`

If you put several consecutives empty branches `(?<=|||)` (that is useless but allowed), you obtain the error: *"Alternator at this position effectively truncates the group, rendering any other tokens beyond this point useless"*. It's true, but it should be only a warning, not an error.

**Comment by nhahtdh** [comment]
I have also confirmed it by checking with pcretest (pcrelib 8.35) that look-behind with alternation of fixed length patterns is allowed. Even something like  `/(?<=(.{2}){2})/g` is allowed, but `/(?<=.{1,20})/g` is not allowed.

**Comment by firasdib** [comment]
Will look into this

**Comment by firasdib** [comment]
I have a potential fix for this, in testing phase (will have to pester OnlineCop ;)).

**Comment by nhahtdh** [comment]
@firasdib Shouldn't this be an easy fix like the case with `(?R)`? pcretest seems to return the error..

**Comment by firasdib** [comment]
@nhahtdh All validation is done in a pre-processing stage which is why I can create meaningful and accuracte error messages. If I wanted to use the built in functionality I would merely get an offset where the engine stopped and some semi-generic error message. Not only that, I would need to compile the pattern every single time (quite heavy), instead of compiling it just once.

**Comment by firasdib** [comment]
I believe I have fixed this, but would appreciate if one of you could pop by IRC and give it one last test. Will push changes live soon.

**Comment by nhahtdh** [comment]
@firasdib: The problem is not totally fixed. Please refer to the first post and this regex `(?<=abc|^).`

Permalink: https://regex101.com/r/lW4wT0/1

Output from pcretest
```
$ pcretest
PCRE version 8.35 2014-04-04

  re> /(?<=abc|^)./g
data> khksdabcskldfl
 0: k
 0: s
data>
```

**Comment by firasdib** [comment]
You need to join irc to test it. I have not pushed my changes live.

**Comment by nhahtdh** [comment]
Confirm fixed.
