### ISSUE TITLE
C# delimiters for 3x, 4x and 5x double quotes are not string literals

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#2192]
## Bug Description

The default C# delimiter is `@"..."` (single quote string literal). The additional options currently show `"""..."""`, `""""....""""`, `"""""..."""""` (3x, 4x, and 5x quote strings, but not string _literals_) when switching to them.

These other delimiter options should probably also be string literals.

## Examples

1. `@"..."` delimiter:
    - REGULAR EXPRESSION: `@""((?>[^""]+|[""]{2})*)""`
    - TEST STRING: `@"" @"text" @"a\nb" @"a""b" @"a\""\""b"`
    - SUBSTITUTION: `"$1"`
    - Code Generator snippet:
        ```c#
            public static void Main()
            {
                string pattern = @"@[""]((?>[^""]+|[""]{2})*)[""]";
                string substitution = @"""$1""";
                string input = @"@"" @""text"" @""a\nb"" @""a""b"" @""a\""\""b""";
        ```
    - Result (in substitution field) on [regex101](https://regex101.com/r/3Vmv3E/1): `"" "text" "a\nb" "a""b" "a\""\""b"`
    - Result (of "Code Generator" [output](https://regex101.com/r/3Vmv3E/1/codegen?language=csharp)) on [try.dot.net](https://try.dot.net): `" @"text" "a\nb" "a"b" "a\"\"b"`

2. `"""..."""` delimiter:
    - REGULAR EXPRESSION: `@""((?>[^""]+|[""]{2})*)""`
    - TEST STRING: `@"" @"text" @"a\nb" @"a""b" @"a\""\""b"`
    - SUBSTITUTION: `"$1"`
    - Code Generator snippet:
        ```c#
            public static void Main()
            {
                string pattern = """
        @[""]((?>[^""]+|[""]{2})*)[""]
        """;
                string substitution = @"""$1""";
                string input = @"@"" @""text"" @""a\nb"" @""a""b"" @""a\""\""b""";
        ```
    - Result (in substitution field) on [regex101](https://regex101.com/r/3Vmv3E/2): `"" "text" "a\nb" "a""b" "a\""\""b"`
    - Result (of "Code Generator" [output](https://regex101.com/r/3Vmv3E/2/codegen?language=csharp)) on [try.dot.net](https://try.dot.net) (after manually prepending `@` to `"""`): `" @"text" "a\nb" "a"b" "a\"\"b"`

## Expected

1. The delimiters should show `@` before the `"""`, `""""`, `"""""`.
2. The Code Generator output should as well. Additionally, there should probably not be a newline after the opening `"""` and before the closing `"""`, as shown above.
    - I would expect it to look the way the `@"..."` outputs now.

**Comment by firasdib** [comment]
Thank you, fixed locally
