### ISSUE TITLE
Javascript backreference vs octal character

### ISSUE THREAD

**Issue by sancarn** [firasdib/Regex101#2193]
## Bug Description

The `\01` in the following regex: `(.)\01` is listed in Regex101 as "Backreference: Matches the same text as the 1st capturing group". But the evaluation indicates this is not the case, and actually it matches any character followed by an octal?

### Reproduction steps

![image](https://github.com/firasdib/Regex101/assets/7938900/6e861c3f-6ac3-49e8-9250-4b9c5c986c6a)

**Comment by working-name** [comment]
https://regex101.com/r/qA4E2s/1

**Comment by firasdib** [comment]
Thank you, fixed locally!
