### ISSUE TITLE
Unicode group \p{Zs} description is not correct

### ISSUE THREAD

**Issue by six5536** [firasdib/Regex101#2194]
## Bug Description

Unicode group \p{Zs} description is not correct

### Reproduction steps

Use regex: [\p{Zs}] 
Flavour: JavaScript, 
Flags: gu

### Expected Outcome

A description something like:
`\p{Zs} matches a space character (of various non-zero widths)`

### Actual Outcome

The following group description
`\p{Zs} matches a whitespace character that is invisible, but does take up space`

### Browser
Chrome 120.0.6099.109 (Official Build) (x86_64)

### OS
MacOS 14.1.2 (23B92)

**Comment by working-name** [comment]
Hi @zx-ncoderz,

I'm afraid I don't quite see the difference other than a narrower definition from `whitespace` to `space`. The rest of it is semantics that don't change the underlying meaning. Would you like to expand further?

Also, I'm not sure if 120 implemented it but the regex engine in Chromium 119 doesn't know about `\p{Zs}`
<img width="459" alt="image" src="https://github.com/firasdib/Regex101/assets/16505052/f5bef518-39d7-44ab-880a-446694c29717">

**Comment by six5536** [comment]
@working-name You are right, I somehow mis-read the original text. Thanks for the heads up regarding support in Chrome.
I'll close the issue.
