### ISSUE TITLE
Allow batch/multiple match expressions mode for substitutions.....

### ISSUE THREAD

**Issue by 4evermaat** [firasdib/Regex101#2198]
## Enable batch mode so that multiple regex searches on a sample text can be performed.

-> This would allow the user to have several find/replace operations that happen sequentially.  Because seeing just one search/replace result may not be enough.  We sometimes need to see how several replacements done sequentially will look like (the final replace text).

```
search/replace pair 1
search/substitute pair 2
search/substitute pair 3
search/substitute pair 4
search/substitute pair 5
search/substitute pair x
```
-> I'm thinking a different tab might be needed for this (or a tabbed setup in a new browser tab), and you can show each step in a separate tab.  With a pane that shows all the search/replaces as a list (you can give each search some short title/description to make it easier to keep track of the pairs.

-> Drag/drop would be good so that you can easily re-order the search pairs.  And the debug tool would still work mostly the same.

-> And some kind of play/pause/step button to where you can run the batch all at once,  or step through each search one at a time.

Re-arranging text sometimes requires several searches combined.  It isn't always convenient or practical to attempt to make one long regex search/replace to attempt to do everything.  And I think ultimately this allows users to write more efficient regex phrases as it doesn't overwhelm people to try to create a long, complicated single phrase regex.

**Comment by working-name** [comment]
Hello @4evermaat 

Thank you for your suggestion! 

This was discussed before and I did not see a change in the conclusion yet. Please see: #1624, #1360

**Comment by 4evermaat** [comment]
I think it is inevitable that you will include this.  **You can't scale the regex capability without using multiple passes.**

At the same time, I do respect that it might be a lot of work in terms of having to figure out how to incorporate this into the existing UI interface.

As a compromise, you could have a user save their regex strings and then have a button that would allow them to copy the replacement text of `search1` to the new regex search/replace string of `search2`.   

It is a manual process.....and eventually users would just eventually ask "Can you just combine all these searches into a single click?"

I use TextCrawler and/or EmEditor for these things; they are Windows desktop apps.   But of course was hoping regEx101 could emulate this as well.

**Comment by firasdib** [comment]
I have been thinking a lot about this feature and its usefulness, and decided, it provides a lot of value. It took me 5+ years to realize this, but I can announce that it's on the road map and being developed.

I will be a feature available to regex101 Pro users, and it will allow you to create an arbitrary chain of regexes and substitutions and apply those recursively on an input string.

If you'd like to discuss more, I am available on both IRC and Discord.

**Comment by firasdib** [comment]
This feature is now live on the site.

**Comment by 4evermaat** [comment]
@firasdib can you remove the "closed as not planned" label?

Glad to see myself (and others) were able to help you see the light.
