### ISSUE TITLE
shortcut save/update

### ISSUE THREAD

**Issue by Svadilfari83** [firasdib/Regex101#2199]
## Enhancement
Switch keyboard shortcuts for save and update regex.
CTRL-S should update existing regexes, as in any other software program

Personally, I end up with multiple regexes all the time in "my expressions" because I hit ctrl-s instead of ctrl-shift-s.
Then needing to clean up and copy paste the code into the "original" expression.

**Comment by firasdib** [comment]
This has been discussed and changed back and forth many times over the years.

The primary issue with your suggestion is that many people open existing entries through e.g. stackoverflow, start editing, and hit save. By default, that'll add a new version to that entry, and not create a new one. This has, consequently, also confused a lot of people.
