### ISSUE TITLE
Cannot access saved expressions after changing Github username

### ISSUE THREAD

**Issue by chrisnuzum** [firasdib/Regex101#2205]
I log in to regex101 with Github. I recently noticed I cannot access my saved expressions ("You have not created anything yourself yet.") My guess is that this occurred when I changed my Github username about a month ago.

I came across [this issue](https://github.com/firasdib/Regex101/issues/2096) and figured it was a similar problem. I did email my info to contact@regex101.com on 12/29/23 in the hopes that you could at least manually migrate my expressions.

**Comment by firasdib** [comment]
I replied the very same day, check your inbox :-)!

**Comment by chrisnuzum** [comment]
Went to spam :(
It's working now, thanks!
