### ISSUE TITLE
Java: Flags `d` and `U` are not supported

### ISSUE THREAD

**Issue by Marcono1234** [firasdib/Regex101#2206]
## Bug Description
Java supports the following flags: `idmsuxU` (see [documentation](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/regex/Pattern.html#flags))

However, Regex101 does not seem to support / recognize these flags:
- `d`: [`UNIX_LINES`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/regex/Pattern.html#UNIX_LINES)
- `U`: [`UNICODE_CHARACTER_CLASS`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/regex/Pattern.html#UNICODE_CHARACTER_CLASS)

Also, there is no dropdown entry for `UNIX_LINES` in the global flag selection.

### Reproduction steps
1. Select the Java regex flavor
2. Enter this pattern
    ```
    (?idmsuxU)a
    ```
    :x: Bug: It shows a parse error

### Expected Outcome
The pattern should be parsed successfully

Or if these flags are not supported yet by Regex101, it would at least be good if the parse error explicitly mentioned that.

### Browser
Firefox 121.0 (64-bit)

### OS
Windows 10

**Comment by firasdib** [comment]
Thank you, this will be fixed in the next release.
