### ISSUE TITLE
Multiple characters in negative character group not working.

### ISSUE THREAD

**Issue by ThomHurks** [firasdib/Regex101#221]
Test Input:

http://deportes.terra.es/futbol/internacional/criticas-al-bayern-por-jugar-un-amistoso-en-arabia-saudi,cca6a1e8e950b410VgnVCM3000009af154d0RCRD.html

Regex:

http://deportes\.terra\.es/([^/,]+/)+[^/,]+,[^/]+\.html$

Goal: match the URL.

Result: does not match. But does match on other sites like Debuggex.com or with the PCRETest command line tool. If you remove the comma (,) from the character group then it does work.

**Comment by firasdib** [comment]
Hmm... It seems to work fine for me: https://regex101.com/r/pT9dO4/1 and https://regex101.com/r/pT9dO4/2

Can you show me an example where it fails?

**Comment by ThomHurks** [comment]
What do you mean? The first link (with comma) does not match, but should match.

**Comment by firasdib** [comment]
Did you view my links? Matches fine for me. 

If I have gotten it wrong, give me a full example on regex101.com where it fails.

**Comment by ThomHurks** [comment]
![screen shot 2015-01-24 at 13 49 07](https://cloud.githubusercontent.com/assets/6796124/5887423/d96ac18c-a3cf-11e4-8231-bd3cdda5252a.png)

Is it my browser then or something? I use Google Chrome.

**Comment by firasdib** [comment]
It looks like you have a newline in there. Give me the link please.

**Comment by ThomHurks** [comment]
https://regex101.com/r/pT9dO4/3

**Comment by firasdib** [comment]
That matches just fine in my Chrome. Open up the console and look for any errors there please.

**Comment by ThomHurks** [comment]
I see no errors in my console. I am using Chrome 64-bit beta 41.0.2272.16 on Mac OS X

**Comment by firasdib** [comment]
I don't know what to say. Works fine for me on Chrome Version 40.0.2214.91 (64-bit) on OSX.

![screen shot 2015-01-24 at 14 13 06](https://cloud.githubusercontent.com/assets/1335165/5887488/5902863e-a3d3-11e4-9fa6-39b4977104fc.png)

**Comment by ThomHurks** [comment]
Perhaps a regression in Chrome 41 then, hmm.

**Comment by firasdib** [comment]
Have you tried it in incognito or another browser?

**Comment by ThomHurks** [comment]
Okay, weird. I just opened the tab with regex101 open and it had matched! I refreshed the page and then it didn't match again.

**Comment by firasdib** [comment]
Very weird. Could be a bug in the beta version.

**Comment by ThomHurks** [comment]
I guess :/ I will keep an eye on it.

**Comment by firasdib** [comment]
Can anyone else recreate?
