### ISSUE TITLE
Regex.com critical error on certain pattern paste

### ISSUE THREAD

**Issue by rubankopli** [firasdib/Regex101#2211]
## Bug Description
Regex.com throws a critical error on pasting a pattern in the site text box
May be due to local plugins/not tested with other patterns

### Reproduction steps

1. Open a new tab and browse directly to regex101.com
2. Click inside the 'Regular Expression' text box
3. Paste `(?m)\s*([A-Z][A-Z,0-9]+-[0-9]+)[^0-9]*\s*` from the keyboard (right click menu paste does not cause the issue)

### Expected Outcome
Pattern should be picked up by the site without issue

### Browser
Include browser name and version
Waterfox G6.0.7

### OS
Include OS name and version
Windows 10 Enterprise version 22H2 build 19045.3693

### Console Messages
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&family=Source+Code+Pro:wght@400;500;700&display=swap css2
Initializing bitwardenContentMessageHandler bootstrap-content-message-handler.js:229:13
Attaching message event listener. bootstrap-content-message-handler.js:217:17
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/102476/envelope/?sentry_key=5f9e813965e0433598973663dff85743&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.80.1. (Reason: CORS request did not succeed). Status code: (null).
Loading failed for the <script> with source “https://analytics.regex101.com/js/plausible.js”. regex101.com:112:116
Applied necessary polyfills (0 ms) bundle.bf8c6664774bca491cc7.js:1:418014
Begin RegEx101 v11.4.7 initialization... bundle.bf8c6664774bca491cc7.js:1:418438
Parsed initial state (0 ms) bundle.bf8c6664774bca491cc7.js:1:418585
Settings loaded (0 ms) bundle.bf8c6664774bca491cc7.js:1:419552
State management configured (0 ms) bundle.bf8c6664774bca491cc7.js:1:419608
Initialization done (1 ms) bundle.bf8c6664774bca491cc7.js:1:419804
Application rendered (1 ms) bundle.bf8c6664774bca491cc7.js:1:419913
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap utls.js:155:15
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://fonts.googleapis.com/css2?family=Roboto+Serif:opsz,wght@8..144,400;8..144,500;8..144,600;8..144,700&display=swap utls.js:155:15
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;600;700&display=swap utls.js:155:15
Successfully registered service worker bundle.bf8c6664774bca491cc7.js:1:171477
Referrer Policy: Ignoring the less restricted referrer policy “no-referrer-when-downgrade” for the cross-site request: https://srv.buysellads.com/ads/CESIEKJM.json?callback=jsonp_1705505350376_55523 vendors-bundle.d9bbafef67c3266eeefb.js:2:48683
Loading failed for the <script> with source “https://srv.buysellads.com/ads/CESIEKJM.json?callback=jsonp_1705505350376_55523”. regex101.com:1:1
Unable to load sponsor data Error: JSONP request to https://srv.buysellads.com/ads/CESIEKJM.json failed
    onerror https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    exports https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    exports https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Ce https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    promise callback*Ce https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    je https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    je https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    t https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    t https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    Ch https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    51372 https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    l https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    O https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    <anonymous> https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    <anonymous> https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
bundle.bf8c6664774bca491cc7.js:1:172345
    Ce https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    (Async: promise callback)
    Ce https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    je https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    (Async: EventListener.handleEvent)
    je https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    t https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    t https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    Ch https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    51372 https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    l https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    O https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    <anonymous> https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    <anonymous> https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/102476/envelope/?sentry_key=5f9e813965e0433598973663dff85743&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.80.1. (Reason: CORS request did not succeed). Status code: (null). 3
DOMException: Node.removeChild: The node to be removed is not a child of this node
    pl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ml https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    vl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    uu https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Fi https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    hu https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    flushSync https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    f https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    b https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    r https://regex101.com/static/vendors-sentry.1ef81c919791684673a6.chunk.js:1
    We https://regex101.com/static/vendors-sentry.1ef81c919791684673a6.chunk.js:1
    _ https://regex101.com/static/vendors-sentry.1ef81c919791684673a6.chunk.js:1
    wo https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    il https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ku https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    uu https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Fi https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ou https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    S https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    T https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    60053 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    63840 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    64448 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    73935 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    20745 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    51372 https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
vendors-sentry.1ef81c919791684673a6.chunk.js:1:250712
    _ https://regex101.com/static/vendors-sentry.1ef81c919791684673a6.chunk.js:1
    fa https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    callback https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Io https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    xl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    wl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    bl https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    uu https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Fi https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    hu https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    flushSync https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    f https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    b https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    r https://regex101.com/static/vendors-sentry.1ef81c919791684673a6.chunk.js:1
    (Async: EventListener.handleEvent)
    We https://regex101.com/static/vendors-sentry.1ef81c919791684673a6.chunk.js:1
    _ https://regex101.com/static/vendors-sentry.1ef81c919791684673a6.chunk.js:1
    wo https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    il https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ku https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    uu https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Fi https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    Su https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    ou https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    S https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    T https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    (Async: EventHandlerNonNull)
    60053 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    63840 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    64448 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    73935 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    20745 https://regex101.com/static/vendors-bundle.d9bbafef67c3266eeefb.js:2
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    51372 https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    o https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    l https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    O https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    <anonymous> https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
    <anonymous> https://regex101.com/static/bundle.bf8c6664774bca491cc7.js:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/102476/envelope/?sentry_key=5f9e813965e0433598973663dff85743&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.80.1. (Reason: CORS request did not succeed). Status code: (null). 4
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/102476/envelope/?sentry_key=5f9e813965e0433598973663dff85743&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.80.1. (Reason: CORS request did not succeed). Status code: (null). 2
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/102476/envelope/?sentry_key=5f9e813965e0433598973663dff85743&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.80.1. (Reason: CORS request did not succeed). Status code: (null).

**Comment by working-name** [comment]
Hello!

I'm seeing alot of CORS related stuff but that should not factor in, they're optional services.

That being said, I tried to replicate the issue with waterfox G6.0.7 and firefox 114.0.1 and neither of them misbehaved.

Can you please retry this in incognito mode or after disabling your addons?

**Comment by rubankopli** [comment]
I tried to replicate the issue on a different pc running firerfox 121.0.1 waterfox G 6.0.7 with a slightly different set of extensions as well and was unable to reproduce. Probably related to an extension then. Do you want to close the issue? I can always re-open it if I'm able to narrow down the extension.

**Comment by working-name** [comment]
It's possible that an extension caused it. If you do end up bumping into it again comment and we'll re-open. Thanks!
