### ISSUE TITLE
Export/Import unit tests

### ISSUE THREAD

**Issue by aquadim** [firasdib/Regex101#2213]
## Feature
I would like to see import / export functionality in unit tests tab

## Why
I love it, but i don't like that in order for my regex to save its unit tests i have to create an account and save regex

## How i imagine it
Just add another couple of button in three dots menu titled 'Import unit tests' and 'Export unit tests'. Export functionality should be in json or xml format -- what's better for you

**Comment by fgiering** [comment]
isn't this a duplicate of https://github.com/firasdib/Regex101/issues/1868 ?

**Comment by aquadim** [comment]
> isn't this a duplicate of #1868 ?

Yes, i guess it is a duplicate, thanks for pointing this out
