### ISSUE TITLE
show .NET version being used

### ISSUE THREAD

**Issue by danmoseley** [firasdib/Regex101#2215]
## Feature

For Java you show the Java version, but it doesn't show the .NET version.
![image](https://github.com/firasdib/Regex101/assets/6385855/3fd26fd2-bf0c-4cd0-841a-2dd18fea2602)

Suggestion: show something like ".NET 8" (example, but it is the latest supported) eg

![image](https://github.com/firasdib/Regex101/assets/6385855/92c4a2ac-ba86-4e04-a0d1-2f9fdb61b0a8)

**Comment by firasdib** [comment]
Good idea, will be included in the next version.
