### ISSUE TITLE
"A critical error has occurred" when positioning the cursor at a certain position (on "," symbol) in the regex

### ISSUE THREAD

**Issue by roship** [firasdib/Regex101#2216]
## Bug Description
"A critical error has occurred" when positioning the cursor at a certain position in the regex.

### Reproduction steps
"A critical error has occurred" when positioning the cursor at a certain position in the regex, exactly on "," symbol in REGEXP string.

REGEXP:
 (\d{4}-\d{2}-\d{2}_\d{2}:\d{2}:\d{2}.\d{5})\s+(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}.\d{3})\s+(\w+)\s+(\d+)\s+---\s+\[([\w-]+)\]\s+([\w.]+)\s+:\s+(((Incident|Message)\s?(create|update|delete|received):\s?(Incident|InputMessage)?\((id=([^,]+)?.*)?\))?.*)

### Browser
Chrome
Version 120.0.6099.234 (Official Build) (arm64)

### OS
macOS Sonoma Version 14.2.1 (23C71)

**Comment by working-name** [comment]
Hello @roship I downloaded the same chrome version as yours, and have grammarly and 1password extensions. I could not make it crash. Also, the screenshot regex is not the same as the pasted one, but either way, while editing it and clicking around, including on the `,` character, I did not manage to make it crash.

Would you try to reproduce it on your end, maybe without addons enabled?

**Comment by roship** [comment]
Yep, works fine without addons (incognito mode).
I should have thought about it.  My apologies for all your extra work because of this.

The cause of trouble was addon "[Burning Vocabulary](https://chromewebstore.google.com/detail/ljfjnlcnpmabfcgcmffkmgainghokdpl)"

**Comment by working-name** [comment]
Awesome, glad you found the culprit!

**Comment by roship** [comment]
I have to say your service is the best I've found.

**Comment by working-name** [comment]
Agreed, I use the app quite a bit myself. I like it. @firasdib did a great job 😄
