### ISSUE TITLE
Option for using JS XRegExp

### ISSUE THREAD

**Issue by rightaway** [firasdib/Regex101#222]
Would be nice if XRegExp for JS were supported, as it has named capturing groups and other extra functionality.

**Comment by firasdib** [comment]
XRegExp is  a very small subset of PCRE, just write your regex with that selected engine and you will get the same result.

**Comment by rightaway** [comment]
Could be useful to add a note or hover message over PCRE or Javascript options saying this so people using XRegExp could know immediately which one to use.
