### ISSUE TITLE
Rust named capture groups appear as errors

### ISSUE THREAD

**Issue by esemeniuc** [firasdib/Regex101#2220]
## Bug Description
This example fails in regex101: https://docs.rs/regex/latest/regex/#example-named-capture-groups

Docs:
https://docs.rs/regex/latest/regex/#grouping-and-flags
### Reproduction steps
 I enter `Homer (?<middle>.)\. Simpson` using the rust option, and I see the following:
<img width="537" alt="image" src="https://github.com/firasdib/Regex101/assets/3838856/22bdee66-d430-4873-902e-1597af06efe9">

### Expected Outcome
I expect to see a capture group for the middle name.

### Browser
Firefox 122.0

### OS
Arch Linux, kernel 6.6

**Comment by firasdib** [comment]
See https://github.com/firasdib/Regex101/issues/2167
