### ISSUE TITLE
Can this tool help detect redos?

### ISSUE THREAD

**Issue by zejas** [firasdib/Regex101#2221]
## Question
In the past, when I wrote the redos regular expression, it would tell me that the matching timed out, and I was used to using this tool to determine the redos. Today, when I wrote the redos, I found that it would match normally. I wonder if the tool can provide the redos detection capability.

**Comment by working-name** [comment]
As far as I know there's no assessment for DDOS potential of a regular expression. The timeout you bumped into was your computer and browser timing out matching your text given the regex. That's both reflective of your computer's performance and the regex's.

**Comment by firasdib** [comment]
It still detects catastrophic backtracking: https://regex101.com/r/dE2jet/1
