### ISSUE TITLE
Old saved regexps don't open

### ISSUE THREAD

**Issue by rrr2rrr** [firasdib/Regex101#2224]
## Bug Description
Can't open old saved regexp https://regex101.com/r/Cyz2ea/5

### Reproduction steps
1. Open https://regex101.com/r/Cyz2ea/5
2. Redirect to amin page

### Expected Outcome
1. Open regexp with examples that i have saved previously

### Browser
Chrome

### OS
MaxOS

**Comment by pjsde** [comment]
I also have this problem [https://regex101.com/r/ZwBSEy/1](https://regex101.com/r/ZwBSEy/1)

**Comment by trbtm** [comment]
Me too

**Comment by working-name** [comment]
Hello guys, is this still a problem? I'm able to access the links normally. No redirection.

**Comment by pjsde** [comment]
Now it's ok

**Comment by working-name** [comment]
Okay, glad to hear! Please feel free to comment again if that's not the case for everyone else.

**Comment by MOHAMMADALDREAI** [comment]
/(?<opening>\b(?<montage>[a-zA-Z]:[\/\\])|[\/\\][\/\\](?<!http:\/\/)(?<!https:\/\/)(?>[?.][\/\\](?:[^\/\\<>:"|?\n\r ]+[\/\\])?(?&montage)?|(?!(?&montage)))|%\w+%[\/\\]?)(?:[^\/\\<>:"|?\n\r ,'][^\/\\<>:"|?\n\r]*(?<![ ,'])[\/\\])*(?:(?=[^\/\\<>:"'|?\n\r;, ])(?:(?:[^\/\\<>:"|?\n\r;, .](?: (?=[\w\-]))?(?:\*(?!= ))?(?!(?&montage)))+)?(?:\.\w+)*)|(?:'(?&opening)(?=.*'\W|.*'$)(?:[^\/\\<>:'"|?\n\r]+(?:'(?=\w))?[\/\\]?)*')|"(?&opening)(?=.*")(?:[^\/\\<>:"|?\n\r]+[\/\\]?)*"/g

**Comment by MOHAMMADALDREAI** [comment]
** **أو__ __	Command+ B(Mac) أو Ctrl+ B(Windows/Linux)	**This is bold text**
