### ISSUE TITLE
Generate a link pointing to Regex101.com with pattern and test strings

### ISSUE THREAD

**Issue by grrrrreg** [firasdib/Regex101#2225]
First off, I want to take a second to thank all involved in this project, it has been my bible for pretty much the past decade: you built something that is crazy invaluable to a lot of users.

## tl;dr
The product I run is a Network Monitoring tool and it has a feature which scans lots of router interface entries and based on regexes on their description attributes, labels them with what their function is.
As users have to build regexes into a rules engine, they want to test them against their interfaces without creating the rule.
Knowing regex101, there's absolutely no way we can do a better job at it, so I was thinking that maybe there was an existing capability (or plan for one) to generate a link pointing to regex101 which would take the user to a regex101 tab pre-filled with:
- the regex they are testing from our UI
- a sample set of entries to test it on
So that they can simply work on it in an interface that is designed around testing regexes (regex101) and get back to rule editing once they've found the right pattern.

## side notes
I realize I'm basically asking a community project to fill one of the gaps of my commercial product and I would see how this would definitely be frowned at, but I thought maybe there were existing capabilities that I was missing that may already do what I'm after.

**Comment by firasdib** [comment]
Best way would be to use the API. Have a button on your site that says `View on regex101`, when clicked, make the necessary API calls on the backend, and give the user the link.
