### ISSUE TITLE
Replacement window eating EOF newlines

### ISSUE THREAD

**Issue by CodeMan99** [firasdib/Regex101#223]
The replacement window will strip one newline from the EOF regardless if there is a regex or not.

For example I have

```
def main():
    pass


```
(Three newlines at EOF)

and in the replacement window I see

```
def main():
    pass

```
(Two newlines at EOF).

Browser: Chrome 40.0.2214.91 (Official Build)
OS: OS X Yosemite 10.10.1

**Comment by firasdib** [comment]
Could you please give me a permalink?

**Comment by CodeMan99** [comment]
Alright: https://www.regex101.com/r/eX3sP6/1

Again, I see a newline eaten regardless if ANY regex is being used. You can leave all three input boxes blank.

**Comment by AndrioCelos** [comment]
That regular expression is actually replacing the newlines.
I do notice an oddity, though: in Chrome, the newlines are there, as you can see with the _display whitespace_ option, but you can't scroll all the way down to them. You can in Firefox, and the editor looks generally messed up in Internet Exporer.

**Comment by CodeMan99** [comment]
I know that regular expression is replacing newlines. The count in the result is still wrong.

I do see what you are saying about the *display whitespace* option though. The last line is marked as having a newline, but there is not a blank line following that (that the cursor can navigate to).

So this is a matter of navigation then? Definitely want the same behavior in the `substitution` area as that is in the `test string` area. Regardless, if I take the regex I just tested (and didn't have the *display whitespace* option on) be lead to believe the regex has a different result on __regex101__ than it did in my language of choice.

The case for the example regex is to strip out unnecessary newlines, and the result as written would have two newlines at the end of file if a replacement took place. This is critical to understand since you may not want that to occur. If you are navigating through the result with the cursor you will (incorrectly) conclude that your result will alway end with a single new.

**Comment by firasdib** [comment]
I still don't get the problem.... Looks to work just fine for me?

**Comment by CodeMan99** [comment]
1. Type some text into the first line of the `test string` window follow by any number of newlines. One is fine.
2. Count the number of newlines by moving the cursor with the left right arrow keys.
3. Move your cursor into the test string window and count the newlines with your arrow keys.

A screenshot:
![screen shot 2015-01-26 at 11 35 06 am](https://cloud.githubusercontent.com/assets/6373201/5903411/82b61b1c-a54f-11e4-90c8-ca180796dc19.png)

Note where my cursor is in the window. I cannot move my cursor to the same location in the substring window.

**Comment by firasdib** [comment]
Weird, but seems to be able to work around by just appending a newline to the end of each line. It seems to get stripped away for some reason.
