### ISSUE TITLE
Catastrophic backtrack - changing the debugger steps will crash the browser

### ISSUE THREAD

**Issue by kkmuffme** [firasdib/Regex101#2231]
### Reproduction steps

If the regex has a catastrophic backtrack error at e.g. position 180000 and you open the debugger, by default it will be from steps 1 (left input) to 1000 (right input)

If you increase the right input to e.g. 181000, it will crash the browser tab.
If you try to slowly increase the right to 10000, then left to 9999, then right to ... it will eventually crash anyway when you reach 100k, since temporarily the 89999 is changed to 9999 to change to 99999 and it will crash.

### Expected Outcome

No crash - however I don't think that's possible.
I suggest 2 things to fix this:
1) do not rerun the debugger while either of the steps input fields are active
2) if ( left input + 10000 ) < right input => do not run the debugger but display an error that the number of steps is too big and might crash the browser tab. (maybe optionally a button: "I know what I'm doing, run the debugger anyway" for people who want to crash their browsers)

### Browser

Chrome 121, Firefox 123
The same issue happens in all older browser versions too though.

### OS
Unix, Windows

**Comment by firasdib** [comment]
I am unable to reproduce this in either FF or Chrome on my Mac. Can you try in an incognito window?

**Comment by kkmuffme** [comment]
Yes, same issue there too.

Here's a screenrecording showing the reproduction on Win 11 x64, 32GB RAM (10GB unused), Firefox 123
https://github.com/firasdib/Regex101/assets/11071985/11c7a738-a150-4164-830e-ac8e0fd7d58a
(issue happens with much smaller number too, e.g. if it's at e.g. 183000)

Providing the regex and text is difficult (since it contains lots of PII), but if you really need it I can try to create an anonymized reproduction.

**Comment by firasdib** [comment]
I will need an example to work off of that can produce that many steps

**Comment by kkmuffme** [comment]
Here you go: https://regex101.com/r/E6ADtK/1
Change right input in debugger to 105000 (it will automatically take the max value) and then change left to 99999 (it will start to crash after typing 99 normally)

If you cannot reproduce, just copy & paste the lorem ipsum part at the end to make it longer then it will crash for sure.

**Comment by kkmuffme** [comment]
Just saw that when you keep the right at 1000 (default) but change the left from 1 to 999 (type it, don't paste it), it will become incredibly slow for a bit too (but won't crash)
I guess it's too greedy/fast - it tries to update on every keypress instead of waiting until I'm done writing the whole number.

EDIT: now even if you are able to e.g. put 99999 and 100351 and then play, it's just stuck - the green highlighter won't move at all.

**Comment by firasdib** [comment]
I can't make it crash by changing the ranges, but if I paste a MASSIVELY long text (like millions of characters) into the test area, and then try to debug that, it lags out massively.

Is this what you're doing...?

Edit:
By disabling the whitespace visualization it seems to completely stop lagging for me.

**Comment by kkmuffme** [comment]
>By disabling the whitespace visualization it seems to completely stop lagging for me.

Yes, this works!
It looks like it's trying to process whitespace even for text outside of (= before) the selected range, thus creating the lagging.

---

However, even then (unrelated to this setting), it's stuck at "S" forever (everything else changes, e.g. the step count,... but the highlighter is stuck at this "S")
![issue](https://github.com/firasdib/Regex101/assets/11071985/1e75a14c-208a-4bc7-8846-ca1f7f255931)

**Comment by firasdib** [comment]
It's not stuck, that's where the engine is in the pattern :-)

I will look into the performance inwhitespace visualization.

**Comment by kkmuffme** [comment]
>It's not stuck, that's where the engine is in the pattern :-)

Ok oh, clear.

**Comment by firasdib** [comment]
You should join discord or IRC to get a more detailed explanation by one of the expert as to why that is. (Hint: greedy quantifiers)

**Comment by kkmuffme** [comment]
Yeah, I realized that the second I replied

**Comment by firasdib** [comment]
I've implemented some mitigations for this in the next version, where a hard limit will be set for the amount of whitespace to be visualized.
