### ISSUE TITLE
Escape ' for Javascript code generator alternative solution

### ISSUE THREAD

**Issue by at-ng** [firasdib/Regex101#2234]
## Bug Description

Minor bug!
Code generator "alternative solution" does not escape '.

### Reproduction steps

1. Select JavaScript flavor
2. Add ' as regular expression
3. Click code generator (Javascript)
4. Note the following line
>//  const regex = new RegExp(''', 'gm')

### Expected Outcome

The line should be
> const regex = new RegExp('\\'', 'gm')

as ' needs to be escaped. Or the surrounding quotes could be replaced with something else like `` which is already used below.

### Browser
Firefox

### OS
Windows

**Comment by firasdib** [comment]
Thank you, fixed in next release
