### ISSUE TITLE
See who saved a regex/revision

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#224]
To the side of each revision, I'd love to see who made that change (when possible).

For anyone NOT logged in who creates or updates a regex, [anonymous] is shown. For registered users who create/update either their own OR others' regex, their nick would appear instead.

(revision 1) [anonymous]
(revision 2) [OnlineCop]
(revision 3) [OnlineCop]
(revision 4) [anonymous]

Due to privacy, using their nick when they save a regex should be optional (a member preference).

**Comment by firasdib** [comment]
Well, the only data I have is their email which is used to log in - nothing else. I'm not sure people would like to show their email publicly like that. A solution would be to pull their name from google/github, again, maybe not something everyone agrees to. Another solution is adding a textfield you can fill in in the account page - but meh, not sure I like that either...
