### ISSUE TITLE
Fails to load regex engine

### ISSUE THREAD

**Issue by jhshukla** [firasdib/Regex101#2244]
### Browser
Include browser name and version

### OS
Include OS name and version

firefox failes to load regex engine

![image](https://github.com/firasdib/Regex101/assets/64787821/67b5fe4d-b7cd-4515-95bb-9bbfff2896eb)

**Comment by working-name** [comment]
Hello! Which firefox version? Which OS? Have you tried it in incognito mode (or safe mode with all add-ons disabled)?

**Comment by jhshukla** [comment]
seems like this was temporary
