### ISSUE TITLE
Pattern containing Quote characters inconsistent error message

### ISSUE THREAD

**Issue by geno333** [firasdib/Regex101#2247]
## Bug Description
When selecting the C# regex type, the error messages conflict each other when entering Quote Characters in the pattern

### Reproduction steps
Type this into the regular expression pattern    
"xyz\"

### Expected Outcome
either just the Quote Character, or the Escaped Quote Character should be the correct format.
But here are the two error messages, that conflict with each other.

" An unescaped delimiter must be escaped; in most languages with a backslash (\)
\" This token has no special meaning and has thus been rendered erroneous

### Browser
Brave Browser (latest version)

### OS
Windows 11

**Comment by geno333** [comment]
I see that the recorded error text was changed from what I typed in.
Under the Steps To Reproduce the string that give conflicting error messages is

Quote  xyz  Backslash-Quote

" xyz  \ "
(without the spaces)

**Comment by working-name** [comment]
Hi @geno333 

Please see #1859 #1968 #2017 #2063 #2085 (I'm sure there's more but that's all I could find for now). Hope this helps!

Feel free to comment and I'll reopen it if I misunderstood you. Have a great one!

**Comment by geno333** [comment]
Thanks Alan!
