### ISSUE TITLE
Delimiter in URL no longer reflects in the regex box

### ISSUE THREAD

**Issue by quixrick** [firasdib/Regex101#2249]
## Bug Description
I have the following bookmarked: https://regex101.com/?delimiter=~

It used to be that when I went to regex101, the tilde would automatically populate in the regex box.  This no longer works.

### Reproduction steps
Go to https://regex101.com/?delimiter=~ and notice that the delimiter is a forward slash.

### Expected Outcome
The delimiter should be a tilde.

### Browser
Include browser name and version
Chrome v123

### OS
Include OS name and version
Windows 10

**Comment by working-name** [comment]
Hey @quixrick,

I cannot say I've monitored for changes in the way the fill-by-url works, so I'll have to trust you 😃

As far as I can tell, there's both caching and some minimum requirement thing going on. So if you load [this url](https://regex101.com/?delimiter=@&flags=&testString=&regex=xax) and then change the delimiter to something else, it won't change. However, as soon as you make another change, it'll update the delimiter.

Also, it looks like just passing `delimiter=` alone won't do anything - you need at least `regex=` passed as well.

As far as I understand this was not meant to be an official thing, so I am not sure how likely it is that it's being monitored for regressions and such.

Hope this helps!

**Comment by quixrick** [comment]
I am able to append "&regex=z" and it works.

https://regex101.com/?delimiter=~&regex=z

Good enough for me.  Thank you!
