### ISSUE TITLE
Unescaped delimiter when using /

### ISSUE THREAD

**Issue by adamjimenez** [firasdib/Regex101#225]
I was trying to match "/" in a url regex and I got the "unescaped delimiter" error even though this was deliberate. It then refuses to show matches. Maybe downgrade this to a notice or warning.

**Comment by CodeMan99** [comment]
Are you using `PCRE` or `Perl` "Flavors"? (List on the left) If you are that would be why. "/" is the begin & end delimiter for those languages so using the "/" character un-escaped would terminate your regex early.

If you select the `python` flavor you'll notice that the `/` on either side of the *regular expression* input box changes to a double quote `"` character. This allows use of `/` without escaping.

**Comment by adamjimenez** [comment]
thanks, that was it
