### ISSUE TITLE
About rergex quiz

### ISSUE THREAD

**Issue by sohaib-sadeqi** [firasdib/Regex101#2251]
Hello 
Excuse me for asking this question, I just got stick in replacing part. Actually, I don't know what should I write in substitution part.
![Screenshot 2024-03-31 232912](https://github.com/firasdib/Regex101/assets/149667925/0fc71a8b-7e4c-4a91-b9b8-47f3a7a52510)

**Comment by fleetingbytes** [comment]
@sohaib-sadeqi Your regular expression captures `i` in the context specified in your regular expression. In the substitution part you write what you want your match - or each of your matches - to be replaced with. Try `I` (capital letter I).

**Comment by working-name** [comment]
If you need further help with this please join us on IRC or Discord, whichever you like. Generally we do not post solutions for the quiz online in an effort to not spoil it for everyone else trying.
