### ISSUE TITLE
Regex Checker for Python doesn't flag bad variable names

### ISSUE THREAD

**Issue by andrewspencerbsu** [firasdib/Regex101#226]
After consulting with a friend who is a very good programmer the advice was never start a variable with a number (such as a variable name 2ndrun).

This passed your regex tester but failed silently in the python regex task I was working on.

You might want to add a flag for variables that will cause python to fail but your regex101 debugger handles with grace and style. I now know about starting with a number, not sure if there are other flaws.

Well wishes to you!

**Comment by firasdib** [comment]
Aha, I have adjusted this. Thanks for the pointer.
