### ISSUE TITLE
Font size too small

### ISSUE THREAD

**Issue by 50Death** [firasdib/Regex101#2261]
## Bug Description
Font size is too small at 4K resolution monitor
![image](https://github.com/firasdib/Regex101/assets/30155715/ed368850-1c00-4891-87fd-742816689b47)
While Other website is larger. Scale of the page is 100%
![image](https://github.com/firasdib/Regex101/assets/30155715/019b43fc-1b92-44c7-9db5-3e8dda0077f1)

### Browser
Include browser name and version
Google Chrome 123.0.6312.124 ARM64
### OS
Include OS name and version
MacOS Sonoma 14.4.1

**Comment by working-name** [comment]
Hi @50Death 

What's your DPI setting for that screen?
<img width="431" alt="image" src="https://github.com/firasdib/Regex101/assets/16505052/8b753598-5ff2-4bce-b8e9-609b56a1e227">

I looked at CSS and regex101.com has a default body font size of `16px` (1rem) which is generally the value used. nytimes for example has `0.875 rem` for body size on their front page. Google uses `14px` on average on their search engine front page. 

Are you referring to a particular part of the site or all of it?

**Comment by 50Death** [comment]
I'm referring the whole site. I regularly use this delicate site for testing but this time I found the font is quite smaller.
This is my settings. I'm using a external 4K monitor and a 16 inch macbook. On both monitor I believe the font is smaller than before.

This is 27 inch 4K external monitor setting
![image](https://github.com/firasdib/Regex101/assets/30155715/871a3102-0088-4bc5-986c-8e25a7c417b0)
This is 4k external monitor screenshot
![image](https://github.com/firasdib/Regex101/assets/30155715/5823a296-5128-4fe4-ba77-4d99d5f0a2e2)

This is 16 inch macbook built in monitor setting
![image](https://github.com/firasdib/Regex101/assets/30155715/6be5f9d8-a567-4dab-97e3-f9bef71f3ed5)
"默认" means default
This is how it looks like on build in monitor
![image](https://github.com/firasdib/Regex101/assets/30155715/b1672abc-270f-43a8-80c5-cc78aa9bf45a)

**Comment by working-name** [comment]
Hmmm, interesting. I'm not sure what to think, I don't remember there being a change in font size, but then again I've been wrong before. We'll see what Firas has to add.

**Comment by firasdib** [comment]
The font size has not changed in years.

**Comment by working-name** [comment]
It sounds like you might need to `CMD` `+` this one until you're happy with the size, @50Death. Closing for now.
