### ISSUE TITLE
Typo in quick reference token description for End of word

### ISSUE THREAD

**Issue by jock0rama** [firasdib/Regex101#2267]
## Bug Description

The current token description for **Start of word** reads:
`[[:<:]] This POSIX equivalent of the \b (word boundary) is interpreted as \b(?=\w)`

The current token description for **End of word** reads:
`[[:>:]] This POSIX equivalent of the "\b" word boundary is interpreted as \\b(?<=\\w)`

### Reproduction steps

Go to main landing page: https://regex101.com/

Navigate to the **Quick Reference** UI panel (bottom-right corner) and select **All Tokens**.

Search for "end of word" and click on the result to view more.

### Expected Outcome

The correct token description for **End of word** should read:
`[[:>:]] This POSIX equivalent of the "\b" word boundary is interpreted as \b(?<=\w)`

### Browser
Firefox 125.0.2

### OS
macOS 14.4.1

**Comment by firasdib** [comment]
Thanks, will be fixed in the next release
