### ISSUE TITLE
Infinite loop in generated Javascript

### ISSUE THREAD

**Issue by jukkahuhtamaki** [firasdib/Regex101#227]
This piece of generated Javascript seems to result into infinite loop:

    var re = /(.*)\/title\/(.*)\/(.*)\?/; 
    var str = '/browse/games/title/xbox360/a?view=detailed';
    var m;
     
    while ((m = re.exec(str)) != null) {
        if (m.index === re.lastIndex) {
            re.lastIndex++;
        }
        // View your result using the m-variable.
        // eg m[0] etc.
    }

**Comment by nhahtdh** [comment]
This should be fixed by using `if` instead of `while` for non-global regex.

**Comment by firasdib** [comment]
adjusted. Will be pushed live soon.
