### ISSUE TITLE
Incorrect hint for Golang `\w`

### ISSUE THREAD

**Issue by wxiaoguang** [firasdib/Regex101#2271]
## Bug Description

regexp101 says: `Golang \w match any word character in any script (equivalent to [\p{L}\p{N}_])`

But Golang document says:  `\w : word characters (== [0-9A-Za-z_])` https://pkg.go.dev/regexp/syntax

### Reproduction steps

![image](https://github.com/firasdib/Regex101/assets/2114189/e4a0d694-dbcd-4fcf-9787-b62d13380ad3)

```golang
	r := regexp.MustCompile(`\p{L}`)
	println(r.MatchString("α")) // true
	r = regexp.MustCompile(`\w`)
	println(r.MatchString("α")) // false
```

So the explanation `equivalent to [\p{L}\p{N}_]` is not right.

**Comment by firasdib** [comment]
Thanks, will be fixed in the next release
