### ISSUE TITLE
Regex Quizz Task 11 Validate Floating Point 

### ISSUE THREAD

**Issue by Heinz051** [firasdib/Regex101#2273]
## Bug Description 
Does‘nt accept \d or [0-9] as decimal digits.
![IMG_1594](https://github.com/firasdib/Regex101/assets/168349913/ad3b20fc-a635-415c-aa1c-862741ec83c9)

### Browser
Include browser name and version
 Safari

### OS
Include OS name and version: iPadOS 17.4.1 (21E236)

**Comment by working-name** [comment]
Hello @Heinz051,

That is not an error, it's a requirement for that task. Keep playing with it, I'm sure you'll get it! 👍 

Also, please do not post quiz solutions online so as to not spoil it for others.
