### ISSUE TITLE
Support Golang named caputures with same name

### ISSUE THREAD

**Issue by Roemer** [firasdib/Regex101#2278]
## Feature

Go supports named captures with the same name (see on https://pkg.go.dev/regexp) but using such a regex (like `(?P<word>.*)\s+(?P<word>.*)`) shows an error: `A subpattern name must be unique`. Would be great if those would be supported in Regex101 as well.

**Comment by firasdib** [comment]
Thanks, will be fixed in the next version

**Comment by Roemer** [comment]
Awesome, thanks!

**Comment by 15051975** [comment]
ARTH
Colours





Colors of the Earth Element are yellow, brown, taupe, beige.




YANG EARTH ELEMENT

Primary Stars: Hades, Demeter
Organ: Stomach
Colours: Light Brown, Yellow, Tan


YIN EARTH ELEMENT

Primary Star: Zeus
Organ: Brain
Colours: Brown, Beige, Khaki
