### ISSUE TITLE
Select .Net 7 (C#) but not working, throw engine error

### ISSUE THREAD

**Issue by SeriaWei** [firasdib/Regex101#2279]
![image](https://github.com/firasdib/Regex101/assets/6006218/e26a9f96-3bcf-4851-b12c-4a63890baaff)

**Comment by working-name** [comment]
Hi @SeriaWei,

Can you please try that in an incognito session or a browser without addons?
Also, open dev tools and go to the network tab before you load the page. That way you can see what gets blocked and potentially by what.

Also it would be very useful to know which OS and browser you're using so I can try to reproduce it. So far, on windows, Brave, with a gazillion add-ons and ad blockers, it works.

**Comment by beligg** [comment]
I sometimes encounter the same problem, but it can be solved by reloading the page.
This is the console log:

bundle.506f496942c824f31ed9.js:1 Applied necessary polyfills (0 ms)
bundle.506f496942c824f31ed9.js:1 Begin RegEx101 v11.7.0 initialization...
bundle.506f496942c824f31ed9.js:1 Parsed initial state (0 ms)
bundle.506f496942c824f31ed9.js:1 Settings loaded (0 ms)
bundle.506f496942c824f31ed9.js:1 State management configured (2 ms)
bundle.506f496942c824f31ed9.js:1 Initialization done (3 ms)
bundle.506f496942c824f31ed9.js:1 Application rendered (0 ms)
bundle.506f496942c824f31ed9.js:1 Successfully registered service worker
bundle.506f496942c824f31ed9.js:1 Error: Unable to load worker, timeout after 10s
    at bundle.506f496942c824f31ed9.js:1:262973
_runWorker @ bundle.506f496942c824f31ed9.js:1
await in _runWorker (async)
(anonymous) @ bundle.506f496942c824f31ed9.js:1
setTimeout (async)
runWorker @ bundle.506f496942c824f31ed9.js:1
runMatch @ bundle.506f496942c824f31ed9.js:1
(anonymous) @ bundle.506f496942c824f31ed9.js:1
rl @ vendors-bundle.34d914cfcb77ca820fbb.js:2
ku @ vendors-bundle.34d914cfcb77ca820fbb.js:2
(anonymous) @ vendors-bundle.34d914cfcb77ca820fbb.js:2
xu @ vendors-bundle.34d914cfcb77ca820fbb.js:2
lu @ vendors-bundle.34d914cfcb77ca820fbb.js:2
ji @ vendors-bundle.34d914cfcb77ca820fbb.js:2
(anonymous) @ vendors-bundle.34d914cfcb77ca820fbb.js:2

**Comment by working-name** [comment]
> bundle.506f496942c824f31ed9.js:1 Error: Unable to load worker, timeout after 10s

This is making me think network related. I can think of 2 things:
1. Server had network hiccup.
2. Your browser is somehow blocking the request.

You might be able to find out more if the network tab happens to be open before loading the page... 🙃

**Comment by beligg** [comment]
This is the network har, when the problem occured:
[regex101.com.zip](https://github.com/user-attachments/files/16039458/regex101.com.zip)

**Comment by beligg** [comment]
Browser is Chrome 126.0.6478.127 in incognito mode.
OS is Windows 10 pro 22H2 19045.4529

**Comment by beligg** [comment]
This is the har when the page has been reloaded several times and everything is ok.
[regex101.com 2.zip](https://github.com/user-attachments/files/16039480/regex101.com.2.zip)
This time, the resources were loaded mostly from cached sources and much faster

**Comment by working-name** [comment]
> This is the network har, when the problem occured: [regex101.com.zip](https://github.com/user-attachments/files/16039458/regex101.com.zip)

Thank you, did you manage to see any red lines (below is mine from brave)?
![redline](https://github.com/firasdib/Regex101/assets/16505052/42a8deae-a849-491a-9314-d47153bf3d50)

If you do, try to figure out the reason behind why that connection was blocked or if it timed out.

The `har` files only contain connections that have happened, it won't export those that got blocked. A fresh load of regex101.com in an incognito mode, with a switch to .NET and `a` in both regex and test string should yield a `har` file that's about 26.8 MB in size.

**Comment by beligg** [comment]
No requests were blocked
![snap1](https://github.com/firasdib/Regex101/assets/109658726/153f1c14-57fb-4ea2-8aa5-b9c32233f090)

**Comment by working-name** [comment]
Quite unusual. There's gotta be something blocking the connection, otherwise the 10s timeout would mean trash server. Tried another browser? What about your phone, with wifi off (use cell data)?

**Comment by wwwalker** [comment]
I get engine failed to initialise when I entered string match. In Web Developer Tools, worker was not loading.
It then worked on private window.
I deleted cookie and cache for regex101.com but it still happened in normal tab.
Later it eventually worked on normal tab.
Browser: Firefox 128.0.3 (64-bit) on Windows 11 Home on NBN Wifi (Australia) (broadband on desktop).

**Comment by woldaker** [comment]
I am getting the same thing. Incognito or otherwise, the result is the same. I first clicked on .NET to change the flavor. That went fine. But then, as soon as I enter a regex pattern, I get this:
![image](https://github.com/user-attachments/assets/2db54576-736d-4f14-89aa-c4044d6abb52)

and in the console:
![image](https://github.com/user-attachments/assets/1d5391d6-01ec-41ed-902e-fd5e1df65e5b)

**Comment by firasdib** [comment]
Looks like you have something blocking the requests. Firewall? Content filter? Maybe some security filter in your browser?
