### ISSUE TITLE
Changing the interface language has no effect

### ISSUE THREAD

**Issue by StrollStars** [firasdib/Regex101#2284]
## Bug Description
Changing the web interface language has no effect.

### Reproduction steps
1. Click on the settings icon
2. Click on the drop-down language menu
3. No change occurs no matter which language is selected

### Expected Outcome
The web interface language will change

### Browser
Chrome 109.0.5414.75
Edge 125.0.2535.51

### OS
Windows 7
Windows 10

**Comment by huzhiming** [comment]
me too, I have the same problem.

**Comment by LinXP** [comment]
I have the same problem.

**Comment by firasdib** [comment]
Will be fixed in the new version
