### ISSUE TITLE
Bug when trying to sign in

### ISSUE THREAD

**Issue by Klrfl** [firasdib/Regex101#2285]
## Bug Description
I wanted to sign in to play the quiz, but after choosing the Github provider, this error popped up instead in the URL:

`https://regex101.com/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider`

### Reproduction steps
Go to [the quiz page](https://regex101.com/quiz/) Then click the sign in link. Choose Google or Github as provider.

### Expected Outcome
You should get the same error message in the URL as I did above.

### Browser
Firefox Version 126.0

### OS
Windows 11 Home

**Comment by json-bateman** [comment]
I can't log in but am not getting that url, instead when i try to do OAuth on google, the local storage sets like 4 variables for a second, then disappear when the page reloads. 

### Browser
Google Chrome: Version 125.0.6422.78 (Official Build) (arm64)

### OS
MacOS Sonoma 14.3.1

**Comment by younforet** [comment]
Same issue with both providers and URL https://regex101.com/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider

### Browser
Google Chrome: Version 125.0.6422.112 (Official Build) (arm64)

### OS
Windows 11 Pro 22631.3593

**Comment by NolanDeveloper** [comment]
I'm having the same issue.

**Comment by working-name** [comment]
Hello! Thank you for reporting this. I just tried github as well, and while I don't get an error, I am still not logged in after the redirection.

**Comment by NolanDeveloper** [comment]
@working-name I'm able to see error in the address line. I don't see any errors anywhere else either.

**Comment by firasdib** [comment]
Sorry, should be fixed.

**Comment by scrutinizer11** [comment]
I'm having the same problem. The regex101 site works to the full extent of its capabilities, but it won't sign me into my GitHub account. I click on "Sign-In", provide the correct credentials and am brought back to where I was. 

**Browser**: Firefox 78
**OS**: macOS 10.9 "Mavericks"

**Comment by working-name** [comment]
Please see #2307
