### ISSUE TITLE
Default 3-column view may look bizarre on narrow screen

### ISSUE THREAD

**Issue by MasterInQuestion** [firasdib/Regex101#2287]
https://regex101.com/?regex=(?:0|false|F(?:alse|ALSE)?)(*:0)|(?:1|true|T(?:rue|RUE)?)(*:1)&flags
<img src="https://github.com/MasterInQuestion/attach/raw/main/firasdib/Regex101/2287/3-column.webp" />
    Caused by recent new default:
    Left sidebar auto-collapse Breakpoint 1080px maybe underestimated: try 1440px?

**Comment by firasdib** [comment]
The size hasnt changed, I just made them available for you to change. What is the exact problem though? Looks fine for me. Vänliga hälsningar / Best regards,Firas DibOn 30 May 2024, at 20:43, MasterInQuestion ***@***.***> wrote:﻿
    https://regex101.com/?regex=(?:0|false|F(?:alse|ALSE)?)(*:0)|(?:1|true|T(?:rue|RUE)?)(*:1)&flags

    Caused by recent new default:
    Left sidebar auto-collapse Breakpoint 1080px maybe underestimated: try 1440px?

**Comment by MasterInQuestion** [comment]
https://github.com/MasterInQuestion/attach/raw/main/firasdib/Regex101/2287/3-column.webp
    For me originally the left sidebar was default hidden: now would display.

**Comment by firasdib** [comment]
Does the sidebar hide if you manually resize the window a few pixels?I don’t think anything changed here, but I will investigate this weekend. Vänliga hälsningar / Best regards,Firas DibOn 30 May 2024, at 22:38, MasterInQuestion ***@***.***> wrote:﻿
    https://github.com/MasterInQuestion/attach/raw/main/firasdib/Regex101/2287/3-column.webp
    For me originally the left sidebar was default hidden: now would display.

**Comment by MasterInQuestion** [comment]
Doesn't automatically hide if I minorly adapt the viewport size accordingly:
    Though indeed doesn't display when reloaded with < 1080px.
    And would auto-display after dynamically changing to >= 1080px.
    .
    But no vice versa: unless I change the viewport size greatly.
    (to the extent that causes both sidebars hidden)

    Library issue perhaps.

**Comment by firasdib** [comment]
I am unable to replicate this issue. Please feel free to reopen if the issue persists.

**Comment by MasterInQuestion** [comment]
My viewport width is exactly 1080px.
    And it seems to require auth to reopen..?

**Comment by firasdib** [comment]
Heh, I did find a bug just now. Your issue will hopefully go away in the next version.

As for auth, I don't know what you're talking about.

**Comment by MasterInQuestion** [comment]
Another word: "permission".
    Not random users may reopen closed issues, in GitHub's default. (I believe?)

**Comment by MasterInQuestion** [comment]
Implementation note:
    Note the suggested change is "> 1440px", not ">=".
    (the difference matters)
