### ISSUE TITLE
Golang replace string edge case

### ISSUE THREAD

**Issue by FrancescoLuzzi** [firasdib/Regex101#2289]
## Bug Description

Can't replace a string with a new string containing a `$` inside it.
The golang docs on [regexp.ReplaceAllString](https://pkg.go.dev/regexp#Regexp.ReplaceAllString) and [regexp.Expand](https://pkg.go.dev/regexp#Regexp.Expand) states that in this case you should use `$$`

### Reproduction steps

- select `golang` flavour
- select `substitution` function
- enter regular expression to match and replace
- enter a substitution string like `$$test`

### Expected Outcome

The substitution pattern should not error and return the modified string

_Pretty sure this is a logic error, if you still need browser and os infos let me know_

**Comment by working-name** [comment]
Go example run to recreate the edge case described: https://go.dev/play/p/TveUE4pFo6L?v=goprev

**Comment by FrancescoLuzzi** [comment]
Also this one https://go.dev/play/p/tv5Q7FFkt0v

In a nutshell, when you want to escape the capture group placeholders in a replaceString,
instead of writing something like "\\$" you'll need to write "$$"

**Comment by firasdib** [comment]
Will be fixed in the next release, thank you!
