### ISSUE TITLE
Cannot Match \x

### ISSUE THREAD

**Issue by iamfreeman** [firasdib/Regex101#229]
(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\x{00a1}-\x{ffff}0-9]-*)*[a-z\x{00a1}-\x{ffff}0-9]+)(?:\.(?:[a-z\x{00a1}-\x{ffff}0-9]-*)*[a-z\x{00a1}-\x{ffff}0-9]+)*(?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,})))(?::\d{2,5})?(?:/\S*)?

\x here cannot be matched

**Comment by nhahtdh** [comment]
Please use 3 backticks ```` ``` ```` to surround your regex.

Anyway, this is the problem of regex101 using UTF-16 version of the PCRE library instead of UTF-8 version, which is used by PHP. If you fail to get the code to work correctly in PHP, you probably need to use `u` flag.

**Comment by firasdib** [comment]
Are you trying to say your regex doesnt match in the tester? If so, give me a permalink to investigate.
