### ISSUE TITLE
Unable to initialize the regex engine! 

### ISSUE THREAD

**Issue by mjmhall1** [firasdib/Regex101#2290]
## Bug Description

I get the following message in the Match Information window when I try to use .NET (7.0) C#:

Please try to reload the web page. If the issue persists, please open an issue here: https://github.com/firasdib/Regex101/issues
### Reproduction steps

Try any RegEx with the .NET 7.0 (C#) Flavor.

### Browser
Include browser name and version
Chrome Version 125.0.6422.141
### OS
Include OS name and version
Windows 10 Enterprise 10.1.19045

**Comment by working-name** [comment]
Hi @mjmhall1,

Any other errors? Can you please try this in an incognito window or another browser that doesn't have addons?
Take a look at the networking tab before you switch to .NET and see what happens. Generally WASM gets downloaded as needed. Something may be blocking it.

**Comment by mjmhall1** [comment]
Hi Alan

Thanks for the reply. You are correct; the problem is caused by Zscaler blocking WASM.   

![image](https://github.com/firasdib/Regex101/assets/83765781/079a0924-9997-480a-ae33-f35820b1eb40)
