### ISSUE TITLE
Python replacement string doesn't use dollar syntax $1

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#230]
`$1` doesn't have any special meaning in the replacement string in Python `re`

So the following test https://regex101.com/r/fA0uY6/1 (search for `(x)` and replace with `$1`) should result in a bunch of `$1` in the resulting string.

Output from Python 2.7.8 to show the expected result.

```
Python 2.7.8 (default, Jul 25 2014, 14:04:36)
[GCC 4.8.3] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.sub('(x)', '$1', 'xxxxxxxxx')
'$1$1$1$1$1$1$1$1$1'
>>>
```

**Comment by firasdib** [comment]
I see. I manually implemented a universal replacement syntax for PCRE/Python, but I could modify it for the case of Python I suppose.

**Comment by hankthetank** [comment]
Should use \1 instead as stated here. https://docs.python.org/2/library/re.html#re.sub

**Comment by firasdib** [comment]
Adjusted. Will be pushed live soon.

**Comment by earthelf** [comment]
still not fixed...

**Comment by firasdib** [comment]
@earthelf works fine for me.

**Comment by earthelf** [comment]
@firasdib  I checked https://regex101.com/r/fA0uY6/1 once more.

Issues1
'$1' as substitution still not works as python does, latter take $1 as literal

Issue2
There are both "Contents in capture group 1:$1" and "Contents in capture group 1:\1" , only latter supported by python
