### ISSUE TITLE
Cannot login using Github or Google accounts

### ISSUE THREAD

**Issue by russ749** [firasdib/Regex101#2307]
## Bug Description
Redirected to google sign in / github sign in, sign in successfully, brought back to regex101 website, no acknowledgement of sign in. 

### Reproduction steps
Select the quiz tab, click the link to sign in using google or github, sign in, return to regex101, and click quiz tab.

### Expected Outcome
Logged in, able to take quiz

### Browser
Include browser name and version
Google Chrome 126.0.6478.114 
### OS
Include OS name and version
Windows 11 Pro Version 23H2, OS Build 22631.3737

**Comment by pjsde** [comment]
It's happening to me too. I can't login with github

**Comment by turtlefast** [comment]
Similar sign-in failure using GH option.  First time login (I think?).

Browser
Mozilla Firefox 127.0 (64-bit)

OS
Windows 11 Pro Version 21H2, OS Build 22000.2538

**Comment by firasdib** [comment]
I will fix this next week. Sorry everybodyVänliga hälsningar / Best regards,Firas DibOn 1 Jul 2024, at 17:05, Karl ***@***.***> wrote:﻿
Similar sign-in failure using GH option.  First time login (I think?).
Browser
Mozilla Firefox 127.0 (64-bit)
OS
Windows 11 Pro Version 21H2, OS Build 22000.2538

**Comment by turtlefast** [comment]
No problem.  Thanks for the update... and for this incredible tool!  🙏

**Comment by russ749** [comment]
No worries! Thanks for the quick responses.

**Comment by toaoJan** [comment]
Same Problem across multible browsers :) Hope you get it fixed <3

**Comment by kingletit** [comment]
I have same problem today: July 26 2024

**Comment by unicornware** [comment]
is this still an issue for anyone else? i'm unable to sign in with github and need to access some expressions i saved. re-authorizing on the github end didn't work either.

**Comment by working-name** [comment]
@unicornware You're right, it is happening again.

**Comment by firasdib** [comment]
Thank you guys, this is a "known" issue. I have a fix coming, but it'll take a while longer. Until then, please just ping me if it re-occurs!
