### ISSUE TITLE
Several Polish characters cannot be input into regex field

### ISSUE THREAD

**Issue by mmkay** [firasdib/Regex101#231]
Polish national characters are input by pressing right alt + character. For example, right alt + s = ś , right alt + z = ż.

Entering right alt + z in regex field with any text available results in 'undo' action, right alt + s results in pop-up with unique link to tested regex.

Probably related to similar issue on medium.com - https://medium.com/medium-eng/the-curious-case-of-disappearing-polish-s-fa398313d4df

**Comment by firasdib** [comment]
I see.

If it triggers undo/save, that means your 'alt'-key is triggering the `META`-key event in your browser. Which browser are you using? Have you tried with another?

**Comment by mmkay** [comment]
Checked on Firefox 35.0.1, Chrome 40.0.2214.94, IE11, my system is Windows 8.1. The same issue occurs on each of the browsers.

**Comment by firasdib** [comment]
Then it must be that Windows triggers `META` with the `alt`-key. I will have to throw up a test for you to run to make sure this is what happens. No time right now though, feel free to look it up on your own if you have the time.

**Comment by firasdib** [comment]
I have tried a small fix for this, I push it live to see if it works. If you have time to pop by IRC to test it out for me I would really appreciate it.

**Comment by firasdib** [comment]
This will have to be retested for v2.

**Comment by firasdib** [comment]
@mmkay Can you check if you can insert those characters in here: https://codemirror.net/ ?

**Comment by mmkay** [comment]
@firasdib On codemirror all Polish characters can be entered. On regex101 now, there are two combinations that fail: alt gr + s (ś character) and alt gr + z (ż character). It is possible to paste them manually from outside regex101.

**Comment by firasdib** [comment]
@mmkay Then it will be supported on version2, thanks for verifying for me!
