### ISSUE TITLE
Golang does not support (?<name>re) added in go1.22

### ISSUE THREAD

**Issue by aletheia7** [firasdib/Regex101#2311]
## Bug Description

Golang added ```(?<name>re) ``` syntax entitled  "named & numbered capturing group (submatch)" in go1.22. This syntax is not supported and produces the error, "? The preceding token is not quantifiable". See go doc [regex/syntax](https://pkg.go.dev/regexp/syntax@go1.22)

### Reproduction steps

Use ```(?<name>abc)``` with a Test String of ```abc```

See: [Saved Regex101](https://regex101.com/r/v0lZzN/1)

### Expected Outcome

Works like [```(?<name>abc) = (?P<name>abc)```](https://regex101.com/r/ubIYS8/1)

Probably just need to upgrade go version to 1.22+ to fix.

### Browser
Firefox 127.0.2

### OS
Linux Debian Testing

**Comment by firasdib** [comment]
I've been trying to re-compile the `re2` library to add this feature, but I have been unable to do so ever since the change of `absail`. I use emscripten to compile it, but I can't get it to work anymore, and I'm quite frankly at a loss. Would you have any idea how to do it?

**Comment by aletheia7** [comment]
Would using https://github.com/google/re2-wasm/ provided by google work instead of compiling re2 with abseil-cpp?

**Comment by firasdib** [comment]
That would likely be equally old and not support the syntax. Plus, last time I tried one of the precompiled libraries, they were exceptionally slow.

**Comment by aletheia7** [comment]
I see. I looked at the dates of re2-wasm and it appears it may be too old. I have not used abseil-cpp.

**Comment by firasdib** [comment]
I've managed to get this working, an updated version will be included in the next release :)
