### ISSUE TITLE
 After clicking on the Regex Flavour Guide, then click outside the dialog box redirects to Critical error occured

### ISSUE THREAD

**Issue by srinivasskc** [firasdib/Regex101#2313]
## Bug Description
 After clicking on the Regex Flavour Guide, then click outside the dialog box redirects to Critical error occured

### Reproduction steps
Open https://regex101.com/ 
Then click on Regex Flavour Guide
Then click outside the dialog box

Actual Result: 
A critical error has occurred
If possible, open up an issue with as many details as you can here: https://github.com/firasdib/Regex101/issues.

It might be a good idea to take a screen shot of your dev console window, if you know how to open it.

### Expected Outcome
It should not redirect to error page.

### Browser
Chrome Browser
version: 126.0.6478.127

### OS
Mac OS:
Version: Sonama 14.5

<img width="2048" alt="Screenshot 2024-07-17 at 7 16 29 PM" src="https://github.com/user-attachments/assets/bee16197-a4f0-4c71-a52e-8fcab47b0ad6">

**Comment by working-name** [comment]
Hey @srinivasskc I cannot reproduce this yet. Anything else you got going on in the browser? Addons? User script/css injection? Have you tried it in incognito mode where hopefully all addons are disabled?

**Comment by srinivasskc** [comment]
Today, I have tried multiple times. This is not reproducible.

**Comment by working-name** [comment]
Understood. Will close for now, please let me know if you bump into it again!
