### ISSUE TITLE
Test 58/93 failing even though its correct

### ISSUE THREAD

**Issue by yash-chandna** [firasdib/Regex101#2314]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Task 11: Validate Floating Point Numbers (optional)

### Bug Description

Test 58/93: A leading dot or comma must be allowed.
This is being validated but still not being accepted

### Reproduction steps

https://regex101.com/r/X53ADx/1 Test 58 is failing at this but it shouldn't

### Expected Outcome
This test should pass

### Browser
Chrome v126.0.6478.128 

### OS
Win 11 Pro Version	10.0.22631 Build 22631

**Comment by firasdib** [comment]
Hi, the test is actually correct, but the message is a bit misleading. I have adjusted it and will push it with the next release.
