### ISSUE TITLE
Unit Tests: Allow Match of multiple Capture Groups

### ISSUE THREAD

**Issue by dougthor42** [firasdib/Regex101#232]
Unless I'm mistaken, it's currently impossible to use the "unit tests" page to assert on a capture group other than group 1.

I think it would be nice if the user could choose which capture group should be matched against.

So you could have your dropdowns be:
assert that <kbd>Capture Group</kbd> <kbd>1</kbd> <kbd>equals</kbd> [user string].

Of course, if the user wanted to match capture group 4 and only 2 were found, that would be a failing test.

EDIT: Accidentally hit post rather than preview...

**Comment by firasdib** [comment]
I think you're mistaken.

Seems to work for me:
![screen shot 2015-02-09 at 15 11 31](https://cloud.githubusercontent.com/assets/1335165/6107776/fb558016-b06d-11e4-9fe7-0a0dd6cb2409.png)

**Comment by dougthor42** [comment]
Hmm...  might be an issue with the RegEx I'm using then:

Try the following:
``(?:\(|,)(?:\s*)(?P<kwparam>[_a-zA-Z0-9]+)(?:\s*=(?!=))``

with a test case of:
``func(a=1, b=2, c=3)``

The main page successfully matches `a`, `b`, and `c`. But when I try the unittest, there's only one option for capture group.

Here are the images:
First, successfully finding the three captures:
![image](https://cloud.githubusercontent.com/assets/5386897/6110894/be0a5288-b039-11e4-993c-63d9e01ae362.png)

Second, only one option for capture group when UnitTesting:
![image](https://cloud.githubusercontent.com/assets/5386897/6110917/e5ad5984-b039-11e4-9add-c50d457a5158.png)

Sorry, I should have put the test case in the original report. My bad :-P

**Comment by firasdib** [comment]
There is only one capture group in that regex.. Perhaps I should find a way to show the name, instead of just `1`.

**Comment by dougthor42** [comment]
There's only 1 capture group, but it captures `n` times. I'd like the UnitTest to be able to check that all 3 results are present.

So is that functionality currently present? I would like to set my UnitTest result to either `['a', 'b', 'c']` or be able to say:
`CaptureGroup1Result1='a'`
`CaptureGroup1Result2='b'`
`CaputreGroup1Result3='c'`

If it's not present, then that's what this issue is for :-D. I can make a new Issue with a better, clearer comment if desired.

**Comment by firasdib** [comment]
You can set up n individual cases if you want that matches each one of those cases.

**Comment by dougthor42** [comment]
That's what I was afraid of.

OK, thanks.

**Comment by firasdib** [comment]
No problem!

Mvh Firas
