### ISSUE TITLE
What version of PCRE2 are you using?

### ISSUE THREAD

**Issue by oleedd** [firasdib/Regex101#2321]
The thing is I found a bug in PCRE2 on your site. Maybe it was fixed in a later version.

**Comment by firasdib** [comment]
What is the bug you have found?

**Comment by oleedd** [comment]
It is about match results. It is very unlikely that it is on your side. What PCRE2 version do you use? I can't find it on the site.

**Comment by oleedd** [comment]
It is about some match result. It is very unlikely that it is on your side. What PCRE2 version do you use? I can't find it on the site.
In releases, they often say about bug-fixes. It is probably already fixed. And I don't want to report it if your version is not 10.44 (last).

**Comment by firasdib** [comment]
I am using 10.42, I will ensure to include version flavor guide in the future.

**Comment by oleedd** [comment]
@firasdib
Did you update to 10.42 recently? I already don't see that bug.

**Comment by oleedd** [comment]
@firasdib
Did you update to 10.42 after opening this issue? I already don't see that bug.

**Comment by firasdib** [comment]
No, been the same for quite some time. Vänliga hälsningar / Best regards,Firas DibOn 2 Sep 2024, at 16:42, oleedd ***@***.***> wrote:﻿
@firasdib
Did you update to 10.42 after opening this issue? I already don't see that bug.

**Comment by oleedd** [comment]
@firasdib
No, I still see. This version has a bug. See: https://github.com/PCRE2Project/pcre2/issues/456
Updating to 10.44 is required.
