### ISSUE TITLE
SED code gen Substitution translation

### ISSUE THREAD

**Issue by thisRedH** [firasdib/Regex101#2326]
## Feature
The code generator for SED should translate `$1` Substitution to `\1` as that's what SED uses.

regex: `/(bar)(foo)/g`
test string: `barfoo`
substitution: `$2 $1`

Currently: `sed -E 's/(bar)(foo)/$2 $1/g;t' <<< "barfoo"`
Expected: `sed -E 's/(bar)(foo)/\2 \1/g;t' <<< "barfoo"`

**Comment by working-name** [comment]
Hi @thisRedH,

Just FYI, the code generator just gives you an example on how to implement and escape the regex in the target language. It doesn't actually touch your regex outside of that. So if you placed `$1` in substitution or use a feature not available in sed, it won't scream at you, it'll just treat it the same.

Probably not what you wanted to hear :)

See #1606, #1634, #1795, #2049,
