### ISSUE TITLE
I can't login. After entering the credentials I'm thrown to the login page 

### ISSUE THREAD

**Issue by expressvpn3711** [firasdib/Regex101#2328]
## Quiz Bug

DO NOT POST QUIZ SOLUTIONS!

### Task
Please write both task name and number.

### Expected Outcome
If there are any test cases you think need to be added, you can write that here as well.

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by working-name** [comment]
Are you able to recreate this? I just tried and it worked, I was able to log in.

**Comment by hesclebo** [comment]
If I try to log in via github I get no direct error but the URL has the following string attached:
https://regex101.com/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider
This is a fresh github account, so maybe that is the problem? Anyway to remedy this?

**Comment by hesclebo** [comment]
> If I try to log in via github I get no direct error but the URL has the following string attached: https://regex101.com/?error=Grant%3A%20missing%20session%20or%20misconfigured%20provider This is a fresh github account, so maybe that is the problem? Anyway to remedy this?

Someone helped me out in the IRC Chat by rebooting the website? It immediatly worked afterwards.
