### ISSUE TITLE
A feature to apply the regex on the string x times, then do the average match time

### ISSUE THREAD

**Issue by Palloxin** [firasdib/Regex101#2329]
## Feature
I would like a way to apply the regex x times and then get the average match time, for test purposes.

Would this feature be feasible?

To cope I currently make the string gigantic, and then add and delete continuosly a space in the regex to trigger a change of the time used to match the regex. When i compare two regexes performance i usually watch visually the one that gives lower match times more often.
I usually multiply the string x100 or x1000 times to make the changes more evident. It's bothersome

**Comment by Palloxin** [comment]
Feel free to edit the title with a shorter and clearer one.

**Comment by slevithan** [comment]
Using the running time for benchmarking in that way is probably a bad idea, and will mislead you in many ways. Regex performance is dependent on many things, and is highly dependent on the specific target strings a regex is matched against. If you want to compare the performance of two regexes it is probably better to compare the number of steps, which regex101 shows for the PCRE/PCRE2 flavors. The steps don't need to be multiplied 1000x to understand the difference, and they are less susceptible to being misleading.

**Comment by Palloxin** [comment]
1. I prefer it
2. Javascript, Java 8, Golang, .NET 7.0 and Rust do **not** have "steps", only match time.

Either this feature or I do it manually as I described above.
It's just more comfortable with this feature.

**Comment by firasdib** [comment]
I'm going to add a basic benchmarking feature to the website, we'll see how useful it is. Coming in next version.

Be aware that what @slevithan said is correct. I mostly imagine this will be used as a fun way of measuring performance without worrying too much about engine warmup etc.

**Comment by Palloxin** [comment]
@firasdib Take this as example:
https://regex101.com/r/OqRlHL/1

replace ``(?=<br>\s*<br>)`` with ``(?:<br>\s*<br>)`` on both Javascript and PCRE2 flavors

PCRE2 steps:
``(?=<br>\s*<br>)``: 588,000 steps
``(?:<br>\s*<br>)``: 450,000 steps

PCRE2 says there are less steps with ``(?:<br>\s*<br>)`` but with Javascript the match time showed is clearly slower with ``(?:<br>\s*<br>)`` if you do a quick test (34ms vs 52ms)


Another thing:
PCRE2 doesnt add steps for the addition of non-capturing groups ``(?:``, but on Javascript having them gives a clear match-time speed boost

**Comment by firasdib** [comment]
You can play with it when the new feature releases. On my machine, your regex has an average execution time of 27ms for PCRE2, and 26ms for JavaScript. What you're seeing is probably just noise :)

**Comment by Palloxin** [comment]
What i was saying is that "steps" dont mean much across other flavours
EDIT: I got it now:
34ms: (?= thing - javascript
52ms: (?: thing - javascript

**Comment by slevithan** [comment]
> Another thing: PCRE2 doesnt add steps for the addition of non-capturing groups `(?:`, but on Javascript having them gives a clear match-time speed boost
> [...] What i was saying is that "steps" dont mean much across other flavours

Steps count the number of match/backtracking steps per match (one or more per token, depending on the target string). Although JavaScript and most other implementations don't offer a API for reporting them, this concept holds regardless of flavor, and it's unaffected by capturing groups. Backtracking is not the only thing that affects performance, but it is generally the main concept people should be concerned about when thinking about comparative optimization when using a backtracking regex engine.

Indeed, capturing groups generally add a small perf hit because recording and keeping capturing groups up to date takes some small amount of time, but this is unrelated to backtracking steps except in that backtracking can of course cause the value remembered for a capturing group to be updated. Using JS's `/d` flag to track capturing group start and end indices will also incur a small perf penalty for similar reasons, and again this is not related to steps.

**Comment by Palloxin** [comment]
@firasdib What about adding also a min & max match time measured in the benchmark session?

**Comment by firasdib** [comment]
@Palloxin Min/max will probably give too much false positives, i.e., you'll see wildly fluctuating values that will rather showcase your system doing something in the background than give you any insight into the regex.

This is already, as @slevithan has pointed out, a wary road to go down. The feature will be added as an initial test only.

**Comment by Palloxin** [comment]
Alright, I though the regex execution was well isolated from the browser other activities.
Well, even with a little interference, the average time should show differences between two regexes.
Btw, I understand the max value can fluctuate wildly, but what about the min match time? From my "manual" experience it was a good reference point somehow.
