### ISSUE TITLE
Un-Format regex

### ISSUE THREAD

**Issue by Enissay** [firasdib/Regex101#233]
While building a regex the `format regex` option can be usefull. But, it would be great to add the opposit function that produces a one line regex to use inside the code.

Yes, i could use a regex to remove the extra spaces but why not to implement this, I think it's axiomatic to do so, isnt it ?

**Comment by firasdib** [comment]
Sure, it's possible I suppose - but not sure if its worth it. I see a lot of potential edge cases that would be a headache.

**Comment by firasdib** [comment]
In fact, when I think about it, when you format the regex, it is a destructive action. You can in other words not go back to the exact same regex you had prior. This would of course mean that it would only work with `x`-flag enabled. Not sure what I feel about it, but I will leave this issue open.

**Comment by firasdib** [comment]
I will mark this as duplicate of #142
