### ISSUE TITLE
Auto-collapse category list in Quick Reference

### ISSUE THREAD

**Issue by Calorion** [firasdib/Regex101#2330]
## Feature
On my iPad, the tokens list is truncated to the point of unusability (see screenshot). When I tap on a category, it should collapse to the left so I can read the token descriptions until I tap on the category list again to expand it (or some other method that allows me to read the tokens list).

![image](https://github.com/user-attachments/assets/2fb9cceb-6c06-47a2-b5d2-82ec6cbdfcbc)

**Comment by firasdib** [comment]
Have you considered expanding the sidebar? You can drag the edge, at least with a mouse. I'm not sure how well that works on a touch device.

**Comment by Calorion** [comment]
No, that does not seem possible on iPad.

**Comment by Calorion** [comment]
Workaround: Pinch in to the central pane, and it will relegate the left and right panes to slideover panes. But there's no way to make it stick this way. I would expect this to happen when you "Request Mobile Website," but it doesn't.

**Comment by firasdib** [comment]
This will be fixed in the new version where you will be able to resize the sidebar on touch devices
