### ISSUE TITLE
PCRE2 version check fails to parse

### ISSUE THREAD

**Issue by david-wahlstedt** [firasdib/Regex101#2335]
## Bug Description

The `(?(VERSION>=10.00)yes|no)` pattern is rejected in PCRE2 mode.

### Reproduction steps

When `(?(VERSION<=10.00)yes|no)` is entered in the "REGULAR EXPRESSION" text field, there is a syntax error message saying 
"(? Incomplete group structure
) Incomplete group structure".

I enter 'no' in the input field, and it has no impact(of course, since the regex is not accepted).

### Expected Outcome

If the PCRE2 version is below 10.0, it should match 'no', otherwise it should match 'yes'.

I guess it is kind of difficult to give a satisfactory answer on this "yse/no" question, since the implementation on regex101 must be an approximation of the full PCRE2 syntax. So, what "version" would be appropriate to test?

### Browser
Shouldn't be relevant, but I have tried both Chrome and Firefox, both on Andriod and Linux, all latest versions.

### OS
Ubuntu 22.04

**Comment by firasdib** [comment]
I could add support for this construct, it's not an issue. I'll put it on the todo list :)

**Comment by firasdib** [comment]
Will be included in the next version
