### ISSUE TITLE
Quiz validation deems unnamed capturing group as superfluous even though it's used by a subroutine call later in the expression

### ISSUE THREAD

**Issue by A-Paint-Brush** [firasdib/Regex101#2337]
### Task
7. Validate an IP

### Bug Description
I attempted to submit a regular expression that contains one non-capturing group, and a unnamed capturing group inside it. To the right of the non-capturing group, there is a subroutine call `(?1)` to the unnamed capturing group inside the non-capturing one. So it looks something like this: `/...(?:...(...)...)...(?1).../`

By testing it in the regex editor, it appears to work correctly and satisfy the requirements. However, the quiz deems the first capturing group in the expression as unnecessary and refuses to accept the answer. This is incorrect, because you can't refer to a group using a subroutine call unless it's a capturing group.

I also tried changing the first capturing group to a named group and changing the subroutine call accordingly, so it looks something like this: `/...(?:...(?P<octet>...)...)...(?&octet).../`

The quiz still won't accept this, and gives the same error message. So apparently the quiz is unaware that capturing groups which are referred to by subroutine calls aren't superfluous?

### Reproduction steps
1. Go to task 7 of the quiz.
2. Write a regex in the format I gave which satisfies the question's requirements.
3. Attempt to submit the answer.
4. See the (incorrect) error message.

### Expected Outcome
It tests my regex against its test cases, instead of incorrectly telling me that the first capturing group is unnecessary and should be removed. Following its advice of changing the first group to a non-capturing group (obviously) breaks the expression.

### Full Error Message
`Test 148/150: Don't create backreferences when you don't need them. If you need to group, use (?:regex); it's the same as (regex) but it doesn't create a backreference.`

### Browser
Microsoft Edge, Version 127.0.2651.105 (Official build) (64-bit)

### OS
Windows 10, Version 22H2 (OS Build 19045.4780)

**Comment by A-Paint-Brush** [comment]
Sorry, I forgot that you're not supposed to post the solution. I've already edited the report to remove them. But how else can I share the regex that the quiz is having trouble with?

**Comment by A-Paint-Brush** [comment]
Ok, I've changed the report to describe the problematic regex in a very un-specific and general way. Hopefully it's still specific enough to be reproduce the bug.

**Comment by firasdib** [comment]
It's intentional, to drive better behavior when creating regular expressions. Generally, using capturing groups will store data unnecessarily if not used. Now, in the grand scheme of things, this doesn't really matter for a modern computer, but always good to learn the basics.

Would it be sufficient to rephrase the message to address capturing groups, instead of backreferences?

**Comment by A-Paint-Brush** [comment]
@firasdib But if capturing groups aren't allowed unless the question asks for it, how can you use subroutine calls? The reason I wanted to use a subroutine call is because I wrote a regex to match a single valid octet value (0~255), then I put a literal dot after it, wrapped both the "octet matcher" and the following literal dot in a non-capturing group, then used a repeating quantifer to make the non-capturing group (octet + dot) repeat 3 times.Now to match the last octet, if subroutine calls aren't allowed, I would have to copy-paste the "octet matcher" as-is to the end of the expression, which seems wrong. Am I going about it the wrong way?

**Comment by A-Paint-Brush** [comment]
Oh, I got it working by placing the regex for matching a single octet in an unnamed capturing group and putting it in a DEFINE block at the start of the regex, then using subroutine calls to call back to it in the remainder of the RE. It also doesn't actually capture data into the 1st capturing group (tested in regex101 editor). The syntax of the "define" construct makes the character count of the regex pretty long though (75 characters), so there's probably a much shorter and entirely different approach that I'm not seeing.
