### ISSUE TITLE
Other users saving versions of your expressions

### ISSUE THREAD

**Issue by Calorion** [firasdib/Regex101#2338]
## Question
Is my understanding correct that if I share a permalink to a regex, other users can save changes to it such that they will show up under that same link, if the version number at the end of the link is `latest`?

**Comment by firasdib** [comment]
Yes, permalinks are open for anyone to edit and save "on top off" unless you're signed in and disable this. If you're signed in , you'll see a menu in the sidebar to manage your entry:
<img width="220" alt="Screenshot 2024-08-29 at 21 09 47" src="https://github.com/user-attachments/assets/02ce381a-4e92-4552-afd5-6e641d30651f">
