### ISSUE TITLE
Add a regex length counter

### ISSUE THREAD

**Issue by Enissay** [firasdib/Regex101#234]
This was a requested feature in the old version and it received too many votes.

I'm sure it's not that hard to implement (it's nothing compared to what is already implemented), but I remember that you weren't supporting it for some unknkown reason :<

**Comment by nhahtdh** [comment]
There is no point in having a regex length counter for most of the purposes, except for regex golf.

**Comment by firasdib** [comment]
I also fail to see the point here, besides regex golf. It will just be another thing to clutter up the GUI imo. Feel free to convince me otherwise though.
