### ISSUE TITLE
Task 14: Test 68 falsely detects backreferences or is worded incorrectly.

### ISSUE THREAD

**Issue by KonnyK** [firasdib/Regex101#2341]
### Task
Task 14: Spam Filter

## Bug Description
I keep getting rejected with the message: "**Test 68/74: Your expression is fine, but I don't want backreferences, as they in this case use unnecessary memory and slow down the match. Fix it and try again.**"
Either my regex knowledge is lacking (which it probably is anyways ^.^ ) or the verification just checks for "\\" which is not necessarily a backreference.

### Reproduction steps
I'll send you the regex by message if you write me.

### Expected Outcome
It says it's fine, but doesn't like backreferences. Which is also a very annoying feature. If it's right, it's right, why reject a valid solution... Just warn that it's a bad solution and encourage to find a shorter and better one.

### Browser
Firefox 129.0.2 (64-Bit)

### OS
Microsoft Windows 10 Pro 10.0.19045

**Comment by KonnyK** [comment]
I found the "issue", the Quiz considers any capture groups as backtracking. Using (?:) instead of () makes the regex longer though. Does it really cost that much performance? In my opinion and as far as my google searches ae concerned this cannot be called a backreference though. Referencing the capture later is what makes it a backreference.

**Comment by firasdib** [comment]
Capture groups are saved for later, and can be used through backreferences. The test checks for capturing groups, but is worded a bit loosely. 

The performance aspect is measureable on a low power CPU, not really on a Macbook M1. But it's considered best practice to not use them if they are not needed.
