### ISSUE TITLE
Allowed creating a private copy for offline use

### ISSUE THREAD

**Issue by arnoudx6** [firasdib/Regex101#2342]
Hi,

*Please understand that this is not your typical can you open source it question.

For our company I want to use RegEx101 offline in an environment with very little internet. If I understand correctly there are no offline binaries or containers. Is it correct that RegEx101 runs completely client side in Javascript? In that case would you allow it if I create a copy of it and use it internally in our company?

We are non-commericial and if we can get it to work, we will not distribute the files.

Kind regards,

Arnoud

**Comment by firasdib** [comment]
Your best bet will be https://digidib.dev/docs/regex101/licenses/ - feel free to reach out to discuss specific quotes.
