### ISSUE TITLE
Incorrect extra } in \U{YY} in rust regex

### ISSUE THREAD

**Issue by Axlefublr** [firasdib/Regex101#2344]
## Bug Description
![image](https://github.com/user-attachments/assets/db7ead7f-b097-421d-a213-76fb35eb7ab7)
![image](https://github.com/user-attachments/assets/38d01ec2-df90-468a-8129-d376edadd07d)

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by firasdib** [comment]
Thank you, will be fixed in next version
