### ISSUE TITLE
Wrong link to twitter account

### ISSUE THREAD

**Issue by TerrniT** [firasdib/Regex101#2345]
## Bug Description
The twitter link is not valid as twitter is now x.com

### Reproduction steps
From the main menu, select dropdown “socials” and try to go to the Twitter page 
![image](https://github.com/user-attachments/assets/ab4e5ab9-ca40-4e1d-b5b6-2668b7b8e328)

### Expected Outcome
- Re-direct to twitter (x.com) page

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by firasdib** [comment]
Thank you, will be fixed in the next release
