### ISSUE TITLE
SSL Certificate Expired

### ISSUE THREAD

**Issue by jespertheend** [firasdib/Regex101#2348]
Seems like the certificate expired five hours ago.

<img width="714" alt="image" src="https://github.com/user-attachments/assets/8a51d74b-dd6f-4516-b1f8-735eb2b2f1f7">
<img width="535" alt="image" src="https://github.com/user-attachments/assets/57cc14f5-5f1e-4d99-a401-f2028b45ef39">

**Comment by firasdib** [comment]
Thank you, this is temporarily resolved. I'll debug certbot when I get a moment over.
