### ISSUE TITLE
Explanation cannot highlight the 11th Capturing group and more

### ISSUE THREAD

**Issue by wdhwg001** [firasdib/Regex101#235]
Unlike the Match Information, the Explanation cannot mark the 11th Capturing group in green, and such thing also happened in 12th, 13th, etc.
![bug_regex101](https://cloud.githubusercontent.com/assets/8943519/6100967/43af18bc-b056-11e4-9a6b-742a8d5600c1.png)

**Comment by firasdib** [comment]
Can you give me the permalink to use as reference?

**Comment by wdhwg001** [comment]
Just try match:
```
1234567890abcdef
```
with regex like:
```
1(2)(3)(4)(5)(6)(7)(8)(9)(0)(a)(b)(c)(d)(e)f
```
Then it goes like:
![bug2_regex101](https://cloud.githubusercontent.com/assets/8943519/6107958/20c7582e-b0aa-11e4-8c7f-34f9adeaea39.jpg)

**Comment by firasdib** [comment]
Thanks, will be adjusted.
