### ISSUE TITLE
Benchmark feature: a way to increase the number of interations

### ISSUE THREAD

**Issue by Palloxin** [firasdib/Regex101#2350]
## Feature
![CD0GKyYB](https://github.com/user-attachments/assets/5df573f0-ce08-405f-b98a-2428f1435436)

Too little interations. I would like to custom them. How? Maybe make a message appear with the number of iterations after benchmark is less than.. 80 idk
Alas, it's better if users were allowed to choose the min interations and/or a precise number

**Comment by firasdib** [comment]
The benchmark runs for 10 seconds, and as many iterations as it can finish in that time, is what is used. I could make this value configurable if you think that's better.

**Comment by Palloxin** [comment]
Where would like to insert the configurable setting?
I thought about in the very same benchmark window.

**Comment by firasdib** [comment]
The new setting will be in the editor settings, https://regex101.com/settings/editor
