### ISSUE TITLE
Theme adaption on website first visit doesnt trigger

### ISSUE THREAD

**Issue by Palloxin** [firasdib/Regex101#2351]
## Bug Description
Theme adaption of the website doesnt trigger automatically on the first website visit, I have to reload the page to make it apply.

### Reproduction steps
1. Visit for the "first" time regex101 with Firefox (mobile or desktop), dont touch anything else.

### Expected Outcome
Auto adaption of website theme directly on the first visit without me having to reload the page.

### Actual Outcome
The theme adaption occours only if I reload the website

### Browser
Firefox (desktop) 

### OS
Windows 10

**Comment by firasdib** [comment]
Thank you, I understand the issue now. I have a fix locally, will push it tomorrow.
