### ISSUE TITLE
login fails - resulting in "Unable to load live version of RegEx101" error.

### ISSUE THREAD

**Issue by smoser** [firasdib/Regex101#2354]
## Bug Description
Creating a new account or signing in with github results in error message 'Unable to load live version of RegEx101"

### Reproduction steps
I tried to use the 'sign in with github' flow today for the first time (no previous account with regex101).
It resulted in this message:
![image](https://github.com/user-attachments/assets/345cdc63-ae8b-44aa-9570-e525b0d1d326)

### Expected Outcome
Signed in so I can manage saved regex.

### Browser
Google chrome Version 129.0.6668.58 (Official Build) (64-bit)
Also error with  Firefox 130.0.1 (64-bit)

### OS
Ubuntu 24.04

**Comment by firasdib** [comment]
Are you still having an issue with this? If so, please reopen the issue.
