### ISSUE TITLE
Unit Tests not failing when they should.

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#2355]
## Bug Description

Unit Tests are succeeding, even when they should fail.

### Reproduction steps

https://regex101.com/r/x3LIvr/1 (cloned from https://regex101.com/r/9Z7P3x/1 )

Input is `yyy` and pattern is `xxx`.

Test condition is: `assert that regex does match` and shows success.
Test condition is: `assert that regex does not match` and shows success.

### Expected Outcome

`xxx` should not match `yyy`. Unit test should reflect the correct outcome.

### Browser

Vivaldi: 6.9.3447.46 (Stable channel) (64-bit) 
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
JavaScript: V8 12.8.374.33

### OS

OS: Windows 10 Version 22H2 (Build 19045.4894)

**Comment by kiradb023** [comment]
###

**Comment by firasdib** [comment]
This should be fixed, please reopen if issue persists.
