### ISSUE TITLE
Going to editor resets code to original.

### ISSUE THREAD

**Issue by Palloxin** [firasdib/Regex101#2356]
## Bug Description
Happens only with saved regexes as far as i have seen.
The regex and string reverts back to the original data from saved regexes links if you go to settings and come back.

### Reproduction steps
1. Go here https://regex101.com/r/6QpdBB/1
2. change the regex to `v+`
3. delete a little bit of the string part.
4. Click settings icon
![image](https://github.com/user-attachments/assets/5ae10dc2-fd15-420f-aa28-eda163775df5)
5. click regex editor icon
![image](https://github.com/user-attachments/assets/218c63b0-2cd4-48bc-b383-d0bfb4e1d552)

### Expected Outcome
The state i left it, not reverted to the original data from the saved regex link, i didnt reload the page.

### Browser
Firefox 130

### OS
Windows 10

**Comment by firasdib** [comment]
I can't reproduce this, is it still an issue? If so, please reopen.
