### ISSUE TITLE
UI Error : match highlights on test string are placed on the wrong letters for a single line larger than about 100 letters

### ISSUE THREAD

**Issue by iv2015** [firasdib/Regex101#236]
The highlights on the test string for matches fall on the wrong letters. They indicate the right matches on hover but are placed on the wrong letters. I think this happens as the letters are word-wrapped automatically by the browser and the highlights calculating javascript doesnt account the wrapped offset. So each and every wrapped line adds some offset to the highlights div's and the effect gradually increases.

Browser : Firefox

I created a regex as below :
/[^\w\s.,]/ig

Test String :
The sun did not shine. It was too wet to play. So we sat in the house All that cold, cold, wet day. I sat there with Sally, we sat there we two. And I said, â€œHow I wish we had something to do!â€ Too wet to go out and too cold to play ball. So we sat in the house. We did nothing at all. So all we could do was to Sit! Sit! Sit! Sit! And we did not like it. Not one little bit. And then something went BUMP! How that bump made us jump! We looked! Then we saw him step in on the mat! We looked! And we saw him! The Cat in the Hat! And he said to us, â€œWhy do you sit there like that?â€ â€œI know it is wet And the sun is not sunny. But we can have lots of good fun that is funny!â€ â€œI know some good games we could play,â€ Said the cat. â€œI know some new tricks,â€ Said the Cat in the Hat. â€œA lot of good tricks. I will show them to you. Your mother Will not mind at all if I do.â€ Then Sally and I Did not know what to say. Our mother was out of the house For the day. But the fish said, â€œNo! No! Make that cat go away! Tell that Cat in the Hat you do NOT want to play. He should not be here. He should not be about. He should not be here When your mother is out!â€ â€œNow! Now! Have no fear. Have no fear!â€ said the cat.

![regex](https://cloud.githubusercontent.com/assets/10919366/6102965/62aec484-b064-11e4-8372-8b5a6350c2f7.jpg)

**Comment by firasdib** [comment]
Would you mind giving me a permalink?

Mvh Firas

**Comment by iv2015** [comment]
Sorry for that, here it is
https://regex101.com/r/qQ4mO4/2

it doesnt appear when the test string is less.
just found out its due to the scrollbar, when ever text is more than the box the glitch appears.

**Comment by firasdib** [comment]
Ah right, Firefox still has sizing issues. Typical. I'm not sure how much I can do about this, but I will give it another look.

**Comment by iv2015** [comment]
cheers... let me know if you need anything...
If i was right about the scrollbar thing... I guess putting a custom scrollbar for all browsers might solve the problem (coz custom scrollbars remove the scrollbar padding of the browsers in the div)... just my 2 cents...

hope this helps... !

**Comment by firasdib** [comment]
Yes, that would work, but is quite a bit more work than you'd imagine with the way things are setup. Plus, it would ruin all the default behavior of the OS/system. Like the inertia of osx and stuff.

**Comment by iv2015** [comment]
ya. You are correct.

**Comment by firasdib** [comment]
Fixed in v2
