### ISSUE TITLE
Match output representation

### ISSUE THREAD

**Issue by Gowrisriprabha** [firasdib/Regex101#2360]
## Bug Description
Though there are multiple matches present for the given pattern, it is highlighting only first match.

### Reproduction steps
.$

### Expected Outcome
should produce(highlight) all the symbols.

### Browser
Include browser name and version
https://regex101.com/
![del](https://github.com/user-attachments/assets/34f2bead-e026-4fef-ae16-1eb63349e805)
![del](https://github.com/user-attachments/assets/e26f58e5-26a1-4023-8e88-d44096a0db14)

### OS
Include OS name and version

**Comment by working-name** [comment]
Hello!

To instruct the regex engine not to stop after the first match, you need to enable the `/g` or `global` flag.
