### ISSUE TITLE
PCRE2 v10.43+ new quantifier shorthand not recognized by regex101's parser (though it works)

### ISSUE THREAD

**Issue by Davidebyzero** [firasdib/Regex101#2370]
## Bug Description

PCRE2 v10.43, following Perl v5.34.0, introduced the ability to use e.g. `{,21}` as a shorthand for `{0,21}`. This syntax works in regex101, but is not properly syntax-highlighted or described in the "Explanation" panel.

### Reproduction steps

https://regex101.com/r/rntSsH/1

### Expected Outcome

The syntax highlighting and Explanation for the above-linked regex should be the same regardless of whether it is `^ab{,3}$` or `^ab{0,3}$`, as long as it is in PCRE2 mode. In PCRE mode (and all others), it should continue to not recognize the `^ab{,3}$` syntax.

**Comment by firasdib** [comment]
Welcome back David, you've been sorely missed!

Thank you for the bug report, I'll have this sorted asap.

**Comment by OnlineCop** [comment]
Has this been pushed out yet? As of API v12.0.10, the above link shows the tooltip and EXPLANATION text as `ab{,3} matches the characters ab{,3} literally (case sensitive)` instead of the expected `{,3} matches the previous token between 0 and 3 times, as many times as possible, giving back as needed (greedy)`.

**Comment by firasdib** [comment]
No, not live yet :-)

**Comment by Davidebyzero** [comment]
> Has this been pushed out yet?

It has now :-)

Thanks very much!

**Comment by NameYourOwn** [comment]
It's 12.0.11 now

**Comment by Manoj1234m** [comment]
1 2 3 4

**Comment by Manoj1234m** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ride On - Motorcycle Game</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header>
    <h1>Ride On - The Ultimate Motorcycle Game</h1>
    <nav>
      <a href="#about">About</a>
      <a href="#screenshots">Screenshots</a>
      <a href="#download">Download</a>
      <a href="#leaderboard">Leaderboard</a>
    </nav>
  </header>

  <section id="hero">
    <h2>Experience the thrill of racing!</h2>
    <button onclick="window.location.href='#download'">Play Now</button>
  </section>

  <section id="about">
    <h2>About the Game</h2>
    <p>High-speed motorcycle action with stunts, challenges, and endless fun!</p>
  </section>

  <section id="leaderboard">
    <h2>Top Players</h2>
    <div id="leaderboard-data"></div>
  </section>

  <footer>
    <p>© 2024 Ride On. All Rights Reserved.</p>
  </footer>

  <script src="script.js"></script>
</body>
</html>
