### ISSUE TITLE
Python \B "shouldn't" match empty string

### ISSUE THREAD

**Issue by Alcaro** [firasdib/Regex101#2374]
## Bug Description
See title

### Reproduction steps
- Switch to Python flavor
- Set regex to \B
- Leave test string empty

### Expected Outcome
Same as Python - doesn't match

Actual expectation would be that they fix their regexes, but they don't seem likely to do that anytime soon https://github.com/python/cpython/issues/124130 so I'm just gonna file an issue here

### Browser
Firefox 128.3.1esr, but this isn't browser specific

### OS
Debian 12

**Comment by working-name** [comment]
Hi Alcaro,

Just FYI, the site is being updated to emulate the python 3 `re` module (in case you bump into other behaviors that don't seem to match). See https://github.com/firasdib/Regex101/issues/1464#issuecomment-758062925

You are right, however, the `re` module does not match a blank string in both py 2 and 3.

Once the update is complete, this will also be addressed.
