### ISSUE TITLE
Searching for 'Back' in Quick Reference guide doesn't locate the 'Match subpattern' page

### ISSUE THREAD

**Issue by alystair** [firasdib/Regex101#2376]
## Bug Description
The word 'backreference' used in the quick guide page's description can't actually be used to locate the specific guide page. This is another name for matching subpatterns.

### Reproduction steps
search for 'back' in the quick reference area

### Expected Outcome
'Match Subpattern #' page should be located.

### Browser
Chrome 130.0.6723.92 

### OS
Win 11 Stable

**Comment by Douhgn** [comment]
Q

**Comment by firasdib** [comment]
I will add some additional search terms and ways to match them to make the search functionality more useful, thank you!
