### ISSUE TITLE
[A-Za-z] Not working

### ISSUE THREAD

**Issue by TFenby** [firasdib/Regex101#238]
![image](https://cloud.githubusercontent.com/assets/858881/6115149/54659e40-b071-11e4-97ea-e03be39a8601.png)

**Comment by firasdib** [comment]
Any errors in your console? Browser? OS? Do you have a link?

**Comment by TFenby** [comment]
No errors. Link is here: https://www.regex101.com/r/xS0eF4/1
But the repro steps are literally just "go to website and type in as shown"

**Comment by TFenby** [comment]
Also, Chrome 41 on Win7 Pro x64

**Comment by firasdib** [comment]
Can I get a print screen of the entire editor?

**Comment by TFenby** [comment]
![image](https://cloud.githubusercontent.com/assets/858881/6115523/1ae6abb6-b074-11e4-9f53-b7387db5a99d.png)

**Comment by firasdib** [comment]
Weird, I can't reproduce. And console has no errors?

Does it happen for PCRE/JS too?

**Comment by TFenby** [comment]
It does work on JS, but not PCRE or Python.
Here's a weird one for ya: it works as soon as I open the console. Tried it in incognito as well and it does the same. Uhh.

**Comment by firasdib** [comment]
Sounds like a problem with your Cache, since it works when you open the console...

**Comment by TFenby** [comment]
Seems like that'd be solved by incognito mode, though. Eh, either way. Not a problem on your end.

**Comment by firasdib** [comment]
I've had it before myself, it was weird. Hope it works out for you! Clearing cache might help.
