### ISSUE TITLE
How can I buy you a coffee?

### ISSUE THREAD

**Issue by JohnPaton** [firasdib/Regex101#2382]
## Question

Love the tool, use it regularly. I'd like to make a small donation to say thanks, but I can't find a way. Maybe you could set up https://buymeacoffee.com/ or something similar?

**Comment by working-name** [comment]
There's a donate button on the site, top right. Right now I see PP and Github as options, outside of the corporate options.

**Comment by JohnPaton** [comment]
🤦 overlooked it, sorry for the spam!
