### ISSUE TITLE
Confirmation for button that loads an example from within the Quick References

### ISSUE THREAD

**Issue by JamesDean3** [firasdib/Regex101#2387]
## Feature
Since the arrow button that loads an example (that you find within the Quick References area, after clicking on one of the examples to get more details), will clear anything that you currently have in the Regular Expression text area, it would be nice if it would confirm before doing so. 

When I went into one of the examples to get more details and meant to go back to the list showing all the Quick References, I accidentally pressed that button instead and it cleared everything I was doing, and as far as I can tell, there isn't a history or a undo button to get that back, so a confirmation as a barrier to losing work would be greatly appreciated.

Side note: Thanks for your work on this project, it is a helpful tool to have when dealing with regex.

**Comment by firasdib** [comment]
If you go to either field and hit ctrl+z, that should bring it back to the previous state. I think adding a confirmation button would make it quite cumbersome to use.
