### ISSUE TITLE
(?R) does not fail outright with a warning

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#241]
In pcretest, `/(?R)/` will fail outright, but regex101 will just execute the regex and timeout.

```
$ pcretest
PCRE version 8.36 2014-09-26

  re> /(?R)/
Failed: recursive call could loop indefinitely at offset 3
  re>
```

**Comment by firasdib** [comment]
Yes, there is nothing I can do about this. This is just the most basic case, but for example, `.*(?R)` would be the same thing, etc etc. If I were to detect this before running the match I would have to do a lot of pre-processing which I don't think is worth it - plus, its overly complex with all the various ways to recurse a pattern and halt execution with verbs etc etc.

I have no idea how pcretest does it, but my guess is it compiles it with some specific flag that would check for this.

**Comment by nhahtdh** [comment]
> As it turns out, the same message is returned on regex101 [...]

Yeah, this is what I'd expect from the library, since this should be done in the studying step as the pattern is built. I expect the result is also used for calculating length in look-behind and probably optimizing the repetition.

**Comment by firasdib** [comment]
I have adjusted the code to take this into account. Will work as expected when I push the new update.
