### ISSUE TITLE
PHP code generator: wrong syntax for backreferences

### ISSUE THREAD

**Issue by borekb** [firasdib/Regex101#244]
This is an example of generated PHP code:

    $re = "...";
    $str = "...";
    $subst = "\1\2new-value\4";
     
    $result = preg_replace($re, $subst, $str);

The `$subst` string is wrong - should contain `$1`, `$2` and `$4` instead of `\1`, `\2` and `\4`.

Note: I can, in the UI, change `\1` to `$1` and it will work fine in the replacement preview pane, however, the UI suggests to use the backslash syntax in which case the generator should convert `\` to `$` so that the final code works.

**Comment by firasdib** [comment]
Does not php support both?

**Comment by borekb** [comment]
Certainly not unescaped backslashes :) Dollar sign is recommended anyway.

**Comment by firasdib** [comment]
You are indeed correct. I have adjusted this. Will be pushed live soon.
