### ISSUE TITLE
Java code generator

### ISSUE THREAD

**Issue by mibac138** [firasdib/Regex101#245]
Maybe, you would add Java generator? I would be really happy! :smiley:

**Comment by yerfinojul** [comment]
+1

**Comment by firasdib** [comment]
Sure, that is not impossible, but I won't be able to support all the Java-specific syntax.

**Comment by mibac138** [comment]
Ok, thanks! :)

**Comment by Opsse** [comment]
Java generator would be great. Thx for your work !

**Comment by firasdib** [comment]
I could generate code for Java, but it would be limited to the syntax available for the flavors regex101 supports. Since I don't support the Java flavor, you won't be able to use character class intersections etc. Are you all fine with that?

**Comment by Opsse** [comment]
I don't really understand where is the limitation, but it is better than nothing i guess.

**Comment by firasdib** [comment]
@Opsse: I am unable to support Java, C#, etc right now because I have found no easy way of compiling their respective regex engine into JavaScript, which is the method I have used for the other languages in order to make the website more responsive and not rely on a backend vulnerable to attacks.

**Comment by Opsse** [comment]
Ok, i get it. For me it isn't a problem.

**Comment by Claudweb** [comment]
Would be better than no java support at all.

**Comment by ProcTrap** [comment]
@firasdib a simple escape of `\` would be enough for the most things.
For completeness a simple java code for using a matcher with capturing group 1,
in case you want to add that:
```java
Pattern pattern = Pattern.compile("REGEX HERE");
Matcher matcher = pattern.matcher("STRING TO COMPARE");
if(matcher.matches()){
	String group1 = matcher.group(1);
}
```

**Comment by d4nirod** [comment]
+1 for Java support even is its limited. 
As for sample code generation you can probably directly map a few modiers [to flags] (http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#field_summary) in [Pattern.compile()] (http://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#compile%28java.lang.String,%20int%29)

**Comment by jeffburton** [comment]
First, you have the best regex development page on the web - and I've tried a lot. I would love to have java code generation - it doesn't have to be compiled - just show the source.

**Comment by mibac138** [comment]
Hope it will be added in short time. Seven months is a lot for thing like this :laughing:

**Comment by thackel** [comment]
The "Code generator" itself is not really required, because its trivial. Its more because of the escaping which is required to have the regular expression in Java-Code.
When you have more complex expressions its quite errorprone and annoying to escape them manually.

So it would be enough to get the expression as "escaped-Java-String".

**Comment by JensRantil** [comment]
Duplicate of #54?

**Comment by firasdib** [comment]
Implemented in v2, rejoice! Lets hope I finish the site asap. (So much work)
