### ISSUE TITLE
Regex non working properly

### ISSUE THREAD

**Issue by napomokoetle** [firasdib/Regex101#246]
My two sample events:

02/17 08:29:03.05 s4zaj1syap18   sqlagt:select0      15540 ERROR        sqlsrvr.c             1647 SQL connection lost detected and is being handled.
02/16 21:24:35.07 s4zaj1syap16   rep_daemon           2460 ERROR        main.c                 232 Domsrvr connection lost

My constructed regex:

\s+(?<caTime>\d+.\d+.\d+.\d+)\s+(?<caWebSrv>\w+)\s+(?<caProcessName>.*)\s+(?<caProcessId>\d+)\s+(?<caMessageType>\w+)\s+(?<caProcessFile>\w+.\w+)\s+(?<caMessageId>\d+)\s+(?<caLostConnType>\w+)\s(?<caMessage>.*)

=======================+
I expect the regex to catch both events, but it only catches the first one! Seems like a bug on the regex function to me.

**Comment by firasdib** [comment]
Have you tried using the `g`-flag?
