### ISSUE TITLE
Indicate in QUICK REFERENCE when Character Class is Unicode-compatible

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#247]
In PHP, character classes such as  [[:alnum:]], [[:alpha:]], [[:lower:]], [[:upper:]], [[:word:]] can match Unicode characters such as ß, ñ, ü, and so on. A small visual cue (a different color for the link, or a **u** somewhere) to indicate that it can match Unicode characters when the 'u' modifier is enabled would be nice.

**Comment by firasdib** [comment]
Do you mean, if `u`-flag is enabled, add a short snippet of text to the explanations that they also match unicode characters?

**Comment by OnlineCop** [comment]
You could either do that, or simply have a floating 'u' or 'unicode' cue somewhere on the tooltip which would indicate that it's Unicode-aware.

**Comment by firasdib** [comment]
Re-reading this, was your initial suggestion just to mention it in the qucikreference? "This token can be modified using the `u`-flag"?

**Comment by OnlineCop** [comment]
Right. Just a simple mention in one of the QuickReference tooltips. Nothing
fancy/flashy/wordy.

**Comment by working-name** [comment]
Noted. Will incorporate it in the quick reference.

**Comment by firasdib** [comment]
Closing this for now then! Thanks @working-name
