### ISSUE TITLE
Custom delimiter

### ISSUE THREAD

**Issue by StevenRoddis** [firasdib/Regex101#248]
I often work with regex that doesn't use delimiters or allows me to chose `%` as a delimiter.

`^http://(?:www\.)?regex101\.com/`
needs to be converted into the uglyier
`^http:\/\/(?:www\.)?regex101\.com\/`
and then back again when I go to use it.

It would be great if custom delimiters were supported or even the ability to turn them off.

**Comment by firasdib** [comment]
You can click the delimiter and change it
