### ISSUE TITLE
Unit tests should run automatically

### ISSUE THREAD

**Issue by rillig-nm** [firasdib/Regex101#249]
I have written a regular expression with some unit tests. To run the unit tests, I have to manually click the Play button.

The unit tests should run whenever I change the regular expression. I don’t want to press Play manually.

**Comment by firasdib** [comment]
I don't agree. This will most certainly end up in most peoples browsers hanging and crashing. At best, spike in CPU usage. Just press the button instead and think your changes through before hand.
