### ISSUE TITLE
The Add Test button should be in the lower right corner of the Create Test area

### ISSUE THREAD

**Issue by rillig-nm** [firasdib/Regex101#250]
When I initially open the view for writing unit tests, the Add Test button is positioned in the upper right corner. This suggests to me that I can click that button immediately, without filling out some elements. But this is wrong.

The expected input sequence is:
1. fill out the test string
2. select the values from the two dropdown fields
3. click Add Test

This typical sequence is not represented by the position of the GUI elements. The Add Test button should be in the same row as the two dropdown fields, aligned on the right edge.

To make the keyboard navigation simple, the tab sequence should be adjusted. The Add Test button should directly follow the two dropdown fields. Currently, when the second dropdown is focused and I press Tab, the Explanation area gets the focus.

**Comment by firasdib** [comment]
I agree, will look into this. I have not found a good position to place the 'add test' button on, since the GUI changes depending on the combo boxes. But I will start by adjusting the tab issue.

**Comment by firasdib** [comment]
Fixed in v2
