### ISSUE TITLE
`/` cannot be passed into expression

### ISSUE THREAD

**Issue by DavidArenburg** [firasdib/Regex101#251]
For example, the following expression [returns an error](https://www.regex101.com/r/hV8lQ7/1)
````
[ /].*
````
 While it is a [valid regex](http://rick.measham.id.au/paste/explain.pl?regex=%5B+%2F%5D.*).

**Comment by firasdib** [comment]
Change delimiter or escape the character. https://www.regex101.com/r/hV8lQ7/2
