### ISSUE TITLE
? quanitifier does not seem to work with groups

### ISSUE THREAD

**Issue by runxel** [firasdib/Regex101#252]
I have the following regex: `UI_INFIELD(\{[2-3]\})?`
This should match all of these:
`UI_INFIELD`
`UI_INFIELD{2}`
`UI_INFIELD{3}`

Regex101 matches only the first one with my construction. If I delete the `?` it will only – correctly – match the last two.

**Comment by firasdib** [comment]
Are you using the `g`-flag?

**Comment by runxel** [comment]
Yes.
Aaaand boy, I also used the `U`-flag... my fault – sorry.

**Comment by firasdib** [comment]
Ah that explains it. Happy you solved it!
