### ISSUE TITLE
Explanation displays the wrong character when astral plane character is specified

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#254]
Sample regex:

    [\x{13000}-\x{1342F}]\x{1342F}

Wrong explanation:
```
    \x{13000}-\x{1342F} a single character in the range between the following two characters
        \x{13000} the character 　 with position 0x13000 (77824 decimal or 230000 octal) in the character set
        \x{1342F} the character 㐯 with position 0x1342F (78895 decimal or 232057 octal) in the character set

\x{1342F} matches the character 㐯 with position 0x1342F (78895 decimal or 232057 octal) in the character set
```
`㐯` has code point `U+342f`

https://regex101.com/r/rR8iN9/1

**Comment by firasdib** [comment]
Ah, the issue is javascript is limited to 16bits, that is any value greater than 2^16 = 65536 will return weird results, as you have experienced. I will have to implement my own method then I suppose.

**Comment by firasdib** [comment]
I've fixed this now, will push when I get the time to fix a few more kinks. Sorry for the delay, hope its alright.
