### ISSUE TITLE
Export Matches Bug With \n

### ISSUE THREAD

**Issue by cjbarth** [firasdib/Regex101#255]
When exporting matches that contains a new line character, the CSV and Plain Text export functions don't work, but the JSON export correctly outputs \n.

**Comment by nhahtdh** [comment]
The CSV, as far as I can see, is correct, but not many CSV parser can parse it correctly.

Regarding plain text export function, what do you expect anyway?

**Comment by cjbarth** [comment]
In further testing it appears that the issue is related to new line characters in combination with other characters: https://regex101.com/r/iK9mV2/1. Note the difference between the JSON results, CSV results, and Plain Text results. I would prefer if at least the rest of the results aren't stripped at the first big of bad data. Even better would be to escape, perhaps using HTML escape codes, everything that wouldn't work correctly in CSV or Plain Text.

**Comment by firasdib** [comment]
I see the error and will adjust it, but wont have time to push the changes until a few weeks (exam period.. sorry)

**Comment by cjbarth** [comment]
No worries. I hope your exams go well:)

**Comment by firasdib** [comment]
Fixed, will push live soon.
