### ISSUE TITLE
Match ASCII control characters

### ISSUE THREAD

**Issue by zigfreid5** [firasdib/Regex101#257]
I need to match control characters found in ascii characters 0-33. Is there a way to use these in the "TEST STRING" textarea?

**Comment by nhahtdh** [comment]
You shouldn't test those character on an online-test anyway: https://regex101.com/r/yP2qV8/2

The trick is to open the console, loop through the characters from 0 to 31, concatenate them and output to console, then copy it into the field. Note that this trick doesn't work with `\r` and `\0`. `\r` will just get converted to `\n`, and `\0` kind of "terminates" the string so nothing is copied.

**Comment by firasdib** [comment]
I agree with @nhahtdh
