### ISSUE TITLE
I don't find working negative or positive lookbehind

### ISSUE THREAD

**Issue by niorko** [firasdib/Regex101#258]

**Comment by firasdib** [comment]
Thats not very informative. Give me more details.

**Comment by niorko** [comment]
Sorry for short description. I don't find working **positive** or **negative lookbehind**:

    (?<apple)
    (?<!pineapple)

I think it's not an issue, because as I'm looking, regex101 just doesn't support it, but it would be nice feature. Thanks for reply.

**Comment by firasdib** [comment]
It is supported just fine. Make sure you're not using the javascript flavor, as javascript does not support lookbehinds.

The syntax is
```
(?<=positive)
(?<!negative)
````
