### ISSUE TITLE
An error when using "|"

### ISSUE THREAD

**Issue by dantexier** [firasdib/Regex101#259]
My regular expression is "a*b|b*a", so, the words that accept are:
aaaaab
b
ab
bbbba
ba
a

But, this RE does not accept the part second "b*a", ie,
bbbba
ba
a

But, if my regular expression is only "b*a", if accept these words:
bbbba
ba
a

Are you suggestions?

Thanks,
Jose

**Comment by firasdib** [comment]
Please post a permalink

**Comment by nhahtdh** [comment]
You need to anchor the regex. Otherwise, since `a*b` can match a lone `b`, it will just match it without trying the second branch.

https://regex101.com/r/vD3nS9/1
