### ISSUE TITLE
Ability to change delimiters

### ISSUE THREAD

**Issue by quasipickle** [firasdib/Regex101#262]
The ability to change the delimiter character would be nice.

**Comment by firasdib** [comment]
It's been discussed a few times, and the ability is already there: #248 #31 #96 

Just click one of the delimiters :)

**Comment by quasipickle** [comment]
I asked in IRC & it was said it wasn't possible.

I'm happy to consider this closed, but maybe a UI tweak to make it more obvious would be prudent.

**Comment by firasdib** [comment]
They must be misinformed. I'm on IRC now if you would like to have a chat and discuss further improvements!
