### ISSUE TITLE
SS# not getting found within certain text, but found in all others

### ISSUE THREAD

**Issue by kristyb** [firasdib/Regex101#263]
Regex:
\b[0-9]{3}-[0-9]{2}-[0-9]{4}\b

Text to search (copied & pasted from .pdf file into regex101 tester. Actual numbers changed):
APPLICANT
NAME: asdfssfd sadfsdfs
S.S.N : 111-11-1111 Date Received: 02/24/15

**Comment by kristyb** [comment]
Note: Perhaps somehow the formatting of the .pdf was picked up (boxes around the text), but I think that should be ignored when pasted into regex tester.

**Comment by firasdib** [comment]
Matches fine for me. What is the bug more exactly?

And no, nothing will be ignored that is being pasted into the box. If you did not want it there you should have removed it before hand.

**Comment by kristyb** [comment]
Okay, so if you copied and pasted the text from here and it worked then it must have kept some formatting when I copied from the .pdf. That's all I can think of..Thanks!
