### ISSUE TITLE
Allow editing a unity test

### ISSUE THREAD

**Issue by he7d3r** [firasdib/Regex101#264]
It seems the only way to change a unity test right now is by creating a new one and deleting the existing test.

**Comment by firasdib** [comment]
I agree this needs to be implemented, but I'm still not sure how to implement it UI wise. Do you have any ideas?

**Comment by he7d3r** [comment]
It could either have a new icon on the left, besides the delete icon, or it could allow double clicking in a test. In both cases, the unity test data would be loaded in the form, where the user could change the values as desired.

**Comment by mskadu** [comment]
+1

**Comment by firasdib** [comment]
Fixed in v2
