### ISSUE TITLE
The server fails to save astral code point and corrupts all existing test cases with astral code point

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#265]
If you type `xd🀄abcde` into the input box and save it, the next time you reload the page, the character is displayed as `?`.

https://regex101.com/r/dH0tE3/3

Additionally, any astral plane character in the database before the recent change are corrupted

https://regex101.com/r/dH0tE3/1

(This is taken from the bug report: https://github.com/firasdib/Regex101/issues/190#issuecomment-84799229. Previously, astral plane characters can be saved)

Another corrupted test case https://regex101.com/r/rR8iN9/1 from https://github.com/firasdib/Regex101/issues/254

**Comment by firasdib** [comment]
This is because mysql does not use real utf8, it does now though. I have fixed this issue but introduced another that has been temporarily fixed. Please tell me if you have trouble saving utf8 in the future.
