### ISSUE TITLE
Your expression took too long to evaluate.

### ISSUE THREAD

**Issue by seefor** [firasdib/Regex101#266]
My RegEx:
(\/\w*)*\s*\d*\s*\d*\s*\d*\s*([7-9][0-9])\s*(\/|none|proc|tmpfs)
Checking against 
Mount-on                  1K-blocks      Used   Available   Use%  Filesystem
/                            409600     65332      344268     73   /dev/root
/proc                             0         0           0     77   proc
/sys                              0         0           0     80   none
/isan                       1572864    676908      895956     44   none
/var                          51200       460       50740      1   none
/etc                           5120      1856        3264     37   none
/nxos/tmp                    102400      1376      101024      2   none
/var/log                      51200      4876       46324     10   none
/var/home                      5120        24        5096      1   none
/var/tmp                     307200       304      306896      1   none
/var/sysmgr                 3670016       208     3669808      1   none
/var/sysmgr/ftp              819200    218492      600708     27   none
/var/sysmgr/srv_logs         102400         0      102400      0   none
/var/sysmgr/ftp/debug_logs     10240         0       10240      0   none
/dev/shm                    3145728    377812     2767916     73   none
/volatile                    512000         0      512000      0   none
/debug                         5120        16        5104      1   none
/dev/mqueue                       0         0           0      0   none
/debugfs                          0         0           0      0   nodev
/mnt/plog                    242534      4335      225677      2   /dev/sda1
/mnt/fwimg                   121515      4127      111114      4   /dev/sda3
/mnt/cfg/0                    75917      4850       67147      7   /dev/md5
/mnt/cfg/1                    75415      4850       66671      7   /dev/md6
/bootflash                  1773912    953920      729880     90   /dev/md3
/cgroup                           0         0           0      0   vdccontrol
/var/sysmgr/startup-cfg      409600      8852      400748      3   none
/dev/pts                          0         0           0      0   devpts
/mnt/pss                      38172      5404       30797     15   /dev/md4
/fwimg_tmp                   131072       480      130592      1   tmpfs
/bootflash_sup-remote       1773912    953848      729952     57   127.1.1.10:/bootflash/

**Comment by firasdib** [comment]
This executes fine for me, but you can try increasing the timeout. Click the gear icon in the upper right cornor and increase the time a little bit and try again.

**Comment by seefor** [comment]
Thanks that worked
