### ISSUE TITLE
Setting the regex string and test string using query params

### ISSUE THREAD

**Issue by boris-bascarevic** [firasdib/Regex101#267]
It would be nice to implement setting of the regex and/or test string by using a querystring, so we can create a URL for a specific regex. 

Both could be url-encoded or base64-encoded UTF-8 so that special characters are preserved: 
https://regex101.com?q=XkhlbGxvIFdvcmxkISQ&testString=SGVsbG8gV29ybGQh

**Comment by Bilge** [comment]
When you click *save regex* you receive a share link. This issue should be closed.

**Comment by nhahtdh** [comment]
Already supported, but it is a hidden feature: https://github.com/firasdib/Regex101/issues/213

**Comment by firasdib** [comment]
While it has some legacy support, I strongly recommend using the permalink feature.
