### ISSUE TITLE
pcrelib16.js Assertion failed: Cannot call unknown function getCalloutAddress

### ISSUE THREAD

**Issue by knox** [firasdib/Regex101#269]
Since a few days this wonderful site is broken, at least for me. Here is what i can see in my Chrome's JavaScript console window:

    Redirect at origin 'https://fonts.gstatic.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The request was redirected to a URL ('about:blank') which has a disallowed scheme for cross-origin requests.
    (index):449 Resource interpreted as Script but transferred with MIME type text/html: "about:blank".
  
    Assertion failed: Cannot call unknown function getCalloutAddress (perhaps LLVM optimizations or closure removed it?)
    pcrelib16.js:99 Assertion failed: Cannot call unknown function getCalloutAddress (perhaps LLVM optimizations or closure removed it?)
    pcrelib16.js:5450 Uncaught abort() at Error
        at abort (https://regex101.com/js/pcrelib16.js:5450:26)
        at assert (https://regex101.com/js/pcrelib16.js:458:32)
        at getCFunc (https://regex101.com/js/pcrelib16.js:490:56)
        at Object.cwrap (https://regex101.com/js/pcrelib16.js:533:14)
        at https://regex101.com/js/pcre.regex101.js:1:7795

**Comment by firasdib** [comment]
This means the javascript libraries have been hard cached and not re-downloaded since I updated them. Try clearing your cache or doing a hard refresh, `ctrl+f5`.

**Comment by knox** [comment]
On my mac, it is cmd+shift+R. But the problem remains:

    Assertion failed: Cannot call unknown function getCalloutAddress (perhaps LLVM optimizations or closure removed it?)
    /js/pcrelib16.js:99 Assertion failed: Cannot call unknown function getCalloutAddress (perhaps LLVM optimizations or closure removed it?)
    /js/pcrelib16.js:5450 Uncaught abort() at Error
        at abort (https://regex101.com/js/pcrelib16.js:5450:26)
        at assert (https://regex101.com/js/pcrelib16.js:458:32)
        at getCFunc (https://regex101.com/js/pcrelib16.js:490:56)
        at Object.cwrap (https://regex101.com/js/pcrelib16.js:533:14)
        at https://regex101.com/js/pcre.regex101.js:1:7795

**Comment by firasdib** [comment]
Chrome is pretty notorious with its caching policies. Try `CMD+shift+delete` and clear cache from there.

**Comment by knox** [comment]
Thanks, clearing the cache indeed solved my problem
