### ISSUE TITLE
Pcre Flags (SKIP*)(FAIL*) not working

### ISSUE THREAD

**Issue by fedepia** [firasdib/Regex101#270]
Hello, the flags to make a regex fail aren't working.

You can see below an example:
https://regex101.com/r/hV2lV2/1

The word 'example' shouldn't be matched

**Comment by firasdib** [comment]
That is because you're misusing the syntax for verbs, I think you we're looking for `(*SKIP)` and `(*FAIL)`. See here: https://regex101.com/r/hV2lV2/2
