### ISSUE TITLE
Regex debugger fails to run

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#271]
Here is the error in the console:

> TypeError: debugData is undefined

I don't see any request being sent to the server.

**Comment by firasdib** [comment]
Any more specific error?

Tried clearing cache?

**Comment by nhahtdh** [comment]
I tried a hard refresh (Ctrl + Shift + F5). All files seem to be loaded properly, but the debug feature still return the same error as above (from common.regex101). To be sure that the proxy doesn't block any of the requests, I even checked the content of each file individually.

![](https://cloud.githubusercontent.com/assets/564162/7173391/ff90c0fa-e420-11e4-81dc-060c8315e490.png)

**Comment by firasdib** [comment]
The file that is updated is not in that screenshot. Try clearing cache from settings menu. Can I get a print screen of the error in the console?

**Comment by nhahtdh** [comment]
@firasdib It just got fixed, either from your end, or due to caching (but I doubt it's caching, since I did a hard refresh when I took that screenshot)

**Comment by firasdib** [comment]
Its caching :)
