### ISSUE TITLE
Regex Upon Results feature

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#274]
Many people ask to find results which are limited to be within a specific range. For example: finding all tab (<code>\t</code>) characters IF they occur between <code>\<code></code> and <code>\</code></code> tags.

Currently, the website allows for a single regex. If there could be two regexes, where the second matches based off of the CAPTURED or MATCHED results of the first regex, you could have something like:

Input: <code>\tStuff\t\<code>blah\tblah\tblah\</code>\tMore Stuff\t\<code>foo bar\tfootball\tsoccer\</code>\tEven More Stuff</code>

Search1: <code>(?<=\<code>)(?s:.*?)(?=\</code>)</code>
Match1: \[<code>blah\tblah\tblah</code>, <code>foo bar\tfootball\tsoccer</code>\]

Search2: <code>\t</code>
Replace2: <code>--</code>
Match2: \[<code>blah--blah--blah</code>, <code>foo bar--football--soccer</code>\]

Results: <code>\tStuff\t\<code>blah--blah--blah\</code>\tMore Stuff\t\<code>foo bar--football--soccer\</code>\tEven More Stuff</code>

*hint* This could be available only to subscribers ;-) *hint*

**Comment by firasdib** [comment]
This is not a bad idea, but it would make for difficult UI. I'm assuming you should in reality be able to stack as many searches upon each other as you'd like. Do you have any thoughts on how you could design it?

Performance is another factor, it would be as slow as unit tests currently are (Chrome slow, FF fast).

**Comment by firasdib** [comment]
I'm closing this, it doesn't seem like anything I will give into and even a bit too broad.

**Comment by nhahtdh** [comment]
Related/Dup: https://github.com/firasdib/Regex101/issues/281, https://github.com/firasdib/Regex101/issues/439
