### ISSUE TITLE
Reposition and/or retitle "save regex" button

### ISSUE THREAD

**Issue by morganhein** [firasdib/Regex101#275]
I hang out in the #regex channel quite a bit, and quite often people cannot find the save regex option when trying to share their regex. This is probably, in my opinion, the biggest struggle when using the site the first time.

It would be great if this was moved, and possibly renamed. "Save regex" does not inherently also mean "with the possibility of sharing" afterwards (although not a great stretch to figure out, for sure).

I personally think that the "save" button needs to be closer to where people input the regex's themselves, possibly below the modifier entry. Thanks!

**Comment by firasdib** [comment]
I agree, I will move that up further. Thank you.
