### ISSUE TITLE
Remind PHP users modifier `g` is not required

### ISSUE THREAD

**Issue by shivanraptor** [firasdib/Regex101#277]
Common mistake of using Regex in PHP is that adding modifier `g` after the RegEx. This is not required by PHP, and it is an invalid PCRE modifier, which will generate a warning:

http://stackoverflow.com/questions/7653055/preg-replace-bad-regex-unknown-modifier

**Comment by nhahtdh** [comment]
It is required in pcretest. regex101 is not strictly a PHP tester - it's more of pcre 16-bit library tester.

**Comment by firasdib** [comment]
I feel that if you are unsure of how to use your regular expression, try the code generator.
