### ISSUE TITLE
[\v] matches vertical whitespace but Explanation fails

### ISSUE THREAD

**Issue by billynoah** [firasdib/Regex101#278]
Vertical whitespace escape `\v` is ok to use inside character class `[\v]`, and although your engine succeeds with a match, the **Explanation** fails to properly describe this.

https://regex101.com/r/wL4hT4/1

**Comment by nhahtdh** [comment]
The same happens for `\h`, which also works in character class.

**Comment by firasdib** [comment]
Thank you, fixed.
