### ISSUE TITLE
Suggestion: allow repeated replacements

### ISSUE THREAD

**Issue by luis140219** [firasdib/Regex101#281]
Suggestion: add a Repeat checkbox in the Substitution area. If checked, it would repeat the replacement until it cannot do nothing to the input.

**Comment by firasdib** [comment]
Just use the `g`-flag next to the regex, it affects both substitution and matching functionality.

**Comment by luis140219** [comment]
My regex-and-replacement's mission is to remove **all matching** parenthesis from a string.

This is a proof that the g-modifier is **different** from repeat as specified in my description:

Consider the regex `/\(([^\(\)]*)\)/`, the replacement `$1`, and the string `((hello )(world))`.

The regex matches `(`, then a set of consecutive non-parenthesis characters as big as possible (greedy), then a `)`.

First the regex matches both `(hello ) hello` `(world ) world`. (don't return on first match)
Before space: whole match, after space: first capturing group.

The replacement removes the parenthesis from each match, therefore resulting in `(hello world)`.

As I've said, repeat uses the following algorithm:
```
The function repeat_replacement(re, s, n) works as follows:
  1. Let x be s.
  2. While s.test(re), do:
     a. Let w be the result of calling the replace method of x with inputs re and n.
     b. Set x to w.
  3. Return x.
```

Steps:
```
Step 1: x = "((hello )(world))"
Step 2: Regex matches (hello ), so:
  Step 2.a: Regex replaces (hello ) with "hello " and sets w to (hello (world)).
  Step 2.b: x becomes (hello (world)).
Step 2: Regex matches (world), so:
  Step 2.a: Regex replaces (world) with world and sets w to (hello world).
  Step 2.b: x becomes (hello world).
Step 2: Regex matches (hello world), so:
  Step 2.a: Regex replaces (hello world) with "hello world" and sets w to "hello world".
  Step 2.b: x becomes "hello world".
Step 2: Regex cannot match. Loop stops.
Step 3: x is returned.
```

So, this time the mission was accomplished. The string is now "hello world".

**Comment by firasdib** [comment]
You're thinking of a recursive replacement?

**Comment by luis140219** [comment]
Yes.
