### ISSUE TITLE
regex101 vs python regex: different behaviour 

### ISSUE THREAD

**Issue by adamlee1776** [firasdib/Regex101#283]
multi line support is missing, 
for example:

for same input ('data'):
adam@gmail.co.il
adam@gmail.co.il
adam@gmail.co.il

with same pattern:
"\r?\w+@(\w+\.){1,2}\w+\n?"

regex101 gives only the first row as match, 
while the following python code gives all 3:

python code:
-start-
pattern = "\r?\w+@(\w+\.){1,2}\w+\n?"
regex = re.compile(pattern)

matches = len(re.findall(regex, data))
-end-

thanks,
Adam

**Comment by firasdib** [comment]
Did you use the `gm` flags?

**Comment by adamlee1776** [comment]
You are correct, the 'gm' flags solving this - now regex101 gives all 3 lines.

thanks.
