### ISSUE TITLE
PHP matches where yours doesn't: /[가-힣]/  matches "à proprement parler"

### ISSUE THREAD

**Issue by wordreference** [firasdib/Regex101#284]
Your tool looks quite good, and that is why I need to report what I consider to be an error.

I needed to match Korean characters, so I created a range.

In PHP, it stupidly matches:
pattern: /[가-힣]/
string: à proprement parler

It matches the à!
Yes, it is that stupid.

Your page's behavior:
Your example page doesn't make that match.

Expected behavior:
You make the same match as PHP.

What PHP needs for that to work correctly is the "u"
pattern: /[가-힣]/u
string: à proprement parler

=>No match, as it should be.

I suggest updating your page to match it.

I would include a link to my use of your page, but I can't figure out how to do it.  (I want to click on "share this regex test" but can't find it.)

Cheers.

**Comment by nhahtdh** [comment]
regex101 compiles to JavaScript from PCRE 16-bit library instead of the PCRE 8-bit library, which is what PHP actually uses. The behavior as you can see is correct for 16-bit library, but it is indeed confusing for PHP users.

**Comment by firasdib** [comment]
Unfortunately not much I can do about this issue.

**Comment by Dustin4444** [comment]
> Your tool looks quite good, and that is why I need to report what I consider to be an error.
> 
> I needed to match Korean characters, so I created a range.
> 
> In PHP, it stupidly matches: pattern: /[가-힣]/ string: à proprement parler
> 
> It matches the à! Yes, it is that stupid.
> 
> Your page's behavior: Your example page doesn't make that match.
> 
> Expected behavior: You make the same match as PHP.
> 
> What PHP needs for that to work correctly is the "u" pattern: /[가-힣]/u string: à proprement parler
> 
> =>No match, as it should be.
> 
> I suggest updating your page to match it.
> 
> I would include a link to my use of your page, but I can't figure out how to do it. (I want to click on "share this regex test" but can't find it.)
> 
> Cheers.
