### ISSUE TITLE
Make it possible to share a RegEx and the test string

### ISSUE THREAD

**Issue by rugk** [firasdib/Regex101#289]
It would be nice if you could just export the actual "view", so the RegExp and the test string should be included in an URL that I can send others so that they can simply test the RegExp like I did.

Example: *https://regex101.com/share?regexp=\<a base64 encoded string of the regular expression\>&str=\<a base64 encoded string of the test string\>*

**Comment by firasdib** [comment]
This has been discussed before. The functionality you're asking for already exists if you look at the left hand side at the top of the menu.

**Comment by rugk** [comment]
Ahh it's "Save RegEx". Thanks for letting me know.
I was a bit confused of this name. (because IMHO "save" more-or-less suggests to a local saving, such as "download")

Related issues: (e.g.) https://github.com/firasdib/Regex101/issues/275 https://github.com/firasdib/Regex101/issues/90 https://github.com/firasdib/Regex101/issues/205 https://github.com/firasdib/Regex101/issues/206
