### ISSUE TITLE
[HTTPS] Vulnerable to Logjam attack

### ISSUE THREAD

**Issue by rugk** [firasdib/Regex101#290]
The site is vulnerable to the [Logjam attack] (https://weakdh.org/). ([test] (https://www.ssllabs.com/ssltest/analyze.html?d=regex101.com))
Here is what you should do now: https://weakdh.org/sysadmin.html

And BTW. Also enabling [HSTS] (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) and/or [HPKP] (https://noncombatant.org/2015/05/01/about-http-public-key-pinning/) would great (for security).

**Comment by firasdib** [comment]
Thank you, this should be fixed now.

**Comment by rugk** [comment]
Okay, then do it later.
I think having security related stuff up-to-date isn't a bad idea anyway. :smile:

**Comment by Zarthus** [comment]
This looks fixed to me, closing issue

**Comment by rugk** [comment]
Nice, just some notes:
* You send the root certificate (which is unnecessary) and the chain is a bit unordered. That's stated by SSLLabs in:

  > Chain issues: Incorrect order, Contains anchor

* And you could send the [HSTS header](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security). When you do this you will get A+ on SSLLabs.

**Comment by Zarthus** [comment]
(I'm in no way affiliated with the setup)

Personally I think HSTS is going to become an issue. Comodo (several CEO forum posts, [the letsencrypt issue](https://letsencrypt.org/2016/06/23/defending-our-brand.html), overall poor experience as user) (the company that issued the cert) is from experience not very trustworthy and might be a reason for downtime later if ever switched.  As far as things go, I don't think pressing for HSTS is a good idea _right this minute_. But I don't have the insight into plans as much as firasdib does, of course!

**Comment by rugk** [comment]
HSTS only means you use a HTTPS connection. It does not mean (from the server perspective) "I use (and will use) a HTTPS cert from Comodo". It just says "I use (and will use) a valid HTTPS connection".
Therefore RegEx101 can always switch certs in the future, e.g.  switching to [Let's Encrypt](https://letsencrypt.org/).

**Comment by Zarthus** [comment]
I know it doesn't, I'm just saying enabling HSTS means there may be noticeable downtime, and for a single developer (where Regex101 is not in any form a source of income) those kinds of guarantees are hard to make for long periods. There's only one reasonable cheap provider around for SSL certs that I know of (LetsEncrypt), and it only takes one (major) screwup of them and things will stop trusting it.

The main thing about HSTS is not only that it means you will be using a HTTPS connection, but are also indicating "and this HTTPS connection will remain valid until X", which is where I start seeing the risks involved.

All in all, I think the guarantee is just a little bit hard to make. SSL certificates are still not where they need to be.

**Comment by rugk** [comment]
> There's only one reasonable cheap provider around for SSL certs that I know of (LetsEncrypt)

There is also StartSSL.

> those kinds of guarantees are hard to make for long periods

Well.. he could start with a HSTS header valid for a relative short time.

**Comment by Zarthus** [comment]
StartSSL also has obtained a relatively poor reputation as of late. (i'd rather not elaborate on this in public.)

I agree a short duration is a good option if anything, but I think it's better to commit with HSTS when you are ready to commit.

**Comment by rugk** [comment]
> StartSSL also has obtained a relatively poor reputation as of late. (i'd rather not elaborate on this in public.)

No problem, I know...
https://community.letsencrypt.org/t/vulnerable-startencrypt-enabled-mis-issued-startssl-certs/17500

But they are going to switch to ACME, so that's good. But as for this issue this if off-topic.
