### ISSUE TITLE
Do this

### ISSUE THREAD

**Issue by morganhein** [firasdib/Regex101#291]
a link on the internet: http://imgur.com/PnkOcd3

**Comment by nhahtdh** [comment]
What is the problem you are trying to report here?

**Comment by nhahtdh** [comment]
Although I'm not the owner of regex101, please at least tell us that you want the CSS to be changed, and where in the UI. It's hard to tell what you want with just the image.

**Comment by morganhein** [comment]
nhahtdh, thanks for the feedback, however lindrian requested I put up an image like this in exactly this format, and since he's the one writing the code....

**Comment by firasdib** [comment]
Sorry lol, he's right. Thanks for sticking up for me though @nhahtdh - appreciate it. Bro-five.
