### ISSUE TITLE
Prefill fields based on url values

### ISSUE THREAD

**Issue by Epskampie** [firasdib/Regex101#292]
Hi, thanks for creating this awesome tool.

I would love to send my users to your tool to debug their own regexes. For this this purpose, I would have to be able to send them to a link like http://regex101.com?regex=a|b|c&test_string=xyz . The fields would then be prefilled using the values provided.

I could not find this function in your interface. I am NOT talking about the ability to save a regex, I know that is already possible.

Would you consider adding this? Thanks!

**Comment by firasdib** [comment]
There is old legacy support for this, with limited features: https://regex101.com/?regex=foo&text=bar&options=baz

May I ask why 'save regex' is not sufficient? It allows for a short link and many, many more features.

**Comment by Epskampie** [comment]
Awesome!

The reason that save is not sufficient is because the flow is as follows:

My users enter a regex on _my website_ to parse some text. I want to to to help them easily debug the regex they entered, so I want to send them your fully featured editor, with the regex they already entered, as well as the text that they have to parse.

**Comment by ayanamist** [comment]
It seems that this old legacy support has been removed? I try `https://regex101.com/?regex=foo&text=bar&options=g` but nothing prefilled.

**Comment by firasdib** [comment]
That is correct, I no longer support it in v2.

**Comment by ayanamist** [comment]
So maybe you need to remove related item from FAQ?

**Comment by firasdib** [comment]
First line of FAQ:

> This page has not been updated to reflect version 2 of the site.

**Comment by mikechamberlain** [comment]
I really think this was a killer feature, at least for our use case (well of course!).

As a necessary evil, we allow users (most of whom are only semi-technical, or less) to construct what are usually simple regexes on our site. As regex101 is the nicest regex tester out there, we currently link to you with a "Test this out" link, but that requires the users to copy and paste what they just entered. We want to make things as simple as possible for them, but don't have the resources to create a regex tester anywhere near as great as yours.

On the face of it, it sounds like a fairly simple change, and as far as I can see a feature that none of your competitors offer. Further, it made it into your FAQ, so seems to be something that others found quite useful too.

So here's thanks for a great site, and a plea for reconsideration of this feature.

**Comment by mikechamberlain** [comment]
PR created for regexr: gskinner/regexr#187

**Comment by firasdib** [comment]
@mikechamberlain You could use the API and get a permalink that way.

**Comment by TWiStErRob** [comment]
@firasdib that would force him to "Save" the regex, which may leak info from the users into your DB?

**Comment by mikechamberlain** [comment]
@firasdib thanks! I have been looking for this but didn't find it until now.
