### ISSUE TITLE
Have a "return" button on the regex debugger page

### ISSUE THREAD

**Issue by Chaddock** [firasdib/Regex101#294]
The regex debugger page does not have any *obvious* option to let the user return back to their regex. Clicking the "regex tester" *tab* is not obvious. A return button will be useful.

**Comment by firasdib** [comment]
Not sure where I could place it. The idea is that the "regex debugger"-button is a toggle button. Any suggestions?

**Comment by Chaddock** [comment]
Seeing as to how this affects all these "toggles", a quick-fix would be to add a "Back to your regex" link below the Tools menu. Either that or each tool should be prefixed by a checkbox; but that might be a li'l clunky.

That said, "format regex" does not appear to be a toggle. (It should probably be moved into the regex textfield much like the help icon in the modifier textfield.)

**Comment by firasdib** [comment]
Fixed in version2
