### ISSUE TITLE
Highlight the "Save regex" button better

### ISSUE THREAD

**Issue by Chaddock** [firasdib/Regex101#296]
Moving the "Save regex" option to the top of the list has made a big difference. But highlighting it better along the lines of the "old version" warning might improve usability even further.

The same applies for "update regex", but less so.

**Comment by firasdib** [comment]
Do you think highlighting the header is enough?

**Comment by Chaddock** [comment]
Perhaps add some colour to the icon as well? Animating it might be a li'l much.

Do you maintain statistics for user behaviour? Perhaps a tab can be maintained on how many users save their regexes and then things can be tweaked based on rise and fall in numbers.

**Comment by firasdib** [comment]
Adjusted in version 2
