### ISSUE TITLE
Rename "community" to "library" or similar

### ISSUE THREAD

**Issue by Chaddock** [firasdib/Regex101#297]
While it is a community feature, the "community" page is primarily a "library" or a repository of regexes and should be renamed accordingly.

FYI, I clicked on the "community" link for the first time today. By mistake :)

P.S. "Post to community" would also then need to be amended to something like "Add to library".

**Comment by re22** [comment]
Please guys, consider the name change.

**Comment by firasdib** [comment]
Agreed. Will adjust soon.

**Comment by firasdib** [comment]
Done
