### ISSUE TITLE
Please make a Java Flavored RegEx evaluator

### ISSUE THREAD

**Issue by razalghul** [firasdib/Regex101#298]
Please please please do this. I will donate. Java RegEx has slightly different rules, like requiring an extra backslash escape character. In the statement "\\d" versus other flavors only needing one backslash "'\d" to evaluate a digit.

**Comment by nhahtdh** [comment]
See https://github.com/firasdib/Regex101/issues/54

**Comment by razalghul** [comment]
Well I'm glad that other people want this as well.

On Mon, Jun 1, 2015 at 7:26 AM, Hong Dai Thanh <notifications@github.com>
wrote:

> See #54 <https://github.com/firasdib/Regex101/issues/54>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firasdib/Regex101/issues/298#issuecomment-107422082>.
>



-- 

--
Michael Cordero
Information Services

*CONFIDENTIALITY NOTICE: This e-mail transmission (and/or the attachments
accompanying it) may contain confidential information belonging to the
sender which is protected by the attorney-client privilege. The information
is intended only for the use of the intended recipient. If you are not the
intended recipient, you are hereby notified that any disclosure, copying,
distribution or the taking of any action in reliance upon the contents of
this information is strictly prohibited. Any unauthorized interception of
this transmission is illegal under the law. If you have received this
transmission in error, please promptly notify the sender by reply e-mail,
and then destroy all copies of the transmission.*
