### ISSUE TITLE
Allow donations/bounty to submitter (not just site)

### ISSUE THREAD

**Issue by ghost** [firasdib/Regex101#302]
RegEx is over my head, mostly because I just don't need to use it that often.  But when I do need to use it, I need it right away.  I hate to mooch of the experience of others.  Someone over in /r/RegEx was kind enough to whip up an expression for me to help solve a problem with a professional project I write.  I thought it would be cool to throw a little gratuity their way.  Or if my request wasn't getting any traction, I could offer a bounty for its solution.  If a bounty was offered, the expression could be hidden until after payment.  Payment could just be direct to submitter's PayPal which would be simple.  Or it could go to the site before being doled out to the submitter.  This way, the site owner can take a cut.

**Comment by firasdib** [comment]
This sounds like a fun idea. I'll think about it.

**Comment by firasdib** [comment]
I think this might be a little too ambitious for regex101 atm. There are great places for help, like SO and the IRC channel (linked on the website), for free.
