### ISSUE TITLE
Can type in the SUBSTITUTION output field

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#303]
1. Expand the SUBSTITUTION section.
2. You shouldn't be able to type text into the output field BELOW the SUBSTITUTION text input field.
3. Typing in capital letters (holding SHIFT+letter, not using CAPS LOCK) allows the text to be inserted.

**Comment by firasdib** [comment]
Interesting. How did you find that? I'll adjust it.

**Comment by OnlineCop** [comment]
I selected stuff and forgot that I was in the output box. It was letting me type (sometimes) and so I figured I'd post the results for your perusal.

**Comment by firasdib** [comment]
Fixed in v2
