### ISSUE TITLE
Python code generation fails with verbose regular expressions

### ISSUE THREAD

**Issue by badp** [firasdib/Regex101#305]
Python string literals cannot contain newlines unless you use `"""`-quotes. :)

So the code you generate:

    import re
    p = re.compile(ur'(?x)         # Verbose regexp                    
    ^            # Start of input                    
    $            # end of input                      ')

won't work, but this will:

    import re
    p = re.compile(ur"""(?x)         # Verbose regexp                    
    ^            # Start of input                    
    $            # end of input                      """)

...and if you could handle it, this would be even better:

    import re
    p = re.compile(ur"""
      (?x)         # Verbose regexp                    
      ^            # Start of input                    
      $            # end of input                      
    """)

**Comment by firasdib** [comment]
@nhahtdh Can you verify in v2?

**Comment by nhahtdh** [comment]
@firasdib See https://github.com/firasdib/Regex101/issues/577. I think there are some confusion due to changes in the later discussion, but we should use triple quoted string in COMMENT mode.

**Comment by firasdib** [comment]
@nhahtdh Is this issue fixed as a result of https://github.com/firasdib/Regex101/issues/577 ?

**Comment by nhahtdh** [comment]
Confirm fixed and close :+1: .
