### ISSUE TITLE
In Match Information I saw groups overlapping.  This should not be.

### ISSUE THREAD

**Issue by RobinLRandall** [firasdib/Regex101#306]
using my regex ^(.*)(\$\d\.\d*)(.*)$ on:

If I just type some text here $1.67 and stuff

         Match 1
I got:     1.         [0-30]     ...    Char 30  should not be in group 1 and  group 2.  Slices confuse here.
             2.         [30-35]   ...     Use ":" and not dash "-" if you are using slices.
             3.         [35-45]   ...

**Comment by nhahtdh** [comment]
The range is like what you would use in substring(start, end) function to get the string from index start to index (end - 1). There is no bug here.

**Comment by firasdib** [comment]
What @nhahtdh said
