### ISSUE TITLE
Signin Issue

### ISSUE THREAD

**Issue by taf008** [firasdib/Regex101#308]
Unable to signin usign either gmail or github. Signin with gmail reports reports a 'Redirect loop' error and with github just a blabk page is showing.

**Comment by firasdib** [comment]
Hmm, github stopped working for me but google still seems fine. Can you please try again to confirm?

**Comment by taf008** [comment]
Not successful once more, please find attached the screenshot for the error
I am getting. Thanks for checking the issue.

**Comment by firasdib** [comment]
I think you forgot to attach the screenshot.

Both github and google work for me now, odd.

**Comment by taf008** [comment]
Odd indeed,I might add, everything is back to normal now, Thanks again
