### ISSUE TITLE
Regex fails but in Javascript not!

### ISSUE THREAD

**Issue by sant123** [firasdib/Regex101#309]
Hi, this is the regex /[oó]/gi and the word is comunicación. It works fine, but when I capitalize the letter 'o' it does not work.
![image](https://cloud.githubusercontent.com/assets/7959437/8215313/ba713bf8-14f4-11e5-89d0-ac2a626b5ceb.png)

![image](https://cloud.githubusercontent.com/assets/7959437/8215337/d4d34f18-14f4-11e5-9559-5ad6e2bee66e.png)

**Comment by nhahtdh** [comment]
Use `u` flag for UTF-mode to enable case-insensitive matching for code points from 128 and above.
