### ISSUE TITLE
Newlines aren't copied from the Substitution output box in FF

### ISSUE THREAD

**Issue by Phoenixsong** [firasdib/Regex101#310]
1.  Use the latest release version of Firefox.
2.  Enter a test string containing newlines.
3.  Open the substitution section and select all + copy the output.
4.  Paste into a text editor.  Note that any newlines are replaced with a single space character.

I've been working around it by appending "\n" to my substitution format strings, which causes the output to be displayed as double-spaced in the browser, but copy-pastes correctly.

**Comment by firasdib** [comment]
Fixed in v2
