### ISSUE TITLE
pcre alternative pattern not matching as expected

### ISSUE THREAD

**Issue by bsweeney** [firasdib/Regex101#314]
`&(#(?:x[a-fA-F0-9]+|[0-9]+);)` does not match, for example, against the text `&amp;#8230;` though this does match in practice.

(credit to @scotteh for the regex via dompdf/dompdf#962)

**Comment by firasdib** [comment]
Please give me a link on regex101 with your example showing where it does not work

**Comment by bsweeney** [comment]
Here it is: https://regex101.com/r/oR9iQ1/1

**Comment by firasdib** [comment]
I don't see how that regex would ever match.

**Comment by bsweeney** [comment]
You're right. My bad. Was parsing the wrong text.

**Comment by bsweeney** [comment]
([actual match](https://regex101.com/r/oR9iQ1/2) is on text similar to `&#8230;`)

**Comment by firasdib** [comment]
I suspected as such, no problem :)!
