### ISSUE TITLE
SOH character \x01 not shown as space in test box

### ISSUE THREAD

**Issue by Eldaw** [firasdib/Regex101#315]
If I copy a FIX message, which uses SOH characters (\x01) to delimit fields, into the test box, those characters are not visible. For comparison, RegexBuddy shows the SOH characters as spaces in its test area (with the default Windows 1252 encoding).

**Comment by nhahtdh** [comment]
Works for me. I think it depends on the program from which the text is copied. However, note that some characters can never be used in the textbox (NUL character, for example), due to browser limitation.
