### ISSUE TITLE
Rename IRC to IRC Help or similar

### ISSUE THREAD

**Issue by Chaddock** [firasdib/Regex101#316]
A number of website users seem to join the #regex channel only to quit immediately without saying a word. Perhaps they are curious to know what the IRC menu does. Alternatively, users might not know that the IRC menu basically means "Live help". We might be taking it for granted that all programmers are acquainted with IRC.

The menu should probably be renamed and perhaps include an explanatory prompt before connecting to Freenode. It could be renamed to "IRC help" or even "Get help" :D

**Comment by firasdib** [comment]
Good idea.

**Comment by firasdib** [comment]
Fixed in v2
