### ISSUE TITLE
Support \U, \L and \E in replacement string syntax

### ISSUE THREAD

**Issue by lookfirst** [firasdib/Regex101#317]
https://regex101.com/r/mT5yJ4/1

also see:

https://youtrack.jetbrains.com/issue/IDEA-70451

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/214

**Comment by firasdib** [comment]
Upon close thought I might implement my own substitution syntax in the future.

**Comment by nhahtdh** [comment]
https://github.com/firasdib/Regex101/issues/387#issuecomment-164185978

**Comment by firasdib** [comment]
I have implemented `\U`/`\L` in version2. These tokens will uppercase/lowercase until the `\E` token has been reached.

**Comment by lookfirst** [comment]
👍
