### ISSUE TITLE
Add a "test" button

### ISSUE THREAD

**Issue by moham96** [firasdib/Regex101#319]
sometimes when i edit my regex i get an error message and it indicates that the  regex doesn't match the string (while in fact it does) and i have to wait for seconds and then it says that the regex matches the string or sometimes i cut the regex from the text field and paste it again to make regex101 test it again, so if you could add a button that i can click when i'm done editing the regex to test again it would be really helpful

**Comment by firasdib** [comment]
I have done my best to sort out these issues, hopefully a button like this is not necessary.
