### ISSUE TITLE
Wrong highlighting on Safari 8.0.7

### ISSUE THREAD

**Issue by purrrminator** [firasdib/Regex101#321]
![](http://monosnap.com/image/J5djZOyV3z18VhDM6NIlMV1C92PJJK.png)

**Comment by nhahtdh** [comment]
You should at least post a permalink to the test, your browser and OS.

**Comment by firasdib** [comment]
This edge case has been around for quite some time. Can you please provide more details?

**Comment by purrrminator** [comment]
@nhahtdh how can I obtain the permalink?

**Comment by purrrminator** [comment]
@nhahtdh @firasdib  related only to Safari (my is 8.0.7). https://regex101.com/r/rQ1pI0/1 the problem appears in certain moment when you slide the vertical separator in buggy position. http://monosnap.com/image/5AwcNu3Vp28a7074Ws7bvCBumHf42I.png

**Comment by firasdib** [comment]
Fixed in v2
