### ISSUE TITLE
Chrome app

### ISSUE THREAD

**Issue by hkaju** [firasdib/Regex101#322]
I would pay money (in addition to donating) to have Regex101 as a Chrome app that can be run offline.
I already use Regex101 whenever I need to write complex regexps but sometimes I don't have internet access so an offline app would be the killer feature for me.

**Comment by nhahtdh** [comment]
Related/dup: https://github.com/firasdib/Regex101/issues/76

**Comment by firasdib** [comment]
Thanks for the suggestion, and I agree. Time is just scarce at the moment. See #76
