### ISSUE TITLE
Substitution Issue while generating code in python

### ISSUE THREAD

**Issue by nitinmlvya** [firasdib/Regex101#324]
Using **SUBSTITUTION** on the Regex on *python*, **substitution(\1)** is not working fine. I generate the code. Below is the code:

*Your Code Generator Output:*

```
import re 

p = re.compile(ur'(http:)(.*?)(.org)(ontology|.*)')

test_str = u"http:dbpedia.orgontologySpaceShuttle"

subst = u"\1//\2\3/\4/"

result = re.sub(p, subst, test_str)
```

In **subst** variable, We need to insert **"r"**. So, **subst** variable should be like this **ur"\1//\2\3/\4/"**.
current status =>  ```subst = u"\1//\2\3/\4/"```
suggest status => ```subst = ur"\1//\2\3/\4/"```

Inserting **"r"** into **"subst"**, Issue get solved.

*Expected Code Generator Output:*

```
import re 

p = re.compile(ur'(http:)(.*?)(.org)(ontology|.*)')

test_str = u"http:dbpedia.orgontologySpaceShuttle"

subst = ur"\1//\2\3/\4/"

result = re.sub(p, subst, test_str)
```

Please fix that issue ASAP.

**Comment by firasdib** [comment]
@nhahtdh Can you verify if this is relevant in v2?

**Comment by nhahtdh** [comment]
Yep, it's still an issue. The safest way to do this is to convert it to normal Python string, rather than raw string, since you can't specify replacement text of `'"` in the raw string.

**Comment by nitinmlvya** [comment]
@nhahtdh: Shall I close this issue? Seems that it is resolved.

**Comment by nhahtdh** [comment]
@nitinmlvya No, it's wrong in both versions (old and new).

**Comment by firasdib** [comment]
@nhahtdh Is this fixed now?

**Comment by nhahtdh** [comment]
Confirmed fixed :+1: .
