### ISSUE TITLE
Private library (for dev/testing purposes)

### ISSUE THREAD

**Issue by Burnett01** [firasdib/Regex101#326]
Hey it'd be nice if one could save a regex in their 'private' account. Perhaps you can add a new button that says 'Add to account' or something like that. Why? Because I don't want wan't to browse all my browser-subs just to find my regex.  

I know this would require more database space, but why don't you add premium accounts or some sort of donator-features. Marketing: "Pay dem $$$ and receive your own library."

Eryone does that :+1:   NPM with their private npm-repo, Github private repos, pastebin Pro Accs, etc..

Okay, thanks.

**Comment by OnlineCop** [comment]
When you log in, either with Github or Google, you can save regexes and mark them as *favorites*. When you do, clicking *account* at the top of the regex101.com page shows you all regexes you've contributed to (your own and others), as well as all your *favorited* items.

Is this what you mean?

**Comment by Burnett01** [comment]
@OnlineCop  yes indeed! Thank you!
