### ISSUE TITLE
Regex is not working fine [PCRE]

### ISSUE THREAD

**Issue by dcarrasay** [firasdib/Regex101#329]
I have the following regex and the string:
Regex:
`/ *(?'PassengerNumber'[0-9]*\.(I\/)?[0-9])(?'PassengerLastName'[A-Z ]*)\/(?'PassengerNames'[A-Z ]*)/`

String:
`1.1SUINNOWENS/SHANNONTYLER KAUIONALANI
8.H-172892238 HK HA 1.1 SUINNOWENS/SHANNONTYLER`

Knowing that the regex is based in PCRE, this should match "1.1SUINNOWENS/SHANNONTYLER KAUIONALANI" in one time, instead match two times. I think this is a bug.

Thanks!

EDIT:
Permalink: https://regex101.com/r/fD8vL4/3

**Comment by nhahtdh** [comment]
Would you please include a permalink? And please format the code with ```` ``` ````

**Comment by dcarrasay** [comment]
Done! Do you have any suggestion or help?

**Comment by firasdib** [comment]
Try the `g`-flag

**Comment by dcarrasay** [comment]
Oh, works fine!I tried with `/ *(?'PassengerNumber'[0-9]*\.(I\/)?[0-9])(?!\s)(?'PassengerLastName'[A-Z ]*)\/(?'PassengerNames'[A-Z ]*)/`  (Adding lookahead  `(?!\s)` in my expression)  but I prefer add `g` flag.
Thanks guy!
