### ISSUE TITLE
$ end of string

### ISSUE THREAD

**Issue by wolfv6** [firasdib/Regex101#330]
regex o$ should highlight "o" at end of string for each line.
Currently $ only highlights for the last line.
![screenshot from 2015-07-25 10-30-00](https://cloud.githubusercontent.com/assets/1121166/8890289/254bb340-32b9-11e5-8502-869617d4cada.png)

**Comment by firasdib** [comment]
Thats a mighty small window. Try the `m`-flag

**Comment by wolfv6** [comment]
Thanks firasdib.   So I learned something new today - flag.
But now only the first line highlights the "o", where I am expecting all three lines to have the "o" highlighted.
![screenshot from 2015-07-25 22-42-40](https://cloud.githubusercontent.com/assets/1121166/8892606/dd8e3af8-331e-11e5-91d9-dde79c5c88d3.png)

**Comment by firasdib** [comment]
Try the `g`-flag

**Comment by wolfv6** [comment]
o$  gm worked beautifully.  Now all the o are highlighted.
This Regex101 is a very nice learning tool.
Thank you for making it.
