### ISSUE TITLE
RegEx not matching when copied and pasted from WordPad

### ISSUE THREAD

**Issue by dwardosa** [firasdib/Regex101#331]
When I copy and paste a RegEx from WordPad it loads fine in the Explanation, just fails to correctly match any matching strings. It works fine from Sublime Text, so I guess its a WordPad issue, and my fault for using it, just bringing it to your attention - Maybe issue with RTF? 

- Love the app though guys nice job

**Comment by dwardosa** [comment]
![image](https://cloud.githubusercontent.com/assets/10574539/8980707/954b3d6a-36aa-11e5-8c57-cf9d680ae208.png)

**Comment by firasdib** [comment]
Do you have a space at the end of your regex? It looks like you do. Remove it and it will work.
