### ISSUE TITLE
Regex Match Count not updated

### ISSUE THREAD

**Issue by sellcom** [firasdib/Regex101#332]
Regex101 seems only to find the FIRST match in large body of text. My recent test case involved pasting in subsequent paragraphs of text, and only the original 1st match was shown.
Deleting the text of the first match caused regex101 to hilite the NEXT match, but still a Count of "1", even though more matching text existed.

My regex:
https://regex101.com/r/pY7uV8/2

**Comment by firasdib** [comment]
Try the `g`-flag

**Comment by sellcom** [comment]
Argh. Sorry about that. I was switching between regextester.com and Regex101 and failed to notice missing g flag.
