### ISSUE TITLE
spaces not showing when placed at the end of the input box

### ISSUE THREAD

**Issue by florian-bailly** [firasdib/Regex101#334]
I think this proof will be enough to understand the issue :
![capture d ecran 2015-08-01 a 15 05 52](https://cloud.githubusercontent.com/assets/996915/9021934/d9c84bb2-385e-11e5-9332-67c89bbaf604.png)

**Comment by firasdib** [comment]
Interesting. I use the css property `white-space: pre-wrap` which I thought should handle this. Changing it to `pre` seems to solve it, but I don't know if this might break anything else.

**Comment by firasdib** [comment]
Fixed in v2
