### ISSUE TITLE
\d+ doesn't work anymore, whaaaat!?

### ISSUE THREAD

**Issue by aleksey-bykov** [firasdib/Regex101#335]
The website doesn't make any sense anymore. Please fix

**Comment by firasdib** [comment]
Please elaborate

Mvh Firas

**Comment by aleksey-bykov** [comment]
Go online. Try Javascript regexp \d+ on against 10px.

**Comment by firasdib** [comment]
Please post a permalink and what you expect.

**Comment by aleksey-bykov** [comment]
looks like it works again, nevermind
