### ISSUE TITLE
[Feature Request] Accept bitcoin donations

### ISSUE THREAD

**Issue by jonathancross** [firasdib/Regex101#336]
Would love to be able to tip you for this fantastic site using bitcoin.
Why Bitcoin? It allows people to make a tip with no account signup, no personal information being exposed and no loss to PayPal fees.  The recipient receives the full amount of bitcoin, or you can convert to your local currency automatically using a payment processor like BitPay.com or Coinbase.com

**Comment by firasdib** [comment]
I had a bitcoin address at some point which people donated to, but I would much prefer paypal for the sheer simplicity.
