### ISSUE TITLE
Add support for .NET regular expressions <feature request>

### ISSUE THREAD

**Issue by liwsoft** [firasdib/Regex101#337]
The following **.net-compatible regex** is not recognized because group balancing is not supported:

    \{(?>(?:"[^"]*(?:""[^"]*)*"|[^{}]+)|\{(?<n>)|\}(?<-n>))*(?(n)(?!))\}

At the following sample:

    TEXT{bbbbb}TEXT{cccc|{dddd}}TEXT{eeee|ff{gg}hh|ii{jj}"kk}{|{}ll""mm{nn}"oo|{pppp}}TEXT

It should yield 3 matches:

    {bbbbb}
    {cccc|{dddd}}
    {eeee|ff{gg}hh|ii{jj}"kk}{|{}ll""mm{nn}"oo|{pppp}}

You can easily verify validity of the above regex using online .net regex debuggers.

**Comment by nhahtdh** [comment]
Dup https://github.com/firasdib/Regex101/issues/156
