### ISSUE TITLE
[feature request] mod_rewrite RewriteRule support

### ISSUE THREAD

**Issue by jessetbenton** [firasdib/Regex101#338]
Support for RewriteRule matching and testing would really be awesome. From what I've read, mod_rewrite uses PCRE. I've found a few subtle differences from the existing pcre(php) option, such as forcing the escape of /.

**Comment by firasdib** [comment]
If it uses PCRE, just use the built in PCRE tester and export the syntax yourself. There is no good way for me to add support for something like this without being too invasive. You can change delimiters.
