### ISSUE TITLE
Voting on a regex library submission with a negative value more than once returns NaN

### ISSUE THREAD

**Issue by keegandonley** [firasdib/Regex101#340]
Clicking downvote on a submission in the regex library a second time (toggling the downvote) returns NaN if the value is less than or equal to 0.
![screen shot 2015-08-06 at 2 37 57 pm](https://cloud.githubusercontent.com/assets/12700819/9124054/a08ebcd0-3c48-11e5-8706-00524b1ce9d6.png)

**Comment by firasdib** [comment]
Fixed in v2
