### ISSUE TITLE
rtl languages

### ISSUE THREAD

**Issue by reza1615** [firasdib/Regex101#341]
I work on rtl unicode regexs. is it possible to add switch key to see rtl the right to left texts?
for example at https://regex101.com/r/uK9nA0/1
At TEST STRING by pressing Ctrl+Shift the text will be switch to right but the highlight box doesn't move to right and match to the matched text 
At the REGULAR EXPRESSION box using Ctrl+Shift is not possible!
We have many rtl languges such as Arabic, Persian, Hebrew ,...

**Comment by amire80** [comment]
I agree, this should be fixed - the alignment should follow the direction unless there's a good reason not to do it.

**Comment by ebraminio** [comment]
Yes, it would be useful. Please :)

**Comment by reza1615** [comment]
We added a botton which can solve this request. I uploaded your codes on
http://tools.wmflabs.org/rezabot/regex101/
please use the code inside view-source:http://tools.wmflabs.org/rezabot/regex101/
line 454 to end and line 269
thank your for your nice tool

**Comment by khaledannajar** [comment]
I have regular expression that accepts Arabic characters. The tool shows error at "\u" character which defines UTF8 characters. So I can't test it against Arabic characters. Please support it.
the regular expression:
^([a-zA-Z0-9\u0600-\u06ff](\\-|\\_|\\.|\\ )?(\\ )?)+$

**Comment by firasdib** [comment]
@khaledannajar Use `\x` with the `u` flag in PCRE or select the javascript flavor.

**Comment by firasdib** [comment]
This can be added for the actual editor areas, but as for the entire site, its too much work to do so and I'm afraid I can't implement it.

**Comment by reza1615** [comment]
it is only two line and I sent the code you only should copy and past :)

**Comment by firasdib** [comment]
@reza1615 But you see it breaks the page layout. For example, some components I have created assume text will be applied to the right of it, so it adds padding to the right. This is no longer correct in RTL as the padding should be applied to the left. Sure its possible, but it wont look good.

**Comment by reza1615** [comment]
When it is RTL
![01](https://cloud.githubusercontent.com/assets/2202483/16557655/62b760b0-41f6-11e6-98c9-3753baf262a4.png)
When it is LTR
![02](https://cloud.githubusercontent.com/assets/2202483/16557666/69db933e-41f6-11e6-8879-d27677eed945.png)
as you see we don't have any broken part the RTL screen had highlighted the text correctly

**Comment by firasdib** [comment]
I don't know what that button does, does it add `direction: rtl` to the entire page or only the editor?

**Comment by reza1615** [comment]
please test http://tools.wmflabs.org/rezabot/regex101/

**Comment by firasdib** [comment]
The website input fields have (limited) RTL support. With codemirror 6 on the horizon, this will be improved further.

There is also multi language support that can be used translate the website.

**Comment by omindatat** [comment]
it means it is solved or only just closed?

**Comment by firasdib** [comment]
I have done as much as I can. If you translate the site to arabic it can be made rtl too. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by reza1615** [comment]
why people should switch to another language UI to see RTL? many users use Windows or Linux or Mac 
 or websites like wikipedia (in English UI but still, they have access to RTL tools and directions. 
for example, I am a data analysis and I don't know anything about Arabic but I want to catch some words from an Arabic text. why should I switch to Arabic UI?
You can add an option in setting which allows the user to have a button for switching the REGEX, TEST STRING, EXPLANATION text boxes (only these parts is important for RTL)
Please take a look at [here](http://tools.wmflabs.org/rezabot/regex101/) the only parts should have toggle direction is shown at the below image.

![image](https://user-images.githubusercontent.com/2202483/50427671-40f0ca80-087c-11e9-87c2-01cecf58514c.png)

At below you can see ar.wikipedia.org with english UI but the text parts still in arabic so english guys can explore arabic wikipedia without confusing on the UI Language or direction

![image](https://user-images.githubusercontent.com/2202483/50427694-ead05700-087c-11e9-8bcc-c2b895b6539a.png)

**Comment by firasdib** [comment]
I will take this into consideration in the future, but it will depend on the codemirror support.

If you insert arabic text in the inputs, they will be automatically switched to RTL. But the support is still very limited.

That website you linked also runs an old version of my code, without my permission.

**Comment by reza1615** [comment]
> That website you linked also runs an old version of my code, without my permission.
2015 I requested for this simple feature and some days ago you closed it. you should know this request is so important for us because without changing RTL using your website for us is impossible.
I deactivated that page.
