### ISSUE TITLE
An error should be displayed when evaluating (a)?(?(1)(?R)c|b) on aabcc instead of hiding the error information in the debug view

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#343]
Regex

    (a)?(?(1)(?R)c|b)

Test string:

    aabcc

The error appears in the regex debugger, on the last line when expanding MATCH 1.

Permalink: https://regex101.com/r/nW6mC9/1

Doing some investigation reveals that the same error is observed on `pcretest`. However, I think it's better to display an error on the main UI, instead of saying the regex doesn't match the string.

**Comment by firasdib** [comment]
Hah,  `Funky error`- I forgot about that. This is a non-standard error that was caught. In this case, it's because it hits a recursive loop.

**Comment by firasdib** [comment]
Handling for cases like this have been dramatically improved. The error is handled gracefully and you are informed that there was an error while trying to match your expression. An error code (the one reported back from PCRE) is included in the message.
