### ISSUE TITLE
Code generator for java or android 

### ISSUE THREAD

**Issue by Joisar** [firasdib/Regex101#346]
Code generator is currently working great for php,javascript,python. It would be very useful if you can add code generator for java or android as well.

**Comment by thackel** [comment]
Just to speed up things ;-) 
http://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html
and
https://docs.oracle.com/javase/tutorial/java/data/characters.html
to see which characters need to be escaped (especially ",' and \\).

I would provide code, but there is no code...

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/245
