### ISSUE TITLE
Failure to detect adjacent quantifiers

### ISSUE THREAD

**Issue by rtm** [firasdib/Regex101#349]
The regexp

    \d{8}+

should be identified as an error, but it is not. Instead, it is parsed as

    \d{8}+ match a digit [0-9]
      Quantifier: {8}+ Exactly 8 times

**Comment by nhahtdh** [comment]
It's not an error. `+` is still meaningful for fixed quantifier.

Compare https://regex101.com/r/pK1oP0/1 and https://regex101.com/r/pK1oP0/2

**Comment by firasdib** [comment]
It's not invalid, it's a possessive quantifier. The explanation should mention this though.

**Comment by rtm** [comment]
Correctly identified as invalid syntax if JS mode selected. Closing.
