### ISSUE TITLE
Unit Test assertion dropdown shows defined groups are "capture" groups.

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#350]
https://regex101.com/r/vK4iX9/1

When looking at the Unit Test area, the dropdown next to 'assert that' is filled with

* regex
* matched result
* capture group 1
* capture group 2
* capture group 3

There are two definitions within the `(?(DEFINE)...)` block:

* `(?<named_group>[a-z])` and
* `(?<unused_group>[A-Z])`

I don't think those should be considered *capture groups* per se, as I found no way to actually match any values against them.

**Comment by firasdib** [comment]
This is a tricky case to handle, but I might be able to sort it out.

**Comment by firasdib** [comment]
This is still occurring in version2. Question is how we should handle this, what is the correct way?

**Comment by firasdib** [comment]
@nhahtdh / @OnlineCop thoughts?

**Comment by nhahtdh** [comment]
How about removing all the capturing groups found in `(?DEFINE)`?

**Comment by firasdib** [comment]
Well I only maintain one array of available subpatterns to be references for the entire regex, I don't distinguish from where they come. Technically you can refer to a subpattern like that, `(?(DEFINE)(?<name>test))\k<name>` is valid but won't match. And I don't think this scenario is going to come up often enough for this to be a problem. My idea is to just leave it.

**Comment by nhahtdh** [comment]
Didn't you have a parse tree when you build the explanation tree? Can you keep track of the capturing groups inside `(?(DEFINE))`

**Comment by firasdib** [comment]
I build the parse tree later on in the process to keep the initial parse fast. I could add something for the DEFINE-construct, but it does not feel worth it to me.

**Comment by firasdib** [comment]
Fixed and pushed to beta
