### ISSUE TITLE
Special characters in substitution

### ISSUE THREAD

**Issue by rugk** [firasdib/Regex101#353]
If I'm using characters like *\n* or *\t* in the substitution area on regexp101.com it will be replaced there too. (see https://regex101.com/r/kA2bC0/2)
However when I'm using a real PHP script (like [this](https://gist.github.com/rugk/1751ebe9c5d909c35242) for testing) I get another result, because *\n* and so on are not replaced in reality:
![regexptest](https://cloud.githubusercontent.com/assets/11966684/9361597/7246567c-469c-11e5-8028-fcd106d5a4f3.PNG)

PHP version 5.6.11

**Comment by nhahtdh** [comment]
In single quoted string `'...'`, `\n` and `\t` are not recognized as escape sequence. In your case, use double quoted string instead:

    $replacement="$1:\nThis is now \2\t\3";

**Comment by rugk** [comment]
Ah yes of course.
So it's not really the regexp-feature which is responsible for this, but the general string parsing.

Thanks for the reply. So as it is not an issue of regexp101.com I'm closing this now.
