### ISSUE TITLE
Metasymbol \v in Python

### ISSUE THREAD

**Issue by hwndx** [firasdib/Regex101#355]
On regex101.com, Javascript and Python flavor says `\v` matches any vertical whitespace character. After checking the documentation, it states that `\v` only matches the vertical tab.

**Comment by nhahtdh** [comment]
Apart from the wrong explanation, `\v` in Python implemented by regex101 actually matches new line (a vertical whitespace character), which is wrong.

Permalink: https://regex101.com/r/oM0eS8/1

**Comment by firasdib** [comment]
Fixed in v2
