### ISSUE TITLE
Can't type AltGr+S (ś) - saves the regex

### ISSUE THREAD

**Issue by mateon1** [firasdib/Regex101#356]
When you try to type a special character using `AltGr+S` instead of adding that character to the regex/text it saves the regex.

AltGr works the same as the combination of Alt and Ctrl pressed together. The fix would be to not save unless only the Ctrl modifier `keyEvent.ctrlKey` is active, but not `keyEvent.altKey` and `keyEvent.shiftKey`.

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/231
