### ISSUE TITLE
Support escaped \ characters

### ISSUE THREAD

**Issue by paulhickman** [firasdib/Regex101#358]
I know you can't add full support for .Net regular expression syntax, but it would be useful to support the escaping of \ characters that is necessary in .Net source - i.e. when the escaping option is enabled:

replace \" with " before parsing
replace \\ with \ before parsing

This option would be most useful on the regular expression, but could also be useful on the test string too

**Comment by nhahtdh** [comment]
If you want to write regex in .NET, use verbatim string. You only have to escape `"` by doubling it up `""`.

**Comment by paulhickman** [comment]
Verbatim strings work around it for many situations but not when you want to use c#6 string interpolation.

**Comment by nhahtdh** [comment]
Not sure if [this is the final version for string interpolation in C# 6](https://roslyn.codeplex.com/discussions/570614), but it seems to double up `"`, `{`, `}` to escape them, and `\` is treated as literal character.

**Comment by firasdib** [comment]
I don't think this is relevant for most of the users. Perhaps a section could be added in the code generator for this.
