### ISSUE TITLE
Group matches output by match number

### ISSUE THREAD

**Issue by landen99** [firasdib/Regex101#360]
I would really like to see a feature where the matches output box on the right can group the event field matches by event where all matches for each event fall under the column for the match name, even if some events do not have a match for a given field where it is blank, see below:
```
Match Num,field1, field2, field3
1,val1,val2,val3
2,value1,value2,value3
3,3v1,,3v3
```
I prefer Neither the current match format:
```
MATCH 1
Title	[0-35]	`Best Practices and Better Practices`
2.	[120-144]	` Speakers: Burch Simon |`
speakers	[131-142]	`Burch Simon`
time_date	[157-184]	`Tuesday, September 22, 2015`
time_start	[199-207]	`11:00 AM`
time_end	[220-228]	`11:45 AM`
location	[241-254]	`114 (Level 1)`
...
```
NOR the current csv output:
```
MATCH_NUM,GROUP,START,END,VALUE
1,"Title",0,35,"Best Practices and Better Practices"
1,2,120,144," Speakers: Burch Simon |"
1,"speakers",131,142,"Burch Simon"
1,"time_date",157,184,"Tuesday, September 22, 2015"
1,"time_start",199,207,"11:00 AM"
1,"time_end",220,228,"11:45 AM"
1,"location",241,254,"114 (Level 1)"
...
```
It would be much better to see (for the csv output part):
```
match_num;Title;2;speakers;time_date;time_start;time_end;location
1;Best Practices and Better Practices;Speakers: Burch Simon;Burch Simon;Tuesday, September 22, 2015;11:00 AM;11:45 AM;114 (Level 1)
```
I am using a ";" semi-colon because the data contains "," commas.  A delimiter choice would be very useful.  I don't see anywhere on the web where we can use regex to create a table of data from raw events, and that feature would be very valuable to me.  Perhaps the tabular format could be a toggle option.

**Comment by firasdib** [comment]
I'm a bit confused what you're trying to say here. Reopen if you still think its relevant.

**Comment by landen99** [comment]
It's still relevant.  I would like the matches to create a spreadsheet with columns for the field names and each match value filling the rows beneath them.

**Comment by firasdib** [comment]
Seems illogical to me. Why do you think this is better?

**Comment by landen99** [comment]
In the first place, spreadsheet style extractions allow me to take an event where the data is hidden deep within each event, and present it in a spreadsheet where the data is exposed and the eye can naturally track down the column from one row (event) to the next to see the trends.  Spreadsheet opens the data up to analytics beyond what the data is saying toward extraction anomalies to assist in discovering if and where the extraction is going wrong.  Otherwise, I have to scroll the list of events with a few visual spotchecks here and there.  Tools to catch bad extractions (captures) assist in determining if the pattern (regex) is correct or not.  stats count by field allows me to see the most common fields and the least common fields.  If a rare pattern yields a bad capture, I need to know that.  I deal with super big data (Splunk) and cannot afford to eyeball and evaluate every individual event and field capture.

**Comment by firasdib** [comment]
Ok. With the format you have requested I don't see how I could add the match position information though, which is a bit problematic.

**Comment by landen99** [comment]
How about this?:

Match #, field1, field2, field3
1, a1, b1, c1
2, a2, b2, c2
3, a3, b3, c3
etc.

where a1 is the value of field1 in match 1, etc.

**Comment by firasdib** [comment]
Yes, that works fine, but what about the capture position? The `START` and `END` columns below.

```
MATCH_NUM,GROUP,START,END,VALUE
```

**Comment by landen99** [comment]
While I never use the capture start and stop, I do see how they can be useful.  A checkbox for showing capture position would be useful to me.  I would prefer to have it in a different table if it was checked and to look like the following format:

Match #, field1_start, field1_end, field2_start, field2_end, etc
1, a1s, a1e, b1s, b1e, c1s, c1e
2, a2s, a2e, b2s, b2e, c2s, c2e
3, a3s, a3e, b3s, b3e, c3s, c3e
etc.

where a1s is the start position of the first field and a1e is the end position of field1.  While these positions could be put into the same table as the field values, I would have a lot of columns to delete before I could start looking at the data unless there was a way to uncheck the display of the position information.

**Comment by firasdib** [comment]
I see where you're coming from. I'll think about it and see what I decide to do :smile:

**Comment by landen99** [comment]
Thank you.

**Comment by firasdib** [comment]
I've reimplemented the export matches feature for v2 and I still haven't seen anyone request this feature again. I personally don't think the proposed data serialisation method is superior, and thus I've decided to omit it.
