### ISSUE TITLE
Wrong highlighting(?)

### ISSUE THREAD

**Issue by martijn-vdm** [firasdib/Regex101#362]
([\.|_])+ should match all dots and underscores. However, the highlights stop after the first occurence.

**Comment by nhahtdh** [comment]
`([.|_])+` also matches `|`. Stop using `|` inside character class...

That aside, without a permalink, it's unclear what your issue is... What is your input? Did you forget `g` flag?

**Comment by martijn-vdm** [comment]
I'm sorry, you're right -- I forgot about the g flag!
