### ISSUE TITLE
Add About page to Regex101

### ISSUE THREAD

**Issue by nowox** [firasdib/Regex101#366]
I am missing an "About regex101" page which describes:

- What will be the future of regex101
- What technologies are behind
- Who's the author
- What is the license of the source code
- How companies can use it
- How long a saved regex will be stored on the server

**Comment by Hamz-a** [comment]
Are you referring to the source code of the regexes posted on the website or the source code of the website itself? If the latter then there's no license since there's no source code available to start with.
See https://github.com/firasdib/Regex101/issues/6

**Comment by firasdib** [comment]
I will update the readme of this repo in time with this information.

**Comment by firasdib** [comment]
Done
