### ISSUE TITLE
Mask the $ (thank you for the money) when money was given

### ISSUE THREAD

**Issue by nowox** [firasdib/Regex101#367]
I would appreciate if the $ sign on the bottom left corner disappear if money was given.

**Comment by Hamz-a** [comment]
I think that technically it would not be feasible unless you have signed in on regex101.

**Comment by nowox** [comment]
Well, I always sign in :)

**Comment by firasdib** [comment]
The donation button is much less prominent on v2 and hopefully solves this issue.
