### ISSUE TITLE
Current State of RegEx101

### ISSUE THREAD

**Issue by firasdib** [firasdib/Regex101#369]
Hello everyone,

I get mails on a daily basis with requests, bug reports, suggestions, etc. I read them all, I really do - and it breaks my heart that I don't have the time to dive into it. I first want to thank you all for your help, your rigorous testing, and your offers to help (be it knowledge or just supplying hardware). And of course, all the donators.

But as you might have noticed, the issues have been stacking up since somewhere around this summer and the reason is I simply do not have the time anymore to maintain the website. This website was nothing but an ugly hacked together site initially; I just made it to help a few guys with regex. It grew and I kept hacking things together as time went by. It has now reached an unmaintainable point and would need a complete overhaul, since not even I remember what all the spaghetti code does.

Today, it's the largest regex testing website in the world and is being used by *a lot* of people. Shutting it down is not an option, but at the same time someone needs to maintain it and keep fixing bugs. So I guess the question is, what do you guys think should happen next? Does anyone feel they want to take this upon themselves and bring regex101 up 2 date?

Feel free to write your thoughts and ideas below.

Best regards,
Firas

**Comment by Hamz-a** [comment]
I think the day has come where you will need to answer this question https://github.com/firasdib/Regex101/issues/6 with a YES or NO (ie: make the source code available or not?). I understand the pros and cons but you could always make a private repository and cherry pick some contributors to handle and improve the website. See https://help.github.com/articles/issues-only-access-permissions/

**Comment by firasdib** [comment]
I would be happy to assemble a team that could help out and work on the site. I'm not ready to release the source at the moment.

**Comment by running-coder** [comment]
hey firasdib, just taking a couple mins to tell you GJ on the project, it's the best regex testing website I've seen by FAR! I use it all the time & showed it to my programmer buds!

Keep up the good work!

**Comment by firasdib** [comment]
Thanks for the kind words @running-coder

**Comment by Zenexer** [comment]
What technologies does it use?  I've noticed PHP 5.4 in the headers, as well as Underscore and jQuery.

It's a pretty awesome website.  I wonder if it would be more sustainable if there were perks for donors, thereby encouraging more donations.  If #302 were implemented, you could also take a cut.

How bad is the current code?  I may be open to contributing.

**Comment by firasdib** [comment]
@Zenexer You're right. I haven't used any framework to really structure the code, so it's basically just a mashup of my own stuff. It's not terrible, but ideally I would rewrite it using some sort of MVC-type framework.

**Comment by Erutan409** [comment]
I'd have questions about the knowledge requirements for maintaining the site.  Does someone need to be EXTREMELY proficient in RegEx to maintain the code or are you just looking for someone to be an optimizer for the code that satisfies "general" requests, etc.?

**Comment by firasdib** [comment]
You don't need to know much regex, perhaps if you want to work on the tokenizer since that uses a lot of regex. But for the general stuff you'll be fine if you're proficient in JS.

**Comment by OnlineCop** [comment]
I wouldn't mind helping. I've got a hefty amount of MVC under my belt, and think that it would probably be best if this project could be TDD from the get-go. I'd rather it take longer to fix bugs, but be able to fix new issues and be sure that they don't introduce other bugs, than just throw everything together spaghetti-style and hope nothing new breaks.

Realize, though, that life as a programmer may mean that I have to deal with work AND family first, so some days (hopefully not weeks) may pass before some bugs get my attention, but I'd still love to help.

**Comment by firasdib** [comment]
There has been a lot of chatter on IRC. I'll post my thoughts here.

A variable amount of people help work on the site, submitting pull requests, which are reviewed and integrated into master. The site will be entirely coded in javascript with a backend in whichever language. I use PHP now, since the backend doesn't really need to be complex and it works.

For the frontent I would like to play with react for the view, and perhaps backbone for the model + control - unless someone has any other suggestions?

The core of regex101 will be reused, that is, the explanation, regex tester, colorizer etc. Those things need to however be unit tested, something I have not had time to do. And probably also recoded a bit, since they have received a fair amount of hacking too.

**Comment by OnlineCop** [comment]
Just to be clear:

* **React** https://facebook.github.io/react/
* **Backbone** http://backbonejs.org/

Is that correct?

**Comment by firasdib** [comment]
Yes

**Comment by firasdib** [comment]
We have started development, anyone who wants to help (in any shape or form) may join slack, just contact me and I'll send you an invite.

**Comment by hobarrera** [comment]
> I would be happy to assemble a team that could help out and work on the site. I'm not ready to release the source at the moment.

I'm curious: Why not? We all know the pros, but, what are the cons of this?
