### ISSUE TITLE
unable to login with google

### ISSUE THREAD

**Issue by jedipunk** [firasdib/Regex101#370]
Tried in Chrome, IE11, and edge.

For what it is worth, it seems github login is broke, too.

**Comment by piecedigital** [comment]
Having the same issue. It seems as though the login process goes nowhere.

**Comment by Erutan409** [comment]
Same for Github.

**Comment by firasdib** [comment]
Sorry, fixed.

**Comment by Erutan409** [comment]
This appears to be an issue, again.

**Comment by firasdib** [comment]
Sorry, should be fixed now. This will be resolved with the site update thats in the works.

**Comment by Erutan409** [comment]
:+1:

**Comment by Erutan409** [comment]
Also, I can open up another issue if necessary, but I've noticed that there's been a ton of timeout errors when I load my profile of saved regexes when I am authenticated.  It's been happening for the last couple of weeks.

**Comment by hurie** [comment]
I tried today, and it didn't work.

**Comment by t1k3** [comment]
:up:
