### ISSUE TITLE
round brackets with X-modifier

### ISSUE THREAD

**Issue by EarthDweller** [firasdib/Regex101#371]
![2015-09-17 20-47-14](https://cloud.githubusercontent.com/assets/11925402/9941338/602b2ede-5d7d-11e5-9293-4f9f11443c7d.png)

*\\( Due to the X-modifier, this token is invalid. Any character following a \ without special meaning is faulted* – is it correct?

I thought round bracket is character with special meaning.

Pattern is works for PHP: 5.5.28;

**Comment by firasdib** [comment]
I would have to agree with you on this one.

**Comment by firasdib** [comment]
Fixed in v2
