### ISSUE TITLE
Remove weird drag-to-open panel

### ISSUE THREAD

**Issue by landaire** [firasdib/Regex101#376]
I visited regex101 for the first time today in a while and spent a couple of minutes trying to find where the quick reference had gone. What I thought was actually my scrollbar was the "drag zone" for the side panel which actually tells me I have to keep dragging in order to activate it. This is, in my opinion, terrible UX. The way it was prior was perfect.

**Comment by firasdib** [comment]
Its been like this for at least a year.

Mvh/Best regards,
Firas Dib
