### ISSUE TITLE
Get RegExp & unit tests via an API

### ISSUE THREAD

**Issue by rugk** [firasdib/Regex101#378]
It would be nice to be able to call regex101.com with a specific parameter, so that it executes the unit tests and returns the result.
This way you could e.g. use it in CI builds for testing regexp.

E.g.
https://regex101.com/r/qB3fX0/2?getunittest

could return a JSON or just plain-text reply like "10/10".
```json
{
  "executed": "10",
  "success": "10",
  "failed": "10",
}
```

Of course also more information would be possible:
```json
{
  "api": {
    "provider": "https://regex101.com",
    "version": "1.0",
  },
  "regexp": {
    "id": "qB3fX0",
    "version": "2",
  },
  "unittest": {
    "executed": "10",
    "success": "10",
    "failed": "10",
  },
}
```

And finally it would be better to be able to pass the unit tests to execute per POST. This way you don't have to add them to every regexp you create.
E.g. passing a JSON per post with a similar return like the examples above:
```json
{
  "unittest": {
    "1": {
      "str": "mailto:somebody@google.com",
      "check": "regex",
      "operator": "matches",
      "value": "",
    },
    "2": {
      "str": "mailto:somebody@google.com",
      "check": "capture group 3",
      "operator": "equals",
      "value": "mailto:",
  },
}
```

Related to https://github.com/firasdib/Regex101/issues/292, https://github.com/firasdib/Regex101/issues/318, https://github.com/firasdib/Regex101/issues/377

**Comment by nhahtdh** [comment]
While regex101 stores the data for the unit test on the server side, the regex execution runs on client side, so I guess this feature is pretty much impossible.

**Comment by rugk** [comment]
Yes, I thought this too. That's a thing which would be solved.
However if you already run the JS code by yourself (before calling the API) probably you don't really have to use regex101 as you can just test the RegExp by yourself.
So probably the only thing would be to use regexp101 to store the RegExp and the unit tests, to fetch them and to run them locally. This would be just a simple API for RegEx.

**Comment by JanPietrzyk** [comment]
:+1:

**Comment by Zarthus** [comment]
I think extracting them for your own would help reduce load on Regex101.com, but nevertheless some way to obtain Unit Test information would be neat.

**Comment by firasdib** [comment]
Version 2 has an api you can use for this purpose (only to fetch data).
