### ISSUE TITLE
Explanation broken for lookarounds in conditionals

### ISSUE THREAD

**Issue by mateon1** [firasdib/Regex101#381]
Minimal example: https://regex101.com/r/dG6oG5/1

When you look at the explanation, the lookahead in the conditional statement warns about an empty alternative and a redundant alternation, while it isn't empty, then lists the characters one-by-one, unlike in a lookahead that isn't in a conditional (lists the whole string of characters at once, doesn't warn about a falsely empty alternative).

**Comment by firasdib** [comment]
Fixed in v2
