### ISSUE TITLE
Minor layout issue

### ISSUE THREAD

**Issue by designdrumm** [firasdib/Regex101#383]
I noticed that the regex textarea is not responsive. In fact when shrunk down, it sizes down to 1px. Hard to see what you type.. :)

Just fyi really. Love this website. Would love an app for my iPhone 5.
Does this exist?

Best,
Karl

**Comment by OnlineCop** [comment]
A more platform-independent version is in the works, but no ETA on delivery date as of yet.

**Comment by designdrumm** [comment]
That would be an app I would get. Thanks for your response.

**Comment by nhahtdh** [comment]
This issue has been fixed in version 2 (not yet released at time of writing).
