### ISSUE TITLE
Newline is removed from SUBSTITUTION

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#384]
* Expand SUBSTITUTION
* TEST STRING value: `abc\n` (newline character, not `\\n`)
* Copy the substitution value, and there is no `\n` at the end of the string
* Change TEST STRING to `abc\n\n` and copy the substitution value
* Now it contains `abc\n` instead of `abc\n\n`

Seen from OS X Firefox 41.0.2 and OS X Chrome 46.0.2490.71

**Comment by firasdib** [comment]
See: #310

**Comment by firasdib** [comment]
This is still an issue in v2, but unsure how much I can do about it as it seems to be standard browser behavior, or something along those lines.

**Comment by firasdib** [comment]
Closing since this is a dup

**Comment by firasdib** [comment]
Pushed a fix to v2
