### ISSUE TITLE
Literal backslash in Javascript is not being converted in code generator

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#385]
https://regex101.com/r/yX8oH5/3

With the Javascript regular expression of `\\` with input of
`\home\something\something2\file.jpg`
the code generator should show
`var str = '\\home\\something\\something2\\file.jpg';`
but shows instead
`var str = '\home\something\something2\file.jpg';`

**Comment by firasdib** [comment]
Fixed in v2 (using es6 syntax)
