### ISSUE TITLE
Highlighting is sometimes too short in Firefox

### ISSUE THREAD

**Issue by jay** [firasdib/Regex101#386]
In Firefox I notice occasionally the highlighted portion of content is incorrect by being sized a few letters less than it should be. Unfortunately I don't have a basic test case, this is about as basic as I could get: https://regex101.com/r/yJ4mX7/1

![highlight sizing in ff](https://cloud.githubusercontent.com/assets/965580/10867289/ac6ee12a-8030-11e5-8fb5-fb092e83ae0f.gif)

Chrome seems to be unaffected.

**Comment by firasdib** [comment]
Thank you. I will be working on a generic fix for this.

**Comment by yasinallana** [comment]
try wrapping each of the matched characters with a span tag.should solve the problem pretty easily

**Comment by firasdib** [comment]
@yasinallana How would that help?

**Comment by yasinallana** [comment]
well since each character is wrapped in a span the issue would automatically disappear (no issue of the highlight width etc)

**Comment by firasdib** [comment]
Fixed in v2
