### ISSUE TITLE
Lowercase Named Capture Group in Replacement

### ISSUE THREAD

**Issue by Erutan409** [firasdib/Regex101#387]
Is there a way to lowercase the text captured in a named group when using it to replace text?  I see that there's [some documentation](http://bit.ly/1Pmq4PL) that refers to what I'm asking.  I figured out the way in which I use named capture groups in the replace by doing:

```
${namedCaptureGroup}
```

I was just curious if you could add some kind of '\L' prefix to facilitate this functionality:

```
\L${namedCaptureGroup}
```

Doesn't seem to work.  Thanks!

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/317

**Comment by firasdib** [comment]
Something like this could be implemented, but would be limited to regex101 only.

**Comment by Erutan409** [comment]
:+1:

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/317
