### ISSUE TITLE
Unit test by capture name

### ISSUE THREAD

**Issue by tbenst** [firasdib/Regex101#389]
I'm following a Test Driven Design workflow and do not know the capture group numbers ahead of time. Thus, I would like to define unit tests using named captures. Could this be added to the assert dropdown? Thanks for considering!

**Comment by nhahtdh** [comment]
I don't understand your use case. If it's Test Driven Design, you should write some code to test on your side rather than relying on regex101.

**Comment by tbenst** [comment]
Considering how nice of an environment Regex101 is for development, I'd much rather do it here.

Let's say I'm writing a regex to parse phone numbers of various formats and only want numbers for dialing without any extension information: +1 (123) 456-7890, 123.456.7890, +86123-456-7890x203, 1234567890#5555, etc. In a simple case it may be obvious that $1='+1', $2='123', $3='7890', but with more complex syntaxes the programmer may find it helpful or necessary to create a backreference (e.g. $2=\.) & thus cause the tests to fail due to syntactical reasons as now $2=\., $3='123'. With named references, this is not an issue, e.g. ${area}='123'

And if for some reason you don't buy this explanation, it increases readability & utility to write tests about ${foo} rather than $12.

**Comment by nhahtdh** [comment]
The feature is nice to have, but my point is, the unit test should be stored in your project's repo, not some website on the Internet. It also helps when you need to run automated testing.

**Comment by tbenst** [comment]
We are switchtracking:
http://www.npr.org/2015/09/22/434597124/trying-to-change-or-changing-the-subject-how-feedback-gets-derailed
- my feedback is that it would be a useful feature to have on the website.
Whether it's sufficiently useful for the time it would take to implement is
for you to decide.

Appreciate all the hard work--wonderful website!

**Comment by nhahtdh** [comment]
Since you mention TDD, it makes me wonder about your use case of the web site and how it integrates with your workflow. I'm just another user of regex101, and so far, I only consider it as a sandbox/demo hosting/debugger, not a place to reliably host the unit test.

I can see that the unit test feature is missing capturing group altogether (you can't even specify the group number to test), and it would be a nice feature to have.

**Comment by tbenst** [comment]
Group number works fine

<img width="1012" alt="screenshot" src="https://cloud.githubusercontent.com/assets/863327/11158528/9ea10a46-8a0d-11e5-9b65-22467d0939f2.png">

**Comment by firasdib** [comment]
Fixed in v2
<img width="424" alt="screen shot 2016-04-25 at 22 25 05" src="https://cloud.githubusercontent.com/assets/1335165/14797775/96dbfb10-0b34-11e6-93da-46814b19b779.png">

**Comment by tbenst** [comment]
Looks like a nice improvement! I'm not sure if this fully addresses the issue, however, as the assert statement is still dependent on "capture group 1".

Imagine the regex changed from "(?<name>foo(bar)|baz(?:bing))" to "(?<id>\d+):(?<name>foo(bar)|baz(?:bing))". If the assert statement uses named capture this would work, but as I understand the image above this would fail.

**Comment by OnlineCop** [comment]
![screen shot 2016-04-25 at 6 36 59 pm](https://cloud.githubusercontent.com/assets/1168697/14803260/48c921c4-0b15-11e6-9c8a-47d19646bd95.png)
![screen shot 2016-04-25 at 6 37 45 pm](https://cloud.githubusercontent.com/assets/1168697/14803264/4d04e138-0b15-11e6-83b7-140b27f74e6f.png)

Naturally, if you're going to change the parameters of what the pattern expects, it will break unit tests, just like in all other programming languages. This is trivially easy to modify, however.

**Comment by firasdib** [comment]
Agreed with @OnlineCop. Tests can easily be edited now so this is likely not a huge issue.

**Comment by tbenst** [comment]
Agreed that it's much easier now!

Still think there is value to named-capture unit tests, mainly for complex regex using recursion 

Here's a real-world example that I wrote using regex101 for a Sublime Text snippet--can't imagine doing it without your awesome debugger. I ended up writing my own named capture unit tests. Would be great to have it baked in natively though.

Test string: """x: int, y, as: as, z: str="A complicated  \"substring\" ", hah = [1, 2, 3, 4], h: int"""

Expected captures for <var>: x, y, as, z, hah, h.

Regex:
```
(?(DEFINE)(?'quote'(?:((?'q'["'])(?:(?!\k<q>|\\).)*(?:\\.(?:(?!\k<q>|\\).)*)*\k<q>))))
(?(DEFINE)(?'delim'(?:,\s?)))
(?(DEFINE)(?'paren'(?:(\((?>[^()]|(?&paren))*\)))))
(?(DEFINE)(?'brac'(?:(\[(?>[^\[\]]|(?&brac))*\]))))
(?(DEFINE)(?'curl'(?:(\{(?>[^\{\}]|(?&curl))*\}))))
(?(DEFINE)(?'equal'(?:=\s?(?:(?P>quote)|(?>\w+)|(?P>brac)|(?P>curl)|(?P>paren))(?:(?P>delim)|\z))))
(?'var'(?>\w+))((?>:\s\w+)(?:(?P>equal)|(?P>delim)|\z)|\s?(?P>equal)|(?P>delim)|\z)
```
