### ISSUE TITLE
Switch quick reference search filter on by default

### ISSUE THREAD

**Issue by Chaddock** [firasdib/Regex101#390]
Unsure if this is applicable for regex102: the quick reference filter/search feature is very handy. But it's a little tedious that it can be accessed only by clicking the magnifying glass icon. IMO, it should be switched on by default so that there's a search field below the "QUICK REFERENCE" panel heading or alternatively, allow the field to be triggered by clicking on either the magnifying glass or the "FULL REFERENCE" heading.

**Comment by firasdib** [comment]
Agreed.

**Comment by firasdib** [comment]
Fixed in v2
