### ISSUE TITLE
Add regex verbs to quick reference

### ISSUE THREAD

**Issue by Chaddock** [firasdib/Regex101#391]
Currently the only documentation on [verbs](http://perldoc.perl.org/perlre.html#Special-Backtracking-Control-Verbs) in the quick reference panel states

> Verbs allow for advanced control of the regex engine. Full specs can be found in pcre.txt

It'll be useful to expand this and add compatible verbs to the reference list.

**Comment by firasdib** [comment]
I'm fairly certain this is done for v2. Alan will verify.

**Comment by working-name** [comment]
Hi Chaddok,

Yes it is in the works, together with pretty much everything in pcre.txt. There's examples and a description accompanying each quick reference item.

**Comment by firasdib** [comment]
Closing as the issue has been adressed.
