### ISSUE TITLE
Emit javascript REs as escaped strings (feature request)

### ISSUE THREAD

**Issue by rdpoor** [firasdib/Regex101#392]
It could avoid a lot of head scratching and newcomer errors to offer the RE as an escaped string, maybe as part of the code generator.  Trivially you could replace \ with \\, and I'd be happy with just the following:

    $re = /^[\s]*(.*?)[\s]*$/
    // alternately: $re = new RegExp('^[\\s]*(.*?)[\\s]*$');

But if you wanted to go REALLY overboard (and had a lot of extra time on your hands), you could output the RE as a fully annotated string, much in the way that regex101 already does:

    $re = new RegExp(
        '^' +   // assert position at start of the string
        '[' +   // match a single character present in the list below
        '\\s' + //   match any white space character [\r\n\t\f]
        ']' +   // end of list
        '*' +   // Quantifier: * Between zero and unlimited times, as many times as possible, giving back as needed [greedy]
        '(' +   // Start of Capturing group 1:
        '.' +   //   matches any character (except newline)
        '*?' +  //   Quantifier: *? Between zero and unlimited times, as few times as possible, expanding as needed [lazy]
        ')' +   // End of Capturing group 1
        '[' +   // match a single character present in the list below
        '\\s' + //   match any white space character [\r\n\t\f ]
        ']' +   // end of list
        '*' +   // Quantifier: * Between zero and unlimited times, as many times as possible, giving back as needed [greedy]
        '$',    // assert position at end of the string
        'g'     // modifier: global. All matches (don't return on first match)
     );

... or some such madness.  That would be rather cool, since people could cut and past the annotated RE directly into their code.

**Comment by nhahtdh** [comment]
Your example of annotated RegExp is madness. It's harder to read than the bare regex without comment. Not saying that comments are redundant, just that it should tell the purpose of the regex, or explain a snippet of the regex, rather than a break down of the syntax.

**Comment by rdpoor** [comment]
I'm glad someone agrees that (as I said) it would be madness.

I'd be happy with a simple quoted string that could be copied and pasted... :)

**Comment by firasdib** [comment]
I don't quite see the point of this. Care to elaborate?

**Comment by rdpoor** [comment]
First, I hope that you understood the second version was tongue in cheek (as if "if you wanted to go REALLY overboard" and "some such madness" wasn't enough of a hint).

But the first version could be useful: I often build up REs using regex101 and then want to import it in my javascript code.  I use the string version as shown in the comment.  I cannot count how many times my copy and paste failed because I forgot to escape one of the \ characters.  So it would be trivial to implement, and it could be useful for those that need their javascript regexen in string from.

**Comment by nhahtdh** [comment]
@firasdib: I think this would be useful for people who use the site (inappropriately) for languages such as Java, where the regex subjects to double escaping, once in string literal and another in the regex syntax.

Also, I suppose it's useful for copy/pasta the string literal form of the regex when you are constructing a regex programmatically.

**Comment by firasdib** [comment]
Well I suppose. I'll see what I can do.

**Comment by firasdib** [comment]
I will add Java to the code generator in v2
