### ISSUE TITLE
Add .htaccess flavor (feature request)

### ISSUE THREAD

**Issue by Quantme** [firasdib/Regex101#393]
Greatest regex site I've seen.

It will be very useful a .htaccess flavor, adding flags for RewriteRule (desirable). I have to escape (\) many times and later delete them into .htaccess file.

*And alternative donation systems (google, bitcoin, etc.) I don't like PayPal.*

**Comment by nhahtdh** [comment]
.htaccess uses PCRE, as far as I know, but the flags are specific to processing URL. I think it would require a major change to regex101 interface if you were to implement this.

**Comment by firasdib** [comment]
What @nhahtdh said. I see no point of this, as the regex engine itself is compatible, and the UI would have to be modified to support this flavor.

I'll look into alternative donation systems :smile:
