### ISSUE TITLE
Export Unit Tests

### ISSUE THREAD

**Issue by jtpereyda** [firasdib/Regex101#397]
It'd be handy to download unit tests created on the site to put them into a Python unit test file.

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/378

**Comment by JanPietrzyk** [comment]
@nhahtdh I don't think so. Exporting the tests means code generation for different Plattforms & Unit Testing Frameworks to c&p the tests created to the local suite. Wich is what I was looking for when checking the tracker here.

So :+1:

**Comment by Zarthus** [comment]
Perhaps not entirely duplicate, but it would make sense to have the discussion on how you could retrieve unit test information there rather than at multiple places.

**Comment by firasdib** [comment]
Version 2 will have an API you can use to fetch data.
