### ISSUE TITLE
Generate multi-line input string in code generator

### ISSUE THREAD

**Issue by chrisgotter** [firasdib/Regex101#398]
could there be an option to have the code generator generate multi-line test strings? It is not a significant inconvenience but it would be nice.

**Comment by firasdib** [comment]
Yes, this will be looked into in the new version.

**Comment by firasdib** [comment]
Fixed in v2

**Comment by chrisgotter** [comment]
when will version 2 be released?

**Comment by firasdib** [comment]
When its done (hopefully soonish)
