### ISSUE TITLE
Preview a sed/vi-style replacement

### ISSUE THREAD

**Issue by roblevy** [firasdib/Regex101#399]
Love the site! It's my new favourite thing.

It'd be amazing if I could also preview `sed`-style replacements of the form:

```
> echo "How does this look now?" | sed 's/[A-Z]*[a-z]*/& &/g'
How How does does this this look look now now? 
```

**Comment by nhahtdh** [comment]
sed and vi has their own regex and replacement string syntax, so it's best if the whole flavor is supported rather than mixing the syntax and engines.

**Comment by Zarthus** [comment]
Duplicate of https://github.com/firasdib/Regex101/issues/196
