### ISSUE TITLE
Editing of my regex that in library

### ISSUE THREAD

**Issue by vitaly-zdanevich** [firasdib/Regex101#401]
I found that I can make my regex better but I can't update it - only remove, create new and add to the library.

**Comment by firasdib** [comment]
Just hit save again (update regex) in the left sidebar. Don't submit it to the library if you want to edit it again.

**Comment by vitaly-zdanevich** [comment]
And how can I now remove my old-version regex from library?

**Comment by firasdib** [comment]
You can not remove an entry submitted to the library. This might change in the future though.
