### ISSUE TITLE
Improper result for defined number of characters

### ISSUE THREAD

**Issue by arthurdn** [firasdib/Regex101#403]
Check (\\d\\.\\d\\.{0,1}\\d{0,1})(-)(\\d{9}) for this string 5.7.2-0000000000

**Comment by firasdib** [comment]
Whats the error?

**Comment by arthurdn** [comment]
0000000000 has 10 digits, but I specified 9 digits in the pattern.

**Comment by firasdib** [comment]
Yes, but your pattern is not anchored, so it does not care about the length of the test string. Try `/^(\d\.\d\.{0,1}\d{0,1})(-)(\d{9})$/`
