### ISSUE TITLE
Redundant check in JavaScript code generator for non-global regex

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#405]
The check

    if (m.index === re.lastIndex) {
            re.lastIndex++;
    }

is redundant when the regex is non-global (without `g` flag), since the `lastIndex` is always 0 in such case.

For example

    var re = /a*/; 
    var str = 'xyz';
    var m;
     
    if ((m = re.exec(str)) !== null) {
        if (m.index === re.lastIndex) {
            re.lastIndex++;
        }
        // View your result using the m-variable.
        // eg m[0] etc.
    }

can be simplified to

    var re = /a*/; 
    var str = 'xyz';
    var m;
     
    if ((m = re.exec(str)) !== null) {
        // View your result using the m-variable.
        // eg m[0] etc.
    }

**Comment by firasdib** [comment]
Thank you, will be adjusted. Unsure if you saw my previous comments, but please send me an email at `contact@regex101.com` - would love to chat with you real quick :smile:

**Comment by nhahtdh** [comment]
@firasdib I'll send an email later, but I think you know my email from when the site was before the redesign.

**Comment by firasdib** [comment]
Adjusted in new version.
