### ISSUE TITLE
Copy full regex in clipboard

### ISSUE THREAD

**Issue by eljuanchosf** [firasdib/Regex101#407]
It would be VERY usefull that when the user copies the content of the Regex textbox into the clipboard, the full Regex (including the beginning and trailing slashes as well as the modifiers) is copied. Example:
if the user wrote: `this.*will\swork`, when Cmd+C (or Ctrl+C) is pressed, `/this.*will\swork/gm` is copied in the clipboard.
If that is not possible, a "Copy full Regex" button will also work wonders.

Thank you!

**Comment by firasdib** [comment]
This is not a bad feature. Although you can not modify the clipboard (due to security reasons), and last time I checked, you would need a flash plugin to do so. So I'm not entirely sure if this is possible, and if it is, if its worth it.

**Comment by firasdib** [comment]
Quick google gave me this: http://stackoverflow.com/questions/2026335/how-to-add-extra-info-to-copied-web-text  - so might not be entirely impossible.

**Comment by eljuanchosf** [comment]
That is cool! Hope we lazy users can see that implemented soon. :-)
Remember also that a simple button can also do the trick. Thank you!!!

**Comment by firasdib** [comment]
Spoke with a few friends about this, they said it had its pros and cons. Some did not like it, some did. For example, some of them working in JAVA would hate it. I'm torn, I'll let the community decide.

**Comment by nhahtdh** [comment]
@eljuanchosf In the meanwhile, I think you can use the code generator to get your regex, already formatted for the language you are going to use the regex in.

**Comment by firasdib** [comment]
I wonder how useful this is going to be though. Maybe its easier to open the code generator and copy it from there instead?

**Comment by OnlineCop** [comment]
I was in favor of a "copy to clipboard" feature, but then had a few hangups.

- How would multiline patterns be represented? Do we show
```
s/line1
line2
line3
/replace1
replace2
/gm
```
or translate all newlines to `\r\n` or `\n`:
```
s/line1\nline2\nline3\n/replace1\nreplace2\n/gm
```

- Does it escape characters depending on the language, so `s/blah\nblah/` becomes `s/blah\\nblah/`?

- If the delimiter is changed, does it need to reflect as well? `s_search_replace_g`

- Do we copy it as a search pattern if SUBSTITUTION is collapsed and a replacement pattern if the SUBSTITUTION field is expanded?

- Would it fit better simply as "another language" for the code generator output?

**Comment by firasdib** [comment]
I agree, this becomes a bit messy. I believe the best thing is to open the code generator and copy it for the language you're using. Version 2 will have many more languages to chose from and a sleeker interface.
