### ISSUE TITLE
Copying text from "Substitution" textarea replaces newlines with spaces

### ISSUE THREAD

**Issue by borekb** [firasdib/Regex101#408]
For example, I see this in the Substitution output:

```
First line

Second line
```

but the clipboard only contains

```
First line Second line
```

**Comment by OnlineCop** [comment]
I am unable to reproduce this on Chrome 47.0.2526.80 (64-bit) on OS X. Please save an example and link it here so we can see the same results. Also let us know if this affects multiple browsers, or a specific one. Also, do any browser plugins affect the normal behavior of the `substitution` output? NoScript? AdBlock/Adblock Plus? WOT? GreaseMonkey?

**Comment by firasdib** [comment]
Duplicate of https://github.com/firasdib/Regex101/issues/310
