### ISSUE TITLE
Regular expression works in Regex101 but not in Python

### ISSUE THREAD

**Issue by ipserc** [firasdib/Regex101#410]
I'm having a problem with this regexp
(L-V):([LMXJV,]+):DE +(\d*:\d*) +A +(\d*:\d*)(\/| +Y +([LMXJV,]+):DE +(\d*:\d*) +A +(\d*:\d*))

It works in the web with the Python perspective. This is the text for using it. 
L-V:L,M,X,V:DE 08:30 A 14:30 Y J:DE 08:30 A 19:00/S:DESIN SERVICIO/Festivos:SIN SERVICIO

But in my code, it fails and doesn't match anything

...
        searchStr = "(L-V):([LMXJV,]+):DE +(\d*:\d*) +A +(\d*:\d*)(\/| +Y +([LMXJV,]+):DE +(\d*:\d*) +A +(\d*:\d*))"
       horarioStr = "L-V:L,M,X,V:DE 08:30 A 14:30 Y J:DE 08:30 A 19:00/S:DESIN SERVICIO/Festivos:SIN SERVICIO"
        match = re.search(searchStr,horarioStr)
        print("match.group(2)" +  match.group(2)) # <- here crashes 
...

Any suggestion?

Thanx in advance

**Comment by OnlineCop** [comment]
Can you edit your post and rewrite the code portion in Markup syntax? I think some of the characters were modified instead of staying as literal code.

**Comment by OnlineCop** [comment]
If I modified this correctly, https://regex101.com/r/wA3eK7/1 appears to have the regex that matches (I inserted `+` characters, although you may have actually done something like `\d{2}` instead of `\d+` to limit the numbers). Using the `code generator` on the left, I see that the string is using `ur` items immediately before the quoted string. Could this be what's going on?

**Comment by ipserc** [comment]
I'm very sorry, really, I've just noticed that the file from which I was loadind the lines has the Y i lowercase.

Thank you for your time and for answer me.

Sorry,

**Comment by ipserc** [comment]
Hi,

Finally I followed some of the hitns you gave me (Tons of thanks)

The final code I'm using is the following (Sorry cause it is Spanglish)

def escribeListaHorariosApertura(horarioStr):
    horario =""
    searchStr = "(L-V):(?:DE +(\d{2}:\d{2}) +A +(\d{2}:\d{2})(/| +Y +DE
+(\d{2}:\d{2}) +A +(\d{2}:\d{2}))|([LMXJV,]+):DE +(\d{2}:\d{2}) +A
+(\d{2}:\d{2})(/| +Y +([LMXJV,]+):DE +(\d{2}:\d{2}) +A +(\d{2}:\d{2})))"
    match = re.search(searchStr, horarioStr, re.IGNORECASE)
    if match:
        if match.group(7) is None:
            print("match.group(1):" + match.group(1))
            horario = procesaHorarioApertura(match.group(2), match.group(3))
        else:
            print("match.group(7)" +  match.group(7))
            horario = procesaHorarioAperturaExt(match.group(7),
match.group(8), match.group(9), match.group(11), match.group(12),
match.group(13))
    searchStr = "\/(S):(DE)+ +(\d{2}:\d{2}) +A +(\d{2}:\d{2})"
    match = re.search(searchStr, horarioStr, re.IGNORECASE)
    if match:
        horaTotal = formatHora(match.group(3)) + formatHora(match.group(4))
        horario = horario + ',{"diaSemana":"6","tramoHorario":"' +
horaTotal +'"}'
    searchStr = "\/(F)estivos:(DE)+ +(\d{2}:\d{2}) +A +(\d{2}:\d{2})"
    match = re.search(searchStr, horarioStr, re.IGNORECASE)
    if match:
        horaTotal = formatHora(match.group(3)) + formatHora(match.group(4))
        horario = horario + ',{"diaSemana":"7","tramoHorario":"' +
horaTotal +'"}'
    if horario != "":
        horario = horario + ']'
    return horario

IGNORECASE was the key

Thank you very much

Jose Luis
