### ISSUE TITLE
Bug in Regex Debugger for a look-behind pattern with astral plane character input

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#411]
Regex:
```
/(?<!ක)/ug
```
Input:
```
xd🀄abcde
```

Permalink: https://regex101.com/r/vC6wM9/1

When you click on Regex Debugger, the UI freezes. I found this error in the console:

> TypeError: callout_data[match_id] is undefined

**Comment by firasdib** [comment]
Fixed in v2
