### ISSUE TITLE
bug in python code generator 

### ISSUE THREAD

**Issue by aixi** [firasdib/Regex101#412]
import re
        p = re.compile(ur'(?<=\})([\n\s]*)(while[\n\s]*\(.*\);)')
        test_str = u"int main(void)\n{\n    while (1)\n    {\n        a = 1;\n        \n    }\n    for (a = 1; b < 2; b++)\n    {\n        sum = 1;\n        \n    }\n    if (a>1)\n    {\n        a = 2;\n        \n    }\n    else\n    {\n        a = 4;\n        \n    }\n    do\n    {\n        a = 1;\n        \n    }\n     while(1);\n    \n}"
        subst = u" \2"
        result = re.sub(p, subst, test_str)

this code is auto-generated,there is a bug

the variable subst should be a RAW string subst = ur'\2'

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/324
