### ISSUE TITLE
No matches for special characters?

### ISSUE THREAD

**Issue by matthewssa** [firasdib/Regex101#413]
Regex:

    [Cc][Ll][Ii][Cc][Kk]([_\-\s])[Hh][Ee][Rr][Ee]

Test String:
```
Click Here
Click-HEre
Click_here
```

**Comment by nhahtdh** [comment]
Please use 3 backticks `` ` `` to surround your code or indent it by 4 spaces, or post a permalink showing the bug.

**Comment by Zarthus** [comment]
Hi.

Regex101 is not at fault here, you need to use the 'g' flag, without it. Regex101 returns at the first match.

Your regex: https://regex101.com/r/dR4qE9/1
Fixed: https://regex101.com/r/dR4qE9/2

Extra note, you may use the `i` flag to enable case insensitivity, making the regex a lot more readable for one. https://regex101.com/r/dR4qE9/3
