### ISSUE TITLE
When hovering over matches in the match information, select the matches in the textbox.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#415]
I think it would be nice if I could hover over match information to then get the same sort of popover (or highlighted) in the textarea to easily find where the match is.

http://i.imgur.com/LZMEaM2.png

**Comment by firasdib** [comment]
I'll consider this for v2

**Comment by firasdib** [comment]
You can now click the matches in the right sidebar to have it highlighted in the text input.

**Comment by Zarthus** [comment]
:+1: excellent, was there a reason you didn't close the task? do you intend to do the same the other way around?

**Comment by firasdib** [comment]
Forgot to close it
