### ISSUE TITLE
IRC: Regex101 could randomize the names, rather than the client.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#416]
Hi,

Sometimes, the digits at IRC names can get confusing. I don't often see others fall in this pit, but I do.

Would it be possible to get a gfycat-style random-word-generation for names so they look less alike? or at simplest for Regex101 to change how many dots are in the URL, so that sometimes names have 1, 2, 3, or 5 digits?

I think this would reduce confusion as names don't all have the same length, and tab-completion also is easier to oversee if you got the right name.

**Comment by firasdib** [comment]
I just use freenodes qweb api, so nothing I can control really. Randomizing numbers works I suppose, but i'd rather not interfere too much.

**Comment by Zarthus** [comment]
Ultimately generating a new URL every page opening is what I had in mind.

```js
var name = generate_name();
var url = "https://webchat.freenode.net?channels=regex&nick=" + name;
```

**Comment by OnlineCop** [comment]
I actually like seeing a consistent naming scheme for the IRC nicknames. Knowing that someone is visiting IRC from the regex101 site, I can ask them to post examples on the site, and know full well that they know which site I refer to.

**Comment by Zarthus** [comment]
Oh, I do want the names to remain somewhat consistent. And am totally okay with the "regex101-" prefix.

I'd just prefer if there was something after that that was more different from the common visitor. It gets confusing the moment there is more than one person requesting assistance and skimming through the scrollback to see pending issues becomes annoying and easy to miss.

**Comment by firasdib** [comment]
Problem is I'll have to figure out if a nickname is taken or not, and have a list of words to create nicknames from etc etc. Don't feel its worth the hassle tbh

**Comment by Zarthus** [comment]
Webchat automatically appends a _ to a name if it is taken. The list of words definitely is a problem, but even something like the following is better than a random 4 digit number (in my opinion):

```js
function randomName() {
  var len = parseInt(Math.random() * 5) + 1;
  var charmap = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890';
  var name = 'regex101-';
  for (var i = 0; i < len; i++) {
    name += charmap[parseInt(Math.random() * charmap.length)];  
  }

  return name;
}
```

Produces:
```
regex101-KqsD
regex101-J
regex101-rR
regex101-pgzK
regex101-8KUz
regex101-uV3b
regex101-pDZ
regex101-W3DZK
regex101-vNFyB
regex101-2e
```

This is of course my personal preference. I just think it would help making more distinguishable names

**Comment by firasdib** [comment]
I don't see how random letters are any better than random numbers. And adding a dictionary to find words and stuff seems unnecessary.

**Comment by Zarthus** [comment]
The main thing is that the names have more variety to them and don't appear the same. It's too easy to get confused when there are more than two people asking support.

**Comment by firasdib** [comment]
Then I reckon we need to find a way to randomize words instead. Maybe we can use the programming language to grab keywords from it.

**Comment by Zarthus** [comment]
You can use something to fetch from `/usr/share/dict/`. It's not ideal but it's not a bad start. Overall, just keep in mind freenode's nick limit is 16 characters, leaving only 7 characters to randomly generate with `regex101-`.

**Comment by firasdib** [comment]
Hm. Using the local filesystem was not my intention, but just grabbing the keywords from JS, `var`,`while`, etc. I'll leave this open for further suggestions.

**Comment by Zarthus** [comment]
This is just the cherry on the top: but if you could get it to generate random words based on an IP hash (so that their names remain consistent as they reopen the page) that would be an excellent addition as well. I won't really blame you if you can't be arsed to do that - considering it's rather insignificant. But we have plenty of people rejoining thinking "this time I will fool them with my exact same question, expecting a different response!"

I think programmatic keywords are a bit too few, but that might just be me. I have no idea how the r101 backend is constructed so I can't really assist with implementation detail. But I'd just grab a bunch of words from the `/usr/share/dict` and use those, then append a random digit after it to still avoid accidental name collision. The biggest problem here is just getting the list and avoiding collision. I'll poll some opinions from #regex.

**Comment by firasdib** [comment]
Feel free to write something yourself in JS for the IP stuff, if you'd like.

**Comment by Zarthus** [comment]
Just having the backend generate some nick and then using JS localstorage to cache the name would work excellently too. If we store `re101-$name....` the WebChat software will take care of generating numbers for us. This sounds like the easiest (and best working) method I can think of.

**Comment by firasdib** [comment]
This has been implemented.
