### ISSUE TITLE
Match Information - group name bug

### ISSUE THREAD

**Issue by gethiox** [firasdib/Regex101#417]
When group was matched but was empty, "Match Information" window shows this group without label (display index only).
I think it is bug because python "re" module for regex provides empty string with correct group name, and also is logical for me that name is supposed to appear.

> Group with data:
> {'msg': 'a'}
> Empty group:
> {'msg': ''}

Here is an example on regex101: (first versus second version)
https://regex101.com/r/rM3sZ5/1
https://regex101.com/r/rM3sZ5/2

![screenshot](https://cloud.githubusercontent.com/assets/1618352/12173445/265526d8-b557-11e5-9162-9c5d3ec1b9fb.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/1618352/12173447/286bbb8a-b557-11e5-8d78-ef17bd67b030.png)

**Comment by firasdib** [comment]
Thanks, this is fixed in version 2.

**Comment by firasdib** [comment]
Fixed in v2

**Comment by jgehrcke** [comment]
Also running into this. Can we use this "version 2" already?

**Comment by firasdib** [comment]
@jgehrcke Not yet, but hopefully soon.
