### ISSUE TITLE
Named capture group loses name

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#422]
https://regex101.com/r/xP5kF3/1

MATCH INFORMATION on the right displays `test1_group` but `2` and `3` for the other captures.

Add a newline or any other whitespace to the end of the sample text.

MATCH INFORMATION on the right displays all 3 captured names: `test1_group`, `test2_group`, `test3_group`.

**NOTE:** This same problem does not appear to occur on the 2.0 version of the site.

**Comment by firasdib** [comment]
Fixed in v2
