### ISSUE TITLE
Substitution panel doesn't appear on Chrome

### ISSUE THREAD

**Issue by diego-vieira** [firasdib/Regex101#423]
When I click it doesn't shows up.
OSX El Capitan 10.11.3
Chrome 48.0.2564.97 (64-bit)

**Comment by firasdib** [comment]
I believe this is a bug with chrome, see this example: http://codepen.io/anon/pen/zroYWp

**Comment by diego-vieira** [comment]
@firasdib you're right, seems to be chrome.

**Comment by OnlineCop** [comment]
A temporary work-around that I've been using is to click `substitution` so it registers that it _should_ be open, then click `code generator` or `unit tests` on the left, and then close that view. The `substitution` area is again visible for me.

**Comment by diego-vieira** [comment]
Ah, I don't know why, but it started working again all of the sudden.

**Comment by OnlineCop** [comment]
Is your version of Chrome more recent than what you posted while you were seeing the problem?

**Comment by diego-vieira** [comment]
@OnlineCop yes, sorry, forgot to mention - Version 48.0.2564.116 (64-bit)

**Comment by firasdib** [comment]
Fixed in v2
