### ISSUE TITLE
Highlighting goes away

### ISSUE THREAD

**Issue by joshuaquiz** [firasdib/Regex101#424]
This started happening earlier this week, I opened two tabs of the site in Chrome and it has been acting funky since then.

![image](https://cloud.githubusercontent.com/assets/6497800/12680664/0d4d1bb8-c679-11e5-95d7-952d766136c4.png)

**Comment by firasdib** [comment]
Check the settings, it might have been flicked off. This will be resolved in the new version.

**Comment by firasdib** [comment]
Fixed in v2
