### ISSUE TITLE
Suggestion: Highlight matching parenthesis/bracket/brace

### ISSUE THREAD

**Issue by julianjensen** [firasdib/Regex101#425]
In the input box, when writing a regex with lots parentheses, it would be very helpful if, when the cursor is at one parenthesis, it would highlight the matching parenthesis. Substitute brackets and braces in the previous sentence for a three-in-one suggestion. :)

For example, if we have this:

```
.*@([^ ]+)(?: +?(?:\{(.*)\})?(?: +([^ \n]+))?)?
          ^ if cursor is here                ^ highlight this
// and vice-versa
          ^ highlight this                   ^ if cursor is here
```

Sometimes, in long expressions with lots of parentheses, it's easy to lose track of what ends up where.

~~As an additional bonus suggestion, it would be nice if there was an option (not a permanent 'on' feature) to display unprintable white space in the results panel, like carriage returns, tabs, and so on.~~

And a final bonus suggestion, not so simple, please consider the equivalent of an 'x' flag, which ignores white space in the regex (in other words, you have to explicitly indicate white space using \s) as this allows you to format a regex so it's easier to read. To run such a regex in JavaScript, for example, you would have to do this before running it against the input:

```js
let actualRegex = regexAsText.split( /\s+/ ).join( '' );
```

Combine that idea with a multi-line input box. :)

Anyways, just ideas. That first suggestion, however, would be really useful to me every day.

P.S. I donated some money to you. I have other, more powerful, regex tools, but I keep coming back to this one because it's so damn easy to use and has a clean uncluttered interface. Very nice work.

**Comment by julianjensen** [comment]
Just wanted to add that I realize that it will do the parentheses highlight if I turn on 'colorize syntax' but those colors make the whole regex much harder to read. Just an opinion, of course, but I feel that the colors are way too much. I guess what I am really asking for is just the highlight parentheses feature from the 'colorize syntax' without the colorizing. :) I also realized that the white space does already show up in the results window, so disregard that one. I should have checked with a better test.

**Comment by OnlineCop** [comment]
The logic to colorizing "some" of the pattern is the same logic that would colorize "all" of the tokens. The 2.0 version of the site has new theme support, so it should be easier to just highlight the braces without the other tokens.

**Comment by nhahtdh** [comment]
If you don't mind, would you please edit the original post and mark the parts you no longer need with `<s>`?

> And a final bonus suggestion, not so simple, please consider the equivalent of an 'x' flag, which ignores white space in the regex (in other words, you have to explicitly indicate white space using \s) as this allows you to format a regex so it's easier to read.

JavaScript does not support `x` flag. We don't want to confuse people by adding it. If you need `x` flag, use PCRE flavor instead. Do note that there are some differences in the matching semantic, though.

By the way, you indicate space by escaping it with `\`. `\s` is a character class of whitespace characters which includes newline. Don't over include when you don't mean to.

**Comment by firasdib** [comment]
The bracket matching highlight works as expected with or without syntax highlight being enabled in v2.
<img width="342" alt="screen shot 2016-04-25 at 22 11 12" src="https://cloud.githubusercontent.com/assets/1335165/14797350/a6a89b90-0b32-11e6-8991-b666c71baca7.png">
