### ISSUE TITLE
Multi-line modifier stopped working

### ISSUE THREAD

**Issue by foxylad** [firasdib/Regex101#426]
First, awesome tool. Thanks for your very generous contribution to the universe.

Since I last used it (several weeks ago) I think the multi-line modifier has stopped working. If I enter the regex `^.*$` and the modifier `m`, and enter the test string:

    Line 1
    Line 2
    Line 3
I expect all lines to match, whereas only the first does. Or am I doing something stupid?

Cheers!
Greg.

**Comment by OnlineCop** [comment]
The `m` modifier indeed matches `^` to the beginning of the line and `$` to the end. It will stop after the first match.

The `g` (global) modifier will continue matching to the end of the text, allowing all 3 lines match if they all match that pattern.
