### ISSUE TITLE
Unit test: allow comparison with 'nothing'

### ISSUE THREAD

**Issue by rentalhost** [firasdib/Regex101#428]
Currently you have four options to group result on unit test: starts with, ends with, contains and equals. But and if the group results in nothing? This situation is real and is annotated on unit fail:

> given the string [1000] assert that [capture group 1] [equals] [nothing] => [fail]

But is impossible check if group is equals to nothing, even using a empty value.

![image](https://cloud.githubusercontent.com/assets/421851/12787510/dc3b52ee-ca7c-11e5-9e18-668105c6bab8.png)

**Comment by firasdib** [comment]
Your regex doesn't match at all, so you could use that instead?

**Comment by rentalhost** [comment]
It's a simplified case, just to exemplify that a not matched group will return 'nothing' and it cannot be tested currently.

**Comment by firasdib** [comment]
Can you give me a non-simplified example please?

**Comment by rentalhost** [comment]
Now I understand. This [regex] should [don't match]. Thanks!
