### ISSUE TITLE
Partial matching

### ISSUE THREAD

**Issue by joepie91** [firasdib/Regex101#43]
I'm not sure to what degree this is possible (as I'm not familiar with the internal workings), but it would be great if it were possible to see partial matches, optionally filtered by a minimum match length (to prevent it from matching absolutely everything).

When debugging regular expressions, this would make it very easy to spot at what point a regex stops matching, when it _should_ be matching entirely.

**Comment by firasdib** [comment]
This is still nothing I've considered or thought to be of much use to be honest. I'd like to think if you end up with something like this, you're likely doing something wrong, but I'm sure there are exceptions.

What do you think @nhahtdh? PCRE does have the ability to report partial matches, but I'm unsure how to represent that information or what to do with it really.

**Comment by joepie91** [comment]
Well yes, if this occurs, you *would* be doing something wrong - that's why it'd be useful as a debugging tool :)

Sometimes you have to write rather complex expressions, and it might break because you've forgotten something like a `+` in a single place. That's kind of the usecase I'm envisioning here - the "display longest match" strategy I described would highlight everything *up to* that point where you forgot the `+`, thus making it obvious what the issue is.

For a (simplified) example, consider a regex like `/^[a-z]+[0-9]$/`:

```
aaabbbcccdddeeefffggghhh000111222333444555666777
                        ^ Longest match ends here
```

In that case, it'd be obvious at a glance that you *intended* to match multiple numbers, not just one.

There are two possible interpretations of "longest match", though, and I'm not sure which is ideal here, or whether it might even need both:

1. Longest match in target string by bytecount
2. Longest match in regex by 'amount of fulfilled tokens'

Especially when dealing with groups that have options of varying complexity, these two 'strategies' are likely to result in different results. I do think that both could be implemented on top of the debugger that is *already there*, without too much extra work or special requirements from the regex engine - simply iterate through the debugger steps and determine the longest match according to the above strategies.

**Comment by nhahtdh** [comment]
@firasdib This is the first I have heard about this capability, so I don't know what kind of information it returns to suggest anything. Do you have some example?

**Comment by firasdib** [comment]
@nhahtdh This article is good: http://man7.org/linux/man-pages/man3/pcrepartial.3.html

**Comment by firasdib** [comment]
The new debugger might make the partial matches clearer to see and follow. If its still not enough, please reopen.
