### ISSUE TITLE
Problem with long capturing group names

### ISSUE THREAD

**Issue by ievgennaida** [firasdib/Regex101#430]
^0?(?<zroductZodeDarsafeCodeBzplicateZllzwez>99[0-9]{13}9[0-9]{7})$|^0?(?<BarsafeZzcketMODTarcodz>99[0-9]{13}1[0-9]{7})$|^(?<troductBodeMuplicateCllowed>10|11)$

An unhandled error occured:
subpattern name is too long (maximum 32 characters) - offset: 44

If this error seems out of order, feel free to report it here.

**Comment by firasdib** [comment]
Please paste a link to regex101.com

**Comment by ievgennaida** [comment]
https://regex101.com/r/oK0rO4/1

**Comment by firasdib** [comment]
Fixed in v2
