### ISSUE TITLE
Remove matching from user I/O

### ISSUE THREAD

**Issue by frontenddeveloping** [firasdib/Regex101#434]
Then I have ~40000 matches javascript freeze user i/o. Chrome ask me to kill the tab.
If you will use WebWorker API you can prevent freeze.
Thanks.

**Comment by nhahtdh** [comment]
If I hazard a guess, the problem does not come from the regex execution, but from the time needed to render highlight and content of 40k matches on the page.

**Comment by luckydonald** [comment]
This is not about the regex itself, which is not highlighted any more?
![image](https://cloud.githubusercontent.com/assets/2737108/13676137/dbc4085e-e6e4-11e5-9e5f-fb26a9fcb842.png)

**Comment by OnlineCop** [comment]
The highlighting may have been toggled off. Check your settings in the top-right corner of the page.

**Comment by luckydonald** [comment]
@OnlineCop Oh, indeed was. Thanks :+1:

**Comment by nhahtdh** [comment]
[I have removed 3 irrelevant messages from this issue. Please make a new issue if your problem is about a different topic. Thanks.]

**Comment by frontenddeveloping** [comment]
@nhahtdh you can reproduce this issue very simple, just add big text and start regexp with dot (.)
This will affect every symbol. 

I just added source code of site and type `gmi` for options and `.` for source of regexp.
I/O was freeze for several seconds

**Comment by nhahtdh** [comment]
@frontenddeveloping I had done that when I posted my previous comment (dated Feb 16). As far as I know, the regex matching is already done by the WebWorker, so the delay is most likely due to the complex DOM that the browser has to render.

**Comment by frontenddeveloping** [comment]
@nhahtdh Chrome Profiles tab can provide some info:
https://drive.google.com/file/d/0B_IMUCr-vos4MEtNUEl4cTNqdlU/view

**Comment by firasdib** [comment]
This will be less of a problem with the new version I reckon

**Comment by firasdib** [comment]
This has been alleviated as much as possible in v2
