### ISSUE TITLE
Support for generating random strings matching a regexp

### ISSUE THREAD

**Issue by JensRantil** [firasdib/Regex101#435]
Hallå Firas!

This is a feature request to add support for generating random strings matching a regexp.

For the following reasons:
 * Useful for RegExp noobs to understand which strings that might match something they've types up.
 * Useful to get test strings when writing unit tests.

See also http://stackoverflow.com/questions/22115/using-regex-to-generate-strings-rather-than-match-them.

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/339, which is closed as won't fix.

As a side node, it's possible to even [encode NP-hard/NP-complete problem in a regex with look-ahead](https://codegolf.stackexchange.com/questions/39829/cops-and-robbers-regex-golf), making it infeasible to find a matching string.
