### ISSUE TITLE
Programming languages under "Code generator" could link to their regexp references

### ISSUE THREAD

**Issue by JensRantil** [firasdib/Regex101#436]
Improvement: Programming languages under "Code generator" could link to their regexp references.

 * Java: https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html
 * Python: https://docs.python.org/2/library/re.html
 * PHP/PCRE: http://php.net/manual/en/book.pcre.php

**Comment by JensRantil** [comment]
Woops, noticed Java wasn't officially supported, but JavaScript is. Please ignore Java in the description.

**Comment by firasdib** [comment]
Good idea :+1:

**Comment by firasdib** [comment]
This has implemented in version2, which I hope to release soon.
