### ISSUE TITLE
Emoji causes offset in highlighter

### ISSUE THREAD

**Issue by BenLeggieroNCR** [firasdib/Regex101#437]
Screenshot says it all: ([live example](https://regex101.com/r/vW3hZ7/1))

![screen shot 2016-02-18 at 17 52 28](https://cloud.githubusercontent.com/assets/10726457/13160916/8e84d424-d668-11e5-972b-98b62a08d1c1.png)

**Comment by nhahtdh** [comment]
Which browser are you using? Safari on Mac?

On a side note:

- Mozilla Firefox 44 on Windows renders correctly for the most part, except for the boxing character, which is quite an edge case.
- Chrome 48 on Windows renders with wrong offset.

**Comment by BenLeggieroNCR** [comment]
Chrome 48 for Mac OS X

**Comment by firasdib** [comment]
Fixed in v2

**Comment by BenLeggieroNCR** [comment]
Eh, close enough I guess :P

![screen shot 2016-04-25 at 14 06 11](https://cloud.githubusercontent.com/assets/10726457/14793827/0d74c7b6-0aef-11e6-9709-dec8ebe1c598.png)

**Comment by firasdib** [comment]
Thats still the old site, I'm talking about my new version thats not yet released
