### ISSUE TITLE
Suggestion: Button to move substitution to test string

### ISSUE THREAD

**Issue by mattbell87** [firasdib/Regex101#439]
I'd like to be able to click a button that: 

1. Clears the test string, then 
2. Moves the substitution to the test string, then
3. Puts input focus on the regex.

The main target audience would be people who are using this tool for replacements on a string rather than testing a regex for use in their application.

Some use cases:
* You need to substitute two or more different things in a string
* You've tidied up a few things and now you want to get rid of some extra newlines
* You've converted some HTML classes to CSS classes and now you want to get rid of the rest of the HTML

Here are a few suggestions for the name of the button:
* Use as test string
* Use
* :arrow_up: 
* Accept substitution
* Accept

**Comment by mattbell87** [comment]
Here is a concept of where the button could sit:
<img width="436" alt="screen shot 2016-02-26 at 9 49 08 am" src="https://cloud.githubusercontent.com/assets/2722612/13337211/3ddf6636-dc6e-11e5-989f-aee2c4f48cfc.png">

**Comment by nhahtdh** [comment]
Sounds like you want a text editor like Sublime Text or Notepad++...

**Comment by firasdib** [comment]
Been considering this again for quite some time. And again I've come to the conclusion that I don't think this is something I will implement. There is a handy copy button to grab all the contents on the new version, you can do the copy/paste yourself I reckon. It's not worth to put in the UI and clutter things up.

If you have any objections, lets her 'em 😄
