### ISSUE TITLE
Add replacement functionality

### ISSUE THREAD

**Issue by devonparsons** [firasdib/Regex101#44]
A la Javascript, 
str = str.replace(/^(my)(regex101)$/, '$1improved$2');

Specifically, 
1. Add an option for replacement.
2. If replacement is enabled, 
   a. Add a second input line, beneath the regex, to allow for the replace string
   b. Add a second text area, to the right of the current text area, showing the result of the replace

**Comment by SMerrill8** [comment]
the substitution panel can appear hidden - look on the bottom left edge of the screen and click to expand it.

**Comment by devonparsons** [comment]
Man I opened this ticket over 3 years ago and it's already been closed...
why respond?

**Comment by SMerrill8** [comment]
Customer Service. I responded to instruct others like myself who can't find the Replace panel, but browse here to find the answer. 

~ Shaun Merrill

**Comment by andreifilip123** [comment]
2 years later and still useful ! Thanks @SMerrill8

**Comment by SMerrill8** [comment]
Haha. Good to know!  I LOVE this site and use it every time I have a regex to write.

**Comment by alexfornuto** [comment]
It's 2020 and @SMerrill8 is still saving lost souls like my own! For anyone else still expecting the replacement to go in the main input field:
![image](https://user-images.githubusercontent.com/2349184/73288988-8b502380-41c1-11ea-8932-267cb0d55e33.png)
