### ISSUE TITLE
Sign-in icon on https://regex101.com/ is confusing

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#441]
The Sign-in icon in top-right corner of the page is normally means "exit". You should change it to more meaningful.It also doesn't changed, when user logged in.

**Comment by OnlineCop** [comment]
The sign-in icon actually comes from FontAwesome, where its icon is [pointing into the box](http://fortawesome.github.io/Font-Awesome/icon/sign-in/). The sign-out icon is [pointing out from the box](http://fortawesome.github.io/Font-Awesome/icon/sign-out/).

**Comment by MNF** [comment]
Hi,

I've put 2 browsers next to each other, and now I can see the difference,
when I know what to look for. I think that these icons are too similar are
their meaning is not intuitive for new users. It's better to have
additionally(or instead) text button "sign-in"/"sign-out" (hover tool-tip
is not sufficient)


​


Regards,
Michael Freidgeim

**Comment by luckydonald** [comment]
I second that.

**Comment by OnlineCop** [comment]
Since we are using the FontAwesome library for images/fonts, you can look through the [icons](http://fortawesome.github.io/Font-Awesome/icons/) they have and propose another icon. Changing the value is as simple as pointing from `\uf090` to the Unicode value of the new icon.

**Comment by luckydonald** [comment]
Let me try some constructive critic, here are my thoughts:

I believe a text button would be better.
Also the login might be grouped with the account tab in some way?

If a user is not logged in, there is no `account` tab, so there is some space left.
So if you are not logged in, you could use the space to display a text based "sign in" button.

Maybe the `twitter`, `contact` and `bug reports & suggestions` buttons in the top bar can be moved to the side bar above the other donation button, if more space is needed.

I quickly replaced the icon with the text, and doubled the with to `4em`. The text size is way to big, but the space is there.
![image](https://cloud.githubusercontent.com/assets/2737108/13676870/d32f8486-e6e7-11e5-85f2-29e58b2d73b4.png)

**Comment by firasdib** [comment]
This will be handled differently in the new version :smile:

**Comment by firasdib** [comment]
Fixed in v2

**Comment by luckydonald** [comment]
When will it go live?

**Comment by firasdib** [comment]
There is no date I'm afraid, I'm working as much as I can on it inbetween uni and work.

**Comment by luckydonald** [comment]
Just tell me when there is a beta, please 😄

**Comment by firasdib** [comment]
Absolutely 😄
