### ISSUE TITLE
Make Saved Expressions view customizable - to show all expanded or collapsed

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#443]
It will be good if user will have saved option to customize how Saved Expressions list will be opened, when account menu is clicked:
1. All collapsed.
2.All expanded(current view)

Additionally may be have option to hide language/date line, as it possibly not important for some users

**Comment by firasdib** [comment]
This has been implemented in a different way in version 2, after you've seen that we can revisit this issue I believe 😄
