### ISSUE TITLE
Show Saved Expression Title in Header Section

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#444]
In a list of my saved expressions it's possible to specify Title and Tags.  When I opened saved expression in the header of the page it shows version number, but not the title of the saved expression.

> REGULAR EXPRESSION —  version 4

It will be good to show the title(and optionally tags) for easy identification what the expression does

**Comment by firasdib** [comment]
Been thinking about this one lately. This is likely not going to play nice with all screen sizes and might end up cluttered. Displaying the title has some benefits, but it might also be confusing. I'm unsure if its truly that useful or not.

@OnlineCop thoughts?

**Comment by MNF** [comment]
You can show title and tags above the REGULAR EXPRESSION line. If the title or tags are too long, truncate them to max allowed length and show full string in tooltips.

**Comment by firasdib** [comment]
Added in v2
