### ISSUE TITLE
Run test button missing

### ISSUE THREAD

**Issue by reevu** [firasdib/Regex101#445]
![image](https://cloud.githubusercontent.com/assets/4651970/13523882/5c07cb3c-e1f8-11e5-98d4-b7961386db47.png)

**Comment by nhahtdh** [comment]
No repro on latest Firefox and Chrome. There should be a small arrow before 0/8. The same thing is available on "unit tests" selection on the left panel.

**Comment by reevu** [comment]
ok

**Comment by nhahtdh** [comment]
@reevu: What do you mean by "ok"? Did you find out what cause the bug? Can you still reproduce it? And if you can, what is your browser and OS?

**Comment by reevu** [comment]
@nhahtdh It's working now.
![image](https://cloud.githubusercontent.com/assets/4651970/13612009/931befa2-e565-11e5-8c8a-6b4d344215ff.png)
