### ISSUE TITLE
Error state doesn't resolve after correcting error

### ISSUE THREAD

**Issue by mrchief** [firasdib/Regex101#446]
- First, on page load there is this error

```
Uncaught TypeError: Cannot read property 'slice' of null            pcrelib16.js:1
```

 - Type in a valid expression, then introduce an error and correct it later. The error state doesn't resolve and you again get this error:

```
Uncaught TypeError: Cannot read property 'slice' of null           pcrelib16.js?cache=sucks:1 
```

See screenshot: 

![image](https://cloud.githubusercontent.com/assets/781818/13531181/35762e1e-e1f3-11e5-9b4b-cbc4547eb2e0.png)

And rest of the page doesn't work - i.e it fails to match valid matches.

**Comment by firasdib** [comment]
Weird, I can't reproduce. Can you post a permalink?

**Comment by mrchief** [comment]
Maybe a browser version issue? I'm on Chrome 50.0.2652.0 canary (64-bit), Win 7 x64.

https://regex101.com/r/sU4pZ4/1

**Comment by mrchief** [comment]
Works for me on IE11

**Comment by OnlineCop** [comment]
Can't reproduce in OS X Chrome 48.0.2564.116, Safari 9.0.3 (11601.4.4).

Do you have any blockers: AdBlock (Plus, Pro), NoScript, etc.?

**Comment by mrchief** [comment]
And on Chrome  48.0.2564.116 m... So yeah, I think its a canary issue. I don't have those blockers.

**Comment by mrchief** [comment]
Doesn't happen on Chrome 51.0.2667.0 canary (64-bit). Closing this.
