### ISSUE TITLE
Request: Add java/.net flavors

### ISSUE THREAD

**Issue by bangoker** [firasdib/Regex101#447]
It'd be useful if there was a Java / .Net flavor where the required regular expression has to match java/.net regex strings.

An example would be having to escape quote signs, so `\"` instead of `"`

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/54 / https://github.com/firasdib/Regex101/issues/245) and https://github.com/firasdib/Regex101/issues/156 / https://github.com/firasdib/Regex101/issues/320
