### ISSUE TITLE
codegen: Dart Language Support

### ISSUE THREAD

**Issue by kaendfinger** [firasdib/Regex101#45]
Support for Dart Code Generation, etc.

[Dart Site](https://www.dartlang.org/)

**Comment by chrisgotter** [comment]
isn't dart JS flavor?

**Comment by kaendfinger** [comment]
Yes, it is, however I specifically meant the Code Generator.

**Comment by firasdib** [comment]
I could add it if you give me sample codes for single match, global match and substitution like the other languages implement 😄

**Comment by kaendfinger** [comment]
@firasdib Awesome :)
```dart
RegExp regex = new RegExp("[A-Z]+");
if (regex.hasMatch("Hello World")) {
  Match match = regex.firstMatch("Hello World");
  Iterable<Match> matches = regex.allMatches("Hello World");
  "Hello World".replaceAll(regex, "ABC");
}
```

Dart has optional typing, but I decided to type it all so you can understand it better.

**Comment by Zarthus** [comment]
Howdy, 

I'm absolutely critically late to this issue, but I'm reorganizing a few things around in order to hopefully have a better organising around. Unfortunately your existing example isn't quite sufficient for a legitimate codegen entry. I'll hopefully have more details tomorrow to make contributing codegen entries easier.

**Comment by firasdib** [comment]
@kaendfinger Could you show me more detailed examples? You can look at any existing example on the website, to see the scope of the code required.

**Comment by firasdib** [comment]
Here's a guide for writing a code generator: https://github.com/firasdib/Regex101/wiki/Writing-a-Code-Generator

I can of course help, but I need you to get it started.

I'll close as there hasn't been a response for a long time. If you still want this, please reopen.

**Comment by mika76** [comment]
I think the code example posted in https://github.com/firasdib/Regex101/issues/45#issuecomment-213115822 is perfectly fine. It's pretty much the same as the C# code generated when selected.
