### ISSUE TITLE
Czech diacritics Upper case not matched with Ignore Case

### ISSUE THREAD

**Issue by cinkova** [firasdib/Regex101#450]
https://regex101.com/r/cO7nZ2/2 see červen matched but not Červen, while prosinec and Prosinec both match - otherwise it's cool, thank you!

**Comment by nhahtdh** [comment]
Since you are matching Unicode, use `u` mode: https://regex101.com/r/cO7nZ2/4

**Comment by cinkova** [comment]
Many thanks! 
silvie
