### ISSUE TITLE
Would be nice to have a feature to test replace with Regexp

### ISSUE THREAD

**Issue by vicneanschi** [firasdib/Regex101#451]
For example to show solutions for question like this
http://stackoverflow.com/questions/36046523/javascript-replace-square-brackets-in-a-string/36046619

**Comment by nhahtdh** [comment]
Already supported: https://regex101.com/r/yL5yG6/1

**Comment by vicneanschi** [comment]
Oops. Didn't notice it at the bottom of the screen. Could you make it more visible?

**Comment by OnlineCop** [comment]
The `substitution` field at the bottom of the page actually changes the generated regular expression. When it is collapsed, all the `code generator` output will simply match. If you expand `substitution`, all of the generated code changes into `replace()` or `replaceAll()` variants.

By default, it is collapsed so as to give the user more screen real estate.

**Comment by AdrianFahrbach** [comment]
I only found that function because I googled for it and found this issue. 
I think you should make that option more prominent since this isn't my first time using your tool and also not the first time I'm looking for that function.

**Comment by adarshmadrecha** [comment]
Agree with @AdrianFahrbach , same here. Googled how to test substitution and came across this issue.

**Comment by firasdib** [comment]
Any suggestion on how it can be made more prominent?


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by AdrianFahrbach** [comment]
> Any suggestion on how it can be made more prominent? Vänliga hälsningar / Best regards, Firas Dib
> […](#)
> On 13 Aug 2020, at 08:08, Adarsh Madrecha ***@***.***> wrote: ﻿ Agree with @AdrianFahrbach , same here. Googled how to test substitution and came across this issue. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I think the substitution tab should either be expanded by default (not always the case) or the tab chevron should be moved closer to the "Substitution" headline, so it's clear that thats something you can click.

**Comment by Doqnach** [comment]
What can also work is increasing the contrast of the pane header so people are more drawn to the bar being something to interact with.

**Comment by firasdib** [comment]
@Doqnach Could you help me visualize it?

**Comment by Doqnach** [comment]
I'm no designer, but:

![image](https://user-images.githubusercontent.com/25537191/90123148-a437b500-dd5e-11ea-8df4-aff1d48d2a81.png)

**Comment by firasdib** [comment]
Right, I understand. The current design language translates across all panels, including the right side panel. Could the chevron itself be highlighted in any meaningful way that would draw the attention to it?

**Comment by Doqnach** [comment]
Because it is placed on the right (like all the other pane headers), and people's focus on a screen is more or less an 'F' shape, I think putting something on the left with high contrast would be easier to notice. But still, it is rather packed to the bottom of the screen so that is still a bit of an issue UX wise I guess, causing people to miss it completely.

Other option would be some way at the very top (around the "Regular Expression pane") having some toggle to move between match and sub. Could be in the form of tabs or some toggle/switch button.

![image](https://user-images.githubusercontent.com/25537191/90125107-bc5d0380-dd61-11ea-8727-f3abf10efa7c.png)

**Comment by firasdib** [comment]
It would seem that a larger UX revamp is necessary, which would tie into the whole unit test design too. Perhaps a clickable option for both substitution and unit tests can be placed in the meft sidebar instead? Similar to how the flavor is picked. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by Doqnach** [comment]
![image](https://user-images.githubusercontent.com/25537191/90127557-acdfb980-dd65-11ea-9c1a-730d21e51a1b.png)

**Comment by firasdib** [comment]
I think that looks good. I'll try to work on that soon.

**Comment by firasdib** [comment]
I've implemented this, but the UX is not 100%. The issue arises when you try to save; its not quite clear if the substitution is going to be saved or not... If you go from subst to unit test, then save, are you intending to save the substitution or not? If you go back to matching, should the subst be saved?

**Comment by firasdib** [comment]
I'm going to push what I have live, and we can see how it feels.

**Comment by adarshmadrecha** [comment]
> I'm going to push what I have live, and we can see how it feels. 
@firasdib 

Looks good perfect to me. I am sure this will improve the usage of substitution testing. In case you use google analytics, it would be good to add an event to the clicking of "Substitution" to track how many users are using this.
