### ISSUE TITLE
App is not usable on the phone

### ISSUE THREAD

**Issue by anton-matosov** [firasdib/Regex101#453]
Please make app responsive

**Comment by anton-matosov** [comment]
![image](https://cloud.githubusercontent.com/assets/3339485/13868581/c49001da-ec87-11e5-8451-0658dc96cd33.png)

**Comment by nhahtdh** [comment]
I think it's already in v2

**Comment by OnlineCop** [comment]
Yes, v2 has improved this, specifically for mobile devices: http://imgur.com/a/GNIX8

It has, IIRC, about 12 different collapse options depending on the screen resolution, and works great on all tested smartphones, tablets, screens with low resolution, and 4k televisions.
