### ISSUE TITLE
Long regular expression gives a really unclear error

### ISSUE THREAD

**Issue by JamesDonnelly** [firasdib/Regex101#454]
I've written the following JavaScript regular expression:

    ^\[\s*(((-?([_a-z]|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))([_a-z0-9-]|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))*)|\\*)?|)?(-?([_a-z]|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))([_a-z0-9-]|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))*)\s*((\\^=|\\$=|\\*=|~=||=)\s*((-?([_a-z]|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))([_a-z0-9-]|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))*)|((\"([^\n\r\f\"]|\\n|\r\n|\r|\f|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))*\")|(\'([^\n\r\f\']|\\n|\r\n|\r|\f|(?![\u0000-\u0239]).*|((\\[0-9a-f]{1,6}(\r\n|[ \t\r\n\f])?)|\\[^\r\n\f0-9a-f]))*\')))\s*)?\]$

It compiles fine in Chrome, Firefox and IE, but the error Regex101 gives me is:

> `|` Alternator at this position effectively truncates the group, rendering any other tokens beyond this point useless

https://regex101.com/r/oH6jC3/1

It doesn't point out where this error actually is. I'm not sure if this is a Regex101 bug or if my regular expression genuinely does have this problem.

**Comment by OnlineCop** [comment]
You have `||` next to each other: `(\\^=|\\$=|\\*=|~=||=)`

**Comment by nhahtdh** [comment]
I personally think that it should be a warning instead of an error in this case. The syntax is technically valid in any of the languages.

**Comment by firasdib** [comment]
I'm a bit torn. It's always a design error and as such should be fixed, but as you said, its "valid".

**Comment by nhahtdh** [comment]
Just to be sure, did you fix this in v2, or did you decide not to fix it?

**Comment by firasdib** [comment]
I decided to leave it as an error.
