### ISSUE TITLE
Code generator for PowerShell

### ISSUE THREAD

**Issue by jcauthorn** [firasdib/Regex101#455]
Would love to see a PowerShell Regex Flavor option as there are differences with Powershell.

**Comment by nhahtdh** [comment]
PowerShell is implemented on top of .NET regex, so the engine is overlapped with https://github.com/firasdib/Regex101/issues/156

I will leave this open for the code generator feature.

**Comment by firasdib** [comment]
If you write a code template I can use I can include it in v2.

**Comment by jcauthorn** [comment]
Do you have a link to an existing template I can use as a guide to get started? 
This is the tech reference for it from Microsoft:
https://msdn.microsoft.com/en-us/library/az24scfc%28v=vs.100%29.aspx
Please let me know where to start to provide a template. Thanks,

+Jonathan

**Comment by nhahtdh** [comment]
Example for JavaScript.

Non-global mode (note the `if`):

    var re = /regex/; 
    var str = 'input string';
    var m;
     
    if ((m = re.exec(str)) !== null) {
        if (m.index === re.lastIndex) {
            re.lastIndex++;
        }
        // View your result using the m-variable.
        // eg m[0] etc.
    }

Global mode (note the `while`):

    var re = /regex/g; 
    var str = 'input string';
    var m;
     
    while ((m = re.exec(str)) !== null) {
        if (m.index === re.lastIndex) {
            re.lastIndex++;
        }
        // View your result using the m-variable.
        // eg m[0] etc.
    }

Replacement:

    var re = /regex/g; 
    var str = 'input string';
    var subst = 'replacement'; 
     
    var result = str.replace(re, subst);

The actual code for other languages may vary, depending on the combination of flags and whether you are matching only or also replacing text. What we want for the matching code is a piece of code that shows how to match the regex and extract all the matches (including capturing groups). What we want for the replacement code is a piece of code that shows how to replace text given a regex and replacement string.

**Comment by firasdib** [comment]
@jcauthorn Status on this? Is this still relevant?

**Comment by Zarthus** [comment]
Closing due to no response. If people still want this, please make a new issue (and try to keep codegen and flavour requests split if possible)
