### ISSUE TITLE
Chrome Beta Substution panel is off-screen and cannot be used

### ISSUE THREAD

**Issue by rwlaschin** [firasdib/Regex101#456]
Great tool.  Thanks.  One small issue.  

![image](https://cloud.githubusercontent.com/assets/2682324/14054551/67f9e24a-f297-11e5-86b0-80194756f1e6.png)

Windows 7
Chrome Version 50.0.2661.37 beta-m (64-bit)

**Comment by firasdib** [comment]
Does this happen on stable?

**Comment by OnlineCop** [comment]
This is, unfortunately, a known bug (see #423) with some of the latest versions of Chrome. I've been able to resolve this temporarily by clicking one of the side menu options (like `code generator`) and back, and then SUBSTITUTION appears again.

Clicking around the screen can also make the SUBSTITUTION handle shift around, and the same `code generator` (or any other side menu option) resets its position.

**Comment by rwlaschin** [comment]
Thanks.  Sorry I searched for the issue but didn't see it.  I hacked the css and made the test string dialog shorter and then I was able to use the substitution panel.  It seems to grow upwards instead of downwards.  Don't know if that helps or not.

**Comment by firasdib** [comment]
There has been some changes to the Flexbox spec which I need to take into consideration. Thanks for highlighting this

**Comment by StrikeForceZero** [comment]
removing `#regex_editor #main_editor` `float: left;` fixes it for me.
