### ISSUE TITLE
Bug in Python regex

### ISSUE THREAD

**Issue by rgouda** [firasdib/Regex101#457]
Hi,
It is a great site to quickly check regex. 

The site returns a search/replacement text on the following inputs:
**Regular Expression field input:** (?<=GP)\s*(?= LP)

**Test String field input:** GP    	     LP

**Generates output:** GP LP

However, if I run the above in Python with re.match, it is not a match. Tried on both 2.7 and 3.0 at Pythontutor.com.  Here is the Python code snippet - 

`import re`
`regex = '(?<=GP)\s*(?= LP)'`
`string = 'GP    	     LP'`
`print(re.match(regex, string))`

Is this a bug? Could this be fixed? Any help is much appreciated.

Thanks,
Gouda

**Comment by nhahtdh** [comment]
You used re.match without knowing that it anchors the match to the beginning of the string. See https://stackoverflow.com/questions/180986/what-is-the-difference-between-pythons-re-search-and-re-match/180993#180993

If you click on Code Generator, you will get the code with re.search, which does what you want:

    import re
    p = re.compile(ur'(?<=GP)\s*(?= LP)')
    test_str = u"GP LP"
     
    re.search(p, test_str)

**Comment by rgouda** [comment]
Thanks. That was helpful.
