### ISSUE TITLE
Wrong code is generated for PHP when Python flavor is selected

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#458]
Steps to reproduce:

- Write a regex with Python flavor selected (e.g. https://regex101.com/r/hL1yU1/1)
- Click on Code Generator

The regex string in the code generated for PHP tries to use `"` as delimiter (from Python) and produce code with syntax error:

    $re = ""^\\d+$"";

**Comment by firasdib** [comment]
Fixed in v2
