### ISSUE TITLE
Character class used within a character range does not throw an error

### ISSUE THREAD

**Issue by Sheldan** [firasdib/Regex101#460]
If I use the regex: `list=([\w-_]*)`, Regex101 does not throw an error, but this regex is invalid, as it uses a character class for the start of a character range.

I used this in the Python flavor.

**Comment by firasdib** [comment]
@nhahtdh can you verify?

**Comment by vsajip** [comment]
I can verify this. Simplifying, `regex101.com` accepts `[\w-_]`, but in Python this causes an error:

```
>>> re.compile(r'[\w-_]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
sre_constants.error: bad character range
>>>
```
The reason is that the hyphen is not at the end of the range, and Python tries to interpret this as a character range. However, if the regex is changed to `[\w_-]`, Python accepts this as a character set consisting of word chars, underscore and hyphen - as does `regex101.com`.

In Python mode, `regex101.com` should reject the first form as illegal, because Python does.

**Comment by nhahtdh** [comment]
I guess this is another discrepancy between Python and PCRE (and also JavaScript).

PCRE/JavaScript/Ruby (Onigmo) allows `-` which comes after a character class to be recognized as literal character. (There is no ambiguity here, anyway).

Python does not allow this, for some reason or another.

**Comment by vsajip** [comment]
Agreed, there's no ambiguity - this is a drawback of Python which has remained so, I think, for reasons of backwards compatibility.

**Comment by firasdib** [comment]
Fixed in v2

**Comment by nhahtdh** [comment]
Just to make sure this is implemented correctly, let me add some test cases.

### Pass

```
>>> re.compile(r'[\x04-]', re.DEBUG)
in
  literal 4
  literal 45
re.compile('[\\x04-]', re.DEBUG)
>>> re.compile(r'[\x04-\x45]', re.DEBUG)
in
  range (4, 69)
re.compile('[\\x04-\\x45]', re.DEBUG)
>>> re.compile(r'[\v-\x45]', re.DEBUG)
in
  range (11, 69)
re.compile('[\\v-\\x45]', re.DEBUG)
>>> re.compile(r'[-\v]', re.DEBUG)
in
  literal 45
  literal 11
re.compile('[-\\v]', re.DEBUG)
>>> re.compile(r'[\d-]', re.DEBUG)
in
  category category_digit
  literal 45
re.compile('[\\d-]', re.DEBUG)
>>> re.compile(r'[-\w]', re.DEBUG)
in
  literal 45
  category category_word
re.compile('[-\\w]', re.DEBUG)
```

### Fail

```
>>> re.compile(r'[\d-5]', re.DEBUG)
>>> re.compile(r'[5-\w]', re.DEBUG)
>>> re.compile(r'[\d-\w]', re.DEBUG)
```

**Comment by firasdib** [comment]
Fixed 100% + tests added
