### ISSUE TITLE
Incorrect string is generated when there are even number of backslashes in the input string

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#462]
Given the test string `\\`, the code generator should generate:

- `"\\\\"` or ~~`'\\'`~~ `'\\\\'` for PHP
- `"\\\\"` for JavaScript
- `u'\\\\'` or `ur'\\'` for Python

Currently, the string generated in regex101 only contains a single backslash for all 3 languages.

[Permalink](https://regex101.com/r/vS8iI2/1)

**Comment by firasdib** [comment]
@nhahtdh Can you verify this is an issue on v2?

**Comment by firasdib** [comment]
This seems fine to me. Please have a look at the latest escape util, and if you want, add some tests and run them to see.

**Comment by firasdib** [comment]
Still relevant?

**Comment by nhahtdh** [comment]
Still wrong for PHP and Python.

- PHP needs 4 slashes regardless
- Python needs 4 slashes since we are using normal string.

**Comment by nhahtdh** [comment]
Confirmed fixed :+1: .
