### ISSUE TITLE
Incorrect string is generated when single backslash is followed by single quote in the input string

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#463]
Given the test string `'''\'''`:

- In PHP, the generated string is `"'''\'''"`, which is correct, since `\'` is not recognized as an escape sequence, so both `\` and `'` are preserved.
- In JavaScript, the generated string is `'\'\'\'\'\'\''`, which is **missing the backslash**.
- In Python, the generated string is `u"'''\'''"`, which is **missing the backslash**, since `\'` is recognized as an escape sequence.

[Permalink](https://regex101.com/r/hJ2eL7/1)

**Comment by firasdib** [comment]
@nhahtdh Can you verify this is an issue on v2?

**Comment by nhahtdh** [comment]
This is still an issue in PHP - it generates `\'\'\'\'\'\'`, which misses the `\`. I suggest that you implement separate escape function for each of the language, since they have different behavior with their escapes.

To implement PHP's case **correctly** (but may not readable - esp. the case with lots of single quotes `'`), the code would be as simple as: `str.replace(/['\\]/g, "\\$&")` - no backslash counting needed.

I can confirm that PHP can eat null character in singly quoted string:
```
<?php

$str = "";
eval("\$str = '\x00\x01abc';");
echo strlen($str);
eval("\$str = '\x01abc';");
echo strlen($str);
eval("\$str = 'abcdefgh';");
echo strlen($str);
```

I need more research to suggest anything for other language.

**Comment by firasdib** [comment]
It seems to result in the correct results for me. Lets talk on Slack and write up some tests for it.

**Comment by firasdib** [comment]
Still relevant?

**Comment by nhahtdh** [comment]
The string above is correct, but Python fails for input `'''\'''```\```"""\"""`, not sure if I should open a new issue or not.

**Comment by firasdib** [comment]
@nhahtdh What does that mean?

**Comment by firasdib** [comment]
This has been adjusted. The editor requires you to escape every instance of the delimiter, so if you insert `"""` the editor will require you write `\"\"\"`. Does that work? Check it out on the site.

**Comment by nhahtdh** [comment]
It's not fixed. I'm not sure what you adjusted, but I'm talking about **Input String**/**Test String**.

This is what I see in Python:

```
test_str = "'''\'''```\```"""\""""
```

and I want it to be ``````""'''\\'''```\\```\"\"\"\\\"\"\"""`````` like the case of Java

**Comment by firasdib** [comment]
Fixed. Please try again. If still broken, join slack so we can figure this out together.

Please also verify related issues, #324 and #462

**Comment by nhahtdh** [comment]
Confirmed fixed :+1:
