### ISSUE TITLE
Infinite redirect loop in google login 

### ISSUE THREAD

**Issue by mbarkhau** [firasdib/Regex101#466]

**Comment by mbarkhau** [comment]
I hope this is easily reproducible for others, otherwise I'll add more info.

**Comment by LeightonSmallshire** [comment]
I am having the same problem. I cannot login through Github either.

**Comment by LeightonSmallshire** [comment]
I am having the same problem. I cannot login through Github either

**Comment by Zarthus** [comment]
I'm not able to reproduce. Can you tell me which browser you are using and if there are any errors in the console?

**Comment by firasdib** [comment]
This is fixed now, and will be permantently fixed in the new version.
