### ISSUE TITLE
Incorrect generated Javascript regex when the regex contain unescaped `{` and `}`

### ISSUE THREAD

**Issue by Olloth** [firasdib/Regex101#467]
Given the following:

Regex:

    \(\s*foo\s*{\s*([\s\S]*?)}\s*\)

Test string:

    (foo {foo blah})

My regex works as expected, with the flavor set to JavaScript.

But the generated JavaScript results in this:

    var re = /\(\s*foo\s*{\s*([\s\S]*?)}\s*\)/g;

Note that the first `{` is not escaped, which was fine in the input box, but is not fine in actual JavaScript.

**Comment by nhahtdh** [comment]
According to the specification of ECMAScript 5.1, you are right, `{` and `}` are not to be treated as literal character unless it is escaped. However, browser implementations are allowed to extend the grammar of the regex, and many allow `{` and `}` to be treated as literal character if they don't form a range quantifier, and many browsers do this.

In this regards, while regex101 does parse the regex to check for common syntax error, it doesn't check this case and let the browser decide whether the regex is valid or not. Basically, if the regex runs on your browser, the generated code will also run on your browser.

**Comment by Olloth** [comment]
Web dev is a magical creature. My IDE (IntelliJ) threw up an error so that's how I noticed.

Okay, well thanks for the information. I just wanted to do my duty and let the "bug" be known, I'll let you guys be the judge on if it's something that should be changed or not.

**Comment by firasdib** [comment]
yeah, I reckon we can leave this as is. Its common among most engines to treat `{}` as literals if they don't have numbers in them
