### ISSUE TITLE
Word boundaries does not validate with \b

### ISSUE THREAD

**Issue by dhurren-kelly** [firasdib/Regex101#468]
when using \b and a single word the word is not validated

**Comment by OnlineCop** [comment]
Could you give an example?

**Comment by OnlineCop** [comment]
https://regex101.com/r/wV3rB6/1 gives some sample text, and `\b` as the only element in the regular expression.

You'll notice that there is a very small blue highlight to the left of `abc`. That is the word boundary.

If you were to add the `g` flag so it will globally search, it will additionally show a blue highlight to the right of the letter 'c' in `abc`.

This is working properly in those cases.

**Comment by firasdib** [comment]
Closing as there seems to be no response.
