### ISSUE TITLE
Change the $re and $str order in the code generator

### ISSUE THREAD

**Issue by guile2912** [firasdib/Regex101#469]
Most of the time, the $str variable is just a test string that will be replaced in the real code.
But we are going to keep $re variable and the rest of the code as it is.
So can you please change the order of the $re and $str variable ( $str then $re ) so that a single copy past and no modifications afterwards are needed ? 
This can also prevent people from forgeting about the $str they just past and make their code just regex again a useless test value.

**Comment by firasdib** [comment]
I don't think this is worth the change, and generally prefer defining the regex above the string.
