### ISSUE TITLE
How can I delete/replace entry in a regex library.

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [firasdib/Regex101#472]
I've added an entry to the library. After this I found that data should be changed and updated the data.
I've submitted it again to the library, providing the same name and description, but now 2 entries are shown with the same name "replace-last-comma  with semicolon". 
How can I delete previous version?

**Comment by firasdib** [comment]
There is no way to currently change an entry to the library, but I could account for this in the new release. Any suggestions on how that would reasonably work?

**Comment by MNF** [comment]
I think, library reference can be kept as a part of my account list-  have a button  to publishe to the library and a button to delete from the library(probably locate them next to make public/private icon). I assume that the latest version will always be the one that published. 
If you want to have control which version number is published or not, you need to have version number drop-down to allow specify is selected version published or not.

**Comment by firasdib** [comment]
In the new version you can both edit and delete your entries.
