### ISSUE TITLE
Library search is case-sensitive

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#474]
When  doing search in library, it is case-sensitive, which is very inconvenient. Can you make it case-insensitive, please? 
Also loading of library is too slow now. I feel that previously it worked quicker.

**Comment by firasdib** [comment]
You're right on both points. This will be adjusted with the new version, the current version is poorly coded and outdated. Sorry for the inconvenience.

**Comment by firasdib** [comment]
Closing for now as its being adressed in the new release.
