### ISSUE TITLE
Do not show expressions title in UPPER case.

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#475]
When logged in, in "YOUR SAVED EXPRESSIONS" titles are shown in upper case.However when select Edit, original case of the title is shown.
It's much easier to read the string in case that was selected during the original save.

Also in library when select item from the list, on right expression details tab title is shown in upper case, but better to show in the original case.

**Comment by firasdib** [comment]
This is being reworked in v2.0, so expect this to be resolved in the future.
