### ISSUE TITLE
Failed match?

### ISSUE THREAD

**Issue by Dimpl** [firasdib/Regex101#476]
I think `^(00|11|(01|10)(00|11)*(01|10))*$` should match any binary string with an even number of 1's and 0's, but it doesn't match, for example, 011101.

**Comment by firasdib** [comment]
Matches for me.

**Comment by Dimpl** [comment]
Huh. I copied and pasted from a PDF, which messed up the *'s (though I retyped those)... maybe there was something else left over from the copy, like a hidden line break. Seems to work fine pasting from my original post.
