### ISSUE TITLE
Allow disabling of automatic closing bracket insertion

### ISSUE THREAD

**Issue by Zephilim** [firasdib/Regex101#477]
Please can you provide a flag or a switch to disable the automatic insertion of closing bracket. On the face of it, it seems like useful behaviour, but in reality it is a hindrance to the point of making the regex field impossible for writing experessions into without it being automatically interfered with. The work around at the moment, is to write your regex in an external editor then paste it into the regex field.
Just to be clear, when you type an opening bracket, the regex field automatically inserts the closing bracket. If you're trying to insert a bracket into a long and complicated expression, this is usually unhelpful because you lose track of which bracket you inserted particularly if that insertion changes the text wrapping.

**Comment by firasdib** [comment]
There is a setting for it that you can use to enable/disable it.

**Comment by Zephilim** [comment]
So there is
