### ISSUE TITLE
Add a free text field to enable user to write free fragments of regexes

### ISSUE THREAD

**Issue by Zephilim** [firasdib/Regex101#478]
When crafting a new regex, it would be useful if there was another pull up field (much like you can pull up the 'SUBSTITUTION' field by clicking the + button at the bottom of the page. Itr would be great if there was another one for a Free Text Field, where you could paste any fragments of regex as a holding area. The alternative at the moment, is to use an external text editor which can break up your work flow and can be inconvenient.

**Comment by firasdib** [comment]
I really don't think this is in the scope of the regex app I'm afraid.
