### ISSUE TITLE
Regex Library Load Failure

### ISSUE THREAD

**Issue by Lexus27** [firasdib/Regex101#480]
Loading freezes , but looking at the console to see that there was an error loading data , and so constantly , I was cleaning the cache

**Comment by Hastegan** [comment]
It does that because all the regex are loaded at the same time, one big request, if it times out, there is an error.
I don't know why it was made this way, but this is really something to improve.

**Comment by firasdib** [comment]
This will be fixed in version 2, the current version is terrible and fetches all entires at once.
