### ISSUE TITLE
Feature: Support for 'no more than' quantifier syntax

### ISSUE THREAD

**Issue by Epigene** [firasdib/Regex101#484]
I see the "at least" `/a{3,}/` example, but how about the "no more than"  `/a{,3}/` variant? Engines really not supporting those? Ruby engine does support it.

**Comment by nhahtdh** [comment]
It's not commonly supported for obvious reason. You can just add 0 as minimum bound to specify the same meaning `{0,3}`.

- PCRE doesn't support `{,3}` as quantifier, but it does not throw an error and instead treat it as literal string.
- JavaScript doesn't support `{,3}` as quantifier, and popular browsers just treat it has literal string.
- Python does support this syntax, but regex101 implements Python flavor by restricting features in PCRE engine, so regex101 is not accurate in this regards.

  ```
$ python3
Python 3.4.3 (default, May  5 2015, 17:58:45)
[GCC 4.9.2] on cygwin
>>> x = re.compile('a{,3}', re.DEBUG)
max_repeat 0 3
  literal 97
>>>
```

**Comment by Epigene** [comment]
Good to know. And `{0,3}` obviously works just fine.
