### ISSUE TITLE
Substitution box doesn't expand on click "+" button

### ISSUE THREAD

**Issue by xserrat** [firasdib/Regex101#485]
Hi,

I'm trying to make a regex substitution, but when I click to the plus icon in order to expand the substitution box, the icon toggle to minus icon but the substitution box doesn't expand...

Here a screenshot with the error case explained above:

![Error on expand substitution box](https://cloud.githubusercontent.com/assets/5933658/15275651/bbfd1792-1ad1-11e6-8076-ca22f6723543.png)

**Comment by nhahtdh** [comment]
Are you on Chrome? If that's the case, then this is dup of https://github.com/firasdib/Regex101/issues/456

**Comment by xserrat** [comment]
Yes @nhahtdh, I am on Chrome.

Sorry for opening this issue here. I'll follow this issue through #456.
