### ISSUE TITLE
Suggestion: predefined test strings

### ISSUE THREAD

**Issue by emlyn** [firasdib/Regex101#487]
It would be useful to be able to load the test string with some sample text without having to go and find something to copy and paste (see e.g. [RegExr](http://regexr.com)). There could be a drop down on the top right of the test string box with a few different versions.

**Comment by firasdib** [comment]
Not sure I follow here. What is it you're asking?

**Comment by emlyn** [comment]
Just some predefined blocks of text to easily load into the test string (with some normal English, some email addresses, web addresses, phone numbers etc) for testing regexes.

**Comment by firasdib** [comment]
There is the regex library. Its poorly coded as it stands now but will be refreshed in the new version.
