### ISSUE TITLE
Suggestion: comments on regex library

### ISSUE THREAD

**Issue by emlyn** [firasdib/Regex101#488]
The regex library is useful, but it would be better if we could post comments on submissions, for example to report bugs or suggest improvements.

**Comment by nhahtdh** [comment]
From what I see, you would need some sort of full-blown commenting system, [like what Gist has](https://gist.github.com/dperini/729294). I'm not sure whether regex101 is the right venue to bring all those discussion in, not to mention the effort needed to moderate those.

**Comment by emlyn** [comment]
I agree that a full blown commenting system would be a big change and might be overkill, but I think some way of flagging that a regex does not do what it says it does would make the library more useful.
For example the password validation regex (`/^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[0-9]).{6,})\S$/`) does not guarantee that there are no spaces, as it claims in the description (it accepts <code>"Aa0&nbsp;&nbsp;&nbsp;a"</code>).

**Comment by firasdib** [comment]
Is there an open commenting system we can just plug in place?

**Comment by Zarthus** [comment]
You could consider https://disqus.com/

**Comment by firasdib** [comment]
@Zarthus Could work. I'm not entirely sure how to tackle thing yet. I will have to sit down and think about the regex library first 😄

**Comment by Microserf** [comment]
I came here to make exactly this suggestion.

My use case is this: I'm looking for a regex pattern to validate e-mail addresses on an AngularJS signup form. Full RFC validation is too much, but the built-in Angular validation (i.e. doesn't require a TLD) is too little.

I see several JavaScript/email validation patterns in the library, but it's not always clear from the titles or descriptions what is in and what is out -- are TLDs supported? Are there any known bugs (i.e. two consecutive dots being allowed)?

The votes are definitely useful, but I feel like a simple threaded discussion board (with upvotes) attached to the descriptions would be really useful. (I'm picturing something like HackerNews has.)

**Comment by firasdib** [comment]
@Microserf There are inherently 3 problems with this:

1. Someone needs to moderate the comments
2. It needs to be coded (quite a bit of work, especially if we want to have something similar to what we have here on github)
3. Context of the comments. Should the comment be about the regex or how to use it? People might ask for help, which is not the right forum, etc.

I'm all for it, and I'm mainly limited by 2.

**Comment by firasdib** [comment]
This has been added.
