### ISSUE TITLE
Accept donation from different payment providers

### ISSUE THREAD

**Issue by Bema** [firasdib/Regex101#490]
I'd love to donate but don't work with paypal, it would be great if you worked with other providers like Flattr or Bitcoin.

**Comment by davidi17** [comment]
Agree

**Comment by davidi17** [comment]
Agree

**Comment by davidi17** [comment]
Agree

**Comment by DRSDavidSoft** [comment]
I agree too. Bitcoin can be used here whereas Paypal is blocked.

**Comment by jonhwilliams** [comment]
a lot of people in US seem to use Square Cash!  
I would say Bitcoin would be my 3rd choice after Google Wallet

**Comment by firasdib** [comment]
A few years have passed and I wonder what peoples stance is on this now.

**Comment by firasdib** [comment]
Closing due to lack of response.
