### ISSUE TITLE
Bash code generation

### ISSUE THREAD

**Issue by saschpe** [firasdib/Regex101#492]
Could be another option for easy copy-n-paste.

**Comment by OnlineCop** [comment]
Pure bash? Bash using command-line perl? Sed? Awk?

**Comment by nhahtdh** [comment]
Regex101 doesn't support BRE or ERE matching semantic (left-most longest match). Providing the bash code generation without it will just cause more confusion, unless it uses some tool that support Perl-like syntax and matching semantic (left-most "earliest" match).

**Comment by firasdib** [comment]
Issue seems to have gone stale, closing.

**Comment by nhahtdh** [comment]
@firasdib: If you see no merit in this issue, please add won't fix label. Otherwise, I see no reason for closing this, as the request is rather clear.

**Comment by firasdib** [comment]
@nhahtdh How is it clear? He did not answer any question asked.

**Comment by nhahtdh** [comment]
Ah, OK, I have my browser scrolled down and didn't read previous discussion. I was having my own assumption that it's the `=~` operator when they talk about `bash` and regex, but other people may think it's sed and awk. Well, if people want them, then they can open a new issue with a more specific description then.
