### ISSUE TITLE
false Unescaped Delimiter error

### ISSUE THREAD

**Issue by gcbw** [firasdib/Regex101#493]
Inside character classes, the [only special chars](http://www.regular-expressions.info/charclass.html) are `]^-\`. The regex delimiter (whichever it is at the time) should not matter.

yet, i get an "Unescaped delimiter" error for the [valid regex](https://www.debuggex.com/r/dPMDO4_nt9nkfvDm): `/[/]/` (which should match `/`

test case: https://jsfiddle.net/7y4gczzn/

**Comment by nhahtdh** [comment]
Confirm that this is a bug, since according to ECMAScript specs, the regex above passes the lexical check for [Regular Expression Literal](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-literals-regular-expression-literals).

**Comment by OnlineCop** [comment]
Both the Javascript (https://regex101.com/r/gP4dA4/1) and Python (https://regex101.com/r/gP4dA4/2) flavors of `[/]` produce a match, while PCRE does not. This is also consistent across multiple websites as well: Javascript support across the board appears to accept `[/]` while the PCRE implementation of the same sometimes match and sometimes don't, depending on how the site authors implemented the feature.

**Comment by nhahtdh** [comment]
In PCRE, `/[/]/` doesn't work:

```
$ pcretest
PCRE version 8.37 2015-04-28

  re> @abc@
data> abcjdejk
 0: abc
data>
  re> /[/]/
** Unknown modifier ']'
  re>
```

Even if it works, I don't think you can use the same code in PHP anyway.

Python doesn't need the delimiter, so `/` doesn't need to be escaped.

JavaScript standard allows the regex above, so our implementation has a bug here.

**Comment by firasdib** [comment]
PHP does not allow for `/[/]/` - their delimiter parsing is very limited.

**Comment by firasdib** [comment]
I think we can agree the current behavior in regex101 is sufficient?

**Comment by nhahtdh** [comment]
Yes, I just tested JavaScript, and the problem seems to have been fixed.
