### ISSUE TITLE
after clicking unit test there is no obvious way to return to normal view.

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#494]
I've clicked unit tests to see what the page does. After this I wanted to return back to normal regular expressions view. Unfortunately I didn't find  a way to return to normal view.
I had to refresh the page.

Could you please provide a link/button to return to the normal view from unit tests view

**Comment by OnlineCop** [comment]
Clicking `unit tests` again will return you back to the same view as before. The same goes with `code generator` and `regex debugger`.

Additionally in either `code generator` or `regex debugger` (but not `unit tests`), hitting ESC will close the windows.

The new version of the site already has this addressed with an 'x' button in the corner of the window. The new site will be available in the coming months.
