### ISSUE TITLE
Regex101 shows group captures as matches

### ISSUE THREAD

**Issue by MNF** [firasdib/Regex101#495]
I've used regex [https://regex101.com/r/eE0bO3/3](https://regex101.com/r/eE0bO3/3) with capturing and non-capturing groups
`(?:(3[47][0-9]{13})(?:\D))`
and for string
`378282246310005is Amex`
on a right panel it was shown

> MATCH 1
> 1.    [0-15] `378282246310005`

I've tried to use the regex in .Net and it showed that the match is 378282246310005i ( including last letter 'i'). The number 378282246310005 is not a full match, but capture of the first capturing group.
I checked http://regexstorm.net/tester, and it has the same terminology.

Even if regex101 way to describe match is more intuitive(as people normally concerned only about capturing groups), it doesn't follow standard terminology.

It will be better to show it similar to the following (from http://stackoverflow.com/a/3513858/52277)
Match "http://stackoverflow.com/"
     Group 1: "stackoverflow.com"
     Group 2: "/"

**Comment by nhahtdh** [comment]
It seems to be a dup of this one https://github.com/firasdib/Regex101/issues/27, which has been resolved in v2.
