### ISSUE TITLE
Improvement Suggestion - Append line break for replace output 

### ISSUE THREAD

**Issue by alexculea** [firasdib/Regex101#496]
Hi everyone,

Because the replace output is generated into the form shown below, copy pasting in Excel does not work as Excel needs < br / > to put the result in a multiline form. It instead places all the content in one cell.

This is the current output:

```
<div contenteditable="true" id="subst_result" class="monospace hard_break box_overflow_fix">
<span class="match0">23/05/2016 17:29:29</span>
<span class="match0">24/05/2016 07:58:36</span>
</div>
```

Adding a < br / > after each **span** would get the pasting to work correctly with multiple lines.

This is not an issue per se, but an improvement suggestion as it can help many process our reporting data at work :-)

Have a nice day,
Alex

**Comment by nhahtdh** [comment]
I recommend that you use text editors (e.g. Sublime Text), which highlights the match as you type your regex. It should be more convenient to use than a regex tester, whose purpose is to test and debug regex.

**Comment by alexculea** [comment]
@nhahtdh,

Thanks for your response.

What if you do not have administrator privileges or cannot decide what software to be installed on your work PC? As this is the case for many work environments. 

Especially if funds need to be approved because Sublime Text is not free, for example. Anyway, technically, you are correct but sometimes we use what we have (or don't have in this case).

Other than my suggestion, the application looks great; keep up the good work!

**Comment by firasdib** [comment]
I have changed the way the substitution box works in v2, so this will likely be fixed then!
