### ISSUE TITLE
Named groups with 0 length

### ISSUE THREAD

**Issue by ReinRaus** [firasdib/Regex101#500]
https://regex101.com/r/hC9tE2/1  

If the named group coincided with the position, rather than the text, its name is not displayed.

**Regex**  

    (?P<test>a|(?=b))

**Text**  

    acccbc

**Result**  

    MATCH 1
    test	[0-1]	`a`
    MATCH 2
    1.	[4-4]	``

**Comment by firasdib** [comment]
Thanks for the report! It's fixed in v2 😄
