### ISSUE TITLE
Old urls are not redirecting to the correct version

### ISSUE THREAD

**Issue by aelor** [firasdib/Regex101#503]
Hello, first of all congratulations for the awesome job you have done at regex101.

I have a lot of old answers on stackoverflow with a reference url to check the regex on your website. What I have been observing lately is that the old urls point to the latest version. for eg :
https://regex101.com/r/hE9gB4 automatically redirects to https://regex101.com/r/hE9gB4/11 which may be confusing for people who follow the link to see the correct regex, which is https://regex101.com/r/hE9gB4/1

I have to manually go and edit those old links to make them work again. Is there something that can be done for this. I hope this should be a small fix. Thanks in advance.

**Comment by OnlineCop** [comment]
We actually designed the URL that contains no explicit version to always update to the latest version: in most of our user feedback and own tests, people visit the site and start with a non-working expression, and as they receive help or just tinker around with the regex themselves, they find a solution that works after several revisions.

The upcoming 2.0 version of the site is designed the same way: a missing revision number will always display the most recently-created version, so it may be appropriate in the case of StackOverflow to actually update those links with the /1 version, or whatever version is most appropriate for the question.

**Comment by firasdib** [comment]
Actually i thought about this long ago and v2 will redirect to version 1. 

Mvh Firas

**Comment by nhahtdh** [comment]
(Reopened to track this issue, since it will be fixed in v2)
