### ISSUE TITLE
Why not give a menu to quick add favorites?

### ISSUE THREAD

**Issue by Zjmainstay** [firasdib/Regex101#506]
When I visit a regex tester like [https://regex101.com/r/cS1gZ9/1](https://regex101.com/r/cS1gZ9/1), I want to add it to my favorites, but I cann't. I need to fork one and mark checkbox to "Add to favorites?", and then it change the link to another one.Why not  give a menu to quick add favorites for the tester I just visit?

**Comment by firasdib** [comment]
This has been added in v2 😄
