### ISSUE TITLE
Create a new unit test from an existing test or edit a test

### ISSUE THREAD

**Issue by mcrot** [firasdib/Regex101#507]
I've just created some unit tests for my regex and realized that
I've chosen the wrong capture groups in all of them.

It would be great to be able to create a new unit test from an existing one, so I don't have to enter the almost the same stuff again before deleting the wrong test. Or alternatively to just edit an existing test?

Thanks for this helpful tool!

**Comment by firasdib** [comment]
This is implemented much better in version 2 of the site which will hopefully be available soon.
