### ISSUE TITLE
Inline flags in in Python are global to the whole pattern

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#510]
For example, `^(?m)^` doesn't match at only the beginning of the string. Since inline flag in Python affect the whole pattern regardless of its position in the regex, the `(?m)` affects all `^` in the pattern and the regex actually matches at the beginning of every line.

Example Python code with `^(?m)^.` to clearly show the effect:

```
$ python
Python 2.7.10 (default, Jun  1 2015, 18:05:38)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re; re.findall('^(?m)^.', 'sdfds\ndsfsdf\nsdfdsf\nsdf')
['s', 'd', 's', 's']
>>> 
```

Permalink: https://regex101.com/r/iZ2nN9/2

**Comment by firasdib** [comment]
note to self: enforce rule to place modifiers at the start of the pattern.

**Comment by firasdib** [comment]
This has been adjusted. You are now required to place the modifiers at the very start of the regex.

**Comment by nhahtdh** [comment]
For the record, since inline flags in Python are applied to the whole pattern and cannot be turned off, we have decided to force all inline flags to be specified in the flag field or at the beginning of the regex. While this is technically a workaround to save the effort to fix the explanation and matching semantics, the requirement above is a good practice to avoid confusion when people move from other languages to Python.
