### ISSUE TITLE
Add Qt format

### ISSUE THREAD

**Issue by rugk** [firasdib/Regex101#513]
You already have PCRE, Python and JS. What about [Qt](https://doc.qt.io/qt-4.8/qregexp.html)?

Or is Qt exactly compatible to one of the three syntaxes?

**Comment by nhahtdh** [comment]
There are 2 regular expression classes in Qt:
- [`QRegExp`](https://doc.qt.io/qt-4.8/qregexp.html), the old regular expression class.
- [`QRegularExpression`](https://doc.qt.io/qt-5/qregularexpression.html), the new regular expression class from Qt 5.0, replacing `QRegExp`.

Looking at the [source code of `QRegExp`](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/tools/qregexp.cpp?h=5.7.0), it seems that `QRegExp` implements its own engine. I don't work with Qt, so I don't know how close it is to the other engines, but I expect that there will be differences.

Looking at the [source code of `QRegularExpression`](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/tools/qregularexpression.cpp?h=5.7.0), it is actually using PCRE library underneath, so we can reuse the PCRE engine, and customize the UI and the code generator to provide support for this.

**Comment by rugk** [comment]
Also see https://github.com/blizzard4591/openMittsu/pull/9#issuecomment-233687127

**Comment by firasdib** [comment]
If its PCRE or a subset of PCRE, would that not suffice to use which the site already offers?

**Comment by Zarthus** [comment]
Closing due to no reaction, please make a new issue (and try to split them up between a codegen request and a flavour request so it's easier to sort.)

**Comment by rugk** [comment]
I have no idea, but I think it is relatively standard-like.
