### ISSUE TITLE
FR: Official support for querystring parameters

### ISSUE THREAD

**Issue by saveman71** [firasdib/Regex101#516]
I'm currently working heavily with regexes, and I could see why it would be useful to prefill the regex101 fields (regex and test text) from querystring parameters.

I know it has already been discussed in #267 and #213, but please consider this case:
* My code fails due to un unknown new type of input.
* My error handler would know what regex failed, with what flags and with what content
* It could allow the generation of a debug link, to rework the regex to adapt to the new input

This has the advantages of not loading regex101's servers in any way.

Of course, in this case, the permalink feature is out of scope.

As for the current undocumented hidden feature, would you mind to share (even privately)? This could greatly improve my workflow, instead of doing tens of back and forth copy pastas.

Many thanks for the great tool :+1:

**Comment by firasdib** [comment]
This feels like a really tailored case, which I personally don't feel is worth it. I understand it would be nice, but I don't think its worth it I'm afraid. You're going to have become efficient in your copy/pasta game 😄
