### ISSUE TITLE
Tester Does Not Work in Firefox 47 (and possibly other versions)

### ISSUE THREAD

**Issue by rambouillet** [firasdib/Regex101#517]
I guess a change was made recently to the Regex Tester that left it non-functioning in Firefox 47 (and possibly other versions)

I tested it by simply using "abc" as the pattern and "abc" as the test string.

Regex101 simply says "Detailed match information will be displayed here automatically", although it obviously should show a match. See screenshot: http://i.imgur.com/RwLX90Z.png (Screenshot is also in attachments)

It DOES work in Internet Explorer, however (all versions)

![regex101](https://cloud.githubusercontent.com/assets/20598632/17059396/8340cf90-4fea-11e6-85bd-8c4d65147c28.png)

**Comment by AndrioCelos** [comment]
It works in my Firefox 47.0.
Can you give us an example regex101 link that shows the problem?

**Comment by rambouillet** [comment]
@AndrioCelos here you go https://regex101.com/r/jZ5kI9/1

**Comment by rambouillet** [comment]
@nhahtdh The only script that was being blocked is **google-analytics.com**. Anyway, I tested it out again this morning and it is working now. I haven't restarted my PC or updated anything, just refreshed the page again, and it worked. I had been refreshing the page all last week to no avail.

**Comment by firasdib** [comment]
Next time this happens, open the console and copy whatever error is there.
