### ISSUE TITLE
Incorrect explanation for range if use \r as start

### ISSUE THREAD

**Issue by davidi17** [firasdib/Regex101#518]
pcre
    [\r-z]+/

    [\r-z]+ match a single character present in the list below
        Quantifier: + Between one and unlimited times, as many times as possible, giving back as needed [greedy]
        \r-z a single character in the range between the following two characters
            \r the literal character r (case sensitive)
            z the literal character z (case sensitive)
Should be:
 \r matches a carriage return (ASCII 13)

**Comment by nhahtdh** [comment]
It also bugs out for patterns such as `[\f-a]`, or `[\n-a]` or `[\a-a]`. Regex101 interpret them as character range correctly, but the explanation of the starting character is wrong, similar to the report above:

```
  re> /[\f-a]/
------------------------------------------------------------------
  0  36 Bra
  3     [\x0c-a]
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 0
No options
No first char
No need char
```

Apart from that, octal escape with `\o{}` is incorrectly parsed:

[`[\o{10}-a]`](https://regex101.com/r/cV1hK6/1)

```
  re> /[\o{10}-a]/
------------------------------------------------------------------
  0  36 Bra
  3     [\x08-a]
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 0
No options
No first char
No need char
```

In the case of [`[\b-z]`](https://regex101.com/r/pS0vX5/1), Regex101 recognize `\b` as backspace correctly, but it doesn't recognize a range:

```
 re> /[\b-z]/
------------------------------------------------------------------
  0  36 Bra
  3     [\x08-z]
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 0
No options
No first char
No need char
```

In the case of [`[\v-a]`](https://regex101.com/r/sH5lC7/1), `\v` is taken as character class in PCRE, so the character class contains `\v` as character class, hyphen plus `a`. Regex101 fails to explain this regex at all:

```
  re> /[\v-a]/
------------------------------------------------------------------
  0  36 Bra
  3     [\x0a-\x0d\-a\x85]
 36  36 Ket
 39     End
------------------------------------------------------------------
Capturing subpattern count = 0
No options
No first char
No need char
```

**Comment by firasdib** [comment]
@nhahtdh These should work in v2, but would you mind helping me write tests to ensure?

**Comment by firasdib** [comment]
Turns out this is not working properly in v2 and needs work. This is planned in my refactor of the regex parser.

**Comment by firasdib** [comment]
Fixed in v2, please verify and close.

**Comment by nhahtdh** [comment]
This is going to take some time... So many cases @_@

**Comment by firasdib** [comment]
@nhahtdh I have added a few to the test suite.

**Comment by firasdib** [comment]
This is fixed. Please reopen if you find issues with it again.
