### ISSUE TITLE
\x can have 0 to 2 hexadigits following it in PCRE

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#521]
`\x` can have 0 to 2 hexa-digits following it, and `\x` is interpreted as `\x00`, while `\xd` is interpreted as `\x0d`. Currently, regex101 doesn't support the case with less than 2 hexa-digits following `\x`

```
  re> /[\x\x3-\f\xf\x210-\x50]\x/
------------------------------------------------------------------
  0  38 Bra
  3     [\x00\x03-\x0c\x0f!0-P]
 36     \x00
 38  38 Ket
 41     End
------------------------------------------------------------------
Capturing subpattern count = 0
No options
No first char
Need char = \x00

```

**Comment by firasdib** [comment]
Correct, but intentional. As I mentioned in another issue, where do we draw the line between "helpful and best practice" and as exact feature translation as possible?

**Comment by nhahtdh** [comment]
It's fine to throw an error if you make it clear that it's best practice.

**Comment by firasdib** [comment]
I suppose it should be a warning instead of an error

Mvh Firas

**Comment by firasdib** [comment]
Fixed in v2
