### ISSUE TITLE
Update explanation of \s, as it now matches \v

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#522]
The current explanation of `\s` (in non-UTF mode) in PCRE reads:

>  `\s` match any white space character `[\r\n\t\f ]`

According to the documentation:

> For compatibility with Perl, \s did not used to match the VT  character (code  11),  which  made it different from the the POSIX "space" class. However, Perl added VT at release  5.18,  and  PCRE  followed  suit  at release  8.34.

Since regex101 has updated to new version of PCRE, we should update the explanation text to include VT (`\v`).

[Permalink](https://regex101.com/r/tY6wU5/1)

**Comment by firasdib** [comment]
Fixed in v2
