### ISSUE TITLE
(?m)^ matches at 2 positions in "abc\n" in Python

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#523]
In Python `re`, given the string `"abc\n"`, `(?m)^` matches at the beginning of the string and right after `\n`, even if it is the last `\n` in the string. (It is not the case in PCRE and Java, which doesn't match after the line terminator if it is the last in the string).

```
$ python3
Python 3.4.3 (default, May  5 2015, 17:58:45)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re; re.findall('(?m)^', 'abc\n')
['', '']
>>> import re; re.findall('(?m)^', 'abc')
['']
```

**Comment by firasdib** [comment]
Not quite sure if I can align with this. Thoughts?

**Comment by nhahtdh** [comment]
I think it's very hard to emulate this behavior with PCRE engine, probably impossible to do so correctly for all sort of variation of the regex above. We probably have to document this behavior instead of trying to emulate it at all.

**Comment by firasdib** [comment]
Related #579

**Comment by firasdib** [comment]
I don't think we can do anything about this. Best would be to document it. Closing this in favor of #589
