### ISSUE TITLE
global modifier in php flavor

### ISSUE THREAD

**Issue by mnemanov** [firasdib/Regex101#524]
in php preg_replace the g modifier triggers a fatal error.

When selecting the php flavor perhaps the global modifier should not be accepted and it should always do a global match as it would behave in php.

**Comment by nhahtdh** [comment]
> When selecting the php flavor perhaps the global modifier should not be accepted and it should always do a global match as it would behave in php.

We are aware that the `g` modifier can be confusing, but PHP actually exposes `preg_match` for single match and `preg_match_all` for global match, so we need to support both cases.

If you have a good idea on how to present the UI to be less confusing, sure, but not removing a feature that is actually available from PHP end.

**Comment by firasdib** [comment]
I've tried to normalize the UI of all engines supported into a "standard" one, that is, what Perl would be using.

**Comment by alexplusde** [comment]
this problem also occurs if you want to use preg_replace.

**Comment by Hamza-Khiar** [comment]
just deprecate the preg_match_all and let us use the global modifier that we're used to in other languages

stuff like regex should be standardized
