### ISSUE TITLE
Information Sidebar (Right) Flexbox Bugs

### ISSUE THREAD

**Issue by SudoCat** [firasdib/Regex101#525]
The right hand sidebar is having some issues with collapsing and expanding in Chrome (Haven't checked any other browsers). Currently, you often end up with one giant box, and the others either very small or sometimes completely hidden, even while open. This seems to be an issue with how flexbox has been setup. 

If the flex-basis value is changed from auto to 33.33333%, then the boxes will always be an equal size to one another, regardless of how many are open.

**Comment by firasdib** [comment]
I've seen this as well. This is probably because the flexbox standard changed and the code on the site is no longer functional. This is fixed in v2, so for the time being, just try to work around it. I'm working as fast as I can to release the new version :-)
