### ISSUE TITLE
Bug in textarea and cursor

### ISSUE THREAD

**Issue by hlcb91** [firasdib/Regex101#527]
The text area does not appear all. The cursor is strange, I put my cursor after the letter "e" in the word "title" and he is in another position, is before the string "\x22"

Screenshot:

![](http://i.imgur.com/aCKMQUQ.png)

`\<a href\=\"\/abcdefg\/([A-Za-z0-9]+)\.html\"[^\x3e]*title\=\"([^\x22]+)\"[^\x3e]*\>(.+)\<a[^\x3e]*`

**Comment by nhahtdh** [comment]
Which browser and platform are you on?

**Comment by hlcb91** [comment]
Linux Mint 17, Google Chrome.

User-Agent: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36`

I edited the CSS through the inspecting, removing the property `word-break` of selector `#treeview span, .hard_break, .richtext pre, .richtext textarea` and could fix the error seems to be that part.

**Comment by nhahtdh** [comment]
I can also reproduce the problem on the same version of Chrome on Windows, when I resize the window so that the regex spans multiple lines.

**Comment by firasdib** [comment]
I noticed this as well. This is probably due to the fact that flex standard changed and the code the site currently uses is no longer functional. This works in v2, which I hope to release soon. For the time being just try to work around it. Thanks for understanding!
