### ISSUE TITLE
Match highlighting in source text is off by 1 character

### ISSUE THREAD

**Issue by JesseDeLoore** [firasdib/Regex101#529]
I don't often post bug reports, so if I do things wrong please educate me.
Linked you will find an image of what goes wrong,I'll try my best to explain it below too and I'll add an example.
[Image](http://puu.sh/qkBuc/debfa0905a.png)
[Example](https://regex101.com/r/lJ2cY2/1)
When a non capturing group as added before a capturing group the highlight of the captured group stops 1 character early (it may also start 1 character early, can't verify).

Kind regards,

Jesse

**Comment by nhahtdh** [comment]
Which browser and platform are you on? Also, please upload the image on github, not some third party image hosting.

**Comment by firasdib** [comment]
This is a known bug, happens with different browsers at different resolutions. It seems to come and go. It's 100% fixed in v2 so we can ignore this for now. Please just bare with me until its ready for release :-)
