### ISSUE TITLE
Backslashes bug: \\ and \\\\

### ISSUE THREAD

**Issue by doiftrue** [firasdib/Regex101#530]
![](http://savepic.net/8266424.png)

All correct in service. But in PHP I need replace `\\` to `\\\\`, otherwise I have php error... And if I place `\\\\` in service it works not like in PHP...

pattern of example:
`(?:__|_e|__dem)\( *([\'"])(.+?)(?<!\\)\1`

text of example:
`$r = __('Разрешить \' ".','dem') . __('ответы.','dem');`

**Comment by nhahtdh** [comment]
The interface uses raw regex, so you need to escape the characters as necessary when they are enclosed in string. When in doubt, use the code generator.

[Permalink](https://regex101.com/r/pP3uH4/1) (click on code generator)

**Comment by doiftrue** [comment]
Thanks for explanation!
