### ISSUE TITLE
Sometimes fails when pasting text in - Catastrophic something or rather

### ISSUE THREAD

**Issue by dbareis** [firasdib/Regex101#531]
Sorry can't reproduce now to get error message, was getting an error and I'd use backspace and retype the last character to fix the issue.

**Comment by nhahtdh** [comment]
We cannot do anything without a test case to reproduce the issue. I will close this issue for now, and reopen when you post a reproducible test case.

**Comment by dbareis** [comment]
Ok, but I assumed you'd at least look at the copy/paste code to see how it
might fail to work, but oh well..

**Comment by nhahtdh** [comment]
Well, we take bug report seriously, but without a reproducible test case with relevant information (e.g OS, browser), there is nothing we can do. I do use the copy/paste function from time to time and have no problem at all.

**Comment by dbareis** [comment]
OK, thanks, It was pasting on to the end of an existing working expression
in Windows 7 64 bit.  I can't remember if it was the latest Chrome browser
or IE 11 (probably Chrome).
