### ISSUE TITLE
Capture groups don't highlight for javascript

### ISSUE THREAD

**Issue by Gyomo** [firasdib/Regex101#533]
Capture groups don't highlight at all if Javascript is the selected language.  And it doesn't appear to matter if the checkbox is checked in settings for any language.  PHP and Python always highlight, while Javascript never does.  Perhaps "highlight groups" doesn't mean what I think it does... but I would expect all three flavors to behave the same regardless (the actual groups that match are the same, just not the highlighting)

**Comment by nhahtdh** [comment]
This is by design. The JavaScript API doesn't expose any way to access the start and end index of the capturing groups - it only gives the content of the capturing groups. Therefore, the most we can do is show the match content on the right panel, and highlight the main match.

**Comment by Gyomo** [comment]
Even a close approximate would be nice.  It would be even closer if the approximate happened to match the other two flavors.  That is to say if the python and/or the php flavor give the start and end index as that exactly matches a javascript test -->  sTestText.substring( pythonStartIndex, phpEndIndex )  I would be pretty confident to just have an asterisk nearby marking it as approximate.

That said  I can also see why you might not want to bother.  As it is I just toggle between php and javascript to see that matches and it works just fine (but obviously there could be differences).

Anyway, great tool.  Than you so much for your time.

**Comment by darkred** [comment]
> Capture groups don't highlight at all if Javascript is the selected language.  And it doesn't appear to matter if the checkbox is checked in settings for any language.  PHP and Python always highlight, while Javascript never does.  Perhaps "highlight groups" doesn't mean what I think it does... but I would expect all three flavors to behave the same regardless (the actual groups that match are the same, just not the highlighting)   

> This is by design. The JavaScript API doesn't expose any way to access the start and end index of the capturing groups - it only gives the content of the capturing groups. Therefore, the most we can do is show the match content on the right panel, and highlight the main match.

If I'm not mistaken, groups are **always** highlighted in PHP and Python, even if the setting `HIGHLIGHT GROUPS` is disabled.
And because in Javacript they are **never** highlighted,
I'd like to make a suggestion, please: 
- maybe it would be better to remove the ``HIGHLIGHT GROUPS` setting in all three cases, altogether?
- or, make it so that its **checkbox** is disabled in all cases,  
**checked** in PHP and Python, and unchecked in Javacript,  
and its **text font color** is normal in PHP and Python, and grayed out in Javascript?
i.e. something like:
```
// PHP and Python
document.querySelector('#highlight_interaction').disabled = true;
document.querySelector('#highlight_interaction').checked = true;
document.querySelector('#colorizer_themes > label:nth-child(10)').style.color = "black";

// Javascript
document.querySelector('#highlight_interaction').disabled = true;
document.querySelector('#highlight_interaction').checked = false;
document.querySelector('#colorizer_themes > label:nth-child(10)').style.color = "lightgray";


```

**Comment by nhahtdh** [comment]
@darkred That's a separate issue and should belong in a separate bug report.

**Comment by darkred** [comment]
@nhahtdh Ok. Please check issue #550
