### ISSUE TITLE
Make copying from Python easier with multiline raw quoted regex strings

### ISSUE THREAD

**Issue by adamboche** [firasdib/Regex101#534]
I often break up my regexps into multiple lines, and mark them as raw strings, like this. Is it possible to permit this type of behavior in the regex box?

```
r'(?P<last>[^,]*),?\s*'
r'(?P<first>[^ ]*)\s*'
r'(?P<middle>[^,]*),?\s*'
r'(?P<suffix>[^ ]*)'
```

to match 'JOHNSON, John James, Jr.'

**Comment by nhahtdh** [comment]
You can enable comment mode (enabled with `x` flag) in Python to make it ignore whitespaces (spaces, new line) in the regex.

[Example](https://regex101.com/r/hS9hN7/1)

The code generator for Python is broken for `x` flag at the moment (https://github.com/firasdib/Regex101/issues/305), so you have to fix the code yourself.

**Comment by firasdib** [comment]
The new code generator will also do this for you.
