### ISSUE TITLE
Match information panel never shows position 0

### ISSUE THREAD

**Issue by wal-f** [firasdib/Regex101#535]
Even says

>No match groups were extracted.
>
>This means that your pattern matches but there were no (capturing (groups)) in it that matched anything in the subject string.

You're forced to put parentheses in patterns that do not require them.

**Comment by firasdib** [comment]
This has been adjusted in v2. This will be released soon!

**Comment by liitii** [comment]
Neat. I'm sure this will help more people understand the $0 match. I see a lot of regexes in the wild where it seems people don't know it even exists.
