### ISSUE TITLE
Doesn't match expression that expected 

### ISSUE THREAD

**Issue by irenkamalova** [firasdib/Regex101#536]
Expression [\w\.\-]+ can find
test-test
but can't find
test.test

**Comment by miparnisari** [comment]
Shouldn't the expression be `[\w\.-]+`?

**Comment by nhahtdh** [comment]
@irenkamalova: [Works for me](https://regex101.com/r/jH0eB1/1). Did you [forget `g` flag](https://regex101.com/r/jH0eB1/2)? Some language does not have `g` flag, though we use `g` to indicate "match all".

@miparnisari: Except for some flavors which supports POSIX collating sequence, `.` does not need to be escaped in character class.
