### ISSUE TITLE
Suggestion: Adding a string length count

### ISSUE THREAD

**Issue by calebjonasson** [firasdib/Regex101#537]
It would be nice to have  a string length count that represents the sample text to indicate if you are within the boundaries of the regex string limit.

**Comment by firasdib** [comment]
I'm not sure I follow. What regex string limit?

**Comment by calebjonasson** [comment]
If I'm using the expression "^[a-z]{1,256}$"

I want a maximum string length of 256.

It would be nice to have a value that shows the length of the test string entered by the user. just so we can see how long the input is without having to go to another website like https://www.tools4noobs.com/online_php_functions/strlen/ to check that the input length is working correctly.

**Comment by OnlineCop** [comment]
And what happens on those lines that contain 257 characters? If your ^ and $ anchors both match, then a line containing 257 a-z letters will fail when it hits that $ assertion.

**Comment by calebjonasson** [comment]
My idea wasn't to show an error on the text or anything like that, just an indicator of how many characters make up the test string.

**Comment by firasdib** [comment]
This feels like something that would be very difficult to implement, what about the case when you alternatives or lookarounds, etc?

**Comment by luckydonald** [comment]
![image](https://cloud.githubusercontent.com/assets/2737108/17699651/3bafd41e-63c2-11e6-8bc5-aca1a905a442.png) ![image](https://cloud.githubusercontent.com/assets/2737108/17699686/67e2f7aa-63c2-11e6-9a9e-0a8bc23d15aa.png)

You aren't talking about having a counter in one of this fields?

**Comment by firasdib** [comment]
No update; closing.
