### ISSUE TITLE
Bug on python Interface

### ISSUE THREAD

**Issue by reza1615** [firasdib/Regex101#538]
Hi at https://regex101.com/r/cZ2tL9/3 it shows "- Invalid range" error but at the javascript it is Ok!
I got the regex from [here](https://www.safaribooksonline.com/library/view/python-cookbook-3rd/9781449357337/ch02s10.html)
![image](https://cloud.githubusercontent.com/assets/2202483/17580349/3a5fe9ae-5fb3-11e6-97f6-3a38e92f77c4.png)

**Comment by reza1615** [comment]
this the python test and at python this regex is true. so  https://regex101.com has bug
`>>> import re
>>> p = re.compile(ur'[\u0600-\u06ff\u0750-\u077f\u08a0-\u08ff]+')
>>> test_str = u"text الفبا"
>>> subst = u""
>>>
... result = re.sub(p, subst, test_str)
>>> result
u'text '
>>>`

**Comment by OnlineCop** [comment]
The current version of the regex101 site uses Python 2.
http://www.regular-expressions.info/python.html says: 

> Prior to Python 3.3, Python's re module did not support any Unicode regular expression tokens.

A newer version of the site is in progress which supports both Python 2 and Python 3 syntax, where version 3 would support the `\uxxxx` notation.

**Comment by reza1615** [comment]
The answer was https://regex101.com/r/cZ2tL9/4

**Comment by reza1615** [comment]
http://stackoverflow.com/questions/393843/python-and-regular-expression-with-unicode

**Comment by reza1615** [comment]
please open this. you should put ur'' instead of r'' in front of the regex bar

**Comment by reza1615** [comment]
now at the Code generator the python code is correct if you run that code it will works but the website interface it shows error
I use python 2.7

>Python 2.7.6 (default, Jun 22 2015, 17:58:13)
>[GCC 4.8.2] on linux2
>Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> p = re.compile(ur'[\u0600-\u06ff\u0750-\u077f\u08a0-\u08ff]+')
>>> test_str = u"text الفبا"
>>> subst = u""
>>>
... result = re.sub(p, subst, test_str)
>>> result
u'text '
>>>

**Comment by nhahtdh** [comment]
@reza1615 We are aware of this issue, and it has been covered in https://github.com/firasdib/Regex101/issues/209#issuecomment-70689715

**Comment by OnlineCop** [comment]
@reza1615 This issue was not closed because it is invalid, but because this issue has already been resolved in the 2.0 version, where the `\uxxxx` notation and `ur'...'` syntax errors have been corrected for both 2.x and 3.x versions of Python.

We do appreciate the bug report, though. We hope that this will be available soon so you can enjoy the changes!

**Comment by reza1615** [comment]
@OnlineCop  :) thanks
