### ISSUE TITLE
Missing definition of line terminator in explanation of anchors `^` `$` and dot `.`

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#539]
# Line terminators in different regex flavors

In general, `.`, `^` and `$` are defined based on the concept of line terminator:
- `.` (default mode) match any character except for line terminators
- `^` and `$` in multi-line mode matches the beginning and the end of a line, as delimited by the set of line terminators 

However, different languages have different definition of line terminator:

- In either ASCII/Unicode mode, PCRE will follow the default set of line terminators as chosen during compilation time. There are 5 modes:

  - Only `\r`
  - Only `\n`
  - Only `\r\n` sequence
  - `\r`, `\n`, `\r\n` sequence
  - `\r`, `\n`, `\r\n` sequence, plus `\v`, `\f`, `\x85`, `\u2028`, `\u2029` (the last 2 are not recognized in ASCII mode of 8-bit library)

  The following test [on ideone](https://ideone.com/rNg2VX) reveals that PHP's PCRE library is compiled to recognize only `\n` as line terminator:

  ```
  <?php

    $input = json_decode('"' . 'A\u0008B\u000bC\u000cD\nE\u2028F\rG\u2029H\u0085I\r\nJ' . '"');

    preg_match_all('/./u', $input, $matches);
    var_dump($matches);

    preg_match_all('/(*ANY)./u', $input, $matches);
    var_dump($matches);
  ?>
  ```

  Testing the code on [past versions](https://3v4l.org/o3TuP) of PHP, we can see that this behavior is consistent across different versions of PHP.

  The version being used by regex101 seems to be compiled with the option to include all Unicode line terminators, as seen in the following [permalink](https://regex101.com/r/fJ7gD5/1), which is different from the default settings in PHP.

- In default mode, JavaScript recognizes `\n`, `\r`, `\u2028`, `\u2029` as line terminator (no consideration for `\r\n` sequence).
- In default mode, Python recognizes only `\n` as line terminator

# regex101 bugs/enhancement

- [ ] [JavaScript] Fix explanation for `.` to include the exact set of line terminators
- [ ] [JavaScript] Fix explanation for `^` and `$` to include "... as delimited by `\n`, `\r`, `\u2028`, or `\u2029`
- [x] [PCRE/PHP] Align the behavior to PHP by setting `PCRE_NEWLINE_LF` when compiling the regex
- [x] [Python] Align the behavior to Python by setting `PCRE_NEWLINE_LF` when compiling the regex
- [x] [PCRE] Improve explanation of `(*ANY)` to list out the exact set of line terminator sequences.

**Comment by firasdib** [comment]
Great investigative work @nhahtdh. My question is if this is worth mentioning in the explanation or if its just going to result in clutter and confusion. What are your thoughts? 

@Zarthus @OnlineCop wanna chime in?

**Comment by Zarthus** [comment]
I think being as complete as possible is useful, but you might wish to make a setting "show advanced help in quickref" of some description.

**Comment by nhahtdh** [comment]
One way to give the detail about the line terminator while avoiding cluttering the interface is to change the term being used to "line terminator", and display a detailed list of terminator on hover. What do you think?

**Comment by firasdib** [comment]
@nhahtdh That is a possibility.

**Comment by firasdib** [comment]
Related: https://github.com/firasdib/Regex101/issues/594

Problem with both issues is how to express this without being too verbose and clutter the explanation area.

**Comment by firasdib** [comment]
<img width="349" alt="screen shot 2016-09-06 at 22 39 34" src="https://cloud.githubusercontent.com/assets/1335165/18290189/d184460c-7482-11e6-9e4f-272e8dff08df.png">
<img width="335" alt="screen shot 2016-09-06 at 22 38 50" src="https://cloud.githubusercontent.com/assets/1335165/18290190/d1996852-7482-11e6-80db-a077257551d5.png">

Thoughts about this? Does this look viable?

**Comment by nhahtdh** [comment]
For every language, store the current line terminator definition.
- JavaScript fixed to `\n, \r, \u2028, \u2029`
- Python fixed to `\n`
- PCRE set to `\n`, or whatever set by the last `(*CR)`/`(*LF)`/`(*CRLF)`/`(*ANYCRLF)`/`(*ANY)` (e.g. for `(*ANY)`, the list is `\r\n`, `\n`, `\r`, `\v`, `\f`, `\x85`, `\u2028`, `\u2029`)
- Go (don't know)

For the following tokens (in square bracket is the tooltip):

- `.` in default mode: match any character, except for line terminators [line terminators are <line-terminator-list>]
- `^` in `m` mode (leave the default mode as-is): assert position at the beginning of the line [line as delimited by <line-terminator-list>]
- `$` in default mode and `\Z`: assert position at the end of the string, or before the line terminator right at the end of the string (if any) [line terminators are <line-terminator-list>]
- `$` in `m` mode (ignore `D` flag if set): assert position at the end of the line [line as delimited by <line-terminator-list>]
- `$` in `D` mode and `\z`: assert position at the end of the string.

If line terminator list contains `\n` and `\r`, but not `\r\n`, add "no special consideration for `\r\n` sequence" for tooltips of `^` and `$`.

**Comment by nhahtdh** [comment]
By the way, there is a bug when specifying 2 or more of the new line convention verbs. e.g. `(*ANY)(*ANYCRLF)`. The rule is to use the last one, in this case is `(*ANYCRLF)`.

**Comment by firasdib** [comment]
Running the following code

```go
package main

import "fmt"
import "regexp"

func main() {

    r, _ := regexp.Compile("(?m)^(.+)$")

    fmt.Println(r.FindAllStringSubmatchIndex("a\nb", -1))
    fmt.Println(r.FindAllStringSubmatchIndex("a\r\nb", -1))
    fmt.Println(r.FindAllStringSubmatchIndex("a\rb", -1))
    fmt.Println(r.FindAllStringSubmatchIndex("a\u2028b", -1))
    fmt.Println(r.FindAllStringSubmatchIndex("a\u2029b", -1))
    fmt.Println(r.FindAllStringSubmatchIndex("a\vb", -1))
    fmt.Println(r.FindAllStringSubmatchIndex("a\vf", -1))
}
```

We can determine that only `\n` is recognised for golang.

**Comment by firasdib** [comment]
I've added this and pushed live, but I'm not sure about the `\Z` token. Does it require different handling for Python and PCRE?

**Comment by firasdib** [comment]
Just remembered `\Z` in python acts like `\z` in PCRE, so the table above is correct. I've pushed the complete changes now. Please verify that I haven't made any dumb errors.

**Comment by firasdib** [comment]
@nhahtdh Ouims thought the phrasing of m-mode was a bit confusing, `the line` to be specific. Should we use `each line` instead? Or `a line`?

**Comment by nhahtdh** [comment]
@firasdib: Please change it to `a line`.

**Comment by nhahtdh** [comment]
Some comments:

**PCRE**

- (Tooltip) `.`, `^` in default mode and other: Change "The line terminator(s)..." to "Line terminator(s)..."
- `\z` and `$` (`d` mode), and equivalent in other languages: Should have the same explanation: Remove "absolute" or add "absolute" to all of them.
- (Tooltip) `^` in `m` mode. Don't use "should" in "The lines should be delimited", also drop "The". Change to "Lines are delimited ..."
- `\Z` in `m` mode: Wrong explanation. Make sure `\A`, `\Z`, `\z` has the same explanation regardless of flag in PCRE.
- `$` in `m` mode: Fails to ignore `D` flag

**JS**

- `$` in default mode: Wrong description. Remove " or before the line terminator right at the end of the string (if any)"

**Comment by firasdib** [comment]
@nhahtdh Ah, I was a bit confused as your post initially mentioned \Z changed with PCRE. I'll fix. But in that case, both `\z` and `\Z` will have the same explanation, but they won't work exactly the same. Isn't that a bit confusing?

I've pushed the other fixes.

**Comment by nhahtdh** [comment]
@firasdib Sorry, the way I phrase it was confusing. `\Z` and `\z` should never have the same explanation. I mean `\Z`'s explanation should not change when any flag is specified, and the same applies for `\z` and `\A`.

**Comment by firasdib** [comment]
This is fixed and added. Reopen if you find issues.
