### ISSUE TITLE
Wrong highlight of matching color

### ISSUE THREAD

**Issue by tfrdidi** [firasdib/Regex101#541]
When I enter the Regular Expression

`(?P<date>\d+[-\d+]+) \S+ \S+ \S+ \S+ \S+ (?P<path>\S*) \S+ \S+ \S+ (?P<ip>[\w*.:-]*) \S+ \S+ \S+ \S+ \S+ (?P<status>\d+) \S+ \S+ \S+ \S+ \S+`

and the test string 

`2015-01-03 23:00:33 W3SVC4 S01EDV04 172.17.8.4 GET / - 80 - 172.17.8.2 HTTP/1.0 check_http/v2.0.3+(nagios-plugins+2.0.3) - - - 401 2 5 1657 128 1`

I get a match as expected and the correct match information. But the color that hightlights the group status which I would have expected to highlight the 401, highlights ' 40' (including the whitespace before). From that point the following highlighting color seems to be shifted one character to the left, which results in the last number to be not highlighted. 

To me it seems like a bug that only affects the highlight of the result.

**Comment by nhahtdh** [comment]
No repro on Firefox. I guess you are using Chrome?

**Comment by nhahtdh** [comment]
Reproduced on Chrome 52:

![](https://cloud.githubusercontent.com/assets/564162/17722898/efe21e7c-645f-11e6-8480-a01fef6c9162.png)

**Comment by nhahtdh** [comment]
Related highlighting issues: https://github.com/firasdib/Regex101/issues/321. https://github.com/firasdib/Regex101/issues/351. https://github.com/firasdib/Regex101/issues/489, https://github.com/firasdib/Regex101/issues/529.

This issue occurs on different browsers from time to time and involve a long string and variable screen size.
