### ISSUE TITLE
Regex Library is not loading

### ISSUE THREAD

**Issue by AnilGoswami** [firasdib/Regex101#542]
It keeps saying "Loading content, please hold..."

**Comment by luckydonald** [comment]
It sometime really takes time.

In my case I often accidentally click it. 
Nice would be an **cancel button**, because loading that library then is blocking work for a minute.

**Comment by firasdib** [comment]
I know, and I'm sorry. The existing version is complete rubbish and is being replaced asap. I am soon finished with the new version of the site which means you're no longer going to have to endure this!
