### ISSUE TITLE
Incorrect explanation and matching [\.\-_] regex for javascript

### ISSUE THREAD

**Issue by AlexeyMz** [firasdib/Regex101#543]
Test case:
1. regex = `[\.\-_]`
2. test string = `-`
3. flavor = `javascript`

In the Explanation panel it says: 

    \- matches the character - literally

But despite that the Match Information panel displays
    
    No match groups were extracted.

**Comment by OnlineCop** [comment]
This is correct behavior. The rest of the Match Information panel should also display

```
No match groups were extracted.

This means that your pattern matches but there were no (capturing (groups)) in it that matched anything in the subject string.
```
https://regex101.com/r/zS3xH9/1

If you want match groups, enclose `-` with parentheses: `([\.\-_])`
https://regex101.com/r/zS3xH9/2

**Comment by firasdib** [comment]
fwiw, the new version will show you the complete match regardless in that box.
