### ISSUE TITLE
alternate donation methods

### ISSUE THREAD

**Issue by jonhwilliams** [firasdib/Regex101#544]
It would be great to have more than paypal to donate.

Paypal requires an agreement that voids legal protections built into credit cards.

A few people never use Paypal (myself included).

Thanks!

**Comment by firasdib** [comment]
What would you suggest? Everyone seems to have their preference, and I can't register everywhere. Ideally I'd like to just have one place that accepts every form, but that doesn't work :(...

**Comment by firasdib** [comment]
Going to close as duplicate of https://github.com/firasdib/Regex101/issues/490
