### ISSUE TITLE
positive and negative look behind should allow quantifier

### ISSUE THREAD

**Issue by nvqc86** [firasdib/Regex101#545]
positive and negative look behind should allow quantifier
For example:
(?<=(["'].*))someString

**Comment by OnlineCop** [comment]
Look-behinds in .NET and Java support quantifiers, and those have some specific rules. All other regex flavors forbid variable-length look-behinds, and so quantifiers are unavailable in the languages supported by regex101.

**Comment by nhahtdh** [comment]
Just for the record:

### PCRE

```
$ pcretest
PCRE version 8.38 2015-11-23

  re> /(?<=(["'].*))someString/
Failed: lookbehind assertion is not fixed length at offset 12
  re>
```

### Python 3

```
>>> re.compile('(?<=(["\'].*))someString')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/re.py", line 223, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.4/re.py", line 294, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 572, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 557, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 164, in _compile
    raise error("look-behind requires fixed-width pattern")
sre_constants.error: look-behind requires fixed-width pattern
```

### JavaScript

Doesn't allow look-behind in the first place.

-----------------------------

By the way, Java technically shouldn't allow that regex, but there is a bug with integer overflow which ends up allowing them.
