### ISSUE TITLE
[VERSION2] iOS: no cursor, space scrolls, caps lock on inputs

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#546]
### A few issues on iOS webkit:
- [x] tapping space bar will scroll the page while inputting text
- [x] input is auto caps-locked
- [x] _no cursor is rendered_ **(known issue)**
- [x] inability to use the loupe to position cursor 
### Here's the screen-grabbed behavior:
- as seen on [iPhone 6+ hardware](https://bugout.regex.cf/iPhone6+_hardware-editor-caps-space-acts-as-scroll.mp4), iOS 9.3.3.
- as seen on [iOS Emulator 9.0](https://bugout.regex.cf/iOS-9-simulator-double-type-space-scrolls.mp4), with the additional bug which I do not see with a physical hardware: duplicated keypresses.

| OS | Browser | Version |
| --- | :-: | --: |
| iOS 9.0 | Safari | 601.1.46 |
| iOS 9.3.3 (no updates to Safari since 9.0) | Safari | 601.1.46 |

**Comment by firasdib** [comment]
Looked into this, fixed a few of the issue. Please try it again :).

Constant caps-lock issue: https://github.com/codemirror/CodeMirror/issues/3403

**Comment by working-name** [comment]
I was a little excited thinking that jsfiddle may have a solution for this but it doesn't look like they're running CM on the mobile version. 

Yes now I get a cursor and can use the loupe. The other odd thing is that CM does not allow double spacebar to period replacement that usually happens. Granted, mobile keyboards have their own specific behavior anyway, so that's minor. 

Great job!

**Comment by firasdib** [comment]
How lazy of them!

Anyway, I'll leave this open for a while. I doubt codemirror will fix it, but we'll see.

**Comment by firasdib** [comment]
Fixed!

**Comment by TWiStErRob** [comment]
@firasdib the linked CM issue is still Open?
