### ISSUE TITLE
[VERSION2] Mobile: sidebar by tapping results text

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#547]
I often find myself wanting to tap the results text to bring up the sidebar rather than the hamburger menu icon. Definitely something you can get used to, however, having the sidebar show when one taps the results text is probably more *intuitive*.
![results text](https://bugout.regex.cf/usability-enable-sidebar-on-results-text.png)

**Comment by firasdib** [comment]
Well, if you just select the tab you want to view in the sidebar and then close it, that will be tab thats open when you re-open the sidebar. And the button is literally 20px above it. 

Closing this.

**Comment by working-name** [comment]
Yeah I see your point. I meant the sidebar itself, not the results sidebar, specifically. Just one of those things you're conditioned to.
