### ISSUE TITLE
[VERSION2] quickref html entities do not get decoded by the browser

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#549]
Notice ```\g&lt;0&gt;``` is not interpreted by the browser.
![html entities](https://bugout.regex.cf/html-entities.png)

| OS        | Browser           | Version  |
| ------------- |:-------------:| -----:|
|OS X 10.10.5     | Chrome | 51.0.2704.106 |
|OS X 10.10.5     | Safari | 9.1.2 (10601.7.7) |
|OS X 10.10.5     | Firefox | 47.0 |
|OS X 10.10.5     | Firefox Nightly | 51.0a1 |

**Comment by firasdib** [comment]
Thanks, fixed!
