### ISSUE TITLE
(about the "HIGHLIGHT GROUPS" setting) Remove it or make its checkbox always disabled

### ISSUE THREAD

**Issue by darkred** [firasdib/Regex101#550]
_(As a continuance to issue #533 )_

> Capture groups don't highlight at all if Javascript is the selected language.  And it doesn't appear to matter if the checkbox is checked in settings for any language.  PHP and Python always highlight, while Javascript never does.  Perhaps "highlight groups" doesn't mean what I think it does... but I would expect all three flavors to behave the same regardless (the actual groups that match are the same, just not the highlighting)   

> This is by design. The JavaScript API doesn't expose any way to access the start and end index of the capturing groups - it only gives the content of the capturing groups. Therefore, the most we can do is show the match content on the right panel, and highlight the main match.

Groups are **always** highlighted in PHP and Python, even if the setting `HIGHLIGHT GROUPS` is disabled.
And because in Javacript they are **never** highlighted,
I'd like to make a suggestion, please: 
- maybe it would be better to remove the `HIGHLIGHT GROUPS` setting in all three cases, altogether?
- or, make it so that its **checkbox** is disabled in all cases,  
**checked** in PHP and Python, and unchecked in Javacript,  
and its **text font color** is normal in PHP and Python, and grayed out in Javascript?
i.e. something like:
```
// PHP and Python
document.querySelector('#highlight_interaction').disabled = true;
document.querySelector('#highlight_interaction').checked = true;
document.querySelector('#colorizer_themes > label:nth-child(10)').style.color = "black";

// Javascript
document.querySelector('#highlight_interaction').disabled = true;
document.querySelector('#highlight_interaction').checked = false;
document.querySelector('#colorizer_themes > label:nth-child(10)').style.color = "lightgray";
```

**Comment by firasdib** [comment]
Hello,

This has changed in v2, the setting named were poorly chosen.

As was explained earlier, javascript does not give me any way of knowing where a capture in a sentence has happened, and thus I can not possibly display it to you. A simple search and replace in the string would not work if the captured string is recurring, for example. As a result, I'm only able to do this for php, python and golang.

**Comment by nhahtdh** [comment]
As the bug report suggested, I can't see any difference in the UI when I toggle the setting. What was the `HIGHLIGHT GROUPS` settings intended for?

**Comment by firasdib** [comment]
Its not a bug, its so that when you click a match its highlighted in the match info, if I recall correctly. But as I mentioned, no longer relevant in v2 as settings are described in a different manner and much clearer.

**Comment by darkred** [comment]
@firasdib Alright, then. Is there an estimation on when v2 of the site will be released?

**Comment by nhahtdh** [comment]
If you check the issue list, version 2 is undergoing testing. It should be available soon

**Comment by darkred** [comment]
Ok.Thank you very much for offering such a great regex testing service!

PS. Is the version 2 beta of the site publicly available for testing? Could you please give the URL?

**Comment by firasdib** [comment]
@darkred Its not public just yet. I'm testing it out with a few trusted users, but as soon as thats done, we'll open it up for everyone.

**Comment by darkred** [comment]
@firasdib Ok, thanks again. Looking forward to the new version!
