### ISSUE TITLE
Beta: Brief scrollbar when opening flags list

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#552]
Chrome 53.0.2785.34 beta-m (64-bit), windows 10

![video](https://i.imgur.com/9JkDFFV.gifv)

https://i.imgur.com/9JkDFFV.gifv

Also appears when changing the delimiter

**Comment by nhahtdh** [comment]
Confirmed on Firefox 48/Windows 7 also

**Comment by firasdib** [comment]
This issue exists for me as soon as I open the login menu, and stays on there forever. 

![capture](https://cloud.githubusercontent.com/assets/1335165/17862910/a874a816-6897-11e6-83fc-87ec845c5511.PNG)

**Comment by firasdib** [comment]
Seems fixed for me on OSX and @Zarthus on windows, closing!
