### ISSUE TITLE
Beta: For languages which needs string concatenation for multiline input, don't put empty string at the end

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#559]
Given an input with only a new line character, Python and Java doesn't need the empty string at the end.

```
test_str = ("\n"
	"")
```

**Comment by firasdib** [comment]
Upon closer inspection there seems to be no trivial way of solving this without going a bunch of ugly work, and I wonder if this is really an issue? Its a bit ugly perhaps, but not worth the hassle as far as I can tell.

**Comment by nhahtdh** [comment]
How are you handling this currently? Can you check the array of lines and remove the last empty string?

**Comment by firasdib** [comment]
Not quite, I split the string by newlines and build it up as I go. Pop on slack and we'll discuss it.

**Comment by nhahtdh** [comment]
@firasdib I can't join Slack right now, since it's broken behind corporate firewall. I can only read, but not send message.

**Comment by firasdib** [comment]
@nhahtdh Ok. I'm on IRC as well if thats any better.

**Comment by firasdib** [comment]
I really can't think of a decent way of doing this without making things super ugly.

Here is my code, feel free to take a stab at it (adapted a bit so it doesn't depend on my escape code):

```js
  createJavaMultilineString(string) {
    return string
      .split('\n')
      .map((line) => {
        return '\t + "' + line + '\\n"';
      })
      .join('\n')
      .slice(4, -3) + '"'; // Remove the last newline and unfortunately last quote, and re add it
  }
```

**Comment by nhahtdh** [comment]
Guess we can write the split as `.split(/\n(?!$)/g)` or better `.split(/\n(?!$|\n)/g)` (compact empty lines to one line)

**Comment by firasdib** [comment]
`.split(/\n(?!$|\n)/g)` doesn't work because it'll squash newlines in the middle of the sentence, we only want it to do so at the end. 

`.split(/\n(?!$)/g)` will leave a literal newline at the end.

Nothing seems to be good & easy.

**Comment by nhahtdh** [comment]
Sorry, I only look at the split without checking the rest.

This behavior is what I have in mind:
```
    .match(/[^\n]+\n*|\n+/g).map((line) => '\t + "' + line.replace(/\n/g, '\\n') + '"').join('\n').substr(4)
```
(Pass output of `line.replace` in `escapeString` in actual code)

For example:
```
"\n\n\nsdfdf\n\n\nfffdf\n".match(/[^\n]+\n*|\n+/g).map((line) => '\t + "' + line.replace(/\n/g, '\\n') + '"').join('\n').substr(4)
```
Outputs:
```
"\n\n\n"
	 + "sdfdf\n\n\n"
	 + "fffdf\n"
```

What do you think?

**Comment by firasdib** [comment]
That would probably work, I'll check it out in the morning :)

**Comment by firasdib** [comment]
Pushed your fix, please verify and close.
