### ISSUE TITLE
Beta: When regex has new line as the last character, it's not reflected in the explanation

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#561]
Test by a regex with only 1, 2, 3 raw new line characters.

**Comment by firasdib** [comment]
Can not reproduce. Can you show a print screen?

**Comment by nhahtdh** [comment]
Here you go:

![untitled](https://cloud.githubusercontent.com/assets/564162/17852417/76ef9360-6891-11e6-9aee-4560dcb7f21a.png)

**Comment by firasdib** [comment]
Ah. The actual newline is explained, but its not visible in the regex itself. This is a browser limitation, I can't force it to show it. I've tried and failed, unsure why. Not that big of a deal as its actually explained correctly though.

**Comment by nhahtdh** [comment]
If the regex ends with a new line, can you add another new line to the HTML in the explanation? That should fix the problem.

**Comment by firasdib** [comment]
It could, but I'm unsure if there are any potential side effects we aren't considering.

**Comment by firasdib** [comment]
I've decided to not do this. Does not seem worth it to me and the representation doesn't end up looking any better in my opinion.  If it comes up again I'll give it another think.
