### ISSUE TITLE
Beta: Errors that there was a problem saving my regex when the Test String is too long.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#563]
You get the error "There was a problem while trying to submit your regex to the library. Please try again later.", could change it to "Your Test String is too large, please shorten it"  since many people fancy uploading entire websites in the test strings at times.

```
2016-08-22 13:01:03.166 (index):47942 Error while submitting library data: Error: Payload Too Large(…)
```

**Comment by firasdib** [comment]
I've upped the limit to the correct values. Your browser is likely going to cry before this becomes an issue again.
