### ISSUE TITLE
Beta: Explanation for `u` mode in Python is wrong

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#564]
The current explanation about UTF-16 and stuffs is wrong. `u` mode in Python will make the shorthand character class Unicode aware, but the flag is redundant anyway, since shorthand char-class in Python 3 are Unicode aware by default.

**Comment by firasdib** [comment]
You mean the `u` flags description in the explanation window?

**Comment by nhahtdh** [comment]
Yes. A screenshot to clarify:

![untitled](https://cloud.githubusercontent.com/assets/564162/17878219/777f3d94-6913-11e6-8fb9-8923007986c8.png)

**Comment by firasdib** [comment]
You have better insight in this, can you give me strings I can use?

**Comment by nhahtdh** [comment]
I think we can say:

`Make \w, \W, \b, \B, \d, \D, \s and \S perform matching with Unicode semantic (redundant in Python 3)`

**Comment by firasdib** [comment]
Fixed
