### ISSUE TITLE
Beta: Unit Tests assert-that "Does Not Match" does not work.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#566]
Write a regex, put an "assert that $x does not match", and the test will fail because "does not match" is not a found.

![http://i.imgur.com/R4PBJze.png](http://i.imgur.com/R4PBJze.png)

Footnote: Saving the regex beyond this also serves an Internal Error (500)0
```
{error: "Unable to service request (Error Id: e7477ab2-667b-48fe-863c-577cbee57472)"}
```

**Comment by firasdib** [comment]
Fixed
