### ISSUE TITLE
Beta: Look & Feel / UI 

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#570]
Here's something I currently have some mixed feelings about.

Given the following page: https://i.imgur.com/8xxg4LC.png

Can you find the IRC help easily? I feel it doesn't stand out _as much_ as it did before - I'd personally give it a blue background, someone on IRC also suggested a single chat box with IRC (or chat) written in it.

I'd definitely make them blue (rather than gray) on hover. Something like http://i.imgur.com/wg48ZKz.png (only then not ugly)

Note: This being an image means some UI elements are not visible, when you visit the page yourself you will be able to move your cursor around and see some of the default-hidden popups that explain function, but ideally I think it's better if it's obvious.

**Comment by firasdib** [comment]
Do you want me to highlight the IRC button only, or all the buttons in the sidebar?

**Comment by Zarthus** [comment]
Consistency is important, I'd go with and make them all blue (on hover or just normally)

**Comment by firasdib** [comment]
I'm not convinced. We'll see what others have to say.

**Comment by Zarthus** [comment]
I think IRC will definitely receive a traffic drop once v2 hits just because people can't find live support.

**Comment by Ouims** [comment]
I think Zarthus has some points.
Imo, it's not just the sidebar, a lot of text in the dark theme are very hard to see.
Basically everything which is grey and too close from black, "switch to unit test" for example (it looks like to me that "Test String" is lighter.)

I think that all the grey color should be made lighter.

**Comment by firasdib** [comment]
@Ouims Those are the same color.

I've adjusted a few colors here and there, but if you can take screen shots of exact things you want to adjust, I'd be happy to do it. 

I'm spoiled with a fantastic monitor allowing me to see subtle changes in colors, where other monitors would perhaps show one color. So you'll have to excuse my poor color choices 😄

**Comment by firasdib** [comment]
I'm closing this as its gone a bit stale and might be outdated. If there any particular nits, open an issue for them individually.
