### ISSUE TITLE
Beta: Python code generator don't split regex string in COMMENT mode

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#577]
As detailed in https://github.com/firasdib/regex101-app/issues/170, in `COMMENT` mode, please place the **regex string** in triple quoted string (and indent it to make it looks good). Don't split the string up by new line.

**Comment by firasdib** [comment]
This has been adjusted, check it out on the site and close if you think its good.

**Comment by nhahtdh** [comment]
Confirm fixed and close :+1: .
