### ISSUE TITLE
Complete Python replacement syntax

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#578]
Python accepts the following replacement syntax:
- [x] `\g<0>` refers whole pattern
- [x] `\g<n>` refers to capturing group n
- [x] `\g<name>` refers to named capturing group `name`
- [x] `\1`, `\2`, ..., `\99` refers to capturing group 1, 2..., up to 99...
- [ ] ... , when we parse, we takes 2 digits if possible, and throw error if capturing group does not exist.
- [ ] `\0oo` is octal escape - the first character must be `0`, and it can optionally have up to 2 more octal digits (i.e. `\0`, `\01`, `\012` are valid octal escapes)
- [ ] `\1oo`, `\2oo`, `\3oo` are octal escapes
- [x] `\a`, `\b`, `\f`, `\n`, `\r`, `\t`, `\v`, `\\` are recognized as escape sequence in replacement syntax
- [x] Otherwise, `\` escape the next character, ...
- [x] ... but you can't have a lone `\` at the end of the string. (Already implemented, but we need a more prominent error, like changing the substitution result to red).
- [ ] Other string replacement syntax should be disabled.

---
### Code for parsing octal escapes and group reference:

```
        elif c == "0":
            if s.next in OCTDIGITS:
                this += sget()
                if s.next in OCTDIGITS:
                    this += sget()
            lappend(chr(int(this[1:], 8) & 0xff))
        elif c in DIGITS:
            isoctal = False
            if s.next in DIGITS:
                this += sget()
                if (c in OCTDIGITS and this[2] in OCTDIGITS and
                    s.next in OCTDIGITS):
                    this += sget()
                    isoctal = True
                    c = int(this[1:], 8)
                    if c > 0o377:
                        raise s.error('octal escape value %s outside of '
                                      'range 0-0o377' % this, len(this))
                    lappend(chr(c))
            if not isoctal:
                addgroup(int(this[1:]))
```

**Comment by firasdib** [comment]
Why a more prominent error? The user is already seeing a bright red token that indicates an error. Perhaps changing the substitution text to an error notice or something?

The other replacement syntax could be disabled, but I don't think its worth it. I've allowed for my enhanced syntax to be used in any flavor simply because it might be beneficial for the task the user is running. It's a double edged sword, I suppose.

As for octal escapes, I've disabled that as it clashes too much with numeric backreferences `\n` and how javascript handles it etc. Better if the user uses another method.

**Comment by nhahtdh** [comment]
When there is a *fatal* error in the replacement string syntax, an exception will be thrown, and there will be no output. I simply don't like the substitution result still reflecting the test string when such case happens.

Regarding the replacement syntax, when you have a bunch of stuffs from other languages, it disallows perfectly valid replacement string, or change the meaning of literal characters in the current language. I think your full replacement syntax should only be used in PCRE. JavaScript and Python should only stick to whatever allowed in those languages. Actually, I would prefer that each engine has their own implementation, instead of allowing every replacement syntax and mislead the user.

(Case in point, Python always parses `\10` as reference to capturing group 10, regardless of whether the pattern has the group or not. User has to write `\1\060` or `\g<1>0` to mean capturing group 1 followed by 0. The current implementation uses a flexible definition of `\10` and fails to warn user about this case in Python)

By the way, I have just updated the first post with a more complete specification, just for reference.

**Comment by firasdib** [comment]
Yes, I somewhat agree with you. It depends if we want to go down the text editor route or simply being as compatible as possible. I've added non-standard `\U` and `\L` so users can upper/lowercase their match. This would have to be disabled in python, for example.

**Comment by firasdib** [comment]
This has been implemented.

Will be pushed in a few days with the big update.

Further tracking in https://github.com/firasdib/Regex101/issues/648
