### ISSUE TITLE
Show backing engine version and configuration

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#579]
I think it would be nice to show the version of PCRE or re2 engine that you are using, and some relevant configuration information (such as the default line terminator/UCP support/16-bit library/etc. in PCRE, and equivalent information, if any, in re2 engine). For JavaScript, we probably reflect the running browser's information. For Python, we will show PCRE, plus the version we are aligning with.

I'm not sure about the UX. I guess it can be placed in an about page (less clutter) or an icon on the language name (more clutter).

**Comment by firasdib** [comment]
I suppose there is _some_ merit to this, but I'm not sure to what extent. The fact that I'm using a 16bit library technically does not impact the user as what they're inputting also is utf16, so its only for browser compatibility reasons. 

And as you said, no idea where to place this in the UI. Would placing it in the settings window be weird? Or perhaps a little icon next to the `FLAVOR`-label that when clicked opens a modal?

**Comment by Zarthus** [comment]
The settings window seems like a good place for this. In the dark grey text so it is not really marked as relevant to most.

**Comment by nhahtdh** [comment]
There is also the option of linking to the existing Wiki, where we will populate information about the backing engines and stuffs. How about a FAQ button on top which links to the Wiki?

**Comment by Zarthus** [comment]
I'd imagine the GitHub wiki is a bad place for this if the values are dynamic. Putting it in settings would make more sense if the variables/versions can be directly accessed in the code.

**Comment by firasdib** [comment]
That depends. I think the Wiki is a good place for it, what information do we really want to show?

**Comment by nhahtdh** [comment]
@firasdib Something like what I have written here: https://github.com/firasdib/Regex101/wiki#how-close-does-regex101-emulates-the-engines

Basically, engine information (real or emulated, version, compilation information, known but can't fix issues, etc.)

**Comment by firasdib** [comment]
@nhahtdh I like it. It needs to be updated though, but I will include a link to it in the header as soon as its updated.

**Comment by firasdib** [comment]
Closing this in favor of https://github.com/firasdib/Regex101/issues/589
