### ISSUE TITLE
\k{} should not accept number or name starting with number

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#584]
According to the [documentation](http://www.pcre.org/original/pcre.txt)

> Names consist of up to 32 alphanumeric characters and underscores,  but   must  start  with  a  non-digit.  Named capturing parentheses are still allocated numbers as well as names, exactly as if the  names  were  not present.  The PCRE API provides function calls for extracting the name-to-number translation table from a compiled pattern. There  is  also  a convenience function for extracting a captured substring by name.

Therefore, `\k{name}` should only accept `name` that matches the regex `[a-zA-Z_][a-zA-Z0-9_]{0,31}`.

Currently `\k{0}` is accepted by regex101, which causes unhandled exception when compiled.

**Comment by firasdib** [comment]
Fixed
