### ISSUE TITLE
\p{Cn} is not supported by re2

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#585]
According to the [documentation](https://github.com/google/re2/wiki/Syntax), `\p{Cn}` is not supported by re2. However, regex101 fails to reject `\p{Cn}` as invalid for re2/golang, and the following error can be seen in the console:
```
re2/re2.cc:187: Error parsing '\p{Cn}': invalid character class range: \p{Cn}golang.js%20line%201%20%3E%20eval:1:3328
re2/re2.cc:546: Invalid RE2: invalid character class range: \p{Cn}
```

**Comment by firasdib** [comment]
Fixed

**Comment by nhahtdh** [comment]
It would be nice if you push the changes live before you close it. This way, I get a notification and can confirm whether the bug is fixed or not.

**Comment by firasdib** [comment]
Ok. Feel free to reopen the issues and close them after testing :-)

**Comment by firasdib** [comment]
Pushed. Please verify and close.

**Comment by nhahtdh** [comment]
It seems your fix makes `\p{Cn}` invalid in PCRE, while it's valid and is accepted by pcretest.

**Comment by firasdib** [comment]
Yes, but looking at the documentation it seems the token does nothing so I opted for simplicity and aligned the flavors

Mvh Firas

**Comment by firasdib** [comment]
Pushed a fix, please verify and close.
