### ISSUE TITLE
Line number in the regex area - V2

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#592]
If you enable line numbering in the option, it also numbers the line in the pattern area, which i think isn't a good idea at all.

Having line number there might be useful for long and/or splitted regex, but I don't think that happens too often.

I suggest a new options, specifically for line number in pattern, which would be related to the current one (greyed out if the current option is disabled).
It would be disabled by default when you enable the current option, well at least that would be my liking, but as long as we have the option..

https://dl.dropboxusercontent.com/u/4249275/pic/reg.png

**Comment by nhahtdh** [comment]
I'm curious - what do people use the line number for? It makes sense in code, since the stack trace points to line number and stuffs, but I can't imagine how it is useful in either the input string or the regex.

**Comment by firasdib** [comment]
Not sure if its worth the extra steps tbh. Does it hurt to have them in the regex?

**Comment by nhahtdh** [comment]
I see them as clutter, but I really want to see if anyone has a different opinion regarding line number in regex field.

**Comment by firasdib** [comment]
I personally like line numbers in both fields. It allows me to refer to specific lines in my comments.

Regardless, if I were to implement this, it would make no sense to limit line numbers in the regex field by line numbers in the test string area. It would make more sense for them to be completely independent.

**Comment by Ouims** [comment]
It's just that in case of single line regex pattern, you just get a '1' in front, it's not really clear it's a line number then, and just add clutter, as said.
The test string often gets more lines and there the line number can be used to reference a specific test, like the use asking for help can say ' yeah i don't want the line 3 to match' when using /gm with ^$ anchored pattern to make multiple tests at once without using test units..

**Comment by firasdib** [comment]
After some thought I came to the same conclusion as you guys and have now separated the option into two distinct ones. Thanks for the feedback!
