### ISSUE TITLE
Explanation of $ and \Z missing note about matching before the terminating new line

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#594]
\Z will allow trailing newline(s) to be there, I think the explanation for \Z should have at the end, in parenthesis, something like "(trailing newline(s) are still considered the end of the string)" or similar.

**Comment by nhahtdh** [comment]
By the way, `$` in default mode has the same behavior as `\Z`, and should have the same explanation as `\Z` in PCRE.

**Comment by Ouims** [comment]
Right, and it does not handle any number of newline but only one actually, so /a$/ or /a\Z/ won't match "a\n\n" like i implied, only "a\n".

**Comment by firasdib** [comment]
So what we need is to define what a line is. Question is if we should mention this in the explanation or not, as its definitely going to get cluttered, and it feels hard to keep the explanation for something like this short.

Any ideas?

**Comment by Ouims** [comment]
pcre:
default mode:
\z is the absolute end of string - "a\z" does not match "a\n"
\Z is the same as $: allow a trainling newline before the end - "a\Z" and "a$" matches "a\n"

multiline mode /m:
\z doesn't change
\Z doesn' change
$ matches when \Z matches and matches at newline

javascript:

default mode:
\z \Z matches literal
$ matches absolute end of string

multiline mode /m:
$ matches on newline as well as absolute end of string

Python:

default mode:
 \Z is the absolute end of the string - "a\Z" doesn't match "a\n"
\z matches literal
/!\ $ matches like \Z and $ in pcre - "a$" matches "a\n"

multiline mode /m
\Z doesn't change
$ matches like in default mode + at newline

Golang
\Z is an error
\z is absolute end of string in both mode
$ matche like \z in normal mode, add matches at newline in multiline mode

**Comment by firasdib** [comment]
Wait... I was just thinking about this, and isn't what you're saying absolutely logical? Is there any other conclusion you can come to? With the enhancement of #539 I don't think this issue is valid any more. All of these tokens operate by line terminators, and its obvious it leaves trailing line terminators as it will match those as well in due course.

So my plan of action is to implement #539, properly track line terminators in the regex and explain them with a tooltip.

**Comment by Ouims** [comment]
$ and \Z in pcre still don't have the same explanation

**Comment by firasdib** [comment]
@Ouims https://github.com/firasdib/Regex101/issues/539#issuecomment-245667096

**Comment by Ouims** [comment]
But 539 is more about newline, this is about \z \Z and $ specifically

**Comment by nhahtdh** [comment]
@Ouims I have also addressed the matching before new line problem in #539, since it's related to this issue
