### ISSUE TITLE
Match which spans across lines has the white space after the line highlighted

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#596]
Using [this test case](https://regex101.com/r/aP5zR6/7#python) from https://github.com/firasdib/Regex101/issues/595 on the beta version shows the first match spanning to the next line by highlighting the rest of the line:

![](https://cloud.githubusercontent.com/assets/564162/18043777/42d46e44-6df4-11e6-86b9-8258489e3032.png)

Is this intentional?

**Comment by firasdib** [comment]
This is by design. If the match continues on the next line, the whole line is highlighted to show that.
