### ISSUE TITLE
Catastrophic backtracking seems to locks up the MATCH INFORMATION window until regex is modified

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#597]
Reusing [this test case](https://regex101.com/r/aP5zR6/7) from https://github.com/firasdib/Regex101/issues/595, with the following input string:

```
https://github.com/someone/a.gi
http://github.com/someone/reposdf.
https://github.com/someone/repo.git
https://github.com/someone23cmD_M_R_L_/repo_fy-i
https://github.com/docopt/docopt.rs
```

The regex has no issue with this input. We add `g` after `reposdf.` and we trigger catastrophic backtracking. So far so good. However, if we remove the `g` we just added, the MATCH INFORMATION keeps the warning without updating match information. The warning stays however we modify the input string.

The only way to clear the warning is by making modification to the regex.

Is this behavior intentional?

**Comment by firasdib** [comment]
Fixed

**Comment by nhahtdh** [comment]
For less serious cases, the debugger still manages to load. However, when I increase the length of the string, the debugger fails with an unknown error.

For example, using this simple regex `^(a|a){100}$` with this test string `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab`.

The debugger on the new version also takes quite some time to load compared to the version 1. The debugger in version 1 is blazing fast, regardless of how bad the regex is.

**Comment by nhahtdh** [comment]
Confirmed fixed :+1:
