### ISSUE TITLE
Regex debugger dies when catastrophic backtracking happens

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#598]
When catastrophic backing happens, using this test case as an example:

    ^(a|a){100,}$

against:

    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab

Clicking on Regex Debugger shows this message:

> The regex debugger was unable to debug your pattern due to an error.
> -8

This makes the feature totally useless.

**Comment by firasdib** [comment]
Fixed

**Comment by nhahtdh** [comment]
For less serious cases, the debugger still manages to load. However, when I increase the length of the string, the debugger fails with an unknown error.

For example, using this simple regex `^(a|a){100}$` with this test string `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab`.

The debugger on the new version also takes quite some time to load compared to the version 1. The debugger in version 1 is blazing fast, regardless of how bad the regex is.

**Comment by firasdib** [comment]
1. I agree that it seems to take longer to load, but I am not sure why.
2. I can not reproduce, I get accurate debug result even with large strings. What error do you receive? No error code?

**Comment by nhahtdh** [comment]
The error message is

> The regex debugger was unable to debug your pattern due to an error.
> Unknown error occured

It's intermittent, so I guess it's memory issue. Increasing the length of the test string seems to increase the chance of the issue happening.

I'm using 32-bit Firefox (48.0.1) by the way.

**Comment by firasdib** [comment]
What does your console say?

**Comment by nhahtdh** [comment]
Nothing out of ordinary. Just the normal `asm.js` compiled successfully and stuffs.

**Comment by firasdib** [comment]
I'm running a new build now that will output the error itself for you, give it another go in 5 min and tell me what you find out. I'm on slack and IRC if you want to make this message loop shorter 😄

**Comment by nhahtdh** [comment]
Error message:

> An unhandled error was thrown, please report this
> out of memorypcreWorker.js:7:281
> [579]/self.onmessage()

**Comment by firasdib** [comment]
Great. So the issue is your browser is running out of memory trying to clone the objects. I'm surprised you got this to work on v1 but not v2 as they use the same method of posting data. I've posted info in the private repo on how we can solve this.

**Comment by nhahtdh** [comment]
I'm on IRC, but probably for a short time anyway. Cannot find you there.

**Comment by firasdib** [comment]
It just hit me after comparing new and old version, that the new version is generating 2million results, while the old version only 200 thousand. This is definitely the culprit. Question is why.

**Comment by nhahtdh** [comment]
Both issues fixed. We might need to readjust the match limit or allow user to adjust it themselves, but that's for when someone file an issue requesting for it.
