### ISSUE TITLE
Display whitespace feature in version 2 and debugging

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#599]
[This test case](https://regex101.com/r/aP5zR6/7) from https://github.com/firasdib/Regex101/issues/595 is a good example of where display whitespace with proper support in the regex debugger would help debugging the issue.

What we currently have in version 2 doesn't have any indication that the new line is matched in step 36:

![](https://cloud.githubusercontent.com/assets/564162/18045038/fa73c616-6dfa-11e6-8ef6-c1dc947b4260.png)

I have no idea how to make it clearer giving that version 2 no longer has the DISPLAY WHITESPACE option.

Version 1 with DISPLAY WHITESPACE on is buggy and fails to show the new line being matched in step 36. However, if it's implemented properly, it would be clear what is happening here.

![](https://cloud.githubusercontent.com/assets/564162/18045234/08ba1ddc-6dfc-11e6-9118-44f89ac981e0.png)

**Comment by firasdib** [comment]
Perhaps we should by default show whitespace in the debugger?

**Comment by nhahtdh** [comment]
I think it's a good idea to do so. There is a bit of an edge case where people actually use the characters which represent whitespaces in the regex or the input, but I guess those are rather rare.

**Comment by Ouims** [comment]
Unsure why you removed the option, I think it should be enabled by default, but we should still be able to disable it, why was it removed?

**Comment by firasdib** [comment]
@Ouims It was removed because it was messy to implement with the editors I'm currently using. I will add it for the regex debugger though.

**Comment by firasdib** [comment]
I have added newline characters like shown in the screenshot to the regex debugger.

**Comment by TWiStErRob** [comment]
Will you consider adding whitespace display for input later? I sometimes use regex to clean up whitespaces. Here's an incomprehensible one without showing whitespaces: https://regex101.com/r/R03MOf/1

**Comment by firasdib** [comment]
@TWiStErRob Perhaps in the future. You can open an issue about it specifically.
