### ISSUE TITLE
Public source code?

### ISSUE THREAD

**Issue by Hamz-a** [firasdib/Regex101#6]
Will you ever put the source code online? Or maybe a part of it? You might get support from the community.

**Comment by J5lx** [comment]
:+1: Definitely agree!

**Comment by rugk** [comment]
:+1:
So when will this future arrive?

If you're already using GitHub I think it would be a great idea to Open Source like it was already suggested in https://github.com/firasdib/Regex101/issues/77 and https://github.com/firasdib/Regex101/issues/89

You will get a star if you do so. That's for sure. :smiley:

**Comment by styfle** [comment]
:+1:

**Comment by dicm** [comment]
Just here to say that an open source of it would be great! WIll donate if / when it becomes open source.

**Comment by tuxayo** [comment]
Me too, it's a really nice tool that I wish would be durable by being open sourced

**Comment by rognoni** [comment]
Rereading...
http://www.gnu.org/philosophy/open-source-misses-the-point.html

**Comment by NekR** [comment]
@firasdib you could really use some help to make it offline capable and PWA, if it were open source..

**Comment by rugk** [comment]
@firasdib, so [in the FAQ](https://github.com/firasdib/Regex101/wiki/FAQ#will-you-open-source-regex101) you state you have no such plans, which is a bit different to your last statement "maybe in the future".
I'd suggest you: right now. :smiley: 

Also you could reopen this issue when you think to potentially FLOSS it* in the future…

\* (yeah, using this as a verb sounds crazy, …)

**Comment by DMW007** [comment]
6 years later, and sadly it's still proprietary. I'd also donate if regex101 goes open source.

**Comment by Ailothaen** [comment]
I support this suggestion. Even if we can still access the website, having an offline version would be useful for settings where there is no internet access, or when we are dealing with sensitive data that must not leave the company's network.

**Comment by Doqnach** [comment]
Offline version is not part of this discussion, please see #76 instead.

**Comment by Ailothaen** [comment]
I think I badly explained it: what would be nice, in my case, is having the source code of the app, so it can be hosted on one's own servers. An offline version is useful, but as it is opaque its code cannot be seen, and it is a concern when we are dealing with sensitive data.

**Comment by Doqnach** [comment]
If you use it offline, no data is ever sent to the server. If you don't save an entry, no data is sent to the server.
So you have full control over what data is sent to the server if that is your concern.

**Comment by savchenko** [comment]
@Doqnach , I think the point @Ailothaen makes is valid: if development is on "air-gapped" network, regex101 can't be loaded in a first place.

**Comment by Tayflo** [comment]
> Rereading...
> http://www.gnu.org/philosophy/open-source-misses-the-point.html

I quite agree with this. The point should not be (only) about practicality but (also) about freedom – freedom to understand, to change and to have durable access.
I'm not highly comfortable with the idea of relying, on a routine basis, on a non-free software, that I won't be able to study or to amend.
[gskinner/regexr](https://github.com/gskinner/regexr/) may have slightly less features, but is open sourced.

**Comment by tacerus** [comment]
> [gskinner/regexr](https://github.com/gskinner/regexr/) may have slightly less features, but is open sourced.

Thank you for the tip! I was looking for something like this in the past.

**Comment by valerio-bozzolan** [comment]
12 years ago, the author started writing many times this positive phrase about open sourcing the tool:

> Maybe in the future.

12 years later, that's the longest [cookie licking](https://www.redhat.com/en/blog/dont-lick-cookie) lesson I've ever learned. That is, make everybody believe you will work in a direction, while receiving donations for that, but the author just wants to work alone, on a website that says "It's on GitHub", but in that creative way of having no source code at all, using GitHub like a nonsense ticket system to attract a community that should just go away on a 100% open source project, like https://github.com/gskinner/regexr/ , so that there is mutual help, and not just 1 user controlling everybody else.

Thanks for all the fish.
