### ISSUE TITLE
Warn about regular expressions that are vulnerable to ReDOS

### ISSUE THREAD

**Issue by rillig-nm** [firasdib/Regex101#600]
In many implementations of regular expressions, `^(?:a{1,4})*$` can take exponential time to match. This affects Perl, Java, PCRE and probably other engines.

Regex101 should warn about these constructs. In this example, it is the nested quantifier that leads to backtracking. Matching the string `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaab` against `^(?:a{1,4})*$` takes a very long time.

See https://en.wikipedia.org/wiki/ReDoS

**Comment by OnlineCop** [comment]
There is a timeout period available for the regex101 site, exactly for this reason. You can find the value under Settings, in the top-right corner of the regex101 page. If you have an expression which could take a long time (and you want it to try longer before timing out), you can increase that value.

If an expression has catastrophic backtracking like that, there will be an error in the output, and you can use the "regex debugger" on the left to evaluate where the backtracking is occurring.

It's extremely difficult to consistently calculate when a pattern could result in this kind of situation. A pattern as simple as what you showed might not be that problematic, but anything that involves a lot of branches or uses a lot of recursion may be impossible to be able to determine.

Hence the timeout: you can tell in real-time that you've got catastrophic backtracking occurring, and adjust your regex accordingly.

I'm going to mark this as closed. If I'm missing something, please elaborate.
