### ISSUE TITLE
Python code generator should escape backslashs in the test string

### ISSUE THREAD

**Issue by etiktin** [firasdib/Regex101#601]
To demonstrate the issue, let's say my test string is (you can also see it at https://regex101.com/r/aI4aJ7/1):
`ab\'c`
And I want to match:
`b\'`
So my regex would be:
`b\\'`
The generated Python code is:
```python
import re
p = re.compile(ur'b\\\'')
test_str = u"ab\'c"
 
re.search(p, test_str)
```
Run it in a python REPL and you'll see no match is found.
If you escape the backslash in `test_str` it will work:
```python
import re
p = re.compile(ur'b\\\'')
test_str = u"ab\\'c"
 
re.search(p, test_str)
```

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/463. Fixed in version 2, which will be released soon.
