### ISSUE TITLE
Restrict choices of regex delimiters in PHP/PCRE

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#602]
Currently, the list in beta version has `'` and `"` included, which will be confusing to escape as we need to include the regex inside string literal (and the code generator currently fails to generate correct code for `'` and `"`). I suggest that we remove them to narrow down the list to `` ` `` `~` `@` `%` `;` `/`, as in the version 1.

**Comment by firasdib** [comment]
You're right. Fixed.
