### ISSUE TITLE
Choice of font causing ~ looking like – in the delimiter selection list for certain zoom level

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#603]
On default zoom level (100%), Firefox 48 and Chrome 52, the `~` in the delimiter selection list looks like a dash.

Below is screenshot for Chrome, but the same is observed on Firefox.

![Chrome screenshot](https://cloud.githubusercontent.com/assets/564162/18087586/26bf3f44-6ee0-11e6-951d-fb06b5b3a10a.png)

Changing the zoom level will make its appearance toggles between tilde and dash, but it generally appears as tilde on zooming in.

**Comment by firasdib** [comment]
Funny, not the case for me. I suppose it depends on your system fonts.

**Comment by nhahtdh** [comment]
Seems to be some sort of rendering bug of Open Sans. (I'm on Windows 7, btw).

**Comment by firasdib** [comment]
Funky. Not sure what I can do about it besides just live with it

**Comment by firasdib** [comment]
Seems this semi-known: http://stackoverflow.com/questions/26568908/google-web-font-open-sanss-tilde-rendering-as-a-dhash-when-the-font-size-is-13

**Comment by TWiStErRob** [comment]
You could just add `font-weight: bold` to fix the issue. It fixes Windows and doesn't affect others.

**Comment by firasdib** [comment]
@TWiStErRob Then I need to add that rule to every place where a tilde might potentially be used.

**Comment by TWiStErRob** [comment]
That's possible, however this issue is about the selector list which would benefit from bold or even very bold text anyway. Note that when I select the tilde, the selected delimiter around the regex already shows correctly.
