### ISSUE TITLE
Beta: Ruby over-escaping backslashes

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#605]
For the regex `/\"/`, the code generated for Ruby is `re = /\\"/`, which over-escapes the backslash.

The code should be `re = /\"/` instead (like JavaScript)

**Comment by firasdib** [comment]
ping @Zarthus

**Comment by Zarthus** [comment]
I don't have anything to add.

**Comment by firasdib** [comment]
Fixed. Please verify and close.

**Comment by nhahtdh** [comment]
Confirmed fixed :1
