### ISSUE TITLE
Beta: Rust code generator wrong handling of raw string in the call to Regexp.new

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#606]
[Raw string literal in Rust](https://doc.rust-lang.org/reference.html#raw-string-literals) simply treats everything inside literally (`\` doesn't have special meaning), and the string literal must be terminated by a double quote which is followed by matching number of `#` before the opening quote.

Therefore, given the regex, `/"/`, converting it to `Regex::new(r"\"")` will result in unterminated string literal - we have `r"\"` as one string and `"` the opening quote of a new string.

**Comment by nhahtdh** [comment]
One option is to search for the maximum number of `#` which goes right after a `"` in the regex string, and insert as many `#` plus one before opening quote and after closing quote.

The other option is to switch to regular string, which requires double escaping, though I guess people would prefer the raw string literal for regex..

**Comment by firasdib** [comment]
ping @Zarthus

**Comment by Zarthus** [comment]
is this still the case with https://github.com/firasdib/Regex101/issues/572? I don't write rust so I have nothing to add here and it seems like you've already for everything figured out.

**Comment by firasdib** [comment]
@Zarthus yes, we need to add `#` before and after the string, or switch to regular string

**Comment by firasdib** [comment]
Fixed (perhaps not bullet proof, but likely good enough)

**Comment by nhahtdh** [comment]
It seems that you count the number of `#` in the string. It's not necessary. Just find the longest string which matches `"#*` in the regex string.

**Comment by firasdib** [comment]
@nhahtdh thanks, adjusted.

**Comment by nhahtdh** [comment]
Failed for this case ```~!@#$%^&*()_+{}|[d]\\:";'<>?,.\/"klsjf"##skdjhf"#```.

Simpler test case `""##"#`, expected result `r###"""##"#"###`

**Comment by firasdib** [comment]
@nhahtdh 

I wen't with 

```js
(regex.match(/"#*/g) || ['']).reduce((a, b) => a.length > b.length ? a : b).length;
```

Both are interesting solutions though 😄
