### ISSUE TITLE
I have to login every time a new session

### ISSUE THREAD

**Issue by Kristinita** [firasdib/Regex101#607]
### Purpose

I want each new session I went to regex101.com under my account. At all other sites in my browser, I do not need to «Sign In», I always enter into my account logged.

### Steps to reproduce

I worked in regex101.com → I close my browser → I open site regex101.com again → I need «Sign In» to enter in my GitHub account.

### Environment

Windows 10 Education
Firefox 48.0.2, cookies enabled for me

Thanks.

**Comment by firasdib** [comment]
This should be fixed in v2. I'll leave this open to verify.

**Comment by firasdib** [comment]
As this is fixed in v2 I see no point of leaving this open. If it were to happen again when v2 is launched, feel free to reopen.

**Comment by Kristinita** [comment]
@firasdib, when v2 is planned? Thanks.

**Comment by firasdib** [comment]
@Kristinita It's currently undergoing beta testing, I hope soon.
