### ISSUE TITLE
Clarify the branding

### ISSUE THREAD

**Issue by Microserf** [firasdib/Regex101#608]
I just discovered the site tonight, and love the idea! I will be bookmarking it and coming back again!

One thing that struck me as a bit odd, however, was the branding. The domain name is `regex101.com`, but the top-left corner calls it "regular expressions 101".

I wonder if it would be a good idea to clarify the branding, and put `regex101` in the top-left corner. This way, if someone sees or remembers seeing "that cool site, Regular Expressions 101", they may first try `regularexpressions101.com`, `regexp101.com` and/or a Google search before finding the site.

Unifying the branding could pose one less obstacle in the user acquisition funnel.

**Comment by Ouims** [comment]
Frankly, when you go to a website, you usually remember either part of the name or the whole name.
Given browser's features nowadays, by just starting to type reg.. the browser will immediately suggest regex101.com if you visited it already, and I don't know anyone who would try to type regularexpressions101.com, it's very long. In any case google will solve the problem, plus, the text "regular expressions 101" fits better, it occupies more space.
So imo, the obstacle you are talking about is just not there, people dealing with regex certainly have some kind of computer science knowledge/background, that won't be an obstacle to them, or did that happen to you :)?

**Comment by Microserf** [comment]
Nope, didn't happen to me. It was just an observation that I had hoped could help make the site's branding a bit clearer/stickier.

**Comment by firasdib** [comment]
I'd like to keep the full name, `regular expressions 101` and don't think it confuses things.
