### ISSUE TITLE
The regex library screen isn't part of the browser history

### ISSUE THREAD

**Issue by Microserf** [firasdib/Regex101#609]
**Steps to reproduce:**

1. Go to http://regex101.com/
2. Observe that you are in a blank "regex tester" screen
3. Click on "regex library" link at the top
4. Wait for the regex library to load
5. (Optional) set your search and filter conditions
6. Select a pattern to view its details
7. Click on the pattern title, to open it in the "regex tester" tool
8. Hit the browser back button

**Expected result**

1. You navigate back to the regex library, with your search and filter parameters as you left them.
2. You can then pick another pattern and repeat steps 6-8 until you find the needed pattern

**Actual result**

1. You are brought back to (2)
2. You must then load the regex library again, set your search and filter parameters again, and risk losing track of which patterns you've looked at, and which ones you haven't.

**Workaround**

1. A quick workaround is to ask the browser to open the patterns (step 7) in a new window.
2. Having the pattern links auto-open in a new window (i.e. `<a target="_blank" ... >`) would present an easy workaround as well, but I think a better fix would be to have the regex library modify the window URL and/or insert itself into the browser history stack.

**Comment by OnlineCop** [comment]
This is a known issue, and has been resolved in the beta version of the site, which should be available soon.

**Comment by firasdib** [comment]
As @OnlineCop, the old website is a static SPA which does not utilize the URL. The new version fixes this. It will be out soon!
