### ISSUE TITLE
[VERSION2] Auto-complete Brackets: Should not complete in character class

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#612]
- Enable `Auto-complete Brackets` under Settings
- Create a character group: `[a-z]`
- Within the character group, add `\[`

The closing `]` bracket should not be added when inside a character class. Deleting the previous `[` character should not then remove both itself and the closing `]`.

Outside of the character class, this is probably fine.

**Comment by firasdib** [comment]
The function is not context aware, it just adds the brackets. I can look into this in the future.

**Comment by firasdib** [comment]
This is not worth the extra work I reckon, so I'll close this. If this is an issue that bothers more people we'll see more issues opened.
