### ISSUE TITLE
No flexibility on the PHP string delimiter in the code generator

### ISSUE THREAD

**Issue by florian-bailly** [firasdib/Regex101#613]
Hello,

It's not possible to chose single quotes on the generated code for PHP.
Single quotes are better for this usage because its content is not interpreted.

Everytime I generate my code I need to replace escaped double quotes by single quotes and replace quotes by escaped single quotes because I only use single quotes in my project (except if the content of the string needs to be interpreted of course but for a regex it's not the case).

It would be nice if there could be a "quote toggle" to choose between simple/double quotes.

**Comment by nhahtdh** [comment]
In version 2, the quote will always be single quote to reduce escaping. I'm aware of use cases where double quote is better, usually involving those which uses a lot of single quote `'` in the regex, though I'm not sure about introducing a toggle to the UI.

**Comment by firasdib** [comment]
The new version is going to use single quotes, always.
