### ISSUE TITLE
[VERSION2] replacement string autofill hiccup

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#614]
I never thought of pasting a `s/find/replace/g` for some reason but that thing is so awesome! 

Anyways, it seems there's a hiccup in V2 where *it doesn't insert the replacement string at all*. 

Chrome doesn't complain but FF says `unreachable code after return statement pcrelib.js:5:60` however it fails to actually highlight that part of the code in the minified js file so I don't know if that's really related to this or not. 

To clear it up, [behavior can be seen here](https://bugout.regex.cf/auto-fill-for-substitution-hiccup.mp4).

| OS        | Browser           | Version  |
| ------------- |:-------------:| -----:|
|OS X 10.10.5     | Chrome | 52.0.2743.116 |
|OS X 10.10.5     | Firefox | 48.0.2 |

**Comment by firasdib** [comment]
Argh, this again. Time to refactor. Thanks for the report.

**Comment by firasdib** [comment]
This should be fixed now. I've pushed it live on the beta site, please verify that I didnt goof anything up. If all is OK, close this issue please.

**Comment by working-name** [comment]
Confirmed, working as expected in both desktop browsers and Webkit on iOS. Good job!
