### ISSUE TITLE
ES6 - Firefox y flag behavior detection

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#615]
As per https://github.com/firasdib/Regex101/issues/564, we need to warn Firefox users who uses old version with the stupid behavior of `y` flag. We can execute the following code to detect:

    'aaa'.match(/^a/gy)

In the old version, there are 3 matches, while there will only be 1 match in the new version.

**Comment by firasdib** [comment]
Looking at http://caniuse.com/usage-table it seems there are very few users using an older version of FF. Should we run this test, if its found, disable the `y` flag as it has unexpected behavior?

**Comment by nhahtdh** [comment]
When you disable it, I would prefer that the option is still there, but the user cannot include the flag. When the user tries to, we can display some text to explain why it's disabled. Either that, or we put an error in the explainer saying that the `y` flag is not supported on your browser.

Another option is still allow user to test, but put a warning in the explanation section. I initially want to suggest this approach, but you will need to display a different explanation for `^` when `y` flag is used in old version, which is rather wasteful effort for a feature that is non-standard.

**Comment by firasdib** [comment]
I see where you're coming from, but it just feels like a lot of extra work thats simply not worth it. Easiest would be to just remove the option entirely as it doesn't align with the expected features.

**Comment by firasdib** [comment]
@nhahtdh Lets start with disabling it when the behavior does not align, and if we get any issues about it, we revisit. Sounds good?

**Comment by nhahtdh** [comment]
That's fine with me.

**Comment by firasdib** [comment]
Added
