### ISSUE TITLE
Handling of \number escape in Python

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#619]
Pseudocode:
- If `\` followed by `0`, continue to take **up to** 2 octal digits (can be 0, 1, or 2) and interpret as octal escape
- If `\` followed by `[1-9]`:
  - If found 3 octal digits, interpret it as octal escape. If out of range (larger than `\377`), throw error.
  - Otherwise, continue to take **up to** 1 decimal digit (can be 0 or 1) and treat it as group reference

Here is the reference implementation from Python source code:

```
        elif c == "0":
            # octal escape
            escape += source.getwhile(2, OCTDIGITS)
            return LITERAL, int(escape[1:], 8)
        elif c in DIGITS:
            # octal escape *or* decimal group reference (sigh)
            if source.next in DIGITS:
                escape += source.get()
                if (escape[1] in OCTDIGITS and escape[2] in OCTDIGITS and
                    source.next in OCTDIGITS):
                    # got three octal digits; this is an octal escape
                    escape += source.get()
                    c = int(escape[1:], 8)
                    if c > 0o377:
                        raise source.error('octal escape value %s outside of '
                                           'range 0-0o377' % escape,
                                           len(escape))
                    return LITERAL, c
            # not an octal escape, so this is a group reference
            group = int(escape[1:])
            if group < state.groups:
                if not state.checkgroup(group):
                    raise source.error("cannot refer to an open group",
                                       len(escape))
                state.checklookbehindgroup(group, source)
                return GROUPREF, group
            raise source.error("invalid group reference", len(escape))
```

**Comment by nhahtdh** [comment]
# Test cases

The first token is whatever indicated in the heading. Entries with 2 tokens are commented as such.

## Octal escape

```
\0
\080 # Parse as \0 and string 80
\09 # Parse as \0 and string 9
\00
\000
\01
\016 # Parse as \01 and string 6
\070
\110
\117
\377
```
## Group reference

```
\1
\11
\118 # Parse as \11 and 8
\409 # Parse as \40 and 9
\778 # Parse as \77 and 8
\9
\99
\990 # Parse as \99 and 0
```
(Of course, group reference must reference to a valid group, but this only test how the parser handles the input)

## Bad octal escape [FAIL]

```
\400
\550
\777
```

**Comment by firasdib** [comment]
We need to spec this for all the flavors, because it seems to differ between them all, and my existing code probably does not fulfill the spec for any of them. Do you have time to go through it? Perhaps we can help eachother out over IRC or something.

**Comment by firasdib** [comment]
This is very messy in both PCRE and JS:

## PCRE

```
     After \0 up to two further octal digits are  read.  In  both
     cases,  if  there are fewer than two digits, just those that
     are present are used. Thus the  sequence  \0\x\07  specifies
     two binary zeros followed by a BEL character (code value 7).
     Make sure you supply two digits after the  initial  zero  if
     the character that follows is itself an octal digit.

     The handling of a backslash followed by a digit other than 0
     is  complicated.   Outside  a character class, PCRE reads it
     and any following digits as a decimal number. If the  number
     is  less  than  10, or if there have been at least that many
     previous capturing left parentheses in the  expression,  the
     entire  sequence is taken as a back reference. A description
     of how this works is given later, following  the  discussion
     of parenthesized subpatterns.

     Inside a character  class,  or  if  the  decimal  number  is
     greater  than  9 and there have not been that many capturing
     subpatterns, PCRE re-reads up to three octal digits  follow-
     ing  the  backslash,  and  generates  a single byte from the
     least significant 8 bits of the value. Any subsequent digits
     stand for themselves.  For example:

       \040   is another way of writing a space
       \40    is the same, provided there are fewer than 40
                 previous capturing subpatterns
       \7     is always a back reference
       \11    might be a back reference, or another way of
                 writing a tab
       \011   is always a tab
       \0113  is a tab followed by the character "3"
       \113   might be a back reference, otherwise the
                 character with octal code 113
       \377   might be a back reference, otherwise
                 the byte consisting entirely of 1 bits
       \81    is either a back reference, or a binary zero
                 followed by the two characters "8" and "1"

     Note that octal values of 100 or greater must not be  intro-
     duced  by  a  leading zero, because no more than three octal
     digits are ever read.
```

## Javascript

`\n` is either a backreference or an octal escape. The rules seem to be

1. If there are `n` capture groups, its a backreference.
2. If there are less capture groups, then its parsed as an octal escape.
3. It's parsed as an octal escape as far as it can, for example, `\19` would be an octal escape `\1` followed by a literal `9`.
4. If it can't be parsed as an octal, and it can't be parsed as a backreference, it's a escaped string.

**Comment by firasdib** [comment]
@nhahtdh unless you can find any info that contradicts my findings, I'll get to work implementing it tomorrow.

**Comment by nhahtdh** [comment]
@firasdib You might want to use the latest definition from http://www.pcre.org/original/pcre.txt

       The handling of a backslash followed by a digit other than 0 is compli-
       cated,  and  Perl  has changed in recent releases, causing PCRE also to
       change. Outside a character class, PCRE reads the digit and any follow-
       ing  digits  as  a  decimal number. If the number is less than 8, or if
       there have been at least that many previous capturing left  parentheses
       in  the expression, the entire sequence is taken as a back reference. A
       description of how this works is given later, following the  discussion
       of parenthesized subpatterns.

I think we need to generate a bunch of test cases for PCRE for all 3 digit sequences of `\number` and run it through pcretest to get the expected behavior.

As for ES6, the parsing behavior differs when `u` flag is on or not. You can specify back-reference to capturing group 1000 in ES6:

    new RegExp('()'.repeat(999) + '(a)\\1000', 'u').exec('aa')

Here is [the specs](http://www.ecma-international.org/ecma-262/6.0/#sec-regular-expressions-patterns) that we need to follow. This is the extended grammar for browser implementation, which includes octal escape support in non-`u` mode.

**Comment by firasdib** [comment]
@nhahtdh What version does that reflect? Mine was from the 8.39 text file. Do you think you will be able to generate those test cases for me? It would make it easier when I implement for sure.

Ugh grammars, how complicated 😦

**Comment by firasdib** [comment]
I've implemented this to the best of my doc-reading-abilities. Please give it a go.
