### ISSUE TITLE
Matching /$/gm against a\n in Go resulting in 2 matches at the same position

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#620]
As shown in the screenshot, the 2 matches starts and end at the same indices (`1-1`), which is incorrect.

![](https://cloud.githubusercontent.com/assets/564162/18346626/81b5320c-75eb-11e6-8d0f-1849624695b3.png)

The correct result, as tested by firas:

![](https://i.imgur.com/yGv4bAx.png)

**Comment by firasdib** [comment]
Running the following code

```go
package main

import "fmt"
import "regexp"

func main() {

    r, _ := regexp.Compile("(?m)$")

    fmt.Println(r.FindAllStringSubmatchIndex("a\n", -1))
}
```

Gives me `[[1 1] [2 2]]` - so the indices in that screenshot are wrong as well I believe. But either way, it should not report two matches at the same position. Now the question is why this is happening, and is quite likely something to do with my matcher.

**Comment by firasdib** [comment]
Fixed and pushed. Thanks for the help.
