### ISSUE TITLE
Operator OR pipe | don't work efficient with operands order

### ISSUE THREAD

**Issue by wirelesss** [firasdib/Regex101#623]
I found bug with this example:

REGEXP:
`X(X*|(\([0-9]*[1-9]+[0-9]*\)))?`

MODE: /g

DATA TEST:

RESULTS:
MATCH: X 
X (20)
X(1)
X(01)
X(10000)
X(000001)
MATCH: XXXXXXXXXXXXXX
x(000001)
x(000000)
X(000000)

But other cases don't recognize like "X(10000)", etc.

If I swap operands like this:
`X((\([0-9]*[1-9]+[0-9]*\))|X*)?`
RESULTS:
MATCH: X 
X (20)
MATCH:X(1)
MATCH:X(01)
MATCH:X(10000)
MATCH:X(000001)
MATCH:XXXXXXXXXXXXXX
x(000001)
x(000000)
X(000000)

It should work with last results independent operands sort.

**Comment by nhahtdh** [comment]
It's how backtracking engine works. It will evaluate the options in alternation from left to right, and stop at the first one that matches.

Your requirement is not too clear, so I can't give much advice regarding the regex, except for changing `X*` to `X+`, since the case of empty string has been covered by `?`.

**Comment by wirelesss** [comment]
My suggest is when use OR operator, that it recognize the more long operand:
A | B  , with lengthOfOperand(B) > lengthOfOperand(A).

I hope you accept this idea.
Thanks in advance.

**Comment by nhahtdh** [comment]
The engines in PCRE/PHP, Python, Java, Onigmo/Ruby, JavaScript,... are backtracking engine, which evaluates alternation from left to right. Regex101 is a regex testing site, and we strive to replicate the behavior of the target engine. If you want the behavior changed, file a bug to those projects, though it's unlikely that they will change the behavior.

There is also POSIX BRE/ERE where the engine will try to find the left-most longest match. In those engines, order in alternation is irrelevant. Your regex will probably work in such engine. Unfortunately, regex101 currently doesn't support those flavors.
