### ISSUE TITLE
Matched groups highlight is wrong

### ISSUE THREAD

**Issue by QuestionAndAnswer** [firasdib/Regex101#624]
Found highlight error.

Browser: Chrome  52.0.2743.116 m
Screen Resolution: 1920x1080

Regex: /(-?[0-9]+)/g

Test string: M6386 3345l-280 -280 15 -15 279 280 0 15 -14 0zm14 -15l8 7 -8 8 0 -15zm-294 280l280 -280 14 15 -279 280 -15 0 0 -15zm15 15l-8 7 -7 -7 15 0zm-280 -295l280 280 -15 15 -280 -280 0 -15 15 0zm-15 15l-7 -8 7 -7 0 15zm295 -280l-280 280 -15 -15 280 -280 15 0 0 15zm-15 -15l7 -7 8 7 -15 0z

![image](https://cloud.githubusercontent.com/assets/6842709/18504463/118727f4-7a6b-11e6-9966-d14c6c04d38e.png)

**Comment by firasdib** [comment]
Thanks for the report @QuestionAndAnswer. This is a known bug, which has been resolved in the new version which I aim to release this week.

**Comment by nhahtdh** [comment]
As firas said, dup of https://github.com/firasdib/Regex101/issues/321
