### ISSUE TITLE
inline modifier

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#629]
https://37.139.17.130/r/fwVLwY/1

it doesn't seem to recognize inline modifier

**Comment by firasdib** [comment]
What inline modifier?

**Comment by Ouims** [comment]
...,
That's maybe another issue, it looks like you fixed the issue nonetheless?

About the issue, if i load a regex link, edit the content of stuff and click fork the regex, it's forking the old content, is this intentional?

**Comment by firasdib** [comment]
Yes. The behavior was intended to fork the permalink, not the current changes in the editor.

**Comment by Ouims** [comment]
could be a good idea to be able to fork the current content instead of having to reload a new page =)

**Comment by firasdib** [comment]
Again, what you're saying makes no sense and is not true. The site does not need to be reloaded. The fork happens on the server and it grabs the latest saved information there, NOT what you have locally modified.

**Comment by Ouims** [comment]
it made perfect sense, you missed the point, forking the new content is not possible currently, to do it, you have to do it manually. I'm not sure what makes no sense there :)

**Comment by Doqnach** [comment]
Maybe disable forking if there are unsaved changes?

**Comment by Ouims** [comment]
@Doqnach I did not see before posting that comment, but I had actually suggested that he adds something for the current content, and he did, if you hold shift while clicking 'fork' it will fork the current content you see instead of the original content :)
