### ISSUE TITLE
Ability to copy as C string

### ISSUE THREAD

**Issue by rakeshta** [firasdib/Regex101#632]
Currently i have to add extra back-slashes `\` to escape the existing ones in the regex pattern. It would be very helpful if I could 'copy as c-string' that does this automatically.

Bonus would be an option to 'paste from c-string' that does the reverse!

**Comment by firasdib** [comment]
The new version has a bunch of built in code generators that will escape and generate code for a particular regex. I believe you can use this to get an escaped string.

**Comment by rakeshta** [comment]
Thanks @firasdib. I will use that.
It would still be cool if I could do it directly in one click.

PS: I love Regex101. Thank you for making it. It's a life-saver.

**Comment by nhahtdh** [comment]
Different languages have different escaping rules, so it doesn't quite make sense to support one way to escape the string when a flavor can be used in different languages.

**Comment by rakeshta** [comment]
True. But I would argue in favour of supporting the most popular languages. 

C style would be a good start as it is compatible with a lot of languages like java, objective c, swift etc. 

Add JavaScript style and you would have supported most of the languages in the top 10 list.

**Comment by firasdib** [comment]
Javascript is already supported, both in the editor and in the code generator.
