### ISSUE TITLE
Copy/Paste Visualstudio

### ISSUE THREAD

**Issue by SamuelCarrier** [firasdib/Regex101#633]
When doing a copy/paste of a pattern it adds spaces and so when you execute the c# code it doesn't work. It would be better if no useless spaces would be added for example  [0-9] becomes [0 - 9]

**Comment by nhahtdh** [comment]
Would you please include browser name, version, OS and the version of Visual Studio? I can't seem to reproduce this problem on Firefox 48.0.2 on Win 7 and VS 2005.

**Comment by firasdib** [comment]
No response from issue creator, closing.
