### ISSUE TITLE
"(.*?) {" does not match python behaviour

### ISSUE THREAD

**Issue by Rich165** [firasdib/Regex101#634]
Hey,

Running a regex string which contains "(.*?) {" which I'm expecting to match in a non-greedy way upto the first left curly brace. In python it becomes a greedy match and matches upto the second curly brace, the correct expression in python to get this to work appears to be  "(.*?) {?" 

As an example I'm trying to match  HTTP-PROFILE in the sample text below;

"Some stuff HTTP-PROFILE { app-service none defaults-from http some-setting { configured thing }  }"

I'm no regex expert, but there is a difference in behavior between regex101 and python (2.7.5) interpreter in this case.

Cheers,

Rich

**Comment by Ouims** [comment]
https://37.139.17.130/r/doED6A/1 this is the version 2 of the website, the pattern is matching correctly.
something that would match HTTP-PROFILE in the string above would be this https://37.139.17.130/r/doED6A/2

**Comment by firasdib** [comment]
I just ran the following code in Python 3:

```python
import re

regex = r"(.*?) {"

test_str = "Some stuff HTTP-PROFILE { app-service none defaults-from http some-setting { configured thing } }"

matches = re.search(regex, test_str)

if matches:
    print ("Match was found at {start}-{end}: {match}".format(start = matches.start(), end = matches.end(), match = matches.group()))
    
    for groupNum in range(0, len(matches.groups())):
        groupNum = groupNum + 1
        
        print ("Group {groupNum} found at {start}-{end}: {group}".format(groupNum = groupNum, start = matches.start(groupNum), end = matches.end(groupNum), group = matches.group(groupNum)))

# Note: for Python 2.7 compatibility, use ur"" to prefix the regex and u"" to prefix the test string and substitution.
```

And it seemed to work as expected. Reopen if you think there is a problem.
