### ISSUE TITLE
Clicking in regex places cursor in wrong position

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#635]
1. Use this regex:

    ```
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.\n\nbbbbbbbbbbbbbbbbbbbbb
    ```
2. resize the main area so that the `\n\n` is at the end of the first line (partially hidden):
    ![image](https://cloud.githubusercontent.com/assets/2906988/18809920/2a36b1fe-8289-11e6-9649-e46644685c9a.png)
3. click on a `b` character

This makes editing long regexes impossibly hard and happened almost every time I used the tool today (5-6 different regexes).

**Comment by OnlineCop** [comment]
Fixed in the beta version: https://37.139.17.130/r/2HXAXf/1
