### ISSUE TITLE
Unit test: null matches

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#637]
The regex `(\.)|.` should capture a literal `.` character and match any other character.

In the unit tests for https://37.139.17.130/r/tbN2iL/1 the character `.` and `!` are used. For both cases, `.` is matched (correct) and capture group 1 equals `.` (correct).

The `!` is matched (correct) and should _not_ be captured, so should match (nothing).

If the "insert comparison string" is left empty, the saved unit test says that it is _null_ [which looks fine](http://imgur.com/a/AhfS4).

What should the values be to indicate that the capture group should NOT match anything?

**Comment by firasdib** [comment]
There is no apparent way of doing it, because when you do that, the first group is not participating. I could add a test for that to ensure it isnt participating.

**Comment by firasdib** [comment]
I updated the unit test code so your permalink is no longer valid, I created a new version to fix it for you: https://37.139.17.130/r/tbN2iL/2/tests

**Comment by OnlineCop** [comment]
Updated the titles (but not the content) for the https://37.139.17.130/r/tbN2iL/3/tests for clarity.

**Comment by firasdib** [comment]
Updated: https://37.139.17.130/r/tbN2iL/5/tests - does this work better? If so, feel free to close the issue.

**Comment by OnlineCop** [comment]
Much better.
