### ISSUE TITLE
Allow to have navigation drawer of rarely used items even on large screens

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#638]
I took a look at your beta after you fixed an issue yesterday. I found two things that could be more consistent with current trends. I'm a long-time Android user and developer and their navigation scheme is really intuitive. It's documented in Material Design: [teaser](https://www.youtube.com/watch?v=Q8TXgCzxEnw), [explanation](https://www.youtube.com/watch?v=p4gmvHyuZzw), [docs](https://material.google.com/).

For example your editor, library, "irc" icons and save, share, flavor, tools actions on the left would be nice to be able to collapse and open them and see the names like this:
![drawer](http://i.imgur.com/LgRyHSi.gif)
Full res: [collapsed](https://lh5.ggpht.com/WK1g2s6NMv0pWJPJPfGBf2tzDgxI0IdSj4YFB2YrZhOI3f3-5sJIYjLLwKF7AEJmfgc=h900), [expaned](https://lh3.ggpht.com/dmKfexnbDeRg_9elMFUQlAJGW0DzYYhKS5XxSWsMZguWyQ8gSN41oQE0mZ2RlS1llv1f=h900)
This is called navigation drawer in material design and is opened/closed by pressing the "hamburger button" (3 horizontal lines in the top left corner). Worth mentioning that I liked the tabs better, it was easier to notice than the beta icons on left and didn't take up extra space like the icons do. Collapsing the actions on the left would be also nice, because I don't think those actions are not used a lot compared to entering the regex/test string and stuff in the right column.

The other thing I noticed is in the quick reference when you open an item:
![image](https://cloud.githubusercontent.com/assets/2906988/18813954/42258438-830c-11e6-8439-2b4b1d1b5c3c.png)
escape and close navigation has always been on the top (browsers have back arrow in upper left, windows have &times; in upper right, and whatever macs do is on the top too), so I suggest you move that down-pointing arrow like this:
![image](http://i.stack.imgur.com/Oul74.png)
I'm an engineer and it took my by surprise that a down arrow would bring be backwards. It was always left or up-pointing or an &times;.
If you make it possible to collapse the reference categories like a drawer, then you have a fixed icon next to quick reference that could change from the hamburger icon to a left-up arrow when a reference item is opened.

Also: what happened to resizable panes? The beta is hard to use on low-res devices.

**Comment by TWiStErRob** [comment]
Ok, just noticed that you already have the drawer, but it's only available when a css breakpoint is hit. I think it would be nice to at least give the option to collapse the mentioned left panes on larger screens too.

**Comment by Zarthus** [comment]
```
(11:16:41) <+Zarthus> the down pointing arrow is actually not uncommon
(11:16:51) <+Zarthus> the left-arrow tends to mean "back", in this case, you're just collapsing it.
(11:17:50) <+Zarthus> one might argue the arrows should be reversed, because it currently displays active status, not what clicking on it will do ('pull it up'), I don't mind either solution
(11:18:19) <+Zarthus> a back arrow on the right side also just doesn't work
```

The key thing with the arrows is that it works really well for things like the substitution window, which is collapsed by default. Perhaps less for the right-side, where they're uncollapsed by default.

**Comment by TWiStErRob** [comment]
> The key thing with the arrows is that it works really well for things like the substitution window, which is collapsed by default.

Yes and that arrow points upward to open the pane, while the reference drill-down is pointing down:
![image](https://cloud.githubusercontent.com/assets/2906988/18814498/586817f2-8315-11e6-8eb1-32ea0e577b94.png)
I guess it's counteracting the animation the fades in from the bottom, but it just feels inconsistent somehow. It's your call in the end.

**Comment by Zarthus** [comment]
it points down because you're collapsing it, generally going down is associated with, and UI wise it makes sense too, because that's the direction it goes to

**Comment by TWiStErRob** [comment]
Looking at it again: I think my confusion comes from the fact that if you just look at the image in my prev comment, you don't see **what** will "go down".

**Comment by firasdib** [comment]
So this was my reasoning with the sidebar.

If your screen is large enough to accommodate it, why not show it. The issue lies in it being entirely hidden when your screen is smaller. My thought process was: this is a regex testing website. If your screen is tiny, you probably just want to see whats important. Anything in the left sidebar is something you're only ever likely to click on once or twice, in most cases. Thus I went with it being completely hidden instead of just collapsed like your int screenshots.

**Comment by TWiStErRob** [comment]
> If your screen is large enough to accommodate it, why not show it. 
> If your screen is tiny, you probably just want to see whats important.

Yes, hiding unimportant stuff to make the important usable is good thinking, but I didn't spend 800 dollars on a monitor because I want to make place for the unimportant stuff, I want to see **more** of the important stuff.

> Thus I went with it being completely hidden instead of just collapsed like your int screenshots.

My suggestion is to be able to collapse (or hide, even better) the sidebars even on larger screens, not just on mobile devices. In the beta version there are two barely-rarely used always visible sidebars taking up space from test string and matched. The live version has 200px wasted space, and beta has 280px.

**Comment by firasdib** [comment]
Right. I could potentially add a setting to always hide the left sidebar if thats what you're asking.

**Comment by TWiStErRob** [comment]
You already have logic to show those two sidebars as a navigation drawer with hamburger icon. If you add an option to always use that logic regardless of CSS breakpoints I would be most pleased ;)

What do you think about the down-arrow thing in quick-ref? I guess you're on the same page with Zarthus.

**Comment by firasdib** [comment]
I'll consider settings for that.

The arrow points down to close the box which entered up and exits down. Makes sense to me.

**Comment by TWiStErRob** [comment]
Renamed to reflect final intentions.

**Comment by firasdib** [comment]
I have recoded the quickref and improved the UX quite a bit. Hit me up on slack/irc and we can test it out.

**Comment by firasdib** [comment]
Added!

**Comment by TWiStErRob** [comment]
Nice, thanks.
