### ISSUE TITLE
Cross-link test strings and matches

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#640]
Current:
![image](https://cloud.githubusercontent.com/assets/2906988/18814542/809512ec-8316-11e6-9a08-fc67e419dfc3.png)

Desired (quick dev tools css hack mockup):
![image](https://cloud.githubusercontent.com/assets/2906988/18814537/5816b488-8316-11e6-8257-9d4710810989.png)

Details:
1. When scrolling down the list of matches on the right the matches should have a `:hover` effect (just simple background), so the currently hovered match is easily distinguishable, even more so than the horizontal lines
2. When I hover the mouse in the _Test string_ area it highlights the match or the group. It would be nice and useful if that hover action also highlighted the same match and same group in the _Match information_.
3. The reverse of 2) should be also true: if I hover a match/group/group value in the right panel the test string area should light up where that match is, this is really useful to see the context of the match. Lighting up could be as simple as adding the brighter border, or fully popping up the black.

Bonuses:
- consider not just highlighting, but actually scrolling to the related match in the other pane: so if I hover in the _Test string_ area, the _Match information_ scrolls so that the match I hovered is fully visible.
- consider a visible line (straight or curved) connecting the two for more obviousity

**Comment by TWiStErRob** [comment]
If you like this, similar could be done for *Regular Expression* &lrarr; *Explanation* panes.

If you're really crazy about it, all 4 panes could be cross-linked: hovering test string character highlights which part of the regex matched that and also highlight the relevant part of the explanation. Hovering part of the regex/explanation highlights that bit in the *Test string* area for **all** matches.

**Comment by firasdib** [comment]
I've considered it, but its not trivial and requires a bit of work, which is why its on the backburner. In v2, match results in the match info pane are lazy loaded as well, which makes the feature not always work which might cause confusion.

**Comment by TWiStErRob** [comment]
> match results in the match info pane are lazy loaded

This only affects the scroll-to-hovered match feature, not the rest. If the match is already in view that means it's loaded and hence can be linked.

Why do you say it's not trivial? As a user (didn't peek under the hood yet) it seems that all the information required is available. You have the match number in both places, you have all the text offsets for all groups. When I do [stuff like this](http://web.twisterrob.net/vis-algo/), I usually just attach the data to the view and also include all the possible views as members of data. This gives `O(1)` access to all UI where model is shown.

**Comment by firasdib** [comment]
It's never as easy as one might think. I can't just include the views everywhere, they are deeply nested and depend on a bunch of things. I'd have to use an event system which would get ugly quick. If I were to do something like this I would need to think about it for a while.

**Comment by TWiStErRob** [comment]
This is where not knowing how the app is structured comes in :) It looks so simple on the surface.

Can you at least do 1) on the list? That should really be comparable to writing a single CSS rule.

**Comment by firasdib** [comment]
I think that when something changes on hover, it's something you can interact with, which you can't in this case. So I'm not convinced just yet.

**Comment by firasdib** [comment]
I've added the ability to allow you to click a group/match in the right sidebar, and have it highlighted in the subject string. Not the other way around, because the match information is lazy loaded (for performance reasons).
