### ISSUE TITLE
Match export button overlaps with scrollbar

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#641]
Beta:
![image](https://cloud.githubusercontent.com/assets/2906988/18818608/50dcadd6-837e-11e6-9522-d0fb8a0f29eb.png)
Live:
![image](https://cloud.githubusercontent.com/assets/2906988/18818611/6fc78374-837e-11e6-9258-e366521e6f18.png)

**Comment by firasdib** [comment]
Browser and os please.

**Comment by TWiStErRob** [comment]
Windows 10, Chrome latest, both x64

**Comment by TWiStErRob** [comment]
Windows 10, Edge 25:
![image](https://cloud.githubusercontent.com/assets/2906988/18827072/0ea0d476-83d1-11e6-95b0-30493659ca26.png)

Windows 10, FF 48:
![image](https://cloud.githubusercontent.com/assets/2906988/18827231/1024b032-83d2-11e6-8662-6bcb493fe3a9.png)

With the dark theme it's invisible on Chrome 53:
![image](https://cloud.githubusercontent.com/assets/2906988/18827004/b707010e-83d0-11e6-85c3-957538b4e589.png)

**Comment by firasdib** [comment]
Thank you for the thorough testing. I've identified the issue, just trying to think of how to fix it.

**Comment by TWiStErRob** [comment]
Is IE11 supported? I can't expand right panes there in the beta.

**Comment by firasdib** [comment]
@TWiStErRob Yes. Do you have any errors in your console?

**Comment by TWiStErRob** [comment]
#642

**Comment by TWiStErRob** [comment]
> just trying to think of how to fix it.

I found that adding `overflow-y: scroll;` to the button displaces it by the right amount from `right:0`:
![image](https://cloud.githubusercontent.com/assets/2906988/18828103/9dd53696-83d6-11e6-9c57-18ffd613281a.png)

but the scrollbar is visible, decreasing the `z-index:0` gives this:
![image](https://cloud.githubusercontent.com/assets/2906988/18828038/5186108a-83d6-11e6-9d8b-9824669a5a84.png)

the problem is that the fake scrollbars also appear when there's no scrolling content in matches:
![image](https://cloud.githubusercontent.com/assets/2906988/18828079/82fcbc54-83d6-11e6-9210-7e4e9bc7099c.png)

**Comment by TWiStErRob** [comment]
by the way button should have an opaque background, regardless of scrolling:
![image](https://cloud.githubusercontent.com/assets/2906988/18828295/6b88f168-83d7-11e6-8c35-a9369e804232.png)

**Comment by firasdib** [comment]
Yes, which is why that is not a good solution. The background thing is a good idea.

**Comment by TWiStErRob** [comment]
I guess adding `overflow-y: scroll` to the match list to always show the scrollbar which hides the other scrollbar is not an option?

**Comment by firasdib** [comment]
No, I will think of another more elegant solution. I will push a fix for IE11. Can you pop on IRC?

**Comment by TWiStErRob** [comment]
> I'm thinking of placing the "export matches" button at the top instead of bottom
> Solves any issues with it overlapping the "Load more" button

That's true, if you add a little top margin above match 1 it could even be permanently visible at half opacity.

Android not wrapping any more, but now it's not centered.

**Comment by firasdib** [comment]
I've added some JS to the mix, that will have to do it. Its not worth wasting more time on this I reckon. If you feel there is more to add, re-open the thread.

**Comment by TWiStErRob** [comment]
Hmm... feels a little annoying, but probably because of my weird fade animation issue with my monitor.
I could accept this as it's much better than the overlapping one, and I agree with spent a lot of time on it.

A quick thought-inducing question: if you added javascript, why didn't you go back to having the absolute positioning in the bottom corner and just offset `right:` with the scrollbar width?

**Comment by firasdib** [comment]
No reason, looked nice :)

**Comment by TWiStErRob** [comment]
The more I see this fading effect after every scroll the more annoying it gets. It's like it wants me to click it, but it's not a "main" functionality, just a little helper.
