### ISSUE TITLE
Beta: panes cannot be expanded in IE11

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#642]
Any clicking on these doesn't do anything:
![image](https://cloud.githubusercontent.com/assets/2906988/18827525/89c40356-83d3-11e6-9dac-3143adc423fc.png)
![image](https://cloud.githubusercontent.com/assets/2906988/18827527/8d352efc-83d3-11e6-90bf-97a06522f767.png)

There's an error when loading the page:
> "TypeError: Object doesn't support property or method 'assign'
   at o (https://37.139.17.130/main.js:2398:131)
   at Anonymous function (https://37.139.17.130/main.js:3123:335)
   at Anonymous function (https://37.139.17.130/main.js:2197:37)
   at c (https://37.139.17.130/main.js:1217:201)
   at Anonymous function (https://37.139.17.130/main.js:2198:88)
   at Anonymous function (https://37.139.17.130/main.js:2863:433)
   at Anonymous function (https://37.139.17.130/main.js:3118:399)
   at Anonymous function (https://37.139.17.130/main.js:2196:34)
   at j (https://37.139.17.130/main.js:2632:268)
   at L (https://37.139.17.130/main.js:2632:356)"

![image](https://cloud.githubusercontent.com/assets/2906988/18827709/7eb017a6-83d4-11e6-8d82-1203de02169b.png)

```
i.SET_REGEX_RESULT:return Object.assign({},e,{matchResult:t.value});
```
![image](https://cloud.githubusercontent.com/assets/2906988/18827585/e55c1ac8-83d3-11e6-9684-8db04c12898c.png)

**Comment by firasdib** [comment]
This particular issue is fixed by adding the missing polyfill.

**Comment by TWiStErRob** [comment]
Was it though? It still can't be expanded because of the `flex: calc` thing.

**Comment by firasdib** [comment]
That detail is not mentioned in this issue. Can you post more information.

**Comment by TWiStErRob** [comment]
I though you already downloaded the VM. The problem probably got lost in chat noise.

After `assign` fix:
![2016-09-26_16-29-40](https://cloud.githubusercontent.com/assets/2906988/18838252/1e2a4eaa-8407-11e6-9122-f75e5e27f215.gif)

potential CSS problem identified by me:
![image](https://cloud.githubusercontent.com/assets/2906988/18838279/31ae2028-8407-11e6-9d1c-d38170daa6a9.png)
CSS fix (invalidated the `flex` shorthand and expanded the the rule:
![image](https://cloud.githubusercontent.com/assets/2906988/18838339/6669766e-8407-11e6-80d2-2efeba3b70bf.png)
visual after expanding that rule (no collapse or expand animation):
![image](https://cloud.githubusercontent.com/assets/2906988/18838342/6c326d44-8407-11e6-8711-b3a585d293bb.png)

**Comment by TWiStErRob** [comment]
Confirmed fixed on beta site.
