### ISSUE TITLE
Beta: Scrollbar misbehaves in Quick reference

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#643]
on Windows 10
Repoes: Chrome 53
Doesn't repro: FF 49, Edge 25

If I navigate in quick reference from any list that already has a scrollbar to another list that requires a scrollbar, the second lists' contents will be hidden below the scrollbar.

Here are some concrete steps:

1. Open https://37.139.17.130/
2. Make sure quick reference is yea big (full screen on 1366x768):
    ![image](https://cloud.githubusercontent.com/assets/2906988/18828657/12a5c89e-83d9-11e6-8478-f20f11507e32.png)
3. Click "anchors" and note that it's nice and readable
4. Click "quantifiers" and note that it's nice and readable
5. Click "group constructs" and note that it's nice  and readable and scrollbar appears
6. Click "meta sequences" and note that it's impossible to read the escaped chars
![image](https://cloud.githubusercontent.com/assets/2906988/18828577/c35bd35a-83d8-11e6-8ecc-2c09816b266d.png)

*By the way, the layout in step 2 is a really good example why #639 (and/or #638) is needed: cannot read the names of the regex constructs and there's no way to make them readable other than clicking them one by one.*

**Comment by firasdib** [comment]
Duplicate https://github.com/firasdib/Regex101/issues/555
