### ISSUE TITLE
New lines are lost when copying substitution output!

### ISSUE THREAD

**Issue by Darker** [firasdib/Regex101#644]
I needed to refactor some sourcecode and I found out that new lines dissapear when I copy text from the "Substitution" output box. That's a very nasty trap.

Is there any workaround for that? I tried to inspect the element for original text, but with no results. Still, the text displays correctly with newlines in the Substitution textbox. Only once I copy it it becomes broken.

**Comment by firasdib** [comment]
Fixed in v2. Issue with some browsers in v1.

**Comment by Darker** [comment]
I don't get it. It's fixed in version that wasn't released yet?

**Comment by firasdib** [comment]
Yes. Its going to be released any day now.
