### ISSUE TITLE
Beta regression: clicking logo clears data

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#645]
On live version if you middle-click
![image](https://cloud.githubusercontent.com/assets/2906988/18842559/bbf82b58-8415-11e6-961c-771b28231170.png)
you get a new tab with empty stuff and your current regex is preserved.

Doing the same on beta (shouldn't we start calling it RC?) reloads the page in place clearing everything out. Granted it asks if you want to leave, but it's a pathological case of webapp trying to be more clever than browser/user by replacing behavior.

Browser independent.

**Comment by firasdib** [comment]
People typically dislike things opening new tabs so I tried keeping that at a minimum. The typical behavior is to open in the same tab for most pages.

**Comment by TWiStErRob** [comment]
Yes, exactly, that normal if you click on it, but notice that I said "middle click"!

**Comment by firasdib** [comment]
Oh my bad. I'll fix.

**Comment by firasdib** [comment]
Fixed!
