### ISSUE TITLE
Substitution backreferences should be colored

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#647]
Captured groups are ever so colorful everywhere in the app, except in substition:

![image](https://cloud.githubusercontent.com/assets/2906988/18845116/a7f9ffe0-8420-11e6-8969-9ef04e2330fa.png)

I propose two changes:

1. easy: use the same colors for backreferences in substitution input box as everywhere else:
\1 \2 \3 \4 $1 $2 $3 $4 should be colored with the same colors as in Match info

2. hard: highlight the replaced string to show where the parts originated from: for example searched `a(.)c`, input `abc adc`, replacement `x$1x`, result: xbx xdx, then the bottom textarea should show x in plain black and `b` and `d` highlighted with group 1 color (green).

**Comment by firasdib** [comment]
You have selected the text in the replacement box which is why its all blue. Regardless, I don't see the value in doing what you're proposing and it involves quite a bit of work.

**Comment by TWiStErRob** [comment]
Sorry, even if I deselect the colors have nothing to do with anything else in the UI:
![image](https://cloud.githubusercontent.com/assets/2906988/18845390/e9210d82-8421-11e6-844b-dc9e4d3af592.png)

Even 1) is so much work?

**Comment by firasdib** [comment]
No, 1. is inconsistent. These are tokens you're inserting, not the outputted result. I would hope the users are clever enough to see what number they have typed without having to have it color coded.

**Comment by TWiStErRob** [comment]
It's not about being clever, if you color-code it helps to associate parts and detect bugs in the replacement string faster. It makes the site more efficient to use. I've been to the other end of the spectrum: used grep in bash a lot without any highlight and it's hell compared to your heavenly colored website.

> These are tokens you're inserting, not the outputted result.

That's true, but they refer to the groups that will be output. I though the color refers to "group N", isn't it? A backreference to `$N` or `\N` is just a shorthand for saying "group N".

**Comment by firasdib** [comment]
I understand, I just don't agree. You have color coded tokens and you have explanations on hover. I think thats more than enough. If I start color coding those references the regex expressions are starting to become inconsistent and weird looking if you ask me. It will be harder to determine which tokens mean what.

**Comment by TWiStErRob** [comment]
But the references are already color-coded in substitution, just with "exists" and "not exists" colors that is not used anywhere else. As far as I know the only other thing that can go in the substitution string are literals and escaped characters, so it wouldn't confuse that field to use the group colors. I agree that in the top regex color-coding the (currently green) parentheses would be too rainbowy.

**Comment by OnlineCop** [comment]
I would side with firas on this one: color in the substitution area doesn't really add much visually, and it adds complexity to the code. Also, if a match group is colored red, how does the user differentiate when there's an invalid substitution number (which currently shows in red)? Yes, it might make something like `$10` (where there is only a single capture group) make the `$1` bold and the `0` show as a normal character, but it adds very little else, IMO.

**Comment by TWiStErRob** [comment]
@OnlineCop Consider this (on the above picture): You're writing a subst string that should output "Something*" (green) and "And|Other" (orange) parts of the input. Currently what you need to do it to either look at the syntax highlighted top regex and count the parentheses as normal, or look at the color (green/orange) in the match information pane and work your way back to figure out that orange is group three and green is group one. Then you enter `$1....$2` in substitution and you see that they're both OK backreferences (colored dark green). Did you notice you made a typo at 2am? If this enhancement is implemented you would get immediate visual feedback (colors) that your output will be correct and you can even be illiterate and still be able to tell that the output will be correct.
