### ISSUE TITLE
Substitution escapes stopped working

### ISSUE THREAD

**Issue by keyserbrian1** [firasdib/Regex101#649]
I am no longer able to use the /n or /t escapes in the substitution pane. They are silently ignored. The substitution deletes the original match, but doesn't put in the newline or tab that should be there.

**Comment by TWiStErRob** [comment]
Repro: https://37.139.17.130/r/TdCcF9/1

@keyserbrian1 you can write \n and \t literally on GitHub, though I suggest that you wrap them in backticks to signify code like so: <code>&#96;\n&#96;</code> &rarr; `\n`

**Comment by firasdib** [comment]
Thanks guys. Silly error on my part. Fixed!
