### ISSUE TITLE
Updating a regex: text should not indicate that users can delete it

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#650]
Creating a new regex should append the text "... It will not be deleted unless you decide to delete it." only to the first version. After that, the only person who should see it is the original author.

Example:
* Person 1 creates and saves the regex
* Person 2 updates the regex

Person 1 should see the delete key on creation, and the note that it will not be deleted unless they themselves delete it.
Person 2 should not see the "unless you decide to delete it" text, as they have no control to delete the regex.

**Comment by firasdib** [comment]
How about we change it to `Unless the owner decides to delete it`

**Comment by OnlineCop** [comment]
I think the sentence should be removed entirely. That wording sounds like the owner decides to delete _your revision_ and not the entire thread (previous revisions included).

**Comment by firasdib** [comment]
Adjusted.
