### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#652]
I want some user discussion and feedback here.

I'd like to have analytics for the site: how many times various areas are used/clicked, which flags are enabled most frequently, which 'code generator' languages are used most.

I want all of the analytics to be opt-in only: but not only that, reporting is _manual_ not automatic. Meaning:
1. Each element that can be clicked on the regex101 site is recorded: 'code generator' link, delimiter (for PCRE and any other language that supports it), IRC, checkboxes toggled under Settings, etc.
2. All data is aggregated offline, client-side. We can use local storage to persist it across sessions if we need.
3. None of the data is ever sent back to the server: users can inspect all the information, and copy-and-paste it from the analytics window into a submission form elsewhere (like github or surveymonkey, or whatever).

I'd like to know which features are being used quite often, and should be promoted forward so it takes fewer clicks to reach. Or, moved to be more prominent: If "code generator" is used as much or more than "save regex", it could be moved from under TOOLS to near the top so it's more visible. Things like that.

No one needs to opt into the analytics, or submit the data if they don't want. Once the regex101 page is loaded, they can unplug their computer from the internet and we'll never "see" them or their data again. But if they choose to share the data with us, great: we can make the site more tailored to be easier for users in the future.

I know that Firas is a huge supporter of privacy, so I want this data to be as transparent as possible, even if the collection process isn't the easiest. Feedback? Thoughts?

**Comment by TWiStErRob** [comment]
My first thought is that you'll get a very skewed statistic this way. The people who give feedback doesn't necessarily represent the grand population: http://ben.balter.com/2016/03/08/optimizing-for-power-users-and-edge-cases/#the-silent-majority-of-users

As long as you don't submit the username/regex/input/replacement strings I think privacy shouldn't be a concern, even if their length is reported (for example to see if regex field need to be multi-line).

I would support the eu-cookie style "Your actions will be collected, anonymized and sent to server. [I want to not do that, please]". If you want to be transparent keep a history of sent data and provide a simple view that lists all that.

**Comment by working-name** [comment]
Since you already are aware that the collection process would not be easy, it's a great idea, and especially careful going about people's privacy. 

On a personal note, I don't mind if people collect anonymous statistics to better their service. However, that doesn't mean I am fine with it happening without my consent or worse, behind my back.

Therefore, I'd say having a notice at the bottom, with an opt-in for analytics is beyond amazing. Also a link explaining what gets collected for those who want to look into it. 

That way you mitigate both privacy concerns and ease of use for raw data.

If however not enough people opt in for analytics, you can always revert to the usual notification that anonymous analytics are collected and you can disable that if you so wish. It's not as"free choice" but it may increase the percentage of people willing to allow anonymous statistics.

**Comment by TWiStErRob** [comment]
@working-name if the data is anonymous, then what's the concern about collecting behind the back (i.e. with an implicit ToS)? (Genuine question, never understood it.)

**Comment by OnlineCop** [comment]
In thinking about the 80/20 issue, most people using the site will never look under the Settings in the first place, where they would have to switch it on to opt in each time. Especially if they are in Incognito, use different browsers, log in from multiple locations, etc.

Of those 20% who opt in, I'd guess that we might (on a good day) get less than 1% of them to go through the process of manually submitting the data. And that number is only for people to report it ONCE, let alone daily, weekly, etc. over longterm.

The opt-out approach grates on some people: Remembering to set that on every device and browser, especially after using Incognito. But it would allow much more data to flow in. Perhaps the site could be bookmarked with a special `?analytics=opt-out` query to allow the user to disable the feature.

Ultimately, Firas would be the final voice on this. If he wants no analytics at all, this would be moot.

**Comment by working-name** [comment]
@TWiStErRob the main issue I have is the "**if**". Ask yourself: *how many sites or pieces of software* do you trust to only collect anonymous things? 

I don't trust, I sniff network traffic and check for myself when I use a service/app that handles my private information.

Therefore, I prefer they don't do things behind my back, and unfortunately I don't have a habit of reading the ToS. It's usually legalese, which bores me.

I've also had instances where I deselected "send usage data & crash reports" yet the app continued to send them. Not cool.

As I mentioned, this is a personal belief, and like many such things it can be skewed by ignorance, poor perception of what's really going on, or plain different personal values.

Sorry, this is probably way off topic.

Going back to the analytics thing, bookmark opt-outs are even cooler than being bothered with a prompt on every device. Another great idea, OC 👍

**Comment by TWiStErRob** [comment]
Personally I would probably never submit the data manually. But if asked by a dialog, I would happily press "Yes" even daily (which would probably get annoying quickly). Other than that, similar to sidebar blindness, I don't care about questions, usually never read them, just assume which answer will dismiss the dialog faster to get on with whatever **I'm** doing. I mean questions like the cookie consent, PP & ToS, ... they're just required noise in everyday life. If I want to use a service I have to accept it regardless of being in real agreement with it. I'm not sure if this mentality is normal, but having a default opted-in status lets the site gather data from people like me who don't care. I agree, for those who care, there must be a way of easily opting out. I like the idea of query param, another idea I'd throw in is IP blocking, though wih dynamic ISP IP assignment it may not work well.

**Comment by TWiStErRob** [comment]
@working-name thanks, and sorry for the detour.

**Comment by TWiStErRob** [comment]
Actually, thinking about it more, nagging the user might not be such a bad idea, if done reasonably. On the first day for new users nothing happens; usage data is collected to local storage. On subsequent visits data is still being collected. After some time (e.g. 100 actions recorded), the site could ask "here's what I have on you, do you allow me to send it home?". User could choose "always, yes, no, never, later" (with some nice UI, not these actual buttons). If they choose yes then another 100 is recorded and asked again. If they say no, then stop recording for a few days/week and ask if it's "ok to start collecting and sending data, or you want to permanently shut me up"?

This has the benefit of giving the option without defaulting to any behaviour, and also filters out one-time users, so the collected data reflects users who would benefit from improvements.

**Comment by firasdib** [comment]
Most of the features are tracked with google analytics.

**Comment by firasdib** [comment]
Issue seems to have gone stale, and seeing as how google analytics tracks everything for me, I'll close this.
