### ISSUE TITLE
Bad superposition of arrows in the quick ref pan

### ISSUE THREAD

**Issue by turlutton** [firasdib/Regex101#653]
In the quick ref panel, when there are too much explanation infos on a token, it appears a scrollbar.
Then, the "go back" arrow superposes itself on the scrollbar.
![capture du 2016-09-27 19 50 42](https://cloud.githubusercontent.com/assets/13371063/18885765/5bfa28f4-84ed-11e6-854b-b09b42ce3b6c.png)
Note: it could be nice to add an explanation tool tip when hovering the mouse on the "go back" arrow

**Comment by firasdib** [comment]
Fixed!
