### ISSUE TITLE
ctrl+a or cmd+a in substitution box selects content of entire page

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#655]
Chrome Version 53.0.2785.116 (64-bit)
OS X 10.11.6 (El Capitan)

1. Add text to the TEST STRING area. A regex is not required.
2. Expand the SUBSTITUTION box and focus somewhere within it.
3. Hit ctrl-a (or cmd-a on Mac) to select all

You should see only the SUBSTITUTION text selected; the rest of the page should not be selected.

http://i.imgur.com/f1sLmGQ.png

**Comment by Zarthus** [comment]
While the clicks are not well shown, the issue on Chrome53/Windows is present but only if you're outside of the existing text area. Selections also remain selected.

https://dl.dropboxusercontent.com/u/55123779/2016-09-27_20-49-33.mp4

**Comment by firasdib** [comment]
I have added a new style showing you when you have selected text and the editor is not active anymore. Does that help with this issue?

**Comment by working-name** [comment]
Hi, still happens on Chrome 53, FF 49.

**Comment by firasdib** [comment]
I don't understand what is happening though. Can someone else please make a video with the latest update I pushed? This will likely make it clearer for me.

**Comment by working-name** [comment]
Sure, [select all behavior - firefox 49](https://bugout.regex.cf/select-all.mp4)

**Comment by OnlineCop** [comment]
@working-name Whatever program you're using that captures the keystroke names and stuff... I want it.

@firasdib: As you can see, you can't select all the substitution replacement text. In the old site, I could select the text down there, cmd-a, copy it, and paste it into my text document.

In the live version, the text area does not take focus, so I cannot cmd-a to get only the text within it: it captures all the text on the page, like I hit cmd-a outside of a text field.

**Comment by working-name** [comment]
@OnlineCop It's ScreenFlow :)

**Comment by firasdib** [comment]
This has been fixed. If you find another issue with it please reopen.
