### ISSUE TITLE
Right side scrollbars hides part of information

### ISSUE THREAD

**Issue by ignas-x** [firasdib/Regex101#657]
After page redesign (which i personally don't like at all, like somewhere hidden flags, and no posiiblility to reposition frame borders/size) -  **right side scrollbars hides part of information**, for example \s \w \d selectors in "Quick reference" frame.

(Windows 7 Pro SP1,  Chrome Version 53.0.2785.116 m, 1920x1080)

![regex_scroll](https://cloud.githubusercontent.com/assets/22024720/18904318/2c3c9c22-8566-11e6-8a20-7dee7edcec56.png)

**Comment by nhahtdh** [comment]
Dup of https://github.com/firasdib/Regex101/issues/555

**Comment by ignas-x** [comment]
Sorry, I searched for 'scrollbar' before posting, but found none. Should I remove it from here or leave ?

**Comment by TWiStErRob** [comment]
@ignas-x You can't delete/hide GitHub issues. only close them (and optionally mark them as duplicate if you repo has a label for it).

**Comment by firasdib** [comment]
Its unfortunate you do not like the new version. What do you mean about "hidden flags"? Previously all you could resize was the right hand sidebar, is that what you're referring to?
