### ISSUE TITLE
Coloration of unwritten area

### ISSUE THREAD

**Issue by NecZdmr** [firasdib/Regex101#658]
Hi, 
Firstly thanks for the nice new version of the site.
There is a difference compared to the past in the test string area.
As I mentioned in the title, unwritten areas are also colored. I do not know if it was done on purpose, But this constitutes a really bad image. While testing written statements It becomes more difficult to understand the result. Is there a possibility to rectify this situation? Or at least the possibility to make an adjustment based on preferences.
Thanks.

![test_string](https://cloud.githubusercontent.com/assets/7038041/18904705/301d2274-8568-11e6-93c7-306c10a2b05c.png)

Necati Özdemir
Natek Bilişim A.Ş

**Comment by TWiStErRob** [comment]
Do you mean "unmatched" by "unwritten"?
I think a saved regex url would help Firas a lot to help diagnose the issue, if there's any.

**Comment by nhahtdh** [comment]
He says it's by design in https://github.com/firasdib/Regex101/issues/596, but I really want a second take on this issue.

**Comment by NecZdmr** [comment]
No, I did not mean it. @TWiStErRob 
As @nhahtdh says, For example, If you look at the picture, text ends with "2016/08/19". But the match to continue in the following line, so It coloring made until the end of the line.

If Its by design. I think it was really bad and This feature should be based on preference.

**Comment by TWiStErRob** [comment]
I would say it's necessary, otherwise you couldn't really see the matches in this one https://regex101.com/r/R03MOf/1

**Comment by NecZdmr** [comment]
Of course it may be necessary for those who need one. But Coloration of the new line can be made by a different method. It was a bit strange but familiar somehow.

**Comment by firasdib** [comment]
What this is trying to do is indicate to the user that the _entire_ line is being matched, including the newline. The old site had no proper way of representing this which could be misleading.

I realise it might look odd at first, but once you know what it means its typically quite useful.

**Comment by nhahtdh** [comment]
@firasdib Of course, we need to document it in the wiki if there is no better solution to show that the match goes across lines.

I'm thinking of displaying whitespace character and highlight up to the whitespace character if the match spans lines, but not sure how hard it would be for you to implement.

**Comment by TWiStErRob** [comment]
@NecZdmr take another look, @firasdib made a change to line highlights. It's still higlighting the end of the line to signify continuation of the match, but there's a little space between lines so they're better distinguished.

**Comment by NecZdmr** [comment]
Yes, this was much better. It looks more elegant. but I think there's a problem out of it. Existing of whitespace characters (tab and space) is not understood at between end of the text and end of the line.
I do not have any idea but perhaps can be found a solution for this situation.

**Comment by TWiStErRob** [comment]
Turn on white spaces in settings.

**Comment by NecZdmr** [comment]
yes! this is really nice. I did not notice this feature. Perhaps it is new. Thanks.
