### ISSUE TITLE
HTML/XML characters comments are shown as escaped in Explanation

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#659]
For example enter regex `/# check Explanations: ' " < > &gt;/x`.

![image](https://cloud.githubusercontent.com/assets/2906988/18905609/4ad295d0-8564-11e6-9fc2-ac4636c83889.png)

Without `x` flag it escapes well:
![image](https://cloud.githubusercontent.com/assets/2906988/18905637/632acd28-8564-11e6-9cce-c1f16a20bff2.png)

**Comment by firasdib** [comment]
Thanks, fixed.

**Comment by maherbo** [comment]
With regexes `["-'<->]` or `[^"-'<->]` ( no matter the flags), the explanations are still double-encoded (when in ranges only):

**Match a single character present in the list below**
`["-'<->]`
`"-'` a single character in the range between `&quot;` **(index 34)** and `&#39;` **(index 39)** (case sensitive)
`<->` a single character in the range between `&lt;` **(index 60)** and `&gt;` **(index 62)** (case sensitive)
