### ISSUE TITLE
Re-add whitespace support

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#661]
From https://github.com/firasdib/Regex101/issues/599#issuecomment-250110963

I sometimes use regex to clean up whitespaces. Here's an incomprehensible one without showing whitespaces: https://regex101.com/r/R03MOf/1

I suggest to add visible white-spaces to at least input string, but much better if replaced string and match information also shows them.

**Comment by firasdib** [comment]
Added!
