### ISSUE TITLE
Remember or set a default language flavor

### ISSUE THREAD

**Issue by sundeepgupta** [firasdib/Regex101#663]
It would be nice not have to switch to the javascript flavor (in my case) each time.

**Comment by TWiStErRob** [comment]
#662 was just opened for this.

**Comment by firasdib** [comment]
Closing this in favor of #662

**Comment by aprilandjan** [comment]
Although this issue is closed long ago, it seems that currently it is still not able to remember selected language flavor. Am I missing something ?

**Comment by firasdib** [comment]
@aprilandjan Change it in the settings and it will be remembered.
