### ISSUE TITLE
Feature request: I want to type in my modifiers

### ISSUE THREAD

**Issue by jay** [firasdib/Regex101#664]
I already know what the modifiers are, my request is the old way where I can type them in. I am not suggesting you get rid of the clickable flag, merely that the text area to the left of it be modifiable so that when I click it I can type them in rather than have the menu appear. Thanks for your consideration.

**Comment by firasdib** [comment]
Have you tried opening the menu (can be opened by tabbing) and then hitting the keys on your keyboard? 😉

**Comment by jay** [comment]
Thanks, sorry for the noise. I do prefer it the old way without the menu, but as long as the typing works it seems like something that would affect few people.

**Comment by OnlineCop** [comment]
We actually considered a typeable area like the previous site used, but we also had to consider mobile/tablet devices and various resizing issues that came with it. When small screens were used, the keyboard would open on an input field, blocking most of the screen and causing various problems. I was also a fan of the "type it in" style, but had to agree that for portability, it had to go.

When you're in the regex field, you COULD paste in something formatted with the delimiters with the flags at the end, and it populates all the intended fields for you: `/ /gmx` would enter a space into the regex portion, but would set `g`, `m` and `x` flags for you. `s/ //gmx` would enter a space into the regex portion, set `gmx` flags, and open the substitution field with nothing in it.

**Comment by TWiStErRob** [comment]
@OnlineCop that's a really nice feature, didn't notice it yet. Is there a way to do the reverse of pasting `s/ //gmx`, that is to copy the regex with modifiers?

**Comment by firasdib** [comment]
@TWiStErRob For that purpose I would use the code generator.
