### ISSUE TITLE
Long list of tests make RUN TESTS button disappear

### ISSUE THREAD

**Issue by mloskot** [firasdib/Regex101#669]
* Windows 10
* Microsoft Edge
* Firefox 49.0.1

Steps:
* Adding tests for a regex
* List of tests in the tests area is getting longer and longer
* At some point, it pushes the RUN TESTS button down so far, that it disappears

Problem:
* No scroll appears

![run-test-button](https://cloud.githubusercontent.com/assets/80741/19005687/2b85f1b4-875c-11e6-8962-3e3749d80e7b.png)

![run-test-button-disappearing](https://cloud.githubusercontent.com/assets/80741/19005691/317f8508-875c-11e6-8244-eaf380c2c03a.png)

![run-test-button-disappeared](https://cloud.githubusercontent.com/assets/80741/19005693/35e0b66c-875c-11e6-8ab0-65b52aa66454.png)

**Comment by firasdib** [comment]
Thanks for the great bug report.

I've pushed a fix for this, sorry for the inconvenience.

**Comment by mloskot** [comment]
@firasdib Thanks for the quick fix
