### ISSUE TITLE
Options $flags for php : the result are displayed in PREG_SET_ORDER no option defined

### ISSUE THREAD

**Issue by Trebly** [firasdib/Regex101#670]
Hi,

This tools is essential quite perfect.
Nevertheless I met today the problem of the combining the alternate and the use of $flags in php.
The result are displayed with PREG_SET_ORDER flag which is not the default. This is the most of case that I met.
When the pattern introduces alternate patterns,  **depending of data structure we can met holes into the index of arrays because the index into each main pattern is the index of the capture into the whole pattern, not into each alternate pattern.**

_I propose for this reason a little enhancement :_ 
1.  display the results using options $flags
2.  display the results using options of $offset parameter

Best regards

Trebly

---

Note 1 : I use such pattern for the first time with four alternate patterns to analyse html (176c. for the pattern). The resulting order is important so the following treatment much more shorter.
So the fourth alternative inherits of array with index 0, 6 and 7. Consequently I have to partially rebuild the array.
I have used alternate solution better than four requests and merging records (arrays) using offset. 

Note 2 : Previously I had analysed successfully html tag pattern with no alternative. I have written the code but not tested on real data only the sample with this test tool. So  I am not completely sure of the results. I foresight, and confident don't planned short test, that the display of the tools was the display of the array (as var_dump) with the option  PREG_SET_ORDER.  **Thanks to confirm quickly this, if possible**

**Comment by firasdib** [comment]
If it would help with any confusion I can add `PREG_SET_ORDER` to the generated code sample to keep it consistent with the UI.

**Comment by firasdib** [comment]
No response, closing.

**Comment by Trebly** [comment]
Hi,
Sorry I had a hardware failure on my computer. To get back a new computer and reinstall everything stopped my work during six weeks. I am trying currently to re initiate all that had been stopped since near 3 month now.  

The option PREG_SET_ORDER ( PREG_PATTERN_ORDER or  PREG_SET_ORDER) for $flags 
and
$offset

Are really a plus to define particularly, with the best fiability, the post treatment of the resulting arrray.

Best regards

Trebly

**Comment by firasdib** [comment]
I'll look into this again.
