### ISSUE TITLE
Greplace mode

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#672]
It would be welcome if the substitution allowed for replacing a grep result.

Consider this: `{\@(\w+) (.*?)}[\s\S]*?|}`, it allows to find all the JavaDoc inline tags. The site highlights them nicely: https://regex101.com/r/fFwyVP/1

Now what if I want to have a list of these (grep) with some set formatting (replace)? There's a way, but it's tedious and might not always be possible: https://regex101.com/r/fFwyVP/3

``` regex
[\s\S]*?{\@(\w+) (.*?)}[\s\S]*?|[\s\S]+$
```

I propose to have some replacement "flags" to allow this behavior easily.

**Comment by firasdib** [comment]
I think the current way the site works is fine, but if you still think this is an issue, please leave a comment.
