### ISSUE TITLE
Show whitespaces in explanation

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#674]
Currently only the new line character is shown out of the many invisible characters:
![image](https://cloud.githubusercontent.com/assets/2906988/19055831/47dd58ae-89c6-11e6-9281-2a42ab44a0dc.png)

https://regex101.com/r/Y4Z3GQ/3

**Comment by firasdib** [comment]
There is no straight forward and performant solution to this that I can think of. I don't want to print non-whitespace chars in the place of whitespace chars because you would no longer be able to copy it. And wrapping each char in a span is going to be quite heavy.

Sorry but no dice.

**Comment by TWiStErRob** [comment]
Good point about copy, thanks.
