### ISSUE TITLE
Explain substitution

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#675]
May be a rare case, but imagine that you find some really advanced regex with some weird looking substitution string: e.g. including named references and case-changing replacements.
In that case (and possibly other cases as well) it would be helpful to have a full description of the replacement similar to the regex's.

**Comment by firasdib** [comment]
I don't think this is worth its own panel like the regex. Hover will explain the items and most of the time they are very basic.

**Comment by TWiStErRob** [comment]
I didn't mean a separate panel, you can just concat it the end of the scrolling explanation.

**Comment by firasdib** [comment]
@TWiStErRob Perhaps, but that might even confuse things further. Most substitution syntax is very clear/obvious - so I'm not sure it warrants this change.

**Comment by TWiStErRob** [comment]
`abc.d` is obvious too, but for someone learning the language, it may not be.
I couldn't find the upper/lowercase transformation in the quickref, but I still think it's a good idea to show that. If you want you can skip explanation when the substitution only contains literals and backrefs.

UI-wise I don't think it would be confusing to have another expandable tree in the same area. You can start it with "substitution/replacement string" to make it more obvious.
