### ISSUE TITLE
RFC/User discussion: TAB key behavior

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#676]
Currently the TAB key behavior is inconsistent and sometimes very confusing. We've talked a little about this with Firas, but we couldn't reach a quick conclusion, so we agreed to ask. I think for the shortcuts to be consistent, the below list should be able to be summarized in two short sentences, which is currently impossible. So here's the breakdown:
- Regex field:
  - **Tab**: opens regex flags (even when text is selected)
  - **Shift-Tab**: nothing (even when text is selected)
- Flags popup:
  - **Tab**: focuses Test string
  - **Shift-Tab**: focuses Regex field
- Test string field:
  - **Tab**: inserts tab character, or indents by 2 spaces when text is selected  
    (leading tabs are replaced by spaces)
  - **Shift-Tab**: opens regex flags (even when text is selected, so no unindent action)
- Substitution field:
  - **Tab**: inserts tab character, or indents by 2 spaces when text is selected  
    (leading tabs are replaced by spaces)
  - **Shift-Tab**: focuses Test string
- Replaced text area:
  - **Tab**: nothing
  - **Shift-Tab**: nothing

Everywhere:
- **Ctrl(+Shift)+Tab**: cycles browser tabs
- **Alt(+Shift)+Tab**: cycles OS windows

I propose to either:
- have the TAB always insert tab character/indent/unindent in ALL fields and steal Ctrl+Tab from the browser to enter the tab character similar to how chat applications enter new line on Shift+Enter.
- have the TAB key always go cycle through fields with tabindex (probably more accessible than previous) and have Ctrl+Tab insert tab character, or Ctrl+Tab and Ctrl+Shift+Tab indent and unindent text when selected.

Some discussion points (with my views):
- **Would you prefer more consistency, or mostly _meh_?**  
  _I do, if you didn't guess ;)_
- **Which is more important: navigation, entering Tab character or indent/unindent**  
  _I would mostly want enter characters and indent, most likely very rarely navigate_
- **Should the fields allow indent/unindent actions at all? Is it ever used?**  
  _Currently the indentation is 2 spaces which also strips leading tabs, in this state I would prefer it to be turned off. If there's an option to set CodeMirror to recognize any type of indentation, that I would prefer most._
- **Is it mean to steal Ctrl+Tab behavior from the browser?**  
  _I think stealing when in a smart text editor component on a page is not an issue, especially since the whole app steals other shortcuts, like Ctrl+S_

**Comment by OnlineCop** [comment]
Good points. I don't think the "indent by two spaces" thing is very convenient, although it's probably something to do with CodeMirror.

Answers on http://ux.stackexchange.com/questions/39868/accessible-way-to-override-tab-key-in-textarea state a few recommendations for this.

Across browsers, TAB will move from one text field to the next (according to the element's tab index) UNLESS it is a textarea. Then, in _most_ (not all) sites, TAB will insert a `\t` character. Across the board, Shift+TAB always focuses one field back (according to the element's tab index), and does not indent or un-indent text.

In theory, if anyone were to lay out a site similar to the fields in regex101, there would be no way to TAB from the regex field down to the substitution field as the test string's textarea would insert literal tab characters into the next, and never allow a normal TAB to blur the field. Also in theory, the only way to reach the substitution field would be to Shift+TAB and cycle backward through all the elements to reach it.

As far as *consistency* goes, _within this site_, navigation using TAB is inconsistent. However, this behavior is very consistent with how _almost all other sites_ operate using TAB and Shift+Tab. I would be in favor of keeping it consistent with how _other sites_ treat TAB navigation. When I am in a textarea and hit TAB, I _expect_ that a literal tab character is inserted into the text. It is very bad if you were to try to override the *Ctrl+Tab* or *Alt+Tab* behavior.

**Comment by firasdib** [comment]
It seems keeping the existing behavior seems like the most sane thing to do. Please reopen if you feel otherwise.

**Comment by TWiStErRob** [comment]
I think these actions that need be done here for better experience without breaking common navigation patterns regarding Ctrl/Alt.

 * disable "smart" indenting in test string and substitution, because replacing leading tabs with spaces on indent is a really bad choice and you likely don't want to have to add indent detection or preferred indent configuration. I say disabling, because there's no unindent action (other than undo). I think even "TAB overwrites selection" is a better thing than forcing an indentation style.
 * allow to move back to substitution via Shift+Tab from replaced text area. It's focusable, but other than arrows, keys don't do anything.
 * potentially allow to cycle back to regular expression with Tab from replaced text area and vice versa. This only applies if replacement is visible.

**Comment by Ouims** [comment]
hello, feedback:

I tested a bit tab and shift tab and everything works 'well' to me, nothing unintuitive, tab always gets you to the next element unless you are in the test string and it gives a real tab, and shift tab goes backward except in the regex area.
Maybe shift + tab, since it's doing nothing in the regex area, could actually result in \t getting added to the current pos? ^_^
Otherwise, i think this can be closed.

**Comment by firasdib** [comment]
Lots of accessibility work has been made where tabbing was included. Give it a spin and open issues for anything you find.

**Comment by qbui-quod** [comment]
Hi, sorry but recently I have not been able use Tab key to indent code in the Test String section anymore. Is this functionality taken away? If so, is there an alternative way to indent code in Test String?

**Comment by ApolloBiz** [comment]
> recently I have not been able use Tab key to indent code in the Test String section anymore.

I'm having the same issue today, 2021-05-26. 
I was trying to build/edit a test data set that needs to be tab-delimited, and I could NOT find a way to enter the TAB character in the test data.

Please re-enable this feature.

Thanks.

**Comment by Ouims** [comment]
There is an actual report about it: https://github.com/firasdib/Regex101/issues/1572
