### ISSUE TITLE
re.A for python codegen

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#677]
Just a reminder to add `re.A` to the python code generator
### Update: something to keep in mind - discussed in #679

Python3 has `re.U` turned on by default and supports unicode characters in files, while Python2.x does not support unicode files by default, and it needs `re.U` flag to consider unicode characters in patterns. 

As a result, if you have any unicode characters in your test string, _regardless of wether they're considered by the regex or not_, Python2.x chokes on it and says this:
`SyntaxError: Non-ASCII character '\xce' in file so-and-so.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Said declaring of encoding must exist on line 1 or 2 of the script file, and it looks like this:

``` py
# coding=utf8
# the above magic tag is for Python2.x compatibility
import re
...
```

That magic tag has no effect on Python3, but it might be worth mentioning why that's there.

**Comment by firasdib** [comment]
Added
