### ISSUE TITLE
unicode in python 2 vs 3

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#679]
@nhahtdh 

Being as you're the resident pro, how should we handle the fact that Python 2 parses stuff in ascii mode, but Python 3 parses stuff in unicode mode? I'm talking about the code generator.

I found that with Python2.7 you can set the encoding mode using this magic tag on line 1 or 2

``` python
# coding=utf8
```

However tag only helps Python 2 parse through the file whether it contains unicode characters or not. It will still require the use of `u` flag to get regex to match unicode characters. I figured that since someone may be using unicode characters in their test string, they'll bump into the parsing error.

Coding tag doesn't affect Python3. 
#### Question 1

Should we help them out or let them figure it out on their own?

**Comment by firasdib** [comment]
I've implemented https://github.com/firasdib/Regex101/issues/677
