### ISSUE TITLE
python flavor - a, ascii flag behavior

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#680]
@nhahtdh tagging you because you're a pro. 👍 

I've been testing this locally in both Python 2.7 and 3, and I'm getting the opposite in terms of what is matching on regex101.com. That being said, Python2.7 has that odd unicode thing and researching online, I've found that if you turn the string and regex into unicode (which I'm guessing has to do with the `encode()` function) it should behave the same as Python 3. 

Python 3 returns the whole test string without any flags (which means re.U is set), and Python 2 would return `α` alone as a match, and as a second match the rest of the test string `alpha`.

[This is the test regex and string.](https://regex101.com/r/d3NwH5/1)

My main concern is that we don't reflect reality in regex101.com's code generator. But also on a personal level, how do you even get python 2.7 to return one match as python3 does? I keep getting errors about python not being able to encode the `α` character. ~~And lastly, isn't `alpha, α` included in ASCII?~~

**Comment by TWiStErRob** [comment]
Alpha char in ASCII? ASCII is 0-127, I don't think it has space for much. Check out these:
http://apps.timwhitlock.info/unicode/inspect?s=alpha%2C+α
https://r12a.github.io/uniview/?charlist=alpha%2C%20α
https://r12a.github.io/apps/conversion/?q=alpha,%20α

**Comment by working-name** [comment]
Cool, thanks.

**Comment by firasdib** [comment]
The code gen is created for version 3, the version 2 notes and comments are there out of courtesy.
