### ISSUE TITLE
UX: Highlight matches on hover of EOL

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#681]
https://regex101.com/r/CrS8hE/1
is it possible to make CodeMirror give you an even when you hover the blue whitespace at the end of the line? It looks a little strange when you hover the `a` or `b` characters and the whitespace is highlighted, but you can't actually hover the mouse over that area to highlight the same match. I think it breaks a visual contract with the user.

**Comment by firasdib** [comment]
That is currently not possible. The extended highlight is meant to show that the entire line is matched (and proceeds to the next). Further discussion here https://github.com/firasdib/Regex101/issues/658

**Comment by TWiStErRob** [comment]
I understand what it shows, here are some images in case we misunderstood each other:
hovering on "a" highlights the match (notice borders around line continuation):
![image](https://cloud.githubusercontent.com/assets/2906988/20463930/140bd710-af3e-11e6-8bd9-ef5a0350718c.png)
hovering on "b" highlights the match (notice borders around line continuation):
![image](https://cloud.githubusercontent.com/assets/2906988/20463933/2c7c2002-af3e-11e6-96a5-4caeb40082e0.png)
hovering on or after the end of line whitespace character shows no highlight:
![image](https://cloud.githubusercontent.com/assets/2906988/20463946/4f871ea8-af3e-11e6-85af-6a9d0e4e85bf.png)

I would expect to move my mouse along the match and it's always showing the highlight and the match popup.
