### ISSUE TITLE
Engine error with recursive pattern loop

### ISSUE THREAD

**Issue by ai4rei** [firasdib/Regex101#683]
**Match information:**
Your expression caused an unhandled error. Please submit all your data (regex, test string, etc) and the following error in a bug report:

recursive call could loop indefinitely - offset: 3

**RegEx:**
`(?R)`

**Comment by Ouims** [comment]
Hello, (?R) means the whole pattern (here "(?R)") is applied at this point, you are indeed creating an 'infinite loop', the behavior is normal

**Comment by firasdib** [comment]
Thanks for the report. I've adjusted this message so users are not always prompted to report it. This specific error I can not handle I'm afraid.
