### ISSUE TITLE
regex101.com Substitution includes unmatched text?

### ISSUE THREAD

**Issue by WritingSolutions2020** [firasdib/Regex101#684]
My apologies in advance if I've misinterpreted the situation, but per the attached PNG screenshot it appears that regex101.com's _Substitution_ panel is including text that is not part of a capture group(?)

![2016-10-07_regex101dotcom-substitutionerror](https://cloud.githubusercontent.com/assets/3333327/19204207/46690b7c-8c90-11e6-8685-8a8ea03a8480.png)

As shown, the _Explanation_  and _Match Information_ areas indicate that four out of five text tokens have been found for capture group one (1). But in typing _$1_ the _Substitution_ area includes not only the matched capture groups but also text that has NOT been matched.

Or is this just me?

**Comment by TWiStErRob** [comment]
I think what you're missing is that substitution is not grep. See #672. In every language I know subst, replaceAll or whatever it is called only replaces the match with the substitution text. You can confirm this by typing `+\1+` in the substitution input box on the website.

**Comment by OnlineCop** [comment]
This is the intended behavior of substitution. Only matched text is affected by a substitution: everything that is not matched is left alone. The contents of the SUBSTITUTION field will show you where matched text is replaced (either by the contents of a captured value, or "nothing" as the case may be), but all other (unmatched) text should not be touched.

If you have the text `ABC123DEF` and wanted to substitute the numbers with "nothing" (removing numbers, in other words), `s/[0-9]+//g` would only match `123` and replace it (with nothing), but leave `ABC` and `DEF` alone, giving `ABCDEF` as the output.
