### ISSUE TITLE
Feature of performance comparison

### ISSUE THREAD

**Issue by greatvovan** [firasdib/Regex101#69]
Is it possible to implement feature of comparing two (or several) RE with relation to performance? More often than not there are more than one variant of regex for some purpose. It's useful to compare several variants and choose fastest. Some information gives debugger (the number of steps) but actual test with timings will be appreciated, imho.

**Comment by firasdib** [comment]
With the coming update you will be able to see how many steps your regex takes to finish processing. You can't compare several regexes, but its a step in the right direction.

**Comment by firasdib** [comment]
V2 will show execution time for a regex, you can open up two tabs and compare the tiems manually.

**Comment by greatvovan** [comment]
Hmm... And where can I find it?

**Comment by firasdib** [comment]
v2 is not yet released, sorry.

**Comment by greatvovan** [comment]
Oh, I just missunderstood...
I'm looking forward for it!
