### ISSUE TITLE
The latest version's code generate tool is worse than the previous!

### ISSUE THREAD

**Issue by JavaCS3** [firasdib/Regex101#691]
I prefer the previous code generate tool which took regex flags into counts;
The code generated by the latest version is real ugly.

**Comment by working-name** [comment]
Hi there, which flavor is not taking flags into account, and which flags specifically?

**Comment by JavaCS3** [comment]
@working-name I use Python code generator which is a little bit complicated. 
After I go through the generated code line by line, I found it's right. Sorry for the wrong read for the first time.
From my view, the old versions code is short and clean. I prefer the old one.

**Comment by firasdib** [comment]
The Python code is obvious and takes flags into account in all languages provided. If you run the code you will quickly see what it outputs. Its nothing fancy.

**Comment by TWiStErRob** [comment]
Just curious @JavaCS3, what would be a a better code than the current?
