### ISSUE TITLE
"\w" operator not working correctly 

### ISSUE THREAD

**Issue by outboundexplorer** [firasdib/Regex101#692]
This is a snippet of text that I am matching against 

```<h1>CSS </h1><h1>Layout</h1>``` 

I am trying to match against the middle ```</h1><h1>```

Originally i tested with

``` /<\/\w*><\w*>/ ``` 

and the software showed that this would work.  However, this seems to be incorrect as perhaps the correct regex should be

``` /<\/[a-z0-9]*><[a-z0-9]*>/ ```

**Comment by TWiStErRob** [comment]
Where does I not work? What is you real execution environment?

**Comment by outboundexplorer** [comment]
This is working with the DOM in javascript

**Comment by firasdib** [comment]
You are using the regex incorrectly. There is no error with the regex testing service.

`\w` = `[a-zA-Z0-9-]`

Try stackoverflow for JS related help.

**Comment by outboundexplorer** [comment]
Appreciated that I might not be using the regex correctly.  But plugged into the regex testing service, they both return the same full match when fed the string that I quoted.  Anyhow, I just felt that if something is wrong, then maybe they shouldn't return the same match.  Either way no worries.  Cheers :)

**Comment by firasdib** [comment]
If you're using the `RegExp` object you need to double escape `\`

**Comment by outboundexplorer** [comment]
Of course.  Thanks :) And there I was thinking I was helping you out.  That's what happens when i get up at 3am :(
