### ISSUE TITLE
a* should BE matched to a\\* RATHER THAN a\*

### ISSUE THREAD

**Issue by peterpandayang** [firasdib/Regex101#693]
a* should BE matched to a\\*  however in the website it is matched to a\*, which is wrong. plz fix this problem.

**Comment by TWiStErRob** [comment]
Not sure what you mean, can you please be more clear about the regex and input you're using?

These are correctly working on the site as I tried (code is regex, quoted is input):
`a*` matches "", "a", "aa", "aaa", ... as many `a`s as you want
`a\*` matches "a\*", but nothing else
`a\\*` matches "a", "a\", "a\\\\", "a\\\\\\", ... as many backslashes as you want

(Make sure you try your comment with preview because * and \\ are special formatting characters.)

**Comment by peterpandayang** [comment]
I don't know if it depends on the language. I use Java and run on my IDE and it is a\\* that could matched to "a*" NOT a\*.

**Comment by peterpandayang** [comment]
I don't know if it depends on the language. I use Java and run on my IDE and it is a\\* that could matched to "a*" NOT a\*

**Comment by peterpandayang** [comment]
I don't know if it depends on the language. I use Java and run on my IDE and it is "a\\*" that could matched to "a*"   while "a\*" CANNOT be matched to "a*"

**Comment by TWiStErRob** [comment]
Ah, I see. Java needs unintuitive (at first) double escaping. Try to test out your regex on the website and then use he code generator on the left to see what actual `String` you need to put in your code.

**Comment by peterpandayang** [comment]
Yes, that is exactly what I mean. Please just look at the title rather than the comments because there is backslash missing in the comments.(github automatically delete?)

**Comment by TWiStErRob** [comment]
*GitHub also needs escaping, to write \\ in plain text you need to type \\\\. Also to write a star you need to type \\*.*

For me it seems to generate the correct code: I typed `a* a\* a\\*` in regex input and the code is:
```java
String regex = "a* a\\* a\\\\*";
```

Did you select the Java language to generate code, or you're looking at PHP?
```php
$re = '/a* a\* a\\\\*/';
```
@firasdib, is that single backslash correct in PHP?

**Comment by peterpandayang** [comment]
Oh, I see the problem now. Thank you!

**Comment by firasdib** [comment]
@TWiStErRob yes it is

Is there an issue here that I don't see?

**Comment by TWiStErRob** [comment]
I think the problem was that Peter was trying to copy the PHP-string into Java source code.

**Comment by firasdib** [comment]
Closing. If there is an issue, feel free to reopen.
