### ISSUE TITLE
Unit Tests: a failed test is not an "error"

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#695]
![img](http://i.imgur.com/tWd8MUb.png)

Error makes it sound like Regex101 encountered an error while running the test. I'd say "Test Failed (because):"

**Comment by TWiStErRob** [comment]
Agreed! In testing discipline it's important to distinguish between failure and error:
 * **failure** means that either the test (input/expectation) or the test subject (regex) is incorrect,
 * **error** means that the execution environment (or maybe the test) is broken and the result of the test execution is inconclusive.

**Comment by firasdib** [comment]
I do not distinguish between "errors" and "failures" in the code - they are the same. Perhaps I could just remove the `Error:` and make the entire message bold instead to make it stand out to the user, regardless.

**Comment by firasdib** [comment]
I've removed the `Error:` label for now. Lets see how this works out. If you still feel there is an issue, please reopen.
