### ISSUE TITLE
Unit Tests: setting to have the tests expanded by default, rather than manually click on them.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#696]
I like verbose information, having the unit test test's automatically expand by default would be a nice quality of life feature.

**Comment by TWiStErRob** [comment]
If a test passed, why do you need to see "why" it passed?

**Comment by firasdib** [comment]
There is a button to expand/collapse all entries

**Comment by Zarthus** [comment]
I'd like them to be expanded by default (with a setting), and it's good to see (someone elses, specifically) test information as to what has already been tested and what still could be tested.

The expanding of all button is definitely nice but I had no idea it was there, it's not very obvious and could be made more obvious.

I still think as a standalone suggestion it's a nice thing to offer more settings, but as far as priorities go it's very low.

**Comment by firasdib** [comment]
I don't see the need to automatically expand tests. I can see cases where it would be nice, and others where it would just be annoying. The buttons should satisfy both cases.
