### ISSUE TITLE
Denote when there is trailing whitespace at the end of a regular expression.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#697]
Sometimes you accidentally add a space at the end of your regex (either from copypaste or otherwise.)

Regex101 does a poor job at showing this, and if this were made clearer perhaps less people would scratch their head as of why a regex does not match.

for VIM, I have something like this (which will not apply, but might help make my point clearer):

![img](http://i.imgur.com/nEKh4Oi.png)

note: There's already an option for showing whitespace, but that's for everywhere. I specifically want it when there's trailing whitespace for it to always be shown, since 99/100 cases it is a mistake.

**Comment by OnlineCop** [comment]
That's why I usually show all the hidden characters from settings (the wrench menu in the top-right). It shows the spaces and newline characters so I can see when I have anything trailing.

**Comment by TWiStErRob** [comment]
@onlinecop did you see the note at the end?

**Comment by Zarthus** [comment]
The problem with that setting is that it is not enabled by default. Regex101 can detect when the user is probably making a mistake very well in some scenarios. I think it's the UIs job to help the user find them where it can (in a default-enabled setting).

**Comment by OnlineCop** [comment]
Ah; I did not see the note at the end. Re-opening for another pair of eyes. Would the paste simply need a `.trim()` kind of functionality to simply remove leading/trailing newlines and spaces?

**Comment by Zarthus** [comment]
No, because sometimes trailing whitespace is wanted.

Bad example:

```
PING PONG
```

When capturing just `PING` you open up the false positive of matching with

```
PINGPONG
```

(\b can be used, but sometimes is not applicable.)

I think just something to denote it as "hey, there's whitespace here, but you can't see it unless you click on it" will help a lot.

**Comment by TWiStErRob** [comment]
So you it sounds like what you want is an option to toggle leading/mid/trailing whitespaces separately with trailing on by default.

**Comment by Zarthus** [comment]
Just trailing is important here. Leading is easy to spot in a regex, and so is mid whitespace. It's just trailing that is essentially invisible and WILL mess up your regex if you accidentally include it. It's not a rare occurrence for it to happen, and providing that bit of extra visual feedback to show characters you otherwise would not be able to spot without explicitly selecting it is cumbersome and often forgotten or missed.

**Comment by Ouims** [comment]
Agreed, something to toggle the option for non-printable char with the keyboard would solve your problem though, rather than having something specific for trailing spaces.

**Comment by firasdib** [comment]
Its impossible to know when the user means to leave a trailing whitespace and when they don't. I think the whitespace option is the right way to go, and it should not be enabled by default. This seems to be standard behavior os almost all text editors I have worked with.
