### ISSUE TITLE
Duplicate entry of \0 in Python, Golang and PCRE PHP.

### ISSUE THREAD

**Issue by MitalAshok** [firasdib/Regex101#698]
It says that `\0` is both "complete match contents" and "null character".

[![A picture of `\0` being listed twice in the search results](https://cloud.githubusercontent.com/assets/21043110/19416779/38d8f776-9391-11e6-9d32-55a02a46c93e.png "Duplicate `\0` in search results")](https://cloud.githubusercontent.com/assets/21043110/19416779/38d8f776-9391-11e6-9d32-55a02a46c93e.png)

As you can tell from the screenshot, one is a substitution and the other a token in the pattern.

The problem is that it hard to tell the difference. `\0` do not mean null character in substitution, but does not mean complete match contents in the pattern.

For `\1`, it means "contents in capture group 1" both when substituting and in the pattern, but it only lists it in substitution. (At least in Python, `(a)\1` matches `'aa'`, but not `'a'`)

The problem is that substitutions aren't clearly identified. Maybe list them second after a `<hr>` or a different colour?

**Comment by TWiStErRob** [comment]
If you look at the found categories you see "general tokens" and "substitution". If you click each you'll see that `\0` can only mean "null character" when used as a "general token" in the regex.

Notice that `\0` is only said to be valid in the substitution string to mean "complete match contents"; in a regex pattern it doesn't even make sense, because there's no "complete match" **yet** during the regex execution.

**Comment by MitalAshok** [comment]
@TWiStErRob Well, then it might be a UI issue where it's hard to tell what it means. There might not be an easy way to fix this. Original has been edited in response.

**Comment by firasdib** [comment]
I see where you're coming from, but I'm not convinced that would actually do anything to clear the situation up. Adding the category to each line would greatly reduce the space we have to work with, which is already limited. Cases where this happens are quite low, and will be even lower once https://github.com/firasdib/Regex101/issues/578 is implemented it will be even less.
