### ISSUE TITLE
Feature request: Keyboard shortcut for syntax hilighting

### ISSUE THREAD

**Issue by natcl** [firasdib/Regex101#699]
With long regex, syntax hilighting can sometimes become confusing, I know we can diable it in settings but it would be nice to have a keyboard shortcut to toggle it on and off !

Thanks !

**Comment by Zarthus** [comment]
Keyboard shortcuts for most settings would be desirable. I'd wager.

**Comment by firasdib** [comment]
What would be a reasonable keyboard shortcut for this?

**Comment by firasdib** [comment]
Now tracked in #1088
