### ISSUE TITLE
<span className="group-1">aaaa</span> - not reflected

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#701]
@firasdib Is this still something we're implementing? 

In example: ( ... ), sometimes explanations require the use of capture groups, on top of matching. 

I just realized all span tags are just treated equally in the quickref.

Thank you

**Comment by firasdib** [comment]
Currently they are all the same, yes. Poke me on slack and we can try to figure something out.

**Comment by firasdib** [comment]
Is this still relevant?

**Comment by working-name** [comment]
It is if you still think making the explanation look pretty is worthwhile. There are examples where capture groups are used but right now they look like any other match.

**Comment by firasdib** [comment]
Is this still an issue? I think not.

**Comment by TWiStErRob** [comment]
Sounds like in
![image](https://user-images.githubusercontent.com/2906988/50400045-9b563200-077b-11e9-9540-2488a6c952d4.png)
the colors in quick ref don't match the reality (note it's not `(he+)`:
![image](https://user-images.githubusercontent.com/2906988/50400061-c17bd200-077b-11e9-80ce-8485f22b0b33.png)
although I don't know how the JSON definition of quick-ref looks like and how it is built.

**Comment by firasdib** [comment]
Its going to be a lot of work to update the quickref for all these cases. 

I’ll take a closer look tonight. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by working-name** [comment]
if you want a specific data attribute or class on those, let me know, I'm willing to go through the quicker and update. Some cases can be automated but others not so much.

**Comment by firasdib** [comment]
Sorry, my bad! I've adjusted this. There are now match colors in the quickref.

**Comment by TWiStErRob** [comment]
Assuming this is not published yet?

**Comment by firasdib** [comment]
Not yet. 

In a few weeks with everything else thats going on. 


Vänliga hälsningar / Best regards,

Firas Dib
