### ISSUE TITLE
Add Python delimiters

### ISSUE THREAD

**Issue by maikelsteneker** [firasdib/Regex101#702]
Right now, for Python regexes, we can choose to choose ' or " delimiters. When using a regex like `('|")`, we need to escape one of these quotes. However, in Python, we can also use ''' or """ delimiters, which allows us to escape neither.

It would be nice to support this in Regex101.

**Comment by TWiStErRob** [comment]
Do you have a link to docs? as far as I know to support this the code generator has to know what to escape inside those quotes.

**Comment by maikelsteneker** [comment]
Strings are defined in https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals. The `longstring` literal is what I'm talking about here.

As for what to escape: only sequences of three quotes matching the delimiters should be escaped. So `'''"""'''` will work just fine (it is equal to '\"\"\"'), as will `"""'''"""`.

If you can tell me specifically what kind of documentation you're looking for, I'll be happy to look for it.

**Comment by TWiStErRob** [comment]
@firasdib will ask if he needs more, I'm just triaging (and curious). If I read this correctly:
> In triple-quoted literals, unescaped newlines and quotes are allowed (and are retained), except that three unescaped quotes in a row terminate the literal. (A “quote” is the character used to open the literal, i.e. either ' or ".)

all these are equivalent and will have 3 quotes at runtime:
* `'"""'` (quotes between apos)
* `"\"\"\""` (escaped quote delimiters)
* `'''"""'''` (quotes between triple apos)
* `"""\"\"\""""` (escaped triple-quote delimiters)
* `""""\"""""` (escaped only one of the quotes to prevent a false triple quote in the middle of the string)

**Comment by maikelsteneker** [comment]
I believe you're almost entirely correct, with the exception of your last example. The literal `""""\"""""` will result in a syntax error, since there is some ambiguity in how the quotes should be interpreted. If we leave off the last `"`, we end up with `'""'`, but with the string as it is it could mean both what you intend to write down, and the string `'""'` followed by a quote that opens another string.

However, `"""\""\""""`would work fine again. Any string where the quote characters are not adjacent to the delimiters (such as `"""hello\"""world"""`) is fine as well.

Welcome to the wondrous and slightly confusing world of Python strings ;)

**Comment by firasdib** [comment]
Added!

**Comment by maikelsteneker** [comment]
Great! It seems to work very well!
