### ISSUE TITLE
Unexpected \U behaviour for JS 

### ISSUE THREAD

**Issue by hpeinar** [firasdib/Regex101#706]
Test case: https://regex101.com/r/9Xu4ST/1

Site result after replace: `fooBar`
Actual JS result (with code generator code) both in newest Chrome and with node v6.9.1: `foo\Ubar`

Issue:
[Javascript RegExp does not support \U ](https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions)

**Comment by TWiStErRob** [comment]
It was explicitly implemented in #317. Though, I agree it is misleading, and there should be a warning or toggle to make this more clear.

**Comment by firasdib** [comment]
This is the same as https://github.com/firasdib/Regex101/issues/648 (although that only mentions backrefs, its related to the way I've implemented it).

I will have to do a proper implementation for each flavor soon.
