### ISSUE TITLE
All quantifiers broken, "The preceding token is not quantifiable"

### ISSUE THREAD

**Issue by JosephShering** [firasdib/Regex101#709]
It doesn't seem to matter what language I use, all quantifiers are currently broken.

I was testing against this string: 127.133.215.21/33

I tried this list of regexs:
\d{3,}
\d+
\d?
\w+
\w?

No quantifiers work. I just keep getting this error: 'The preceding token is not quantifiable'

Running on Chrome and Mac OS X.

**Comment by TWiStErRob** [comment]
@firasdib knows about it and working on as soon as he can.

**Comment by firasdib** [comment]
Fixed
