### ISSUE TITLE
c# code generation: bad substitution string

### ISSUE THREAD

**Issue by MarcoMengoli** [firasdib/Regex101#711]
Generating the C# code to substitute a pattern with the capturing group 1 using \1, it will compile:

`string substitution = @"\1;";`

which actually doesn't substitute the matching text with the capturing group 1, but with \1;

Using `$1` instead `\1`, everything works fine.

I think it would be nice to substitute automatically the `\1` with `$1` when generating C# code.

I allegate an example:

Text is:

```
my first line**
second line**
3rd**
last line**
```

Output wanted:

```
my first line;
second line;
3rd;
last line;
```

Code generated with `\1;` :

```
string pattern = @"([^*]+)(?:\*)+";
string substitution = @"\1;";
```

Code generated with `$1;` :

```
string pattern = @"([^*]+)(?:\*)+";
string substitution = @"$1;";
```

Output with `\1` (tested on Visual Studio 2015):
`\1;\1;\1;\1;`

Output with `$1`:

```
my first line;
second line;
3rd;
last line;
```

**Comment by TWiStErRob** [comment]
@MarcoMengoli What if someone really wants the output to be `\1`: say I wanted to have this exact output: `\1;\1;\1;\1;`. If the site supported what you're looking for there would be no way to do that.

A potentially better fix would be support only the replacements that the flavor supports (or at least be able to toggle that, with defaulting to flavor restrictions).

**Comment by MarcoMengoli** [comment]
You're absolutely right, I had not considered that case.
It's not a dramatic thing what I have suggested, but it took some minutes to me to understand what was happening. If in the main screen the substitution worked fine, why not in vs? Of corse because the regex engine is different from the php/js/go/Python. My fault

**Comment by TWiStErRob** [comment]
Ah, true that. I totally forgot C# is not a flavor, just generated code yet.

**Comment by Zarthus** [comment]
A friendly warning would probably be best here. "Hey, it looks like you are trying to substitute \1. In C#, you can only do this with $1"

**Comment by firasdib** [comment]
The website only supports a fixed set of languages, the languages in the code generator are just there to help the user. There is a disclaimer about this. In this particular case, I could create something to sanitise the replacement string, but I'm not convinced its worth it, since the site does not officially support the language.

I'm closing this for now, but might reopen in the future if this turns out to be problematic for more users.
