### ISSUE TITLE
Users give the deletion link - needs to be hidden by default in some way or made less tempting to share.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#714]
Users, when asking for support, have a tendency to share the deletion link by mistake. It's a pretty high ratio (we get about 3-4 per week, IIRC) -- the behaviour should be improved in one way or another.

**Comment by TWiStErRob** [comment]
Some ideas:
 * make normal link "green", currently the red kind of calls out for "click/copy" me  
(when people may be lazy to read "delete link" above)
 * hide delete link behind an expandable thingy (e.g. `<details><summary>`)  
so it's less likely that they copy it
 * increase the distance between the two links

**Comment by firasdib** [comment]
Is this still an issue? Are you seeing the same frequency on IRC? I'm quite reluctant to changing it, it would seem a very small percentage is actually sharing this link.

**Comment by Zarthus** [comment]
```
2016-10-28 15:43:20     re101-bobcat-908        https://regex101.com/delete/
2016-10-30 13:17:50     re101-iguana-642        Hello! I want to do this regex in reverse or, ideally to remove every line above boo https://regex101.com/delet /
2016-10-31 21:43:22     re101-ferret-276        https://regex101.com/delete/
2016-10-31 21:48:44     re101-ferret-276        https://regex101.com/delete/
2016-11-07 22:25:33     re101-robin-904 https://regex101.com/delete/
2016-11-11 13:13:27     re101-mole-996  https://regex101.com/delete/
```

i'd say yes, still twice a week at least.

Why the reluctance to change? not showing it by default is a good way to go about this, and you can't tell the number of people that do it not on IRC but at work or somewhere else.

**Comment by firasdib** [comment]
@Zarthus Because the link is supposed to be saved, just not shared, in case you want to delete it in the future.

**Comment by firasdib** [comment]
How does this look?

![nov-17-2016 11-31-12](https://cloud.githubusercontent.com/assets/1335165/20385855/6d6c019a-acb9-11e6-89ae-5b58a959546b.gif)

**Comment by TWiStErRob** [comment]
I like it, how about also stating something like "do not share this unless you want others to be able to delete it" in the bottom-most red paragraph?

**Comment by firasdib** [comment]
I think this is good enough now.
