### ISSUE TITLE
undo should undo flag changes ( ie. turning on multiline flag )

### ISSUE THREAD

**Issue by firatsarlar** [firasdib/Regex101#715]

**Comment by firasdib** [comment]
That would basically mean I'd have to implement an undo stack for the menu which I don't believe is worth the work.

**Comment by firatsarlar** [comment]
I'm so sorry. I thought there is an undo feature. But it was browser's ( inputbox ) undo - redo feature, confused me. ( On chrome, if you click cmd Z it undoes last things I write )
