### ISSUE TITLE
REQUEST:  Please Keep the Existing RegEx setup When we Sign In

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#717]
Often I setup and test a RegEx, and then decided I want to save it under my Account.
Can you please retain the existing RegEx setup when we log in?

Thanks.

**Comment by firasdib** [comment]
As it stands right now this is not possible I'm afraid. The site needs to be reloaded.

**Comment by TWiStErRob** [comment]
As a workaround:
 * save it (save delete link)
 * log in
 * open it (from saved link)
 * fork it into your profile
 * delete original

@firasdib is it not possible to keep the currently opened (saved) regex when logging in?
