### ISSUE TITLE
Group names are null in JSON export

### ISSUE THREAD

**Issue by Actine** [firasdib/Regex101#719]
Hi! First of all, loving the web app, super useful!

When trying to parse input with named groups (PCRE), I noticed that in JSON export, `groupName` fields are all `null`. I believe this is a bug, please take a look.

[Link to saved regex and text](https://regex101.com/r/8YHymZ/1)

Thanks!

**Comment by TWiStErRob** [comment]
Agreed, it looks like a bug.

Btw, your regex timed out after 4 seconds in Android Chrome.

**Comment by Actine** [comment]
Yeah, the regex is not the most optimal one (although on my PC Chrome it took <40 ms). I just needed to quickly parse the midterm tests I'm going to review from my students :)

Thanks!

**Comment by firasdib** [comment]
Thanks. This has now been fixed.
