### ISSUE TITLE
handle the "m@pattern@" syntax of Perl

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#720]
It's a perl thing, but supported by PCRE.
if 'm' is there, any non-alphanumeric, non whitespace character can be used as a delimiter.
I would like to see that, if at any given time the regular expression we enter (pasting or not) matches /^m([^[:alnum:]\s]).*\1$/, then \1 becomes the new delimiter.

**Comment by Ouims** [comment]
It's just very convenient as a syntax, some of my regex use that.
You're not even allowing us to choose any delimiter, meaning that if a pattern is currently using a delimiter you're not allowing, it's a huge pain in the ass to test the regex.
Again it's a PCRE thing, you should definitely support it.
It's not confusing at all, most users do not know about it and these users won't ever enter a pattern starting with 'm' when the following character is also at the end with valid modifier etc, or this scenario is very unlikely to happen, in which case we'd explain them what's going on.
I don't see how it's non trivial regarding the find of unescaped delimiter, that part doesn't change, you look for unescaped delimiter the exact same way as before...
The existing delimiter will be enough 99,9% of time for sure but... is this how it works? If so then please remove support for \K, it's rarely used and we can actually do without it in 100% of cases.
If this argument is non sense, yours is as well. If you are supporting pcre, you should support that.
And it's that kind of little things which makes regex101 the best!!

**Comment by TWiStErRob** [comment]
Reopening as a reminder for @firasdib to re-consider.

**Comment by firasdib** [comment]
No.
