### ISSUE TITLE
Jump to match

### ISSUE THREAD

**Issue by ldorigo** [firasdib/Regex101#721]
Hi.

It would be very nice to have the possibility to jump directly to a match by clicking on it - when testing on very long texts it can be really frustrating to scroll trying to find the match.

Keep up the awesome work :-)

**Comment by zachary-kaelan** [comment]
When clicking on a Match, like "Match 24", have the Test String box scroll down to where that match is.

**Comment by firasdib** [comment]
This has been implemented.
