### ISSUE TITLE
Can't sign in using any provider (handshake error)

### ISSUE THREAD

**Issue by dsifford** [firasdib/Regex101#722]
I've been getting this same error for weeks now. Sorry for the delay in reporting.

### How to reproduce
1. Attempt to sign in using any provider.
2. Next screen that loads will show the following message

```
error=Grant%3A%20missing%20session%20or%20misconfigured%20provider
```

### Browser Details

```

Google Chrome	56.0.2906.0 (Official Build) dev (64-bit)
Revision	8d817067131214a7c5ea66b95b9aaa30f41f773f-refs/heads/master@{#428890}
OS	Linux 
JavaScript	V8 5.6.184
Flash	23.0.0.207
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2906.0 Safari/537.36
Command Line	/opt/google/chrome-unstable/google-chrome-unstable --user-data-dir=/home/dsifford/.config/google-chrome-unstable --flag-switches-begin --enable-devtools-experiments --flag-switches-end
```

**Comment by firasdib** [comment]
Seems to work fine for me. Maybe try clearing your cache, there was an old redirect that I used that was bad that might have been cached.

**Comment by dsifford** [comment]
Tried dumping cache, disabling all browser extensions, and incognito mode. Still same result. Not sure what else to do or try at this point.

**Comment by dsifford** [comment]
Also explicitly cleared session and local storage to no avail

**Comment by TWiStErRob** [comment]
In Chrome Developer tools here's how a successful login looks like (Network tab, Preserve log):
 * Regex101 > Sign In > select Google
 * GET https://regex101.com/connect/google 302
 * GET https://accounts.google.com/o/oauth2/auth 302
 * GET https://accounts.google.com/AccountChooser 200
 * Google Chooser shown
 * POST https://accounts.google.com/AccountChooser 302
 * GET https://accounts.google.com/o/oauth2/auth 302
 * GET https://regex101.com/connect/google/callback 302
 * GET https://regex101.com/login/google?access_token 302
 * GET https://regex101.com/ 200
 * Signed in

How far do you get in this process?

**Comment by dsifford** [comment]
I have no idea what I just did but now it worked.

First try that I attempted to get the data that @TWiStErRob requested failed (error in console pointed at [ublock origin extension](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) so I disabled that. Tried again and it worked just fine. AHA! Has to be ublock origin then, right? Nope, enabled the extension and tried again and it still worked... So no idea.

Oh well. I suppose we can call this one resolved!

**Comment by firasdib** [comment]
I used a 301 redirect when I launched the site, which tells the browser it can cache the redirect. This was incorrect, and since I changed it to 302. That means people who used the site as it was released got the cached version, but that doesn't affect many users luckily.

**Comment by TWiStErRob** [comment]
@dsifford maybe the "Disable cache" option was enabled, so you just needed to make the request with the Network tab open to clear the cached 301... intermittent errors are "the best".

Now we have this documented, and hopefully if anyone has problems, they will find this.

**Comment by dsifford** [comment]
@TWiStErRob Yep, you're exactly right. I do have Disable cache enabled. Good call! Thanks gents 👍 

Also, thanks for your work on the site overall. Can't tell you how many times it's saved my ass. And adding the new golang flavor = 💯
