### ISSUE TITLE
VBScript flavor

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#723]

**Comment by OnlineCop** [comment]
For Code Generator, or as another regex flavor?

**Comment by chrisjj** [comment]
Another regex flavour. Which unfortunately is [not well documented](https://archive.is/vGXp5) .

**Comment by TWiStErRob** [comment]
Basic syntax is pretty normal: https://msdn.microsoft.com/en-us/library/1400241x(v=vs.84).aspx
The replacement string is usually not documented, but most languages support the `$n` syntax, Ansgar's answer pretty much documents those: http://stackoverflow.com/a/40438909/253468

I think using JavaScript flavor is a pretty safe bet for coding regex against (J|VB)Script.

**Comment by chrisjj** [comment]
> The replacement string is usually not documented ... Ansgar's answer pretty much documents those: http://stackoverflow.com/a/40438909/253468

Pretty much? Or completely?

**Comment by TWiStErRob** [comment]
Pretty much. I think that is as good as it gets unless you reach out to MS for a [language spec](http://stackoverflow.com/questions/40426065/why-does-my-vbscript-regexp-replace-unexpectedly-fail-when-replacement-contains/40438909#comment68176504_40438909).

http://regular-expressions.mobi/vbscript.html has the same info.

Btw, as far as I know regex101 supports all types of replacement syntax at once, regardless of selected flavor, so when doing replacement you may get different behavior than generated code. e.g. #711

**Comment by chrisjj** [comment]
> Btw, as far as I know regex101 supports all types of replacement syntax at once, regardless of selected flavor, so when doing replacement you may get different behavior than generated code. e.g. #711

Wow. Thanks for the warning.

**Comment by firasdib** [comment]
Does anyone actually still use VBscript 😄 ?

**Comment by chrisjj** [comment]
Unfortunately some have to... until they can afford the time to port out of that muddle.

**Comment by TWiStErRob** [comment]
You can use it to script Windows/Microsoft Office objects. For example open an Word file and save it as PDF, or modify registry entries during an installation/setup process. Essentially automation for Windows or macro-like programs that work on any/multiple Office documents. simultaneously. The alternative to these is to write C++ or .NET code with all the weird linking, compiling and IDEs that you need; for those cases it's much easier to fire up Notepad and write code that can be run on any Windows system without installing extra programs.

**Comment by chrisjj** [comment]
>  code that can be run on any Windows system without installing extra programs

Windows 95 excepted :)

**Comment by TWiStErRob** [comment]
Heh, so you're saying it works on Windows 3.11 and 1.0?
Btw, do you have any current Windows 95 users among your company/friends/family?

**Comment by chrisjj** [comment]
> Heh, so you're saying it works on Windows 3.11 and 1.0?

No... :)

> Btw, do you have any current Windows 95 users among your company/friends/family?

None that have confessed :)

**Comment by firasdib** [comment]
I don't think this is worth it. Reopen if you feel otherwise.
