### ISSUE TITLE
Export result button hides under scroll on Mac OS X

### ISSUE THREAD

**Issue by wow-apps** [firasdib/Regex101#724]
On Mac OS X difficult to click export result button, cuz half of it hides by scrollbar.

Screenshot: http://prntscr.com/d5fvgr

**Comment by firasdib** [comment]
The scrollbar should autohide so the button should be clickable after a few seconds. This is nothing I can really adjust for (in any sane manner) since scrollbars in OSX are zero-width and not accounted for in the browser.

**Comment by wow-apps** [comment]
I doesn't hiding on this block!

**Comment by firasdib** [comment]
Sounds weird. It works fine for me on OSX.

**Comment by wow-apps** [comment]
Browser: Google Chrome 54.0.2840.71 (64-bit)
OS: MacOS Sierra 10.12.1 (16B2555)

**Comment by firasdib** [comment]
Exact same setup for me 😕

**Comment by wow-apps** [comment]
I talk about not all page scrollbar, but just of this block with result

http://prntscr.com/d5fxy3

**Comment by wow-apps** [comment]
I suggest to set a little margin-right for this button...

**Comment by wow-apps** [comment]
In Safari autohide is working well, but not in Chrome
