### ISSUE TITLE
Request:  Please Improve Account Page UI / Layout

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#725]
Hi,

I love your tool, but, to be blunt, the layout of the Account Page is very user un-friendly.
The list of my RegEx Saved Expressions provides very , very, little information for us to use in finding/selecting a specific RegEx.

I have to open EVERY RegEx to learn what it is about.

Screen Shot of Account Page

![image](https://cloud.githubusercontent.com/assets/11052885/20287124/456283e8-aa90-11e6-8c51-ef4889efa02b.png)

### Three Changes Please:

1. Allow us to enter Title, Description, and Tags, just like when we save to the Library, when we only save the RegEx.
2. When on the Account Page, use/show the same form for searching and listing RegEx as you use in the Library search.
3. Restore the "Tags" feature, where we can enter tags for every save, but personal and Library.

Screen Shot of Library Search

![image](https://cloud.githubusercontent.com/assets/11052885/20287268/1aa3abae-aa91-11e6-8ca0-f6410ad6549f.png)

Thanks.

**Comment by firasdib** [comment]
1. You can add a title in the same place where you add tags. Try clicking the edit-icon.
2. What would you search for, though? The only searchable text would be the title - the tags already have a far superior method for searching.
3. See 1.

**Comment by JMichaelTX** [comment]
> You can add a title in the same place where you add tags. Try clicking the edit-icon.

I don't see the edit-icon.  How do I add Title and Tags when I first save a regex (not to the library)?

Here is the window I see:

![image](https://cloud.githubusercontent.com/assets/11052885/20317443/ae78174e-ab2b-11e6-89aa-75f8a002743b.png)

**Comment by firasdib** [comment]
You are right, there is no way to do it from the save window. It can only be done from the account page as it stands right now.

**Comment by firasdib** [comment]
Done
