### ISSUE TITLE
Library Search Issue with Multiple Words

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#726]
When I search the Library using just one word in the Search block, it works:

![image](https://cloud.githubusercontent.com/assets/11052885/20287981/a71e4ffe-aa95-11e6-93c7-a3df82c334ce.png)

BUT, when I add another word, which IS in the Title, the Search fails:

![image](https://cloud.githubusercontent.com/assets/11052885/20288037/1d6f4e42-aa96-11e6-92ff-0adfddf32dd3.png)

Am I doing something wrong (this is typical search syntax), or is this a bug?

**Comment by firasdib** [comment]
That depends, the current method looks for the entire string, not substrings of it. I'm not sure what the default/standard behavior is.

**Comment by JMichaelTX** [comment]
Most search engines I have ever used search for the words, using either a logical "AND" or a "OR" combination.  The words are NOT treated as a string, unless they are in quotes.
The search as it is is very limited.

**Comment by TWiStErRob** [comment]
I second that.

**Comment by firasdib** [comment]
Okay. The current solution is quite naive in that regard then.

How would it be made any better?

Something like: `title LIKE '%word1%' AND title LIKE '%word2%'`?

**Comment by JMichaelTX** [comment]
> Something like: title LIKE '%word1%' AND title LIKE '%word2%'?

It doesn't need to be that complicated.  Just combine the words in the search block with a logical "AND" unless the user puts the words in quotes:

For Example:
`mac ethernet cable`

would be processed as:
`"mac" AND "ethernet" AND "cable"`

I would have very happy to start with a change the Search like the above, which would search BOTH Title and Description.  I'm all for keeping it simple for both the user and the programmer. 😄 

After you release that enhancement, later you could add:

User Types:
`word1 OR word2`
would search for EITHER word.

User Types:
`title:word1 word2`
would search for:
`(title contains "word1") && ((title contains "word2") || (description contains "word2"))`

where:
"&&" is logical AND
"||" is logical OR

The syntax of `fieldName:value` is used in many search engines, and one that I think most users would find intuitive.

But please, just keep it very simple to start with, so that we will have a much more useful search engine soon.  

Thanks.

**Comment by TWiStErRob** [comment]
> It doesn't need to be that complicated.  
> "mac" AND "ethernet" AND "cable"

Yes it does, because he has to implement it somehow. What you wrote might be available in a higher level language, but it seems these queries go straight to SQL.

@firasdib http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html#c7087

**Comment by firasdib** [comment]
I have added a naive fulltext search now instead, which should operate more like you wanted it to. It does not support any boolean searches (even though mysql does support this) because the input need to be sanitised in a non-trivial manner.

The results are not weighted in any particular order, meaning a match found in the title weights in just as much as the description and vice versa.

**Comment by JMichaelTX** [comment]
> I have added a naive fulltext search now instead, which should operate more like you wanted it to. I

OK, many thanks for such a quick response and change!  👍 

However, it appears that the search does a logical OR of the words typed, which actually works against most of my searches.  I was expecting (hoping) that the more words I typed, the fewer regex library items would be found.

Any chance of you changing the search to use a logical AND between the words?

**Comment by firasdib** [comment]
If you want that, I will have to remove all non-word characters with spaces. That would in turn not always work as expected, since `foo/bar` will become `foo` and `bar`, both being required. I can't see a trivial way of accomplishing this, at least not without side effects. However this might be worth the benefits.

@TWiStErRob Thoughts?

**Comment by JMichaelTX** [comment]
> If you want that, I will have to remove all non-word characters with spaces. That would in turn not always work as expected, since foo/bar will become foo and bar, both being required. I can't see a trivial way of accomplishing this, at least not without side effects.

What about putting the search term in quotes, like `"foo/bar"`.
Would that make your implementation any easier, or not too hard?  😃 

Is this a flag you could easily toggle?  I can see different users wanting different behavior.
If so, maybe a setting in "Application Settings"?

Many thanks for being open to discussion.

**Comment by firasdib** [comment]
I have added an option to sort the search results by relevance and made the search a bit "smarter". Feel free to give it a go.

**Comment by JMichaelTX** [comment]
> I have added an option to sort the search results by relevance and made the search a bit "smarter".

OK, many thanks.  That works very well.  As I add words to my search it continues to filter the results to a smaller result set. Perfect for my use.

Thanks again for the very quick response and update to this request.
