### ISSUE TITLE
How Do I Edit a Library Entry?

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#727]
### I'm NOT referring to the actual RegEx, but the Title and Description:

![image](https://cloud.githubusercontent.com/assets/11052885/20288094/8f1cf918-aa96-11e6-80b0-b952dfb9b2ed.png)

Also, if I DO edit the RegEx, and then "Update Library", it does NOT provide the previous Title and Description.  Surely it should.

![image](https://cloud.githubusercontent.com/assets/11052885/20288190/2e259ec0-aa97-11e6-84c0-5ffe9dd31826.png)

**Comment by firasdib** [comment]
You currently can not edit the title/description of a library entry. You can only edit the regex itself by re-saving it.

Do you mean that the title/description is lost when you update the regex?

**Comment by JMichaelTX** [comment]
Please add this feature soon.  It is very easy to make a mistake, or leave out critical information, when first saving a regex to the Library.

When I update a regex in the Library, I expect to see the same screen I get when I created it, with the Title and Description fields as they currently exist.

**Comment by firasdib** [comment]
This is finally implemented. I just have some testing to do which I hope won't take too long.

**Comment by firasdib** [comment]
The change has been pushed live!
