### ISSUE TITLE
Color regex groups in regex editor

### ISSUE THREAD

**Issue by abdulkareemnalband** [firasdib/Regex101#728]
Color regex group in regex editor as same as color of matched text in text editor

**Comment by TWiStErRob** [comment]
I think I asked this too somewhere, and the response was that it would be too colorful. If you think about the current colors + even more colors for each group, every character might be a different color.

**Comment by abdulkareemsn** [comment]
That would also helpful
Highlight the regex which is matching text currently under mouse

**Comment by firasdib** [comment]
I'm not sure what exactly we want changed here, so I'll close for now.

**Comment by TWiStErRob** [comment]
@firasdib I think the ask here is to make the parentheses for `c+` the same color as the character `c` in the input editor: https://regex101.com/r/z2lAlY/2
![image](https://user-images.githubusercontent.com/2906988/50399939-ee7bb500-077a-11e9-977d-a5bda47b7dd7.png)
I would only do it when hovering the match in the text editor.
Question is: is there a way to know which regex part matched a particular character (if not, a best effort group 1-n) parsing would be sufficient I think.

**Comment by firasdib** [comment]
Im not too keen on using that color scheme. 

What I would consider is to highlight what part of the regex matched, but thats a different issue than this I reckon. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by TWiStErRob** [comment]
@abdulkareemnalband, @Oxicode did I get it right what the original request was?

@firasdib 
> What I would consider is to highlight what part of the regex matched, but thats a different issue than this I reckon.

I don't think it's different:

> Highlight the regex which is matching text currently under mouse -- https://github.com/firasdib/Regex101/issues/728#issuecomment-261916077

I think the user need here is to find which part of the regex matched what. How it is shown (highlight, hover interaction, etc.) is an other matter.

**Comment by firasdib** [comment]
Ok!

In that case i believe this is a dup of an older issue. I can check later. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by firasdib** [comment]
Read the issue again, the original request is to use the same colors in both, which I will not do. I think it becomes too colorful and cluttered. Not helpful.

As for the other request, you can refer to https://github.com/firasdib/Regex101/issues/118
