### ISSUE TITLE
Highlight Matched group on mouseover

### ISSUE THREAD

**Issue by abdulkareemnalband** [firasdib/Regex101#729]
Highlight matched group in regex editor when mouse is on matched text and vice versa

**Comment by TWiStErRob** [comment]
See also #640 (not a dupe).

**Comment by abdulkareemsn** [comment]
Yes but match things b/w regex editor and text editor

**Comment by TWiStErRob** [comment]
Yep, just wanted to share the info in case you have not found it.
(https://github.com/firasdib/Regex101/issues/640#issuecomment-249413401 second para includes your request as well)

**Comment by firasdib** [comment]
Dup of https://github.com/firasdib/Regex101/issues/118
