### ISSUE TITLE
Handling of (?|) and possibly /J modifier

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#730]
First, the feature is named incorrectly, we talked on IRC about how that was just you trying to come up with something non too long..
I think that although it's not very explicit, the correct term 'Branch reset' should be used rather than the current "Duplicate Subpattern Group", (?| has very little to do with duplicate or subpattern.
Under the name 'Duplicate Subpattern Group' there is the explanation:
'Subpatterns declared within each alternative of this construct will start over from the same index'
I propose to change this to something better (imo) (taken from pcre's doc):
'Each alternative in a subpattern uses the same numbers for its capturing parentheses'

1) - https://regex101.com/r/5JREHf/1 - Show the same error twice in the explanation panel (which may be correct since it appears twice) however, the match information panel shows weird tokens for the error.
Also, (?| actually doesn't require /J to be set for duplicate name to work (the name have to be the same match number) but the parser seems to be aware of that (see /6), this example should return an error about name starting with number.

https://regex101.com/r/5JREHf/8 this though. unsure why it accepts the same name without /J in /6 but there reports an error about the name, it's almost like it recognize this is undefined behavior (just as /2 below) but the wrong error is given, whereas https://regex101.com/r/5JREHf/9 works

2) https://regex101.com/r/5JREHf/2 doesn't behave as one would expect but it looks like normal/undefined behavior, same as /8.

**Comment by firasdib** [comment]
I've pushed a few fixes for this and used the suggested name `Branch Reset`.

1. The "Duplicate error" is an error for the opening and closing tokens - thats how the parser is setup.
2. The error with group name with leading number is fixed
3. https://regex101.com/r/5JREHf/8 - Named groups must have the same index in a branch reset group. They aren't in your example, thus error.
4. https://regex101.com/r/5JREHf/2 - This is a heap of undefined behavior, and I would discourage anyone from using this.

**Comment by Ouims** [comment]
> https://regex101.com/r/5JREHf/8 - Named groups must have the same index in a branch reset group. They aren't in your example, thus error.

Yes, but the error is incorrect.

**Comment by firasdib** [comment]
Thanks, did not notice that. I've fixed that now.

**Comment by TWiStErRob** [comment]
Re https://regex101.com/r/5JREHf/8, the message looks weird:
![image](https://cloud.githubusercontent.com/assets/2906988/20463815/e6683aa8-af3b-11e6-808c-678ed699e436.png)
Notice closing paren and same message twice without referencing anything form the regex: e.g. group name, index or which alternation.
