### ISSUE TITLE
Cannot enter line breaks into Test String in Firefox mobile on Android

### ISSUE THREAD

**Issue by liitii** [firasdib/Regex101#731]
From a fresh load, and ensuring that *Show whitespace* is unchecked in settings, pressing the enter key gives me a visible `·` instead of a new line. Modifiers (Ctrl, Alt, Shift) make no difference. Doubt it's a keyboard issue since I have tried with a few and get the same result. The error does not occur in Chrome on the same device (using the same keyboards).

**Comment by liitii** [comment]
I think it's a bug in your/CodeMirror's user agent-specific behaviour. If I use Responsive Design Mode in Firefox to get a smaller "screen", then set my user agent to that of my device's browser `Mozilla/5.0 (Android 6.0.1; Mobile; rv:49.0) Gecko/49.0 Firefox/49.0` the same issue occurs. If I refresh, still in responsive mode after removing the custom UA, the problem disappears.

**Comment by liitii** [comment]
Doesn't happen for me on any of the [CodeMirror demos](http://codemirror.net/), though.

**Comment by firasdib** [comment]
Could be they use a newer version on the demos or something?

**Comment by liitii** [comment]
They're demoing 5.20.3, looks like you have 5.19.0.

**Comment by firasdib** [comment]
I will update codemirror when the next release is made and we can check back then.

**Comment by liitii** [comment]
No longer putting in a dot but still unable to enter line breaks at all. Pressing enter does add one but it is immediately deleted, regardless of whether it's before, in the midst of or after other text. Again, reproducible by changing only the user-agent.

**Comment by firasdib** [comment]
How odd, can you reproduce it on the codemirror website as well?

**Comment by liitii** [comment]
Still working fine on codemirror's demo using same user-agent, just not regex101.

**Comment by firasdib** [comment]
Im using vanilla codemirror so thats super odd...

**Comment by liitii** [comment]
It may not be CodeMirror alone. I'd look into it further but, without a dev environment, or even a non-minified version to debug, I can't step through the event to determine the cause.

**Comment by firasdib** [comment]
We can look at it together tonight.
