### ISSUE TITLE
(*LIMIT_RECURSION=d) and (*LIMIT_MATCH=n) don't work.

### ISSUE THREAD

**Issue by MarkWhybird** [firasdib/Regex101#732]
The help panel says (*LIMIT_RECURSION=d) at the start of a regex is possible, and (*LIMIT_MATCH=x) is also listed. However, in all flavors, having either of those anywhere in the regex just shows an error on the * stating that the preceding token is not quantifiable.

Certain other (* constructs, such as (*BSR_ANYCRLF) do not show as an error.

![limit_match](https://cloud.githubusercontent.com/assets/2282210/20418535/0f2350e8-ad9a-11e6-9315-0bcbd78fa854.png)

**Comment by firasdib** [comment]
Thanks for finding this, I have fixed it.
