### ISSUE TITLE
Request: Add option for enabling line numbers on substitution text area

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#733]
Here https://regex101.com/r/5ZtCvT/1 I get this 

![image](https://cloud.githubusercontent.com/assets/6157073/20459101/32a88834-aeae-11e6-962d-f855c2e62216.png)

where I think there's no genuine output value linebreak at the pointer, but there's nothing on the screen to indicate this.

**Comment by TWiStErRob** [comment]
Yes there's no line break, it's a soft-wrap. You can see that if you resize the window (maybe you need a bigger screen to test it).

You can turn off "Wrap long lines", but I think @firasdib is missing a "Show Line numbers for substitution" option which would allow for seeing this:
![image](https://cloud.githubusercontent.com/assets/2906988/20459823/3b6e428e-aed0-11e6-8d5e-90ec8b15a763.png)

**Comment by chrisjj** [comment]
> maybe you need a bigger screen to test it).

Maybe I need just a bigger pane. :)

> You can turn on "Show whitespaces"

That'll do! Thanks.

>  "Show Line numbers for substitution" option which would allow for seeing this:

Yes, that would be ideal.

**Comment by TWiStErRob** [comment]
> Maybe I need just a bigger pane. :)

If you need more space, you can toggle "Always collapse left/right sidebar".

**Comment by chrisjj** [comment]
Thanks. That does it - until the string is even longer :)

I'd been trying to drag the boundary http://i.imgur.com/bCpDxre.png

Do you know the significance of "Always"? E.g. does "collapse left/right sidebar" sometimes happen regardless of that checkbox?

**Comment by TWiStErRob** [comment]
Yes, the page has a responsive design, it works on mobile, tablet as well and other sized screen. In CSS you can define breakpoints based on screen size where certain elements could have different styles, in this case width/visibility/display. On smaller screens the sidebars are automatically hidden, likely yours is just not small enough. Again you can test this out by resizing the window. I turned off those "always collapse" options and empirically it seems the breakpoints are 900px and 1200px.

**Comment by chrisjj** [comment]
Thanks.

> "Show Line numbers for substitution" option which would allow for seeing this:

Did you pass this on as a feature request, or should I?

**Comment by TWiStErRob** [comment]
I think it's best we track it here. He'll eventually see this. I renamed the issue to reflect intent, because your original issue was resolved by pointing you to the options.

**Comment by chrisjj** [comment]
>  I renamed the issue to reflect intent

Thanks.

I added "Request:" :-)

**Comment by firasdib** [comment]
I think line numbers for substitution area could piggy back off of the testarea setting. What do you think?

**Comment by TWiStErRob** [comment]
I'm fine with it, we'll see if anyone complains :)

**Comment by chrisjj** [comment]
I think "[x] Show line numbers in Test String and Substitution areas" would work fine.

**Comment by Ouims** [comment]
I already suggested this feature.

**Comment by TWiStErRob** [comment]
@Ouims where?

**Comment by firasdib** [comment]
Fixed

**Comment by chrisjj** [comment]
Verified: http://i.imgur.com/YtTUkjk.png.

Thanks.

But "Show Line Numbers in Test String Editor and Substitution Result" might better as "Show line numbers on Test String and Substitution"
