### ISSUE TITLE
Bug report/Request: line number in Unit Tests test string area

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#734]
"[x] Show Line Numbers in Test String Editor" omits to take effect on the Unit Tests test string area:

![image](https://cloud.githubusercontent.com/assets/6157073/20463190/717f02cc-af26-11e6-9b92-dc58eaf445b0.png)

It would be good if it did!

**Comment by firasdib** [comment]
It will not do that, sorry.

**Comment by chrisjj** [comment]
OK! Thanks anyway for considering it.

And many thanks for the Units Tests feature! Invaluable!
