### ISSUE TITLE
operations on selection

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#736]
https://regex101.com/r/70zrHi/1 -- in the regex area, select the quantifier '*', try to right click (you can also just try control + c, it doesn't work) the context menu won't be the one expected.

Cannot reproduce on chrome atm, it may be a firefox issue only.

Firefox 50.0

**Comment by firasdib** [comment]
Could be an issue with Codemirror.

**Comment by firasdib** [comment]
Is this still relevant?

**Comment by firasdib** [comment]
Closing, fixed.
