### ISSUE TITLE
Pre-define patterns from the reference guide does not work

### ISSUE THREAD

**Issue by kakuzei** [firasdib/Regex101#737]
Hello,
It seems that the "Pre-define patterns before using them" example from the reference guide does not work: https://regex101.com/r/4Zxz2k/1
Thanks

**Comment by TWiStErRob** [comment]
`(?&letters)` is a workaround I think; see https://regex101.com/library/mR9nV0

**Comment by firasdib** [comment]
Thanks. Ive fixed the bug.

**Comment by kakuzei** [comment]
Thanks for your responsiveness !
