### ISSUE TITLE
Empty page loaded

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#739]
On IRC, when people ask for help, typically using !rehelp, when they give their link, when I click it, it will load an empty page, trying to access that url again right away will usually load the correct content, i think it's timing issue but maybe not.
Since firefox is my main browser, that's what load when i open link from IRC, unsure if it's related to browser, but firefox 50.0.
OnlineCop said it was happening to him as well, I thought it was worth mentioning.

I don't have a link to illustrate unfortunately. But i, or someone else, can assist you trying to reproduce.

**Comment by working-name** [comment]
I can confirm the first issue happening in Chrome on OS X. My Chrome is v53 (most likely old)

**Comment by firasdib** [comment]
Try clearing your cache and see if it persist. This _could_ be related to https://github.com/firasdib/Regex101/issues/722

**Comment by Ouims** [comment]
Alright, i cleared the cache, we'll see

**Comment by Ouims** [comment]
So i just cleared the cache, just opened https://regex101.com/r/Lpp1re/1 from IRC, it loaded a blank page.

**Comment by TWiStErRob** [comment]
Does it load an empty page when you open it from somewhere else? Is it possible that IRC does some tracking (similar to google/gmail/twitter's `http://host.com/...?url=https%3A%2F%2Fregex101...`) that somehow affects this?

**Comment by Ouims** [comment]
No, IRC (mIRC in this case) just pass the url to firefox, via whatever method is available (dde, sendmessage, maybe even command line).
It shouldn't matter from where I open the link.
I asked digitok to save a regex and post the link on IRC, which i quickly opened, but it opened correctly.

**Comment by working-name** [comment]
For what is worth, I'm using Textual, and Chrome is set as my default browser. The behavior continued after cache/cookies were cleared, browser restarted. However it is randomly happening... so that's hard to debug.

**Comment by TWiStErRob** [comment]
Is the browser running when this happens, or the action on IRC triggers a browser launch? (I guess most people have the browser running as long as the computer is running, just want to clarify this.)

Also what does a blank page mean? If I could repro (which I couldn't so far), I would immediately fire up the developer tools when it's white and see the page structure, console output, potential errors, loaded resources, network tab for clues. There are numerous ways to get a white blank browser tab.

**Comment by OnlineCop** [comment]
I will open a link (bookmark, from IRC, or type it directly into my browser) to any saved regex. Instead of loading that page, it will load the base https://regex101.com/ and I have to re-open that link in order for me to see the content.

**Comment by working-name** [comment]
My browser is always running. 

What happens is it opens the URL I clicked, and then immediately redirects to the homepage as if the revision doesn't exist or the branch was removed. But it wasn't, because I can paste it manually and it loads up ok.

**Comment by TWiStErRob** [comment]
Ah so blank does not mean fully white page (i.e. `about:blank`), but a fully loaded regex101 UI with nothing filled in for @working-name. However based on OP @Ouims's case is different, because he said F5 solves it, which wouldn't work after a hard redirect. @working-name Do you see the redirect happening in the url bar? If not, that explains why F5 helps. @OnlineCop's case sounds like he gets a hard redirect.

**Comment by working-name** [comment]
Yes, I initially see the URL I clicked in the nav bar, but it then gets redirected to the home page. Very similar to OnlineCop.

**Comment by working-name** [comment]
@TWiStErRob, I think @Ouims means the same thing however. blank page = regex101.com homepage

**Comment by TWiStErRob** [comment]
@working-name yes, but how does F5 show the correct content if he's at https://regex101.com/? I guess he may have pressed it so soon, that the browser couldn't process the redirect.

**Comment by working-name** [comment]
Yes that would be my thought as well

**Comment by Ouims** [comment]
Yes, sorry about that, i almost wanted to be more explicit but figured it was enough, I do get the main UI loaded. Though i never checked if it were trying to load the correct url (if the url in the url bar is correct at first)

**Comment by Ouims** [comment]
My mention of f5 was also misleading, i meant that trying to access the correct url again will work.

**Comment by Ouims** [comment]
@TWiStErRob I do think it's the same issue but could be wrong, i'll seperate the issue right now

**Comment by Zarthus** [comment]
Happened to me for https://regex101.com/r/lhh0ke/1  - not sure why, nothing useful in console, either. It's not reproducable, it just happens once.
