### ISSUE TITLE
Empty/first revision page incorrectly loaded

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#740]
Suppose i'm looking at a link which is the 5th version. Someone makes an update and save, generating 6th version, they give that link on IRC but instead of loading that url from IRC, I just click the dropdown combo 'select regex version' and it correctly give me the 6th version, but upon clicking it, it will load the first version.

Edit: I don't remember if it'll load an empty/default page or the first revision

**Comment by Zarthus** [comment]
Happened to me for https://regex101.com/r/lhh0ke/1  - not sure why, nothing useful in console, either. It's not reproducable, it just happens once.

**Comment by firasdib** [comment]
Fixed
