### ISSUE TITLE
Unit Tests: Alternations with non-participating matches

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#741]
https://regex101.com/r/RXw0AM/2

An alternation with a capture group in each portion is tested against text that contains text that will match both.

In Unit Tests, the 'capture group 2' reports a failure to match, stating `Group 2 no longer exists in the pattern or did not participate in the match`. Both Group 1 an Group 2 appear under MATCH INFORMATION, so I would expect that Group 2 does -- in fact -- exist, and the unit tests may not be properly discerning it.

**Comment by firasdib** [comment]
This is because the unit tests don't operate under the "global" flag. So in the second unit tests, only the first capture group is ever populated.

**Comment by OnlineCop** [comment]
This makes sense. Closing the issue.

**Comment by Ouims** [comment]
There is no way this issue can be closed. This is a bug which needs to be fixed.
Why are units test not run under the /g modifier when the regular expression has /g?
If there is a good reason for this, then the UI shouldn't let us check for a capturing group which can't be tested.

**Comment by firasdib** [comment]
Because then you'd have to specify which match each group should be tested against, which is not how unit tests are supposed to be constructed. Create your tests better.
