### ISSUE TITLE
Non-accordance of explanation?

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#742]
This https://regex101.com/r/RYpe8v/6 shows 

![image](https://cloud.githubusercontent.com/assets/6157073/20778829/77d90916-b768-11e6-88f1-756fcbfc436c.png)

despite that "Matches as few times as possible" would include line 4 but not lines 2 and 3 as seen.

I don't think I've misunderstood the Explanation. It is inaccurate?

**Comment by Ouims** [comment]
This is correct, you're not using the /U modifier so *? is a non greedy quantifier (match as few times as possible), The engine will match A, then the only way to match C is to match everything in between, if you are talking about the big green highlight, it's a feature, it shows that the newline is being matched

**Comment by chrisjj** [comment]
> This is correct,

What's correct? The Explanation? Or my "It is inaccurate"?

> if you are talking about the big green highlight

I'm not. I'm talking about the Explanation.

**Comment by firasdib** [comment]
The explanation is correct.

The behavior is not though, and I think you have stumbled upon a bug in PCRE.

**Comment by TWiStErRob** [comment]
I think you're looking for `A([^A]*?)C`

**Comment by TWiStErRob** [comment]
Matching happens from left to right, and the lazy quantifier only applies to the end of the match? That is `A.*?C` matches `AxxxxC` in `AxxxxCxxxxC`; if you were to remove the `?` you get `A.*C` which is greedy and matches the whole `AxxxxCxxxxC` string.

**Comment by chrisjj** [comment]
> Everything is working exactly as it should.

The Explanation says "_*? Quantifier — Matches between zero and unlimited times, **as few times as possible**, expanding as needed (lazy)_"

Yet the Match Information shows line 3 is included despite that "as few times as possible" is just the word 'item' on line 4.

![image](https://cloud.githubusercontent.com/assets/6157073/20792233/a3ec62e6-b7b8-11e6-85a5-83c4af6acf40.png)

So, the Explanation fails to accord with the behaviour. Are you really sure that's "Everything is working exactly as it should."??

**Comment by chrisjj** [comment]
> I think you're looking for A([^A]*?)C

Thanks, but that Expression is just a test. What  I'm looking for is an accurate Explanation.

**Comment by firasdib** [comment]
Yes. Everything is working like it should. You can open the debugger to see how the regex engine is matching everything.

The explanation is accurate as well, it seems your knowledge of how the engine is operating is the issue here. I'm not sure how the explanation can be phrased differently.

**Comment by TWiStErRob** [comment]
Don't forget to read the "expanding as needed" part, matches cannot shrink from the left, only from the right. See http://www.regular-expressions.info/repeat.html and the debugger Firas mentioned.

**Comment by chrisjj** [comment]
> it seems your knowledge of how the engine is operating is the issue here. 

I can't see how my knowledge of how the engine is operating has any bearing on the accuracy of the Explanation.

An Explanation is either accurate or not.

> The explanation is accurate as well

How can "as few times as possible" be accurate given this term is clearly matching many more than the four times that are possible?

**Comment by firasdib** [comment]
Because you have the `s` flag enabled.

**Comment by chrisjj** [comment]
I'm well aware the s flag is what allows the term to match more than the word 'item'.

But the s flag does not _require_ the the term to match more than the word 'item'.

Which leaves us with the fact that that the Explanation says the quantifier is matching "as few times as possible" whereas in fact it is matching more that the fewest possible.

**Comment by firasdib** [comment]
No. You are wrong. Read up online or enter IRC and someone will explain it to you.

**Comment by TWiStErRob** [comment]
> I can't see how my knowledge of how the engine is operating has any bearing on the accuracy of the Explanation.

Read the section "The Regex Engine Always Returns the Leftmost Match" at http://www.regular-expressions.info/engine.html

I can see how `AitemC` is shorter than `A\nA\nAitemC`, and agree that both are ambiguously matching your pattern, however the above rule clears up this ambiguity.

It's not possible to write down all the internals of the regex engine for each token's explanation.
