### ISSUE TITLE
Sticking tooltips in webkit

### ISSUE THREAD

**Issue by vktec** [firasdib/Regex101#744]
In webkit-based browsers such as surf and qutebrowser with the QtWebKit backend, tooltips don't go away when you move your mouse off them. See images below.

![1480708133](https://cloud.githubusercontent.com/assets/14016168/20848104/914ef3e0-b8c8-11e6-8960-ea3095647a8a.png)
![1480708173](https://cloud.githubusercontent.com/assets/14016168/20848105/9173e1d2-b8c8-11e6-8561-2b6c8f24546f.png)

**Comment by firasdib** [comment]
Do you have any errors in your console?

**Comment by vktec** [comment]
Yes.

```javascript
TypeError: undefined is not an object (evaluating 'this.onMouseEnter')
```

Also, this seems to be an intermittent fault. Sometimes it works fine, sometimes it doesn't

**Comment by firasdib** [comment]
Fixed
