### ISSUE TITLE
Variation in Full Match colouring

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#745]
Is this variation in the TEST STRING Full Match colouring Working As Designed?

1\) light blue then  2) darker. Not present in MATCH INFORMATION.

![image](https://cloud.githubusercontent.com/assets/6157073/20855496/8b40c410-b8f5-11e6-8137-c0cac511b3e8.png)

If Yes, then what is it trying to tell me?

**Comment by TWiStErRob** [comment]
The test string has alternating match colors so you can see the individual matches:
![image](https://cloud.githubusercontent.com/assets/2906988/20858584/426261e2-b948-11e6-9ce2-59458de9e16b.png)
in the match information panel this is not necessary, because the heading "Match \<n>" separates them.

**Comment by firasdib** [comment]
I have adjusted this behavior to be displayed in the match info box as well now.

**Comment by chrisjj** [comment]
> The test string has alternating match colors so you can see the individual matches:

Aha. I wonder why then alternating match colour aren't used on Groups:

![rvcurwj 1](https://cloud.githubusercontent.com/assets/6157073/20863102/6912d2f2-b9b8-11e6-940c-057e810084a8.png)

Perhaps they should be.

> I have adjusted this behavior to be displayed in the match info box as well now.

Thanks. Verified (https://regex101.com/r/zSSffV/1 before http://i.imgur.com/RYqu9PG.png , after http://i.imgur.com/3WGtTfN.png ) but the MATH INFORMATION green background for Match 2 Group 1 has gone missing.

**Comment by firasdib** [comment]
Only the first group alternates in color. Fixed the bug.

**Comment by TWiStErRob** [comment]
@firasdib I see chris' point, would it be a lot of effort to alternate the brightness for all groups, not just the whole match (group 0)?

**Comment by firasdib** [comment]
For it to look good you'd have to manually select the alternative colors, because creating them programatically does not ensure they have good contrast.

**Comment by TWiStErRob** [comment]
If you use the HSV namespace and change Value by 10 you will get a good distinction between the colors, see for example your Group 1 Green (middle one): https://color.adobe.com/create/color-wheel/?base=2&rule=Custom&selected=2&name=My%20Color%20Theme&mode=hsv&rgbvalues=0.06439024390243503,0.12,0,0.11804878048779756,0.22,0,0.17254901960784313,0.3215686274509804,0,0.2253658536585226,0.42,0,0.27902439024388515,0.52,0&swatchOrder=0,1,2,3,4

**Comment by chrisjj** [comment]
>  Fixed the bug.

Thanks. Verified: 

![image](https://cloud.githubusercontent.com/assets/6157073/20865967/76091538-ba18-11e6-92d2-8d87787f233a.png)

**Comment by firasdib** [comment]
@TWiStErRob I do have that, but its not the problem. Some of the colors I have need to be chosen in a different manner for that to work out great for all 10 groups.
