### ISSUE TITLE
^ and v seem the wrong way around to me

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#747]
^(up) drops the panel and v (down) rolls it up.

![image](https://cloud.githubusercontent.com/assets/6157073/20869333/53b2a8aa-ba68-11e6-833f-5b6d05b843c6.png)

**Comment by TWiStErRob** [comment]
See some parts of #638 with some loosely related discussion.

I think both ways can be argued for, depends on whether the icon reflects the current state, or shows what action will happen.

The current behavior is consistent with common UI designs of trees (closes pattern to expandable panes) for example (e.g. Gmail nested labels,, Windows 10 Device Manager), where you have a `>` (closed, click will expand) and a `v` (expanded, click will close) state.

**Comment by chrisjj** [comment]
> I think both ways can be argued for, depends on whether the icon reflects the current state

There's little point reflecting the current state. The current state is directly visible right below the button.

> or shows what action will happen.

Every other button I see on the page follows the convention that the icon shows what will happen.

> The current behavior is consistent with common UI designs of trees (closes pattern to expandable panes) for example (e.g. Gmail nested labels,, Windows 10 Device Manager), where you have a > (closed, click will expand) and a v (expanded, click will close) state.

Current behaviour has an ^ (up). That's not consistent with e.g. Gmail labels' > (right).
