### ISSUE TITLE
^ and $ assertions cause valid matches to fail

### ISSUE THREAD

**Issue by mddeff** [firasdib/Regex101#748]
# Summary
When using ^ (Beginning of line) and $ (End of line) in patterns, it fails to match anything past the first line (global flag is set).  If the pattern doesn't appear on the first line, it doesn't match at all.  This was done in the `pcre (php)` flavor.

# Test Data
## Regular Expression
```
^bar
```
## Test String
```
bar biz
foo bar
biz bam
bar bam
barfoo
```

# Expected Result
Matching of lines 1, 4, and 5 ("bar biz", "bar bam", and "barfoo")

# Actual Result
Only matches line 1 ("bar biz")

# Discussion
Is this because everything in the "Test String" is treated as one string? Rather than treating each line as a separate string (ala grep, perl, sed).

**Comment by OnlineCop** [comment]
`^` and `$` default to full-text matching modes, so `^` matches the beginning of the string and `$` matches at the end of the string (not end of the line). If you want the `^` and `$` to work on a per-line mode, use the `/m` flag for `multi-line mode`.

**Comment by mddeff** [comment]
Ah!  Thanks @OnlineCop.  Maybe I should read all of the flags next time...
