### ISSUE TITLE
FAQ contents links go to empty topics rather than the sections below

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#749]
On https://github.com/firasdib/Regex101/wiki/FAQ, click

 Will you open source Regex101?

Expected: goes to that section below.
Observed: goes to https://github.com/firasdib/Regex101/wiki#will-you-open-source-regex101 "TBD".

**Comment by firasdib** [comment]
Still needs updating. @nhahtdh do you have time?

**Comment by TWiStErRob** [comment]
Fixed this specific issue, are we tracking the needed update anywhere else?

**Comment by chrisjj** [comment]
> Fixed this specific issue

Verified.
