### ISSUE TITLE
Failure to highlight last matched line break.

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#750]
I expected this https://regex101.com/r/4Zst1V/1 to highlight the final line break.

But it doesn't.

![image](https://cloud.githubusercontent.com/assets/6157073/20907100/13d9f076-bb44-11e6-84d9-dbfa95be5696.png)

**Comment by OnlineCop** [comment]
If you notice in that screenshot, *MATCH INFORMATION* on the bottom-right shows that two newlines have been matched: one after `one` and another after `two`, as the closing backtick is on the line below instead of right after `two`.

If you use `[^\nx]+` instead, your results should show the backtick on the same line as `one` and `two`.

**Comment by chrisjj** [comment]
> If you notice in that screenshot, MATCH INFORMATION on the bottom-right shows that two newlines have been matched

I noticed. I don't know what suggests I didn't.

My issue isn't with the MATCH INFORMATION, or what is matched. Two breaks are matched. That's as expected.

My issue is with the failure of highlight to include the last (second) break.

Here:

![image](https://cloud.githubusercontent.com/assets/6157073/20907570/01a5c92c-bb47-11e6-8050-049f5f889f19.png)

**Comment by firasdib** [comment]
Line break visualization is a shim created by me, as codemirror does _not_ represent newlines. So there is no way to highlight them.

**Comment by chrisjj** [comment]
> Line break visualization is a shim created by me

Could that shim be fixed?

**Comment by OnlineCop** [comment]
Is it absolutely necessary? The backticks do correctly show that the match had a newline, even though the blue highlight does not. With the way that CodeMirror works, we have several edge cases that we have to consider here (multiple newlines, use of `(*CR)` and `(*CRLF)` style verbs, matches that do/don't occur before the end of the string), and it could actually present more bugs than it fixes.

**Comment by chrisjj** [comment]
> Is it absolutely necessary?

Only if this tool is supposed to accurately display the match.

> The backticks do correctly show that the match had a newline

Sure they do. Otherwise I would have reported inaccuracy there too. :-)

**Comment by TWiStErRob** [comment]
@firasdib is it really not fixable? it works just a line before, maybe it's a simple off-by-one type bug. It looks really misleading: https://regex101.com/r/4Zst1V/3

**Comment by firasdib** [comment]
Not sure I follow, @TWiStErRob

**Comment by TWiStErRob** [comment]
@firasdib I meant that it works after "one", so it should be able to show after "two" as well.
