### ISSUE TITLE
Suggestion: icon button to expand unit text

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#751]
I think the Unit Test bar 

![image](https://cloud.githubusercontent.com/assets/6157073/20924948/e2f02332-bbab-11e6-8670-07a82b9f306f.png)

would benefit for an icon button to expand/ collapse the description

![image](https://cloud.githubusercontent.com/assets/6157073/20924965/f90dd448-bbab-11e6-9b8e-2a3a78c6e9f9.png)

**Comment by firasdib** [comment]
The idea is what the entire button is supposed to do that. But perhaps an icon at the far left could do that.

**Comment by TWiStErRob** [comment]
Did you mean "entire bar"?

**Comment by chrisjj** [comment]
> The idea is what the entire button is supposed to do that. 

The problem with that idea is that there is no entire button visible as a button.

**Comment by Doqnach** [comment]
This is now covered by #793 right?

**Comment by TWiStErRob** [comment]
@Doqnach no, you're just seeing it on the screenshot. Firas is working on the todo milestone, which is not updated/released yet.

**Comment by Doqnach** [comment]
Wanted to reference it here in case @chrisjj was looking back on the status of his issue ;-]

**Comment by chrisjj** [comment]
Thanks for the thought! :)

But no, it is not covered by #793.

**Comment by chrisjj** [comment]
FTR, this wasn't implemented.

![image](https://cloud.githubusercontent.com/assets/6157073/23825018/0f99b29a-067a-11e7-8159-ac208776dd26.png)

**Comment by firasdib** [comment]
There is an icon on the far left.

**Comment by chrisjj** [comment]
Thanks. I'd missed that. Esp. since it makes no difference to a hover/click in the middle.

![image](https://cloud.githubusercontent.com/assets/6157073/23825084/34d942ae-067b-11e7-819c-afe0a3f1818c.png)

Definitely some improvement. Thanks.

**Comment by TWiStErRob** [comment]
It changes when you expand/collapse the bar via click on it.
Downward pointing triangle means open, sideways means closed.
Are you expecting the reverse like in #747?

**Comment by chrisjj** [comment]
> It changes when you expand/collapse the bar via click on it.

Sure does. Giving a bar that has two down arrows, doing different things. 

![image](https://cloud.githubusercontent.com/assets/6157073/23832154/5dad3bf2-0727-11e7-85de-171c74f073be.png)

And confusingly still an invisible button behind the two of them that does the same as one of them.

Firas, I think my old-fashioned expectations are probably simply outside the scope of Regex101's UI design philosophy! :)

But the left down arrow could do with a tooltip.

**Comment by TWiStErRob** [comment]
I wouldn't even look for a button to expand/collapse an area like this, the whole bar/title should be actionable, it's more natural, than trying to tap an 16x16 area.
