### ISSUE TITLE
Suggestion: Unit Test 'assert that' wording

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#752]
I think the Unit Test 'assert that' drop-down list options 

![image](https://cloud.githubusercontent.com/assets/6157073/20925078/945177e8-bbac-11e6-8c75-8ec23343c0c8.png)

would benefit from using instead the nomenclature of MATCH INFORMATION:

![image](https://cloud.githubusercontent.com/assets/6157073/20928664/d49af0b0-bbbe-11e6-8e8e-301402d21f6c.png)

`Full match` and `Group <n>`.

**Comment by chrisjj** [comment]
I wonder why this was closed.

Not because it was implemented, for sure.

![image](https://cloud.githubusercontent.com/assets/6157073/23824988/5402d110-0679-11e7-9d85-38f4a4a6a1a9.png)

**Comment by firasdib** [comment]
Are you referring to `capture group n` instead of `group n`?

**Comment by chrisjj** [comment]
Yes.

**Comment by firasdib** [comment]
I think its fine.

**Comment by TWiStErRob** [comment]
Agree with @firasdib there's a little less context given in unit tests, than in a match info pane, so being a more specific doesn't hurt.

**Comment by TWiStErRob** [comment]
Also note: `a(?:b)(c)` has two groups, but only one capture group.

**Comment by chrisjj** [comment]
> being a more specific doesn't hurt.

I don't believe it is more specific. "Group <n>" is already unambiguous and Unit Test isn't lacking any context that makes it clearer elsewhere.
