### ISSUE TITLE
Suggestion: MATCH INFORMATION in Unit Tests

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#753]
In Units Tests MATCH IFORMATION can show a Full Matched empty string

![image](https://cloud.githubusercontent.com/assets/6157073/20928808/533c54ae-bbbf-11e6-8982-e6015eb2fb23.png)

or remnant of the last TEST AREA result

![image](https://cloud.githubusercontent.com/assets/6157073/20928873/a1f9adf8-bbbf-11e6-8b5f-00bfb8a86b34.png)

I suggest it would benefit from instead showing nothing or ideally the result of selected Unit Test.

**Comment by firasdib** [comment]
The sidebar is unrelated to the unit testing view. I could clear it though.

**Comment by chrisjj** [comment]
> I could clear it though.

I definitely think that would be an improvement.

**Comment by chrisjj** [comment]
> I could clear it though.

I see you now do. Thanks.
