### ISSUE TITLE
Bug? javascript (sic) TEST STRING group highlight is missing

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#755]
I'd expect this https://regex101.com/r/reAD3E/7 to highlight TEST STRING `z` in green:

http://i.imgur.com/LliHKTM.png
![image](https://cloud.githubusercontent.com/assets/6157073/21009333/ff5b9464-bd3d-11e6-9c31-827d24cb9e34.png)

It doesn't:

![image](https://cloud.githubusercontent.com/assets/6157073/21009362/1e8a0406-bd3e-11e6-84dc-449a67cda35b.png)

MATCH INFORMATION confirms group match:

![image](https://cloud.githubusercontent.com/assets/6157073/21009467/aa45d772-bd3e-11e6-8f7c-319ad2a2ae4f.png)

**Comment by firasdib** [comment]
It is not possible to get subpattern match position in javascript and thus I can not highlight it.

**Comment by chrisjj** [comment]
OK, thanks.
