### ISSUE TITLE
Java code generator

### ISSUE THREAD

**Issue by mescortes** [firasdib/Regex101#757]
The code generated for this regex is wrong:

"follows": {"count": (\d+)}

It should be: `"\"follows\": \\{\"count\": (\\d+)"`

But instead it is: `"\"follows\": {\"count\": (\\d+)"`

**Comment by firasdib** [comment]
Can you please provide a permalink

**Comment by mescortes** [comment]
https://regex101.com/r/T8tGcY/1

The code generated in java is not escaping before `{` and `}`

**Comment by firasdib** [comment]
Thanks for the info. I've pushed a fix, going to restart the server soon.

**Comment by mescortes** [comment]
Thanks you! That was fast!
