### ISSUE TITLE
Feature Suggestion: Provide with more "expression flags" to test regex

### ISSUE THREAD

**Issue by knayan1** [firasdib/Regex101#759]
Hey Team,

Please provide more "expression flags" while using regular expression. I needed to test for 'c', but unfortunately this site doesn't provide.

regex = /\G./gc

Thanks,
Kamal

**Comment by Ouims** [comment]
Hello, there is no support for the Perl engine (the c modifier seems to be perl related).

**Comment by knayan1** [comment]
Yeah! Its for perl. Closing the thread!
Thanks for response :+1:
