### ISSUE TITLE
Offline version?

### ISSUE THREAD

**Issue by bram1028** [firasdib/Regex101#76]
I would like to see an offline version of this. Maybe a Chrome app.

**Comment by CodeMan99** [comment]
Created script based on @Syskaw's [offline directions](https://github.com/Syskaw/Regex101.com-offline-app/pull/1). Meant to be simple enough you can drop in the parts you want.

**Comment by aurbano** [comment]
@firasdib would it be ok if I package regex101 as a mac application for offline use?

**Comment by firasdib** [comment]
@aurbano go ahead!

**Comment by aurbano** [comment]
@firasdib cool!
This is an extremely early version, I might add some feature over the next couple of weeks: https://github.com/aurbano/regex101-osx

**Comment by firasdib** [comment]
@aurbano Nice work!

**Comment by CodeMan99** [comment]
@aurbano Cool stuff.

I'd love to see this repo your repo get merged or at least linked in the README.

Thoughts @firasdib ?

**Comment by dufferzafar** [comment]
I used the @syskaw's tutorial to get regex101 working offline. So that everyone doesn't have to go through the same work. Here's a [ZIP](https://www.dropbox.com/s/r0gguscne28bf34/Regex101-30-May-2015.zip?dl=0).

**Comment by CodeMan99** [comment]
@dufferzafar : @Syskaw's repo already has a [script for that](https://github.com/Syskaw/Regex101.com-offline-app/commit/0769622cff37fb9f8c90c5b38a3763190123ec5a).

**Comment by dufferzafar** [comment]
Um, the script worked, but not completely - the site still fetched some stuff like FontAwesome, OpenSans font from Google Fonts etc. 

I downloaded each and every dependency, to make it completely offline.

**Comment by firasdib** [comment]
@CodeMan99 I'll add a link

**Comment by akramparvez** [comment]
@firasdib I create a free chrome app, hope it's ok. Let me know if there is any issue.
[https://chrome.google.com/webstore/detail/regex101/pjoipnocgklcnjhohaaeffemifmbnkho](https://chrome.google.com/webstore/detail/regex101/pjoipnocgklcnjhohaaeffemifmbnkho)

**Comment by NekR** [comment]
I could make it a Progressive Web App (available offline, add to homescreen, etc) if I had access to the code.

**Comment by barryanders** [comment]
Offline use would be awesome.

**Comment by Taraflex** [comment]
+1 for @pomeh html5 app cache the simplest way to make an offline version.

**Comment by fnkr** [comment]
@Taraflex Well, it's the only way to make an offline version.

**Comment by NekR** [comment]
@fnkr no. Now there is ServiceWorker and it's way better and now harder if you use tools to generate it.

**Comment by NekR** [comment]
@TWiStErRob it would be really great to make this a Progressive Web App. As I suggested before, I would be happy to help in that and in ServiceWorker implementation (maybe with fallback to AppCache).

I know it isn't open source, but probably we can figure it out somehow anyway.

**Comment by TWiStErRob** [comment]
@NekR I agree, but wrong mention. I don't have code access either, you want @firasdib's attention. You may want to offer your services privately to him to see if you can get involved.

**Comment by Taraflex** [comment]
Simple mirror http://regex101-taraflex.rhcloud.com/ with offline support based on html5 app cache.

**Comment by SecondeJK** [comment]
After having a look around at free apps on Android  and iOS I can safely say there isn't a better regex tool out there. PWA for this and I will give hard cash out!

**Comment by firasdib** [comment]
Offline has finally arrived. I'm using service workers, so you'll need a fairly recent browser. It'll automatically cache everything for you as you visit the site and when you're offline it will continue to work.

**Comment by eromoe** [comment]
Sorry, I don't understand the offline FAQ:
> The website utilizes service workers under the hood

There is no project I can clone, how can I use regex101 offline ?
Why not make a chrome app, somebody make one in 2016, but it doesn't keep lastest.

**Comment by BarryMode** [comment]
As long as the site exists, an offline version isn't that important to me, but if the site were ever to be closed for whatever reason, it would be nice if an app was released. I don't expect the site to go down, just saying. A service I loved, I made the same request years ago and it just went down a couple months ago. No release so it's totally gone. Sad day. Hope that doesn't ever happen to Regex 101.

**Comment by JMichaelTX** [comment]
> Offline has finally arrived. I'm using service workers, so you'll need a fairly recent browser. It'll automatically cache everything for you as you visit the site and when you're offline it will continue to work.

@firasdib, I'm sorry, but I don't understand how to create an offline version of your great web site.  Could you please provide details for doing so with Chrome?

I have done some research, but the only thing I can find seems to save offline copies for EVERY web page I view.  I do NOT want ALL web pages, just regex101.com.  How can I achieve that?

BTW, I suspect there are many others like me who don't understand this.  May I suggest that you add it directly to your [FAQ page](https://github.com/firasdib/Regex101/wiki/FAQ#is-there-an-offline-app-for-regex101).

Thanks.

**Comment by TWiStErRob** [comment]
@JMichaelTX it's really simple: open the regex101 while online, and then go offline and you can still visit the webpage.

**Comment by JMichaelTX** [comment]
> it's really simple: open the regex101 while online, and then go offline and you can still visit and work on the webpage

@TWiStErRob , I don't think it is that simple.  That is just relying on the TEMPORARY cache of the web page and its resources, which will be delete soon.

I'm looking for an offline solution that will work forever.  Use case:  I might using regex101.com online, and then a week later be on an airline trip where I need to access the offline version.  The web page cache is not likely to be available a week later.

Or maybe it has been a month since last used regex101.com online, and I'm at a location with no Internet access, and I now need access to offline regex101.com.

Also, what about my snippets that I have saved to my online account?  Are they available offline?  If so, how?

**Comment by fnkr** [comment]
@JMichaelTX

> That is just relying on the TEMPORARY cache of the web page and its resources, which will be delete soon.

No, it uses service workers, not just the browser cache. https://developers.google.com/web/fundamentals/codelabs/offline/
