### ISSUE TITLE
Updating the Quick Reference details window

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#760]
Suppose i set the flavor to javascript, in the quick reference panel, i select modifier > 'u'.
This correctly shows the 'u' modifier explanation for javascript.
If i switch to PCRE, (which also has a 'u' modifier, but requires different explanation), the description is not updated nor the 'detail window' is closed.
I believe it should update the detail window if applicable (like here) but it should probably close the window if not applicable (and the quick ref list is already updated).
Otherwise, you can be looking at something which does not exist in the flavor, which is misleading.

**Comment by firasdib** [comment]
thanks ouims, the issue has been fixed.

It'll be pushed in a few weeks.
