### ISSUE TITLE
Request to delete personal information

### ISSUE THREAD

**Issue by siuhtk** [firasdib/Regex101#762]
Recently I used Regex101 to write an expression with a test string that contains personal information of a lot of people. I wasn't logged in and didn't store the deletion link (just like some other Issues posted here). Since I basically made their personal information publicly available and I'm not able to manage the information anymore (since I didn't store the deletion link), I wondered if I can request to delete this personal information of these people.

I can provide the estimated time I posted the regex, the URL, and the fact that anyone would probably agree that the test string contains personal information.

Since their privacy is victim of my stupidity, is there any imaginable way to remove this personal information?

**Comment by TWiStErRob** [comment]
see #754

**Comment by Zarthus** [comment]
Lindrian has been quite vocal about his (lack of) cooperation on this issue. I'll close down this issue, but will prod Lindrian to check it out at the very least.

Please continue discussion in the relevant highlighted issue.

**Comment by TWiStErRob** [comment]
@siuhtk Lindrian = @firasdib
