### ISSUE TITLE
Bug: WRONG matching string pattern

### ISSUE THREAD

**Issue by AlbertoBedo** [firasdib/Regex101#763]
This regex: /(^[0-9]+).?([a-z]*)/i

on Regex101 **DOES NOT** match string: 12sa343sdasddsa

However this string should be matched as "12sa"

**Comment by firasdib** [comment]
Works fine https://regex101.com/r/RE25QC/1

**Comment by OnlineCop** [comment]
https://regex101.com/r/ClC4Hy/1

Seems to match to me.

**Comment by AlbertoBedo** [comment]
Oh now it works for me too now. However I have a browser window (chrome) where it still does not match. I copy-pasted the regex and the string multiple times. Maybe a javascript error on the auto refresh?

**Comment by firasdib** [comment]
Which flavor? Please check the console for any errors.

**Comment by AlbertoBedo** [comment]
I closed the browser right now... cannot reproduce anymore :(
