### ISSUE TITLE
Arabic characters not highlighted on match

### ISSUE THREAD

**Issue by zdrd** [firasdib/Regex101#764]
Using the regex: ([^\u0000-\u007F]|\w)+
in JavaScript mode, with sample test string: صف شيشرون سرقوسة بأنها أعظم وأجمل مدينة
returns matches that are not highlighted, but the hover feature shows them as a match when hovering over the arabic text.

**Comment by firasdib** [comment]
Please supply a permalink.

Which browser and OS?

**Comment by zdrd** [comment]
https://regex101.com/r/sV8uK9/9
Chrome browser on Mac Sierra v10.12.2

**Comment by firasdib** [comment]
Seems to be some weird behavior with codemirror and rtl characters.

**Comment by firasdib** [comment]
I've looked into this and I can get it to work, just need to figure out some quirks. There is an upstream bug related to this here https://github.com/codemirror/CodeMirror/issues/4878

**Comment by firasdib** [comment]
A push has been fixed live, please test it out.
