### ISSUE TITLE
Reference the Nth match in substitution field

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#765]
Someone just asked about this, I think it would be nice to be able to reference the Nth match.
$N looks like it could be used since it's not currently used (and i don't think it would break?)

regex         :    /([a-z)/g

test string   :     abc
substitution :  $N. \1

result           : 1. a2. b3. c

**Comment by TWiStErRob** [comment]
It would break this: https://regex101.com/r/kSxJQC/1

**Comment by firasdib** [comment]
Adjust your regex to match your needs instead.

**Comment by Ouims** [comment]
There's no way to adjust a regex to accomplish that, no idea what you meant back then.
