### ISSUE TITLE
Regex for -- -- fails (engine error)

### ISSUE THREAD

**Issue by MBfromOK** [firasdib/Regex101#766]
I have this string "-- --------------------------------------------------------" that I am searching for in a large file

Entering --\s-------------------------------------------------------- as the regex works

Using -{2}\s-{56} or -{2}\s-{16,56} both cause engine errors (as well as -{2}).

(this matters because it is just the start of a multiline string I am searching for and I need to shorten it for clarity)

Thanks!

**Comment by Ouims** [comment]
Can you pleave provide a permalink which shows the error? A quick try with pcre (php) shows no issue https://regex101.com/r/IEeYdw/1

**Comment by firasdib** [comment]
Unable to repro, no feedback. Closing.
