### ISSUE TITLE
C# Match variable not exist

### ISSUE THREAD

**Issue by Edulynch** [firasdib/Regex101#770]
**C# Variable problem**

    Match match = Regex.Match(input, pattern, options);
    Console.WriteLine("'{0}' found at index {1}", m.Value, m.Index);

match != m
error "m" not exist.

**Comment by TWiStErRob** [comment]
Confirmed. This only happens when the `g` flag is not present.

Otherwise the loop variable is correct:
```
foreach (Match m in Regex.Matches(input, pattern))
    Console.WriteLine("'{0}' found at index {1}.", m.Value, m.Index);
```

I vote for changing the loop variable to `match`, instead of the single variable to `m`.
