### ISSUE TITLE
GitHub auth seems to be broken 

### ISSUE THREAD

**Issue by mjcramer** [firasdib/Regex101#771]
When I try to sign in using GitHub oauth, I get the following error message:

error=Grant%3A%20missing%20session%20or%20misconfigured%20provider

**Comment by firasdib** [comment]
Works fine for me. Can you reproduce in a incognito window?

**Comment by mjcramer** [comment]
Yeah, I tried that before and just tried it now and still no love. I do have another data point, though. I only have this problem with safari. Chrome works fine. 
<img width="1440" alt="screen shot 2017-01-26 at 11 05 26 am" src="https://cloud.githubusercontent.com/assets/3793335/22346475/1e613c64-e3b9-11e6-8a5d-a5152eb92838.png">

**Comment by mjcramer** [comment]
Safari: Version 10.0.2 (12602.3.12.0.1)
Chrome: Version 55.0.2883.95 (64-bit)

**Comment by firasdib** [comment]
I can't reproduce this, I believe its a caching issue of some sort. Feel free to reopen if you bump into it again.
