### ISSUE TITLE
POSIX flavor

### ISSUE THREAD

**Issue by vktec** [firasdib/Regex101#772]
A lot of people use sed, grep and other tools using POSIX BRE and ERE. For this reason, it would be very useful to have support for them.
ERE should be relatively easy, as it's a subset of most other regex implementations, but BRE's backslash escaping works differently, so that could be more of a challenge.

**Comment by edupo** [comment]
I also like that idea. Such a great regex tool would be even greater.

Great work!

**Comment by cheako** [comment]
Please close to avoid confusion.  Duplicate of #165

**Comment by vktec** [comment]
@cheako, thanks for pointing that out.
