### ISSUE TITLE
Only 1 match being returned

### ISSUE THREAD

**Issue by cyberpower678** [firasdib/Regex101#775]
It's only ever matching 1 item in the given text.  It used to match all matches, making it easier to see if the regex is working as intended.  Can this be fixed?

**Comment by TWiStErRob** [comment]
Do you have the Global flag on? Please provide a saved regex link.

**Comment by cyberpower678** [comment]
Oh whoops.  I'm used to using preg_match_all on php.  I forgot about adding the g flag.
