### ISSUE TITLE
JS code generation discrepancy

### ISSUE THREAD

**Issue by d10n** [firasdib/Regex101#777]
The editor result and the JS code generation output are different:
https://www.regex101.com/r/iitJAx/3
https://jsfiddle.net/nm3h2ed7/

**Comment by TWiStErRob** [comment]
JS doesn't have `$0` it should be `$&`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

@firasdib are you sure it's not worth flavorizing the replacements as well?

**Comment by firasdib** [comment]
I guess this boils down to https://github.com/firasdib/Regex101/issues/648

**Comment by firasdib** [comment]
Closing to reduce noise. Similar issues exist.
