### ISSUE TITLE
Support copy/paste in `s/foo/bar/gmx` format

### ISSUE THREAD

**Issue by nowox** [firasdib/Regex101#778]
I often work with perl regex in regex101 and I often copy/paste from the shell my regex for testing. 

Their format is usually `/foo/igx` or `s/foo/bar/x` or even `s@foo@bar@`. I would like to copy paste it into the interface. 

With the new interface, things are getting worse because I cannot simply paste `igx` anymore. I have to set independently each option from the drop down menu. So a regular copy paste cost me these steps: 

1. Select the *search* part, copy/paste it into the search bar
2. Select the *replace* part, copy/paste it into the replacement bar
3. Choose the delimiter if different from `/`
4. Add each option manually *e.g.* igx

Apart from this, regex101 is a wonderful tool that I almost use everyday.

**Comment by firasdib** [comment]
This works fine: http://giphy.com/gifs/l0Ex3xrRsOQacTRe0

**Comment by TWiStErRob** [comment]
Do you have the correct flavor selected BEFORE you paste? The flags not applicable to the current flavor cannot be selected, because they don't exist in the dropdown.

**Comment by nowox** [comment]
OMG! I just realize I never even tried to paste my regexes into the search field.
