### ISSUE TITLE
[Python] Unexpected unit test result when test string contains non-latin word characters

### ISSUE THREAD

**Issue by todofixthis** [firasdib/Regex101#780]
Example:
https://regex101.com/r/oB1aA6/9/tests

- Flavor: Python
- Regex: `^.+@[-\w]+(?:\.[-\w]+)+$`
- Flags: `gmu`

Unit test result:
```
given the string username@你好世界.com assert that regex does match
Expected regex to match, but did not.
```

Python 2.7.13 result:
```python
In [1]: import re

In [2]: regex = re.compile(ur'^.+@[-\w]+(?:\.[-\w]+)+$', re.M | re.U)

In [3]: regex.findall(u'username@你好世界.com')
Out[3]: [u'username@\u4f60\u597d\u4e16\u754c.com']
```

**Comment by TWiStErRob** [comment]
It all boils down to [`\w` not matching those Chinese characters](https://regex101.com/r/LTtwFs/1).

@firasdib As the explanation says `\w` means `[\p{L}\p{N}_]` which is `[\p{Letter}\p{Number}_]`, so these chars should be included. PCRE matches them with `\w` and can be confirmed that PCRE treats them as `\p{L}`. These chars are [in "CJK Unified Ideographs" 4E00-9FFF](http://stackoverflow.com/questions/1366068/whats-the-complete-range-for-chinese-characters-in-unicode). They're matched correctly if we use Python flavor with this regex: `[一-鿿]` or `[\u4e00-\u9fff]`.

See more at http://www.regular-expressions.info/unicode.html#category

**Comment by TWiStErRob** [comment]
Just for fun [here's a workaround for correct Unicode `\w` in Python](https://regex101.com/r/LTtwFs/2) (it works even if `u` flag is off) generated via Java 8:
```java
public static void main(String[] args) throws IOException {
	System.out.println(buildRangeRegex(gatherWordChars()));
}

private static String buildRangeRegex(char[] chars) {
	StringBuilder ranges = new StringBuilder();
	ranges.append("[");
	int start = chars[0];
	int last = start - 1; // pretend we're already in a range
	for (char c : chars) {
		if (last + 1 != c) {
			ranges.append(String.format(Locale.ROOT, "\\u%04x-\\u%04x", start, last));
			start = c;
		}
		last = c;
	}
	ranges.append("]");
	return ranges.toString();
}

private static char[] gatherWordChars() {
	StringBuilder sb = new StringBuilder(1).append(Character.MIN_VALUE);
	StringBuilder result = new StringBuilder();
	Matcher wordChar = Pattern.compile("\\w", Pattern.UNICODE_CHARACTER_CLASS).matcher(sb);
	for (char c = Character.MIN_VALUE; c < Character.MAX_VALUE; ++c) {
		sb.setCharAt(0, c); // mutable String with reused matcher (may not be safe, but works)
		if (wordChar.matches()) {
			result.append(c);
		}
	}
	return result.toString().toCharArray();
}
```

**Comment by firasdib** [comment]
It matches them with PCRE, so there is potentially a bug here. I'll look into it.
