### ISSUE TITLE
Python discrepancy in number of step

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#782]
https://regex101.com/r/yFHYtm/6

If you switch between pcre and python, the number of step is different, on the FAQ is says that python is implemented via PCRE, so I believe this is a bug

**Comment by firasdib** [comment]
This is a sideeffect of the implementation, not a bug.

**Comment by Ouims** [comment]
Ok, can you please explain this side effect and why it's affecting this situation?

**Comment by firasdib** [comment]
The regex is matched differently in python mode. There are a lot of internal things going on.

**Comment by Ouims** [comment]
Well I was hoping for more details but alright, thanks.
