### ISSUE TITLE
Try this exp

### ISSUE THREAD

**Issue by forenheith** [firasdib/Regex101#786]
https://regex101.com/r/R8cx44/1

**Comment by firasdib** [comment]
Yes, that is a terrible expression.

**Comment by forenheith** [comment]
It`s all you have to answer me? Howerver Microsoft Visual Studio (Resharper
regex tool) has eat this expression on the breakfast

2017-02-20 13:21 GMT+03:00 Firas Dib <notifications@github.com>:

**Comment by TWiStErRob** [comment]
@forenheith try stating what your actual problem is, we can't know what you find bad.

If it's the speed, remember that VS is running optiimized C++ code, and this is JavaScript

**Comment by forenheith** [comment]
Not speed. I have timeout when i trying find match, however sometimes this regexp works. Wtf?

**Comment by forenheith** [comment]
http://i.imgur.com/dC2gMiG.png

**Comment by firasdib** [comment]
Your expression is badly written which makes it really slow and your computer is not fast enough to calculate it in time.

**Comment by forenheith** [comment]
My laptop has i7 main processor and 16 Gb Ram man. It`s pretty simple regexp.

**Comment by firasdib** [comment]
Open the regex debugger and see.

**Comment by forenheith** [comment]
What can i see in debugger?

**Comment by firasdib** [comment]
You can see how your expression performs. If you do, you see it takes almost 500k steps just to find a match. You need to write a better expression instead.

**Comment by forenheith** [comment]
http://i.imgur.com/H8hat2W.png
14k only

**Comment by firasdib** [comment]
...add them all up. Those are all being performed.

**Comment by forenheith** [comment]
Better? May you trying better in this case?

**Comment by firasdib** [comment]
Try asking on IRC, there is a link in the left sidebar on the page.

**Comment by TWiStErRob** [comment]
There may be an easier solution to this (assuming @forenheith wants to keep this slow regex):
increase the timeout in regex101 settings (wrench in upper right corner).

@forenheith your laptop specs don't necessarily mean that they're being utilised, for example Chrome very likely executes JS on a single core (i.e. doesn't matter if you have 8). Another thing to be aware of is that even though you may have a powerhouse, if the laptop is unplugged it may downscale to preserve power, so you end up with an equivalent of a 5 year old machine.
