### ISSUE TITLE
www is broken

### ISSUE THREAD

**Issue by cauerego** [firasdib/Regex101#787]
https://www.regex101.com/r/jVvbXa/1 will never allow me to login while https://regex101.com/r/jVvbXa/1 works just fine

**Comment by firasdib** [comment]
Fixed

**Comment by cauerego** [comment]
while the www now redirects to the naked domain, which is great, now I can't actually log in with any! the sign thingie is gone. 👎

**Comment by firasdib** [comment]
https://regex101.com/account/all

**Comment by TWiStErRob** [comment]
> the sign thingie is gone. 👎

For those who may be looking for the login button:
![image](https://cloud.githubusercontent.com/assets/2906988/23824759/54ff2280-0674-11e7-9505-75e50ae80a47.png)
