### ISSUE TITLE
\b and \B is confused for cyrillic symbols

### ISSUE THREAD

**Issue by migs911** [firasdib/Regex101#788]
in pcre follow template `\Bтест` matches "тест" word in follow string "опять тест"
but `\bтест` has no match.
With English characters all the way around: `\btest` matches "test" word in "test again" and `\Btest` will not match anything.

**Comment by firasdib** [comment]
Can you post a permalink? Are you using the `u` flag?

**Comment by migs911** [comment]
https://regex101.com/r/CCmLmf/2
No, I'm not

**Comment by TWiStErRob** [comment]
You need to turn that on. See explanation on the right of regex101.

Try using the regex `\w` to see that non-ASCII won't be a word char, and hence cannot be a word boundary around it.

**Comment by firasdib** [comment]
Since it works correctly with the `u` flag this is not a bug
