### ISSUE TITLE
കൂടുതല്‍ <-- paste that in regex101.com

### ISSUE THREAD

**Issue by working-name** [firasdib/Regex101#789]
Hello there, it seems regex101 interprets the last letter as something with a bullet after it, which is not part of the [Malayalam range](http://jrgraphix.net/r/Unicode/0D00-0D7F). That last character should be `\x{0D7D}`

I tried it in Chrome, Firefox, Safari, on macOS 10.12.2.

Can someone reproduce this on other OSes as well?

**Comment by firasdib** [comment]
Please provide a permalink

**Comment by working-name** [comment]
[Here](https://regex101.com/r/1VjWZU/3) it is.

**Comment by firasdib** [comment]
Thats codemirror not able to parse the characters... odd

**Comment by working-name** [comment]
I think Malayalam is quite complex in terms of how many letters you can cluster together. I'm having trouble getting one of the characters identified on http://www.mclean.net.nz/ucf/ ... and I can't match it to anything in the alphabet myself. So maybe there isn't comprehensive support for all possible combinations in that alphabet.

**Comment by working-name** [comment]
`റ` <- that character (nothing to do with the site, just macOS in general) should look like this: ![odd cluster](https://bugout.regex.cf/odd-cluster.png)
but it's being matched by `\x{0d28}` which should be `ന`. 
![codepoint matches the whole cluster](https://bugout.regex.cf/codepoint-matching-whole-cluster.png)

**Comment by working-name** [comment]
Same string as above, but in Sublime. It un-clusters the characters, which reveals that regex101.com is correct in matching that last "letter", since it's a cluster of multiple letters, `\x{0d28}` included.

![sublime splits it into 4](https://bugout.regex.cf/sublime.png)

So we should be good there in terms of what the site does, however the bullet point that codemirror spits out is still the issue.

**Comment by TWiStErRob** [comment]
If you look at the DOM created after paste you'll see this:
![image](https://cloud.githubusercontent.com/assets/2906988/23236062/baa3e95e-f94f-11e6-8fca-f09043be829f.png)
If you look at the wiki of ZWJ, it has exactly your example: https://en.wikipedia.org/wiki/Zero-width_joiner#Examples

When I pasted your title string into Sublime I noticed something: it was shown as "ല ്" but when you move the cursor, there's one more invisible character after  ് which is the ZWJ that CodeMirror cannot handle. You can only notice if you move the cursor via keyboard.

I think this needs to be reported to CodeMirror, i.e. paste the same string into http://codemirror.net

**Comment by firasdib** [comment]
Seeing as how this is a codemirror bug, I don't think its worth keeping this issue open. When they release codemirror 6 we can revisit this.
