### ISSUE TITLE
Wrong match number in hover

### ISSUE THREAD

**Issue by OmgImAlexis** [firasdib/Regex101#790]
Using `/(?!^)[1,2]\d{3}/` with javascript and the g flag I get 2 matches for this.

```
2001
1994
2020
```

On the hover dialog for the matches I see match 2 for 1994 and match 3 for 2020 yet in the right sidebar it shows this.
![screen shot 2017-02-25 at 4 20 22 pm](https://cloud.githubusercontent.com/assets/6525926/23328635/4d132728-fb76-11e6-963a-1b7bf3e52e0d.png)

**Comment by TWiStErRob** [comment]
Huh, that's interesting:
![image](https://cloud.githubusercontent.com/assets/2906988/23332590/3c1de19e-fb74-11e6-8f27-d93ebd8fd2b5.png)

Here's a saved version: https://regex101.com/r/YBIN14/1

@firasdib PCRE shows the correct match #.
