### ISSUE TITLE
Allow export of just captured groups (and not entire matches)

### ISSUE THREAD

**Issue by ryancwalsh** [firasdib/Regex101#792]
It would be _great_ if this tool allowed the export (in json, csv, and plain text) of just the captured groups without the full match results.

**Comment by TWiStErRob** [comment]
It should be fairly easy to ignore (post-process the CSV file).
I don't think there's a way to meet everyone's requirements, you have to adapt to what's available.

There's also an option to generate your own output, for example https://regex101.com/r/CteECm/1

**Comment by ryancwalsh** [comment]
Thanks!

**Comment by NabiKAZ** [comment]
Thanks but not enough, Must disable showing full match in the export.

**Comment by NabiKAZ** [comment]
@Doqnach I expanded it in #1062 #1063
