### ISSUE TITLE
Unit test: fill text with test string (if singleline) rather than unspecified unit test  if nothing is provided.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#794]
Provides a bit more context

**Comment by TWiStErRob** [comment]
Can you screenshot?

**Comment by Zarthus** [comment]
Not at the moment, I'm merely suggesting that re101 fills the title with
something useful instead of unspecified unit test when  you omit the title.

**Comment by TWiStErRob** [comment]
Ah, I see:
![image](https://cloud.githubusercontent.com/assets/2906988/23567655/3aa4873e-004f-11e7-82c6-5f815330758d.png)

**Comment by firasdib** [comment]
Done
