### ISSUE TITLE
Use target=_blank for the top-right links.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#796]
So you don't accidentally leave regex101 when you don't want to.

**Comment by firasdib** [comment]
I'm not a fan of this personally, but I can be convinced of otherwise.

**Comment by Doqnach** [comment]
Agree with @Zarthus here. During the XHTML 1.0 era it was deemed that web developers should not decide for users if they wanted to open the link in the same or a new window. It should be left up to the user to click (same window) or SHIFT-click/middle-click (new window/tab).
Later with HTML5 the use of target="_blank" seems to have made a full comeback.

I feel https://css-tricks.com/use-target_blank/ is a good resource on reasoning to use target="_blank" or not.

**Comment by firasdib** [comment]
@Doqnach That article large seems to argue to not use `_blank`

**Comment by Zarthus** [comment]
It suggests good and bad reasonings to use it, and one of it is "A Good Reason: The user is working on something on the page, that might be lost if the current page changed."

**Comment by firasdib** [comment]
@Zarthus and thats why they have the "are you sure you want to leave" dialog

**Comment by Doqnach** [comment]
@firasdib indeed, the article brings good points for many situations to not use it. 

As I said I agree with @Zarthus in this though and find that "The user is working on something on the page, that might be lost if the current page changed." would qualify here to use target="_blank" in this case. Regardless of the "are you sure?" dialog. That dialog prevents you from opening the link by clicking on it normally if you don't want to leave the page itself. The user will have to explicitly ctrl-click/shift-click/middle-click/right-click the link to open it in a new tab/window.

Could always A-B test it to see if more people will follow the link with target="_blank" or without ;-]

**Comment by Zarthus** [comment]
An alternative route is to make it a [regex101/settings](https://regex101.com/settings) option for people who prefer their links with target="_blank". Sure, it's uncommon, but I've always been a fan of giving people the choice. I personally notice myself still getting the warning dialog often (partially because I assume it is a _blank link.)

To each their own of course, it wouldn't hurt just rolling it out for a while and seeing if people have feedback on it.

**Comment by firasdib** [comment]
Its been a while, and I don't think this is going to happen. Sorry :)
