### ISSUE TITLE
Unit Testing text too small

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#797]
The text for unit tests should be a bit bigger.

![img](https://i.imgur.com/4hCAIWE.png)

**Comment by TWiStErRob** [comment]
what if the string and the assertion are both long?

**Comment by Zarthus** [comment]
String truncation? I'd rather be able to read some of it than none of it.

**Comment by TWiStErRob** [comment]
relax, it's just something for firas to consider

**Comment by firasdib** [comment]
The text will automatically truncate as needed. The size of the text can be adjusted, but we need to ensure it doesn't blow the box up too much
