### ISSUE TITLE
Run Test for unit testing modal

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#799]
Run the test separately to test if it works as expected.

Something like this:

![img](https://i.imgur.com/ziS80XZ.png)

**Comment by firasdib** [comment]
There is no obvious facility to show the result of the test and implementing something to do so seems excessive right now. Having a hard time with this one :-)

**Comment by Zarthus** [comment]
Could make the button (or the modal) green or red depending on the result. Would that work?

**Comment by firasdib** [comment]
But then you'd want to know why it failed, right? `Expected "foo" but got "bar"`

**Comment by Zarthus** [comment]
Ideally - yes. But it's still an upgrade from the existing situation to just give it a proper colour. If the test is green it at least confirms your test works, if it's red you might still need to add it and experiment a bit better.

It doesn't have to be perfect from the start; as it is this issue is already rather low priority (quality of life changes), but it would significantly help with writing tests.

**Comment by firasdib** [comment]
I think there is a better solution somewhere. I'll leave this hanging for now and we'll see what I can come up with.

**Comment by TWiStErRob** [comment]
There's a large area next to the button, the "Expected but got" text could go there.

**Comment by firasdib** [comment]
Depends on screen size, of course. Nothing you can count on always.

**Comment by TWiStErRob** [comment]
Oh, true that, I didn't resize it. I'm wondering how can anyone use the app if it's 2 inches wide though ;)
