### ISSUE TITLE
Suggestion: Increase unit test details legibility

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#800]
The text is currently illegibly small on Chrome, 100%.

![image](https://cloud.githubusercontent.com/assets/6157073/23825020/21373e64-067a-11e7-96d7-6340bb6f78e3.png)

**Comment by firasdib** [comment]
Whats wrong with your font?

**Comment by chrisjj** [comment]
Nothing that I know of.

![image](https://cloud.githubusercontent.com/assets/6157073/23825070/c4761244-067a-11e7-8c4f-e5e60f85bd1b.png)

**Comment by firasdib** [comment]
Everything is rendered in terrible quality. I think you have turned off something in your settings. I assume this is windows?

**Comment by firasdib** [comment]
Closing this in favor of https://github.com/firasdib/Regex101/issues/797

**Comment by chrisjj** [comment]
> Everything is rendered in terrible quality.

All looks fine to me except the line in question.

> I think you have turned off something in your settings. I assume this is windows?

Correct.

**Comment by TWiStErRob** [comment]
What did you turn off?

@firasdib I'm on Windows 10 too, for me it looks ok, and I see now why Jos was complaining about the size:
![image](https://cloud.githubusercontent.com/assets/2906988/23825127/ccf3328e-067b-11e7-8d3e-5a8793c2201d.png)

**Comment by chrisjj** [comment]
> What did you turn off?
>
Nothing I recall. How can I find out?

**Comment by firasdib** [comment]
Try this http://stackoverflow.com/questions/37301132/chrome-overall-font-rendering-issue-2016

**Comment by chrisjj** [comment]
Thanks, but I'll pass. I don't have "the problem of very bad font rendering
in Google Chrome". I just have a problem with one Regex101 line. And I
don't want to mess with setting that might cause more.

**Comment by TWiStErRob** [comment]
Your choice, but I suggest you compare the screenshot that you made and what I made and notice the pixelation on yours even in your Developer Tools HTML/CSS area. Also notice that your Developer Tools tabs (Elements, Console, etc) texts and webpage tab text are nice and smooth.

**Comment by firasdib** [comment]
Everything on your screenshot looks terrible.

**Comment by TWiStErRob** [comment]
@firasdib he may be used to it, as you're used to your hiDPI ;)

@chrisjj btw, the font size for the test details has been increased on the live site

**Comment by chrisjj** [comment]
On 12 March 2017 at 13:26, Firas Dib <notifications@github.com> wrote:

> Everything on your screenshot looks terrible.


The only item illegible to me is the one I reported.

--
Chris

**Comment by TWiStErRob** [comment]
The others are not illegible, just pixelated, please open the two screenshots with dev tools in this issue, side by side.

**Comment by chrisjj** [comment]
You may pixellated as a problem. I see only illegible as a problem.

--
Chris
