### ISSUE TITLE
Account page does not show which account is signed in

### ISSUE THREAD

**Issue by Doqnach** [firasdib/Regex101#802]
When you are signed in, the account page has no indicator which account is currently used to sign-in.

I suggest a "Profile" page in the 'inner-menu' above "sign-out" that shows some details. Optionally in the form of a small dashboard type view?

**Comment by OnlineCop** [comment]
What; like a Gravatar image or something similar?

**Comment by firasdib** [comment]
This ties in closely with #801

**Comment by firasdib** [comment]
This has been implemented
