### ISSUE TITLE
Simplify ADD TAG field

### ISSUE THREAD

**Issue by lucamauri** [firasdib/Regex101#804]
In the _save regex_ window, please simplify the ADD TAG field. Instead of adding a tag at a time, allow multiple insertion separated either by space or comma.
Thanks

**Comment by firasdib** [comment]
Would it be enough to bind the enter key to add a tag? This would allow for tags with any characters (spaces, commas, etc)

**Comment by JMichaelTX** [comment]
> Would it be enough to bind the enter key to add a tag?

Yes.  That would be great.  Currently it is a PITA to have to mouse way over to click on the "Add Tag" button.

**Comment by bmix** [comment]
What about all tags, the user already has in use, in a pane, to choose from by clicking? And/or auto-complete.

**Comment by firasdib** [comment]
@bmix Missed that comment. Its a great idea, but a bit of extra work. The feature is quite rudimentary. The website currently allows you to add tags by hitting enter at least.
