### ISSUE TITLE
Thank you SO much for this app!!

### ISSUE THREAD

**Issue by pati610** [firasdib/Regex101#805]
It is a true lifesaver!

Best Regards,
Patrick

**Comment by pati610** [comment]
I just noticed that donations were possible, so I went ahead and contributed. Keep up the good work!

**Comment by TWiStErRob** [comment]
you're not alone: #768

**Comment by Zarthus** [comment]
I'm closing this issue in favour of comments on #768, so we don't needlessly clutter the issue repository with a bunch of open issues :)

I'll direct @firasdib here considering you donated (you're awesome!)
