### ISSUE TITLE
Anchors don't work

### ISSUE THREAD

**Issue by dwrz** [firasdib/Regex101#810]
Anchors don't seem to be working for me. They work on this site: http://scriptular.com/, but not regex101.

I'm trying to run this expression:
^1?\s?((?\d{3})?)(\s|-)?(\d{3})(\s|-)?(\d{4})$

I get no matches for these strings:
555-555-5555
(555)555-5555
(555) 555-5555

Even though they match on scriptular.

Not sure if it matters, but I'm on Linux + Chromium.

**Comment by firasdib** [comment]
This repo is for regex101.com

**Comment by firasdib** [comment]
Fyi, you'd need the `m` flag.
