### ISSUE TITLE
Check for multiple matches in unit test

### ISSUE THREAD

**Issue by spleiner** [firasdib/Regex101#812]
For one of my unit tests I have 3 matches in a string and I would like the test to check for either the number of matches in capture group 1 (to make sure I have 3 matches and nothing else) or have the ability to specify the different values that would indicate a successful/passed test, (for example 43, 23, and 39) (In this case the matches 43 and 23 but not 39 would fail the test, and matches of all three but also any additional matches would also fail the test)

This ability would make it very easy to perform otherwise complex tests to make sure all expected matches are caught and not any matches that are not expected to be caught.

Other than that, Regex101 is excellent! :-)

**Comment by firasdib** [comment]
There is no support for doing what you're asking for. You'll have to create three separate tests with the same input string but with different capture group validations.
