### ISSUE TITLE
codegen: BRE/ERE codegen support

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#815]
#772

**Comment by firasdib** [comment]
Can you write it?

**Comment by Zarthus** [comment]
Someone still needs to write https://github.com/firasdib/Regex101/wiki/Writing-a-Code-Generator before the community can start contributing Code Generators.

**Comment by firasdib** [comment]
@Zarthus done

**Comment by firasdib** [comment]
Whoever requested this does not seem to want it enough. Closing.
