### ISSUE TITLE
Code generator for PHP ( error )

### ISSUE THREAD

**Issue by smile1980** [firasdib/Regex101#830]
If don't use global option regexp then code generator generic this code:
preg_match($re, $str, $matches, PREG_SET_ORDER, 0);

Error:  function preg_match not accept flag PREG_SET_ORDER

**Comment by Zarthus** [comment]
Yep!

Per http://php.net/manual/en/pcre.constants.php,  `PREG_SET_ORDER` only exists in `preg_match_all()`.
```php
$re = '/abc/';
$str = 'abc';

preg_match($re, $str, $matches, PREG_SET_ORDER, 0);

// Print the entire match result
var_dump($matches);
```

Is invalid, which is what the code generator generates without `g` flag.

Raising the following error:
```
PHP Warning:  preg_match(): Invalid flags specified in Command line code on line 1
```

Whereas it works fine in `preg_match_all`
