### ISSUE TITLE
QUESTION: It's possible to send content to regex101.com directly through GET?

### ISSUE THREAD

**Issue by phenixiim** [firasdib/Regex101#831]
Hi all, thanks for such a great tool! I just want to ask, if there is some possibility to call fox example 
https://regex101.com?regexp=something&text=something and it will fulfill the form for me? 

Thanks a lot!

**Comment by firasdib** [comment]
No, there is no support for this. This is everything you can do: https://github.com/firasdib/Regex101/wiki/API

**Comment by phenixiim** [comment]
What a pitty, thanks again for such a great tool!

**Comment by Zarthus** [comment]
Implemented  (see https://github.com/firasdib/Regex101/issues/872#issuecomment-310917106)
