### ISSUE TITLE
"save regex" broken

### ISSUE THREAD

**Issue by wfaulk** [firasdib/Regex101#833]
I'm consistently getting feedback saying "There was an error trying to save your regex. Please try again later."

**Comment by firasdib** [comment]
Would you mind checking to see what it says in your console?

**Comment by wfaulk** [comment]
Upon loading the page:
> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create main.js:2930:93

Upon entering the regex
> : Successfully compiled asm.js code (loaded from cache in 11ms) pcrelib.js

Nothing after that, including when I click the "save regex" link.

I've just noticed that it works in Chrome.  I'm seeing this problem in Firefox.

I did just notice that I'm getting a 429 HTTP response from "sentry.io".  I don't know if that's related or not.  I don't see any request to "sentry.io" when using Chrome.

**Comment by wfaulk** [comment]
Oh, I'm also seeing that the response from /api/regex is zero-length, despite its Content-Length being 105.

**Comment by wfaulk** [comment]
I just created an empty Firefox profile and it works from there.  There must be an extension that is causing this problem.  I'll see if I can narrow down what it is.

**Comment by wfaulk** [comment]
Conflict is with LastPass: Free Password Manager v4.1.44a

**Comment by firasdib** [comment]
Do you have more info on why this happens?

**Comment by wfaulk** [comment]
I do not have any more info.  At this point, I would assume that there is some conflict between regex101's javascript and the javascript that LastPass injects into the page.

I was able to duplicate the problem merely by installing the extension (from [here](https://www.lastpass.com/?lpInstall)) on a blank Firefox profile.  I didn't have to create or log into a LastPass account at all.

**Comment by firasdib** [comment]
Could you please look at the networks tab while this issue happens and tell me exactly what is returned? If there is an error on my end, you'll get an error id.

**Comment by wfaulk** [comment]
Sigh.  It works now.  It looks like LastPass was updated to 4.1.45a, so maybe this was all on their end.  Their [release notes](https://lastpass.com/upgrade.php?fromwebsite=1&releasenotes=1) don't include information about this update.
