### ISSUE TITLE
Please Do NOT Erase Data when Signing In

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#834]
###

This is very counter-intuitive.  I don't know of any other web site that behaves like this.
Please fix this ASAP so that we do NOT loose our data when we sign in.
Thanks.

![image](https://cloud.githubusercontent.com/assets/11052885/24730261/41fd550e-1a28-11e7-9d9d-dd23fa538d59.png)

**Comment by firasdib** [comment]
Quite normal, is it not?

**Comment by JMichaelTX** [comment]
> Quite normal, is it not?

I don't understand what you are saying.
Whether it is "normal" or not, it is a royal PITA the way it is.
Could you please change it as I requested?

Thanks.

**Comment by TWiStErRob** [comment]
@JMichaelTX if it was that easy it would be already like that...
I think by "normal" he means that most sites lose context as soon as you log in, some can't even redirect back to the page you were looking at.

@firasdib that said, could it be an easy impl to save the regex before login and associate/open it after logged in?

**Comment by JMichaelTX** [comment]
> if it was that easy it would be already like that...
> I think by "normal" he means that most sites lose context as soon as you log in, some can't even redirect back to the page you were looking at.

We clearly have different experiences.  Every site I know of that has a shopping cart always saves the cart even if you are not signed in.  Then, when you do sign in it associates that cart with your account.

> could it be an easy impl to save the regex before login and associate/open it after logged in?

This seems like a reasonable approach to me.  You already know how to save a snippet, so all you have to do is save it in a temp area and reload it after log in.  Is it really that hard?

Another approach is to make the auto-log in last for very long periods of time, say at least 6 months.  And if it has expired, then prompt the user to relog in when the page is first loaded.

Finally, when the user saves a snippet and is not logged in, can't you ask right then if they want to log in?

Oh, one more.  If I save a snippet while not logged in, after I log in why can't I just give you the URL of the saved snippet, and you then associate it with my account?

Seems like lots of choices to help you users avoid losing data.

Thanks.  I want you to know that I love your tool, the RegEx part.  It is the snippet management part that causes me so much pain.  Keep up the good work.

**Comment by firasdib** [comment]
For this to work we would have to either save the current scope into `localStorage` (or something similar) and then fetch it again when the app has reloaded, or save it and associate it with the current account. 

The first option requires some work and needs to be defined in more detail, while I'm not sure the latter is always desired.

**Comment by JMichaelTX** [comment]
> The first option requires some work and needs to be defined in more detail,

OK, thanks for considering this update.  I assume that the "needs to be defined in more detail" is an action that only you can do.  If there is something you need from me, please let me know.

**Comment by Ouims** [comment]
@firasdib ever looked at this is more detail since 2017? It's really not desired this behavior!

**Comment by firasdib** [comment]
This is implemented and will be pushed live in the coming days.

The contents of the regex area (regex, test string, flags, etc) will be saved temporarily and restored once you return to the website.

**Comment by ApolloBiz** [comment]
> This is implemented and will be pushed live in the coming days.

@firasdib , thanks for the update.  Could you please post here when you have released this update, so that we can test and confirm it is working?

**Comment by firasdib** [comment]
@ApolloBiz I'll try to remember :)

**Comment by firasdib** [comment]
The change is live, please try it out.
