### ISSUE TITLE
error not working correctly for this regex

### ISSUE THREAD

**Issue by somnath157** [firasdib/Regex101#836]
my regex `^[a-zA-Z][\w]{7,29}$` for a username is right but its not matching any string for eg. shivam_shain, somu_123  or any other username

**Comment by Doqnach** [comment]
@somnath157 do you have a link to a saved regex to demonstrate this problem? Do you have a test string consisting out of multiple usernames on separate lines, but forgot to specify "Multi line"? (m flag)

**Comment by firasdib** [comment]
Closing due to no feedback
