### ISSUE TITLE
Pythonic code generator

### ISSUE THREAD

**Issue by zhongdai** [firasdib/Regex101#837]
I have noticed following code from the `code generator` tab

```python
for matchNum, match in enumerate(matches):
    matchNum = matchNum + 1
```

Shall we change it to
```python
for matchNum, match in enumerate(matches, start=1):
```

**Comment by firasdib** [comment]
I'm fine with either. I'll let the python fanatics decide.

**Comment by TWiStErRob** [comment]
Even though I'm not a Python dev, I support this. It's more clear what's going on.

I have a lot of C-like language backgrounds and there if you touch (reassign) the loop counter you get weird behavior: for example the `i++` we have here would make the loop iterate every second value, and I was surprised to read that it doesn't.

So I think for clarity, tutorial and best practice purposes, using the built-in syntax to achieve this is better.

**Comment by firasdib** [comment]
Fixed.
