### ISSUE TITLE
Speed of Python version on website

### ISSUE THREAD

**Issue by MalikRumi** [firasdib/Regex101#839]
This is really more of a question than an issue. I was surprised at the speed of the regex101 using Python. (To be fair, its a big project with large blocks of text.) I did some searching and learned a lot about Python and implementations and NFA and all that. I just use your site to calculate the right regex to use. So I just wanted to ask if there anything about the way you make python work on this site that would make it slower than it would be in an interpreter? Thanks. It is a great tool.

**Comment by TWiStErRob** [comment]
Have you read https://github.com/firasdib/Regex101/wiki/FAQ#how-close-does-regex101-emulates-the-engines?

**Comment by Zarthus** [comment]
No response, closing as resolved.
