### ISSUE TITLE
Add support for Go language flavor RE2

### ISSUE THREAD

**Issue by tommynyquist** [firasdib/Regex101#84]
I would love support for Go language regexp. It should be quite similar to what you already have implemented. See http://golang.org/pkg/regexp/ for details.

**Comment by avelino** [comment]
+1

**Comment by guilhermebr** [comment]
+1

**Comment by RobinGertenbach** [comment]
Does [this](https://github.com/uhop/node-re2) help regarding the javascript issue?

**Comment by firasdib** [comment]
@RobinGertenbach If it can be run in the browser it helps :-)

**Comment by ingenthr** [comment]
+1

**Comment by victorhaggqvist** [comment]
@firasdib For what it's worth, I have had pretty good luck with https://github.com/gopherjs/gopherjs in my small test for fun, though never tried regex any stuff using it.

**Comment by firasdib** [comment]
@victorhaggqvist Thanks for the tip. But from the looks of it, that seems to "translate" GO to JS, and not really cross-compile, or am I wrong? Because I believe it will just use the JS regex engine.

**Comment by Xackery** [comment]
Regexp (go package) notes it's using RE2, which from my quick research the closest thing javascript is https://github.com/uhop/node-re2 I don't see any native RE2 support for javascript browser, just that nodejs version. Wrappers of Google's RE2 standard is noted on the readme bottom: https://github.com/google/re2

**Comment by victorhaggqvist** [comment]
@firasdib That might very well be true, since some things are build in to the JS equivalent native code. Though, made a quick test just now, and from what I can tell it might actually be compiling the regex engine to JS as well. Here is my test and the compiled js https://gist.github.com/victorhaggqvist/0c780080c0c46cbd592e8ca712135678

**Comment by firasdib** [comment]
@victorhaggqvist Maybe I was being a bit too pessimistic 😄. If it compiles the actual engine that is totally something I can go ahead and use. If not, perhaps using what @Xackery proposed is a viable solution? If GO uses re2, and re2 is written in C, I can cross-compile it easily and run it in the browser no-problemo. Would you mind joining slack so we can have a chat about it at another time? Perhaps you'd like to help me implement the Go language (as I know nothing about it)?

**Comment by victorhaggqvist** [comment]
@firasdib I could possibly help out, tough not at the moment, possibly later this summer. If I can get access to the code, since it don't appear to live in this repo, I can start poke around when I have some time over.

**Comment by firasdib** [comment]
@victorhaggqvist I can add you on slack so we can have a chat. I have added an experimental version of golang for the new version of the site, but it still needs some work.

**Comment by firasdib** [comment]
You might be happy to know that I have now implemented golang throughout the app and it will be available in the new version! Rejoice! 😄
