### ISSUE TITLE
Feature Request: explanation pane for substitution

### ISSUE THREAD

**Issue by Doqnach** [firasdib/Regex101#840]
Just popped in my head when I saw a regex linked with a substitution using special ("custom") properties:

You can already hover over the individual tokens in the substitution replacement value, but what about an explanation window similar to that of the 'regular expression'?

Unsure how to do this in the UI without causing clutter though... Since the Explanation pane already lets you fold the 'regular expression' explanation, maybe just add it underneath? Could use some way to indicate it's existing to the user though.

**Comment by TWiStErRob** [comment]
I think changing the placeholder "An explanation of your regex will be automatically generated as you type." to include "regex and substitution" should be enough.

**Comment by firasdib** [comment]
I think the substitution pane is simple enough to not require it. There is no nesting or complicated tokens, and the quickref contains the information to cover all of it.
