### ISSUE TITLE
Visual group bug

### ISSUE THREAD

**Issue by grigoreme** [firasdib/Regex101#841]
https://regex101.com/r/umjoXR/2
If you see regexp show all the link as same group but regexp divide in two. So the left panel shows 2 groups, while visual is only one. Hope you understood me.
P.S. Sorry for bad english.

**Comment by degant** [comment]
By visual is only one, do you mean the 'Test String' text area? That it doesn't indicate the groups in separate colors? Or do you mean something else?

I think for the Javascript flavor the 'Test String' area doesn't highlight groups specifically. Change your flavor to PCRE and you'll see the test strings have highlighting based on groups.

**Comment by grigoreme** [comment]
This what i mean: `By visual is only one, do you mean the 'Test String' text area? That it doesn't indicate the groups in separate colors`.

**Comment by Doqnach** [comment]
The javascript regex engine does not support this because it can't report back on positions.

If this is essential, switch to PCRE for the colours and back to JavaScript to verify the regex also works in that flavour before saving.
