### ISSUE TITLE
Suggestion: How about adding Perl and C# regular expression also

### ISSUE THREAD

**Issue by skd123us** [firasdib/Regex101#842]
This is one of the best regex tester I have seen. Few suggestions:

1. Regular expression for Perl and C#
2. String replacements (it might be already there, I haven't studied throughly)

**Comment by Doqnach** [comment]
1. Perl uses PCRE so that is already there.
2. String replacements is there, see the 'Substitution' pane below the 'test string' pane.

**Comment by TWiStErRob** [comment]
Also subscribe to #156 for C# flavor.
(You can already generate code for C#, though the regex may not compile/throw in .NET or behave differently.)

Thanks for the feedback!
