### ISSUE TITLE
Step by step debugger

### ISSUE THREAD

**Issue by TZubiri** [firasdib/Regex101#844]
There's a couple of features a live debugger could have that would really help with debugging:

Basic step button which advances the regex by one step.
At each step, the state of the regex is represented by a caret in the regex box and another caret in the test string box.
Breakpoints and continue button: A breakpoint can be placed on either the regex box or the test string box.
The continue button runs until the regex reaches a breakpoint in either box.

**Comment by kanaikimi** [comment]
Whilst this be an amazing feature, with the existence of the analytic tree on the right, there may be poor ratio of user value to development time for this feature.

**Comment by firasdib** [comment]
Have you looked at the existing debugger? Its not as interactive though.

**Comment by firasdib** [comment]
Closing due to no feedback.
