### ISSUE TITLE
Specific string not matching

### ISSUE THREAD

**Issue by kevinwoodward** [firasdib/Regex101#845]
For the expression : (00+)|(100+)|(0+10+)|(00+1)

The string 001 (or 2+ 0's followed by a 1) doesn't match

**Comment by firasdib** [comment]
Can you post a permalink?

**Comment by TWiStErRob** [comment]
@firasdib https://regex101.com/r/LQ1SNP/1, notice that the match is only `00`, it doesn't include `1`, however the last alternative would match that.

@kevinwoodward I think you could re-order your alternatives to set priorities between ambiguities:
`(0+10+)|(00+1)|(00+)|(100+)`
Also consider using more of the regex language: e.g. collapsing the middle two groups:
`(0+10+)|(00+1?)|(100+)`

@firasdib any better advice than this?

**Comment by firasdib** [comment]
No thats the way it works. He'll have to order his groups better.
