### ISSUE TITLE
Add flavour "egrep"

### ISSUE THREAD

**Issue by chrisblech** [firasdib/Regex101#846]
I use you great tool to design/test rules for the unix-tool "[logcheck](http://logcheck.org)", which uses internally unix command "[egrep](https://wiki.ubuntuusers.de/grep/)".
Most times I achive best results using your flavour "golang", but it seems not to be exact the same. For example, the shortcut `\d` will not be accepted/translated by unix egrep.

So could you please implement the flavour "egrep" natively in your tool ?

**Comment by Zarthus** [comment]
Duplicate of https://github.com/firasdib/Regex101/issues/165? Is egrep different from posix-extended?

**Comment by cheako** [comment]
Please close to avoid confusion.
