### ISSUE TITLE
Multi-line regex can match across lines in a technically correct but confusing fashion

### ISSUE THREAD

**Issue by dom-devel** [firasdib/Regex101#847]
Currently I use multi-line mode, if I'm testing regex for matching multiple URLs.

Most of the time this is no problem, however because new lines aren't possible in URLs, you can occasionally come across problems like this:

https://regex101.com/r/2xGq4w/1

I'm trying to match any URLs which fit in the 3rd or 4th sub-folders. The problem is the last two lines, because new lines aren't possible in URLs, I haven't excluded them as a possible character match, and so the regex proceeds to match the newline as well and matches the last two lines.

I often use regex101 as a place to create and save example regexes, for teaching people URL matching regex, but this one presents a problem, because I would have to write regex differently for regex101 than I would in a program where I'm using it to select URLs, (like Google Analytics for example).

Would it be possible to create a flag for this particular use case, where it wasn't possible to match across multiple lines?

**Comment by Doqnach** [comment]
You can either modify your regex to deal with the problem: https://regex101.com/r/2xGq4w/2

Or wait for wait for the resolution of #795.
