### ISSUE TITLE
Unit tests not showing up on link when uploaded to library

### ISSUE THREAD

**Issue by angularsen** [firasdib/Regex101#850]
1. Anonymous / not logged in: Create new regex with unit tests, copy URL
2. Create account, then visit URL
3. Upload regex (created anonymously) to account's library, copy new URL

Expected: New URL (library regex) has tests
Actual: No tests

Bonus: Tried manually adding tests to the library regex URL from account, but still not showing up when viewing same URL anonymously. Also tried "Update regex" to get a version2, but anonymous browser still does not see the tests on version2.

Anonymous URL: https://regex101.com/r/EMLIwt/1/tests
Library URL: https://regex101.com/r/F5wWrl/2/tests

**Comment by firasdib** [comment]
Fixed in next release.
