### ISSUE TITLE
Quantifier - tester doesnt show any error

### ISSUE THREAD

**Issue by DanielSanIT** [firasdib/Regex101#851]
`^\s*[a-zA-Zа-яА-Я]{2,100}+`

`{2,100}+` - wrong expression, VBScript.RegExp return Error Code 800A139A. Online tester doesnt show any error.

**Comment by TWiStErRob** [comment]
`{}+` is a possessive quantifier, which is not supported by VBScript: http://www.regular-expressions.info/vbscript.html add `()` around what you want to repeat if you wanted to express that.

**Comment by DanielSanIT** [comment]
I dont want to express that. It's just my fault. Maybe good idea add Flavor VBScript.

**Comment by TWiStErRob** [comment]
you mean #723? ;)
