### ISSUE TITLE
New identity = new account, even though there's already one with the same email address

### ISSUE THREAD

**Issue by jeremejevs** [firasdib/Regex101#852]
Originally, my account was made using GitHub auth. Then, today, I've logged in with Google, and it took me a bit to understand why all my saved expressions are missing. It appears that logging in with different identity providers, though with the same email address, results in distinct accounts being created. This is bad UX, in my opinion, and you should consider changing it.

**Comment by firasdib** [comment]
I can agree its confusing, but the only other solution would be to create an account on the my server, which I'm no fan of either...

**Comment by jeremejevs** [comment]
Ah, so you're using identities directly, as users?

**Comment by firasdib** [comment]
Yes, you could say that. Thats why there is just a sign on without an extra step of account creation (since I don't want to have to deal with that stuff).

**Comment by jeremejevs** [comment]
Okay, this is a "won't fix" then 🙂 Thanks for a quick response.

**Comment by firasdib** [comment]
Sorry to disappoint!

**Comment by jeremejevs** [comment]
No worries, it's a small thing; thanks for making this tool!
