### ISSUE TITLE
[Feature Request] upload example to ideone.com

### ISSUE THREAD

**Issue by Doqnach** [firasdib/Regex101#854]
Been seeing some people linking ideone.com as a sandbox website for showing example code.

I wonder if the company that runs ideone.com (http://sphere-research.com/) would be interested in partnering, providing an API to post the 'code generator' examples up on their platform (on request by the user).

That way interactive code examples could be provided to the end-user.

Their tool is also mobile-friendly so that is a big plus too.

**Comment by firasdib** [comment]
That could be cool. Do you want to reach out to them and link them to this issue?

**Comment by Doqnach** [comment]
I'm fine with doing that. Want to be in the CC? (what address)

**Comment by firasdib** [comment]
contact@regex101.com will suffice

**Comment by firasdib** [comment]
Nothing has progressed here. Closing for now.
