### ISSUE TITLE
Update a revision after the regex has been deleted

### ISSUE THREAD

**Issue by OnlineCop** [firasdib/Regex101#855]
Create and save a regex. You should have a Delete link.
Open the same page in a new tab. It should not have a Delete link. Add a few more revisions/changes and save, if you want.
On the first tab, use the Delete link and delete the regex.
On the second tab, make a change and save again.

When saved in the 2nd browser tab, the revision resets down to /1 but reuses the same regex URL/path. It shows a Delete link on this page, but clicking it does not delete the page. It cleared the page, but revisiting the same URL brought up the changes saved in the 2nd browser tab. It appears that this is un-deletable.

https://regex101.com/r/8h8AUR/1 <-- the sample used while creating this ticket.

Suggested fix: If the original link is deleted, saving should act like a fork and give the user a new URL, along with its own Delete link. That way, it can be deleted as well.

**Comment by firasdib** [comment]
This is indeed a bug. I'll fix it.
