### ISSUE TITLE
11|((1|0)(1|0)(1|0)*)

### ISSUE THREAD

**Issue by sevku** [firasdib/Regex101#856]
this regex should match "111" but it only matches 11

**Comment by OnlineCop** [comment]
https://regex101.com/r/0LaArP/1 shows that '111' only matches the '[11]1' portion, but this is because in the regex, the `/11|.../` correctly satisfies the match. Once a regex can return *any* SUCCESS, it stops trying all other paths. This is by design.

**Comment by OnlineCop** [comment]
Did you want a pattern like `(1[01]{2,}|11)` instead, where it only accepts binary values 3 and higher (11, 100, 101, etc.)? https://regex101.com/r/0LaArP/2
