### ISSUE TITLE
Python Pattern works at regexstorm.net but Fails Here

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#857]
Hi guys.  I'm probably doing something wrong, but the following python regex pattern fails here with numerous errors:
`(?<=config\ file\ "([^"]+)"(?s:.*?))
\|\ ERROR\ \|`

Please let me know how to fix this, or if it is a bug.

Example errors:

> " An unescaped delimiter must be escaped with a backslash (\)
> + A quantifier inside a lookbehind makes it non-fixed width
> 

See https://regex101.com/r/aEgkb9/1

But it works at regexstorm.net.
See [this example](http://regexstorm.net/tester?p=%28%3f%3c%3dconfig%5c+file%5c+%22%28%5b%5e%22%5d%2b%29%22%28%3fs%3a.*%3f%29%29%0d%0a%5c%7c%5c+ERROR%5c+%5c%7c&i=24%2f05%2f2017+07%3a39%3a55+PM+%7c+DEBUG+%7c+Reading+config+file+%22FRGD-1_1.cfg%22.+%7c+main.py%3a81+-+set_configparser%28%29%0d%0a24%2f05%2f2017+07%3a39%3a55+PM+%7c+DEBUG+%7c+Reading+config+file+%22FRGD-1_10.cfg%22.+%7c+main.py%3a81+-+set_configparser%28%29++++%0d%0a...++++%0d%0a24%2f05%2f2017+08%3a39%3a55+PM+%7c+DEBUG+%7c+Reading+config+file+%22RFGD-1_5.cfg%22.+%7c+main.py%3a81+-+set_configparser%28%29++++%0d%0a...++++%0d%0a25%2f05%2f2017+09%3a53%3a47+PM+%7c+ERROR+%7c+KeyError.+There+is+an+issue+with+the+config+file+for+this+download.+Please+check+the+config+file+for+errors.+%7c+script.py%3a137+-+main%28%29++++%0d%0a...++++%0d%0a24%2f05%2f2017+10%3a39%3a55+PM+%7c+DEBUG+%7c+Reading+config+file+%22DPGD-4_15.cfg%22.+%7c+main.py%3a81+-+set_configparser%28%29++%0d%0a...++++%0d%0a24%2f05%2f2017+11%3a39%3a55+PM+%7c+DEBUG+%7c+Reading+config+file+%22ZXTD-3_1.cfg%22.+%7c+main.py%3a81+-+set_configparser%28%29++++%0d%0a25%2f05%2f2017+03%3a53%3a47+AM+%7c+ERROR+%7c+KeyError.+There+is+an+issue+with+the+config+file+for+this+download.+Please+check+the+config+file+for+errors.+%7c+script.py%3a137+-+main%28%29++++%0d%0a...++++%0d%0a24%2f05%2f2017+07%3a39%3a55+PM+%7c+DEBUG+%7c+Reading+config+file+%22FRGD-1_1.cfg%22.+%7c+main.py%3a81+-+set_configparser%28%29++++%0d%0a24%2f05%2f2017+07%3a39%3a55+PM+%7c+DEBUG+%7c+Reading+config+file+%22FRGD-1_10.cfg%22.+%7c+main.py%3a81+-+set_configparser%28%29&o=xs).

For details and more background, see https://stackoverflow.com/a/44179324/915019

Thanks for a great tool.  This is the first issue I have had with the actual pattern matching.

**Comment by TWiStErRob** [comment]
Just curious: Does it actually work in native Python?

**Comment by JMichaelTX** [comment]
> Just curious: Does it actually work in native Python?

I don't know.

**Comment by Doqnach** [comment]
The big difference I think is the fact that a .NET regex engine is used on regexstorm.net. .NET does support variable-width look-behinds, whereas other engines don't, like the PCRE engine used for the PCRE and Python flavours on regex101.com.

1. " An unescaped delimiter must be escaped with a backslash (\)
- because the chosen delimiter is `"`, escape it
2. '+' A quantifier inside a lookbehind makes it non-fixed width
- not supported by python
3. (? Incomplete group structure
- `(?s:` not supported in python perhaps? (unsure about this one)
4. A quantifier inside a lookbehind makes it non-fixed width
- not supported by python
5. ? The preceding token is not quantifiable
- not supported by python
6. ) Incomplete group structure
- see 3

**Comment by Doqnach** [comment]
Ah, I read the stackoverflow again and there the guy said that the latest engine actually supports variable-width look behinds? 

https://pypi.python.org/pypi/regex

**Comment by JMichaelTX** [comment]
> The big difference I think is the fact that a .NET regex engine is used on regexstorm.net. .NET does support variable-width look-behinds, whereas other engines don't, like the PCRE engine used for the PCRE and Python flavours on regex101.com.

OK, thanks for your analysis.  That answers my question.  Feel free to close this issue.

**Comment by Doqnach** [comment]
You could open a request for implementing the new Python flavour, for completeness.

**Comment by JMichaelTX** [comment]
> Zarthus closed this 2 minutes ago

What was the basis for closing this?  Has it been fixed?

**Comment by TWiStErRob** [comment]
@JMichaelTX I think this:
> Feel free to close this issue. - https://github.com/firasdib/Regex101/issues/857#issuecomment-304222848
