### ISSUE TITLE
PHP 7.0.3 evals to false 

### ISSUE THREAD

**Issue by Lyca0n** [firasdib/Regex101#858]
I tried the following and  in your site it returns true but in php 7.0.3 it evals to false

preg_match('RRR','(.)\1{2}')

string(3) "RRR"
<br />
<b>Warning</b>:  preg_match(): Delimiter must not be alphanumeric or backslash in <b>[...][...]</b> on line <b>7</b><br />
bool(false)

**Comment by Doqnach** [comment]
Please check this: https://regex101.com/r/ws2FRG/1/codegen?language=php

You are missing the delimiters in your regex string.
