### ISSUE TITLE
I was in the wrong flavor

### ISSUE THREAD

**Issue by willnwhite** [firasdib/Regex101#862]
I didn't know to choose my flavor from the sidebar before I started working on a regex, so I spent time solving my problem with regex that wasn't valid in my language (in this case it was that JS doesn't have lookbehinds), so I had to solve it again.

**Comment by Doqnach** [comment]
What is exactly your point? You would like to have the flavour indicated more clearly somewhere?

**Comment by willnwhite** [comment]
Yes. I would like to have known what flavor I was working in before I started, so that I couldn't make this mistake again.

**Comment by willnwhite** [comment]
I suppose it didn't matter that I was in the wrong flavor until I chose to use a token that didn't exist in my language. So if the tokens that aren't universal were labelled as such, that would have stopped me making this mistake.

**Comment by Doqnach** [comment]
There really isn't many 'tokens' which are universal, because there isn't really an official 'universal' regex definition. There are too many flavours with their own approach. That would result in almost any token being marked ;-].

**Comment by willnwhite** [comment]
Tokens could be marked until you selected a flavor.

**Comment by Zarthus** [comment]
PCRE is not limited to just PHP, it would be impossible to mention a list of all languages PCRE supports.

**Comment by willnwhite** [comment]
Before this issue, I didn't know that there were different flavors of regex, so I couldn't have thought to look for my flavor.

**Comment by Doqnach** [comment]
So this is less a tool/UI issue even, but more a knowledge problem then?

**Comment by willnwhite** [comment]
No, it's both.
