### ISSUE TITLE
JS Regex Inconsistency

### ISSUE THREAD

**Issue by richseviora** [firasdib/Regex101#864]
I'm seeing an inconsistency between the tool, and Chrome 58.0.3029 with the following regex:

    ^(-?\d+\.?\d* *(?:\S+))$

And the test text '45 lbs 45'. The tool indicates that the text is not a match for the Regexp, but I'm not seeing the same behaviour when running the same in Chrome.

To replicate:

1. Paste regex above into tool.
2. Select JS regex mode.
3. Test with `45 lbs 45` text. Receive no match (as expected).
4. Open Chrome console.
5. Run the following:

    let test = /^(-?\d+\.?\d* *(?:\S+))$/.compile(); // Returns undefined
    test.test('45 lbs 45') // Returns true

**Comment by Doqnach** [comment]
Chrome says that any and all test strings are 'true'...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/compile

Seems like the compile feature is deprecated? For me, any compile I do gives me the regex `/(?:)/` and any test therefor gives true.

Regex101 is correct in this case.

**Comment by richseviora** [comment]
LOL! Oh wow, I don't know where I got the idiot idea that `compile()` improved execution speed because that is obviously completely wrong. 

Of course, you have to wonder why an object has an instance method that acts as a constructor, and doesn't complain when there aren't any arguments. But now I know! Thanks! :)
