### ISSUE TITLE
Custom mIRC modifier /S

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#865]
mIRC has this nice custom /S modifier to strip any control code used for colors on IRC etc from the text before matching, could be handy to have that.

**Comment by TWiStErRob** [comment]
So you're proposing a new flag for all flavours?

Custom things are a good idea, but imagine the interoperability (copy-paste/code-gen) problems that it would cause. I would imagine an other way to do cleanup on the input/regex, small menu with some useful actions like "trim all lines", "strip control chars".

**Comment by Doqnach** [comment]
This could be done through a special mIRC flavour of course. So more a flavour request than anything else.

**Comment by Ouims** [comment]
mIRC uses PCRE and doesn't support subsitution with referencing named group capture so i don't think it's worth a special flavor

@TWiStErRob i don't mind a drop menu with these actions, but of course supporting /S would work directly when mIRC users paste a pattern with /S

**Comment by firasdib** [comment]
I think this is out of scope for the website, as its mIRC-specific.
