### ISSUE TITLE
Gets stuck in Processing on Firefox

### ISSUE THREAD

**Issue by iv1k** [firasdib/Regex101#866]
Gets stuck in processing the regex

![image](https://user-images.githubusercontent.com/10919366/27022302-e1a0023c-4f7f-11e7-9c6e-25a5d23fd526.png)

https://regex101.com/r/Tkaik0/1

Just found out it happens only when on PCRE / PHP
If I change it to javascript then it works

**Comment by firasdib** [comment]
Please check your console and tell me what you see there. A screen shot would be good

**Comment by iv1k** [comment]
![image](https://user-images.githubusercontent.com/10919366/27024731-5cd14268-4f8a-11e7-9cc6-f9300a8683ab.png)

**Comment by firasdib** [comment]
Your browser killed the process because it ran out of allowed/allocated memory. Try refreshing, it should work.

**Comment by iv1k** [comment]
I totally had to close the browser along with all its windows and start it again to get rid of the error.
The other tabs / pages in the browser worked fine.

and the error did not appear on setting the javascript option.

**Comment by firasdib** [comment]
Thats unfortunate. I'm not sure what I can do about this though, as its simply the browser limiting how much memory I'm allowed to allocate.

**Comment by Watilin** [comment]
Just experienced the same problem. I respect your wontfix decision but it would be nice to do something about this “processing…” indicator when an out of memory exception is caught. Or any exception by the way.

**Comment by careca1970** [comment]
Hi, just had same problem here.

**Comment by firasdib** [comment]
Okay, I see. Is this all affecting you in a firefox browser?

**Comment by Watilin** [comment]
Yup, Firefox 54.0 32bits on Windows 7.

**Comment by firasdib** [comment]
If you're still having this issue, please comment. Otherwise I'll close.
