### ISSUE TITLE
Invalid Substitution for $0 in JS mode

### ISSUE THREAD

**Issue by akhyzhni** [firasdib/Regex101#867]
In JavaScript the flag to capture all match is **$&**  instead of **$0**.

![invalid substitution for js](https://user-images.githubusercontent.com/16349097/27038063-99fb3c5e-4f92-11e7-9dbe-f8b247e52f2f.png)

Thanks

**Comment by firasdib** [comment]
Partially dup of https://github.com/firasdib/Regex101/issues/648

Its because the substitution lexer is not as smart as it should be (because I was lazy when writing it). I'll be remade.
