### ISSUE TITLE
Creating bulk tests

### ISSUE THREAD

**Issue by aymericbouzy** [firasdib/Regex101#869]
UX is not very good for rapidly creating 10 or so tests for a regex.

What would be great would be to have an interface where each line defines a new test. When typing a string for a test, hitting `return` would create a new line right away. The options (does match, does not match ...) would be available on the right side of the line.

That way, in very few clicks, it would be possible to create a full set of tests.

**Comment by TWiStErRob** [comment]
I remember someone brought this up before, but can't find it.

**Comment by Doqnach** [comment]
#795 and #847

**Comment by aymericbouzy** [comment]
In terms of UI, I was thinking of something like the one of Slack for inviting many new team members at once : 
<img width="979" alt="screen shot 2017-06-13 at 15 48 51" src="https://user-images.githubusercontent.com/8168981/27085567-eddb8cf8-504f-11e7-83e0-0a47a354a682.png">

**Comment by willthemoor** [comment]
Along these lines... It would be handy to paste several lines into the test string field and have the option to test each line separately with the same conditions. "These 21 examples should match."

**Comment by firasdib** [comment]
Thanks for input. Lets track this in https://github.com/firasdib/Regex101/issues/1090
