### ISSUE TITLE
Splunk support

### ISSUE THREAD

**Issue by fenchu** [firasdib/Regex101#870]
I've been working with perl/java/python for 10+ years, but it was after I started working with Splunk I really needed to understand group constructs and meta characters.

Would be nice if You could add a Splunk drop in, like changing any web meta characters so they
can be parsed aka: `[^\] with [^\x5C] or [^\\]`

Splunk supports [PCRE](http://docs.splunk.com/Documentation/Splunk/6.6.1/Knowledge/AboutSplunkregularexpressions) but needs web meta escaping for url encoding and handles flags differently.

* [REX](http://docs.splunk.com/Documentation/SplunkCloud/6.6.0/SearchReference/Rex)
* [REGEX](http://docs.splunk.com/Documentation/SplunkCloud/6.6.0/SearchReference/Regex)

Thanks for an excellent tool.
--
MortenB, Oslo, Norway

**Comment by Doqnach** [comment]
I think this is kind of related to #865 in a way. Some feature to auto-escape any special characters.

**Comment by firasdib** [comment]
I think integrating the website with a specific third party software is a slippery slope. You can try to use the code generator tool (and perhaps there we can add a flavor for Splunk).
