### ISSUE TITLE
A subpattern name need not be unique

### ISSUE THREAD

**Issue by Pascal666** [firasdib/Regex101#871]
I am getting the error "A subpattern name must be unique" from your tester with the example regex below.  This form of regex works fine in Perl v5.16.3.

`(one(?<code>\d+)two|three(?<code>\d+)four)\g{code}`

**Comment by firasdib** [comment]
Yes, unfortunately PCRE is not Perl, its just almost compatible. You can use the `(?|...)` construct to allow this pattern to pass.

**Comment by Pascal666** [comment]
Thank you.  I was able to get my simple example to work as:
`(?|one(?<code>\d+)two|three(?<code>\d+)four)\g{code}`
Unfortunately, the `(?|...)` construct does not appear to support nesting, as the below does not work:
`(?|(?|one(?<code>\d+)two|three(?<code>\d+)four)\g{code}five|six(?<code>\d+)seven)\g{code}`

**Comment by TWiStErRob** [comment]
@firasdib is it possible you're too eager to catch a potential error?
`(?|(?|one(?<code>\d+)two|three(?<code>\d+)four)\g{code}five|six(?<code>\d+)seven)\g{code}` fails with a handled error.
`(?|(?|one(?<code>\d+)two|three(?<code>\d+)four)\g{code}five|six(?<code1>\d+)seven)\g{code}` fails with an unhandled error, that suggests to use the above regex, rinse and repeat ;)

**Comment by firasdib** [comment]
@TWiStErRob That whole part of the code is a bit messy, but I believe there is a PCRE bug somewhere there and I could not be bothered to make my version accept that bug. I could be misremembering though.

**Comment by Doqnach** [comment]
There is also the `(?J)` flag that does enable the re-use of group names in at least PHP PCRE.
