### ISSUE TITLE
Prefill inputs via URL adress

### ISSUE THREAD

**Issue by PavelVais** [firasdib/Regex101#872]
It would be nice if there will be some sort of prefill option to automatically fill expression input, flags and test string. 

I have some list of regular tests and sometimes some of them fails, It would be handy have an option to create a link which will automatically fill everything in regex101 and instantly see whats wrong.

For example: www.regex101.com/fill?regex=xxxxx&flags=xxxx&string=xxxx

**Comment by Doqnach** [comment]
Check out the API: https://github.com/firasdib/Regex101/wiki/API

**Comment by firasdib** [comment]
Due to popular demand I have now added this.

You can adjust the following fields:
```
regex=...
testString=...
subst=...
flavor=javascript|python|pcre|golang
delimiter=....
```
No option depend on the other.

**Comment by dbareis** [comment]
Thanks for adding this. It would be nice if you could now save the existing query in the format.

How would I set the "REGEX FLAGS"?

**Comment by codebymikey** [comment]
https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url

URL template for those curious about it:
```
https://regex101.com/?regex=<regex>&testString=<text>&flags=<flags>&subst=<replacement>&flavor=(pcre2|pcre|javascript|python|golang|java|dotnet)&delimiter=<delimiter>
```
