### ISSUE TITLE
There was an error trying to save your regex. Please try again later.

### ISSUE THREAD

**Issue by kal11** [firasdib/Regex101#873]
Very often, I come across this issue, I cleared my cache and refreshed the page, same story still, I am using google chrome Version 58.0.3029.81 (64-bit) On RHEL 7 KDE.

**Comment by firasdib** [comment]
Can you please open your console and take a screenshot as this happens? The error should be printed in detail there.

**Comment by kal11** [comment]
![image](https://user-images.githubusercontent.com/11075307/27276897-e081b708-54dc-11e7-896d-65bbe66bb260.png)

**Comment by firasdib** [comment]
Interesting. Can you open the actual network request and show me whats being sent?

**Comment by kal11** [comment]
`log.js:7 App initialized
log.js:7 Loaded initial state
log.js:7 Successfully loaded previous state
log.js:7 Store configured
log.js:7 Service worker initialized
/api/regex/ Failed to load resource: the server responded with a status of 400 (Bad Request)
log.js:24 Unable to save regex Error: Bad Request
    at r (checkStatus.js:6)
    at <anonymous>
error @ log.js:24
sentry.io/api/102476/store/?sentry_version=7&sentry_client=raven-js%2F3.12.1&sentry_key=5f9e813965e0433598973663dff85743 Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
sw.js:6 Using cache 'regex101-cache-3.4.3'
sw.js:88 Handling fetch event for https://regex101.com/
sw.js:88 Handling fetch event for https://regex101.com/main.css
sw.js:106 Updated cache for 'https://regex101.com/main.css'
sw.js:106 Updated cache for 'https://regex101.com/'
main.js:2308 POST https://regex101.com/api/regex/ 400 (Bad Request)
e @ decoratedFetch.js:25
window.fetch @ decoratedFetch.js:6
(anonymous) @ raven.js:1069
(anonymous) @ saveRegex.js:28
(anonymous) @ index.js:11
value @ SaveModal.js:155
value @ SaveModal.js:77
updateComponent @ ReactCompositeComponent.js:614
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
updateChildren @ ReactChildReconciler.js:109
_reconcilerUpdateChildren @ ReactMultiChild.js:213
_updateChildren @ ReactMultiChild.js:312
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:157
s @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
C @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
i @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
r @ raven.js:295
log.js:24 Unable to save regex Error: Bad Request
    at r (checkStatus.js:6)
    at <anonymous>
error @ log.js:24
(anonymous) @ SaveModal.js:160
sw.js:88 Handling fetch event for https://regex101.com/
sw.js:106 Updated cache for 'https://regex101.com/'
sw.js:88 Handling fetch event for https://regex101.com/main.css
sw.js:88 Handling fetch event for https://regex101.com/main.js
Navigated to https://regex101.com/
sw.js:106 Updated cache for 'https://regex101.com/main.css'
sw.js:106 Updated cache for 'https://regex101.com/main.js'
sw.js:88 Handling fetch event for https://regex101.com/fontello.woff2
sw.js:88 Handling fetch event for https://regex101.com/open-sans-v13-latin-700.woff2
sw.js:106 Updated cache for 'https://regex101.com/fontello.woff2'
sw.js:106 Updated cache for 'https://regex101.com/open-sans-v13-latin-700.woff2'
log.js:7 App initialized
log.js:7 Loaded initial state
log.js:7 Successfully loaded previous state
log.js:7 Store configured
log.js:7 Service worker initialized
sw.js:88 Handling fetch event for https://regex101.com/pcreWorker.js
sw.js:106 Updated cache for 'https://regex101.com/pcreWorker.js'
sw.js:88 Handling fetch event for https://regex101.com/pcrelib.js
sw.js:106 Updated cache for 'https://regex101.com/pcrelib.js'
decoratedFetch.js:25 POST https://regex101.com/api/regex/ 400 (Bad Request)
e @ decoratedFetch.js:25
window.fetch @ decoratedFetch.js:6
(anonymous) @ raven.js:1069
(anonymous) @ saveRegex.js:28
(anonymous) @ index.js:11
value @ SaveModal.js:155
value @ SaveModal.js:77
updateComponent @ ReactCompositeComponent.js:614
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
receiveComponent @ ReactCompositeComponent.js:547
receiveComponent @ ReactReconciler.js:125
updateChildren @ ReactChildReconciler.js:109
_reconcilerUpdateChildren @ ReactMultiChild.js:213
_updateChildren @ ReactMultiChild.js:312
updateChildren @ ReactMultiChild.js:299
_updateDOMChildren @ ReactDOMComponent.js:936
updateComponent @ ReactDOMComponent.js:754
receiveComponent @ ReactDOMComponent.js:716
receiveComponent @ ReactReconciler.js:125
_updateRenderedComponent @ ReactCompositeComponent.js:754
_performComponentUpdate @ ReactCompositeComponent.js:724
updateComponent @ ReactCompositeComponent.js:645
performUpdateIfNecessary @ ReactCompositeComponent.js:561
performUpdateIfNecessary @ ReactReconciler.js:157
s @ ReactUpdates.js:150
perform @ Transaction.js:140
perform @ Transaction.js:140
perform @ ReactUpdates.js:89
C @ ReactUpdates.js:172
closeAll @ Transaction.js:206
perform @ Transaction.js:153
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
i @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
r @ raven.js:295
log.js:24 Unable to save regex Error: Bad Request
    at r (checkStatus.js:6)
    at <anonymous>
error @ log.js:24
(anonymous) @ SaveModal.js:160
sentry.io/api/102476/store/?sentry_version=7&sentry_client=raven-js%2F3.12.1&sentry_key=5f9e813965e0433598973663dff85743:1 POST https://sentry.io/api/102476/store/?sentry_version=7&sentry_client=raven-js%2F3.12.1&sentry_key=5f9e813965e0433598973663dff85743 429 (TOO MANY REQUESTS)
`

**Comment by firasdib** [comment]
I meant the actual network requests, where I can see what parameters are sent. You should receive an error ID somewhere.

**Comment by TWiStErRob** [comment]
@kal11 go to the Network tab in Developer Tools and then do the action that fails, a new request line should show up.

**Comment by kal11** [comment]
{"error":"Invalid delimiter (Error Id: 00ff5312-09b9-4191-a146-0efbcc5566af)"}

**Comment by firasdib** [comment]
Interesting. I can check this when I get home tonight, thanks. What delimiter did you select and what flavor?

**Comment by kal11** [comment]
@TWiStErRob I had only js errors selected, checked "all" And got it. @firasdib \r python

**Comment by firasdib** [comment]
@kal11 `\r` is not a valid delimiter, how did you end up with that? Try clicking the dropdown and select something else and save again.

**Comment by kal11** [comment]
Sorry r/

**Comment by firasdib** [comment]
Also invalid.

**Comment by firasdib** [comment]
I have found the bug now, I'll fix it tonight. Just select a new delimiter in the dropdown and it will work.

**Comment by kal11** [comment]
Yes, confirmed that it works once you pick any of the delimiters from the drop down menu, the trouble is it's r/ is the default one.

**Comment by firasdib** [comment]
Fixed

**Comment by kal11** [comment]
Tested and works the default delimiter for python flavor now is r"

**Comment by bajwauto** [comment]
![image](https://user-images.githubusercontent.com/60581597/92895036-c47b9200-f438-11ea-95f2-6cecb5bf1a8a.png)
I am facing this issue for last few days now

**Comment by firasdib** [comment]
@bajwauto do you get the same if you try an incognito tab? If so, are there any errors in your console? Do you have any network blocking software?
