### ISSUE TITLE
Changed delimiter is forgotten when revisiting the shared URL

### ISSUE THREAD

**Issue by Integralist** [firasdib/Regex101#874]
I went to https://regex101.com/r/2gDShx/6 and noticed the delimiter was incorrect (or so I thought).

I changed the delimiter from `/` to `~` and saved a new version:

https://regex101.com/r/2gDShx/7

But then realised _that_ URL also doesn't persist the change in delimiter.

**Comment by firasdib** [comment]
Argh, I should test my code better. This is a regression introduced with the fix in #873. I'll fix this as I come home tonight.

**Comment by Integralist** [comment]
Thanks @firasdib
