### ISSUE TITLE
Testpage does not accept characters from other languages ?

### ISSUE THREAD

**Issue by rbuelund** [firasdib/Regex101#875]
The code below should accept two words with characters from all languages but it only accepts english characters ??:

`^((\b[\p{L}]{2,40}\b)\s*){2,}$`

**Comment by Doqnach** [comment]
Could you provide a test link showing this problem?

**Comment by firasdib** [comment]
Did you enable the `u`-flag?

**Comment by firasdib** [comment]
closing, stale issue
