### ISSUE TITLE
/(*UTF8)[[:alnum:]]/ should be valid for pcre

### ISSUE THREAD

**Issue by rjmunhoz** [firasdib/Regex101#876]
The [pcre](http://www.pcre.org/pcre.txt) manual states that, in order to properly deal with encoding, you should add one of these sequences to the beginning of your pattern:

- (*UTF8)
- (*UTF16)
- (*UTF32)
- (*UTF)

Regex101, though, says it's not a valid pattern

**Comment by Doqnach** [comment]
You can try the 'u' flag instead at Regex101. Many programming languages also support this flag.

**Comment by firasdib** [comment]
Only `(*UTF16)` is supported since the library was compiled with that option.

**Comment by rentalhost** [comment]
@firasdib maybe instead of display only the error like `(*UTF8) This verb is unknown or invalid` it could additionally instruct to use `(*UTF16)` instead?

![image](https://user-images.githubusercontent.com/421851/62096766-2be97900-b25b-11e9-8760-1e56382107c0.png)
