### ISSUE TITLE
"The character offset is too large" error in golang flavour

### ISSUE THREAD

**Issue by Coccodrillo** [firasdib/Regex101#878]
I get an error "The character offset is too large" when trying out this regex 

[^\x{1F600}-\x{1F6FF}&^\x{2600}-\x{26FF}&^\p{L}\s']

[Regex101](https://regex101.com/r/X8IoQX/1/)

[Working Playground Example](https://play.golang.org/p/9GVfyUUK-M)

**Comment by firasdib** [comment]
Fixed, thanks for reporting!
