### ISSUE TITLE
Pattern Error seems to work 

### ISSUE THREAD

**Issue by guncs** [firasdib/Regex101#881]
(?:(?P<slug>[-a-z0-9]+)/)? is the regex I tried and it is giving a pattern error because of the last slash, however when i type a url like example.com/somedirectory/id/some-slug it is able to match this regex and return the page. I'm new to regex stuff so maybe this is not an error or I'm missing a point, if so please ignore.

**Comment by firasdib** [comment]
Please post a permalink

**Comment by guncs** [comment]
Oh so sorry, I just realized that I was testing this regex in php "flavor" even though I'm writing a python script, so this is not actually giving a pattern error in python.
