### ISSUE TITLE
Match result is not true for a pattern

### ISSUE THREAD

**Issue by saeidalidadi** [firasdib/Regex101#882]
The pattern: 
`/\dB+.{2}(\dB|--)/`

The string: 
`2B--------5W--3W------5B5W------3B--5B--------2W`

The result should be `4` matches but return  `3` matches.

**Comment by firasdib** [comment]
No, three looks right.

**Comment by saeidalidadi** [comment]
So what do you think about the 4th match?(in parentheses)
`2B--------5W--3W------5B5W------3B--(5B----)----2W

**Comment by firasdib** [comment]
The `5B` is already consumed by the previous match, so its not possible.
