### ISSUE TITLE
Invalid code generator substitution for Java

### ISSUE THREAD

**Issue by Jelkya** [firasdib/Regex101#883]
The code generator for **substitutions** in **Java** is bugged, i guess.
It produces the line
 `final String subst = "\\0";`

instead of

`final String subst = "$0";`

**Comment by TWiStErRob** [comment]
You should use `$0` in replacement box before generating code.

**Comment by Zarthus** [comment]
I agree. This would normally be caught if a `java` flavour was implemented and then selected, but it is not. Regex101 takes both $1 and \1 in the substitution box and expects the user to make the right decision for which "delimiter" to use.
