### ISSUE TITLE
Keep name and tags on update

### ISSUE THREAD

**Issue by zekrom-vale** [firasdib/Regex101#884]
It is required to re-enter all the organization information when updating, if you do not it does not have any information.  Is it possible to pull the previous information when updating?

**Comment by firasdib** [comment]
I have been considering something similar, and I think it has been suggested before. What could be done is that the new version gets a copy of the title/tags of the previous version, which of course could then be individually adjusted. Does that sound good?

**Comment by eToThePi-i** [comment]
I would very much appreciate that change.

**Comment by firasdib** [comment]
This is now the case, 2-3 years later :-)
