### ISSUE TITLE
Does not support Python triple quoted strings

### ISSUE THREAD

**Issue by Paddy3118** [firasdib/Regex101#886]
I wanted to modify a Python regexp that was in a Python tripple quoted string. The regexp contained non-escaped single quotes , but this failed in your tool because it assumes the string starts r"

An option to have the Python string start with r''', r""", r', as well as r" would cover all the pythonic cases.

Thanks for the tool :-)

**Comment by firasdib** [comment]
Click the delimiter and change it

**Comment by Paddy3118** [comment]
Thanks, knowing that it was an option, I was able to find and apply it :-)
