### ISSUE TITLE
Deleting a saved expression deletes ALL my saved expressions

### ISSUE THREAD

**Issue by OphyTe** [firasdib/Regex101#890]
Hi, everything is in the object.

When I click on the basket of an expression in the account page ("Delete permalinks"), it deletes all the expressions previously saved ...

**Comment by firasdib** [comment]
All? It should only delete that permalink, including all subversions of it.

**Comment by OphyTe** [comment]
This is maybe the answer !
How can I know if an expression is a subversion of another one ?

**Comment by OphyTe** [comment]
OK, this is it !
All my expressions have the same permalink root followed by a "/" and a number. I presume this is what you called "subversions".

So I have to create my expressions after refreshing the page (as there's no "new regex" button ;-) -- #712)

Thanks for your reply.
