### ISSUE TITLE
golang: Add FindAllStringSubmatch ability

### ISSUE THREAD

**Issue by Steve-hyas** [firasdib/Regex101#891]
Option to search for Submatch
https://golang.org/pkg/regexp/#example_Regexp_FindAllStringSubmatch
```
If 'Submatch' is present, the return value is a slice identifying the successive submatches of the expression. Submatches are matches of parenthesized subexpressions (also known as capturing groups) within the regular expression, numbered from left to right in order of opening parenthesis. Submatch 0 is the match of the entire expression, submatch 1 the match of the first parenthesized subexpression, and so on.
```

**Comment by TWiStErRob** [comment]
Are you looking for Match Information export?

1. Open https://regex101.com/r/G9oaXt/1
2. Open Match Information on the right (should show 6 matches)
3. Click the export (arrow) button on top right of Match Information
4. Select format
5. Profit.

If the result contains too much info, you can use non-capturing groups: https://regex101.com/r/G9oaXt/2
