### ISSUE TITLE
regexp behaviour discrepency

### ISSUE THREAD

**Issue by brieucdesoutter** [firasdib/Regex101#892]
Hi,

I've tested the following regexp in javascript mode:
/rgba?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3})(?:,\s?(\d?.?\d))?\)/g

In regexp101 it matches the following string: 'rgba(123,123,123,1)' (no space between components) but on Firefox, Chrome:
var re = /rgba?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3})(?:,\s?(\d?.?\d))?\)/g
var res = re.exec("rgba(123,123,123,1)") returns null

![image](https://user-images.githubusercontent.com/30637345/28921444-448f3c1a-7856-11e7-822d-acf58673e892.png)

**Comment by firasdib** [comment]
Works fine for me. The reason it won't work is because you're using `exec` which has an internal pointer to the last match. You should use `matches` instead for this.
