### ISSUE TITLE
Invalid max character offset for PCRE \x{…}

### ISSUE THREAD

**Issue by scy** [firasdib/Regex101#897]
Trying to use ˋ\x{11000}ˋ or any value larger than that in a PCRE (PHP) regex results in the error message "The character offset is too large".

I guess that's a typo in the regex101 source (you forgot an ˋfˋ when defining the maximum, leading to ˋ\x{10fff}ˋ), since PHP supports at least characters up to the current edge of Unicode (10.0), ˋ\x{10ffff}ˋ.

**Comment by firasdib** [comment]
Good eye sir! Fixed

**Comment by xiongchiamiov** [comment]
@firasdib This does not appear to be fixed (or perhaps it's been rebroken): https://regex101.com/r/LAwvDY/1

**Comment by firasdib** [comment]
You need the unicode flag. 


Vänliga hälsningar / Best regards,

Firas Dib
