### ISSUE TITLE
Python Escape  chars

### ISSUE THREAD

**Issue by moiseyo** [firasdib/Regex101#899]
I have  expration
r''^\s*("?(\/\w+[^\s]*)"?(\s+)?)+'
which  run in python 
and application produce 

ll the errors detected are listed below, from left to right, as they appear in the pattern.
" An unescaped delimiter must be escaped with a backslash (\)
? The preceding token is not quantifiable
" An unescaped delimiter must be escaped with a backslash (\)
? The preceding token is not quantifiable

**Comment by Doqnach** [comment]
This is a Python thing, not a regex101.com thing. Check the code generator for an example of Python code. Your quotes seem to be very off (you start with two single-quotes, end with a single single-quote).

https://regex101.com/r/ILCo5o/1/codegen?language=python
