### ISSUE TITLE
support wget regex

### ISSUE THREAD

**Issue by andykais** [firasdib/Regex101#900]
thank you for this great tool!

is it possible to add regex option for `wget`, bash `[ =~ ]`, `sed` regexes? The differences are minor (usually just what needs to be escaped and what doesnt) but I would love to be able to write them here as opposed to testing on the command line. In case any of these are already one of the options, maybe the existing options could say what else they equate to?

**Comment by Zarthus** [comment]
Unless wget is different from POSIX / bash / sed, this is a duplicate.

See https://github.com/firasdib/Regex101/projects/3 for a list of all requested flavours, bash / egrep / sed are all already in there.
