### ISSUE TITLE
Show Symbol (white space, tab, linefeed, carriage return, wrap, etc.) in regex

### ISSUE THREAD

**Issue by Hanne4** [firasdib/Regex101#901]
I like this regex101.com site for its clarity, but one thing is missing.

I would like to refer to Notepad++ for its "Show Symbol" features. The reason why I recommend this is that the EOL (end of line) symbol can be confused with the wrapping of the regex string in the regex field. This can cause issues when copying expressions from one editor into the other. Notepad++ can show all these special space symbols.

**Comment by Doqnach** [comment]
If wrapping is the issue, you can turn on line numbers to help with that.

**Comment by Hanne4** [comment]
Thanks for referring to the Settings. I think this solves my issue.
