### ISSUE TITLE
Browser search doesn't find out-of-view text

### ISSUE THREAD

**Issue by rewardealer** [firasdib/Regex101#903]
I'm unable to search inside the "TEST STRING" block when the target string is out of view. Is could very annoying when you trying to parse a large web page. It would be great in you make a custom search box to fix the problem.

**Comment by firasdib** [comment]
This is a limitation of codemirror. I'd have to implement my own thing (or use some other plugin), which I think will be a bit confusing. Or atleast it'd behave a bit differently and sometimes clash with the built in search in the browser.

**Comment by firasdib** [comment]
Hopefully codemirror 6 addresses this. Otherwise we're out of luck unfortunately. Closing this for now.

**Comment by Doqnach** [comment]
I also think that some cases where this would be useful are also covered (and "fixed") by #721
