### ISSUE TITLE
General Email Regex create invalid go code

### ISSUE THREAD

**Issue by Nhoya** [firasdib/Regex101#904]
i was trying this regex with the golang here
https://regex101.com/r/kpXUYT/1

as you can see the regex is working but the auto generated code will not build with the following errors

```
syntax error: unexpected {, expecting comma or )
bitwise complement operator is ^
illegal character U+003F '?'
illegal character U+005C '\'
illegal character U+0023 '#'
 illegal character U+0024 '$'
.missing '
illegal character U+003F '?'
illegal character U+005C '\'
```

**Comment by Doqnach** [comment]
Do you also have a suggestion on what needs to be changed with the code generator to make it compile?

**Comment by firasdib** [comment]
No feedback, closing.
