### ISSUE TITLE
Add "Flex" flavor

### ISSUE THREAD

**Issue by tclemans** [firasdib/Regex101#905]
Adding a flex regex flavor would be very useful for students taking Compiler classes and anyone who is learning/using flex & bison.

**Comment by Zarthus** [comment]
Can you perhaps link to some documentation for those who don't know what flex is?

https://github.com/firasdib/Regex101/issues/141 might already cover it, also https://github.com/firasdib/Regex101/projects/3 will show all already requested flavours in case Flex is already in there as some sort of derivative.
