### ISSUE TITLE
Feature: Simplified view for "non-technical" users on shared regex 

### ISSUE THREAD

**Issue by gcosta87** [firasdib/Regex101#906]
Hi!

I would like to request a feature: a simplified view on shared links, for those users who only want to test a regex, without seeing all the technical details.

I use regex101 in my work to analyze fixed-length plain text files pertaining to (data exchange) specifications. My co-workers are not technical users, but sometimes they need to validate (test) those records.

I think it would be opportune to hide the technical details: explanation and definition of regex (for example). I think that this way, the gui would be more friendly or comfortable for this type of users.

I thank you in advance ;)

**Comment by Zarthus** [comment]
Do you mean that you'd prefer to be able to share a link where the panels on the right are collapsed by default? It sounds to me like a regular text editor with regex search might better fix the "non-technical" bit and offer more control, but I'm assuming you want something that can be shared across the internet.

Might be possible with a GET parameter I suppose. Alternatively caching setting for collapsed/uncollapsed to remain cached for revisits would serve as a good one-time-hide resolution.

**Comment by gcosta87** [comment]
Hi @Zarthus

Yes, exactly!.

I would like to take advantage of the possibility of sharing over the internet.
From the perspective of a non-technical user: they are not interested in the regex (read / write) syntax, nor the explanation, they just want to validate and / or test with some text.

In my work context, my co-workers often evaluate long lines (140 to 400 characters) corresponding to fixed length specifications.

I think it would be a good idea to make regex101 more user friendly for non-technical regex users ;).

**Comment by Doqnach** [comment]
So your actual question is: can regex101 be made into a tool where I put a regex, and share this as a validation tool for input to other users (who can only input data (test string) and see if it matches or not in a simple to understand interface)?

**Comment by Zarthus** [comment]
I don't think he's asking for an ui revamp, just to collapse the explanation by default.

**Comment by Doqnach** [comment]
His last post suggests he only cares about the result, not even de regex itself. More a matching/validation tool than a "regex writing" tool. So just hiding the panes does not fully cover that wish.

**Comment by gcosta87** [comment]
Hi @Doqnach the idea would be that, as you correctly described in your comment.
There would be different ways to implement the "solution" as well poses you and @Zarthus 

What do you think about the functionality presented in this thread?

**Comment by Doqnach** [comment]
I think it is an interesting feature, but I see it not as the main purpose of the website. I would keep it on a list but not with a very high priority.

Something you really need to start looking into is storage of the validations/tests and retention. Right now no claim on the length of retention is made. If you were to focus even more on such an aspect it starts becoming more important. Thing is, even though storage is not the most crazy expensive thing in the world, it's not free either. @firasdib is paying for all of this from his own pocket, helped by everyones donations a little.

You could start treading into the realm of paid service plans with a guaranteed retention period etc but that opens up a whole new level of commitment required.

Still, it's a nice idea for a service for sure.

**Comment by firasdib** [comment]
I've been considering adding a feature if the site is loaded through an iframe, it opens in read-only mode with sidebars collapsed by default. This could be used for inlining things on stackoverflow, for example.

Does this fullfil your request, @gcosta87 ?

**Comment by gcosta87** [comment]
Hi @firasdib
I think its a great idea of implementation, beacuse its ease and usefull for that users :)

**Comment by firasdib** [comment]
I've thought about this some more, and it seems embedding code samples is no longer used in SO (they have their own implementation), which makes the use case for this extremely slim.

For now, I will close this.

**Comment by firasdib** [comment]
Fwiw, its perfectly fine do do something like this:

```
<embed src="https://regex101.com" style="width:500px; height: 400px;">
```

To embed the website in your own, to show a live regex or something. The full editor is mobile friendly, and will scale automatically.
