### ISSUE TITLE
Substitution matches not replacing correctly for non-numeric substitutions $`, $', $&

### ISSUE THREAD

**Issue by mikehdt** [firasdib/Regex101#907]
It would seem that the non-numeric group substitutions, ``$` ``, `$'`, `$&` aren't working correctly and instead are substituting their pattern literally.

This test regex: `/hello/g`
With this input: `Oh hello there`
And JavaScript regex matching (although PCRE/Python/Golang also seem to behave similarly)

``$` `` replacement results in: ``Oh $` there``
`$'` replacement results in: `Oh $' there`
`$&` replacement results in: `Oh $& there`
However,
`$1` replacement results in: `Oh hello there`

Testing in my browser console, `'Oh hello there'.replace(/hello/g, '$&');` results correctly in `Oh hello there` as a result.

Unless I've mistaken something? Thanks.

**Comment by firasdib** [comment]
Related: https://github.com/firasdib/Regex101/issues/648

**Comment by firasdib** [comment]
Closing in favor of https://github.com/firasdib/Regex101/issues/648

The issue will be tracked there.
