### ISSUE TITLE
Suggest a flavour based on user input

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#908]
Maintain a mapping of `programming languages` => `most compatible flavour` or a popover explaining the limitations and advantages of each flavour and which ones are best to use might mitigate the "This site doesn't have Java. I guess I'll need to find something else" for users who think there are significant differences between the engines.

**Comment by firasdib** [comment]
By default the PCRE flavor is selected, which is the most generic flavor. Not sure how I could add what you're suggesting.

**Comment by TWiStErRob** [comment]
PCRE is the most generic, and that's kind of the problem. Some languages have more limited feature set, so using PCRE allows too many things. There may be another flavor that more closely approximates what's possible in the target language's regex. I think one of the main points is that the Flavor selector should be language based and not engine based. I didn't know for example PCRE was in PHP until I saw your site ;)

![image](https://user-images.githubusercontent.com/2906988/33795837-d14faa74-dce0-11e7-80bd-a36772efe134.png)

Alternatively keep the flavor based selection, but start listing "close" languages for each flavor:
![image](https://user-images.githubusercontent.com/2906988/33795862-393c1366-dce1-11e7-9364-3d1cf912f40a.png)

(Note, the mappings are not correct, just added them to convey the ideas)

**Comment by Ouims** [comment]
I'm not for this suggestion, there are various way to implement regex, it's not impossible for a language to provide two differents regex implementations in which case you wouldn't be able to tell which flavor is used. Regex is not like baking a cake, it's like piloting a plane, it requires skills and a lot of understanding of how string parsing works, people who are not technical enough should not be bothered by this.

**Comment by aifrim** [comment]
My suggestion is to remember the last selected flavor.
Since I write, nowadays, mostly Javascript code I always switch to its flavor.
Just put it in a cookie, no harm no foul.

**Comment by TWiStErRob** [comment]
@aifrim go to settings, you can select a default.

**Comment by firasdib** [comment]
I'm not sure this is possible, so I'm closing for now.
