### ISSUE TITLE
Not able to save.

### ISSUE THREAD

**Issue by SimpelMe** [firasdib/Regex101#909]
Hi.
I used regex101 some weeks. Today I decided first time to login with my github account. 
But when I press ctrl+s and fill in title on the second tab there is nothing saved. My history and my expressions stay empty.

Regards, Conrad

**Comment by SimpelMe** [comment]
I used IE11 at work.
Now being home and using iPad (had to login first time here) I can save and see all in history and my expressions.
Will test IE11 at work tomorrow again.
Conrad

**Comment by SimpelMe** [comment]
Now I'm back to work and it's working. Maybe a cache or initial login issue.
Conrad

**Comment by firasdib** [comment]
Thanks for reporting back. Please reopen if it happens again.
