### ISSUE TITLE
code generator flavor AutoIt

### ISSUE THREAD

**Issue by SimpelMe** [firasdib/Regex101#910]
Hi.
I would like a code generator for AutoIt. An example could be:
```
#include <Array.au3> ; just needed for showing the result
$re = '(?m)^\"?(.+?)(?:\"*$)'
$str = '"test_line_1' & @CRLF & _
		'test_line_2"' & @CRLF & _
		'"test_line_3""' & @CRLF & _
		'test"l"in"e_4"';

$aArray = StringRegExp($str, $re, 3)
;Show the entire match result
_ArrayDisplay($aArray)
```

Sample above with flavour php from your code generator:
```
$re = '/(?m)^\"?(.+?)(?:\"*$)/';
$str = '"test_line_1
test_line_2"
"test_line_3""
test"l"in"e_4"';

preg_match_all($re, $str, $matches, PREG_SET_ORDER, 0);

// Print the entire match result
var_dump($matches);
```

Regards, Conrad

**Comment by Doqnach** [comment]
could you provide more examples for also unicode (/.../u), global (/.../g), non-global (/.../) ?
There is no multiline string variable?

**Comment by SimpelMe** [comment]
Hi.
AutoIt uses the PCRE engine. I think I'm not that expert to answer your questions. But I can provide the link to the StringRegExp() manual/help file: [https://www.autoitscript.com/autoit3/docs/functions/StringRegExp.htm](https://www.autoitscript.com/autoit3/docs/functions/StringRegExp.htm)
I hope that helps. Regards, Conrad

**Comment by SimpelMe** [comment]
But I can offer you testing AutoIt examples your code generator made.

**Comment by Doqnach** [comment]
Without full understanding of the language it would be hard to generate working examples for all cases (of flags etc).

**Comment by firasdib** [comment]
Here's a guide: https://github.com/firasdib/Regex101/wiki/Writing-a-Code-Generator

If its no longer of interest, please close the issue.

**Comment by SimpelMe** [comment]
Hi,

I wanted write a code generator for a long time with the flavor AutoIt. Now I made an example for it.
Unfortunately I couldn't run that code but I hope everything is written correctly.
[Regex101_Code-Generator_AutoIt.txt](https://github.com/firasdib/Regex101/files/3188823/Regex101_Code-Generator_AutoIt.txt)


Regards, Simpel

**Comment by SimpelMe** [comment]
I again thought about un-/commenting the #includes and decided now that it's better to have them. So 3 lines have changed.
[Regex101_Code-Generator_AutoIt.txt](https://github.com/firasdib/Regex101/files/3190610/Regex101_Code-Generator_AutoIt.txt)

**Comment by firasdib** [comment]
Thanks for your hard work @SimpelMe. I'll add this soon.

**Comment by SimpelMe** [comment]
It's a pity that I can't test my code before posting it to you. So while testing your implementation I of course found 3 errors of mine. First and second in AutoIt an already with backslash escaped backslash don't need another escaping by doubling backslashes. That I fixed with the code I'm providing here: [Regex101_Code-Generator_AutoIt.txt](https://github.com/firasdib/Regex101/files/3200026/Regex101_Code-Generator_AutoIt.txt)

But there is a third problem I can't fix alone. If the $string is including line feeds or carriage returns (I'm not sure what is used in your code presented by the test string field) they should be replaced with:
" & @CRLF & _
                "
Do you understand what I mean? At the line break from the test string field the $string should be closed with " then an @CRLF is added with a trailing & _ (there is a space between & and _) followed by a real line break. The next line should start with 4 tabs or 16 spaces and then after a " the $string should continue. 

Can you help?
Regards Simpel

**Comment by SimpelMe** [comment]
I want to push my message I wrote 26 days ago and not open a new issue.

Regards, Simpel

**Comment by firasdib** [comment]
@SimpelMe Thanks for the feedback. I'll try to get around to this asap.

**Comment by firasdib** [comment]
I've adjusted the code according to your latest feedback again. I'll be pushed live soon. Feel free to reopen if there are more issues.

**Comment by SimpelMe** [comment]
Hi @firasdib Thanks for adjusting.
There is an issue with masking backslashes. There are to much of them. Here is an example: [https://regex101.com/r/lTCZP5/3](https://regex101.com/r/lTCZP5/3)

That's how it should look like:
`#include <MsgBoxConstants.au3> ; to declare the Constants of MsgBox`
`Local $sRegex = "(?m)(\d{2})\.(\d{2})\.(\d{4})\\(.*)"`
`Local $sString = "09.10.2018\09:47:30" & @CRLF & _`
`                "14.05.2019\13:48:44" & @CRLF & _`
`                "18.05.2019\14:09:33"`
`Local $sSubst = "$3\\$2\\$1 $4"`
`Local $sResult = StringRegExpReplace($sString, $sRegex, $sSubst)`
`MsgBox($MB_SYSTEMMODAL, "Result", $sResult)`

That's what it currently looks:
`#include <MsgBoxConstants.au3> ; to declare the Constants of MsgBox`
`Local $sRegex = "(?m)(\d{2})\.(\d{2})\.(\d{4})\\(.*)"`
`Local $sString = "09.10.2018\\09:47:30\" & @CRLF & _`
`                \"14.05.2019\\13:48:44\" & @CRLF & _`
`                \"18.05.2019\\14:09:33"`
`Local $sSubst = "$3\\\\$2\\\\$1 $4"`
`Local $sResult = StringRegExpReplace($sString, $sRegex, $sSubst)`
`MsgBox($MB_SYSTEMMODAL, "Result", $sResult)`

At **$sString** you see a `\` after the time before `"` if a new line is following.
Also there is a trailing `\` if a new line is starting. Both are not correct.
Third there should only be `\` between date and time not `\\`.

At **$sSubst** there should be no masking. The `\\` in the tester are currently `\\\\` in the generator. That is not correct.

Regards, Simpel

**Comment by SimpelMe** [comment]
I'm still interested and it would be nice if my personal work around wouldn't be necessary any more. That's why I'm pushing it again.

Thanks for your great tool,
Simpel

**Comment by firasdib** [comment]
@SimpelMe I will adjust and push it live soon.

**Comment by seadoggie01** [comment]
There's a couple of issues with the current version. Newlines in the regex aren't replaced and similarly aren't quoted. When the (?m) flag is missing, there's a leading (?) at the beginning. See [here](https://regex101.com/r/RS6dCN/1)

(And slight nitpick: `#include <Array.au3> ; UDF needed for _ArrayDisplay and _ArrayConcatenate`)

**Comment by firasdib** [comment]
Thanks, I'll update again.

**Comment by SimpelMe** [comment]
Works like charm.
Thank you.
