### ISSUE TITLE
Capture Groups Do NOT Show Highlighting When JavaScript

### ISSUE THREAD

**Issue by JMichaelTX** [firasdib/Regex101#911]
### Capture Groups Do NOT Show Highlighting When JavaScript

When the language is JavaScript, capture groups are NOT highlighted  in the main source window:

![image](https://user-images.githubusercontent.com/11052885/30191806-ef234c48-9408-11e7-8437-ba9557e7eb14.png)

All of the other languages do show highlighting:

![image](https://user-images.githubusercontent.com/11052885/30191817-05913896-9409-11e7-9bc6-0d93289dd66b.png)

Link to RegEx case:
https://regex101.com/r/n6RVF0/1

I love your tool, but please fix this.
Thanks.

**Comment by TWiStErRob** [comment]
It's not possible afaik, JavaScript doesn't support group bounds, positions are just not returned.

**Comment by firasdib** [comment]
https://github.com/firasdib/Regex101/issues/841
https://github.com/firasdib/Regex101/issues/755

Sorry, can't do it.
