### ISSUE TITLE
Move the randomized part of the IRC name to the beginning

### ISSUE THREAD

**Issue by Lysxia** [firasdib/Regex101#912]
It would be more convenient for readability and tab-completion if names looked like `fish-555-re101` instead of the current `re101-fish-555`.

**Comment by Doqnach** [comment]
I kind of like being able to tab-complete through all currently online webirc users actually. Though it would not be a problem if this change were to be made.

**Comment by firasdib** [comment]
The idea was to be able to find the re101 specific users easily. I'm inclined to keep it this way for now.
