### ISSUE TITLE
Enhancement: Have "donate" button open a new tab instead of in current tab.

### ISSUE THREAD

**Issue by surbas** [firasdib/Regex101#914]
Thanks for your website. I find it super valuable and helpful.

My small suggestion is you should have the upper right menu bar buttons like "donate"  new tab by default so a user doesn't potential lose their work. 

Again thanks!
Shon

**Comment by Doqnach** [comment]
Duplicate of/related to #796

**Comment by Zarthus** [comment]
@firasdib please come to a decision for this task as well (given the outcome of #796 was rejected)

**Comment by surbas** [comment]
Dudes just thinking about UX. You want to make it easy to people to donate and use the site. Feel free to close. just my 2 cents (plus the donation I already made).
