### ISSUE TITLE
Add possibility to collapse the left sidebar and the right sidebar

### ISSUE THREAD

**Issue by nowox** [firasdib/Regex101#916]
On my interface I don't have any button to close the right bar and the left bar
![image](https://user-images.githubusercontent.com/1132849/30744856-3f2350d4-9fa4-11e7-8555-765703624528.png)

Form the settings I can check "Always collapse left sidebar", but this is not what I am looking for.

**Comment by Zarthus** [comment]
This used to be possible in Regex101 version 1 by dragging. It looks like that feature was removed/not brought back in the redesign of v2

**Comment by firasdib** [comment]
There are options to always collapse the right and left sidebar. Is this not what you are looking for?

**Comment by nowox** [comment]
@firasdib No this is not, because I don't want to always collapse them. As @Zarthus said in Regex101 version 1 you could click on a notch on the vertical bar to collapse or restore the sidebars. It looks this feature was removed in v2 which is a bit sad.

**Comment by firasdib** [comment]
For the time being you can leave them collapsed and open then with the hamburger in the header.

**Comment by nowox** [comment]
True, but once opened you can't dock them opened which is the feature I am looking for

**Comment by firasdib** [comment]
I've implemented a simple resizer that allows you to drag the sidebar to any given size (within some bounds). This will not be saved and thus be reset each time you visit the site. This was intentional, as there is no simple way to reset the behavior in case you set it to some arbitrary width.
