### ISSUE TITLE
regex works on all flavours, but not on Javascript, but it works in my Javascript application 

### ISSUE THREAD

**Issue by isaklafleur** [firasdib/Regex101#917]
regex: \b(\w+)$

string: ANGULAR CONTACT (ROLLING) BEARING

It return BEARING in my application, but it does not work on your site for flavour js.

Thanks for an awesome site! 

Isak

**Comment by isaklafleur** [comment]
sorry, my bad. I had a new line below.

**Comment by Doqnach** [comment]
Turn on line-numbers in the settings to help you combat such issues.
