### ISSUE TITLE
incorrect php emulation of \n match

### ISSUE THREAD

**Issue by slutchko** [firasdib/Regex101#918]
Regex: `(.*?)((?><br>)?<div class="gmail_quote">)(.*)`
Text: 
```
some text at the beginning<br>subpattern-text until end of paragraph
second paragraph
third paragraph - end of text
```
Your tool returns 3rd Capturing Group as `-text until end of paragraph...end of text` whilst php (and e.g. here www.phpliveregex.com) returns it as `-text until end of paragraph` only.

Thanks for the tool and have a good luck!

**Comment by Doqnach** [comment]
Do you have a working example on regex101 and phpliveregex.com? Because with the given text I can't produce matches on either website. Please note that by default `.` (dot) does not match new-lines (`\n`) unless you specify the `/.../s` flag.

**Comment by firasdib** [comment]
To clarify: the website uses PCRE which PHP also does, and for relatability ive chosen to name it PHP even though it is not a perfect match (as I do not infact run PHP).

If you can provide more info feel free to reopen.
