### ISSUE TITLE
Feature Request: Show RegExp engine being used.

### ISSUE THREAD

**Issue by rajinder-yadav** [firasdib/Regex101#919]
Would be nice to know what "flavor" of regexp is being used.

![regex](https://user-images.githubusercontent.com/439226/31090516-de100f1a-a775-11e7-8b8a-7265429fc5f7.png)

**Comment by rajinder-yadav** [comment]
Also saved the selected settings to local storage so I don't need to keep selecting "javascript".

**Comment by Doqnach** [comment]
Agree with the first suggestion.

The second suggestion is debatable. I sometimes switch to javascript but 90% of my regex's will probably be PCRE. PCRE is also (from these flavours) the widest used. Can always be a setting when you are logged in to have a 'default for new regex'?

**Comment by firasdib** [comment]
There is a default flavor option under the settings menu.

**Comment by Doqnach** [comment]
woops :-P

**Comment by firasdib** [comment]
This is only ever an issue if the sidebar is closed, so I don't think its worth explicitly showing this in the main UI.

**Comment by TWiStErRob** [comment]
@firasdib so all non-desktop devices (phone, tablet, small-screen laptops)? I would think this is part of responsive design, that the information available on large full screen is in some way also available on smaller screens. Mobile has enough space for putting `REGULAR EXPRESSION (PCRE)` to the title, when the sidebar is collapsed.
