### ISSUE TITLE
Quick Reference typo: case mismatch

### ISSUE THREAD

**Issue by BoiloAlex** [firasdib/Regex101#920]
![image](https://user-images.githubusercontent.com/2906988/31201716-962827b2-a957-11e7-9fa6-439da769decb.png)

Quick Reference &rarr; Common Tokens &rarr; A character in the range: a-z or **A-Z**
in code true, on page &rarr; A character in the range: a-z or **a-z**
on maybe need
```
._15gkk {
       /* text-transform:  #lowercase;*/
}
```

**Comment by working-name** [comment]
`.listItem`, most likely in `app/js/components/ListMenu/ListItem.css`
