### ISSUE TITLE
POSIX character classes unsupported in java but used by the code generator

### ISSUE THREAD

**Issue by Flood2d** [firasdib/Regex101#921]
For example if generating the java code example for the following regex `[[:alpha:]]*;` we get a code that doesn't work

```java
import java.util.regex.Matcher;
import java.util.regex.Pattern;

final String regex = "[[:alpha:]]*;"; //It compiles, but doesn't work as expected
final String string = "test;";

final Pattern pattern = Pattern.compile(regex);
final Matcher matcher = pattern.matcher(string);

while (matcher.find()) {
    System.out.println("Full match: " + matcher.group(0));
    for (int i = 1; i <= matcher.groupCount(); i++) {
        System.out.println("Group " + i + ": " + matcher.group(i));
    }
}

```

**Comment by Doqnach** [comment]
The code generator does nothing more than put the supplied regex into a code template, even if the regex itself is wrong (or even generates errors). It does not validate the regex for you.
A JAVA Flavour is currently not supported yet.1

**Comment by Zarthus** [comment]
Will be fixed automatically when/if a Java flavour comes to fruition.
