### ISSUE TITLE
is there a way to link to the highest revision of a 'project'?

### ISSUE THREAD

**Issue by xaxxon** [firasdib/Regex101#924]
for example:  

https://regex101.com/r/fz8g7j

I want to put the link somewhere that will always point to the newest version, but it seems the link without the version always goes to the oldest instead.  I don't want to hard code a version because as I make changes, that will no longer be the newest version.

Love the site, thank you for your work!

**Comment by Doqnach** [comment]
related to #843

**Comment by firasdib** [comment]
Duplicate of #843
