### ISSUE TITLE
Juniper AS-Path Flavor

### ISSUE THREAD

**Issue by ipv6freely** [firasdib/Regex101#926]
Would it be possible to add a flavor for testing Juniper AS-path regular expressions? They're a bit different in that they aren't character-by-character, but instead they are AS-number by AS-number. Here's a URL that explains with some examples.

[https://www.juniper.net/documentation/en_US/junos/topics/usage-guidelines/policy-configuring-as-path-regular-expressions-to-use-as-routing-policy-match-conditions.html ](https://www.juniper.net/documentation/en_US/junos/topics/usage-guidelines/policy-configuring-as-path-regular-expressions-to-use-as-routing-policy-match-conditions.html )

**Comment by firasdib** [comment]
I think the use case for this is so slim, its not worth it. Correct me if I'm wrong!

**Comment by ipv6freely** [comment]
I disagree, but it’s your code so that’s your call.

**Comment by firasdib** [comment]
@ipv6freely Elaborate plz.
