### ISSUE TITLE
Start of string token [^] not working as it should

### ISSUE THREAD

**Issue by JoeBigToe** [firasdib/Regex101#927]
A simple test where I am trying to catch variable assignments, except where those are commented:

**Regex filter**: ^([a-zA-Z]*)\s=

Code to be filtered:
```
' Zerosie total errors and warnings
' gtotalerrors = 0
gtotalerrors = 0
gtotalwarnings = 0
```

The applied filter gives no matches while it should give:
```
gtotalerrors
gtotalwarnings
```

**Comment by TWiStErRob** [comment]
I think you're missing the multiline flag. `^` matches the beginning of the input, you need `/m` to make it match beginning of line.

**Comment by JoeBigToe** [comment]
That's right, `\m` flag is what I was missing. Thanks!
