### ISSUE TITLE
Changes that you made may not be saved popup

### ISSUE THREAD

**Issue by simonmurdock** [firasdib/Regex101#929]
I often encounter this popup when navigating normally around the site:
![image](https://user-images.githubusercontent.com/5403478/31813033-d0168b72-b57c-11e7-92b3-7299e97db28c.png)

Even though I have reloaded the page and have no regex in-progress, I see it in these scenarios:
- In My Expressions, clicking one to load it triggers this popup
- When signing in via GitHub the redirect away triggers this popup

**Comment by firasdib** [comment]
I’m aware of this but unfortunately I don’t have any time to fix it. Maybe in a few weeks. 

Thanks for bringing it to my attention.
