### ISSUE TITLE
Is Regex101 an open source project?

### ISSUE THREAD

**Issue by vaibhav6451956** [firasdib/Regex101#930]
If this is an open source project, can you please provide the link to the repo?

**Comment by Doqnach** [comment]
It is not an open source project. See #806.

**Comment by firasdib** [comment]
Not right now. It might be open sourced in the future.

**Comment by connorshea** [comment]
I'd love to see it be made open source ❤️

**Comment by DMW007** [comment]
Great idea. I'd also donate if it's open source.
