### ISSUE TITLE
Java Pattern Compile Error - Unclosed group

### ISSUE THREAD

**Issue by josebarreiro90** [firasdib/Regex101#932]
Hi,

The regular expression: 

`(\w+)\[((?:\[[^\][]*]|[^\]])+?)\]`

is converted in code java to:

`final String regex = "(\\w+)\\[((?:\\[[^\\][]*]|[^\\]])+?)\\]";`

Then, when compile:

`final Pattern pattern = Pattern.compile(regex);`

And compilation fails with error:

Unclosed group near index 32
`(\w+)\[((?:\[[^\][]*]|[^\]])+?)]`

Thanks,
José Barreiro

**Comment by Doqnach** [comment]
The code generator just takes your regex string and puts it in a code template. It does not check if the regex is valid.

I think you need to escape the `[^\][]*]` more to: `[^\]\[\]*]`, depending on what you want to do. JAVA does not automatically take those `[]` inside the character class as literals it seems, something PCRE does do.

Please provide us with an example link from regex101 if you want more insights, or join us on irc.freenode.org #regex

**Comment by josebarreiro90** [comment]
Thanks for quick reply.

Yes, it was my mistake.

Invalid:
`(\w+)\[((?:\[[^\][]*]|[^\]])+?)\]`

Valid:
`(\w+)\[((?:\[[^\]\[]*\]|[^\]])+?)\]`

Success:
`pattern = Pattern.compile("(\\w+)\\[((?:\\[[^\\]\\[]*\\]|[^\\]])+?)\\]");`

Thanks,
José Barreiro
