### ISSUE TITLE
Allow subpatterns to have a name with a length greater than 32 characters.

### ISSUE THREAD

**Issue by XplittR** [firasdib/Regex101#933]
Regex101.com with the pcre/php flavor works great for matching regex in the .NET flavor, but I have encountered 2 issues:

- Uniqueness of subpattern names: This is easily solved by enabling the "Jchanged" flag.

- Length of subpattern names:
When entering a subpattern where the name is exceeding 32 characters, I get the following error: "A named subpattern may not have a name which length exceeds 32 characters". 

.NET regex supports longer group-names, so when using regex101.com for quick testing, I have to manually truncate some of the group-names to fit within your 32-character limitation.

Suggested solution: Increase the name-length limitation, or add a flag to ignore the 32-character limitation.

**Comment by firasdib** [comment]
Afaik the 32 character limit is a limit within the engine and nothing I can change.
