### ISSUE TITLE
n-to-m repetitions range with n omitted

### ISSUE THREAD

**Issue by CecilWard** [firasdib/Regex101#934]
The regex ^a{,3}$ doesn't seem to match anything I can find. Not the null string, not various numbers of a's.

Should this regex be reported as an error?

**Comment by firasdib** [comment]
This is not valid in PCRE. Try it in Python and it'll work as expected.

https://regex101.com/r/UqWtT5/1

vs

https://regex101.com/r/UqWtT5/2

**Comment by CecilWard** [comment]
Q. should this be _reported_ by the UI as badness if PCRE mode is selected? (I believe there are dialect/flavour-specific error notifications?)

**Comment by firasdib** [comment]
@CecilWard I don't think so. Its a valid regex. The syntax highlight and explanation clearly describes the token.

**Comment by CecilWard** [comment]
Sincere apologies for being stupid - I was not understanding. I had explanations turned off, and I didn't notice that the {,3} was just black text on a white background. You would not say it's a 'pattern error" in pcre mode? (I defer to your expertise.) The description in PCRE mode is that it matches against the literal text "{,3}", which I found surprising, as it would imply that { is sometimes not a special character. But what do I know.

many many thanks for a superb tool! I find it quite simply invaluable

**Comment by firasdib** [comment]
No need to apologise my friend.

You are correct in that `{` is not always a special character in PCRE. It only ever is if its a valid quantifier, such as `{3}`, `{3,}` or {3,5}`.
