### ISSUE TITLE
Donations - paypal - on ipad pro

### ISSUE THREAD

**Issue by CecilWard** [firasdib/Regex101#935]
When I try to make a donation on my ipad (ipad pro 12") it redirects me to an _iphone_ paypal page that is utterly hideous and very ugly and difficult to use, as it is a crazy single-column layout for a phone but stretched out horizontally, massively - ui for the incredible hulk. I realise this is paypal's stupidity. Is there any way of working together to get it fixed somehow and simply get rid of the the brain-damaged "mobile" phone browser-sniffing that is presumably the problem? (The devs need to simply write css that takes proper advantage of whatever the true screen size actually is (ie really really large) rather than starting off with insane assumptions which don't work and then perverting the unsuitable layout according to the actual values discovered way too late. )

**Comment by firasdib** [comment]
Not much I can do here I'm afraid, this is all paypal being paypal 😢
