### ISSUE TITLE
\s in pcre flavor

### ISSUE THREAD

**Issue by Biblos0** [firasdib/Regex101#936]
See https://regex101.com/r/LMxaTv/1

The character between a and b is a no-break space.

In python flavor, the string is correctly selected.

In pcre flavor, it's not.

Why ?

**Comment by firasdib** [comment]
`\s` matches `[\r\n\t\f\v ]` explicitly and only without the `u` flag

**Comment by Biblos0** [comment]
Ah, OK. Thank you for your answer.
