### ISSUE TITLE
Sometimes, escaped string is what you need

### ISSUE THREAD

**Issue by KillyMXI** [firasdib/Regex101#937]
I found this closed issue: #392
But if I have a JS/TS system that stores regexes as strings, I feel uneasy using Java code generator - what if I introduce some hard to find bug relying on wrong tool?

Also, I see this as a feature separated from testing boilerplate generation. I'd like it to be a preview/copy feature somewhere on the main page.
Or, as a minimal passable solution, for languages that may need it, add escaped string as a comment into generated code at least.

**Comment by Doqnach** [comment]
Why are you using the Java code generator for JavaScript/TypeScript? What is wrong with using the Javascript code generator? Or am I understanding your suggestion wrong.

**Comment by KillyMXI** [comment]
@Doqnach JavaScript code generator produces native JavaScript RegExp (the same as written in the editor page).
But I need a string that will be stored and then used to reconstruct the RegExp in the runtime with `new RegExp(regexString, flagsString)`.

**Comment by firasdib** [comment]
@KillyMXI Why?

**Comment by KillyMXI** [comment]
Example: Electron-based app stores include/exclude and some other patterns as regex strings in json file.
Many vscode extensions do store include/exclude patterns like this, and there are some internals there using json with regexes for other needs.

**Comment by firasdib** [comment]
I see. Well there is no reason for you to actually use this if you're coding javascript, so the code generated by the site is the best you can use (for javascript). If you really need escaped strings, you could try copying the Java flavors regex output.

**Comment by KillyMXI** [comment]
That's really really sad to hear that you don't see my point.

Committing to big repository and trying to not to cause issues for a lot of people is the reason why I want to have a right tool to do escaping and avoid:
* mistakes from manual escaping;
* mistakes from difference between languages. JavaScript is not Java. Even though regex syntax mostly the same in simple cases, I have to be always cautious not to run into issues in more complex cases.

I can't change the big system I just contributing small things to. And it is really fine the way it is.
Your denial to support full-fledged language feature just because you can't agree there is a use for it is what upsets me most.

**Comment by firasdib** [comment]
@KillyMXI The code generator does not manipulate your regex besides escaping stuff properly. So the java regex, if developed in the js flavor, will work fine in JS.

I'm not denying you anything, you're asking me add another entry which uses `new RegExp()` instead of the regex literals, which I don't agree with. I don't think you should use the constructor unless you have a very good reason, especially since the regex literals are easier to read, to work with and (used to?) offer a performance boost.

**Comment by KillyMXI** [comment]
I explained my reason. I think it's good enough.
You can't pass regex literals around in json.

And now I think I should be concerned about quality of generated Java code instead...

**Comment by firasdib** [comment]
@vivekKodira That is a valid case. I could add the "valid" regexp syntax as a comment in  the generated code?

**Comment by vivekKodira** [comment]
This would be perfect. Thank you @firasdib
