### ISSUE TITLE
Match highlighting highlights LTR instead of RTL for RTL languages

### ISSUE THREAD

**Issue by sudheesh001** [firasdib/Regex101#939]
Hey,

I've been trying to match Arabic text that lies in between Arabic numerals. However, while the regex `[(\[\u0660-\u0669](.*?)[\u0660-\u0669]` solves the issue. The blue highlight seems to be incorrectly highlighting the number too. 

Link to Regex 101: https://regex101.com/r/4vLdOo/4

### What I see
![arabicregex](https://user-images.githubusercontent.com/4545925/33057689-23394684-ceb2-11e7-8588-3438abe0c4e6.PNG)

### What I expect
![arabicregex](https://user-images.githubusercontent.com/4545925/33057734-4e790488-ceb2-11e7-80b0-4665ce7a70e9.PNG)

**Comment by firasdib** [comment]
Dup of https://github.com/firasdib/Regex101/issues/764
