### ISSUE TITLE
Code Generator named-group bug

### ISSUE THREAD

**Issue by c-reiter** [firasdib/Regex101#940]
I found the perfect Python regex for extracting Snapchat usernames from a string on a Github project, tried it on Regex101 and it worked perfectly.

I then wanted to generate the Javascript code from it, as my project is running on nodejs.

The original Python regex is:
```
r'(?:(?:👻\W*)?(?:(?:(?:snap(?:chat)?\b)(?:.me)?)|(?:sc\b))|(?:👻))(?:\W)*(?P<username>(?:[a-z][\w\.-]{1,13}[a-z0-9])\b)(?:.?👻)?'
```

the generator converted javascript code is:
```
/(?:(?:👻\W*)?(?:(?:(?:snap(?:chat)?\b)(?:.me)?)|(?:sc\b))|(?:👻))(?:\W)*(?P<username>(?:[a-z][\w\.-]{1,13}[a-z0-9])\b)(?:.?👻)?/g
```

the generated javascript doesn't work because of the "?P<username>" which indicates a named group, javascript regex doesn't have the named-group feature, so it won't run.

An example solve for this problem would be to automatically convert named groups to normal groups.

I hope i could help you :)

**Comment by firasdib** [comment]
The code generator does not re-write anything, it uses the existing regex. You'll have to remove the unsupported tokens yourself. You can switch the flavor in the UI to have it help you flag invalid tokens.
