### ISSUE TITLE
Debugger - comments and suggestions

### ISSUE THREAD

**Issue by jay-tea** [firasdib/Regex101#943]
![regex101 debugging](https://user-images.githubusercontent.com/32505088/33656793-9d47ab2a-da90-11e7-9458-6760e40e8b32.png)

1: This part failed to match, so I'd recommend colouring it something other than green (red perhaps?) to visually distinguish it.

2: Uh, plz ignore.. I changed my mind about this.

3: The highlighted portion of the regex failed to match, but the subject string highlighter seems to have jumped a step and is now pointing to the next position in the subject. These two seem to be at odds with one another. Perhaps the position in the subject where the failure occurred would be more suitable to indicate.

4: Suggestion: it would be much neater to have a default view where steps 1 to 3 (which all represent successful partial matches) are consolidated into one step. So, for each attempt at a new matching point, there would be one step showing how far the regex got before failure, then a second step showing where it failed and highlighting the part of the regex it failed on.

In fact, you can create different views with different levels of detail:

"Not so detailed": One step and one position. Show only the consolidated step at the single position where the greatest part of the regex was matched. This is sort of like what I was talking about on IRC. It is likely that this consolidated step is the one the user would be most concerned with, since it will likely reveal which part of the regex needs to be tweaked in order to successfully match the desired subject (if they are constructing the regex in that manner).

"Fairly detailed": One step and many positions. This is what I described above, ie. show a single consolidated step (and failure step) for each new position in the subject where the regex is attempted.

"Detailed": What you have now, with many steps for each matching position.

The "Not so detailed" view would be particularly useful and it's definitely something you may want to consider displaying automatically (or make it very obvious and easy to show) when a regex fails to match a subject string.

**Comment by Doqnach** [comment]
Agreed on point 4, that would be a nice view to have.

Just for clarification: right now every step in the debugger is an actual step of the engine, including backtracking etc. So it does show you a good view of the processing of the regex by the engine. If steps were to be consolidated, maybe it needs an indicator of Step Y-Z so it's still clear how many steps it actually took?

**Comment by jay-tea** [comment]
Great ideas!

**Comment by Ouims** [comment]
Note that in the past the debugger was much weirder to look at, it was improved greatly in that regard, although I agree that still, sometimes a step hold too many informations, I have asked for improvement in that regard but the basic reply is that it's tricky to handle!

**Comment by firasdib** [comment]
The debugger has received a facelift and been changed quite a bit. Poke me on IRC and we can play with it. I'll close this, and we can open new issues for the new debugger.
