### ISSUE TITLE
Remember delimiter

### ISSUE THREAD

**Issue by quixrick** [firasdib/Regex101#944]
Can you please remember which delimeter we prefer in the settings, similar to how you have:

```
Default flavor | pcre || 
Select the flavor you want to use when the site loads.  Note: a saved entries' flavor overwrites this.
```

Obviously, flavors like Javascript won't support different delimiters, but you can just say that if the language doesn't support it, a forward slash will be used.

Thanks!

**Comment by Zarthus** [comment]
For the meantime, you can bookmark something like this:

https://regex101.com/?delimiter=@

**Comment by JMichaelTX** [comment]
@Zarthus , what other parameters can we set in the URL?

**Comment by Zarthus** [comment]
https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url @JMichaelTX

**Comment by firasdib** [comment]
I think @Zarthus solution is fine.
