### ISSUE TITLE
highlight of match/capture is glitchy at init time

### ISSUE THREAD

**Issue by Ouims** [firasdib/Regex101#946]
When I initialize this link : https://regex101.com/r/5XSeTu/1/ the highlight of match/capture is incorrect, resulting in https://www.dropbox.com/s/h39j267itnerwlw/re.png?dl=0 for me

I'm using chrome Version 62.0.3202.94 64bits

**Comment by Doqnach** [comment]
Same here. After I remove the ')' at the end and put it back the highlight is correct.

Opera 49.0.2725.39 (Chrome/62.0.3202.89)

**Comment by Ouims** [comment]
Lindrian commented that is is a problem with codemirror, for me clicking somewhere fix it, so I asked if a fake redraw would be a good workaround and he'll look into it

**Comment by firasdib** [comment]
This is caused by line wrapping. I have not found a solution yet.

**Comment by firasdib** [comment]
Turns out I fixed it.
