### ISSUE TITLE
backticks not escaped in golang generated code

### ISSUE THREAD

**Issue by varunrau** [firasdib/Regex101#947]
example: https://play.golang.org/p/63Ft2Dr_npO

**Comment by firasdib** [comment]
Can you give me a link to the regex on regex101.com?

**Comment by firasdib** [comment]
I see the issue now. Its because you can't escape backticks in golang... Thats annoying.

**Comment by firasdib** [comment]
I've pushed a temporary fix for this in which you're forced to use an escaped version of backticks in golang instead. A bit more tedious but solves this issue at least.

**Comment by varunrau** [comment]
thanks for the quick turnaround!

This [comment](https://github.com/golang/go/issues/18221#issuecomment-265314494) says the 'right' way to escape them is to use a `+` operator.
