### ISSUE TITLE
How to force HTML test string to treat as plain string? HTML Styling tags disappears.

### ISSUE THREAD

**Issue by braj302019** [firasdib/Regex101#95]
HTML test string is not working properly. When I paste a string that has html with some styling then it removes the styling text. I want it to be treated as plain text.

For example:

```
<td style="font-weight:bold;">Business Information</td><td id="BusInfo" colspan="2">Some Company<br /><br />Business Phone Number: (111) 111-1111<br /><br />111 Some STREET<br />Some City, AA 11111<br /></td>
```

**Comment by nhahtdh** [comment]
Probably a dup of https://github.com/firasdib/Regex101/issues/135
