### ISSUE TITLE
Save default flags

### ISSUE THREAD

**Issue by stealer0517** [firasdib/Regex101#950]
So normally you can save which flavor of regex you want to use, but you cannot save the flags you want.
With the regex I do I need the flags G I S. G is on by default, but I and S must be toggled on each time.

A work around I've done is to save "." , and load that save each time, but having that as an actual feature would be much more preferred.

**Comment by JMichaelTX** [comment]
I totally agree.  Not having the unicode flag always set has caused me problems numerous times.

**Comment by Zarthus** [comment]
Workaround:

You can bookmark `https://regex101.com/?flags=gmi` ([wiki page](https://github.com/firasdib/Regex101/wiki/FAQ#how-to-prefill-the-fields-on-the-interface-via-url))

**Comment by firasdib** [comment]
I think @Zarthus solution is fine.
