### ISSUE TITLE
When to support localization language switching?

### ISSUE THREAD

**Issue by Zjmainstay** [firasdib/Regex101#951]
Why regex101 don't support localization language switching?
![localization language switching](https://user-images.githubusercontent.com/3349634/34929170-425b6daa-f9fd-11e7-85c9-3837909fc3d9.jpg)

**Comment by Doqnach** [comment]
Because the translations are not done yet.

Any specific language you are looking for?

**Comment by Zjmainstay** [comment]
No, I just feel a little confused when I see the settings.Maybe I can help to do some Chinese translations.

**Comment by firasdib** [comment]
I just haven't had time to finish it and there hasn't been much need for it, yet.

**Comment by zonky2** [comment]
you can add the project to transifex and anybody can help to translate

**Comment by firasdib** [comment]
This has been added.

**Comment by shrft** [comment]
@firasdib 
Hi. could you please add Japanese language support?
I want to share this site with my Japanese colleagues.
I can help you translate if needed.

**Comment by working-name** [comment]
@shrft Hi there, please start a new Japanese translation [here](https://r101.cf/projects/regex101/www/) Anyone can help translate 👍 
@zonky2 we have a weblate instance set up for translations. Please [give it a try](https://r101.cf/projects/regex101/www/), let me know.

**Comment by shrft** [comment]
@firasdib
hi. thanks. I started working on the translation.
Your site is the best regex check tool and I love it! thank you.

I found it a bit difficult to translate when I cannot tell what goes in to {NUMBER} like below.
{1} — Matches exactly {2} {3} {4}
Is there any way to see example sentence for it?

**Comment by firasdib** [comment]
These cases are a bit difficult to translate. However, 99% of the time, the placeholders will be referencing a regex token. 

Eg. 

{3} - Matches exactly 3 times

{1} is the regex token ”{3}”
{2} is ”3”
{3} is ”times”




Vänliga hälsningar / Best regards,

Firas Dib

**Comment by shrft** [comment]
@firasdib 
Ok. thanks.

**Comment by shrft** [comment]
@firasdib 
In this case "times" cannot be translated. Are these cases going to be fixed in the future?

**Comment by firasdib** [comment]
There will be another translation entry for just ”times”.


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by shrft** [comment]
ok. thanks.
