### ISSUE TITLE
Allow collapsing sub-expressions for readability (aka "named patterns", "macros", "sub-pattern library")

### ISSUE THREAD

**Issue by oberlies** [firasdib/Regex101#952]
The syntax highlighting in the regular expression bar is awesome – but in particular if patterns are repetitive, you still get lost. Consider the following pattern ([source](https://stackoverflow.com/a/48265370/1523648))

> `String\.format\(\s*"([^%]*)%s([^%]*)%s([^%]*)",\s*([^,()]*),\s*([^,()]*)\)`

By design, this pattern contains sub-pattern that occur over and over again:
* `([^%]*)` – for "text"
* `\s*([^,()]*)` – for an "argument"

It would be great if the editor would have a second line above the regular expressions line in which I can use the abstract terms instead of the patterns above. So for the example above, this line would show

> ` String\.format\(\s*"`‹text›`%s`‹text›`%s`‹text›`",\s*`‹arg›`,\s*`‹arg›`\)`

These sub-patterns (or macros, named patterns, or whatever you like to call them) would need to be defined by the user. Plus there might be a library of useful sub-patterns (like ‹_› for `\s*`)

**Comment by firasdib** [comment]
There is no such feature, but you can use the free-spacing mode to make it more breatheable.  See https://regex101.com/r/Uj4Dee/1

**Comment by oberlies** [comment]
Awesome! This is very useful!

**Comment by Doqnach** [comment]
With PCRE you can also use the DEFINE construct to emulate this.

https://www.regular-expressions.info/subroutine.html#define
