### ISSUE TITLE
FR: add MySQL as flavor language

### ISSUE THREAD

**Issue by zonky2** [firasdib/Regex101#954]
in MySQL we have different restrictions e.g. `\s` as `[[:blank:]]` look at https://dev.mysql.com/doc/refman/5.7/en/regexp.html#regexp-operators and it´s difficult to test e.g. at phpMyAdmin

**Comment by Doqnach** [comment]
MySQL does POSIX, which is supported under the PCRE flavour on the webiste, except for a few specific things like `[=character_class=]`, `[.characters.]` (both of which I've personally never seen used) and `[[:<:]], [[:>:]]` (but that last one you can do with `\b` and replace it when converting to a MySQL query).

Being aware of the differences makes you able to write a regex on the website and converting it to MySQL compatible.

**Comment by firasdib** [comment]
MySQL would be very far down the list im afraid. Using PCRE as @Doqnach mentioned is your best bet.
