### ISSUE TITLE
bug on regex

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [firasdib/Regex101#955]
as you can see on the screenshot below, there is an error.
It should match 5 times. I guess it is not getting the 'xl' .
Look, in this sample, I want to match:
-ab
-bc
-xb
-bl
-ll

What is wrong?

![regex](https://user-images.githubusercontent.com/4364432/35196959-d107b1bc-feb7-11e7-8b34-6b9ba255e6ce.png)

**Comment by firasdib** [comment]
That is incorrect. Characters are consumed and never matched twice. There is no bug here.

**Comment by ViniciusDeAndrade** [comment]
but i need to do that!
Like in this site, where it has been catched. http://www.passwordmeter.com/
Try to use my test string and you will see the _Consecutive Lowercase Letters_ being equals to 5

**Comment by Doqnach** [comment]
I expect that website will run each check individually. what makes you believe they did it with Regex and not just by looping through the string?

**Comment by firasdib** [comment]
I see no error here. Join IRC if you need help with creating a regex.
