### ISSUE TITLE
Error regular expression is too large for {0,1000}

### ISSUE THREAD

**Issue by SL-Gundam** [firasdib/Regex101#956]
Regular expression: `/^\s*(On(?:(?!^>*\s*On\b|\bwrote:).){0,1000}wrote:)$/ms`

When i run this i get: regular expression is too large - offset: 51
If i decrease the {0,1000} to {0,589} it does run without errors
PHP does not have any issues with this regular expression

Could not find any documentation about this limit on regex101

**Comment by Doqnach** [comment]
Do you have a link to an (regex101.com) example that produces this error?

**Comment by TWiStErRob** [comment]
@Doqnach just copy the regex in PHP or Python

**Comment by firasdib** [comment]
There is an internal limit for how large the expression might be. There is no way to calculate this before hand. Typically you'll never run into it, but sometimes you will. In those case there isn't anything I can do I'm afraid.

**Comment by TWiStErRob** [comment]
@SL-Gundam this may help: if you replace `{0,1000}` with `*` the problem disappears.

**Comment by SL-Gundam** [comment]
@firasdib If it isn't something that can be fixed maybe its a good thing to document it

@TWiStErRob workarounds i got. I just couldn't find any documentation about this limit so I felt it necessary to report it
