### ISSUE TITLE
Wrong definition for [:print:]

### ISSUE THREAD

**Issue by maherbo** [firasdib/Regex101#957]
The definition for `[:print:]` (unicode) is:

*`[:print:]` matches a visible character or the space character `\P{C}`*

It should read:

*`[:print:]` matches a visible character or the space character `[^\P{C}]`*

**Comment by firasdib** [comment]
`[^\P{C}]` is the same as `\pC` in that case. I'll fix this soon.

**Comment by maherbo** [comment]
I did not noticed the capital 'P'; My mistake.

**Comment by maherbo** [comment]
I just checked the definition of `[:print:]` and `\PC` would still be wrong for PCRE, as Cf should be included according to the [documentation](http://www.pcre.org/pcre.txt):
___
`[:graph:]` This matches characters that have glyphs that mark  the  page
                 when printed. In Unicode property terms, it matches all char-
                 acters with the L, M, N, P, S, or Cf properties, except for:

U+061C           Arabic Letter Mark
U+180E           Mongolian Vowel Separator
 U+2066 - U+2069  Various "isolate"s

`[:print:]` This matches the same  characters  as  [:graph:]  plus  space
                 characters  that  are  not controls, that is, characters with
                 the Zs property.
___

It seems to be the same definition for [PCRE2](http://www.pcre.org/current/doc/html/pcre2pattern.html):
___
`[:graph:]` This matches characters that have glyphs that mark the page when printed. In Unicode property terms, it matches all characters with the L, M, N, P, S, or Cf properties, except for:

  U+061C           Arabic Letter Mark
  U+180E           Mongolian Vowel Separator
  U+2066 - U+2069  Various "isolate"s

`[:print:]` This matches the same characters as [:graph:] plus space characters that are not controls, that is, characters with the Zs property.
___

**Comment by firasdib** [comment]
Fixed
