### ISSUE TITLE
Balancing groups

### ISSUE THREAD

**Issue by hell-racer** [firasdib/Regex101#959]
I try to test an example of balancing groups like ^(?'open'o)+(?'-open'c)+(?(open)(?!))$ (from https://www.regular-expressions.info/balancing.html) and it doesn't work:

(? Incomplete group structure
) Incomplete group structure
+ The preceding token is not quantifiable

Is this intended? E.g. non of the flavors allow this? Thanks!

**Comment by Doqnach** [comment]
Yes. Balancing groups is not supported by PCRE, only by .NET. Regex101 currently does not support a .NET flavour.

You could use recursion instead?

**Comment by hell-racer** [comment]
I can try, thank you. Let's close the issue?
