### ISSUE TITLE
Statistics/performance in match information

### ISSUE THREAD

**Issue by rasqual** [firasdib/Regex101#960]
Love the app. 

Under match information, stats would be nice. Maybe a tab that lists each pattern, and the number of hits next to it. Cut & pasteable. 

Keep up the good work.

**Comment by firasdib** [comment]
You'll have to elaborate on this. What specifically do you mean?

**Comment by rasqual** [comment]
Trying to figure out, myself, what I meant.   ;-)

I think what I was after is this: the tool is not only useful for cobbling regex together, but for evaluating the data to which such regexps are applied in practice. 

Thus, I might paste a thousand strings (so we're talking about multi-line evaluation) into the test string box. The match information tells me what's going on, but can't help me assess which parts of the regex are statistically more often matched than others. If each substring of the regex that matches any number of test string rows were presented (in a part of the UI dedicated to this, I'd think) with a tally beside it, that would be valuable information about the fit of the regex to the data. If particular elements of the regex were never used, present that as well with a "0" by it for its tally.

Think of it as an extension of the utility of this wonderful app into the realm of evaluating the appropriateness of given regex strings to the data against which they are applied. 

I'm thinking like a database geek with this, I know.

**Comment by firasdib** [comment]
I'm not sure I see any value in this, to be honest.

**Comment by rasqual** [comment]
Very valuable for analysis of huge sets of strings against which we apply
regular expressions in the world of web filtering in education. We're
legally required to filter, but keeping it narrow is the challenge.

No probs.

- S

**Comment by firasdib** [comment]
Use the debugger for that and find out which parts are being used in what way. I'm not convinced, but I'm open to being convinced.

**Comment by rasqual** [comment]
The debugger doesn't give a count, though, of how many matches there are
in, say, a 1000-line multi-line match. It's knowing which parts of the
regex are relevant to the strings we're processing that's at issue. The
debugger basically shows everything it does (which is obviously awesome),
but no per-regexsubstring tally. That is, "how many of the line items
pasted in does this part of the regex match? Are there any regex substrings
that end up doing no duty at all with any of our strings?"

That kind of thing.

Can't do bulk analysis by scrolling through a debugger that gives me great
detail about what it matches in each line. I'm imagining an additional tab
(like a second tab in the debugger area) that shows all the elements of the
regex, with a tally beside them. So that's aggregating how many matches
there are for *all* multi-line data, with just a tally given for each regex
substring.

LOL

No biggie; I realize that something that would be *really* handy for our
needs doesn't mean it'd be worth your while to code for it.

Love your app, thanks for the work put in.

- S
