### ISSUE TITLE
Kotlin Template

### ISSUE THREAD

**Issue by elijah-z142** [firasdib/Regex101#961]
-

**Comment by firasdib** [comment]
What about the flags? Replacement? Global/nom global?

**Comment by elijah-z142** [comment]
@firasdib If there were flags, they would be added as the second argument to Pattern.Compile, same syntax as with Java for the flag. Same flag names, as it is the exact same JVM.

The "|" (bitwise inclusive) operator seems to convert to "or".

When I convert "Pattern.compile("a", Pattern.CANON_EQ | Pattern.CASE_INSENSITIVE);" in IntelliJ, it results in "Pattern.compile("aaa", Pattern.MULTILINE or Pattern.CANON_EQ)"

Not sure each of the items that you listed there (ex. replacement) or how to find them on regex101.

**Comment by elijah-z142** [comment]
I'm not familiar with Kotlin's regex classes, though they seem very similar to Java's. If you can make a template I'd agree. Otherwise, this makes a nice 1st version of Kotlin template.

**Comment by elijah-z142** [comment]
It seems the primary difference is how the flags should be constructed, besides the package name. So I think we just need to describe a function for generating the optional flags object.
