### ISSUE TITLE
not giving the correct result`

### ISSUE THREAD

**Issue by pankajasegaonkar1** [firasdib/Regex101#962]
`(?>(fi?rst)_?(na?me?)|f_?name)(?!\w*ID)` this regex will find the first name in lower case as well as in upper case also but in regex.com it is showing no result found for the first_name,fir,first

**Comment by Doqnach** [comment]
Could you please provide a regex101.com link to an example, showing your expected output and the actual output?

**Comment by GCDeveloper** [comment]
I have an issue with regex101.com which is not giving the correct result also.
It says there is no match, but in code (even from the code generator) it does find a match. Here is a link:
https://regex101.com/r/CQugD5/1

**Comment by TWiStErRob** [comment]
@GCDeveloper there are new line characters in the regex, that's matched raw. If you go to PHP and enable eXtended mode it'll match. It'll also match if you remove the line breaks from the regex.

@firasdib the newline characters seem to be handled differently in `/foo/` JS construct

**Comment by GCDeveloper** [comment]
There are no newlines in the string.

**Comment by GCDeveloper** [comment]
Thank you, I didn't notice.

**Comment by TWiStErRob** [comment]
@GCDeveloper I noticed it so easily because "Show whitespace" in settings is checked.
