### ISSUE TITLE
Python 3 `re.sub()` Code Generated Wrong

### ISSUE THREAD

**Issue by cjbarth** [firasdib/Regex101#963]
When generating code, the `$0` notation is invalid in Python for identifying numbered capture groups in replacement. In a test I did, the following code was generated, which does not act as expected:

	import re

	regex = r" *([^A-z]+) *"
	test_str = "Test30:19"
	subst = " $1 "  # should be " \\1 "
	result = re.sub(regex, subst, test_str, 0)

	if result:
	    print (result)  # Test $1 ; should be Test 30:19 as is shown in at regex101.com

**Comment by Doqnach** [comment]
Code generation just puts your regex in a template. It does not check for the validity of the regex.

Make sure to write your regex correctly. There is no validation also on the syntax of the back-references in the substitution right now, based on the chosen flavour.

**Comment by cjbarth** [comment]
Thanks for your reply, it is good to know how it works on the back end. I would add that it is very deceiving to have code work in the browser, but not be generated correctly. I would flag this as a bug in the web UI then.

**Comment by firasdib** [comment]
See https://github.com/firasdib/Regex101/issues/648
