### ISSUE TITLE
Referencing user's saved regexes inside tester

### ISSUE THREAD

**Issue by spadazz** [firasdib/Regex101#964]
Hello everybody,
I just had a chat asking about this and I was re-routed here for some following.
The question is, in my (python) programs I use a sort of "macro" regexes, that are built dynamically at runtime before compiling, something like this:
'date: (?P\<date\>$DMY)'
where the 'date: ' part is just a context match inside the document and $DMY is the real regex.
I know that right now it's not possible, but I think that it would be nice and useful having the capability to reference in the tested expression the name of a saved regex.

Thanks for your help and for the great tester you've built !
Spadazz

**Comment by firasdib** [comment]
This is a bit too complex to be worth implementing, and I don't think very many people would find this useful.

You have `(?(DEFINE)...)` in PCRE which serves a similar purpose, although not identical.

Thanks for the suggestion though.
