### ISSUE TITLE
Substitution token $&  does not work properly

### ISSUE THREAD

**Issue by uicosp** [firasdib/Regex101#965]
Below is the code generated by Regex101
```
const regex = /\d{1,3}(?=(\d{3})+$)/g;
const str = `1234567890`;
const subst = `$&,`;

// The substituted value will be contained in the result variable
const result = str.replace(regex, subst);

console.log('Substitution result: ', result);
```
copy the code in browser console, it works well and output:
`Substitution result:  1,234,567,890`

However, in the Regex101 web page, the output is error:
`$&,$&,$&,890`

## Reproduce the problem
input box value in Regex101:
#### REGULAR EXPRESSION
`\d{1,3}(?=(\d{3})+$)` REGEX FLAGS `g`
#### TEST STRING
`1234567890`
#### SUBSTITUTION
`$&,`
#### Result output
`$&,$&,$&,890`

**Comment by TWiStErRob** [comment]
The substitution part of the site is "flavorless", and the only format supported is documented by Substitution in Quick Reference. `\0` is what you can use for `$&`

**Comment by TWiStErRob** [comment]
See also #648, #867, #907

**Comment by firasdib** [comment]
Duplicate of https://github.com/firasdib/Regex101/issues/648

The issue will be tracked there.
