### ISSUE TITLE
Powershell Code-Generator

### ISSUE THREAD

**Issue by Albager** [firasdib/Regex101#968]
It would be really great to have a **Code-Generator for Windows Powershell's Select-String** -pattern command. It costs a lot of time to fiddle out how to write/escape my regexes working with regex101.com to make them work with powershell... 

See eg https://regex101.com/r/sXVAsi/2 -> It works with the website, but not with Powershell...

**Comment by Doqnach** [comment]
And what would have to be modified to make it work?

**Comment by Albager** [comment]
Yeah, that's the question... I didn't figure out yet..

**Comment by Albager** [comment]
Here's another example: https://regex101.com/r/LS7gPJ/1
This regex works just fine with regex101.com.

To make it work in Powershell, i had to write
 `dir -Recurse | Select-String -pattern "\<table\sclass\=""table\stable-striped\""\>.*
?\<\/table\>"` to filter out the desired tables from a bunch of .html-files.

**Comment by working-name** [comment]
@Albager I'd have a look at this [list of special characters](http://www.neolisk.com/techblog/powershell-specialcharactersandtokens) in PowerShell and go from there.

**Comment by Albager** [comment]
@working-name Nice. Anyways, I can't find a solution... Think I tried it a hundred times now. Do you have any other tipps?

**Comment by working-name** [comment]
@Albager have you tried reducing your regex to the basic `<TABLE\scellSpacing=1` and move on from there? Every time you add something new check if it fails. If it does then you found your culprit.

**Comment by Albager** [comment]
I'm digging into this step-by-step debugging right now... 👍

**Comment by working-name** [comment]
@Albager sounds good. 

Another viable option for your particular HTML extraction needs seems to be [Powershell's ability to use XmlDocument class](https://henry416.wordpress.com/2012/10/05/process-xml-using-dom-model-in-powershell/) which is generally recommended instead of using regex on HTML.

**Comment by Albager** [comment]
**Any ideas how to write the regex for powershell?** It seems to be _not_ an escaping problem and eg with grep for windows in cmd it works perfectly... I need that regex to work to match the tables, then parse these tables like eg https://community.spiceworks.com/topic/543224-downloading-an-http-table-to-an-array

**Comment by firasdib** [comment]
Closing due to lack of interest. Reopen if you feel otherwise.

(There is a guide in the wiki for writing code gens)

**Comment by Liturgist** [comment]
PowerShell has good [System.Xml] handling. See also https://stackoverflow.com/a/1732454/447901
