### ISSUE TITLE
`^` is not working in positive lookahead match

### ISSUE THREAD

**Issue by nallwhy** [firasdib/Regex101#969]
`^(?=.*[^a-z]).+$`

`A` <- should match
`a` <- shouldn't match, but matches

**Comment by firasdib** [comment]
It doesn't match for me. Give me a permalink.

**Comment by firasdib** [comment]
https://regex101.com/r/VFbfY5/1 works fine

**Comment by Doqnach** [comment]
maybe the 'i' flag was on by mistake?
