### ISSUE TITLE
python - re.S flag missing (dot matches all)

### ISSUE THREAD

**Issue by mdamien** [firasdib/Regex101#970]
Just a small note, would be nice to have the `re.S` flag

EDIT: To note, there's already a solution, it's to start the regex with `(?s)`, but this flag might be useful even for beginners

**Comment by Doqnach** [comment]
@mdamien in which flavour? Because there is the 's' flag in all the current supported flavours on the website. Click on the flag next to the regex to see all available flags for the selected flavours.

**Comment by mdamien** [comment]
My bad, I was mistaken with the "single line" help text, but you're right, it's already there.
