### ISSUE TITLE
.* fails to match

### ISSUE THREAD

**Issue by apb1963** [firasdib/Regex101#971]
I couldn't get (.well\-known\/acme\-challenge\/])(.*) to match my test string.

Long story short, I tried .* as my regex as a test of your page and it still failed to match.  Partial page copied below:

/
.*
/
g
.*
matches any character (except for line terminators)
* Quantifier — Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)
↵ matches the character ↵ literally (case sensitive)
Global pattern flags
g modifier: global. All matches (don't return after first match)
**Your regular expression does not match the subject string.**

**Comment by Doqnach** [comment]
Please create an example that shows this behaviour on regex101.com, click save and link it here. Then we can take a look at it.
I already see some points where your syntax might be off, explaining the issue.

**Comment by firasdib** [comment]
No response, closing.
