### ISSUE TITLE
Wrong match

### ISSUE THREAD

**Issue by Tanguerjho** [firasdib/Regex101#972]
I use /^([A-Z]+)/g  on string 
"0ABC
ABC a123 as
C DEF blubb
Cde Tghe 
This is a sentence.
Assumption is that this would be a hit.
and here is no match
THIS IS A FULL MATCH.
AZYX
AXYZ"
and it says it does not get a match which is wrong, as it should match the second to sixth line as well as the last three.

**Comment by simonlindberg** [comment]
Hint: you need to tell it to be multi-line, with the m flag.
Otherwise the ^ means start of string.

**Comment by firasdib** [comment]
No response, closing.
