### ISSUE TITLE
Javascript non capturing groups are not working in firefox

### ISSUE THREAD

**Issue by derrohrbach** [firasdib/Regex101#973]
In Version 59.0.1 (64-Bit) of Firefox the non capturing groups are not working for javascript regex.

Try this regex: **^folder\.item:([\s\S]*?)(?::(\d+))?$**

It should match this: **folder.item:test123:123**

works in regextester: [https://www.regextester.com/?fam=102891](https://www.regextester.com/?fam=102891)

**Comment by working-name** [comment]
Confirmed for `FF 59.0.1 (64-bit)`, and `Safari 11.0.3 (13604.5.6)`. None of the `(?...)` type constructs are recognized, the `?` is only treated as a quantifier.

Chrome, Chromium-derivatives are fine.

**Comment by firasdib** [comment]
Sorry. Regression from yesterdays update. Its fixed now.
