### ISSUE TITLE
Recurring donations don't work

### ISSUE THREAD

**Issue by modo-lv** [firasdib/Regex101#974]
Have tried this several times over the past year. Even though there is a "make recurring" checkbox on the PayPal donation page, the actual donation is always one-time and no recurrence ever happens.

**Comment by firasdib** [comment]
Thats odd. There are some users which send me $1/month, and it's very punctual, so I don't think they're doing it manually.

**Comment by modo-lv** [comment]
I just made another $2 donation with the "recurring" checkbox checked, but my "pre-approved payments" list in PayPal hasn't changed. How recently were the working monthly payments started? Maybe it used to work but something got broken at some point?

**Comment by firasdib** [comment]
Probably a good while ago. I don't know, but if anything broke, it wasn't on my end. Has to be paypal.
