### ISSUE TITLE
Feature to translate between regex flavors

### ISSUE THREAD

**Issue by Bartvds** [firasdib/Regex101#975]
It would be cool if there was a way to convert regular expressions between flavors. 

Like if you have a Python regex you could turn it into a JavaScript version. It could be bets-effort with a message if in-compatible features are used etc.

**Comment by Zarthus** [comment]
@firasdib Unless you have a magical wizardry way of implementing this, am I wrong to say that this is better off rejected due to the impossible amount of effort required?

**Comment by firasdib** [comment]
As @Zarthus said, this would not be worth the effort I reckon.

It's a huge undertaking, as it requires mapping between all flavors and conversion of the regex/substitution strings etc.
