### ISSUE TITLE
(Minor) tag removal bug

### ISSUE THREAD

**Issue by eToThePi-i** [firasdib/Regex101#981]
When a tag is removed from a saved regex in "My history", it is removed from the list of tags, even if other regex have that tag. The tag list resets when the page loads, so it's not a permanent change, but it should probably check if other regex have that tag before removing it from the tag list.

**Comment by firasdib** [comment]
I've solved this by simply not removing the tag until you refresh. This is because I can't know if any other entry has this tag, and it does not seem worth it to query the server to find out.
