### ISSUE TITLE
Match multiple repeated characters as fixed quantifier

### ISSUE THREAD

**Issue by eToThePi-i** [firasdib/Regex101#983]
Currently the regex engine processes repeated characters individually. When I type `\{\{`, the regex engine could optimize processing to `\{{2}`. This applies to most repeated characters, though in most cases it makes sense to use the fixed quantifier instead of repeating characters.

I prefer to use `\{\{` when typing the regex because it's less characters and doesn't have the adjacent `{`'s

**Comment by OnlineCop** [comment]
Remember that regex101 uses the official PCRE/Javascript/Golang implementations of regular expressions. It should work the same on this site as it would work in your own private PCRE- (or other) compliant tool or engine. Meaning that if a user types in `\{\{`, then we will need to have the same optimizations as the pcre.txt file indicates should happen. If we didn't, then we may have bugs OR optimizations that work exclusively on our site but that don't work the same on your own computer. That would be more of a headache for you, the end user.

Now, if you're asking for some kind of "optimize this regex" tool that may combine `\{\{` into `\{{2}` for you, that would be different. In that case, giving suggestions on how to speed up some of these searches would not change how optimizations worked on the site "under the hood."

**Comment by eToThePi-i** [comment]
The reason why I suggest this as a change is because it doesn't change the behavior of the engine at all, i.e. all of the same things match and don't match, it just changes the _efficiency_ of the engine. This change would not affect compliance with the specific regex engines.

Based on your suggested change to the tool, [I've made a regex](https://regex101.com/r/fk8pSG/1/) for personal that performs the above enhancement to a valid regex with pairs of escaped curly brackets (meta regexing).

**Comment by firasdib** [comment]
There is no point to do this. The engine will do these kinds of optimizations better - write what is most readable to you.
