### ISSUE TITLE
When text is in the add tag field, warn the user before the tag is saved.

### ISSUE THREAD

**Issue by eToThePi-i** [firasdib/Regex101#984]
I'm referring to the field labelled "ADD TAG" with the grey suggestion text "Any word can be used as a tag". Often, I click the save account entry button without adding the tag, and the text in the field is lost. It would be nice if the save button asked something like "Do you want to add the tag "<words in tag field>" to this entry?

Alternatively, it could automatically add the text, but the above solution seems preferable.

**Comment by firasdib** [comment]
While I agree this case might be annoying, I don't have any good way of dealing with this sort of behavior currently. 

You can always hit enter to save the tag.
