### ISSUE TITLE
[Bug] When saving a new entry, it should be different from the previous entry.

### ISSUE THREAD

**Issue by eToThePi-i** [firasdib/Regex101#986]
It doesn't seem to make sense to allow users to save an identical entry as a new separate version. At the very least, it should warn before saving if the versions are identical.

Example links showing identical versions can be iterated: [1](https://regex101.com/r/ImodEs/1/ ), [2](https://regex101.com/r/ImodEs/2/).

**Comment by firasdib** [comment]
There is a simple check on the client to only enable the save button if any changes have been made. If these are then reverted, you can still save. It's a bit too much to check on the server when saving and I don't think its worth the work.

**Comment by eToThePi-i** [comment]
@firasdib Couldn't you just have the default formatting saved in the client, and then compare to that default formatting when saving? Then if it's different, it could save and update the default formatting, but otherwise it would not allow saving a new version. That wouldn't require any additional server requests.

**Comment by firasdib** [comment]
@eToThePi-i There are a lot of things to consider, such as the unit tests and what not. I don't think its worth performing this type of check.

**Comment by Doqnach** [comment]
is there a state that is saved in the local-storage? worth saving some hash of a last saved state?

Comparing server-side is too costly for such a small annoyance imo.

**Comment by firasdib** [comment]
@Doqnach No, there is nothing like that atm. Thing is, if the user is working with large quantities of text, hashing it will be slow and might ruin the experience.
