### ISSUE TITLE
Both \d and \d+ are described as "matches a digit (equal to [0-9])"

### ISSUE THREAD

**Issue by PjotrB** [firasdib/Regex101#990]
Regex `\d` is described as: "`\d` matches a digit (equal to `[0-9]`)" - good.

Regex `\d+` is described as: "`\d+` matches a digit (equal to `[0-9]`)" - not good?
Then a line follows that actually describes the `+`.

IMO the `+` should not be included in the `\d+` description. `\d+` is obviously not equivalent to `[0-9]`, it is equivalent to `[0-9]+`. Better to even omit the `+` there because `+` already has it own descriptive line.

**Comment by firasdib** [comment]
I see where this could go both ways.

@TWiStErRob @Zarthus @nhahtdh @working-name thoughts?

**Comment by Zarthus** [comment]
with indentation to the plus, most people should understand the + is a quantifier.

In the end the description is not correct, and I don't think we should keep it as-is. Can we write it as "`\d+` matches a digit (equal to `[0-9]`) (quantified 1 or more times)"

**Comment by TWiStErRob** [comment]
Note: This applies to all explanations, not just `\d`.
consider `(?:[a-z]+\d+\w*)+`, in this case all the primitives (`[]`, `\d` and `\w`) are explained as is then a child node is added to explain the quantifier:
```
/(?:[a-z]+\d+\w*)+/gm
  Non-capturing group (?:[a-z]+\d+\w*)+
    + Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
    Match a single character present in the list below [a-z]+
      + Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
      a-z a single character in the range between a (index 97) and z (index 122) (case sensitive)
    \d+ matches a digit (equal to [0-9])
      + Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
    \w* matches any word character (equal to [a-zA-Z0-9_])
      * Quantifier — Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)
  Global pattern flags
```
I think you were trying to save space, by collapsing the explanation and the complex combined regex onto one line, causing confusion in OP. IMO it shouldn't be trying to save on space and just simply say:
```
/(?:[a-z]+\d+\w*)+/gm
  Non-capturing group (?:[a-z]+\d+\w*)+
    + Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
    Quantified character group [a-z]+
      + Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
      [a-z] a single character in the range between a (index 97) and z (index 122) (case sensitive)
    Quantified shorthand \d+
      + Quantifier — Matches between one and unlimited times, as many times as possible, giving back as needed (greedy)
      \d matches a digit (equal to [0-9])
    Quantified shorthand \w* 
      * Quantifier — Matches between zero and unlimited times, as many times as possible, giving back as needed (greedy)
      \w matches any word character (equal to [a-zA-Z0-9_])
  Global pattern flags
```
This is more scalable/easier than putting/duplicating the quantifier explanation on the `\d+` line , or trying to reword each explanation based on quantifier. It also allows for actually explaining what things are (e.g. `\letter`=shorthand, `[a-z]`=character group) similar to "non-capturing group", which is not done in the current impl.

**Comment by firasdib** [comment]
It seems you want a more natural explanation of the regex. As it stands currently, tokens are split explained in their own subtree. Because the `+` "belongs" to the `\d` they are kept together, and then explained in the subtree.

In the current implementation I tried to explain it in natural text, but also keep the regex lingo and tokens so people learn what to call things.

**Comment by working-name** [comment]
I honestly never gave that any thought, it didn't jump at me. Now that it was highlighted, sure, I see the point, but at the same time I don't find it incorrect to break up explanations based on quantifiers while keeping the unit intact at the top. If the explanation were out of context, without the quantifiers explained below, then yes, that would be incorrect.

In fact, by keeping explanations binary (unit+quantifier) I think we'll help reduce confusion in the minds of people who do not yet have a grasp on quantifiers and how those affect the previous token.

**Comment by firasdib** [comment]
@working-name I agree. Thus, I think we should keep the current behavior.
