### ISSUE TITLE
Feature request: Unit test assert - number of matches is.., match N is ...

### ISSUE THREAD

**Issue by georgir** [firasdib/Regex101#991]
Unit tests should be able to assert number of matches for /g regexes.

Also they should be able to check that i.e. the second match is/contains/starts with something. 
(maybe the "target" options for "match N" should only appear if another assert for the same input exists, giving a value for the upper bound of N; or just hardcode it for 1..5; or add some UI to be able to pick it in another way instead of a dropdown)

**Comment by firasdib** [comment]
A global expression is the same as applying the expression over the same string multiple times, with different start positions. Its better to create a test case for each nth match, than to try target specific iterations.
