### ISSUE TITLE
negative look behind not matching anything

### ISSUE THREAD

**Issue by ConorSheehan1** [firasdib/Regex101#994]
I noticed an issue on regex101 for some negative look behind expressions.  
For example ```^(?!\/).*$``` (which should match any line not starting with "/")

Here is an example:
Sublime behaves as I'd expect
![sublime_negative_look_behind](https://user-images.githubusercontent.com/16896053/38740897-87476856-3f30-11e8-8103-51f8fbf97791.PNG)

Regex101 doesn't match anything. I'm not sure why.
https://regex101.com/r/zBspb8/2
![regex101_negative_look_behind](https://user-images.githubusercontent.com/16896053/38740919-8bdd21d0-3f30-11e8-8e51-9aa14f573e36.PNG)

**Comment by firasdib** [comment]
You need to use the `m` flag. Perhaps this should be enabled by default.

**Comment by ConorSheehan1** [comment]
Yep that was it, and that was insanely fast! Thanks for your help

**Comment by Doqnach** [comment]
Also not you were using a look-ahead, and not a look-behind.
