### ISSUE TITLE
This is a valid regex and yet it does not match any strings...

### ISSUE THREAD

**Issue by ynnelson** [firasdib/Regex101#995]
/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z0-9]{6,}$/g should work but it only works when you do 
/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z0-9]{6,}$/m. Not sure why? What am I missing? It worked just fine on https://www.regextester.com/.

Anyways, not sure if its a bug or if I am misunderstanding something. Just thought I'd point it out.
Thanks

**Comment by Doqnach** [comment]
flag 'm' means 'multi-line'. `^` and `$` match the beginning and end of a **string**. Without the 'm' flag this means the beginning and end of the entire test string. If you do provide flag 'm' this means the beginning and end of each line instead.

**Comment by firasdib** [comment]
@Doqnach Lets enable it by default and see what happens
