### ISSUE TITLE
add from quickreference to regular expresion

### ISSUE THREAD

**Issue by peterhammer** [firasdib/Regex101#996]
such a useful tool!

adding directly from the quick reference would make the site like a regex builder. maybe add a "plus sign" to the left of the description, and when clicking on it just paste it to the end of the text in the regular expression input box.

Hope you like it!

Best regards,
    Federico.

**Comment by firasdib** [comment]
I don't think this is that useful. Do people build their regexes like this?

The ones that require additional info would be too complicated to add in any viable manner imo.

**Comment by peterhammer** [comment]
Thanks Firasdib, maybe you are right and people dont build like that, but maybe that is because there is no such tool. In my case, building from a "tool shed" would be quite useful, but maybe that is just me.
Regarding the variables: i dont think new variables are needed, just add the regex reference to the regex being built where the cursor is.
Thanks again!
Best regards, Federico.

**Comment by Ouims** [comment]
I actually like this suggestion, there's nothing to complete, just paste the generic string being used on the quick ref to the current cursor position in the regex field, (at the end if not the active control)

\n \t \r \d \0 -> paste the corresponding token \n \r etc

[abc] -> paste "[abc]"
[^abc] -> paste "[^abc]"
\Px -> paste "\Px"
\Q...\E -> paste "\Q...\E"
\k'name' -> paste "\k'name'" 

on so on.


However there are some edge cases, the modifiers are listed in there and clicking on a modifier to toggle that modifier, i'm not sure it's that great but why not.

**Comment by Doqnach** [comment]
often with codemirror and similar libraries, if you have selected text it is prefixed&suffixed with stuff. so would the requirement also be that if you have \b and text selected it would prefixed and suffixed with \b? same for \Q...\E? And for other tokens, would it be replaced? or prefixed/suffixed by default?

**Comment by peterhammer** [comment]
Hello Doqnach, I would say that adding from the tool shed should plain paste where the cursor is. If you have selected text, it should replace it, like a paste would do in any text editor. I think Ouims got it quite right what I meant. Just add the example to the regex builder box where the cursor is. Best regards, Federico.

**Comment by TWiStErRob** [comment]
I like the idea of those wrapping the selected text, because that's their job. Adding `\b` around or quoting text would be as tedious as right now if it had no special handling @Doqnach describes.

Repetitions are another interesting one, do you create a (non-capturing) group to repeat, or just repeat the last regex part?

**Comment by Ouims** [comment]
You're missing the point a bit.

When you are new to a programming language, you go check the syntax of functions and you often copy a string from a website into your editor that looks like this:
"regexmatch(input,expression,capture,options..)"

and then you slowly build from that.

This is the point, sometimes you don't remember the syntax or don't know the token you need in regex, you would just search in the quickred list and then click on it to at least get it saved somewhere, if it's \d, sure easy to remember but for someone not as confirmed as you, \Q...\E might be harder for a noob to remember.

The point isn't to quickly build an expression for confirmed users, although that's another good idea maybe, maybe both can be added with a default to the original suggestion, and if shift is held while clicking, then something that dynamically create the regex from the selected text could be tried.

**Comment by peterhammer** [comment]
Thanks Ouims, I think there are a lot of different way to perform programming, also that there are plenty of greys between noob and confirmed users.

IMHO, this would help mostly the grays. 
- Noobs will have to read more, but this will help speed up the trying part probably.
- Confirmed users go pretty much straight to what they need, but still being able to build from the tool shed can make their work easier.
- And then all the greys in between, which will get, probably, most out of it: we don't know all expressions, we don't build as fast, we make syntax or grammar mistakes. So bulding from a shed will be most useful.

But again, all are valid points of views.

Best regards,
    Federico.

**Comment by firasdib** [comment]
The issue I see with this is that the "click" is already occupied with viewing the quickref details of an item. This means the user must first click to open the details, then again click to add the token from there.

I think thats too many clicks to make this a useful feature.
