### ISSUE TITLE
On convert to java this is not working

### ISSUE THREAD

**Issue by ram-reddy** [firasdib/Regex101#998]
Actual :- `^[\p{L}][\p{L}\p{M}\p{Zs}\x2d\x{2010}\x{2013}\x{2014}\x26\x27\x2c\x2e]{0,49}$`
Java Generated Regular expression : 
```
final String regex = "^[\\p\\{L\\}][\\p\\{L\\}\\p\\{M\\}\\p\\{Zs\\}\\x2d\\x{2010}\\x{2013}\\x{2014}\\x26\\x27\\x2c\\x2e]{0,49}$";
```

Getting error on pasting to Editor itself.

**Comment by firasdib** [comment]
Fixed

Thanks
