### ISSUE TITLE
Regex double quotes

### ISSUE THREAD

**Issue by Devolick** [firasdib/Regex101#999]
Value: `S"dima ""' "R"Y'0'"`
Regex: `([A-Z]{1}|[0-9]+)"((?:""|[^"])*)"`
Result regex101 is: `S"dima ""' "`
In my C# Application .NET Core result work fine, result is: `S"dima ""' "`, `R"Y'0'"`

**Comment by TWiStErRob** [comment]
If I interpreted you OP correctly, you're getting two results in .NET.
On the website you need the global flag: https://regex101.com/r/fWCZVV/1 (try turning off `g` on the right of the pattern to see the difference.)
